### ISSUE TITLE
V2 API (project API Endpoint): 500 response code is returned when valid user with any role access the endpoint

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1000]
## Background
Trigger https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/project with valid user having any role. Observed that 500 Internal Server Error is returned
![image](https://user-images.githubusercontent.com/60865903/80469530-4ec9ca80-895e-11ea-9007-b0288f79df01.png)

**_Tried with below users_**
![image](https://user-images.githubusercontent.com/60865903/80469492-42457200-895e-11ea-8b05-c5692a85a730.png)

![image](https://user-images.githubusercontent.com/60865903/80469594-64d78b00-895e-11ea-8715-aca905adda72.png)

**Comment by rinkeshbhutwala** [comment]
@nirupamav @dealako I have verified this ticket and I got the expected status code 403 instead of 500 which is correct.
For any LF roles I have discuss with Prabodh so he told me **Domain should be linuxfoundation** for assigning any LF-Roles.

**Comment by nirupamav** [comment]
@rinkeshbhutwala
Observed that lf-program-manager has access
But lf-finance does not have access
Could you please let me know which roles have access to this endpoint, so that I can test accordingly

**Comment by rinkeshbhutwala** [comment]
@nirupamav I have checked in acs-cli below roles who have access to this endpoint.

1. project-manager
2. community-program-manager
3. LF-program-manager
4. LF-executive
5. LF-admin
6. LF-legal
7. LF-operations

**Comment by nirupamav** [comment]
Tested with below roles and observed expected response code is returned
| Role  | Response Code |
| ------------- | ------------- |
| User  | 403 |
| CLA Manager (Proj|Org Scope)  | 403 |
| CLA Manager Designee (Proj|Org Scope)  | 403 |
| CLA Signatory (Proj Scope)  | 403 |
| Community-program-manager (Proj Scope)  | 200 |
| Company-admin (Org Scope)  | 403 |
| Company-admin (Org Scope)  | 403 |
| Company-alternate-owner (Org Scope)  | 403 |
| Company-owner (Org Scope)  | 403 |
| Contact (Org Scope)  | 403 |
| Contributor (Proj Scope)  | 403 |
| Donor (Proj Scope)  | 403 |
| Human-Resources (Org Scope)  | 403 |
| Mentee (Proj Scope)  | 403 |
| Mentor (Proj Scope)  | 403 |
| Project-Manager (Proj Scope)  | 200 |
| lf-admin (Proj Scope)  | 200 |
| lf-events (Proj Scope)  | 403 |
| lf-executive (Proj Scope)  | 200 |
| lf-finance (Proj Scope)  | 403 |
| lf-legal (Proj Scope)  | 200 |
| lf-program-manager (Proj Scope)  | 200 |
| lf-staff (Org Scope)  | 403 |
| lf-operations (Admin Scope)  | 200 |
| lf-training (Proj Scope)  | 403 |
