### ISSUE TITLE
V2 API (project/{{projectid}} API Endpoint): 500 response code is returned for valid user and 403 is returned for unauthorized user when projectId is not provided

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1001]
## Background
Trigger https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/project/ with unauthorized user. Observed that 403 is returned. If valid projectid is provided 401 is returned for the same user. response code returned should be consistent
**user: nirupamavmentee2 (only user role)**
![image](https://user-images.githubusercontent.com/60865903/80471267-d0225c80-8960-11ea-97eb-17b6def627c5.png)

Trigger https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/project/ with authorized user. Observed 500 is returned
**user: nirupamavmentee2 (lf-operations,project-manager and user role)**
![image](https://user-images.githubusercontent.com/60865903/80471666-576fd000-8961-11ea-9e4e-cb80154415f2.png)

**Comment by dealako** [comment]
@rinkeshbhutwala I am assigning this task to you.

**Comment by nirupamav** [comment]
**Issue2 is still reproducible. Trigger https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/project/ with authorized user. Observed 500 is returned**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/cd425cc1-da04-47de-8c0b-e7240a5e6f24)

**As per current behavior 403 is returned for unauthorized user and Issue1 is fixed**

**Comment by dealako** [comment]
If pageSize is included it works fine - if pageSize missing it returns 500 error.

**Comment by nirupamav** [comment]
**Verified that Issue2 is fixed**

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a6c7c010-57fd-49e3-ae7a-ee5f4cc5bdba)
