### ISSUE TITLE
V2 API (projects API Endpoint): Able to perform http actions when user role scope does not have the external project

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1003]
## Background
**Trigger the api for EasyCLA project and externalProject with valid user but user role scope does not have the external project. Observed that data is fetched. Since the user does not have access to project 401 should be returned**
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/project/{{projectId}} [GET, POST,PUT]
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/project/external/{{external projectId}} [GET]
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/project/name/{{project name}} [GET]
![image](https://user-images.githubusercontent.com/60865903/80479751-22697a80-896d-11ea-8e80-c8506c04aa8b.png)

![image](https://user-images.githubusercontent.com/60865903/80479902-63fa2580-896d-11ea-9336-71515f2b2855.png)

![image](https://user-images.githubusercontent.com/60865903/80479934-707e7e00-896d-11ea-9c05-97e47e319a32.png)

**User: nirupamavmentee1 with super-admin role**
![image](https://user-images.githubusercontent.com/60865903/80479964-7bd1a980-896d-11ea-9754-9ce56886ba93.png)

**User: nirupamav with project-manager role**
![image](https://user-images.githubusercontent.com/60865903/80480094-ae7ba200-896d-11ea-8463-6723548e6672.png)

**Comment by dealako** [comment]
@rinkeshbhutwala please review and diagnose/resolve. Seek assistance with a test scenario from @nirupamav

**Comment by rinkeshbhutwala** [comment]
@nirupamav @dealako I have tested the above workflow looks like it's checking for cla-group with permission of the user doesn't have project scope which we have mention in URL or request it's give me 403 which is as expected.

**Comment by nirupamav** [comment]
For endpoint https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/project/name/{{project name}} when user does not have access to project 404 is returned instead of 403. However when tried with SFID for same project, 403 is returned
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/937179e9-ebd8-48c5-a4f9-c69872d1864a)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/670a034a-2c76-4233-ac5a-dd271c52006f)

**Comment by rinkeshbhutwala** [comment]
@nirupamav I have verified this ticket regarding the GET call for projectName so we are checking first that cla-group is present in a cla-stage-projects table if it is not there so we return 404 and if it is present then we check the ProjectSFID and check that the user has access to that project if not then we are returning 403.

@dealako Let me know this flow is expected or did we change that?

**Comment by vinod-kadam** [comment]
As updated by @wanyaland  the behavior mentioned by @rinkeshbhutwala  is the right behavior. So, closing this ticket.
