### ISSUE TITLE
V2 API (project/external/{{externalprojectid}} API Endpoint): 200 response is returned when invalid external id is provided

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1004]
## Background
Trigger https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/project/external/djfgkf with valid user
Observed that 200 is returned instead of 400. When https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/project/external/ is triggered 400 is returned. Response Code should be 400 when invalid data is provided
**Failed Scenario**
![image](https://user-images.githubusercontent.com/60865903/80481181-99077780-896f-11ea-9a2f-8f2c290b5730.png)

**Working Scenario**
![image](https://user-images.githubusercontent.com/60865903/80481264-bc322700-896f-11ea-90ee-6657b058e115.png)

**Comment by dealako** [comment]
@rinkeshbhutwala more API response code cleanup.

**Comment by nirupamav** [comment]
**Verified that the issue is fixed**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/97e6a75d-83e2-488d-8d60-fa9b13a825a1)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/d3dcc73a-6c5f-4abd-ba56-b976d06569b3)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/42bc3345-e001-474f-9ec8-db4e59091940)
