### ISSUE TITLE
Contributor Console Individual CLA flow step 1, 2 & 3 in Table 1 of PRD

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#1006]
Here is the link to [wireframe ](https://wireframepro.mockflow.com/view/app-easycla#/page/Dab111f6a971bc1cd42c819a1770bc817)for the contributor console of EasyCLA.
![image](https://user-images.githubusercontent.com/57362064/80505730-57100e80-893a-11ea-9e8d-c6257e78ffd2.png)
![image](https://user-images.githubusercontent.com/57362064/80506209-e2899f80-893a-11ea-89e6-dbda5d52f7f7.png)
![image](https://user-images.githubusercontent.com/57362064/80506248-efa68e80-893a-11ea-8cdd-d1babe875a48.png)

This is Table 1 in the PRD below
https://confluence.linuxfoundation.org/display/PROD/Contributor+Console+for+EasyCLA+V2

##Acceptance Criteria
- [x] Design Changes Required ?--> Not Applicable (N/A)   
- [ ] Unit Testing Complete 
    - [x] Unit Testing complete for backend API
    - [x] Unit Testing complete for UI
- [ ] Functional Testing Complete 
    - [ ] Functional Testing complete for backend API
    - [x] Functional Testing complete for UI
- [ ] Integration Testing Complete 
    - [x] Integration Testing complete for backend API and UI
    - [x] Integration Testing complete end to end dev deployment
- [ ] Documentation Updated 
- [ ] Any Open Sev. 1, Sev 2 bug(s)

**Comment by nirupamav** [comment]
Tested Step1 and logged below issues
https://github.com/communitybridge/easycla-contributor-console/issues/4
https://github.com/communitybridge/easycla-contributor-console/issues/5
https://github.com/communitybridge/easycla-contributor-console/issues/6
https://github.com/communitybridge/easycla-contributor-console/issues/7
https://github.com/communitybridge/easycla-contributor-console/issues/8
https://github.com/communitybridge/easycla-contributor-console/issues/9

**Comment by amolsontakke3576** [comment]
@prasannamahajan and @wanyaland I have integrated below endpoint to fetch project name can you please confirm is it use `organization service` internally ?

URL : <base-path>/v2/project/<projectId>

**Comment by amolsontakke3576** [comment]
@prasannamahajan and @wanyaland Also we required endpoint to validate user. Currently, I am using below endpoint just confirm we are on right track.

Endpoint : https://api.dev.lfcla.com/v2/user/userId

**Comment by prasannamahajan** [comment]
we don't use organization-service for any /v2 api.

**Comment by dealako** [comment]
Related to #1196 - https://app.zenhub.com/workspaces/lfx-easyclav2-5ed619832c71a855a76ef404/issues/communitybridge/easycla/1196

**Comment by nirupamav** [comment]
Tested only Step1 and logged bug #1293
Step2 and Step3 are tested in #1196

**Comment by nirupamav** [comment]
@pranab-bajpai 
Testing completed for Step1. Could you please review the test plan and let men know if I missed any test cases
https://confluence.linuxfoundation.org/display/PROD/V2+-+Contributor+Console+Homepage+Test+Plan

Step2 and Step3 will be tested in #1196
