### ISSUE TITLE
Contributor Console Individual CLA flow when there is no signed CLA but company is there. Step 3

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#1011]
Here is the link to [wireframe ](https://wireframepro.mockflow.com/view/app-easycla#/page/Dab111f6a971bc1cd42c819a1770bc817)for the contributor console of EasyCLA.

![image](https://user-images.githubusercontent.com/57362064/80521381-8c275b80-8950-11ea-9e5a-70e4c0d9e42f.png)

Step 3 in Table 3 in the PRD below
https://confluence.linuxfoundation.org/display/PROD/Contributor+Console+for+EasyCLA+V2

##Acceptance Criteria
- [ ] Design Changes Required ?--> Not Applicable (N/A)   
- [ ] Unit Testing Complete 
    - [ ] Unit Testing complete for backend API
    - [ ] Unit Testing complete for UI
- [ ] Functional Testing Complete 
    - [ ] Functional Testing complete for backend API
    - [ ] Functional Testing complete for UI
- [ ] Integration Testing Complete 
    - [ ] Integration Testing complete for backend API and UI
    - [ ] Integration Testing complete end to end dev deployment
- [ ] Documentation Updated 
- [ ] Any Open Sev. 1, Sev 2 bug(s)

**Comment by nirupamav** [comment]
Verified that this feature is working as expected
