### ISSUE TITLE
Project Console -  Not able to update Project(CLA Group) configuration

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1023]
## Background
1. Launch Project Console
2. Login as Project Manager
3. Click on Foundation
4. Click configuration icon to edit project
5. Uncheck/check the checkbox for any field
6. Click Save
7. Observed project already exists message is displayed
**Before Update**
![image](https://user-images.githubusercontent.com/60865903/80564391-4ed3d400-8a0b-11ea-8f81-519cc4a66400.png)

**After Update**
![image](https://user-images.githubusercontent.com/60865903/80564415-60b57700-8a0b-11ea-9035-49d3cf57a067.png)

**Comment by dealako** [comment]
@WillsonHG @pranab-bajpai let's discuss the ramifications of changing the ICLA + CCLA (and ICLA+CCLA combo) on this page. Should we allow this?  If so, let's discuss what this means to the existing signatures in the DB.

**Comment by dealako** [comment]
On edit, only allow updating the name and description.

**Comment by nirupamav** [comment]
Verified that user can only update Project Name and Description and cannot edit CLA type
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/5fdaea63-3cb0-4dec-8c64-2e8a96d23e5a)
