### ISSUE TITLE
Project Console - Page is not auto refreshed when template is generated and then Back to Project is clicked

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1024]
## Background
1. Launch Project Console
2. Login as Project Manager
3. Click Foundation
4. Create CLA Group with only ICLA enabled
5. ClLick SELECT TEMPLATE
6. Click APACHE STYLE
7. Enter all details
8. Click GENERATE PDFS
9. Click on Back To Project
10. Observed that page is not auto refreshed and generated template is not displayed
![image](https://user-images.githubusercontent.com/60865903/80566270-37e3b080-8a10-11ea-9e5b-d2d153257090.png)

**After refreshing the page**
![image](https://user-images.githubusercontent.com/60865903/80566298-4a5dea00-8a10-11ea-8df3-05513216aeda.png)

**Comment by dealako** [comment]
Another simple one - please add a page refresh or... more smartly, reload the CLA group list API call.

**Comment by nirupamav** [comment]
**Issue is still reproducible when followed the steps in the ticket**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/deb7bcb5-2a2f-42d0-8dee-d58a64b7813d)

**After refreshing the page manually I am able to see the generated document**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/492e89c4-a6ce-4e9d-a97f-2d6075e5bb81)

**Comment by dealako** [comment]
The old console is deprecated and removed.
