### ISSUE TITLE
Project Console - Date and Time format is different for Corporate and Individual templates

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1025]
## Background
1. Launch Project Console
2. Login as Project Manager
3. Click on Foundation
4. Create a CLA group with both ICLA and CCLA enabled
5. Generate templates for the CLA Group
6. Observed that date and time format are different
![image](https://user-images.githubusercontent.com/60865903/80568097-ff45d600-8a13-11ea-88b1-df293bc7d9b9.png)

**Comment by dealako** [comment]
Low priority - focus on v2 UI design.

**Comment by dealako** [comment]
The old v1 console is deprecated and removed.
