### ISSUE TITLE
Corporate Console - Updated project name is not displayed in Manage Approved List window

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1026]
## Background
1. Launch Project Console
2. Login as Project Manager
3. Click on Foundation
4. Update the project name of a project that has Pending Whitelists for a company
5. Launch Corporate Console
6. Login as CLA Manager
7. Click on Company
8. Observed the updated project name is displayed 
![image](https://user-images.githubusercontent.com/60865903/80573829-5b155c80-8a1e-11ea-90a7-71fd9c5aba33.png)
9. Click on MANAGE APPROVED LIST
10. Observed that the updated project name is not displayed and still previous project name is displayed
![image](https://user-images.githubusercontent.com/60865903/80573952-8ef08200-8a1e-11ea-92be-799af227f5d1.png)

**Comment by dealako** [comment]
@nirupamav please confirm this works.  Demo'd to team earlier this week.

**Comment by nirupamav** [comment]
Testing blocked due to bug #1626

**Comment by nirupamav** [comment]
Verified that the issue is fixed. Also tested in others pages of Corporate Console, Project Console and Contributor console and issue is fixed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/1d020e7c-83d9-4b1d-a23c-5375fdf64c21)
