### ISSUE TITLE
V2 - Sometimes the metrics almbda function errors out ot takes lot of time to execute

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1028]
## Background
Trigger the lambda function to fetch latest metrics **data**

![image](https://user-images.githubusercontent.com/60865903/80581570-f6acca00-8a2a-11ea-9702-244880d087a5.png)

**_Log output_**
esent"
time="2020-04-29T09:33:12Z" level=warning msg="project id=[1311c5c1-94ca-4d1c-91a6-045dcbb0f9cb] does not exist in projects table but signature [bb0aa87f-f522-467e-8738-d1ac473b7e71] for it is present"
time="2020-04-29T09:33:12Z" level=warning msg="project id=[1311c5c1-94ca-4d1c-91a6-045dcbb0f9cb] does not exist in projects table but signature [4ee09bc0-91ac-4840-9e9c-ab29afb7fd59] for it is present"
time="2020-04-29T09:33:12Z" level=warning msg="company id=[4a02d608-4617-4926-8c97-03fefdb6b975]:name=[] does not exist in companies table but ccla signature [8d199f18-0229-4bc9-8b9d-8f76323e5d9c] for it is present"
time="2020-04-29T09:33:12Z" level=warning msg="project id=[b159981f-b4d1-43fd-be4f-8ebce7258dca] does not exist in projects table but signature [8d199f18-0229-4bc9-8b9d-8f76323e5d9c] for it is present"
time="2020-04-29T09:33:12Z" level=warning msg="company id=[ee95da1b-3a3a-4233-9c89-007184bc4a21]:name=[] does not exist in companies table but ccla signature [2206143f-17d8-488d-a93b-8ed99e62efd7] for it is present"
time="2020-04-29T09:33:12Z" level=warning msg="project id=[5dad0ff3-b567-409d-8f2d-277766e72d9a] does not exist in projects table but signature [2206143f-17d8-488d-a93b-8ed99e62efd7] for it is present"
time="2020-04-29T09:33:12Z" level=warning msg="project id=[d5bcaadb-f6a2-4971-b51b-af8cfb699598] does not exist in projects table but signature [412577db-c70a-465d-b74a-e2f7e29d9305] for it is present"
time="2020-04-29T09:33:12Z" level=warning msg="project id=[62d5a0c2-749e-440c-badc-ed48e3353ba1] does not exist in projects table but signature [ab9aeac3-97f3-48ce-a25a-e6c5eb05ebf0] for it is present"
time="2020-04-29T09:33:12Z" level=warning msg="project id=[09f18c2f-d8f8-4ffe-b8ae-decda33fe2e0] does not exist in projects table but signature [77a3365b-5f54-4af7-aab6-88f2b7b3025c] for it is present"
time="2020-04-29T09:33:12Z" level=warning msg="project id=[980a69e5-739c-4ee9-9702-307b9dd032a2] does not exist in projects table but signature [fdb1ca08-f927-405b-afb6-55d6bd27ddad] for it is present"
time="2020-04-29T09:33:12Z" level=warning msg="project id=[1311c5c1-94ca-4d1c-91a6-045dcbb0f9cb] does not exist in projects table but signature [35ee3a5b-96d0-47f1-ad2f-12be38214f6a] for it is present"
time="2020-04-29T09:33:12Z" level=warning msg="project id=[1152db37-b8bb-4f40-8e14-ff6780d89b79] does not exist in projects table but signature [468f31cf-7217-4f6e-a4af-6da29b51d660] for it is present"
time="2020-04-29T09:33:12Z" level=warning msg="project id=[43c1b31f-5b0d-485f-b073-b5b7fb24f1e5] does not exist in projects table but signature [1be09398-f652-42f8-8f96-c6fc448e5609] for it is present"
time="2020-04-29T09:33:12Z" level=warning msg="project id=[1311c5c1-94ca-4d1c-91a6-045dcbb0f9cb] does not exist in projects table but signature [4dac531d-632e-4bdf-95b6-f344536682b8] for it is present"
time="2020-04-29T09:33:12Z" level=warning msg="project id=[7f30dfaa-f0aa-4bf4-90a5-cff9b990172c] does not exist in projects table but signature [7b4c2ab6-7e24-4e30-9ee3-43dffefec566] for it is present"
time="2020-04-29T09:33:12Z" level=debug msg="Calculating Repository metrics..."
time="2020-04-29T09:33:12Z" level=info msg="processing repositories table"
time="2020-04-29T09:33:12Z" level=debug msg="Calculating Gerrit metrics..."
time="2020-04-29T09:33:12Z" level=info msg="processing gerrit instances table"
time="2020-04-29T09:33:12Z" level=debug msg="Calculating CLA Manager distribution metrics..."
time="2020-04-29T09:33:12Z" level=info msg="calculate metrics took time 5.125691528s"
time="2020-04-29T09:33:12Z" level=debug msg="Completed metrics calculations"
time="2020-04-29T09:33:12Z" level=info msg="saving total count metrics"
time="2020-04-29T09:33:12Z" level=info msg="saving company_metrics"
END RequestId: 98fd588e-fe65-4857-bb4b-81a478580bd0
REPORT RequestId: 98fd588e-fe65-4857-bb4b-81a478580bd0	Duration: 60060.19 ms	Billed Duration: 60000 ms	Memory Size: 1024 MB	Max Memory Used: 100 MB	Init Duration: 357.43 ms	
2020-04-29T09:34:07.863Z 98fd588e-fe65-4857-bb4b-81a478580bd0 Task timed out after 60.06 seconds

**Comment by dealako** [comment]
Resolved. Closing issue.
