### ISSUE TITLE
V2 API -[ project endpoint] - Issues while creating Project 

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1029]
## Background
**_Observed that user is able to create project with invalid data from API_**
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/project
POST

**When empty data is provided for _projectExternalID_**
![image](https://user-images.githubusercontent.com/60865903/80586043-f7952a00-8a31-11ea-8311-c5ca03af4fac.png)

**When invalid data is provided for _projectExternalID_**
![image](https://user-images.githubusercontent.com/60865903/80586094-0ed41780-8a32-11ea-8db1-3d3e8f3dba9a.png)

**Comment by prasannamahajan** [comment]
@nirupamav  @dealako Closing this issue. Since this api is not used in v2 for creating cla-group. 
Instead we use https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/createClaGroup
