### ISSUE TITLE
Contributor Console - Gerrit - Not able to proceed with CCLA flows for existing companies as Submit button is not available

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1032]
## Background
1. Launch the Gerrit Contributor Agreement Link for Corporate
2. User is redirected to Contributor Console
3. Click on Company
4. Observed that SUBMIT button is not displayed to proceed further with CCLA flows for existing companies
![image](https://user-images.githubusercontent.com/60865903/80692520-52408b80-8aef-11ea-9ed5-d0099b2f27b6.png)

**Comment by dealako** [comment]
The old v1 console is deprecated and removed.
