### ISSUE TITLE
Contributor Console - Gerrit - Contributor Email is not displayed for selection When requesting accessing for Company that does not exist in the list

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1033]
## Background

1. Launch the Gerrit Contributor Agreement Link for Corporate
2. User is redirected to Contributor Console
3. Click on **COMPANY NOT IN LIST? CLICK HERE**
4. Click NO
5. Observed that Email of the contributor is not available to proceed further

![image](https://user-images.githubusercontent.com/60865903/80693440-a26c1d80-8af0-11ea-9efc-6b4c9f86d2d8.png)

**Comment by dealako** [comment]
@amolsontakke3576 the user's email should be in the LF login session info...

**Comment by amolsontakke3576** [comment]
I have verified and seems working fine.

![Screenshot from 2020-09-22 11-57-46.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/4b9d28c1-216a-4f79-9d85-239e4ae34e86)

**Comment by nirupamav** [comment]
Verified that issue is fixed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/ed7f58e1-1435-4d8a-b4a3-034421c3a9a5)
