### ISSUE TITLE
Project Console - Page is not auto refreshed after installing easycla app in github and clicking on Project Console

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1034]
## Background

1. Launch Project Console
2. Login as Project Manager
3. Click on Foundation
4. Click on CONNECT GITHUB ORGANIZATION
5. Enter valid github organization
6. Click CONNECT
7. Click INSTALL THE GITHUB CLA APP
8. Click OK on alert 
9. User is navigated to github in new tab
10. Sign In to github if already not signed in
11. Click on Configure/Install
12. Select the organization
13. Click Install
14. Click on the project console browser tab
15. Observed the Project Console is not auto refreshed
![image](https://user-images.githubusercontent.com/60865903/80696855-ab132280-8af5-11ea-808b-da72e290e277.png)

**Comment by nirupamav** [comment]
**_Issue is still reproducible_**

**After installing github org page was not auto refreshed**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/996bde32-840d-4bbd-9621-2a19784285d8)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/12ef113f-3ddd-4186-a881-09b64bcbd02a)

**After I manually refreshed the page**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/50d35c12-fc87-4b89-b144-aea688c4fb73)

**Comment by amolsontakke3576** [comment]
Verified and working as per expectation
 ![Screenshot from 2020-11-17 12-24-01.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/91b64df6-4a05-40f3-83e8-eaccdc08c872)

**Comment by dealako** [comment]
The old v1 console is deprecated and removed.
