### ISSUE TITLE
V2 - Response code is different for different endpoints when data is not found or when data is not provided

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1036]
## Background
**_Response Code is different for different endpoints when data is invalid_**
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/project/external/a0941000002
**GET**
![image](https://user-images.githubusercontent.com/60865903/80703130-d733a100-8aff-11ea-843a-9bb225f7ad56.png)

https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/project
**PUT**
![image](https://user-images.githubusercontent.com/60865903/80703191-f7636000-8aff-11ea-8199-d65270a0d389.png)

https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/project/e6d22047-a559-4edc-88b8-afccc0d98d4c
**GET**
![image](https://user-images.githubusercontent.com/60865903/80703236-0d712080-8b00-11ea-93bf-55abf1b3ec58.png)

https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/signatures/project/e6d22047-a
**GET**
![image](https://user-images.githubusercontent.com/60865903/80703708-e8c97880-8b00-11ea-8381-12061c4d6762.png)

**Comment by nirupamav** [comment]
**Scenario1 - Response Code when invalid projectsfid is provided. As per my understanding 404 should be returned in this scenario**
- 400 is returned https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company/0014100000Te1DWAAZ/project/a092M00001IV4PgQAB/active-cla-list
- 200 with null value for signatures field is returned https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/signatures/project/a092M00001IV4PgQLA/company/0014100000Te1DWAAZ

**Scenario2 - Response Code when invalid companysfid is provided. As per my understanding 404 should be returned in this scenario**
- 403 is returned https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company/0014100000Te1DWAAP/project/a092M00001IV4PgQAL/active-cla-list

**Scenario3 - When no projectsfid/companysfid is not provided. As per my understanding 400 should be returned in this scenario**
- 403 is returned https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company//project/a092M00001IV4PgQAL/active-cla-list
- 403 is returned https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company/0014100000Te1DWAAP/project//active-cla-list

**Comment by dealako** [comment]
@rinkeshbhutwala can you help get these updated to be consistent:

- invalid data or bad/missing parameters: HTTP 400 bad request
- no results from the query: HTTP 404 Not found

**Comment by nirupamav** [comment]
As per current behavior when there is no data we return 200 with empty list for few endpoints and 404 for few endpoints and hence closing this ticket
