### ISSUE TITLE
gRPC PR that CLA Bot is Hung On

### ISSUE THREAD

**Issue by caniszczyk** [communitybridge/easycla#1054]
PR that the CLA bot is hung up on: https://github.com/grpc/grpc/pull/22870

**Comment by WillsonHG** [comment]
confirmed same issue as #1037

**Comment by dealako** [comment]
Status update is now working with the latest release of EasyCLA. The referenced PR is still open for grpc, but EasyCLA is working fine now.  Closing the Issue as it is resolved.
