### ISSUE TITLE
Project Console: "View Companies" table error.

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#1056]
## Summary

For some projects, the "View companies" table does not load and an error can be seen in the console. This is happening with specifically with CNCF and with OpenColorIO, but not all projects have this issue.

## Background

1. Go to project.lfcla.com
1. Click on CNCF or ASWF (OpenColorIO CLA group)
1. Click on "View Companies"
1. See error

## Screenshots

![image](https://user-images.githubusercontent.com/46732999/81109565-49cdc380-8ee8-11ea-9a10-092b8d7df925.png)

https://api.lfcla.com/v3/signatures/project/d8cead54-92b7-48c5-a2c8-b1e295e8f7f1?pageSize=100&signatureType=ccla

## Environment

PROD

**Comment by amolsontakke3576** [comment]
@dealako @WillsonHG @nirupamav above issue not reproducible on Dev Environment but as per the error message in screenshot, issue is in trim function where company name may not come from API. I will write trim pipe for this hope it will solve the issue on Production.

**Comment by nirupamav** [comment]
@WillsonHG 
Could you please check this in PROD as I do not have access to PROD
I tested in DEV env for CNCF CLA Group and observed that it is working as expected without any errors
![image](https://user-images.githubusercontent.com/60865903/81930235-f2c1a000-9605-11ea-85e7-193788eeca1e.png)

**Comment by WillsonHG** [comment]
This looks to be resolved in production.
