### ISSUE TITLE
Corporate Console - Email is sent to Initial CLA Manager and REQUEST ACCESS status is displayed for the project When joined CLA Manager signs the CLA for the project

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1061]
## Background
1. Launch Corporate Console
2. Login as **_nirupamavmentee214_** 
3. Create Company RequestAccessTest 
4. Login to corporate console as **_clamanager2_** 
6. Click Get Started
7. Search and Select company RequestAccessTest
8. Click JOIN COMPANY
9. Login to corporate console as **_nirupamavclamanager101_** 
10. Click Get Started
11. Search and Select company RequestAccessTest
12. Click JOIN COMPANY
13. Login to corporate console as Initial CLA Manager **_nirupamavmentee214_**
14. Click on the Company RequestAccessTest
15. ACCEPT the Pending CLA Manager request for **_nirupamavclamanager101_** 
16, Login to corporate console as **_nirupamavclamanager101_** 
17. Click on the Company RequestAccessTest
18. Click SIGN NEW CLA
19. Search and Select project ProjMay062020
20. Click SUBMIT
21. Click YES
22. Click OPEN CLA
23. Complete the Docusign process
24. Observed that in Docusign by default  **_nirupamavmentee214_** is displayed for SIGN details but other details are related to **_nirupamavclamanager101_**. Also email is sent to only initial CLA Manager **_nirupamavmentee214_** and not to **_nirupamavclamanager101_**. 
![image](https://user-images.githubusercontent.com/60865903/81145172-6410ab80-8f93-11ea-8cfd-9d26dc365ef6.png)

![image](https://user-images.githubusercontent.com/60865903/81145548-1a749080-8f94-11ea-9803-c2453a9af6ec.png)

25. Login to corporate console as Initial CLA Manager **_nirupamavmentee214_**
26. Click on the Company RequestAccessTest
27. Observed that REQUEST ACCESS is displayed for the project for CLA Manager **_nirupamavmentee214_** who created the company/ who is the initial CLA Manager
![image](https://user-images.githubusercontent.com/60865903/81145684-60315900-8f94-11ea-9716-484f860bab51.png)

**Comment by dealako** [comment]
@amolsontakke3576 was this resolved?

**Comment by amolsontakke3576** [comment]
@dealako DocuSign part is pending regarding email.

**Comment by rinkeshbhutwala** [comment]
@nirupamav I have verified this ticket with the company name *Adidas Corporation Pune * which is created by @amolsontakke3576 and he is the initial cla-manager then I tried joined company flow as per the step mention above but seems like flow is working as expected also attached the screen-shot.

![Screenshot from 2020-09-22 12-20-51.png](https://images.zenhubusercontent.com/5f20ee93f9a45844ef8dfce5/c707db48-0c4d-4460-a04b-94274d2d7f4e)

@nirupamav  Can you provide me more details so I can debug further?

**Comment by nirupamav** [comment]
User nirupamav created the company
User v1cla1 joined the company and signed CLA for the project. As expected docusing has details of v1cla1 and v1cla is initial CLA Manager and Singatory
As expected user nirupamav as the status Request Access for the project
**v1cla1**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c1b2aadd-605f-4745-ad67-6e78ee6cc518)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/7159fac4-c13a-4a14-8d3a-c6fbe62aa6d5)

**nirupamav**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/3a22d9cb-e48a-4888-a8e8-e52f391ee78d)
