### ISSUE TITLE
Corporate Console: '-' is displayed for Pending CLA Manager Requests when there are no requests and when there are requests

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1062]
## Background
**_Issue1 - When there are no requests_**
1. Launch Corporate Console
2. Login as CLA Manager
3. Click on the Company
4. Click SIGN NEW CLA
5. Search and Select project
6. Click SUBMIT
7. Click YES
8. Click OPEN CLA
9. Complete docusign process
10, In the Signed projects table observed that **-** is displayed for Pending CLA Manager Requests when there are no pending CLA Manager requests for the project. However **0** is displayed for Pending Contributor Requests when there are no employee contribution approval requests. Behavior should be consistent
![image](https://user-images.githubusercontent.com/60865903/81146138-565c2580-8f95-11ea-9626-70b7b9f227ea.png)

**_Issue2 - When there are requests_**
1. Launch Corporate Console
2. Login as CLA Manager
3. Click Get Started
4. Search and Select Company
5. Click JOIN COMPANY
6. Login to corporate console as CLA Manager of the Company'
7. Click on the Company
8. ACCEPT the pending CLA Manager request
9. Login to Coprorate console as the CLA Manager who was accepted for the company
10. Click on the Company
11. Click REQUEST ACCESS and request for access to the project
12. Login to corporate console as CLA Manager of the Company'
13. Click on the Company
14. Observed that **-** is displayed for Pending CLA Manager Requests  even if there are pending CLA Manager requests
![image](https://user-images.githubusercontent.com/60865903/81146786-95d74180-8f96-11ea-96d2-3537d8ecb3d5.png)

![image](https://user-images.githubusercontent.com/60865903/81146845-b1dae300-8f96-11ea-8170-d297ab36d8e5.png)

**Comment by nirupamav** [comment]
Verified below scenarios and it is working as expected. Keeping it open as I need to perform more testing
1. When all the requests are accepted/declined then the count is 0
2. When there is one pending request count is 1
3. When the 1 pending request is accepted then the count is updated to 0
4. When the 1 pending request is declined then the count is updated to 0

**Comment by nirupamav** [comment]
Verified that issue is fixed and Pending CLA Manager Requests count is displayed as expected

**Comment by dealako** [comment]
@amolsontakke3576 Is this a data loading issue - not updating the default `-` value when results come back?  Should be simple UI fix.

**Comment by nirupamav** [comment]
**Verified that issue is fixed**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/f25988e5-5757-4c6c-b083-46de5aea7589)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/134322e7-f247-4ac8-9b07-3b408b45f930)
