### ISSUE TITLE
Corporate Console - Status is not auto refreshed and changed to Pending after CLA Manager requests for access to the project

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1063]
## Background

1. Launch Corporate Console
2. Login as CLA Manager
3. Click Get Started
4. Search and Select Company
5. Click JOIN COMPANY
6. Login to corporate console as CLA Manager of the Company'
7. Click on the Company
8. ACCEPT the pending CLA Manager request
9. Login to Coprorate console as the CLA Manager who was accepted for the company
10. Click on the Company
11. Click REQUEST ACCESS and request for access to the project
12. Observed that status is not auto refreshed to Pending. User has to refresh the page to view the status
**Before Refresh**
![image](https://user-images.githubusercontent.com/60865903/81147130-49d8cc80-8f97-11ea-9fe6-2af8f92db255.png)

**After Refresh**
![image](https://user-images.githubusercontent.com/60865903/81147153-565d2500-8f97-11ea-9ed5-1f39030b1ec4.png)

**Comment by nirupamav** [comment]
Verified that the issue is fixed

**Comment by dealako** [comment]
Closing since this issue is resolved.
