### ISSUE TITLE
Corporate Console - Project Details is not auto refreshed and CLA Manager details is not updated when the CLA Manager request for the project is accepted

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1064]
## Background

1. Launch Corporate Console
2. Login as CLA Manager
3. Click Get Started
4. Search and Select Company
5. Click JOIN COMPANY
6. Login to corporate console as CLA Manager of the Company'
7. Click on the Company
8. ACCEPT the pending CLA Manager request
9. Login to Coprorate console as the CLA Manager who was accepted for the company
10. Click on the Company
11. Click REQUEST ACCESS and request for access to the project
12. Observed that status is not auto refreshed to Pending. User has to refresh the page to view the status
13. Login to corporate console as CLA Manager of the Company'
14. Click on the Company
15. Click MANGE APPROVED LIST
16. ACCEPT the CLA Manager request
17. Observed that page is not auto refreshed to display the accepted CLA Manager under CLA Managers section. It is updated when user refresh the pages or revisits the page

**Before Refresh**
![image](https://user-images.githubusercontent.com/60865903/81147682-6d504700-8f98-11ea-9719-2b6bae1f02d9.png)

**After Refresh**
![image](https://user-images.githubusercontent.com/60865903/81147771-a4bef380-8f98-11ea-8462-cdacd6dd0bda.png)

**Comment by nirupamav** [comment]
Verified that the issue is fixed

**Comment by mlehotskylf** [comment]
This is resolved, closing.
