### ISSUE TITLE
Corporate Console - Once rejected CLA Manager is able to keep joining the company but request is always set as rejected

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1068]
## Background
1. Launch Corporate Console
2. Login as **clamanager2**
3. Search and Select the company WhitelistAcceptTest
4. Click Join Company
5. Click ok on the notification popup
6. Login to corporate console as nirupamavkrsna (CLA Manager of the company WhitelistAcceptTest)
7. Click on the company
8. Decline the CLA Manager request of **clamanager2**
9. Login to corporate console as **clamanager2**
10. Search and select the company WhitelistAcceptTest
11, Click Join Company
12. Click Ok on notification popup
13. Email is sent to the CLA managers of the company but **clamanager2** is not able to see the company with status Awaiting Approval and Also there is no pending request for **clamanager2** for the CLA Managers of the company. 
I am able to repeat Step13 any number of times. Either rejected CLA Manager should not be able to join company again or if CLA manager is able to join company again, status should be pending and not rejected
![image](https://user-images.githubusercontent.com/60865903/81161840-ddb39400-8fa9-11ea-91d7-725d446ae070.png)

![image](https://user-images.githubusercontent.com/60865903/81161900-f754db80-8fa9-11ea-9eec-7a42cec2b99d.png)

**Comment by dealako** [comment]
@nirupamav @WillsonHG For this one, I have decided (feedback welcome):

- if existing request with 'pending' or 'approved' status - return 409 conflict - UI must show error message @amolsontakke3576 (see swagger spec updated which includes 409 definition)
- if existing request with 'denied' status - let's be nice, allow them to try again - set existing record status to 'pending', updated modified date/time, send emails, add event log notices, UI should refresh to show the current status.

I will create a PR shortly...

**Comment by dealako** [comment]
@nirupamav I didn't get a chance to do a lot of testing on this - can you help verify?  @amolsontakke3576 will want to add error handling on this request: https://github.com/communitybridge/easycla/blob/master/cla-frontend-corporate-console/src/ionic/pages/company-page/company-page.ts#L343

**Comment by nirupamav** [comment]
**Issue is still reproducible**
![image](https://user-images.githubusercontent.com/60865903/81386371-855bce00-9132-11ea-85f5-e14a5b03ad84.png)

![image](https://user-images.githubusercontent.com/60865903/81386259-580f2000-9132-11ea-8842-2b06ff3bac2a.png)

![image](https://user-images.githubusercontent.com/60865903/81386305-6e1ce080-9132-11ea-8077-ebb652a79831.png)

![image](https://user-images.githubusercontent.com/60865903/81386477-aa504100-9132-11ea-93a4-7fef705d619d.png)

**Comment by amolsontakke3576** [comment]
@dealako @wanyaland  I have checked the issue and as per the above comment status should be changed from rejected to pending when user request again.

**Comment by nirupamav** [comment]
**Verified that the issue is fixed**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/acb92c1d-cfc3-4a3d-a4b2-16d0f7a2489f)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c71f0733-ef57-4b58-84b4-8da269d61919)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/994049a9-7891-4676-82e1-5c0e5946b91e)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/642cd2ac-f0df-4c5a-8ce1-4fa9b5ebce3e)

**Comment by dealako** [comment]
Confirmed fixed. Closing issue.
