### ISSUE TITLE
Corporate Console - Empty row is displayed in All Companies when the rejected company is in the list of sorted companies

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1070]
## Background
**Prerequisite**
CLA Manager should have been rejected access to few companies

**Steps to Follow**
1. Launch Corporate Console
2. Login as CLA Manager
3. Observed that empty row is displayed when the company is rejected
![image](https://user-images.githubusercontent.com/60865903/81169127-f0cc6100-8fb5-11ea-890d-41754ad5bb1a.png)

![image](https://user-images.githubusercontent.com/60865903/81169148-fcb82300-8fb5-11ea-9481-ad1c57f3c0b2.png)

**Comment by nirupamav** [comment]
Verified that the issue is fixed

**Comment by amolsontakke3576** [comment]
Verified and working fine now

**Comment by dealako** [comment]
The old console is deprecated and removed.
