### ISSUE TITLE
Corporate Console - Error message is not displayed when trying to add already accepted/added CLA Manager

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1071]
## Background
**Prerequisite**
CLA Manager should be added to the project
CLA Manager request should be accepted for the project

**Steps to Follow**
1. Launch Corporate Console
2. Login as CLA Manager
3. Click on the company
4. Click on MANAGE APPROVED LIST
5. Try to add already added/accepted CLA Manager
6. Observed no error message like CLA manager already exists is not displayed and observed error for API request in network tab
![image](https://user-images.githubusercontent.com/60865903/81173062-114be980-8fbd-11ea-9f08-9aa8ccb2fd48.png)

**Comment by dealako** [comment]
The old console is deprecated and removed.
