### ISSUE TITLE
[Observed only once] Contributor Console - Observed CORS issue and email is not sent when employee send approval request for the contribution

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1074]
## Background
1. Launch github repository
2. Login as employee who is not whitelisted
3. Update any file and create PR
4. Click on CLA NOT SIGNED
5. Click Corporate
6. Search and select Company
7. Click SUBMIT
8. Click Contact
9. Select CLA Manager from list and provide all other details
10. Click SEND
11. Observed CORS issue in console and email was not sent to CLA Manager
**Tried again with same user and different user but could not reproduce the issue**
![image](https://user-images.githubusercontent.com/60865903/81184323-e8802000-8fcd-11ea-9e0e-5d7e8578df94.png)

**Comment by nirupamav** [comment]
**Observed this issue again**
![image](https://user-images.githubusercontent.com/60865903/87394874-02417300-c5ce-11ea-9afd-9d72c404eabb.png)

![image](https://user-images.githubusercontent.com/60865903/87394941-1dac7e00-c5ce-11ea-9fea-e7623900d77d.png)

![image](https://user-images.githubusercontent.com/60865903/87394959-24d38c00-c5ce-11ea-8276-0c2d3c1f0bf4.png)

**Comment by dealako** [comment]
The old v1 console is deprecated and removed.
