### ISSUE TITLE
Corporate Console - Pending Contributor Requests are not shown in Manage Approved List

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1076]
## Background
**Prerequisite**
Employees should have requested approval for contribution

**Steps to Follow**
1. Launch Corporate Console
2. Login as CLA Manager
3. Click on the company
4. Observed that Pending Contributor Requests is displayed as expected 
![image](https://user-images.githubusercontent.com/60865903/81194840-c04aee00-8fda-11ea-8ce9-e549a265f1b9.png)
5. Click on MANAGE APPROVED LIST
6. Observed the Pending contributor details are not displayed in UI. However data is fetched in API in the network tab
![image](https://user-images.githubusercontent.com/60865903/81194804-b5905900-8fda-11ea-99ae-7fb6c4f88d34.png)

![image](https://user-images.githubusercontent.com/60865903/81195077-0011d580-8fdb-11ea-8308-bc2ba55fbf67.png)

**Comment by dealako** [comment]
Resolved issue - raised PR https://github.com/communitybridge/easycla/pull/1077

The issue was with the table show/hide filter.1

Requested @amolsontakke3576 to review.

**Comment by nirupamav** [comment]
**Verified that the issue is fixed**
![image](https://user-images.githubusercontent.com/60865903/81278342-2aaf6d00-9073-11ea-8f12-45202054028c.png)

**Comment by dealako** [comment]
The old console is deprecated and removed.
