### ISSUE TITLE
[PROD] Corporate Console "Request Access" link not showing in CLA Table

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#1081]
## Summary

A CLA Manager cannot request access to a project's signed cla. The table shows a - where it should show "Request Access"

![image](https://user-images.githubusercontent.com/46732999/81232405-dd73c280-8fc2-11ea-8eaa-558580d2681c.png)

An error is observed. 
![image](https://user-images.githubusercontent.com/46732999/81232282-9ab1ea80-8fc2-11ea-846d-511cef8d8bee.png)

**Comment by dealako** [comment]
Need to run infra database update to add indexes to STAGING and PROD.

**Comment by dealako** [comment]
Index update complete in staging.

**Comment by dealako** [comment]
Index update complete in PROD.

**Comment by nirupamav** [comment]
@WillsonHG 
Could you please check this as I do not have access to PROD

**Comment by WillsonHG** [comment]
The request access link is showing in prod!
