### ISSUE TITLE
Corporate Console - Company name and project name text is not completely visible in Manager Approved List UI

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1086]
## Background
1. Launch Corporate Console
2. Login as CLA Manager
3. Click on the company
4. Click on MANAGE APPROVED LIST
5. Observed that Company name and project name text is not completely visible
![image](https://user-images.githubusercontent.com/60865903/81290158-2f7d1c80-9085-11ea-827a-4ca81f509866.png)

**Comment by dealako** [comment]
The old v1 console is deprecated and removed.
