### ISSUE TITLE
Project Console - "Get Access" link update

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#1096]
## Summary

When logging into project.lfcla.com the user sees their projects and/or a message as shown below:

![image](https://user-images.githubusercontent.com/46732999/81715527-54d3a700-9446-11ea-8c96-60807326b4b9.png)

## Expected behavior

The Get Access link should link to https://jira.linuxfoundation.org/servicedesk/customer/portal/4

## Environment

* Environment: DEV STAGING and PROD

**Comment by dealako** [comment]
Created PR: https://github.com/communitybridge/easycla/pull/1097.

@WillsonHG ready for PR review and deployment to DEV

**Comment by dealako** [comment]
Link active in DEV. @WillsonHG ready for validation.

**Comment by WillsonHG** [comment]
Lookgs good in dev!

**Comment by dealako** [comment]
Verified.
