### ISSUE TITLE
Corporate Console PRD Step 2 of Table 1 - No signed CLA found

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#1102]
## Summary
Any user associated with a company will be taken to this page after they switch to member console, select project from left navigation and EasyCLA from top navigation.

Here is the link to [wireframe ](https://wireframepro.mockflow.com/view/corporate-console#/page/Db3d69b699313a6e8106fdb78dea2b182)for the corporate console for EasyCLA.

Step 2 in Table 1 of PRD 
https://confluence.linuxfoundation.org/display/PROD/Corporate+Console+for+EasyCLA+V2

![image](https://user-images.githubusercontent.com/57362064/81768710-4f577a80-94a1-11ea-9cc3-6989777590b4.png)

All the backend operations will be encapsulated in EasyCLA API call. See PRD for more details.

## Acceptance Criteria
- [ ] Design Changes Required ?--> Not Applicable (N/A)   
- [ ] Unit Testing Complete 
    - [ ] Unit Testing complete for backend API
    - [ ] Unit Testing complete for UI
- [ ] Functional Testing Complete 
    - [ ] Functional Testing complete for backend API
    - [ ] Functional Testing complete for UI
- [ ] Integration Testing Complete 
    - [ ] Integration Testing complete for backend API and UI
    - [ ] Integration Testing complete end to end dev deployment
- [ ] Documentation Updated 
- [ ] Any Open Sev. 1, Sev 2 bug(s)

**Comment by vinod-kadam** [comment]
As discussed with Harold/David, this API is available on Dev env & Harold has tested the happy scenarios & are working fine. May be when Nirupama confirms the happy scenarios tomorrow, Harold   will update lfx team on slack channel that the API is ready for integration.

**Comment by nirupamav** [comment]
**Performed testing for happy path and happy path is working as expected. Testing is Inprogress for other scenarios**
User with user role is converted to contact and cla-manager-designee role is added to the user after the post action is successful
**Test Data used**
**_Role_** user
**_Scope_** (organization)
Bakbone

**_Endpoint_**
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company/0014100000Te1DWAAZ/project/a092M00001IfTjXQAV/cla-manager-designee

**_Payload_**
{
"userEmail": "nirupamav+mentee7@proximabiz.com"
}

**_Response_**
{
    "assigned_on": "2020-06-03 16:24:51.432396239 +0000 UTC m=+659.073242205",
    "company_sfid": "0014100000Te1DWAAZ",
    "email": "nirupamav+mentee7@proximabiz.com",
    "lf_username": "nirupamavmentee7",
    "project_name": "SPIRE",
    "project_sfid": "a092M00001IfTjXQAV",
    "type": "contact",
    "user_sfid": "00317000012PRhUAAW"
}

**_IAM roles before post action_**
![image](https://user-images.githubusercontent.com/60865903/83662655-6f341700-a5e5-11ea-892f-62753ef69b9c.png)

**_IAM roles after post action_**
![image](https://user-images.githubusercontent.com/60865903/83662757-968ae400-a5e5-11ea-953b-3a00784cb41f.png)

**Comment by vinod-kadam** [comment]
LFx team can use this API now for integration.

**Comment by omneya** [comment]
while trying this api it's returning 403 without error message this is sample request

**Request:**
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company/00117000013lmNGAAY/project/a0941000002wByYAAU/cla-manager-designee

**Payload:**
```
{
"userEmail": "bstone+testmember@linuxfoundation.org"
}
```

<img width="1142" alt="Screen Shot 2020-06-05 at 10 35 45 AM" src="https://user-images.githubusercontent.com/4056688/83855468-65f79700-a718-11ea-8e34-baba6b3701d6.png">


User Roles:
<img width="1358" alt="Screen Shot 2020-06-05 at 10 36 50 AM" src="https://user-images.githubusercontent.com/4056688/83855542-845d9280-a718-11ea-879d-a5ddedf93a51.png">

**Comment by nirupamav** [comment]
@pranab-bajpai 
User reaches to this step after clicking on Start the CLA process in Table 1, Step 1 of the PRD. As per Step1 below is the requirement for userrole

> This screen is shown when user browses to a EasyCLA screen for a project and two conditions are met.
> There is no CLA signed for that project by user's organization.
> User has access to this project since their organization contributes to this project or is associated with this project in some way.

But observed that as of now only user below role and scope is able to get the cla-manager-designee role assigned
Role - user
scope - Organization 

Could you please confirm which roles should have access to this API to get cla-manager-designee role

**Comment by omneya** [comment]
this endpoint keep returning 403 error

**Request:**
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company/00117000013lmNGAAY/project/a092M00001IV45CQAT/cla-manager-designee

**Payload:**
```
{
"userEmail": "bstone+testmember@linuxfoundation.org"
}
```

<img width="1143" alt="Screen Shot 2020-06-05 at 11 10 53 AM" src="https://user-images.githubusercontent.com/4056688/83889222-27c79b00-a74b-11ea-82f6-52fe03e12523.png">


**User Roles:**
<img width="1363" alt="Screen Shot 2020-06-05 at 4 40 38 PM" src="https://user-images.githubusercontent.com/4056688/83889516-8856d800-a74b-11ea-8c68-a106661ca1a4.png">

**Comment by wanyaland** [comment]
@omneya  So organization scope is amiss on this call and has to be set . We can sync and discuss further

**Comment by niravpatel27** [comment]
@omneya @dealako The permission was missing. We have added it. Can you please try in few mins?

**Comment by omneya** [comment]
it's working now, thanks

**Comment by wanyaland** [comment]
👍

**Comment by nirupamav** [comment]
@wanyaland 
**Tested and observed below issues**
1. A user with cla-manager role has scope Thanos|Bakbone. Now the same user is trying to start the CLA signing process for different project for e.g. KubeEdge. Observed that 403 is returned
When the company Bakbone has signed CLA for Thanos and If a user is cla-manager to Thanos project then the same user should also be able to sign CLA for a project that the company has not yet signed CLA
**_Observed same issue with cla-signatory role as well_**
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company/0014100000Te1DWAAZ/project/a092M00001IfTjOQAV/cla-manager-designee
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/97a0719b-04be-4c57-b3b9-b18e93d8adde)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/49b43cb4-72f6-493c-b355-f3b00cabfb30)
2. Observed that we are able to assign the cla-manager-designee to the user who is associated to the project|organization and also when the project already has signed CLA
I understand that this scenario might not occur when we go through workflow from UI, only case the issue may occur is when endpoint is called in a wrong place. The endpoint should not actually allow to assign cla-manager-designee when cla is already signed for the project. Not sure if this valid scenario but mentioned the issue for tracking purpose

**Comment by dealako** [comment]
Moved to next sprint.

**Comment by wanyaland** [comment]
@nirupamav 
For issue 1 the user has to have project|prg scope and if they dont happen to have that role they will not be authorized. Basing on your example youd stated if the user doesnt have project|org scope for KubeEdge|Bakbone they will not be authorized . Needed clarification on the second issue

**Comment by dealako** [comment]
From @nirupamav 
| 1. A user with cla-manager role has scope Thanos|Bakbone. Now the same user is trying to start the CLA signing process for a different project for e.g. KubeEdge. Observed that 403 is returned
When the company Bakbone has signed CLA for Thanos and If a user is cla-manager to Thanos project then the same user should also be able to sign CLA for a project that the company has not yet signed CLA

- Thanos Project | Bakbone Org -> Start/Complete CLA Flow -> OK
- KubeDege Project | Bakbone Org -> User can only Start CLA Flow IF no CCLA is created, otherwise, they ask the existing CLA Manager (via separate email) to add him as a manager?

**Comment by nirupamav** [comment]
@pranab-bajpai 
Testing completed. There is one open bug #1368 where we are able to assign cla-manager-designee role to a project which has already signed CLA. Since this cannot happen from UI, this is not a blocked and hence moving the user story to QA Done
Could you please review the test plan and let me know if I missed any scenarios
https://confluence.linuxfoundation.org/display/PROD/Assign+cla-manager-designee+role
