### ISSUE TITLE
Table 1 - No CLA Manager Designee Assigned - Step 2.3.1.2 in PRD 

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#1105]
## Summary
Any user associated with a company will be taken to this page after they switch to member console, select project from left navigation and EasyCLA from top navigation.

Here is the link to [wireframe ](https://wireframepro.mockflow.com/view/corporate-console#/page/Db3d69b699313a6e8106fdb78dea2b182)for the corporate console for EasyCLA.
![image](https://user-images.githubusercontent.com/57362064/81770036-b0cd1880-94a4-11ea-8d18-046afa8dff01.png)

Step 2.3.1.2  in Table 1 of PRD 
https://confluence.linuxfoundation.org/display/PROD/Corporate+Console+for+EasyCLA+V2

All the backend operations will be encapsulated in EasyCLA API call. See PRD for more details.

## Acceptance Criteria
- [ ] Design Changes Required ?--> Not Applicable (N/A)   
- [ ] Unit Testing Complete 
    - [ ] Unit Testing complete for backend API
    - [ ] Unit Testing complete for UI
- [ ] Functional Testing Complete 
    - [ ] Functional Testing complete for backend API
    - [ ] Functional Testing complete for UI
- [ ] Integration Testing Complete 
    - [ ] Integration Testing complete for backend API and UI
    - [ ] Integration Testing complete end to end dev deployment
- [ ] Documentation Updated 
- [ ] Any Open Sev. 1, Sev 2 bug(s)

**Comment by prasannamahajan** [comment]
@dealako 
Closing this issue.
No api needed for this.
API to get sign_url is provided in https://github.com/communitybridge/easycla/issues/1104
