### ISSUE TITLE
Corporate Console - No Action performed and error displayed in Console when trying to add CLA Manager who does not exist in LF system and user who exists but not access Corporate Console

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1116]
## Background
1. Launch Corporate Console
2. Login as CLA Manager (who has company with project signature)
3. Click on the Company
4. Click MANAGE APPROVED LIST
5. Click on ADD CLAManager button
**_Issue1_**
6. Add Details of CLA Manager who does not exist in LF system
![image](https://user-images.githubusercontent.com/60865903/82197736-f82a2d80-9918-11ea-8f53-f1f4ccaa2932.png)
7. Click Save. Observed that no action is performed and error is displayed in console
![image](https://user-images.githubusercontent.com/60865903/82198179-94543480-9919-11ea-8dce-c3080d3750f6.png)

API POST request was successful but no response is returned
![image](https://user-images.githubusercontent.com/60865903/82198297-b6e64d80-9919-11ea-989c-cdfa419d25b4.png)

**_Issue2_**
6. Add Details of CLA Manager who exists in LF system(Created in Mentorship page) but not logged in to Corporate Console
![image](https://user-images.githubusercontent.com/60865903/82198458-fa40bc00-9919-11ea-99dd-fbadbe809f68.png)

![image](https://user-images.githubusercontent.com/60865903/82198493-06c51480-991a-11ea-9f57-292067946ecd.png)

**Comment by amolsontakke3576** [comment]
It looks like issue is solved now.

![Screenshot from 2020-09-07 12-28-36.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/5b7101d1-ade6-471b-8af8-305b758e2044)

**Comment by nirupamav** [comment]
**_Verified that the issue is fixed._**

**User without LFID**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/284bb62d-168c-4bc1-a433-ab333108afca)

**USer with LFID but has not logged into corporate console yet**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/e78919ba-6a32-4df2-bba7-4ae548047220)
