### ISSUE TITLE
Corporate Console - EmailId from user service is displayed instead of the email entered while adding CLA Manager

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1119]
##  Background
1. Launch Corporate Console
2. Login as CLA Manager (who has company with project signature)
3. Click on the Company
4. Click MANAGE APPROVED LIST
5. Click on ADD CLA Manager icon
6. Enter CLA Manager name, CLA Manager LFID and email different from the one in user service
7. Click Save. Observed that the emailId from user service is displayed and also email is sent the emaild from user service
![image](https://user-images.githubusercontent.com/60865903/82204909-565c0e00-9923-11ea-8045-e538361fe441.png)

![image](https://user-images.githubusercontent.com/60865903/82204944-6247d000-9923-11ea-8093-4f731d379b26.png)

![image](https://user-images.githubusercontent.com/60865903/82205009-7c81ae00-9923-11ea-80c0-7cf932815d97.png)

**Comment by dealako** [comment]
The old v1 console is deprecated and removed.
