### ISSUE TITLE
Corporate Console - CLA Manager who has been already added to a project in the company is able to request to join the company

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1120]
## Background
1. Launch Corporate Console
2. Login as **clamanager2**
3. Click on the Company **Bakbone**
4. Click MANAGE APPROVED LIST for **EMM** project
5. Add **nirupamavkrsna** as CLAManager to the project
6. Login to Corporate Console as **nirupamavkrsna**
**_Issue1_**
7. Observed the company **Bakbone** is not listed in the Companies list even if the user is CLA Manager to a project in the company
**_Issue2_**
8. Click on Get Started
9. Search for company **Bakbone**
10. Click JOIN COMPANY
11. Observed that the CLA MAnager is able to request to join the company even if he/she is already added as CLA Manager to the project
![image](https://user-images.githubusercontent.com/60865903/82214014-ba3a0300-9932-11ea-9de0-a9a8a31b27ec.png)

![image](https://user-images.githubusercontent.com/60865903/82214068-d473e100-9932-11ea-9b27-8cd86ee58a56.png)

**Comment by dealako** [comment]
The old v1 console is deprecated and removed.
