### ISSUE TITLE
[Project Console] When installing an org, the capitalization must exactly match or the installation fails

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#1126]
## Summary

When installing a github org to a cla group, the capitalization must exactly match or the installation fails with no feedback to the user.

## Background

1. Go to project.lfcla.com
1. Click on project of interest
1. Click "connect github organization"
1. add github org in all lowercase
1. follow steps to install app through github
1. notice installation is successful in github but shows as not configured in project console even after refreshing

## Expected behavior
The github org should be installed whether the user correctly matches the case of the org.

## Screenshots

![image](https://user-images.githubusercontent.com/46732999/82467760-051d5d00-9a90-11ea-946f-6737d87a5f34.png)

![image](https://user-images.githubusercontent.com/46732999/82467820-19615a00-9a90-11ea-9ffb-0c359ce44aae.png)

Cloudwatch logs show 
2020-05-20T15:17:36 WARNING cla: organization name CLATestOrg does not exist

Link to cloudwatch logs:
https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/lambda/cla-backend-staging-githubactivity;stream=2020/05/20/%5B$LATEST%5D8f9e63c125ea46eabcd230f8abe8b77d;start=2020-05-19T15:11:18Z

## Environment

PRODUCTION

**Comment by dealako** [comment]
@WillsonHG Deployed changes to DEV.  Ready to review. I can deploy to staging if desired.

**Comment by WillsonHG** [comment]
This testing is blocked by #1140

**Comment by dealako** [comment]
@WillsonHG resolved 1140, please re-evaluate.

**Comment by WillsonHG** [comment]
I tested installing the clatestorg in all lowercase and it appears to have installed correctly 👍

**Comment by dealako** [comment]
@WillsonHG has confirmed that this works.  Needs deployment to PROD.
