### ISSUE TITLE
CCLA DocuSign "Sign Request For " pulling wrong user.

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#1127]
## Summary

When a cla manager goes to sign a ccla from the corporate console, the wrong user is sometimes shown in the "sign request for " in docusign.

## Background

1. Go to corporate.lfcla.com
1. Click on "sign new cla" and choose any cla.
1. Get redirected to docusign and observe the "sign request for " email is not the cla manager who initiated the signing.
## Expected behavior

The sign request should match the cla manager who initiated the request.
## Screenshots

![image](https://user-images.githubusercontent.com/46732999/82470115-ea001c80-9a92-11ea-9ef5-301b5113e364.png)
\
\
\

![image](https://user-images.githubusercontent.com/46732999/82470355-3cd9d400-9a93-11ea-95ba-23b3bc490bcd.png)

![image](https://user-images.githubusercontent.com/46732999/82470838-d903db00-9a93-11ea-9a63-fdbbd68e46e5.png)

## Environment

STAGING AND PROD

## Assumptions

This is reproduced when I changed the cla manager id  in the companies table to david's user id in staging.

**Comment by WillsonHG** [comment]
This looks to be using the company_manager_id in the companies table and not the person going to sign the ccla.

Even if the user corrects it in docusign as they're signing the ccla, the email sent after signing is still sent to the company_manager

**Comment by dealako** [comment]
Task not complete - moved to the next sprint.

**Comment by dealako** [comment]
Pushed an update to DEV via PR: https://github.com/communitybridge/easycla/pull/1294. Needs validation.

**Comment by dealako** [comment]
Pushed an update to DEV via PR: https://github.com/communitybridge/easycla/pull/1323.  This update sends the confirmation email to the CLA manager (not the company admin).  We also add an event log entry in this update.

**Comment by nirupamav** [comment]
**Verified and observed that the issue is fixed**
**_CLA Manager who created company is nirupamav+v1cla1@proximabiz.com. However details of CLA Signatory who initiated the signature is displayed_**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c078ab0a-9fad-4e8a-b119-27432d7868c3)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/0f2666b4-2f10-4e19-9475-f667f142ade4)
