### ISSUE TITLE
[PROD] Allow List Update Email cleanup

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#1137]
## Summary

When a CLA manager receives an email notification that the Allow list has been updated, the email includes a html> tag at the beginning. 

## Background

1. Go to corporate.lfcla.com
1. Select a cla that you are the cla manager for and modify the allow list.
1. Receive an email that the allow list has been modified.
1. Observe the email contains an html tag missing the opening symbol and the formatting may need to be cleaned up a bit.

## Screenshots

![image](https://user-images.githubusercontent.com/46732999/82921984-0b578180-9f47-11ea-9494-512537c714b8.png)

## Environment

Please complete the following information:
PROD

**Comment by dealako** [comment]
I think this email has been resolved - need to confirm.

**Comment by dealako** [comment]
@nirupamav

**Comment by nirupamav** [comment]
Tested and observed that there is blank tag in the "reach out to us for support" link and also email needs to be formatted
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/351453e3-e524-4b56-a60a-5933cce5dc87)

**Comment by dealako** [comment]
Need to convert the API call from v2 to v3.

**Comment by nirupamav** [comment]
**Observed that the issue is fixed**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/fc119cf4-0729-4ec0-a37d-2c76f061b98f)
