### ISSUE TITLE
Not able to connect to github org

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1140]
## Background
1. Launch project console
2. Login as project manager
3. Click on Project/Foundation
4. Connect github org (created a org lfxorg and connected to Thanos project)
5. Installation in github completed without any issues but in UI it shows Not Configured
![image](https://user-images.githubusercontent.com/60865903/83002992-534fd480-a02b-11ea-9e6d-e2a7424446c0.png)

![image](https://user-images.githubusercontent.com/60865903/83003044-65ca0e00-a02b-11ea-8eac-13f64812d16c.png)

Tried with CNCF foundation and still facing same issue
![image](https://user-images.githubusercontent.com/60865903/83003246-ade93080-a02b-11ea-9738-de8b9e8acbc9.png)

**Comment by dealako** [comment]
@WillsonHG conducted another test and we see this [in the logs](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fcla-backend-dev-githubactivity/log-events/2020$252F05$252F29$252F$255B$2524LATEST$255Dee03af8b47c04319b9b9c3ab6160ecb1):

```
2020-05-29T22:27:13 DEBUG cla: Loading GitHub by organization name: CLATestOrg..
2020-05-29T15:27:13.420-07:00
/var/task/pynamodb/connection/base.py:1514: UserWarning: Legacy conditional parameters are deprecated in favor of condition expressions
2020-05-29T15:27:13.420-07:00
warnings.warn("Legacy conditional parameters are deprecated in favor of condition expressions")
2020-05-29T15:27:13.555-07:00
2020-05-29T22:27:13 DEBUG cla: Loaded GitHub by organization name: organization id:None, organization installation id: None, organization SFID: None, organization project id: None, organization company id: None
2020-05-29T15:27:13.563-07:00
2020-05-29T22:27:13 WARNING cla: organization does not exist: None - unable to update
```

**Comment by dealako** [comment]
Provided update to the Python code which should query and return the organization properly now.  @WillsonHG will test to validate the fix.

**Comment by dealako** [comment]
@WillsonHG confirmed the fix in DEV.

**Comment by dealako** [comment]
Closing issue for now.

**Comment by wanyaland** [comment]
👍
