### ISSUE TITLE
V2 - User with cla-manager-designee role should have access to the endpoint to fetch CLA enabled projects 

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1157]
## Background

Based on below clarification by @pranab-bajpai, user with cla-manager-designee role should have access to the below endpoint to fetch CLA enabled projects 
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/project/enabled/{{foundationsfid}}

![image](https://user-images.githubusercontent.com/60865903/83415714-280b2200-a43d-11ea-9275-09c062683742.png)

LFX ticket - https://jira.linuxfoundation.org/browse/LFX-1678

**Comment by dealako** [comment]
@wanyaland has created a PR.

**Comment by nirupamav** [comment]
Verified and observed that user with cla-manager-designee is able to fetch CLA enabled projects for foundations
