### ISSUE TITLE
convert cla-manager-designee to cla-manager once signing process is complete

### ISSUE THREAD

**Issue by prasannamahajan** [communitybridge/easycla#1171]
## Summary
Before user signs cla we assign cla-manager-designee role to that user
This is temporary role for user.
Once signing process is complete we should assign cla-manager role to the user
and cla-manager-designee role should be removed.

## Background

Step 2.3.2 and 2.3.2.1 in Table 1 of PRD
https://confluence.linuxfoundation.org/display/PROD/Corporate+Console+for+EasyCLA+V2

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. User should be assigned to role of cla-manager once signing process is complete
1. All the stale entries of cla-manager-designee should be removed.
1. cla-manager role in acs should be assigned for all project of cla-group

**Comment by vinod-kadam** [comment]
@prasannamahajan , please provide a ETA.

**Comment by prasannamahajan** [comment]
ETA: 25th June

**Comment by nirupamav** [comment]
Verified below scenarios from LFX portal

1. cla-manager-designee who has signed CLA is given cla-manager role to the project and cla-manager-designee role is removed for the project for the user
2. cla-manager-designee who has signed CLA is given cla-manager role to the project and cla-manager-designee role is removed for the project for the user and cla-manager-designee role for other projects for the user is not removed
3. cla-manager-designee role is removed for the project for other users when one of the cla-manager-designee signs CLA 
4. cla-manager-designee role is removed for the project for other users and  cla-manager-designee role is not removed for other projects for the user when one of the cla-manager-designee signs CLA
