### ISSUE TITLE
V2 - Issues in signatures/project/{{projectsfid}}/company/{{companysfid}} endpoint

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1173]
**Observed below issues in the endpoint to get Approved List of Contributors From My Organization in Project EasyCLA page** 
**User Story - #938**
URL - {{apiserver}}/v4/signatures/project/{{projectsfid}}/company/{{companysfid}}
1. In the response, null is returned for emails in signatureACL object even though there is a secondary email for the user
https://user-images.githubusercontent.com/60865903/83748395-bf5fb780-a67f-11ea-823d-fb4833d4add4.png
2. As per the the response model, git hub details should be displayed in the signatureACL object. But we do not store the github details of the user in cla_dev_users so should those details be in the response model
3. As per the the response model, admin and userExternalID details should be displayed in the signatureACL object. For the CLA Manager admin value exists in cla_dev_users table but is not returned in response. Should sfid for the CLA Manager be returned for userExternalID?
4. CLA group name is not returned in the response. Adding approve list endpoint accepts CLA group ID. If CLA group name is not returned in the response, CLA Manager will not have option to select the CLA group for which the approved list is added and hence from UI approved list can never be added
5. User withe user role and Organization scope is able to access the endpoint and 200 with response content is returned, but 403 should be returned
6. total-count in the response is always returned as 0

**Comment by vinod-kadam** [comment]
David to review if it need to be fixed for 1st EasyCLA release.

**Comment by rinkeshbhutwala** [comment]
@dealako I have verified this ticket and below is my observation.

point 1: If the emails are present in our cla-dev-users table then it will show otherwise return null.
point 2: If the GitHub details are present in the cla-dev-users table then it will be shown in the signature-ACL object.
point 3: If the admin and userExternalID are present in our cla-dev-users table then it will be shown in the signature-ACL object.

**Comment by vinod-kadam** [comment]
@rinkeshbhutwala , I went through your comments.
Point 1 - can you check if primary email is not present then does our code returns secondary email?
Point 6 - Check whether total-count returned is always zero.

**Comment by rinkeshbhutwala** [comment]
@vinod-kadam for point 1: based on signature ACL we are processing using the ACL name we search in cla database and whatever data are present we are showing those in response.

**Comment by dealako** [comment]
We are closing this issue for now due to inactivity. We can re-open this ticket or create a new ticket if needed.
