### ISSUE TITLE
V2 - contributor role should have view access to CLA end points similar to other non cla-manager roles in cla-service.yaml

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1183]
## Background
As per the details provided in Access column for **Corporate Contributor** persona in below PRD, similar to other non cla-manager roles, view access policies should be applied for contributor role also in cla-service.yaml
https://confluence.linuxfoundation.org/display/PROD/EasyCLA+PRD+for+Version+2

![image](https://user-images.githubusercontent.com/60865903/83844266-46666b80-a724-11ea-912e-aa6beac0ba3e.png)

**Comment by dealako** [comment]
Updated ACS CLI permissions to allow the following policies:

- View Templates
- Assign CLA Manager Designee
- Create CLA Manager Request
- View CLA Enabled/Summary Pages
- View Company Project CLAs

which are now applied to the following roles:

- user
- community-program-manager
- lf-executive
- contributor
- contact
- lead
- donar
- lf-training
- + all the other CLA roles (CLA Manager, CLA designee, CLA Signatory, Program Manager, etc.)

@nirupamav ready for review

**Comment by nirupamav** [comment]
@dealako 
Contributor should have ready only access to all the endpoints in Project Dashboard and Foundation dashboard
 ViewCompanyCLAManagers
 ViewCompanyActiveCLAs
 ViewCompanyProjectContributors
ViewProjectCompanySignatures

**Below is the reference**
https://confluence.linuxfoundation.org/display/PROD/Corporate+Console+for+EasyCLA+V2
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/7b2c8df2-0d91-40f4-95f0-0d94da929153)

**Comment by dealako** [comment]
@nirupamav based on the configuration, the above-mentioned profiles should apply to Contributors:

- ViewCompanyCLAManagers
- ViewCompanyActiveCLAs
- ViewCompanyProjectContributors
- ViewProjectCompanySignatures

[See the acs-cli configuration](https://github.com/LF-Engineering/acs-cli/blob/master/services/11-cla-service.yaml#L619-L631).

**Comment by nirupamav** [comment]
**Verified that contributor has access to below endpoints**
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/getCompanyProjectActiveCla
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/getCompanyProjectClaManagers
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/getCompanyProjectEvents
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/listCompanyProjectMetrics
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/getProjectCompanySignatures
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/getCompanyProjectContributors
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/createCLAManagerDesignee
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/createCLAManagerRequest
