### ISSUE TITLE
Support multiple project association with cla_group

### ISSUE THREAD

**Issue by prasannamahajan** [communitybridge/easycla#1184]
## Summary
 
when we create cla_group, we can add multiple repositories from multiple projects or foundation
hence cla_group is associated with the multiple projects and these projects are associated with foundation

## User Story
- As a developer, I need easycla database schema to support cla_group association with multiple projects

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. database design support having multiple project associated with cla_group
2. provide following functions
> 1. get cla_groups by foundation
> 1. get cla_groups by project

**Comment by dealako** [comment]
![v2 Foundation + Project to CLA Group Mapping Concept - Database Tables.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/93bfdd44-b3c1-45f6-9e7e-8d8d8c973e70)

**Comment by prasannamahajan** [comment]
Pull request:
https://github.com/communitybridge/easycla/pull/1194

**Comment by dealako** [comment]
Moved to the next sprint. Awaiting QA @nirupamav

**Comment by nirupamav** [comment]
While testing #1147 Observed that project manager is able to perform below actions and hence moving the ticket to QA Done

1. Able to create CLA group with single/multiple projects
2. Able to Enroll single/multiple projects for a CLA group
3. Able to fetch all enrolled projects for CLA group
