### ISSUE TITLE
Individual Contributor Console Flow Integration - ICLA

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#1196]
## Summary

Integrate the ICLA flow with the backend API.

## Background

David has documented the API flows that the existing v1 system uses and "should work" with the ICLA flow. See the [PRD - table 1](https://confluence.linuxfoundation.org/display/PROD/Contributor+Console+for+EasyCLA+V2#ContributorConsoleforEasyCLAV2-Table1.ContributorConsoleIndividualCLAflow.)

## User Story

As a contributor, I want to sign an ICLA for my project.

## Assumptions

- No v1 API changes are needed for this flow.

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

- [Contributor Console PRD](https://confluence.linuxfoundation.org/display/PROD/Contributor+Console+for+EasyCLA+V2#ContributorConsoleforEasyCLAV2-Table1.ContributorConsoleIndividualCLAflow.)

**Comment by dealako** [comment]
Moved to the next sprint. Awaiting QA @nirupamav

**Comment by nirupamav** [comment]
Testing In progress and logged below bugs
#1239

**Comment by nirupamav** [comment]
Testing of bugs is Completed and waiting for below bugs to be fixed
#1243, #1244, #1245, #1246, #1247, #1248

**Comment by nirupamav** [comment]
@pranab-bajpai 
Could you please check the above mentioned and let me know if they needs to be fixed before I close this user story

**Comment by nirupamav** [comment]
Since the ICLA flow is working as accepted moving the ticket to QA Done
Will discuss about below tickets with @pranab-bajpai and check if they needs to be fixed for MVP release
#1243, #1244, #1245, #1246, #1247, #1248
