### ISSUE TITLE
Individual Contributor Console Flow Integration - CCLA - With Signed CLA

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#1197]
## Summary

Integrate the Individual Contributor Console Flow With Signed CLA flow with the backend API.

## Background

David has documented the API flows that the existing v1 system uses and "should work" with the Contributor Console CCLA - With Signed CLA flow. See the [PRD](https://confluence.linuxfoundation.org/display/PROD/Contributor+Console+for+EasyCLA+V2#ContributorConsoleforEasyCLAV2-Table2.ContributorConsoleCorporateCLAflowwhenthereisasignedCLA.) - Table 2

## User Story

As a contributor, I want to sign an CCLA for my project on behalf of my company.

## Assumptions

- No v1 API changes are needed for this flow.

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

- [Contributor Console PRD](https://confluence.linuxfoundation.org/display/PROD/Contributor+Console+for+EasyCLA+V2#ContributorConsoleforEasyCLAV2-Table2.ContributorConsoleCorporateCLAflowwhenthereisasignedCLA.)

**Comment by dealako** [comment]
Moved to the next sprint. Awaiting QA @nirupamav

**Comment by nirupamav** [comment]
Testing In progress and logged below bugs
#1249

**Comment by nirupamav** [comment]
Testing completed for the flow when contributor is not approved.
Testing pending for the flow when contributor is approved due to tickets #1257, #1319

**Comment by nirupamav** [comment]
All bugs are fixed except for #1364. Moving the user story to QA Done as the bug #1364 is not blocker
