### ISSUE TITLE
V2 - Secondary Email is fetched instead of primary email in company/{{companysfid}}/project/{{projectsfid}}/cla-managers endpoint

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1200]
Trigger the end point to fetch CLA Managers for the company
**Http Method** GET
**API URL** https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company/0014100000Te1DWAAZ/project/a092M00001IV4PgQAL/cla-managers
**Header** Authorization/<Valid Bearer token>

**Observed that secondary email of the CLA Manager is fetched instead of primary email**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/6d084d6d-e5de-4bb1-8a96-ce955133a484)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c536eaf5-cd45-4aed-8caf-33c76d31744c)

**Comment by vinod-kadam** [comment]
@prasannamahajan , Please provide an ETA for this one. This is needed for LFX - delete CLA Manager functionality doesn't work when secondary email is returned (see https://jira.linuxfoundation.org/browse/LFX-1893).

Note: I have set the Milestone to current sprint.

**Comment by prasannamahajan** [comment]
PR: https://github.com/communitybridge/easycla/pull/1288

**Comment by dealako** [comment]
@nirupamav @vinod-kadam merged changes from @prasannamahajan - ready for review/re-test.

**Comment by nirupamav** [comment]
**Verified below scenarios and observed that primary is always fetched in the response**
1. When there is only primary email, primary email is fetched
2. When secondary email is added, primary email is fetched
3. When secondary email is set as primary, updated primary email is fetched
4. When all other emails are deleted and only primary email exists for the user, primary email is fetched
