### ISSUE TITLE
Individual Contributor Console Flow Integration - CCLA - Company Not Found

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#1218]
## Summary

Integrate the Individual Contributor Console Flow - No Company Found backend API.

## Background

Implement APIs to support [Table 4 of the PRD](https://confluence.linuxfoundation.org/display/PROD/Contributor+Console+for+EasyCLA+V2#ContributorConsoleforEasyCLAV2-Table4.ContributorConsoleIndividualCLAflowwhenthecompanyisnotfound.)

## User Story

As a contributor, I want to sign a CCLA for my project on behalf of my company.

## Assumptions

N/A

## Questions

N/A

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

- [Contributor Console PRD -Table 4 - Contributor Console Individual CLA flow when the company is not found.](https://confluence.linuxfoundation.org/display/PROD/Contributor+Console+for+EasyCLA+V2#ContributorConsoleforEasyCLAV2-Table4.ContributorConsoleIndividualCLAflowwhenthecompanyisnotfound.)

**Comment by dealako** [comment]
@amolsontakke3576 API is ready now

**Comment by nirupamav** [comment]
@wanyaland 
Could you please provide the endpoints that I need to test in this ticket

**Comment by wanyaland** [comment]
@nirupamav . The API Doc https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/createCompany.
Endpoint : https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/user/{userID}/company

**Comment by nirupamav** [comment]
**_Tested and observed below issues_**
**1. 500 returned when trying to create company with invalid userid**
**https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/user/cb435299-83f6-4a21-84cc-742dc3af29f6/company**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/870590ac-786b-4079-a5dd-02cdbf883172)

**2. Able to create company with different url formats of website url**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/1a60b0d6-d419-42a1-b8aa-85714841d100)
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/2da128f7-0d90-4c49-a899-4ec126ae04a4)

**3. Observed that when company is deleted in OrgService it is not getting deleted from cla-dev-companies table**

Other Bugs that are related to this endpoint which needs to be fixed are 
#1361, #1362, #1341, #1285, #1287,

**Comment by wanyaland** [comment]
@nirupamav . 
Issue2 is being handled at organization-service layer 
Issue3. At which point was deletion of organization happening.. Was it at core-service level ?

**Comment by dealako** [comment]
@wanyaland please update this ticket? Ready for QA or more dev?

**Comment by wanyaland** [comment]
Issue 3 is not sorted.. Seeing as delete company is not handled in the contributor console.

**Comment by dealako** [comment]
Won't fix issue 3.
