### ISSUE TITLE
Download all Individual Signatures for this CLA Group PDFs as a Zip file

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#1227]
## Summary

Download all Individual Signatures for this CLA Group PDFs as a zip file

## Background

For a description of the services needed, view the [Project Console PRD](https://confluence.linuxfoundation.org/display/PROD/Project+Console+for+EasyCLA+V2).

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the DEV environment.

## References

- [Project Console PRD](https://confluence.linuxfoundation.org/display/PROD/Project+Console+for+EasyCLA+V2)

**Comment by prasannamahajan** [comment]
API : https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/downloadProjectSignatureICLAs

**Comment by nirupamav** [comment]
Testing blocked due to #1448, #1411, #1319

**Comment by nirupamav** [comment]
**_Tested and observed below issues_**
**1. 200 response with url for zip file is returned when there are no ICLA signatures for the CLA Group and when clicked in the url XML page with error is displayed**
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/signatures/project/977c80c6-8282-4d31-a8d2-8c69361bb967/icla/pdfs
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/0b6dc9dc-447f-4573-b7b0-4f4e8278c16d)

**2. Observed that when accesses the url to download zip file with 96.5MB size, it took 6 mins
My internet download speed is 14Mbps and according the speed it should not take more than a minute to download 96.5MB zip file**
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/signatures/project/b15286dd-4b34-4bb7-a57d-543e9c4a4efc/icla/pdfs
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/dfcd11d6-99f7-4ae7-99b1-518bc3d1dadd)

**_Testing for CLA Group at different levels is pending which will be covered in End to End tesing_**

**Comment by prasannamahajan** [comment]
@nirupamav  @dealako 
Raised PR for Point 1.
Returning 404 error if zip file is not present, which should occur only when there is no signature.
