### ISSUE TITLE
Download all Corporate Signatures for this CLA Group PDFs as a zip file

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#1231]
## Summary

Download all Corporate Signatures for this CLA Group PDFs as a zip file

## Background

For a description of the services needed, view the [Project Console PRD](https://confluence.linuxfoundation.org/display/PROD/Project+Console+for+EasyCLA+V2).

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the DEV environment.

## References

- [Project Console PRD](https://confluence.linuxfoundation.org/display/PROD/Project+Console+for+EasyCLA+V2)

**Comment by prasannamahajan** [comment]
API: https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/downloadProjectSignatureCCLAs

**Comment by nirupamav** [comment]
Testing blocked due to #1448, #1411, #1319

**Comment by nirupamav** [comment]
Tested and observed below issues
**1. 200 response with url for zip file is returned when there are no CCLA signatures for the CLA Group and when clicked in the url XML page with error is displayed**
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/signatures/project/234172e4-8342-4ae2-a149-1bc2ceb51f61/ccla/pdfs
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/2678989d-4073-426e-a435-53929c28e61d)
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/f0ac4f9b-9c3f-468b-9ab3-9fea52a77034)

**2. Observed that when accesses the url to download zip file with 135MB size, it took 5 mins
My internet download speed is 27Mbps and according the speed it should not take more than a minute to download 135MB zip file**
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/signatures/project/b15286dd-4b34-4bb7-a57d-543e9c4a4efc/ccla/pdfs
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/6a08e345-632d-46a1-8e4e-ba5947fbcad5)

**Comment by prasannamahajan** [comment]
@nirupamav Raised PR to fix point no 1
https://github.com/communitybridge/easycla/pull/1500

**Comment by dealako** [comment]
@rinkeshbhutwala please pick up this ticket and work with @nirupamav on where we are with this one...

**Comment by nirupamav** [comment]
**Issue1 is fixed. Regarding Issue2, as per discussion in standup call with @dealako , this is downloaded from AWS and performance issue cannot be fixed from our end. Hence moving the ticket to QA Done**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/019be01e-a8be-458f-9b52-683f76682a1c)
