### ISSUE TITLE
Able to send CLA Manager request to user that is not associated with the any organization

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1234]
**Prerequisite**
Create a user account from LFX portal and do not associate the user with any organization
**For e.g. if the employee of the organization created an account with personal email address**

**Steps to Reproduce**

1. Launch https://lfx.dev.platform.linuxfoundation.org/
2. Login with user having below role and scope
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a9c2eb5f-6e43-41e8-9f9c-49e6732a5efd)
3. Expand Cloud Native Computing Foundation
4. Click on any project that has not signed CLA
5. Click on Start the CLA process button
6. Click No in "No Signed CLA Found" dialog
7. Enter email address of user that is not associated with any organization (user created in prerequisite)
8. Observed that CLA Manager request is successful and CLA Manager designee role is getting assigned to the user.

 
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/9e8e2085-45b4-4999-a970-6bef4614ec8d)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/8614f118-bb5f-464d-aada-d17431d308f4)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/270cd3f9-96ae-4ed1-a88c-30ccaaf5dbde)

**Comment by nirupamav** [comment]
**Issue is still reproducible**
Created a new user account and tried to assign cla-manager-designee role for that user. Observed 400 is returned however cla-manager-designee role is still assigned
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/156ba39f-271b-45e8-99ad-01a7112a881c)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/b93f560f-acd1-4816-acdd-2cf6cdeec95d)

**Comment by nirupamav** [comment]
**_Issue is still reproducible_**
**User with only user role**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/cfcf9e2a-c05b-4c0f-810e-6c88d9c9cdf8)

**400 is returned by the endpoint but cla-manager-designee role is assigned**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/864f501a-b402-4ec2-93b5-070b0139b5b7)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/861bb346-a156-4884-8a2f-63c7db3b4b5c)

**Comment by wanyaland** [comment]
@nirupamav . On testing with. a new user I got expected response.
![Screenshot 2020-07-11 at 01.34.30.png](https://images.zenhubusercontent.com/5ed66fcc690afccc216f0ecb/a50b391d-d4a6-4817-a009-7d6dbaed67fe)

**Comment by nirupamav** [comment]
@wanyaland 
Can you please check in Dev environment as I am able to reproduce it whenever I try in Dev environment
**Created a new user**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/828d64bd-366a-4523-8967-0515c032e736)

**API request to assign cla-manager-designee role**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/1c45cb62-d8e0-4a71-8415-c9eca96bdb4a)

**Observed that cla-manager-desginee role is assigned**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/6afef42d-91ce-4b27-a900-d771359b8c89)

**Comment by wanyaland** [comment]
@nirupamav  . Have created a new account and tested in dev and the assignment of cla-manager-designee role was not possible

![Screenshot 2020-07-14 at 18.19.05.png](https://images.zenhubusercontent.com/5ed66fcc690afccc216f0ecb/7ceae74a-0375-480c-8479-a286c1d0a173)

![Screenshot 2020-07-14 at 18.16.57.png](https://images.zenhubusercontent.com/5ed66fcc690afccc216f0ecb/9216de2d-8cec-44c7-aa93-641e91e9163a)

**Comment by nirupamav** [comment]
@wanyaland 
I think I was trying below endpoint
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company/0014100000Te0iaAAB/project/a092M00001IV4AbQAL/cla-manager-designee

**Comment by wanyaland** [comment]
@nirupamav Yes that endpoint doesnt handle the use case for sending CLA Manager request.

**Comment by nirupamav** [comment]
**Verified that the issue is fixed**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/750423a9-72cf-40e7-8a61-99f75457b6a5)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/ed726501-7ced-4f30-a928-f5b75e29a593)
