### ISSUE TITLE
Issues with email content when LFID creation request is sent to the user that is added as cla manager

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1235]
1. Launch https://lfx.dev.platform.linuxfoundation.org/
2. Login as CLA Manager for the Brigade project and Bakbone company
3. Expand Cloud Native Computing Foundation
4. Click on Brigade project
5. Try to add any user that does not exist in the LFX database
6. Request is sent to the user to create LFID
7. Observed below issues with the email content. Since the email is handled through API logging a ticket for API
**_Issue1 - First sentence in the Email content is not mentioned in PRD_**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/9d7ec2d9-2c98-4978-b179-9adb67f72d5d)

**_Issue2 - Email content is not formatted_** 
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/1762ac96-7970-4d42-b1c2-3d7aecdbb21d)

As per content mentioned in PRD(screenshot below) the content should be displayed in a proper paragraph sentence
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/6c8d7441-5070-4ee5-86c6-9809aed45c91)

**_Issue3 - Link to create LFID is provided on different text_**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/9312d0ab-c885-4587-b23c-d2d331e7d7ae)
As per PRD
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/681cbd33-6412-4034-a196-6264714ce069)

**Comment by dealako** [comment]
Issue 1 - PRD is incorrect.  Based on our approved emails, we want to follow the [standard template format](https://docs.google.com/document/d/1jFlSq1tx66LbBwGbSfJm3QS4st68GblfzBEMZRya9gk/edit).

**Comment by dealako** [comment]
Issue 2 needs email cleanup - consolidate the sentences into a single paragraph as outlined by @nirupamav.

Issue 3 - need to clean up the link.

**Comment by dealako** [comment]
@nirupamav created PR https://github.com/communitybridge/easycla/pull/1236 to address the concerns. I have re-formatted the email - will update the PRD to match the text.

**Comment by dealako** [comment]
Merged PR - Deployed to DEV.

**Comment by dealako** [comment]
@nirupamav which PRD is this referencing?

**Comment by nirupamav** [comment]
@dealako 
PRD - https://confluence.linuxfoundation.org/display/PROD/Project+Dashboard+for+EasyCLA
Table 1 Step3.3

**Comment by nirupamav** [comment]
Verified that the issue is fixed. Have a query related to the link to create LFID. Will check with @pranab-bajpai  and log a ticket if required
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/1b75a4e2-ee5c-4a64-8c37-9680902ce449)

**Comment by nirupamav** [comment]
Logged https://app.zenhub.com/workspaces/lfx-easyclav2-5ed619832c71a855a76ef404/issues/communitybridge/easycla/1304 for LFID link issue
