### ISSUE TITLE
V2 - Appropriate error message is not displayed when ICLA template is not generated

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1240]
**Prerequisite**
1. Create a CLA group with only ICLA enabled
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/58312ded-d9cf-4e3f-9020-1fa573975020)
2. Add github repository for the CLA group
3. Do not generate template
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/4a43b25e-c8cf-4c79-b8a8-df4b33acd084)

**Steps to Follow**
1. Login to Github as individual contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Individual Contributor
8. Click on SIGN CLA when the button is enabled
9. Observed error is returned in API call while preparing document as template is not generated
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/51e74d43-5117-4bc1-a768-16a9b5417512)
10. However SIGN CLA button is enabled and CLA Ready For Signature dialog is displayed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/5e1daf50-b3bc-425d-8dcf-99106224244f)
11. Click on SIGN CLA button
12. Observed below error message is displayed. Appropriate error message should be displayed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/633a210f-0ac3-47af-8f2f-0284f31d6919)

@pranab-bajpai 
Could you please provide the error message that needs to be displayed in this scenario. 
Since the issue is identified while preparing the document, instead for CLA Ready For Signature, should another dialog be displayed? If so can you please provide the wireframe design

**Comment by pranab-bajpai** [comment]
Error message should be "CLA system is not able to support your request please open a support ticket"

**Comment by nirupamav** [comment]
Verified that the issue is fixed. Also observed that support link is opened in new tab when clicked on create a ticket link
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/339618f4-75b7-4a93-9f48-4e2551f6394c)
