### ISSUE TITLE
V2 - Docusign is taking around 1min to load the ICLA template

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1242]
**Prerequisite**
1. Create a CLA group with only ICLA enabled
2. Add github repository for the CLA group
3. Generate template

**Steps to Follow**
1. Login to Github as individual contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Individual Contributor
8. Click on SIGN CLA when the button is enabled
9. Observed that docusign is taking around 1min to load the ICLA template
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/b8f2a116-f82a-48d1-9ee0-59e7bea2e9d6)

**Comment by dealako** [comment]
This is a DocuSign demo account website/API that is taking too long. Nothing we can do on the EasyCLA side - this may be related to network slowness??  Closing ticket.
