### ISSUE TITLE
V2/V1 - Email is not sent to contributor after signing the ICLA from contributor console

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1244]
**_In V1 email notification is sent to contributor when ICLA is signed from contributor console. V1 refrence ticket - #963. Not sure if this is valid in V2, but logging the ticket for tracking purpose_**

**Prerequisite**
1. Create a CLA group with only ICLA enabled
2. Add github repository for the CLA group
3. Generate template

**Steps to Follow**
1. Login to Github as individual contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Individual Contributor
8. Click on SIGN CLA when the button is enabled
9. Complete the docusign process
10. Observed that email notification is not sent to the contributor. Below is the email setting in github which was used in V1 as well
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/e73905d4-e3a6-432c-8c64-34c1376430f7)

**Comment by pranab-bajpai** [comment]
@nirupamav what email should be sent at this point? I'll add the text to PRD. Will this be an email where user does contribution acknowledgement?

**Comment by nirupamav** [comment]
@pranab-bajpai 
In V1 below email notification is sent in this scenario. However in V2 email notification is not sent an the issue is tracked in this 
ticket
![image](https://user-images.githubusercontent.com/60865903/88139088-9f269080-cc0c-11ea-9af7-ffd6a7c538f0.png)

**Comment by nirupamav** [comment]
Observed that email is not sent in V1 when both individual and corporate contributor sign the ICLA

**Comment by nirupamav** [comment]
Needs to be fixed for MVP release

**Comment by dealako** [comment]
@wanyaland can you work on this ticket soon? We have a callback from Docusign where we process the signed complete request.  Once we determine it is indeed signed (by looking at the payload), there is logic for both ICLA and CCLA signature processing. Can you review the ICLA flow/logic and ensure we send a confirmation email to the ICLA that signed the document?

**Comment by wanyaland** [comment]
@nirupamav .
The issue caused here is the GH user having a private email.. Hence with an email in the format ```*.noreply.github.com" In that case user is not receiving an email notification upon signing . Could you try with a public email. 
cc @dealako

**Comment by nirupamav** [comment]
@wanyaland 
Even if GH user is private we are storing all emails in out database. When we have valid email in DB not sure why we are using the `*.noreply.github.com `email

**Comment by nirupamav** [comment]
**Verified that email is sent and able to download the signed PDF**
**_V1_**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/899bb7b6-f357-446b-ba2f-e8305447b2cb)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/d3b531df-0101-48f5-ab13-737ca3d6117c)

**_V2_**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c8802b01-2dc3-4d08-b31f-fafae76a20de)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/88e5d705-2c71-44d1-ab5a-13a87ccfce30)
