### ISSUE TITLE
V2 - Contributor is redirected to EasyCLA V1 homepage when clicked on links in PR

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1246]
**Prerequisite**
1. Create a CLA group with only ICLA enabled
2. Add github repository for the CLA group
3. Generate template

**Steps to Follow**
1. Login to Github as individual contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Individual Contributor
8. Click on SIGN CLA when the button is enabled
9. Complete the docusign process
10. Contributor is redirected to github PR and CLA checks passed
**_Issue1_**
11. Click on CLA Signed button/link
12. Observed that user is redirected to V1 EasyCLA homepage

**_Issue2_**
13. Click on Details link as shown in below screenshot
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/5281000a-1b35-4e01-91bc-a4a16d6df19d)
14. Observed that user is redirected to V1 EasyCLA homepage

**Comment by dealako** [comment]
Is this a setting on the GitHub Bot/App or on the status content??? Niru has noticed that this links to lfcla.com rather than the contributor console that I observed.

**Comment by nirupamav** [comment]
Issue is till reproducible. When l clicked on CLA NOT SIGNED or Details link after getting acknowledged from V2, still we are redirected to V1 landing page
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/0d46bc35-f9cf-40b3-ae6b-14b1457c17ba)

**Comment by dealako** [comment]
Current behavior is fine.
