### ISSUE TITLE
V2 - When the ICLA is already signed, Contributor is able to sign again by clicking link in the email notification of failed CLA checks

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1247]
**_Not sure if it is a valid scenario but logging the ticket for tracking purpose_**

**Prerequisite**
1. Create a CLA group with only ICLA enabled
2. Add github repository for the CLA group
3. Generate template

**Steps to Follow**
1. Login to Github as individual contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Individual Contributor
8. Click on SIGN CLA when the button is enabled
9. Complete the docusign process
10. Open the Email notification for failed CLA check
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/7a964c2f-0024-4dd1-ab38-3acfba638d8f)
11. Click on the link to get authorized
12. Observed the contributor is redirected to contributor console and is able to sign ICLA again

**Comment by dealako** [comment]
Email link is still active after user has previously signed. Maybe check this before user is allowed to re-sign?

**Comment by dealako** [comment]
Won't fix. Out of scope of current product requirements/features.
