### ISSUE TITLE
V2 - Select Company - Search is re triggered whenever user switched between windows using ALT+TAB

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1251]
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group
3. Generate template
4. Company should have signed CLA for the CLA Group

**Steps to Follow**
1. Login to Github as individual contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Enter more than 3 characters for the search criteria
9. Search results are fetched
10. Switch between windows with ALT+TAB key
11. Observed that search is re triggered

**_Also observed same issue when user moves to beginning or end of the search text using HOME and END keys_**

**Comment by amolsontakke3576** [comment]
@nirupamav I have tested on Ubuntu Chrome (Version 83.0.4103.106) and Firefox (77.0.1 64-bit) and look like working fine. Can you provide me steps to reproduce including OS and browser version?

**Comment by nirupamav** [comment]
@amolsontakke3576 
I tested in Windows 10 Chrome. Steps are provided in issue description

**Comment by amolsontakke3576** [comment]
@nirupamav Can you chwck on Mac Safari ? may be it's windows issue and I don't have windows machine to debug this.

**Comment by nirupamav** [comment]
Verified and observed that the issue is fixed
