### ISSUE TITLE
V2 - When clicked on the building icon in Select Company screen the search results drop down is closed

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1252]
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group
3. Generate template
4. Company should have signed CLA for the CLA Group

**Steps to Follow**
1. Login to Github as individual contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Enter valid search criteria
9. Search results are displayed
10. Click on the building icon
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/14ed5cb7-da60-43be-b3a4-7f29ce93db3d)
11. Search results drop down is closed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/571a44c8-afd5-4a02-a47a-256b404d8da3)

@pranab-bajpai 
Should the building icon clickable? If so what action needs to be performed when clicked on the icon

**Comment by pranab-bajpai** [comment]
We want the drop down to populate again after clicking on building icon

**Comment by nirupamav** [comment]
Observed that after search results are populated, drop down is closed when clicked on building icon and drop down is displayed when again clicked on building icon
