### ISSUE TITLE
V2 - There is no option to clear search criteria

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1254]
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group
3. Generate template
4. Company should have signed CLA for the CLA Group

**Steps to Follow**
1. Login to Github as individual contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Observed that there is no option to clear search criteria

@pranab-bajpai 
From usability perspective user should be able to clear search criteria. Could you please confirm if we need an option to clear search criteria

**Comment by pranab-bajpai** [comment]
I think this behavior is fine.
