### ISSUE TITLE
V2 - Info is not displayed to indicate that the company does not exists/no data found when there are no search results in Select Company

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1255]
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group
3. Generate template
4. Company should have signed CLA for the CLA Group

**Steps to Follow**
1. Login to Github as individual contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Search for a company that does not exist
9. Observed there are no search results and there is no info displayed to user indicating that the company does not exist
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/f3e5c38c-9338-42c9-870b-c9cde732902c)

@pranab-bajpai 
Could you please provide the info that needs to be displayed to indicate the user that the company does not exist/no data found

**Comment by pranab-bajpai** [comment]
There are 2 situations
1. When user doesn't type minimum 3 characters, you should show a message in the dropdown that "Minimum 3 characters are required to search company name"
2. When the user clicks on building icon after providing 3 or more characters and if the search returns empty show the message "Could not find any matching company"

**Comment by nirupamav** [comment]
**Tested and observed below issues**
1. As per point 1 above, when minimum 3 characters are not types then "Minimum 3 characters are required to search company name" should be displayed but when no search criteria is provided (which is less than 3 characters) "Could not find any matching company" message is displayed. Since the search value is not entered by user this message might mislead the user to understand that there are no companies
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/f4bbf9ee-60ba-4b32-a411-1288ee637bc6)


**Working scenarios**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/2bc61f2d-5022-4c99-ad2d-c5f679520db0)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a3719137-dfe8-4c75-a20d-e196dfc09791)

**Comment by amolsontakke3576** [comment]
@nirupamav : what error message you expect when there is no search by user?

**Comment by nirupamav** [comment]
@amolsontakke3576 
Minimum 3 characters are required to search company name

**Comment by nirupamav** [comment]
**Verified that the issue is fixed and hence moving the ticket to QA Done**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/2cdaa266-786f-416d-b641-ca8a7994ae51)
