### ISSUE TITLE
V2 - Contributor has to request for authorization even when contributor is already added to approved list

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1257]
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group
3. Generate template
4. Company should have signed CLA for the project
5. Contributor should be added to the approved list for the project

**Steps to Follow**
1. Login to Github as individual contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Search and Select the Company
9. Click Proceed
10. Contributor has to Request Authorization even if the contributor is already added to approved list

@pranab-bajpai 
This scenario is not included in the PRD. Could you please provide the design for the scenario when contributor is  already whitelisted. We need design and explanation for below sceanrios
1. Corporate Contributor has to sign ICLA (when the check box for employee to sign ICLA is also checked)
2. Corporate does not have to sign the ICLA and can proceed with contribution

**Comment by pranab-bajpai** [comment]
Let's discuss with @dealako

**Comment by nirupamav** [comment]
@dealako 
Test data used
company(BAKBONE) 4d9c760b-f5b3-4fe6-89b8-f7d9bd4d965c
CLA Group(ICLA CCLA Group) e2923e14-9d3d-4326-ae1e-00a198125e6f
Foundation (The Presto Foundation Fund) a092M00001IfCa5QAF

![image](https://user-images.githubusercontent.com/60865903/85432111-1b8f6a80-b5a0-11ea-8068-59236eb01a7c.png)

![image](https://user-images.githubusercontent.com/60865903/85432147-29dd8680-b5a0-11ea-9923-357119e69c4e.png)

**Comment by nirupamav** [comment]
**Testing In Progress. Logged below bugs** 
#1319

-

**Comment by nirupamav** [comment]
Testing is blocked due to #1319

**Comment by nirupamav** [comment]
Testing is blocked due to #1448, #1411

**Comment by nirupamav** [comment]
All scenarios passed for github flow except for scenario for contribution when githuborg is whitelisted. Issue is tracked in #1498 and hence closing this ticket
