### ISSUE TITLE
V2 - Contributor is redirected to Select Company screen when clicked on Exit EasyCLA button

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1260]
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group
3. Generate template
4. Company should have signed CLA for the project

**Steps to Follow**
1. Login to Github as individual contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Search and Select the Company
9. Click Proceed
10. Click on Request Authorization for the CLA Manager
11. Request Submitted dialog is displayed
12. Click on Exit EasyCLA button
14. Again Click on Exit EasyCLA button in Request Authorization to Contribute
13. Contributor is redirected to Select Company

@pranab-bajpai 
Since there is no redirection to github page, contributor has to navigate back in the browser or has to launch github again to work on the repository. Also GO BACK button is provided to go back to Select Company screen. So should the contributor be redirected to github PR page instead of select company screen after following above steps

**Comment by pranab-bajpai** [comment]
This issue is same as #808 in V1, we need same behavior.

**Comment by nirupamav** [comment]
Verified that contributor is redirected to Github from Request Authorization to Contribute screen when clicked on Exit EasyCLA
