### ISSUE TITLE
V2 - Contributor is able to click on GO BACK button and navigate to previous screen when Authorization request is in process

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1263]
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group
3. Generate template
4. Company should sign CLA for the CLA Group

**Steps to Follow**
1. Login to Github as individual contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Search and Select Company
9. Click Proceed
10. Click on Request Authorization link for the CLA Manager
11. While the request is in process, click on GO BACK button
12. Observed that contributor is navigated back to Select Company screen and Request Submitted button is displayed in the Select Company screen (When clicked in Exit EasyCLA button contributor can see Select Company screen)

**Comment by amolsontakke3576** [comment]
@nirupamav Fix is alrady in ticket #1241.

**Comment by nirupamav** [comment]
Verified that no action is performed when clicked on GO BACK while Authorization request is in process
