### ISSUE TITLE
V2 - No CLA manager found info is displayed when Request Authorization to Contribute is still loading

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1264]
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group
3. Generate template
4. Company should sign CLA for the CLA Group

**Steps to Follow**
1. Login to Github as individual contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Search and Select Company
9. Click Proceed
10. Observed that **No CLA manager found** info is displayed when Request Authorization to Contribute is still loading
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/340c8fb6-473c-4117-af77-4b8ff729aed2)

@pranab-bajpai 
Should that info be shown as I guess there will not be a scenario where CLA Manager is not available when company has signed CLA? If this info should not be displayed how should this be handled?

**Comment by dealako** [comment]
@amolsontakke3576 work with @pranab-bajpai and @nirupamav to resolve this.

**Comment by amolsontakke3576** [comment]
@dealako @pranab-bajpai It is related to the handled error from API side. It's small one, so I will fix it.

**Comment by nirupamav** [comment]
Verified that the issue is fixed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/cace0a5d-18f6-46aa-9ce9-f3719dd70149)
