### ISSUE TITLE
Retrofit v2 Foundation and Project APIs with Project CLA Groups Mapping

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#1267]
## Summary

Retrofit v2 Foundation and Project APIs with Project CLA Groups Mapping

## Background

We need to review existing v2 APIs that were generated before the CLA Group mapping table was added. These APIs need to leverage the new table and ensure the records are updated and queried as needed.

Scope/Endpoints:

- [ ] ....
- [ ] ....

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

- Related to CLA Migration Script: https://app.zenhub.com/workspaces/lfx-easyclav2-5ed619832c71a855a76ef404/issues/communitybridge/easycla/1265
- Related to CLA DEV Database Cleanup: https://app.zenhub.com/workspaces/lfx-easyclav2-5ed619832c71a855a76ef404/issues/communitybridge/easycla/1266

**Comment by nirupamav** [comment]
@pranab-bajpai 
cc: @prasannamahajan 
In scenario where there is 1 project for a foundation and there is a cla-group for the project, Should we display foundation name or project name in Foundation Dashboard. As of now project name is displayed.
In LFX user is can see data only in Foundation Dashboard in this scenario and Project name is displayed. Could you please let men know what is the expected behavior in this case

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/9af12885-7753-494c-a115-0ffe1e95056f)
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/82b9e363-c37f-405c-8b94-6024f9798405)

**Comment by nirupamav** [comment]
Testing In Progress
So far tested below endpoints
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/getCompanyProjectCla
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/getCompanyProjectActiveCla
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/getCompanyProjectEvents
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/getCompanyProjectClaManagers

**Comment by nirupamav** [comment]
Testing of https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/getCompanyProjectContributors is blocked due to below bugs
#1411, #1319

**Comment by nirupamav** [comment]
Observed that below endpoints return 400 below response when CLA Group is at project level and projectSFID is passed to the endpoints. I we pass parent projectsfid (foundationsfid) then it returns data
```
{
    "Code": "ValidationException",
    "Message": "ValidationException: One or more parameter values were invalid: Condition parameter type does not match schema type\n\tstatus code: 400, request id: S7V9U7BOUL44290UJVP1B1PRGNVV4KQNSO5AEMVJF66Q9ASUAAJG"
}
```

https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/getCompanyProjectCla
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/getCompanyProjectActiveCla
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/getCompanyProjectEvents
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/getCompanyProjectClaManagers
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/getProjectCompanySignatures

**Comment by dealako** [comment]
Resolved these issues. Closing ticket.
