### ISSUE TITLE
Request all CLA Managers 

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#1270]
![image](https://user-images.githubusercontent.com/57362064/84906307-5ad92b00-b077-11ea-8574-c2a194e8d630.png)
In this screen we need to provide a link called "Send Request to All CLA Managers" that will send the email to every CLA Manager in the list.

**Comment by wanyaland** [comment]
@pranab-bajpai Could you assist with the content to send to the cla managers ?

**Comment by nirupamav** [comment]
Send Request to All CLA Managers link is not displayed and hence reopening the ticket
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/4fa7a451-2240-4b0c-bd4f-1a5ba8e6c4cf)

**Comment by nirupamav** [comment]
Tested in #1197 and hence moving the ticket to QA Done
