### ISSUE TITLE
Need a button to ExitEasyCLA on the main page

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#1271]
![image](https://user-images.githubusercontent.com/57362064/84906589-c3c0a300-b077-11ea-8f92-191b2842f784.png)
on this page at the bottom provide the ExitEasyCLA button that will take the user back to where they came from (Gerrit or GitHub)

**Comment by nirupamav** [comment]
@pranab-bajpai 
Completed Testing. Could you please review the test plan and let me know if I missed any test scenarios
**TestPlan** - https://confluence.linuxfoundation.org/display/PROD/V2+-+Contributor+Console+Homepage+Test+Plan

**Comment by dealako** [comment]
Exit button was added.
