### ISSUE TITLE
Employee has to be somehow added to EasyCLA V1 database before adding him/her as CLA Manager

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1276]
**Company Admin creation**
1. Launch LFX Portal
2. Create an user account
3. Assign company admin role for a company to the user in IAM 

**Contributor creation**
1. Launch LFX Portal
2. Create an user account
3. Assign contributor role for a company and project to the user in IAM 

**Add CLA Manager flow**
1. Launch LFX Portal
2. Login as contributor created above
3. Click on the project that has not signed CLA
4. Complete the Signing process (There is a bug where cla-manager role is not assigned to user after signing CLA from LFX portal. So after CLA is signed add CLA Manager role for the user in IAM)
5. Now Try to add the company admin created above as CLA Manager
6. Request is sent for the company admin to create LFID even if the user already exists in user service. 
As a workaraound I logged with the company admin credentials in V1 corporate console for the user to get added to users table in V1 database, and after this I am able to add company admin as cla manager

**Comment by dealako** [comment]
@wanyaland added to current sprint.

**Comment by wanyaland** [comment]
@nirupamav Will add user to the CLADB table for users. But that wasnt a workaround as the user-service that checks for users does not need EasyCLA Database. It just checks lfxUsers. I corrected that check with email search in the PR that has been merged so you could test this workflow just to clarify .

**Comment by dealako** [comment]
@wanyaland is this fix pushed to DEV? Can we move this to QA review for @nirupamav

**Comment by wanyaland** [comment]
Yes @dealako  this is in Dev

**Comment by nirupamav** [comment]
**Verified and observed that the issue is resolved**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/d138eee9-8c7b-47da-935b-e6cd2fed5046)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/81f77197-fe5b-458d-ae6a-7ba1023eea40)
