### ISSUE TITLE
[PRODUCTION] CLA Check passing incorrectly

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#1278]
## Summary
The EasyCLA check at the bottom of the pull request shows a success, but the comment shows that the bot has not been authorized.

https://github.com/open-telemetry/opentelemetry-go-contrib/pull/73

## Background

A user who is authorized commits in a pull request with a user who is not authorized. The check will pass even though the unauthorized user does not sign a cla.
## Expected behavior

All users of all commits should have a signature entry found before the check passes.

https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/lambda/cla-backend-prod-githubactivity;stream=2020/06/17/%5B$LATEST%5Decc239d8ec6e4a06b5a32303b8ac757a;refid=35511840414099068059978303930337511847775770619291959317;reftime=1592405998004

**Comment by dealako** [comment]
Read for further testing and confirmation.

**Comment by WillsonHG** [comment]
Fixed for the above scenario but now comment is not being updated after user1 signs.

1. user1 creates pr, hasn't signed, is gated
1. user2 commits to same pr and has already signed, 
1. comment correctly updates with user1 not signed, user2 signed. 
1. Check section at bottom correctly states not passed.
1. user1 signs icla. 
1. check section at bottom correctly states all checks passed
1. comment incorrectly still states user1 not passed - comment is not updated after multiple refreshes

**Comment by dealako** [comment]
Created PR: https://github.com/communitybridge/easycla/pull/1281/files#diff-571200c2978afc08a6ab65c52919d792L905 and merged

@WillsonHG configured the fix in DEV.
