### ISSUE TITLE
V2 - Appropriate results are not fetched when try to search with value " & "

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1284]
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group
3. Generate template
4. Company should have signed CLA for the CLA Group

**Steps to Follow**
1. Login to Github as individual contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Enter search criteria " & " (excluding double quotes)
9. Observed appropriate search results are not fetched. Also observed that it took around 10secs to load the companies (I was trying to find company **OUAS Raahe School of Engineering & Business** from org service)
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a1595488-d5c0-4a13-9174-89ff70104cb9)

**Comment by nirupamav** [comment]
Below is the Org service bug for this issue 
https://jira.linuxfoundation.org/browse/PMM-657

**Comment by dealako** [comment]
Thanks! Let's close this issue as it's not related to EasyCLA API or UI.
