### ISSUE TITLE
V2 - Company Already Exist message is displayed even if company does not exist

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1285]
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group
3. Generate template

**Steps to Follow**
1. Login to Github as individual contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Search for company "hershy's"
9. Observed that company does not exist
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/6ae37a46-f3b6-4957-a924-770c748fc495)
10. Click on **+ Click Here** button
11. Try to add company used in Step 8
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/477af652-cddd-4f5d-b7e0-cb611fd59ca3)
12. Click Next 
13.Company already exist message is displayed even if company does not exist
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/fc61be89-5334-4482-9a8b-6325d70f9fb5)

**Comment by amolsontakke3576** [comment]
@wanyaland Can you please look this

Request URL: https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/user/d3b74e07-ce7c-42b7-abe4-6e9acc7ee402/company

Input `{"companyName":"hershy's","companyWebsite":"http://www.testnvelagap123.com"}`

Response :` {"Message":"unknown error (status 422): {resp:0xc001c64e10} "}
`

**Comment by wanyaland** [comment]
This could be a use case of company name having apostrophes and not being added by the organization-service. Will clarify with the acs team on this issue

**Comment by wanyaland** [comment]
So the name is not valid . On testing the endpoint it returned 
"message": "Name in body should match '^([\\w\\d\\s\\-\\,\\./]+){2,255}$'". That implies apostrophes are not allowed

**Comment by nirupamav** [comment]
Not able to test this flow as there is a client side validation which is not allowing me to add company with special characters and hence reopening the ticket
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/d490a5f3-a6e1-4bf9-b21a-85bdb7115542)

**Comment by amolsontakke3576** [comment]
@dealako  @nirupamav @wanyaland I have set the regex you mentioned in the above comment. and as per this `.` `,` and `-` are only allowed special characters. If you want to allow more then we have to change regex from both (backend and frontend) side.

**Comment by dealako** [comment]
I submitted a PR to the Org Service to expand the regex: https://github.com/LF-Engineering/organization-service/pull/150.  Also, the UI needs to match.

All services should follow the same allowed regex pattern:

- EasyCLA API
- Platform Org Service
- EasyCLA Contributor Console
- LFX???
- Funding

**Comment by nirupamav** [comment]
@amolsontakke3576 @wanyaland 
What is the regex that is accepted now so that I can test accordingly

**Comment by nirupamav** [comment]
As discussed with @amolsontakke3576 the regex needs to be implemented from front end and hence moving the ticket to In Dev

**Comment by wanyaland** [comment]
The regex was implemented on the backend as well > '^([\w\d\s\-\,\./]+){2,255}$'

**Comment by nirupamav** [comment]
**Observed that the issue is still reproducible. Organization is not found/regex not accepted in contributor console but is available in Org service**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/57f7f022-b5e4-4b6a-b5d7-ea00842f5798)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/416fc946-c1e1-4ca3-a561-a6dd39242b76)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/3b4d0301-0eca-43f0-bb6a-ee2ca853cbba)

**Comment by wanyaland** [comment]
@nirupamav . Tested with organization service and apostrophes arent allowed on creation of an org. Probably the given org you state was created a while back before the current regex was effected 
[Uploading... Screenshot 2020-09-02 at 03.21.19.png ]

**Comment by dealako** [comment]
Let's defer this issue until we can coordinate with Organization Service. Apostrophes should be allowed in the org service IMHO.  Seems to be going out of fashion: https://www.washingtonexaminer.com/news/apostrophe-protection-society-shuts-down-because-ignorance-and-laziness-won

**Comment by amolsontakke3576** [comment]
I have updated the regex provided in the swagger. So as per the new regex below is only the valid case
`Organization name may only contain alphanumeric characters or special characters -,.` 

So the issue is no longer valid.

**Comment by manishv09** [comment]
Validated the issue in reference to Amol's comment and now is restricted to use " -,." else error message mentioned above which is "Organization name may only contain alphanumeric characters or special characters -,." is displayed to the user

![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/d05157d9-0f2d-45fe-869f-25a4f03090e7)

**Comment by swinslow** [comment]
Why would we not permit company names to have an apostrophe in them? If the company's name actually has an apostrophe, why would we prohibit them from using their company name?
