### ISSUE TITLE
V2 - Observed that Enter Company Name accepts any number characters and appropriate error message is not displayed when create company fails

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1286]
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group
3. Generate template

**Steps to Follow**
1. Login to Github as individual contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Click on + Click Here button
9. Add company with below details. Observed that appropriate error message is not displayed. However API returns appropriate response
**Name** The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation The mission of the Academy Software Foundation 
**URL**  https://test.com
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/f6071b47-469a-47d8-83c6-7233feb26ee1)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/29e882d7-be52-4a45-b684-267a14cf15bf)

**Comment by nirupamav** [comment]
@amolsontakke3576 
Could you please let me know the min and max length that you set for the company name

**Comment by amolsontakke3576** [comment]
@nirupamav As per `organization-service`, max length capacity is 255 characters but It is creating problem on DocuSign page. So I kept max length 60 characters and minimum length now is 1 but just cross verified from organization service and it should be 2. I will update length.

**Comment by nirupamav** [comment]
@pranab-bajpai 
As per above comments org service accepts 255 characters to create company but since we have issue displaying long company in docusign @amolsontakke3576 has kept the length to 60 characters. Could you please confirm if this is fine

**Comment by nirupamav** [comment]
As discussed with @pranab-bajpai max length for company is 60 characters
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/e2ba248f-255b-4b1c-a707-1417c76cb7c2)

Min length is 2 characters
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/96176e12-a2b3-420b-bb59-8dd819d6ec81)
