### ISSUE TITLE
V2 - Not able to add company name that is starting with digit or special character

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1287]
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group
3. Generate template

**Steps to Follow**
1. Login to Github as individual contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Click on + Click Here button
9. Not able to add company name that is starting with digit or special character (I have given examples of real time companies)
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/6711af08-d15a-4d7f-85c6-bb62f0ccfeb8)
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/b4b20f4c-53f8-43bf-a3e6-b16706063812)

**Comment by amolsontakke3576** [comment]
@nirupamav As per discussion with @wanyaland, only alphanumeric character with space and dash(-) are allowed

**Comment by nirupamav** [comment]
@pranab-bajpai @dealako 
These are real time company names. We might get the companies that start with special characters or digits. Could you please look into this issue

**Comment by nirupamav** [comment]
@amolsontakke3576 
Reopening the ticket as the regex needs to changed as per the discussion in standup call

**Comment by dealako** [comment]
I will work to normalize the regex allowed by:

1. Org Service API
1. Contributor Console UI v1/v2
1. LFX UI
1. EasyCLA V1 UI

Examples from PROD:

- 1&1 Mail & Media Development & Technology GmbH
- 1stdibs
- 3Rein, Inc.
- 56K.Cloud
-   上海道客网络科技有限公司
-   合肥北明网络科技有限公司

**Comment by amolsontakke3576** [comment]
I have updated the regex provided in the swagger. So as per the new regex below is only the valid case 
`Organization name may only contain alphanumeric characters or special characters -,.`

confirmed the same from @nirupamav so closing the ticket.
