### ISSUE TITLE
API to return Foundation(s) & its CLA Groups 

### ISSUE THREAD

**Issue by vinod-kadam** [communitybridge/easycla#1290]
Need an API to return all Foundation & their CLA Groups.
And should provide for foundation filter so that information related to one foundation can be queried.

**Comment by prasannamahajan** [comment]
Response should be like:
`{
  "list": [
    {
      "foundation_sfid": "cncf_sfid",
      "cla_groups": [
        {
          "cla_group_id": "cgid",
          "project_sfid_list": [
            "sfid1",
            "sfid2"
          ]
        }
      ]
    }
  ]
}`

**Comment by dealako** [comment]
API might Look Like:

GET /v4/foundation-mapping                                  # returns all foundation/project mappings
GET /v4/foundation-mapping?foundationID=abc  # returns foundation/project mapping for specified foundation

See the response example above.

**Comment by nirupamav** [comment]
**_Tested and observed that user with role other than EasyCLA role is able to access the endpoint_**
Tested with below roles
only user role
mentee role

**Comment by prasannamahajan** [comment]
@nirupamav 
1. This api is used for foundation landing page. 
2. Since every authenticated user will have user-role, I have provided access of this api to user role.
3. this api does not provided any sensitive-info.

**Comment by nirupamav** [comment]
@pranab-bajpai 
Could you please confirm if this is endpoint can be accessed by any user with any role

**Comment by dealako** [comment]
Let's close.

**Comment by nirupamav** [comment]
@pranab-bajpai 
Testing is completed. Could you please review the test plan and let me know if I missed any scenarios
https://confluence.linuxfoundation.org/display/PROD/EascyCLA-V2-+Foundation+Mapping+Test+Plan
