### ISSUE TITLE
Can't get signed CLA for company

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#13]
<a href="https://github.com/caniszczyk"><img src="https://avatars1.githubusercontent.com/u/63777?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [caniszczyk](https://github.com/caniszczyk)**
_Wednesday Jul 03, 2019 at 14:49 GMT_
----

in Tekton, go to https://project.lfcla.com/#/project/a092M00001G3xhxQAB/cla

Select Corporate CLA, see the list of companies, find IBM, you click but don't see the signed PDF.

**Comment by jpalmerLinuxFoundation** [comment]
Currently, signed CLAs are not available via the consoles. We do have this in our backlog, however.

**Comment by dealako** [comment]
Unable to reproduce for Tekton. Closing this issue during our backlog review. If additional help (be specific) is needed then please create a new ticket.
