### ISSUE TITLE
Change Company to Organization and follow the wireframe to use "Your Organization" where ever it says "Your Company"

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#1302]
Creating a general issue to replace the word "Company" with "Organization" and to follow closely where ever the wireframe says "Your Company" we say "Your Organization" in our implementation.

Here is the link to wireframe - https://wireframepro.mockflow.com/view/app-easycla#/page/Dab111f6a971bc1cd42c819a1770bc817

**Comment by nirupamav** [comment]
**Verified in below screens and observed that Company is replaced with Organization**
Contributor Console Home page
Select Organization screen
Enter Organization Details dialog
Request Authorization screen

**_Could not test other screens as they are not yet available for testing_**

**Comment by nirupamav** [comment]
Company is displayed instead of organization in below places
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/30dbafbb-2470-40d0-8135-71a303a2272e)

**Comment by nirupamav** [comment]
**Tested and observed that in below screens company is displayed**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/09e700af-b8ca-42df-8714-af4eef8a8f4f)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/186ecea6-c54e-4c98-a571-d2943988e356)

**Comment by amolsontakke3576** [comment]
@nirupamav I had a discussion on it with @pranab-bajpai and `Company-Admin` is a role so we kept this as it.

**Comment by nirupamav** [comment]
Verified that the issue is fixed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/b01d1e17-0248-4001-88db-6eb7904fe494)
