### ISSUE TITLE
V2 - CLA group name is displayed instead of project name in email sent for LFID creation

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1305]
CLA group name is displayed instead of project name in **EasyCLA: Invitation to create LFID and complete process of becoming CLA Manager** email notification
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c93177fe-80b3-4a44-a3a2-f28f0c5463c1)

**Comment by wanyaland** [comment]
Verified this is fixed. The endpoint in question is /company/{companySFID}/project/{projectSFID}/cla-manager/requests and this uses the salesForce project name in the email body for users with no LFID

**Comment by manishv09** [comment]
I verified this and found the template has been changed, hence now this is not a relevant bug. Closing now. Please find new template email generated attached.
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/74f14dac-5323-4bdc-81ad-2ba10a233d53)
