### ISSUE TITLE
V2 - Issues with the email sent to signatory after signatory has signed the CLA document

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1307]
Below are the issues with the email sent to signatory after signatory has signed the CLA document

**Issue1 - Completed email sent to Signatory still includes the content which informs Signatory to sign document**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/398c2000-aed2-4b03-976a-f0ec8ad1041f)

**Issue2 - EasyCLA: Signed Document email is sent to company owner who created the company and also signed document is not attached in the email**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/2c7211ab-4991-4485-9b49-70a14aeec2c6)

**Comment by vinod-kadam** [comment]
@wanyaland  please check this one - it might have been taken care already.

**Comment by vinod-kadam** [comment]
@rinkeshbhutwala  updated me after checking with @wanyaland. Following is my understanding.
Now, following email is sent to the user.
![image.png](https://images.zenhubusercontent.com/5e9e9952b186e1325cf5608a/05dba26f-c21a-4a69-874e-7ee176ef0ba5)
So, it doesn't seem to be an issue. So, moved this ticket to Ready for QA.

**Comment by vinod-kadam** [comment]
As updated by @dealako in 4-Dec standup, he has fixed it however pending dev testing.

**Comment by dealako** [comment]
@wanyaland the first email should be a confirmation email sent by Docusign after successful signing.  The email content is not correct.  The email content that is sent is currently working as I have updated the formatting for this and Heather has confirmed. This is sent for CLA Managers who request a given CLA Signatory to sign the PDF document in DocuSign from the corporate console.

When the document is signed by the CLA Signatory, we should have a well-formatted success email with the download link.  Please review this and resolve the ticket.

**Comment by wanyaland** [comment]
@dealako Tested the scenario where a request is made to CLA signatory and after CLA signatory signs and the email content is as expected. 
Upon signing 
<img width="649" alt="Screenshot 2020-12-05 at 02 43 03" src="https://user-images.githubusercontent.com/2846731/101226213-ca35ec00-36a4-11eb-8b29-3ab3f95d0fd3.png">
CLA Signatory Request
<img width="642" alt="Screenshot 2020-12-05 at 02 52 15" src="https://user-images.githubusercontent.com/2846731/101226235-e46fca00-36a4-11eb-8d3d-faae9a567468.png">

**Comment by manishv09** [comment]
Verified issue today and found that user receives the below email :
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/7258f46d-b746-4162-997a-41f02cad1c36)
But gets error 500 when finish button is hit on docusign:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/ac42f6b6-3da2-4527-ad97-8279b3714137)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/b07a9f73-c2bf-4ca5-91e3-ad47fc59dd25)

**Comment by vinod-kadam** [comment]
As updated by @wanyaland  internal server error has been fixed and is now available on Dev & Staging.

**Comment by ashav-github** [comment]
@wanyaland @vinod-kadam Tested on Stage and CCLA is getting signed successfully without any error. 

![image.png](https://images.zenhubusercontent.com/5f6b335ce9044e3973ea11f9/6a317248-2136-40e5-b9ba-272fa341173e)
