### ISSUE TITLE
V2 - User able to Start the CLA signing process for CLA group that has only ICLA enabled

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1308]
1. Launch https://lfx.dev.platform.linuxfoundation.org/
2. Login with user having access to the Cloud Native Computing Foundation and Bakbone company
3. Expand Cloud Native Computing Foundation
4. Click on any project that has only ICLA enbaled
5. Click on Start the CLA process button
6. Observed that user is able to proceed with signing. However it fails at Document generation step

Change is required from API end. I am assuming below endpoint require the changes to fetch only projects for which CCLA is enabled but not sure if it is the correct endpoint
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/getCLAProjectsByID

**Comment by dealako** [comment]
Adding flags to response for:
- CCLA Enabled
- ICLA Enabled
- CCLA Requires ICLA Enabled

**Comment by dealako** [comment]
Pushed PR: https://github.com/communitybridge/easycla/pull/1312

GET http://localhost:8080/v4/project/enabled/a09410000182dD2AAI

**Comment by dealako** [comment]
LFX can now review the response and determine if they should allow the user to select ICLA/CCLA, for example.

**Comment by nirupamav** [comment]
Verified that below flags are returned in the response
ccla_enabled
ccla_requires_icla
icla_enabled

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/3834a179-a7ce-402a-ae25-957e6e2d78bf)
