### ISSUE TITLE
V2 - Contributor is still gated even when contributor is whitelisted and when contributor does not require to sign ICLA

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1319]
**Prerequisite**
1. Create a CLA group with **only CCLA enabled**
2. Add github repository for the CLA group
3. Generate template
4. Company should have signed CLA for the project
5. Contributor should be added to the approved list for the project

**Steps to Follow**
1. Login to Github as individual contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Search and Select the Company
9. Click Proceed
10. You are done message is displayed but still the contributor is gated
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a100a81f-0166-451a-97ec-b6e2fc56df19)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/bda7c22f-2507-4150-a81a-704dd2a1dd5d)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/3424c2da-5617-4b56-a2c4-c32394a5080f)

**Comment by amolsontakke3576** [comment]
@wanyaland Can you check this and also can you change success message as per our discussion.

**Comment by nirupamav** [comment]
**Issue is still reproducible**
https://github.com/nvelagap/ccla_NoEmployeeSign_presto/pull/1
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/ce7cc3e7-b217-4347-a632-4bd96f65bad7)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/3924cdd8-781c-44d8-a5d0-74173f79a6e3)

**_Waited for 30mins but still the status was CLA NOT SIGNED_**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/e05953f3-81ee-4dc4-9b19-2152a0d9b106)

**Comment by wanyaland** [comment]
@amolsontakke3576  the workflow for this use case requires 
1. checking if contributor can sign -> v2/check-prepare-employee-signature
2. Then requesting contributor to sign -> v2/request-employee-signature.
For this case you only invoked the check endpoint which actually doesnt implement the signing process

**Comment by dealako** [comment]
@amolsontakke3576 can you look at this one, please? Thanks!

**Comment by nirupamav** [comment]
**Verified that the issue is fixed**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/7a1ec3f9-652d-4505-9a48-dfa282b5b6e1)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/673cd9c4-2525-4643-9e9f-da6862657ce1)

**After acknowledgement contributor is not gated and is able to contributor without any issues**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/8accf4a6-deba-4923-a747-461f8fa2b1fd)
