### ISSUE TITLE
api to get signed document url for ccla/icla signature

### ISSUE THREAD

**Issue by prasannamahajan** [communitybridge/easycla#1320]
## Summary

write an api to get signed document url for ccla/icla signature

## Background
When user sign cla we upload that document to s3
provide an api to retrieve that document

## User Story

- As a project manager, I want to retrieve the icla,ccla signed document for my cla-group
- As a cla manager, I want to retrieve the ccla signed document for my company

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. api accept signature_id 
1. response of api is presigned s3 link using which project-manager,cla-manager can download signed document.
1. project-manager able to download signed icla,ccla document for his cla-group
1. cla-manager able to download signed ccla document for his company

**Comment by nirupamav** [comment]
Endpoint to be tested
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/getSignatureSignedDocument

**Comment by nirupamav** [comment]
**Tested and observed that the project-manager of cla group is forbidden to fetch the signed ccla/icla documents**
User has project-manager role in IAM for DPDK Core project 
User has access to the project in cla-dev-user-permissions table in V1 database
Project Name - DPDK Core
Project SFID - a092M00001IV4ARQA1
CLA Group Name - DPDK-Core CCLA_ICLA_EmployeeICLA_Yes
CLA Group ID - 6430f241-f118-4379-9713-beb68e61fedc
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/82b7640e-2fd0-49cd-abbd-d8d357d41afd)

**However as per the user story description, cla-managers of the project are able to fetch only the signed ccla document**

**Comment by prasannamahajan** [comment]
@nirupamav 
I checked it. It is working for project-manager role

**Comment by nirupamav** [comment]
@pranab-bajpai 
Testing is completed. Could you please review the test plan and let me know if I missed any scenarios
Only for nirupamav user (project-manager) endpoint returns 403 and logged bug #1365 to track the issue. Since it is working for other user moving the ticket to QA Done
https://confluence.linuxfoundation.org/display/PROD/EascyCLA-V2-+Get+signed+ICLA+or+CCLA+document+Test+Plan
