### ISSUE TITLE
Contributor Console - Integrate Gerrit Flows

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#1322]
## Summary

Integrate the Gerrit contributor flows into the v2 contributor console.

## Background

Integrate the v1 Gerrit flows into the v2 contributor console.

## User Story

As a Gerrit repository contributor, I want to use the v2 contributor console to authorize myself.
 
## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

\(Optional\) Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by dealako** [comment]
Discussion from slack:

@amolsontakke3576  I spoke to @pranab-bajpai  today on the Gerrit flows. I would like for you to copy the login page idea over to v2. For this page, we want @pranab-bajpai  to create a simple page such that we tell the user that he/she needs to login in order to continue the signing process.  This will have the same behavior as the current v1 login page, but it will look like a design that Pranab will provide (v2 fonts/colors/theme/etc.)
Old Design:

![Screen Shot 2020-06-30 at 12.07.16 PM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/bcc4da0d-c4a2-483b-938e-3b4751d9d4eb)

@amolsontakke3576 Another key point - I will need to make an adjustment to the Python code which provides the initial redirection.  I will add logic that looks at the CLA group version attribute. If the value is v2, I will direct to the new v2 console, otherwise, the flow will continue to v1.
See this bit of beautiful HTML code: https://github.com/communitybridge/easycla/blob/master/cla-backend/cla/controllers/gerrit.py#L134. I will update this code to direct to the v2 console page where you have your new login check (like v1).

**Action for** @amolsontakke3576 : when you are ready, provide me the proper link so I can update the python code.

This is the diagram that we discussed. I sent you an invite to review the document (LucidChart):
![Screen Shot 2020-06-30 at 3.50.30 PM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/9d86d8bd-aa0f-4ae8-9ade-44f28a9b6db4)
// CC @nirupamav

**Comment by nirupamav** [comment]
Testing In progress and logged below bugs
#1581, #1580, #1431, #1430,

**Comment by nirupamav** [comment]
Verified that Gerrit flows are working as expected with few open bugs. Will validate the open bugs once they are fixed
