### ISSUE TITLE
Update CLA in EnabledServices array present in project-service.

### ISSUE THREAD

**Issue by prasannamahajan** [communitybridge/easycla#1327]
## Summary

CLA API should update the EnbledServices array with CLA for a project when the project is added to CLA Group.
- when we add cla-group, we add projects in projects-cla-groups table.
- when entry is added, CLA should be added in EnabledServices.
- when entry is removed, CLA should be removed from EnabledServices.

## User Story

- As a project manager, I want to see the list of cla-enabled project.

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. CLA should be added in EnabledServices when we create cla-group with that project.
2. CLA should be removed from EnabledServices when we delete cla-group.

**Comment by nirupamav** [comment]
@pranab-bajpai 
Testing completed. Could you please review the test plan and let me know if I missed any test case
https://confluence.linuxfoundation.org/display/PROD/EascyCLA-V2-+Update+Enabled+Services+for+Project+Test+Plan
