### ISSUE TITLE
V2 - 400 message is displayed when user with LFID is trying to create company and invite is not sent to the user

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1339]
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group
3. Generate template

**Steps to Follow**
1. Login to Github as corporate contributor **_who has LFID_**
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Click on + Click Here button in drop down in Select Company screen
9. Enter below details
**companyName** newcompanytest5
**companyWebsite** https://newcompanytest5.com
10. Click Next
11. Observed that error message is displayed. However company is created. But Email is not sent to the user with link to update organization profile
**Also observed that the user is not assigned with company owner role*. Checked the role in IAM**

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/3efabdea-7e86-43a1-aac9-e7433250d589)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/83145dfb-114f-4335-909e-c00e0c95f1be)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a7f784d9-d897-4b98-8e5e-1ece9ae321f8)

**Comment by nirupamav** [comment]
**Verified and observed that the issue is fixed**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/9b910a0e-c417-4206-bd20-6af92e85a279)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/efbf3bfc-c8c5-4148-8feb-fee32ca0390b)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a4c4183f-9c6a-45e9-bb3d-c04a65f130ff)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/8fbe9532-2bf1-45ec-b20c-6f9ae28861d8)

**Comment by dealako** [comment]
Thanks!
