### ISSUE TITLE
Log Signature Pass/Fail (Gerrit & GitHub)

### ISSUE THREAD

**Issue by jpalmerLinuxFoundation** [communitybridge/easycla#134]
### Summary
For troubleshooting, we need to know and track when someone makes a commit and fails the check, especially when we have a signature for the user.

### Background
This GitHub EasyCLA user is not able to commit even after signing CLA

**Project: OSQUERY**
cla-prod-users.user_github_id: 5714290 
cla-prod-users.user_github_username: alessandrogario 

Issue: based on the logs, the user failed GH OAuth authorization

**Project: ONAP**
Having issues with EasyCLA telling users that they have not signed a CLA when they are whitelisted. Especially for AT&T.

This user Gerrit was having issues in production

Resolution: user was missing from LDAP which prevented him from passing the CLA checks - need to investigate why he was not added to the group

### User Story

- Log when signatures fail
- Log when LDAP update fails to add a user to LDAP group
- Log and ALERT when a signature check fails, times out, etc. when the user has a signature on DynamoDB

### Acceptance Criteria
Testing is "Done"

- Unit Tests for the code modified are "Done"
- Regression testing task associated with this story marked as "Done"
- Direct testing by someone other than an engineer(s) who developed the code for this story are "Done"
- Resulting Defects are re-tested, resolved, and marked as "Done"

Demo to Product Owner (or delegate)

- Perform the function as described in the user story
- Demo in performed dev environment or higher

**Comment by dealako** [comment]
We will include a comprehensive audit log for EasyCLA v2 which will record all pass/fail events - including signature whitelist or ICLA lookup failure.  We now include a troubleshooting page for CCLA users which helps identify FAQ/issues for EasyCLA bot failures.

Closing this issue during our backlog review. If additional help (be specific) is needed then please create a new ticket.
