### ISSUE TITLE
V2 - Error message is displayed when user without LFID is trying to create company and invite is not sent to the user to create LFID

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1340]
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group
3. Generate template

**Steps to Follow**
1. Login to Github as corporate contributor **who does not have LFID**
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Click on + Click Here button in drop down in Select Company screen
9. Enter below details
companyName newcompanytest6
companyWebsite https://newcompanytest6.com
10. Click Next
11. Observed that error message is displayed. However company is created. But Email is not sent to the user with link to create LFID

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/d3e1ca57-2149-4a4c-bad9-ca3b8156dba1)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/6977f8da-3642-43ea-b344-48fd0e2ae842)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/3c5d08e2-e7ec-4f5c-a04d-f3703ab0d07c)

**Comment by nirupamav** [comment]
**Issue is still reproducible**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/755817b5-e7ea-413c-8604-1fb4811179d7)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/104cccbc-3176-4e50-9372-4673cc09b929)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/9c90ac9d-ee17-4a3d-a3bf-1cd4a502bce2)

**Comment by nirupamav** [comment]
**Verified and observed that the issue is fixed**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c2128586-370a-4092-8287-d16155b79e3a)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/e487fcc8-3f1f-4719-9439-e110d1584f52)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/962c75fa-2a4b-485c-bcea-cc27d36914d2)

**Comment by dealako** [comment]
Thank you!
