### ISSUE TITLE
V2 - Whitelist text is mentioned in No Signed CLA Found dialog

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1360]
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group
3. Generate template

**Steps to Follow**
1. Login to Github as corporate contributor who does not have LFID
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Click on + Click Here button in drop down in Select Company screen
9. Enter below details
companyName Comp2
companyWebsite https://Comp2
10. Click Next
11. Click Proceed
12. Observed that whitelist text is mentioned in the No Signed CLA Found dialog
@pranab-bajpai 
Could you please what should be displayed in the dialog instead of whitelist

**Comment by dealako** [comment]
@amolsontakke3576 was this resolved - if so, let's move to ready for QA.

**Comment by nirupamav** [comment]
Verified that the issue is fixed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/d4e5816d-01da-4611-a44a-54bb403493ed)
