### ISSUE TITLE
V2 - Issues with the email sent to contributor (who is assigned with company-owner role) to complete Oraganization profile

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1361]
Prerequisite
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group
3. Generate template

Steps to Follow
1. Login to Github as corporate contributor (with private email in github) who has LFID
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Click on + Click Here button in drop down in Select Company screen
9. Enter below details
companyName Comp1Jul102020
companyWebsite https://Comp2Jul102020.com
10. Click Next
11. Observed the contributor is assigned with company-owner role and and email is sent to the user to complete organization profile
12. However observed below issues with the email sent
**Issue1**
Email subject is different and needs to be changed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/2fc21865-c678-4b83-b24a-238020fb716d)

**Issue2**
When clicked on the link in the email and logged in, company-owner is redirected to Dashboard instead of Organization Profile page in LFX
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/fb58619c-005a-4785-ae00-fbefdf590ef7)

**Comment by nirupamav** [comment]
**_Tested and observed that Issue2 is still reproducible. When clicked on the link in the email and logged in, company-owner is redirected to Dashboard instead of Organization Profile page in LFX_**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/ea85a90a-f911-4720-9b7a-84d7cbbf785a)

**Verified that Issue1 is fixed**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/6e4f532a-1f16-40bb-b16a-d22d20bcbf2a)

**Comment by wanyaland** [comment]
@nirupamav could you test the redirect again as on my end it goes to the organization profile page

**Comment by nirupamav** [comment]
Testing blocked due to #1683

**Comment by nirupamav** [comment]
Verified that the issues are fixed

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/e9026e1f-b8f5-4bcf-ba39-db5e75b1c611)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/7fdabcba-da2b-4fbe-a29d-0a4e34a150d8)
