### ISSUE TITLE
V2 - Few of the URL formats are not accepted while creating Organization

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1363]
Prerequisite
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group
3. Generate template

Steps to Follow
1. Login to Github as corporate contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Click on + Click Here button in drop down in Select Company screen
9. Observed below url formats are not accepted (Observed there are records in org service with those formats)

**Example1**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/6f21c4ce-bd33-4b05-be6c-ac35077ca4d0)

https://api-gw.dev.platform.linuxfoundation.org/organization-service/v1/orgs/0014100000Te028AAB
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/1debb5c2-5125-4729-897b-b3dcd498f1ea)

**Example2**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/760f99b8-ad59-4638-a854-55791e6422a3)

https://api-gw.dev.platform.linuxfoundation.org/organization-service/v1/orgs/0014100000TdzOGAAZ
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/6ae70b6b-d81d-4e77-8fb7-649ab5a8156c)

**Comment by amolsontakke3576** [comment]
@nirupamav It looks like the URL having `HTTP` and `www` is an optional thing so I will remove this is a validator.

**Comment by nirupamav** [comment]
Based on above comments formats mentioned in the ticket are not supported and hence moving the ticket to QA Done
