### ISSUE TITLE
V2 - User data in contributor console/Corporate Console is fetched from V1 database and not from user service

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1364]
**_Contributor Console_**
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group
3. Generate template
4. Company should have signed CLA for the project and should have more CLA managers
5. Change the name of the CLA Manager from MyProfile link https://myprofile.dev.platform.linuxfoundation.org/

**Steps to Follow**
1. Login to Github as individual contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Search and Select the Company
9. Click Proceed
10. Observed that the CLA Manager Name stored in V1 database is displayed instead of the name from user service
**_Name and primary email from user service should be displayed/used in all pages of V2 contributor console_**

**_Contributor Console / Contributor Console_**
If the primary email  of user is changed and if the user is identified as CLA Manager or requested as signatory or added as CLA Manager, Email notification is sent to the email stored in V1 database and not to the updated primary email
If primary email of the CLA Manager is changed, all approval/removal notifications are sent to the email stored in V1 database and not to the updated primary email

**Comment by amolsontakke3576** [comment]
@wanyaland Can you please look at this? it is related to the backend side.

**Comment by dealako** [comment]
We currently do not have a User Service -> CLA Database sync established.  I recommend we add this POST v2 launch.

**Comment by dealako** [comment]
@rinkeshbhutwala we need to subscribe for User profile update events (when the user updates emails).

Can you investigate this?

**Comment by dealako** [comment]
![EasyCLA Subscribe to MyProfile Events.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/6a839088-6b56-4514-9073-5d4727e72a17)

**Comment by nirupamav** [comment]
@rinkeshbhutwala 
How long does it take to update the data in CLA database after data is updated in user service

**Comment by nirupamav** [comment]
Issue is still reproducible. Waited for 30 mins and still the data was not updated

**Comment by nirupamav** [comment]
**_Tested and observed below issues_**
**1. Only user_name field is updated in CLA DB with updated firstname and lastname. Updated primary email is not updated in CLA database**
`Before updating details in My Profile`
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/4d3c0d62-c128-48a4-b402-0188c14784f7)

`After updating details in My Profile`
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/bb3b1d84-7cd8-44f9-9454-01ffb7b63bf6)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/dc323f9d-3dfe-49bd-b731-95c68b09766a)

**2. After updating details, the user is not able to sign CLA**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/2ac9151e-9291-4845-bf40-6bdb540a81e3)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/b393bf9e-9d50-4c12-8e2b-934455cf4210)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/1a8fe848-12f0-4554-a2be-b480576ab1bf)

**Comment by rinkeshbhutwala** [comment]
@nirupamav I have investigated the issue which you posted looks like changes in email like adding a new alternate email or change the Primary email we didn't get any SNS event for the same that's why it's not updated in our cla database.

@dealako I already discuss with Yogesh, He is working on that part to sending an event for the same once the event is come up it will work fine.

**Comment by nirupamav** [comment]
**_Tested below scenarios in V2_**
**1. Created a new user**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/1782d3bb-837e-48ea-a930-8f01de44898a)

**2. Updated user first name and lastname. Observed that update name is updated in cla database and able to view the updated name in docusign, Corporate console, Contributor console and email notifications**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/ce489870-0d20-4239-a399-7d623e755573)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/6928c340-87de-4a70-bab9-92e7ddb142aa)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/f7734360-6180-4752-8e3c-b1427e55aa27)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/fef9ce16-a8e0-40c9-a364-5239dcd8cc0c)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/001be5d9-5924-4bc7-b7fd-1fd217cb5623)

**3. Add alternate email. Observed that alternate email is updated in database and primary email is used in cla flows**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/37dafb23-e21d-4b8f-95d1-045e42b1ae75)

**4. Made alternate email as primary and viceversa. Observed that primary email is updated in database and primary email is used in most of the cla flows and in few flows observed issue which is tracked in #1971**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/e64a7ee0-5cac-485b-9d31-569c02c85530)

**5. Delete alternate email. All CLA flows are working fine**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/7899c2c9-5ae8-469b-b903-b3fb9cf01f5e)

**Comment by nirupamav** [comment]
Testing Blocked due to #2032

**Comment by nirupamav** [comment]
Logged below tickets
#1971
