### ISSUE TITLE
V2 - Only nirupamav user (project manager) is not able to fetch signed CCLA/ICLA document

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1365]
**Observed that the only nirupamav user(project-manager) of cla group is forbidden to fetch the signed ccla/icla documents. It is working fine with other users**
User nirupamav has project-manager role in IAM for DPDK foundation
User has access to the project in cla-dev-user-permissions table in V1 database
Project Name - DPDK Core
Project SFID - a092M00001IV4ARQA1
CLA Group Name - DPDK-Core CCLA_ICLA_EmployeeICLA_Yes
CLA Group ID - 6430f241-f118-4379-9713-beb68e61fedc

**_Endpoint for CCLA_**  https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/signatures/91d68b67-f992-4c46-8113-c46e68f3ce45/signed-document
**_Endpoint for ICLA_** https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/signatures/e2a5ae82-ac5c-41f5-89a2-9173ac12f045/signed-document

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/82b7640e-2fd0-49cd-abbd-d8d357d41afd)

**Comment by prasannamahajan** [comment]
Root cause:
We were not checking the admin permission in the api.
and if user have system-admin role then api-gw does not write individual scopes instead it just write admin flag as true.

**Comment by nirupamav** [comment]
Verified and observed that the issue is fixed and also performed regression to check if other scenarios are working as expected
