### ISSUE TITLE
V2 - Able to assign cla-manager-desginee role for already signed project through API

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1368]
**Observed that through API we are able to assign cla-manager-desginee role for already signed project
Tried for below data**
Project Name - DPDK Core 
Project SFID - a092M00001IV4ARQA1
CLA Group Name - DPDK-Core CCLA_ICLA_EmployeeICLA_Yes
CLA Group ID - 6430f241-f118-4379-9713-beb68e61fedc
praj - contributor for the project (used this user's authorization token and email in the endpoint)
Observed that post was successful and praj was assigned with cla-manager-designee role

**Comment by dealako** [comment]
Once we have a CLA Manager configured for a given CLA Group/Project - do not allow users to become designees and sign.  Once a CLA Manager is established, he/she must add them through the corporate console.

**Comment by nirupamav** [comment]
Observed a regression issue where in always "project already signed" is returned even when there is no signature. Issue is tracked in #1107
Testing is blocked due to this issue

**Comment by nirupamav** [comment]
**_Tried with below 2 endpoints and observed that we are able to assign cla-manager-designee role for a user for already signed Project and Organization_**


**https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company/0014100000Te0iaAAB/project/a092M00001IfR9lQAF/cla-manager-designee**
**https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company/0014100000Te0iaAAB/project/a092M00001IfR9lQAF/cla-manager/requests**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/f1c8c9e3-0002-4938-b845-5e474fee1277)
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/069bbba3-9368-4152-9c10-8fc4d81b36bd)
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/7bd3b0ae-97bc-4951-acec-505dd88cdb93)

**Comment by nirupamav** [comment]
**500 Internal server error is returned for cla-manager/requests endpoint**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a781a53b-6715-4646-8d18-74afa861d59f)

**Issue is fixed for cla-manager-designee endpoint**
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company/00117000018BhtKAAS/project/a091700000AGJ5EAAX/cla-manager-designee
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/3039e464-6dfd-4652-93c6-fe9501bfb543)

**Comment by wanyaland** [comment]
@nirupamav the cla manager request issue was fixed .. reference https://app.zenhub.com/workspaces/easyclav2-5ed619832c71a855a76ef404/issues/communitybridge/easycla/1565 so can be tested for this use case

**Comment by nirupamav** [comment]
**_Verified that issue is fixed_**

**https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company/00117000018BhtKAAS/project/a091700000AHldEAAT/cla-manager/requests**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/7b1560dd-461b-4a1d-9d7f-9a30e36639ab)

**https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company/00117000018BhtKAAS/project/a091700000AHldEAAT/cla-manager-designee**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/560631ca-1506-4ef7-ad6f-2cfe82c82987)
