### ISSUE TITLE
V2 - Name field is not available to in the Identify CLA manager dialog similar to Corporate Console

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1376]
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group
3. Generate template

**Steps to Follow**
1. Login to Github as corporate contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Select Company that has not signed CLA for the project
9. Click No
10. Name field is not available in Identify CLA manager dialog similar to Corporate Console
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/87dbdc57-96b5-47d7-a91d-a6c2f846f73c)

@pranab-bajpai 
Could you please confirm if name field is required in contributor console as well

**Comment by amolsontakke3576** [comment]
@wanyaland: I have added the Name field in UI and also change the payload as per below. Can you make respective changes in API?
Request URL: https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/user/4403e361-8b99-4346-97ac-1ac8101cf31c/invite-company-admin
Payload:
 {
  "companyID": "eb4d7d71-693f-4047-bf8d-10d0e7764969",
  "contactAdmin": false,
  "claGroupID": "e2923e14-9d3d-4326-ae1e-00a198125e6f",
  "name": "Amol Sontakke",
  "userEmail": "akpiminol@gmail.com"
}

**Comment by nirupamav** [comment]
Verified that the name field is available however not able to assign cla-manager-designee role. Logged ticket #1520 to track the issue
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/37cee374-3a05-40fa-83f3-47a59e5f7974)
