### ISSUE TITLE
V2 - Appropriate error message is not displayed when CLA Manager request is sent to user who is already cla-manager-designee for the project

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1377]
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group
3. Generate template

**Steps to Follow**
1. Login to Github as corporate contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Select Company that has not signed CLA for the project
9. Click No
11. Enter email of user who is already cla-manager-designee for the project
12. Click Submit Request
13. Observed that API response is displayed as it is and user friendly message is not displayed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/67afaf55-062d-4b07-9fb6-7651131b0d90)

**Comment by amolsontakke3576** [comment]
@dealako @wanyaland To solve this we need a different status code for each type of error or need to rectify error message.

**Comment by nirupamav** [comment]
Issue still exists. User friendly message is not displayed in the UI
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/120a9dac-f681-47fc-a853-bca8b5b417f3)

**Comment by nirupamav** [comment]
Testing blocked due to #1520

**Comment by nirupamav** [comment]
**Verified that the issue is fixed**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c72ff09d-3f84-48b6-8548-f5d7e90f444f)

**Comment by nirupamav** [comment]
**Observed that issue is reproducible again and hence reopening the ticket**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/69bd8e82-21d8-4307-b97e-b696ad86f38b)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/f24b8d21-b6c9-429c-a7aa-a568f27b97d5)

**Comment by nirupamav** [comment]
Issue is tracked in #1625 and hence closing the ticket

**Comment by nirupamav** [comment]
Verified that the issue is fixed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/9d81f2b9-ad5c-4828-bf47-9905bbe9618f)
