### ISSUE TITLE
V1 - Corporate Console - Company-Project name overlaps on the logo in Manage approved list UI

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1383]
## Background

1. Launch Corporate Console
2. Login as CLA Manager
3. Click on company that has signed CLA
4. Click on Manage Approved List for the project
5. Observed that Company-Project name overlaps on the logo
![image](https://user-images.githubusercontent.com/60865903/87390666-f30af700-c5c6-11ea-84a6-6f769c61deaa.png)

**Comment by amolsontakke3576** [comment]
@nirupamav  It looks like already fixed PFA

![Screenshot from 2020-08-19 13-04-50.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/2ab8a06e-0f06-4bcc-b78d-78de2e8e4f9c)

**Comment by nirupamav** [comment]
**Verified that the issue is fixed**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a7d3f6cd-bc90-44e8-9f4a-bfc74d3cccef)
