### ISSUE TITLE
V1 - Contributor Console - Contributor not able to request authorization for contribution again when declined 

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1384]
## Background
1. Launch github and login as corporate contributor
2. Update file in the repository which is associated with a project that has signed CCLA
3. Contributor is gated by CLA
4. Click on CLA NOT SIGNED link
5. Contributor is redirected to Contributor Console
6. Click Corporate
7. Select the company that has signed CLA for the project associated to the github repository
8. Click Submit
9. Click Contact
10. Select CLA Manager and enter other details and Click Send

11. Login to Corporate Console as CLA Manager
12. Click the Company
13. Click on Manager Approved List for the project
14. Decline the contrbutor
![image](https://user-images.githubusercontent.com/60865903/87397704-5d756480-c5d2-11ea-9efc-e96a162f0227.png)

15. Launch github and login as corporate contributor
16. Click on CLA NOT SIGNED link for the PR that is gated by CLA
17. Contributor is redirected to Contributor Console
18. Click Corporate
19. Select the company that has signed CLA for the project associated to the github repository
20. Click Submit
21. Click Contact
22. Select CLA Manager and enter other details and Click Send
23. Observed that below message is displayed and contributor is not able to request for authorization again (I cleared cache again and still faced same issue)
![image](https://user-images.githubusercontent.com/60865903/87397870-a75e4a80-c5d2-11ea-9f77-30aba43b4f79.png)

![image](https://user-images.githubusercontent.com/60865903/87397921-be04a180-c5d2-11ea-8abd-1e5252732b0b.png)

![image](https://user-images.githubusercontent.com/60865903/87398235-3b301680-c5d3-11ea-9792-cf9d47d1deaa.png)

**Comment by amolsontakke3576** [comment]
@wanyaland I have tested above scenario and below is the observation.
1. When user first-time request for whitelist system throw CORS issue
`Access to XMLHttpRequest at 'https://api.dev.lfcla.com/v3/company/f86e03f3-8c81-4071-834c-68e072648b11/ccla-whitelist-requests/a417d310-90c0-4b8e-b4c5-873b901b1929' from origin 'https://contributor.dev.lfcla.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`
2. Even CORS issue still request goes for whitelisted.
3. When contributor next time ask for whitelist the error message come from backend `{"Message":"CCLA whiltelist request already exist"}`
4. When CLA manager decline the contributor request, contributor should be able to send whitelist request again but still got error `{"Message":"CCLA whiltelist request already exist"}`.

We need to fix this from backend itself.

**Comment by nirupamav** [comment]
**Verified that the issue is fixed**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/cae389f8-effb-4360-9ecd-43e10fd3cf5b)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/df94f3df-91b8-48b2-a8aa-b44e8daa31d8)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/137d1599-d266-45bf-b0fa-1eb41955ba4b)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/51b3f1fa-84b6-4aaa-93a1-fccae728f588)

**Comment by dealako** [comment]
Verified fix. Closing ticket.
