### ISSUE TITLE
V1 - Contributor Console - Confirmation needed status is displayed even if CLA check passed

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1385]
## Background
**Prerequisite**
1. CLA group with only CCLA enabled should exist
2. Company should have signed CLA for the CLA group
3. Contrubutor should be added to approved list by email

**Steps to Follow**
1. Launch github
2. Login as whitelisted contributor
3. Update file and create PR
4. Contributor is gated with status "CONFIRMATION NEEDED"
**_And also this is the first time I am seeing "CONFIRMATION NEEDED" status usually in any CCLA flow I have seen CLA NOT SIGNED status_**
5. Click on the link
6. Click Corporate
7. Select Company
8. Check the checkbox and confirm
9. Click on Return to repo
10. Contributor is redirected to github
11. CLA checks passed but still the CLA status is "CONFIRMATION NEEDED"
https://github.com/admin-console-cla/licenses/pull/1
12. Tried to refresh the page several times still observed same issue
![image](https://user-images.githubusercontent.com/60865903/87405923-b3033e80-c5dd-11ea-9280-852d5e7d48ee.png)

**_In another project(both ICLA and CCLA is enabled) where contributor is whitelisted and then contributor is gated while contributing, observed that the status is CLA NOT SIGNED_**
![image](https://user-images.githubusercontent.com/60865903/87406721-bea33500-c5de-11ea-8c71-7d9667a44793.png)

**Comment by dealako** [comment]
Removing/commented out the logic that checks if the user is already authorized but missing company association. The query was previously removed due to performance reasons and badge/button logic is now updated.

Merged to DEV.

**Comment by dealako** [comment]
@nirupamav ready for re-test.

**Comment by nirupamav** [comment]
Verified below scenarios and did not observe the issue reported in the bug

1. Tried with the same user reported in the bug with different project and company
2. Tried with different user for the repository, project and company reported in the bug
