### ISSUE TITLE
V1 - Project Console - Search by Manager is not working

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1387]
## Background
1. Launch Project Console
2. Login as project manager
3. Click on Foundation/Project
4. Click on View Companies for CLA group that has multiple CCLA's
5. Search text box placeholder says "Enter manager or company name"
![image](https://user-images.githubusercontent.com/60865903/87414194-05962800-c5e9-11ea-93e2-40a6f7db1f89.png)
6. Tried to search by manager name/manager email/LFID but no results are fetched. However search by company name is working as expected
![image](https://user-images.githubusercontent.com/60865903/87414286-31191280-c5e9-11ea-9768-c04d8466a4d2.png)

![image](https://user-images.githubusercontent.com/60865903/87414321-3ece9800-c5e9-11ea-9224-b2f0ccd9f00d.png)

![image](https://user-images.githubusercontent.com/60865903/87415022-32970a80-c5ea-11ea-9f04-9fbf91f59d23.png)

**Comment by dealako** [comment]
The old v1 console is deprecated and removed.
