### ISSUE TITLE
V2 - Any user role associated with the organization should have access to Easycla endpoints

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1394]
As discussed with @pranab-bajpai, any user with any role(for e.g. mentee, mentor...) associated with the organization should be able to proceed with easycla flow in LFX portal. Similar to contributor role, user with any role associated with the organization 
- Should have ready only access to all endpoints in Foundation Dashboard and Project Dashboard of LFX portal
- Should be able to start the CLA signing process
- Should be able to Identify CLA Manager or should be able to contact company-admin

**Comment by dealako** [comment]
Roles and permissions were updated for the CLA service.  We added a view permissions fro user, contributor, contact, donor, mentee, mentor, human-resources, lf-training, etc. After PR is merged: https://app.zenhub.com/workspaces/easyclav2-5ed619832c71a855a76ef404/issues/communitybridge/easycla/1394 then please verify once more @nirupamav

**Comment by nirupamav** [comment]
Tested in #1934 and logged related issues in #1975
