### ISSUE TITLE
add signatory_name field in ccla signatures.

### ISSUE THREAD

**Issue by prasannamahajan** [communitybridge/easycla#1395]
## Summary

add signatory_name field in ccla signatures.

## User Story

- As a company employee, I want to know name of cla signatory for project.

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

**Comment by nirupamav** [comment]
**_Tested below scenarios_**
**1. When CLA Manager Designee signs the CLA**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/20a8984e-28f6-492e-b056-d5fc60e8ecda)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/4bb4e7cd-7a72-4f79-a32b-6d85221d387f)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/b1d95342-0e7a-4190-b3e0-7b94ffa61418)

**2. When CLA Signatory signs the CLA**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/e26641b5-d11c-4847-bdab-cfa53ca011ea)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/d579a1d5-cddc-459e-a122-e0777f67ee6d)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/d8e137b4-1004-49d5-ac25-3b7ff2e3d767)
