### ISSUE TITLE
V2 - Employee signature record is not created when ICLA is signed by employee in contributor console

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1411]
**Prerequisite**
1. Create a CLA group with all three check boxes enabled
2. Add github repository for the CLA group
3. Generate template
4. Company should have signed CLA for the project
5. Contributor should be added to the approved list for the project

**Steps to Follow**
1. Login to Github as corporate contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Search and Select the Company
9. Click Proceed
10. Contributor is prompted to sign ICLA
11. Complete the ICLA process by signing the docusign
12. Observed that contributor is redirected to github and status is CLA SIGNED now
13. Observed that Employee signature record is not created, however only ICLA signature record is created

**Comment by dealako** [comment]
Requesting that @wanyaland diagnose the issue.

**Comment by nirupamav** [comment]
**Verified that the issue is resolved**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/e002a643-8120-431f-965f-f24678942351)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/349448ef-aa41-47fa-8ff4-0a00c10455a9)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/4885ccbe-3f0b-4aac-91f5-ee0b3f2597c8)
