### ISSUE TITLE
V1 - Projects are not displayed in project console and signed projects are not loaded for the company in Corporate Console due to CORS issue

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1418]
**Project Console**
1. Launch project console
2. Login as project Manager
3. Observed that projects are not displayed due to CORS issue
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/3bc7259f-42ab-4dcb-b629-c3c2114a987e)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/2c68841f-cd2a-4f84-8c38-ea4005e34b36)

**Corporate Console**
1. Launch Corporate Console
2. Login as CLA Manager
3. Click on the company that has projects with signed CLAs
4. Observed that due to CORS issue signed projects are not loaded at all
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/04fb2e5b-61cf-4ecd-baa5-b8589ee6136f)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/247a764d-2bfc-4cbd-88c0-a77471c3acae)

**Comment by nirupamav** [comment]
**Not even able to access V1 contributor console**

![image](https://user-images.githubusercontent.com/60865903/87760004-c5bf8280-c82c-11ea-8e04-df157c7dc52a.png)

**Comment by dealako** [comment]
@nirupamav I believe this issue was resolved.

![Screen Shot 2020-08-11 at 4.49.34 PM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/3f7edb7b-a540-45e2-a7a6-728127182422)

![Screen Shot 2020-08-11 at 4.50.27 PM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/ed79ca73-638a-4eb7-9b99-e1c4f2764e20)

**Comment by nirupamav** [comment]
@dealako 
Issue with project console is resolved. However issue exists in corporate console and the issue is tracked in #1533 and hence moving this ticket to QA Done
**Project-Console**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/92c11e5d-5267-42c5-b64b-5b79918d90ca)
