### ISSUE TITLE
Accept special character when adding a CLA manager in corporate console

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#1422]
## Summary

When a CLA Manager tries to add a cla manager with a - in their name, the UI says that special characters are not allowed. A - is a valid character.

## Background

![image](https://user-images.githubusercontent.com/46732999/87830743-b7369280-c84f-11ea-89bb-db65699e949a.png)

## Expected behavior
a Linux Foundation username is allowed to have dashes when they are created. The UI should allow for this when adding someone as a CLA manager.

**Comment by amolsontakke3576** [comment]
@nirupamav Above UI is not part of the current corporate console. For the PFA

 ![Screenshot from 2020-09-02 17-57-45.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/6658442b-d255-43da-b642-1b096325061f)latest UI 


Closing this issue now.
