### ISSUE TITLE
V1 - Not able to view companies due to CORS issue

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1424]
1. Launch Corporate Console 
2. Login as CLA Manager
3. Observed that the companies for the CLA manager are not displayed due to CORS issue
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/fe29ec67-39dc-46bf-a9c9-66fb5eaeb072)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/aae61990-3ee5-4e20-95c5-3ef2cb1bc03b)

**Comment by dealako** [comment]
Pushed PR to resolve. https://github.com/communitybridge/easycla/pull/1458

**Comment by nirupamav** [comment]
**Verified that the issue is resolved**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/3c365cf2-e2c1-4143-ae23-b0e861068f73)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/6fbfbeea-6881-4923-bb6d-6c7cc7903677)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a610ef6a-058a-4e22-b84d-c4b28b4bf705)
