### ISSUE TITLE
V2 - Gerrit - Success message is shown when Finish later is selected in the docusign and contributor has not signed CLA

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1430]
1. Access the ICLA from gerrit
2. Click on Proceed To Authorization
3. Login if not already logged in 
4. Click on SIGN CLA
5. In docusign Click on OTHER ACTIONS -> Finish Later
6. Observed that contributor is redirected below screen which says the action was successful. Contributor should be redirected to gerrit page and also since the document was not signed the action should not be successful

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/d959aaed-fa95-4d1b-a231-ca144ea4c9c3)

**Comment by dealako** [comment]
this is a tricky one - another callback flow from Docusign - this time, it is: Gerrit -> EasyCLA API -> Corporate Console -> Docusign -> Finish Later -> :x: Gerrit Authorized :bangbang:

**Comment by dealako** [comment]
for this one, we could render a small HTML page indicating what has happened with a link back to Gerrit to restart the signing process.

**Comment by dealako** [comment]
Similar to: https://github.com/communitybridge/easycla/blob/master/cla-backend/cla/controllers/gerrit.py#L175

which looks like:

![Screen Shot 2020-11-23 at 12.55.59 PM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/a220d01c-cace-42a4-aada-6f2dadf6e450)

**Comment by dealako** [comment]
@makkalot ping @pranab-bajpai, product owner, for details on what he wants to say.

**Comment by amolsontakke3576** [comment]
@dealako @vinod-kadam Look like the issue still persists.
on click on finish later below page is displayed with some HTML text.
![Screenshot from 2021-01-05 16-53-57.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/b7b59f67-dad2-4a44-b539-0da794f30e95)

**Comment by vinod-kadam** [comment]
As updated by @dealako, solution has been implemented & merged - so now available on Dev env for QA testing.

**Comment by amolsontakke3576** [comment]
@vinod-kadam:  Verified and look working fine now
![Screenshot from 2021-01-07 16-19-49.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/ad73d6cd-2445-4e20-8696-384a70bea9ea)

**Comment by vinod-kadam** [comment]
As discussed in the standup with Pranab/David, "Restart Authorization" takes the user to the PR again - the name seems fine as user is starting again from the beginning.
