### ISSUE TITLE
v2- Error Handling Request Corporate Signature

### ISSUE THREAD

**Issue by wanyaland** [communitybridge/easycla#1432]
## Summary

Error Handling Request Corporate Signature

## Background

1. Launch https://lfx.dev.platform.linuxfoundation.org/login
2. Login with user having access to the Academy Software Foundation and Open EXR company,
3. Expand ASF Foundation,
4. Click on Open EXR project that has not signed CLA,
5. Click on Start the CLA process button,
6. Click Yes in "No Signed CLA Found" dialog,
7. Click Proceed
8. Click Proceed with Signing
9. Click No
10. Enter valid data for Enter First Last Name field
11. Enter email which is already cla signatory for the same organization 

## User Story

As a a UI developer(LFX) I would like to handle the error message and status code in a clearer way than what is being thrown by the backend api

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

https://jira.linuxfoundation.org/browse/LFX-2027

**Comment by nirupamav** [comment]
**Requesting CLA-Signatory for a user for one of the project**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/f09b3baa-a92f-4134-9d60-d6e38f932a78)

**Requesting CLA-Signatory for same user and same project**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/79057593-df24-4fb8-ac00-0b37f2221c87)

**Requesting CLA-Signatory for same user and different project**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/e9391aec-e8ff-4fd9-878a-4d6caf9792ba)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/dcfa8b1e-aa50-485a-bb72-d53a127291a9)
