### ISSUE TITLE
api to get cla-group corporate signatures

### ISSUE THREAD

**Issue by prasannamahajan** [communitybridge/easycla#1442]
## Summary

Write an api to get list of corporate contributors for cla-group and company

## User Story

- As a project manager, I want to see the list of corporate contributors for cla-group and company

**Comment by nirupamav** [comment]
Testing blocked due to #1448, #1411, #1319

**Comment by nirupamav** [comment]
Testing In Progress

**Comment by nirupamav** [comment]
API DOC https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/listClaGroupCorporateContributors

**Comment by nirupamav** [comment]
Tested and observed below issues
**1. 200 with empty list is returned for CLA group which has only ICLA enabled**
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/cla-group/1c857740-4730-4c2e-a24f-6b6641717e17/corporate-contributors

Testing for CLA Group at different levels is pending which will be covered in End to End tesing

**Comment by dealako** [comment]
@nirupamav we should handle this case [via this bit of code](https://github.com/communitybridge/easycla/blob/master/cla-backend-go/v2/signatures/handlers.go#L831-L837). Can you re-test after the refactor?

**Comment by nirupamav** [comment]
**_Tested and observed below issues_**
**1. 500 is returned when invalid cla group id is provided in the url**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/6ab00f5b-c36b-4afc-9a48-8382787e7107)

**2. 500 is returned when invalid companysfid is provided in the url**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/8f5e6728-f174-4b85-983d-f8e1c64b0d8d)

**Comment by nirupamav** [comment]
**Verified that the issue is fixed**

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/2ca6b5e0-fdc7-4d2e-b12b-958b8354da0a)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/124e39a2-5a73-4913-8ab4-c01a0390388a)
