### ISSUE TITLE
[V2 -Regression] - Corporate Contributor is not prompted with ICLA flow when employee is required to sign ICLA

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1448]
**Prerequisite**
1. Create a CLA group with all three check boxes enabled
2. Add github repository for the CLA group
3. Generate template
4. Company should have signed CLA for the project
5. Contributor should be added to the approved list for the project

**Steps to Follow**

1. Login to Github as corporate contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Search and Select the Company
9. Click Proceed
10. Contributor is not prompted to sign ICLA
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/4afd31a1-d9ba-43f1-be56-d8de572289f7)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/84d10165-1d4d-4675-b59d-e4883cfed6ee)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/b410b24e-04e7-45d7-ad39-8e4a682cba05)

**Comment by dealako** [comment]
@amolsontakke3576 can you please look at this issue next?

**Comment by amolsontakke3576** [comment]
@dealako @nirupamav  If contributor already added into the approved list do we need to sign ICLA again?

**Comment by nirupamav** [comment]
@amolsontakke3576 
When controbutor is added to approved list and below checkbox is checked for CLA group, ICLA needs to be signed by employee. 
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/4afd31a1-d9ba-43f1-be56-d8de572289f7)

And this flow was working earlier and below is how you had implemented it earlier which used to take to ICLA flow when clicked on Proceed
![image](https://user-images.githubusercontent.com/60865903/88284731-881a9800-cd0b-11ea-94aa-81efb7282eae.png)
