### ISSUE TITLE
Gerrit Contributor unable to select company

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#1466]
## Summary

When a Gerrit contributor tries to select their company from the list, they are unable to.

## Background

1. Select CCLA from Gerrit agreements
1. Get redirected to EasyCLA contributor console
1. Click a company from the list of companies
1. UI is unresponsive and error is observed in console 

https://contributor.lfcla.com/#/cla/gerrit/project/b71c469a-55e7-492c-9235-fd30b31da2aa/corporate

## Screenshots

![image](https://user-images.githubusercontent.com/46732999/88309916-057ae400-ccdd-11ea-8c71-e24c0355d2f0.png)

## Environment

PROD

**Comment by dealako** [comment]
resolved issue - created PR https://github.com/communitybridge/easycla/pull/1467. The issue was that v1 redirect requires gerrit_id instead of the project_id.

Summary:

    [#1466] Gerrit v1 Redirect Update
    
    - Resolved Gerrit v1 redirect issue (problem was we used project_id
      instead of gerrit_id for v1 redirect)
    - updated redirect page - added favicon, updated text by adding
      corporate or individual to text and button, added title to HTML page
    - Renamed function from postCheckedAndPreparedEmployeeSignature to
      postCheckAndPreparedEmployeeSignature
    - Added/Updated Gerrit and Project python dynamodb data model string
      methods - cleaned up and added additional fields to assist with debugging

**Comment by dealako** [comment]
Merged PR - pushing to DEV.
