### ISSUE TITLE
V2- Link to read the documentation in all email notifications of V2 EasyCLA workflow are pointing to V1 documentation

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1476]
Observed that link to read the documentation in all email notifications of V2 EasyCLA workflow are pointing to V1 documentation instead of V2 documentation link
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/b63e93da-2239-4fdf-a076-5a6ec095f9c8)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/b5868864-56c3-4e61-9096-6853a36ef41a)

**Comment by dealako** [comment]
Submitted PR: https://github.com/communitybridge/easycla/pull/1479

**Comment by nirupamav** [comment]
**Verified few emails and observed that below link is displayed when clicked on **read the documentation** link in email** 
**_https://docs.linuxfoundation.org/docs/v/v2-beta/_**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/58ef28e6-ef0d-4ef3-80bb-d7dbcbbba2c5)
