### ISSUE TITLE
V2 - Corporate Console link of V1 is displayed in email notification sent to CLA Manager

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1477]
Observed that Corporate Console link of V1 is displayed in email notification sent to user when the user is added as CLA Manager to a project from V2 Corporate Console
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/ccbc57f1-9d9d-4631-a608-47ca718c4ca3)

**Comment by dealako** [comment]
Created PR https://github.com/communitybridge/easycla/pull/1479

**Comment by nirupamav** [comment]
**Verified that the issue is fixed and when clicked on the link highlighted below, LFX portal login page is displayed in new tab**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/b2f48279-bfc9-46ef-81bd-973e0a54fd98)
