### ISSUE TITLE
V2 - Assign contributor role after contributor acknowledgement in Contributor Console

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1478]
As discussed in stand up call below flow needs to be implemented in Contributor Console

- Contributor role should be assigned to the contributor after the contributor acknowledgement if the contributor has LFID
- After contributor acknowledgement email notification has to be sent to contributor with Accept Link to assign contributor role when the contributor does not have LFID

@pranab-bajpai 
If contributor already has LFID with an emailId different from github email, how should the scenario be handled in this case

**Comment by dealako** [comment]
Scenario:

**Comment by nirupamav** [comment]
@wanyaland @amolsontakke3576 
Is the implementation same as mentioned in the issue description? If it is different could you please let me know the expected behavior

**Comment by nirupamav** [comment]
**Tested below scenarios and observed that contributor role is assigned. Testing still in progress_**

**1. Github User email is private and has LFID with that email**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/420eabb6-dac4-4894-a145-166d9dcf2af1)

**2. Github User email is public and has LFID with that email**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/0a9a6b10-95b3-4583-b9c4-79e244edf52d)

**3. Github User email is public and has LFID with github user email as alternate email and primary email of lfid is different**

**Comment by nirupamav** [comment]
Verified that error is not displayed when LFID is not there and also in gerrit flow contributor role is assigned
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/8f3170f8-aa42-4157-bb33-62a6cc003402)
