### ISSUE TITLE
V2 - request-corporate-signature returns 500 internal server when CLA Group name is too long

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1497]
Observed that endpoint https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/request-corporate-signature returns 500 when CLA Group name is too long. 

**_CLA Group Id_** 22852a17-a6bb-4665-b5c1-c92bb2c4985c

**_CLA Group Name_** CLA group for NFF-GO project for CCLA and ICLA and employee need not sign ICLA which belongs to DPDK Foundation CLA group for NFF-GO project for CCLA and ICLA and employee must sign ICLA which belongs to DPDK Foundation

**_Payload_**
{
    
    "company_sfid": "0014100000Te0iaAAB",
    "project_sfid": "a092M00001IV4AWQA1",
    "return_url": "https://lfx.dev.platform.linuxfoundation.org/foundation/a0941000005osNmAAI/project/a092M00001IV4ARQA1/cla",
    "send_as_email": false
}

**_Response_**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/ebdc95da-1833-4562-8f10-2a4cc6399dfd)

**Comment by dealako** [comment]
Error is that docusign only supports email subject up to 100 characters.

**Comment by dealako** [comment]
@rinkeshbhutwala please review this one - should be a simple swagger spec update to add validation.  Please ensure that the spec includes:

- Description
- Example
- minLength (as required)
- maxLength (as required)
- format or pattern (as required)

Thanks!

**Comment by dealako** [comment]
Created and pushed PR.  Updated maxLength to 100 characters due to DocuSign limits.  Updated v1 UI to constrain the user from adding more than 100 chars, updated API swagger spec to catch more than 100 chars, updated python API to trim to 100 characters.

@nirupamav ready for review.

**Comment by nirupamav** [comment]
**Since now CLA Group accepts 100 characters, Test with 100 characters and observed that the issue is fixed**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c9a333a5-6c0b-46ed-a15a-31a77a67870d)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/ae2cdc2b-b102-43a6-84d1-b08949dac607)
