### ISSUE TITLE
V2 - CLA Check will pass but status in Github is still shown as CLA NOT SIGNED when contributor approved by githuborg contributes to the project

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1498]
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group
3. Generate template
4. Company should have signed CLA for the project
5. Github org should be added as the approval list
6. Contributor should be invited and the contributor should accept invitation and join the github org(I assigned member role as well as tried with making the contributor owner)

**Steps to Follow**
1. Login to Github as individual contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Search and Select the Company
9. Click Proceed
10. Contributor is redirected to Request Authorization instead getting acknowledged
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c304624e-77cb-4787-8327-96cb9da9a733)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/0fc63d5d-b25c-4a6c-8cc0-a3311fe88c5a)

**Comment by dealako** [comment]
Please ensure you are public.

**Comment by nirupamav** [comment]
**For my user I set Organization visibility to public and then the I was acknowledged. However the status in Github is still shown as CLA NO SIGNED**
https://github.com/dronecodeproject-px4/px4/pull/5

![image](https://user-images.githubusercontent.com/60865903/89020885-49a16080-d33d-11ea-9188-848dfce1c5ff.png)


![image](https://user-images.githubusercontent.com/60865903/89020865-3f7f6200-d33d-11ea-8cea-141b5881b6b1.png)

![image](https://user-images.githubusercontent.com/60865903/89021168-b3216f00-d33d-11ea-8c60-9f27c0bc0a34.png)

**Comment by dealako** [comment]
Note to self: Scenario Summary:

- GH Org Approved before
- Contributor comes in and acknowledges
- Status is updated, but not comment

**Comment by dealako** [comment]
Creating PR for this fix: https://github.com/communitybridge/easycla/pull/1527

**Comment by dealako** [comment]
Deploying attempt to fix to DEV

**Comment by dealako** [comment]
This issue appears to be resolved.

Before authorization (previously on GH Org approval list, but not affiliated with an org):
![Screen Shot 2020-08-05 at 4.53.57 PM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/e5d8b9ea-337b-4594-8fad-b80eb0c4f85c)
After affiliation:
![Screen Shot 2020-08-05 at 4.54.06 PM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/f238dd66-be68-4c37-b04a-9512237640f1)

**Comment by dealako** [comment]
@nirupamav @WillsonHG this should be resolved now

**Comment by nirupamav** [comment]
**_V2_** 
`Scenario - When employee has to sign CLA`
![image](https://user-images.githubusercontent.com/60865903/89496927-eac66600-d7d8-11ea-978a-dd8a9116bba7.png)

![image](https://user-images.githubusercontent.com/60865903/89497071-3711a600-d7d9-11ea-9e1f-6744aee6e08b.png)

`Scenario - When employee need not sign CLA`
![image](https://user-images.githubusercontent.com/60865903/89498165-5e697280-d7db-11ea-82dc-4817a00aed8f.png)

![image](https://user-images.githubusercontent.com/60865903/89498230-7b05aa80-d7db-11ea-98bc-6b9cca0647bd.png)
