### ISSUE TITLE
V2 - Create Company - Company exists or any other server side validations are done after contributor logs into LF system

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1499]
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group

**Steps to Follow**
1. Login to Github as individual contributor (Make sure contributor is not logged in to LF system)
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Click on the building icon
9. Click on **Organization not listed? + Click Here**
10. Enter company which already exists
11. Click Next
12. User is prompted to login to LF system. When user login, user redirected to Contributor Console and then company exists error message is displayed. Since the company already exists there is no need for the contributor to login. Validations should be handled before login to LF

**Comment by dealako** [comment]
@rinkeshbhutwala and @amolsontakke3576 let's setup some validation endpoints for EasyCLA such that @amolsontakke3576 can use them on the contributor console when the user types ahead on the Organization Service:

1. Website
2. Organization Name

BTW, I think the updated wireframe will have the website first, then the organization second (confirm with Pranab). Both should be unique, but I think the Organization Service must be unique.  Contributor console should have a validator that calls our API which can determine if the values are unique.

**Comment by nirupamav** [comment]
Company creation flow has been changed and testing of this ticket is blocked until the new changes are implemented

**Comment by nirupamav** [comment]
Verified that validations are done before login
