### ISSUE TITLE
Project Console: Signatures: Link to digital copy of signed document

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#15]
<a href="https://github.com/caniszczyk"><img src="https://avatars1.githubusercontent.com/u/63777?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [caniszczyk](https://github.com/caniszczyk)**
_Wednesday Jul 03, 2019 at 20:53 GMT_
----

We should have docs for project admins

- how do I find the CLA of a company/individual that has signed
- how do I see the folks that have signed
- which emails are valid for the CCLAs

**Comment by jpalmerLinuxFoundation** [comment]
This should be part of the project.lfcla.com console. When you click on the "View Signatures" within a Foundation's projects (CLA Groups) it will show you who has signed both independent contributors & employees (covered undersigned CCLAs).  The only thing missing is the link directly to the document where the digital signature exists. This is something we have in our JIRA backlog. We're still migrating everything to GitHub.

**Comment by dealako** [comment]
Closing this issue during our backlog review. If additional help (be specific) is needed then please create a new ticket.
