### ISSUE TITLE
V2 - Few Issues when CLA Group is deleted

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1503]
Observed that when we delete CLA group below associations are deleted

- Signatures are set to false
- Projects are disassociated from CLA Group
- Github repositories are deleted 
- Gerrit repositories are deleted

**_However below are still not removed or deleted and also observed issues with event data_**
1. Permissions for CLA Signatories and CLA Managers should be removed for this Project and associated Companies.
2. When CLA group is deleted, even if gerrit is not configured, an event is recorded for gerrit deletion

**_NOTE:_** As discussed in standup call Github Organizations will not be deleted

**Comment by dealako** [comment]
Created PR for these issues: https://github.com/communitybridge/easycla/pull/1517

**Comment by dealako** [comment]
Merged PR which:

**Comment by nirupamav** [comment]
**Tested for scenario when CLA is signed at foundation level and observed that 
Roles are not removed for the users
_Tested for below test data_**
FoundationID - a091700000A6HyRAAV  
FoundationName - CLA_Foundation_1596796963054

**Also observed that instead of CLA signatory name CLA Manager name is displayed**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/b0a31a85-b836-4ed1-915f-fe641f310e58)

**users**
clatestuser2 - CLA Signatory
clatestuser1 - CLA Manager

**Comment by dealako** [comment]
Created PR: https://github.com/communitybridge/easycla/pull/1785

Looks like SFID was not provided for delete roles. Needs more testing...

**Comment by nirupamav** [comment]
Executed automation script for end to end flow for foundation level CLA Group and observed that roles are not removed after CLA Group is deleted
**_NOTE:_** Project was also deleted as part of automation script
**FoundationSFID** - a0902000000A36tAAC
**FoundationName** - CLA_Foundation_1599731711802
**CLAGroupId** - b34b07fd-6e52-4b79-9782-74e31c61a5c0

**Comment by dealako** [comment]
Related to #1716 Role Cleanup on CLA Group delete.

Currently blocked waiting for ACS team to provide an API to query/filter on:

1. role name/role id where role is cla-manager, cla-manager-designee, cla-signatory
1. projectSFID is the project ID

Since these roles are formatted as projectID|organizationID object types, the current ACS API does not provide a filter for me to obtain the roles that were previously assigned to this project.

**Comment by dealako** [comment]
ACS has added the following API: https://api-gw.dev.platform.linuxfoundation.org/acs/v1/api-docs#operation/deleteRolesByObjectType

unblocked.

**Comment by dealako** [comment]
Created and merged PR: https://github.com/communitybridge/easycla/pull/1941. Conducted a few tests via PostMan. Ready for QA.

**Comment by nirupamav** [comment]
Verified that roles are removed now for the organization. Tested for single organization.
Will test for multiple organizations and if I see any issues will log another bug.
