### ISSUE TITLE
V2 - Create Company - Contributor is redirected to LFX dashboard instead of the project page

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1509]
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group

**Steps to Follow**
1. Login to Github as individual contributor (Make sure contributor is not logged in to LF system)
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Click on the building icon
9. Click on Organization not listed? + Click Here
10. Enter company which already exists
11. Click Next
12. User is prompted to login to LF system
13. Login 
14. User is redirected to contributor console
15. Click on Proceed in the dialog box
16. User is redirected to LFX corporate console dashboard instead of LFX project page to start the CLA process

**Comment by amolsontakke3576** [comment]
@nirupamav I am redirecting contributor to the LFX page on below URL
**When Foundation present for project :** `https://lfx.dev.platform.linuxfoundation.org/foundation/<foundationId>/project/<projectId>/cla`
**When Foundation not present for project :** `https://lfx.dev.platform.linuxfoundation.org/project/<projectId>/cla`

After redirecting to the LFX it says `We couldn't find URL`. PFA![Screenshot from 2020-07-31 18-22-48.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/f73b6bec-c12d-4706-83fd-ffc1c1181f9e)


Can you please confirm the LFX url ?

**Comment by nirupamav** [comment]
@amolsontakke3576 
The url seems to be using internal project id from CLA database instead I think the url should use SFID of the project

**Comment by dealako** [comment]
Need to return the list of SF Projects associated with the CLA Group for the API request.

**Comment by amolsontakke3576** [comment]
Deprecated flow so closing now
