### ISSUE TITLE
V2 - While sending request to signatory 500 is returned when only spaces is provided for the authority_name

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1519]
Observed that while sending request to signatory 500 is returned when only spaces is provided for the authority_name

**Endpoint** https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/request-corporate-signature

**HttpMethod** POST

**Payload**
{
"authority_email": "nirupamav+testq322@proximabiz.com",
"authority_name": "              ",
"company_sfid": "0014100000Te0iaAAB",
"project_sfid": "a091700000A5GTvAAN",
"return_url": "https://corporate.dev.lfcla.com/#/company/79b422d0-4261-41d7-a834-ccce7fe07bed",
"send_as_email": true
}

**Response**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/33b3ca23-85d4-4061-a9ba-2f418533c85a)

**Comment by dealako** [comment]
@rinkeshbhutwala can you ensure that we have swagger spec format/pattern to prevent empty or space-only values being passed to our API for this issue?

**Comment by nirupamav** [comment]
**Verified that 422 with appropriate message is displayed**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/5f556422-2b6f-42d0-ae40-400a7f09b3f0)
