### ISSUE TITLE
V1 - Project Console - Not able to delete CLA Group

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1529]
1) Launch Project Console
2) Login as Project Manager
3) Click on The Presto Foundation
4) Delete 06AugV1CLAGroup2
5) Observed that not able to delete CLA Group
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/75cc32ec-464f-4ac4-942f-fa336fb9df53)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/e2f18942-44d8-4769-aa7a-2e55623a3fb8)

**Comment by dealako** [comment]
Created PR https://github.com/communitybridge/easycla/pull/1538

**Comment by nirupamav** [comment]
**Verified that the issue is fixed**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/7e77b983-6f7b-484e-a3d3-aa2b968adf1f)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/95da3550-e55d-4593-99d9-d05b4f23f690)
