### ISSUE TITLE
V1 - Not able to view signed projects and not able to sign CLA for projects in Corporate Console due to CORS issue

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1533]
1) Launch Corporate Console
2) Login as CLA Manager
**_Issue1_**
3)Click on the exisitng Company
4) Observed that signed projects are not loaded and observed CORS error in console
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/bd626dd3-b020-488e-958d-18a188730fe3)

**_Issue2_**
5) Create a Company
6) Click on the Company
7) Click Sign New CLA
8) Select the project
9) Click Submit
10) Observed CORS issue and project name is displayed in UI
11) Click Yes observed CORS issue and project name is displayed in UI
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/f4b5c7f1-f1ba-4eee-88df-8f9440e1bb0f)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/204a4c3e-63a0-48e8-9836-5b1f73ed13de)

**Comment by dealako** [comment]
@nirupamav, @wanyaland has resolved this issue with this PR: https://github.com/communitybridge/easycla/pull/1553/files, can you re-check?

**Comment by nirupamav** [comment]
@dealako @wanyaland 
**I am still able to reproduce the issue**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/b64a7981-4bf1-4291-92fd-b0d755c8a60a)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/d7dd62b6-a76a-448e-92c8-ab8db391c85b)

**Comment by dealako** [comment]
Issue is:

```
[ERROR] IndexError: list index out of range
Traceback (most recent call last):
  File "/var/task/wsgi_handler.py", line 110, in handler
    return serverless_wsgi.handle_request(wsgi_app, event, context)
  File "/var/task/serverless_wsgi.py", line 173, in handle_request
    response = Response.from_app(app, environ)
  File "/var/task/werkzeug/wrappers/base_response.py", line 287, in from_app
    return cls(*_run_wsgi_app(app, environ, buffered))
  File "/var/task/werkzeug/test.py", line 1119, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "/var/task/hug/api.py", line 502, in api_auto_instantiate
    return module.__hug_wsgi__(*args, **kwargs)
  File "falcon/api.py", line 274, in falcon.api.API.__call__
    raise
  File "falcon/api.py", line 269, in falcon.api.API.__call__
    responder(req, resp, **params)
  File "/var/task/hug/api.py", line 356, in version_router
    request, response, api_version=api_version, **kwargs
  File "/var/task/hug/interface.py", line 946, in __call__
    raise exception
  File "/var/task/hug/interface.py", line 917, in __call__
    self.call_function(input_parameters), context, request, response, **kwargs
  File "/var/task/hug/interface.py", line 839, in call_function
    return self.interface(**parameters)
  File "/var/task/hug/interface.py", line 129, in __call__
    return __hug_internal_self._function(*args, **kwargs)
  File "/var/task/cla/routes.py", line 762, in get_project
    project["signed_at_foundation_level"] = project_cla_group_list[0].signed_at_foundation
```

Resolved with PR: https://github.com/communitybridge/easycla/pull/1567

**Comment by nirupamav** [comment]
**Verified that we are able to sign CLA and view signed projects in V1 corporate console**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/15514a6a-5029-4f3e-9d85-5badf449a915)
