### ISSUE TITLE
Wireframe updates to be implemented 

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#1535]
- [x] Need to update "Go Back" buttons as per the wireframe
- [x] Need to add the 3 screens that we deprecated where organization was not found
- [x] Switch the order of website and organization name in the workflow where organization not found
- [x] Check word whitelist is not there in any window or dialog box
- [x]  Add firstname and lastname for CLA Manager invite dialog box                       

https://wireframepro.mockflow.com/view/app-easycla#/page/Dab111f6a971bc1cd42c819a1770bc817

**Comment by nirupamav** [comment]
Will test this ticket when all flows of contributor console are ready for testing

**Comment by nirupamav** [comment]
**_Tested and observed below issues. All other point mentioned in the ticket are fixed_**. 
`I was not able to load https://wireframepro.mockflow.com/view/app-easycla#/page/Dab111f6a971bc1cd42c819a1770bc817 which is mentioned in the issue description and hence validation it with contributor console wireframe https://confluence.linuxfoundation.org/display/PROD/Contributor+Console+for+EasyCLA+V2`

**Need to update "Go Back" buttons as per the wireframe**
1. In Identify CLA Manager popup, GO Back button font size and font weight is not as per wireframe
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/7d01bb75-c054-4630-baf4-598bffb3c8ff)

2. In the below popups font weight is not as per wirerframe
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c5a6a019-e88c-4565-bfdb-3ffe4aac45fa)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/8fcc1870-903a-4534-8aec-adf7001b3c5b)

**Comment by amolsontakke3576** [comment]
@vinod-kadam Need to change some CSS properties as per suggestion so moved to In dev

**Comment by amolsontakke3576** [comment]
Updated UI as per wireframe
![Screenshot from 2021-01-04 16-00-19.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/29ef0cc9-fbd3-4197-ba61-0c1eed4c309d)

**Comment by manishv09** [comment]
Verified it on Staging and found working fine now, please refer the screencast as below:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/8e9cf3f5-fdb0-4870-a710-5cceff239fca)
