### ISSUE TITLE
Open GitHub tab and flash this message

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#1536]
In contributor console right when the user clicks on "Proceed" button and is taken to LF Login screen. 
- [ ] Open up user's GitHub session in a separate tab
- [ ] Flash this message to the user "You will be taken to LF login screen and after successful login you will be redirected to CLA corporate console to finish setting up CLA. Your GitHub session has been opened in a new tab in the background so that you can come back to GitHub and submit your code contribution"

**Comment by nirupamav** [comment]
Testing blocked due to #1571

**Comment by nirupamav** [comment]
As per new changes below flash message is displayed in current tab and after few seconds, Corporate console is opened in new tab and focus is on new tab and in previous tab user is redirected to github
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/926e25bb-73b8-4f58-ac87-d73134b3903c)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/5c02b2b8-e2f0-4e4a-84dc-91d64c8ad85c)
