### ISSUE TITLE
V2 - cla-manager-designee role is assigned to foundation and cla-manager role is assigned to subprojects

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1537]
1) Launch LFX memeber protal
2) Sign CLA at foundation level
3) Observed that cla-manager-designee role is assigned at Foundation level and after CLA is signed cla-manager-role is assigned to sub projects. Due to this CLA Managers cannot be added to the foundation
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/04e9cfd6-1207-4153-b143-e1fe29c093ca)

**Comment by dealako** [comment]
Note: Nirav and his team will have an update to the permissions such that when we assign a role at the foundation level, that sub-projects will also get this permission automatically.

This will hopefully be resolve by this fix.

**Comment by nirupamav** [comment]
**Verified that the issue is fixed**
**_Before Signing_**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/bdd3750c-9bcd-4006-a506-b54b264a01d6)

**_After Signing_**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/56194c52-a6c7-4373-9e2d-c35dfcb7b95d)
