### ISSUE TITLE
V2 - Go back button close (X) icon is not displayed in Request Failed dialog

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1550]
Observed that in Request Failed dialog box in any flow of Contributor console does not have Go Back button or close (X) in the dialog for the user to try with different data or to try again. 
Now user has to click on Exit EasyCLA and then revisit the contributor console again
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/4f5e70ee-c2a0-49ce-8ac9-893d94e164d5)

**Comment by amolsontakke3576** [comment]
@nirupamav No provision for back button in the wireframe please confirm with @pranab-bajpai.

**Comment by nirupamav** [comment]
@pranab-bajpai 
Do to some error Request Failed dialog is displayed in different contributor console flows. However in the dialog box there is no Go Back button or close(X) icon for the user to try again. 
As of now only Exit EasyCLA option is available in the dialog box and user has to return to return to github and try the flow again. Could you please let us know if Go Back button or close(X) icon should be displayed in the dialog box
cc: @amolsontakke3576

**Comment by nirupamav** [comment]
**Verified that the issue is fixed. If I face this issue again in any of the unexpected error scenario will log another tikcet**

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/0ff24181-d52d-4063-8ae2-01c498919ce2)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/e249be86-4f00-49e8-9c79-12c3eadd60ea)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/71f8a9b2-8db9-493b-b803-601765282460)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/7808ab1d-3198-42ab-bcc0-a01f018ce77e)
