### ISSUE TITLE
v1 Project Console - CLA Group Name / Description Validation

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#1555]
## Summary

Update v1 Project Console CLA Group Name/Description validation.

## Background

Provide validation as user types - confirm/validate group name and description before form submission.  The current implementation requires user to hit submit for identifying invalid characters. This should be done as the user types and at the end as well.

CLA Group Name Regular Expression
- [swagger](https://github.com/communitybridge/easycla/blob/master/cla-backend-go/swagger/common/properties/cla-group-name.yaml#L4)
- [UI](https://github.com/communitybridge/easycla/blob/master/cla-frontend-project-console/src/ionic/modals/cla-contract-config-modal/cla-contract-config-modal.ts#L49)

CLA Group Description Regular Expression
- [swagger](https://github.com/communitybridge/easycla/blob/master/cla-backend-go/swagger/common/properties/cla-group-description.yaml#L4)
- [UI](https://github.com/communitybridge/easycla/blob/master/cla-frontend-project-console/src/ionic/modals/cla-contract-config-modal/cla-contract-config-modal.ts#L56)

[UI Form](https://github.com/communitybridge/easycla/blob/master/cla-frontend-project-console/src/ionic/modals/cla-contract-config-modal/cla-contract-config-modal.html#L10-L26)

## User Story

As a project manager, I want to validate the CLA Group Name and Description as I type.

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the DEV environment.

## References

See above links

**Comment by amolsontakke3576** [comment]
@dealako  The regex used to validate CLA group name `^([\w\p{L}][\w\s\p{L}()\[\]\.\,+-_]*)$` and CLA group description `^([\w\p{L}][\w\s\p{L}()\[\]\.\,+-_]*)$` used in angular validator are works fine for English characters but not for other language.

it looks like the validator pattern method has some limitations.

**Comment by amolsontakke3576** [comment]
@dealako As per our last discussion, I had made changes in regex and restrict only special characters. however, it is working fine for certain languages like Chinese, Spanish, English but failed from the backend for languages like Hindi.
PFA
![Screenshot from 2020-12-07 12-14-18.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/e580c48b-0318-4a77-9947-f674a763b13c)
![Screenshot from 2020-12-07 12-14-32.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/b91d5f66-06ad-45b6-8e87-4d006b2d79ce)
![Screenshot from 2020-12-07 12-17-32.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/e313fa13-5544-4d8f-a0f8-0b7dea6ab224)

![Screenshot from 2020-12-07 12-27-11.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/7b134b20-6d65-4a1f-bd58-2587ff47dd68)!

**Comment by amolsontakke3576** [comment]
@dealako Perform the unit testing on the PR (https://github.com/communitybridge/easycla/pull/2276) and below is the result.
1. Unit test for ASCII example: **Indiano-Inc.** 
**_Result : Passed_**
![Screenshot from 2020-12-09 11-16-47.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/1ac00dd4-50e3-4e4d-9136-5ce9d2cd37a5)

2. Unit test for ASCII + other characters example : **Amol Inc. + 阿莫尔公司**
**_Result : Passed_**
![Screenshot from 2020-12-09 11-20-49.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/710a72e6-5817-4d8e-aee5-29fcaeb984b3)

3. Unit test for non-ASCII characters example: **印第安那公司**
**_Result : Partially Failed_**
![Screenshot from 2020-12-09 11-18-10.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/c5bca70f-23d9-431c-aec0-2f23c5170c86)

![Screenshot from 2020-12-09 11-19-26.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/5de60ab0-8a84-466e-b6de-70707f1d5fda)

**Comment by dealako** [comment]
The old v1 console is deprecated and removed.
