### ISSUE TITLE
V2 - Not able to add CLA Manager/approved list to the CLA group when CLA is signed at foundation level

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1560]
1) Launch LFX memeber protal
2) Sign CLA at foundation level
3) Add CLA Manager
4) Observed that 500 response code with message "No cla group is associated with this project" is returned and not able to add CLA Managers at all
Also observed that we are not able to add approval list
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/8c5b4caf-ac0b-4a95-9b14-2b2eda84231f)

**Comment by dealako** [comment]
Discussed with @wanyaland - New Strategy:

- ProjectSFID or FoundationSFID is provided (we don't know which, @nirupamav is sneaky)
- CLA Group Lookup Table via the ProjectSFID index/query
- If the lookup is ok - use this information
- If the lookup fails, let's try the Foundation SFID
- CLA Group Lookup Table via the Foundation SFID index/query
- If the lookup is ok - use this information
- If the lookup fails, no records - we tried, but no luck, give up and show error

**Comment by nirupamav** [comment]
@wanyaland 
I am able to add CLA Manager but not able to add approved list due to 403 response. I have provided Bearer token of CLA Manager of the project and organization. With the same bearer token I am able to add CLA manager but not approved list
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/2c3c042c-0570-4e08-be6f-b38226287dbc)

**Comment by wanyaland** [comment]
@nirupamav could you kindly share the details you used for this endpoint? That is the projectSFID,companySFID,  claGroupID and auth user you used. This error was thrown probably due to missing missing username

**Comment by nirupamav** [comment]
**Verified that able to add Approval List and CLA Manager**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/23e24c00-7c10-4013-b035-8cf2ddd784c3)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/cb535beb-c312-4040-a225-c074e7481d1f)
