### ISSUE TITLE
V2 - Not able to identify CLA Manager or contact admin through cla-manager/requests endpoint

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1565]
**Observed that always 500 is returned by cla-manager/requests endpoint. Tried both through UI and API endpoint**

**_Scenarios tried for Project Level CLA Group_**
1. CLA Manager for another project in the organization
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/f15730b6-811c-48e5-87b0-6eaba3411b4c)

2. user without LFID
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/e5986fab-5866-4bce-ac28-800be8c42743)

3. Contact Admin
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/85bc20ae-e8e1-42f9-9b82-6da4ac387190)

**UI**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/891e85f7-8c97-4429-b263-d90e2cc8b5a5)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/55096c98-1839-4388-bd2f-7889f430de94)

**Comment by wanyaland** [comment]
@nirupamav Tested and endpoint is working as expected. Run against different cases 

- User with LFID
- User with No LFID 
- ContactAdmin

**Comment by nirupamav** [comment]
**Issue is still reproducible**

**_API_**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/aca639d2-3c76-4b8a-92cc-f2c68ac4d0c6)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/4c45b22f-db87-4a85-8fbd-809423ad41d6)

**_UI_**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/445c9840-392b-4ee0-95cb-f18dc4f1e4ce)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/24b44b09-73a2-493c-bc78-c6f42169ff33)

**Comment by wanyaland** [comment]
@nirupamav I tested and was getting a success for each use case.

**Comment by nirupamav** [comment]
@wanyaland 
I am still facing the issue in both UI and API
![image](https://user-images.githubusercontent.com/60865903/91311246-7af03d80-e7d0-11ea-8d42-e627da0b130e.png)

![image](https://user-images.githubusercontent.com/60865903/91311298-8fccd100-e7d0-11ea-8dfe-28d35568ae71.png)

![image](https://user-images.githubusercontent.com/60865903/91311268-85123c00-e7d0-11ea-934a-7ed22e85ad09.png)

**Comment by nirupamav** [comment]
**Verified that the issue is fixed**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/67a98b08-117c-4879-ae11-5bf967d73be4)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/7c8bf3fc-7752-46cb-a4ea-87a7e8de9ede)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/0e0efeae-a67f-4aed-89b1-87974b16d93c)
