### ISSUE TITLE
V2 - Company Not Signed CLA - Creating cla manager designee failed error is displayed when user is already cla-manager-designee for the company and project

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1571]
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group
3. Generate template

**Steps to Follow**
1. Login to Github as corporate contributor who has LFID and is cla-manager-designee for the company and project
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/ed31947b-59a0-4c63-b647-fcbf8974657b)
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Select Company that has not signed CLA for the project
9. Click Proceed
10. Click Yes
11. Click Proceed
12. Login
13. Observed that error message "Creating cla manager designee failed for Project SFID: a091700000AFnivAAD" is displayed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c8b4969a-f07e-4405-9ce0-9273eeb9d25d)

**Comment by nirupamav** [comment]
Verified that the issue is fixed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/1c23496a-1969-4902-9c09-38b5acf4cb45)

**Comment by nirupamav** [comment]
Observed that the issue is still reproducible when CLA Group is at project level and hence reopening the ticket 
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/55ce55cc-8243-46bb-a22f-7c14dc4ad6f2)

**Comment by nirupamav** [comment]
Verified and observed that issue is still reproducible
Foundation Level CLA Group
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/483cb7b8-627e-43a7-97be-7891c0b00e96)

Project Level CLA Group
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/5c680e4b-f0a2-4cfd-8b44-2ccaff61c76f)

**Comment by nirupamav** [comment]
**_Still facing the issue_**

**Project Level**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/449f21c4-552e-4146-9840-af0d0b11b254)

**Foundation Level**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/2ddddf22-d6f0-4889-895d-69ea912a24e1)

**Comment by wanyaland** [comment]
@amolsontakke3576 . For this use case I have returned a 409 and UI change is needed to allow to access corporate console for either conflict(409) or a success(200) which is a change you had asked for

**Comment by amolsontakke3576** [comment]
@wanyaland I am working on the status code changes and moved this ticket to Dev. @nirupamav please track this ticket.

**Comment by nirupamav** [comment]
@amolsontakke3576 @wanyaland 
I see a different error message this time. If user is already a cla-manager-desginee, shouldn't the user be redirected to Corporate Console instead of displaying a message. Contributor will not understand this message and is not sure what to do next.
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/174755df-44f2-4f15-9049-10e6a2709c90)

**Comment by amolsontakke3576** [comment]
@nirupamav I just raised PR for status code related change so can you test after this merged @wanyaland may not know about this frontend change.

**Comment by nirupamav** [comment]
**Verified that the issue is fixed. User is redirected to Corporate Console**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/cfc36613-f35e-429b-8789-cd0d766003f7)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/102883b5-10bf-44d0-9fa7-47718b079313)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/3a3d484f-7279-405c-897a-a3ad8ea8a5f5)
