### ISSUE TITLE
V2 - company admin details are not displayed in the acknowledgement message for user to follow up with them

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1573]
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group
3. Generate template

**Steps to Follow**
1. Login to Github as corporate contributor who has LFID and is cla-manager-designee for the project and company. Also make sure user is logged in to LFX member portal in the same browser session in same or different tab
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Select Company that has not signed CLA for the project
9. Click Proceed
10. Click No
11. Click on Contact Company Admin
12. Observed that company admin details are not displayed in the acknowledgement message. Message says to follow up with the company admin and if contributor is not aware of the company admin contributor will not be able to follow up with them

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/435eed13-81d0-42df-98ce-734f588803a8)

**Comment by amolsontakke3576** [comment]
@wanyaland Can you please add Company Admin details in the response of the below endpoint so that I can show it on the dialog?

`https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/user/d3b74e07-ce7c-42b7-abe4-6e9acc7ee402/invite-company-admin`

**Comment by amolsontakke3576** [comment]
@nirupamav What if the company having a multiple admins? how can we show it on dialog modal?

**Comment by nirupamav** [comment]
@amolsontakke3576 
Company can have upto 3 admins and not more than 3. In LFX corporate console admin details were shown. I am not sure if anything has changed now but earlier that is how it worked. Right now there is a blocker in corporate console I am not able to provide you the screenshot.

**Comment by nirupamav** [comment]
Verified that company admin names are displayed. However there are some minor issues which are tracked in #1599
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/1b3bbd63-6a36-4ea1-912f-cb5c987de1f8)
