### ISSUE TITLE
V2 - Company Not Signed CLA - Appropriate error message is not displayed when session expired

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1577]
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group
3. Generate template

**Steps to Follow**
1. Login to Github as corporate contributor who has LFID and is cla-manager-designee for the project and company. Also make sure user is logged in to LFX member portal in the same browser session in same or different tab
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Select Company that has not signed CLA for the project
9. Leave it idle for few hours or keep performing some actions until bearer token session expires
10. Click Proceed
11. Click Yes
12. Observed error message **API-GW : JWKS Plugin - Authorization header is missing**. Appropriate user friendly error message should be displayed and user should be asked to login again or redirected to SSO login page to proceed further
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/b7205952-9606-4397-8f54-23eb0d66761e)

**Comment by amolsontakke3576** [comment]
@rinkeshbhutwala Can you please update the above error message for below endpoints?
POST : v4/company/' + companyId + '/claGroup/' + projectId + '/cla-manager-designee
PUT : v3/users
GET : v2/project/' + projectId
POST : v1/user/gerrit

**Comment by rinkeshbhutwala** [comment]
@amolsontakke3576 If you are not passing authorization token while calling the API then only you get this response see if you can pass the token never get **API-GW: JWKS Plugin - Authorization header is missing.**  error message.

**Comment by nirupamav** [comment]
I kept the page idle for 2.5 hrs and was able to proceed further. If I face this issue again will reopen the ticket
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/f7e44962-bdb5-4d80-ac65-fd03c5e98a29)
