### ISSUE TITLE
V2 - Gerrit - CLA Not Signed - Appropriate error message is not displayed when trying to become cla manager designee

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1580]
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add gerrit instance
3. Generate template
4. Clone the gerrit repository and commit an changes

**Steps to Follow**
1. Login to gerrit
2. Click on the New Contributor Agreement from Gerrit Agreements page
3. Click on Please review the agreement
4. Change the url accordingly to navigate to corporate contributor console (Require this step in dev environment)
5. Click Auhtorize link 
6. Login with contributor LFID
7. Contributor is redirected to Select Company page
8. Select Company that has not signed CLA for the project
9. Click Proceed
11. Click Yes
12. Observed that cla manager designee role is not assigned to the user and below error is displayed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/e1adb200-a333-4264-be34-f62c77b0ea2a)

**Comment by amolsontakke3576** [comment]
@wanyaland Can you change the error message or update the status code?

**Comment by wanyaland** [comment]
@amolsontakke3576 Is this gerrit flow now fixed ?

**Comment by nirupamav** [comment]
Verified that user is able to execute this flow without any errors and role is assigned as expected
