### ISSUE TITLE
V2 - UI issues in acknowledgement message displayed after company admin is contacted

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1599]
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group
3. Generate template

**Steps to Follow**
1. Login to Github as corporate contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Select Company that has not signed CLA for the project
9. Click Proceed
10. Click No
11. Click on Contact Company Admin
12. **Issue1** Usability Issue - Observed that admin names are not in bold
13. **Issue2** When there are less than 3 company admins empty data with comma's are displayed
**_Note: It is confirmed by Pranab that there will be at least 1 company admin for the company and there will not be a scenario where there are no company admins_**

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/62eb0880-2526-42d0-80e3-609bb90031be)

**Comment by amolsontakke3576** [comment]
@nirupamav can you please check the company admin list comes from backend having a valid name?

**Comment by nirupamav** [comment]
@amolsontakke3576 
Looks like it is data issue
![image](https://user-images.githubusercontent.com/60865903/90494216-e26b1500-e160-11ea-8217-93c235312d99.png)

**Comment by nirupamav** [comment]
**Observed that comma is still displayed and also admin names are not in bold. This was a case where one of the company admin was empty**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/e46331df-4d3d-4d04-8309-077ec4baa0ef)

When we have proper data that that last comma is not displayed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/1c92f192-f7a2-4608-a733-ebde164618e2)

**Comment by nirupamav** [comment]
Verified that issue is fixed.
@pranab-bajpai 
Acknowledgement is as per wireframe. However admin name is not in bold. In Corporate console it is in bold. Should the same be implemented in contributor console
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/8d836e6c-e235-49d1-a5d6-9b932d50fe01)

**Comment by nirupamav** [comment]
@amolsontakke3576 
As discussed in Standup call the acknowledgment should match with the one in corporate console, hence reopening the ticket. Below is link for wireframe of Corporate console
https://wireframepro.mockflow.com/view/corporate-console#/page/D7d2ec781fb7f0fd48a66adfadce7f41b

**Comment by amolsontakke3576** [comment]
@vinod-kadam Verified and moved to QA done 
![Screenshot from 2021-01-04 15-41-32.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/d1b58c32-363f-4c2b-baac-38a47c6a8731)
