### ISSUE TITLE
Corporate Console - Add Company Notification

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#160]
**Corporate Console - Company Search - Add Notification**

This feature adds additional user feedback once the user adds a company.

**Background**

The current implementation does not provide guidance or steps on how to proceed after the user adds a new company.  The redesigned UI will include the updated user experience which shows a pop-up dialog indicating:

Success!
Your company <name of company> is added to EasyCLA!
As the individual who created the company, other company CCLA managers and signatories may request to join this company.  Please respond to these requests by following the links in the notification emails.

**User Story**

As a CCLA Signatory:
1. I need to know what my responsibilities are as a CCLA Signatory so that I approve access to the company for others in a timely manner.
2. I need to know what the next step is after I have the access I need for my company within EasyCLA so that I can sign for my projects quickly and easily

**Tasks**
1. Update UX to include a confirmation dialog box

**Acceptance Criteria**

1. UX provides the above features and works as advertised
2. Project manager review and sign-off
2. Demonstrate the set of capabilities to the product team while the code is
   running in the STAGING environment.

**References**
Corporate Console - Join or Add Company - https://confluence.linuxfoundation.org/pages/viewpage.action?pageId=28484537#PRD-EasyCLAv1Performance&UIUpdates-CorporateConsole.1

**Related**
Frontend search/add company issue: https://github.com/communitybridge/easycla/issues/158

**Comment by pranab-bajpai** [comment]
This issue is duplicated by #361 and #362 . Hence closing
