### ISSUE TITLE
V2 - Issues when new project is added and CLA group is created for new project when already CLA group is signed at Foundation level

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1600]
1) Create CLA Group at Foundation(or parent) level from project console
2) Sign CLA at foundation level from corporate console
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/24e41ec6-d1c3-4d47-8216-46180aa41a8c)
3) Now add new project under the foundation(or parent project)
4) Create CLA group for the new project
5) Now in Corporate console view changes from foundation level to project level which is confusing for corporate console users. Also scenario when CLA group is deleted and there is only 1 cla group after deletion, should be considered it should still be considered as CLA group at project level

@pranab-bajpai @dealako 
When CLA is signed at foundation level and later add new project to foundation, should we restrict creating CLA group for the new project and automatically enroll project to existing CLA Group or should we able to create CLA group for the new project?

**Comment by dealako** [comment]
Step 4 listed above should not be allowed as there is a "Foundation Level" CLA Group already established.

{code}
1.                                           |--> 'Project Group A'      --- Assigned To --> 'CLA Group A'
2. Add project under                  |------> 'Project A1'  --- Not Assigned to any 'CLA Group'
ok
3. Add project to CLA Group    |-------> Project A1 --- Assigned to --> 'CLA Group A'
3.1. Now we have 'CLA Group A' with 'Project Group A' and sub-project 'Project A1'
4. Create CLA Group for the new project ----> Should now be allowed to assign 'Project A1' to any other CLA Group
{code}

Please confirm.

**Comment by ashav-github** [comment]
@dealako I tested this today on dev and the newly added child project in the foundation level cla group was not automatically added(means its just listed under projects where checkbox is unchecked). I had to add it manually on the cla overview page. **Is it fine?**

And after adding it to the cla group there is no way to perform step4 as mentioned by you: "Create CLA Group for the new project ----> Should not be allowed to assign 'Project A1' to any other CLA Group"

**Comment by vinod-kadam** [comment]
This was discussed in the standup, new project should not be added automatically to the foundation level cla group.
The initial bug logged by Nirupama - the usecase it not valid now.
So, closing this ticket.
