### ISSUE TITLE
Update to contributor console landing page to allow download and preview of CLA templates

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#1604]
- [ ] Wireframe for the new landing page - https://wireframepro.mockflow.com/view/app-easycla#/page/Dab111f6a971bc1cd42c819a1770bc817
- [ ] Will need APIs for downloading templates. 
- [ ] Preview will look like this wireframe - https://wireframepro.mockflow.com/view/administrative-console#/page/Dcf6852d486db3fbc656e960c0fe80c36

**Comment by dealako** [comment]
When determining the PDF link:

1. Load the CLA Group - (project_id is the CLA Group ID)
2. From CLA Group JSON, ICLAs will be in an array under `project_individual_documents`, see:

![Screen Shot 2020-08-19 at 8 20 05 AM](https://user-images.githubusercontent.com/519609/90654082-d7fa5b00-e1f4-11ea-91ad-bdd0203ed040.png)

The lastest and most recent document will be the last element in the array. In most cases, there will be only one element in the array. If zero, then ICLA is not enabled for this CLA Group (you can confirm with the `project_icla_enabled` flag in the CLA Group JSON.  The S3 document URL is under the key: `document_s3_url`

For CCLA, the same is true. Look at the array values under: `project_corporate_documents` when the `project_ccla_enabled` flag is true.
