### ISSUE TITLE
Company Status - UI

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#161]
**Corporate Console - Company Status - UI Enhancements**

Enhance the corporate console company view to allow CCLA signatories to view the status and perform the next-steps after joining a company.

**Background**

The current implementation provides a company view but does not show the current status. The redesigned UI will have a view that includes the current status and actions:

1. The company name will be displayed
2. The status will be displayed to include the current state, such as "Joined", "Pending Approval", or "Rejected"

**User Story**

As a CCLA Signatory:
1. I need to know what the status of my join-company request so that I can understand where the process is
2. I need to know what the next step is after I have the access I need for my company within EasyCLA so that I can sign for my projects quickly and easily

**Tasks**
1. Update UX to include a table view to include the company name, status and Action columns
2. Call backend company and signature endpoints to fetch appropriate results.
3. Show progress indicator when the table data is loading
4. Display status based on the database record details
5. Invoke actions from the table view based on existing workflow logic. When appropriate, indicate actions that will be taken by the EasyCLA system and any follow-up steps required.

**Acceptance Criteria**

1. UX provides the above features and works as advertised
2. Product manager review and sign-off
2. Demonstrate the set of capabilities to the product team while the code is
   running in the STAGING environment.

**References**
Corporate Console - Successful Join and Follow-Up - https://confluence.linuxfoundation.org/pages/viewpage.action?pageId=28484537#PRD-EasyCLAv1Performance&UIUpdates-CorporateConsole.1

**Comment by dealako** [comment]
Notes on User Join / "Joined", "Pending Approval", or "Rejected"
User not part of a company: the user's user table record has an `empty user_company_id` field in their user record.

**Comment by jpalmerLinuxFoundation** [comment]
> * If the user is already part of a company (meaning the user has a `user_company_id` entry in their user record), _Can they join another company?_

1. Users with a value in their `user_company_id` field in the users table have confirmed their affiliation with the company that whitelisted them. I don't think this is related to this feature request.

**Comment by jpalmerLinuxFoundation** [comment]
Based on the data (not the code), I would guess that the process of joining a company today to managed by the cla-*-company-invites table.
**Today**
1. When someone types in the company exactly as it is written in the cla-*-companies.compan_name field the user is provided the option to "Request Access" to join the existing company
2. If the user presses "Request..." then a record is created in the cla-*-company-invites table with the user's cla-*-users.user_id in the user_id column, and the company they're requesting access to 
 (cla-*-companies.company_id) in the cla-*-company-invites.requested_company_id field.
3. When a current CLA Manager and/or Signatory approves the request to join then the user's LF ID is added to the cla-*-companies.company_acl list.

Note: If they are rejected, the user is never told (as far as I can tell). When the user is waiting for approval/rejection nothing is shown on the screen. There is no way for the user to tell if anything happened.

**Comment by jpalmerLinuxFoundation** [comment]
![image](https://user-images.githubusercontent.com/51214959/65292587-990fe100-db1d-11e9-9604-dc93cd91d946.png)

**Comment by CareyLF** [comment]
@jpalmerLinuxFoundation I have the same question that David had: Why would a user be rejected? What does "rejected" mean?

**Comment by jpalmerLinuxFoundation** [comment]
@CareyLF @dealako, In the process of joining a company. It is possible for anyone to request to join. If they make the request by mistake or are trying to join for some unknown/invalid reason, I want to not only give the Company ACLs the ability to reject their request. The net change here is that we also update the request on the requester side to "(rejected)". If we don't let them know we've responded to their request then they contact support and have to find out from LF Support that they were rejected. Now they possibly feel embarrassed and defensive. I would like the requester to handle this within their company, if possible. Please let me know if you have follow up questions.

I'm open to changing the verb we're using. "Rejected" is a bit harsh.
