### ISSUE TITLE
V2 - Company Not Found - Organization exists message is not displayed even if organization exists when searched by partial text

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1614]
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group
3. Generate template

**Steps to Follow**
1. Login to Github as corporate contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Click on building icon
9. Click on Organization not listed? + Click Here
10. Enter value BlackBean in Enter Organization Name field
11. Observed that Organization exists message is not displayed
**_NOTE: Observed the same issue with Organization website_**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/ef7fc0d7-46ce-4767-aa48-178da0fd2fa0)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/b236f7e1-afa4-4e45-825a-c8534c754267)

**When complete name is provided it works fine**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/2a4924ac-be52-4638-a633-b3b2761dbd2b)

**Comment by amolsontakke3576** [comment]
@nirupamav Now this ticket is deprecated due to change in workflow mentioned in ticket #1613
