### ISSUE TITLE
EasyCLA email from contributor console to potential CLA manager not being sent.

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#1619]
## Summary

The email sent from the form to request your company added to the list is not being sent to the cla manager.

## Background

1. In the contributor console, select "Corporate"
1. Select "company not on the list"
1. Select "No" to becoming CLA manager.
1. Fill in required form.
1. Notice cla manager does not receive email.

## Screenshots
 
![image](https://user-images.githubusercontent.com/46732999/90682715-6392dc80-e233-11ea-972b-3e3f51a2a821.png)
![image](https://user-images.githubusercontent.com/46732999/90682752-74435280-e233-11ea-896a-bc763ddb9c0b.png)
![image](https://user-images.githubusercontent.com/46732999/90682780-81604180-e233-11ea-9dce-6da50deab626.png)

## Environment
PRODUCTION

## Additional Context
No emails are showing as sent in the mandrill logs. No test email was received to my email.

**Comment by dealako** [comment]
@WillsonHG - @nirupamav tested and worked for us in DEV. I pushed a PROD release today which may include this fix.  Can we confirm once more??

**Comment by patrickofriel-wk** [comment]
My CLA manager is not receiving the emails. I tried at the beginning of this month and then again yesterday

**Comment by rinkeshbhutwala** [comment]
I have tested on dev and it looks like working fine.

![Screenshot from 2020-09-01 16-00-27.png](https://images.zenhubusercontent.com/5f20ee93f9a45844ef8dfce5/013bada5-2ee0-42fa-b6c8-e1d69329a07a)

**Comment by nirupamav** [comment]
@WillsonHG 
Can you please help me with the test data for this as with my user in dev I am not able to see this issue

**Comment by nirupamav** [comment]
@WillsonHG @dealako 
**Tested in Prod and observed acknowledgement message is displayed but email is not sent. Also observed that API call returned 200 but with error response**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/1e0078a1-60af-454f-a8a3-707a9a47f8a1)


![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/6dafaa0c-15f2-4d45-94ab-2d53f13a5206)


![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/dbc1360a-9a11-4873-8961-a5514a26b556)

**I tested again in Dev env and received the email but CORS error is displayed**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/932d0f8a-93d3-4da2-90e3-1d7901ab129d)


![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/2627dc3f-8a7a-4110-ad72-b462762669c2)

**Comment by dealako** [comment]
Issue is resolved. Needed to update the PROD projects tables by running the migration script that @wanyaland wrote - script updates the project_name_lowercase column for all records.  After doing this, @WillsonHG was able to receive the emails.
