### ISSUE TITLE
Manger View Signature Table Updates - UI 

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#162]
**Project Console - View Signature Table Updates - UI Enhancements**

As a project manager, I want an enhanced table view for viewing and paginating CLA signatures.

**Background**

The current implementation provides a simplified table view listing the project signatures. Currently, the table sorting is broken and does not provide searching, pagination or export of CLA signatures. The redesigned UI will have the following new/enhanced features

1. The table view will be paginated so that a limited number of entries will be shown to the project manager. The manager can navigate through previous and next pages of data to display additional records. The manager can select the number of records to see each page.
2. The table will include the user's LFID, when present. This is a new column currently not present on the existing view.
3. The table view will allow column sorting on all columns

**User Story**
As an Open Source Project Manager:
1. I need to be able to view the full set of signatures and whitelisted contributors who are interacting with my project.
2. I should be able to go to the next page by clicking the subsequent page number or clicking the "Next" button.
3. I should be able to go to the previous page by clicking the previous page number or clicking the "Previous" button.
4. I need to be able to see the user's LF ID

**Tasks**
1. Update UX to include an enhanced table view meeting the above user-story requirements.
2. Call backend company and signature search endpoints to fetch results.
3. Show progress indicator when the search is executing and the user is awaiting the results.
4. Provide the capability to display the results in a paginated view (see references screenshots) 
5. Provide the capability to sort the results by column in a paginated view  (see references screenshots).

**Acceptance Criteria**

1. UX provides the above features and works as advertised
2. Project manager review and sign-off
3. Demonstrate the set of capabilities to the product team while the code is
   running in the STAGING environment.

**References**
Project Console - Signature Table View - https://confluence.linuxfoundation.org/pages/viewpage.action?pageId=28484537#PRD-EasyCLAv1Performance&UIUpdates-ProjectConsole.1

**Comment by jpalmerLinuxFoundation** [comment]
@dealako @ngozi-ekekwe, I think we need to minimize what we're delivering here considering the DB limitations. Please set the default list to 100 per page (no option to change) and keep the pagination

**Comment by jpalmerLinuxFoundation** [comment]
![image](https://user-images.githubusercontent.com/51214959/64994524-71f7ac00-d89e-11e9-875f-4edb22461cb5.png)
