### ISSUE TITLE
[Regression] V2 - CLA Not Signed - Appropriate message is not displayed when cla manager request is sent to user without LFID and email is not sent to the user

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1625]
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group
3. Generate template

**Steps to Follow**
1. Login to Github as corporate contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Select Company that has not signed CLA for the project
9. Click Proceed
10. Click No
11. Enter name and email of user who does not have LFID
12. Observed that appropriate message is not displayed. Also invite email is not sent to the user 
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/632e8657-c758-4a9d-ae6a-df9263005847)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/d225940f-6339-45ba-8250-4a51d3d5c29f)

**Earlier below message was displayed which indicates user about invite email to create account**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c0aa5f2b-90d1-4a98-890d-54e40035abe9)

**Comment by wanyaland** [comment]
@nirupamav There was a consensus for this sometime back but shall need clarification. That for this use case from contributors we should not send emails.. explaining the withdrawal of the emails sent to users that have no LFID . @pranab-bajpai can clarify

**Comment by dealako** [comment]
Contributor should send email to the prospective CLA Manager - email should include a link to how to sign-up.

**Comment by nirupamav** [comment]
Email is sent however appropriate message is not displayed. Appropriate message should be displayed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/8abc569d-7f2c-445f-a2d9-6fa967a10c69)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/cc9313b0-a38b-43e8-9fc1-d3939caf7587)

**Comment by nirupamav** [comment]
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/6f5d8afb-0d09-4be3-85d1-90e6252fd11b)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c9f73f60-e0f9-4399-8597-e87b440f4adc)

**Comment by dealako** [comment]
@amolsontakke3576 - please review and update. @wanyaland has indicated that it has been updated: "Because now if no LFID is found it returns a 202 response".  Please update and move to QA.

**Comment by wanyaland** [comment]
@amolsontakke3576 Could you kindly update the UI for this use case when user has no LFID -> Invite Company Admin flow. This happens to return a 202 response and can be updated accordingly

**Comment by amolsontakke3576** [comment]
Tested and work fine.
![Screenshot from 2020-09-11 10-12-50.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/f330944d-1996-4e34-9187-ea559d595ea4)

**Comment by nirupamav** [comment]
**Verified that appropriate message is displayed but email is not sent and hence reopening the ticket**

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/6bec4f12-d5ea-43ca-8561-fc3b3dcdb9e3)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/59af163c-2c3d-4963-b989-c979c06c2a3b)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/640a2dc8-a86c-4234-b5f2-cf56faab5da7)

**Comment by dealako** [comment]
@makkalot I think we just need to address the " email is not sent " part now for the Invite Company Admin. There is an invite company admin endpoint: https://github.com/communitybridge/easycla/blob/master/cla-backend-go/swagger/cla.v2.yaml#L1927 which maps to this handler function: https://github.com/communitybridge/easycla/blob/master/cla-backend-go/v2/cla_manager/handlers.go#L179.

We send the email when the user doesn't have an LFID: https://github.com/communitybridge/easycla/blob/12f96b142ff68e6d86dff3a563a6c72463adff19/cla-backend-go/v2/cla_manager/service.go#L914-L938.

Work with @nirupamav or @wanyaland or even @amolsontakke3576 if you need help understanding the flow or setting up a quick test scenario.

**Comment by makkalot** [comment]
Since the system was not working properly couldn't test the issue hands on but did some digging into logs 

```
Field	Value
@ingestionTime	
1600151229127
@log	
395594542180:/aws/lambda/cla-backend-go-api
@logStream	
2020/09/15/[$LATEST]8186eecca1884edd9b2feb67e674788a
@message	
{"email":"lokeshk+qa4@proximabiz.com","functionName":"SendUserInvite","inviteType":"userinvite","level":"error","msg":"CreateUserInvite failed[POST /invites/sendinvite][400] createUserInviteBadRequest \u0026{Code: Message:}","organizationID":"6b1079c6-2e11-4b0a-b583-38cc3adaa3ee","projectID":"a096s000000373tAAA","roleName":"cla-manager-designee","scope":"project|organization","subject":"EasyCLA: Invitation to create LF Login and complete process of becoming CLA Manager with cla-manager-designee role","time":"2020-09-15T06:27:07Z"}
@timestamp	
1600151227983
email	
lokeshk+qa4@proximabiz.com
functionName	
SendUserInvite
inviteType	
userinvite
level	
error
msg	
CreateUserInvite failed[POST /invites/sendinvite][400] createUserInviteBadRequest &{Code: Message:}
organizationID	
6b1079c6-2e11-4b0a-b583-38cc3adaa3ee
projectID	
a096s000000373tAAA
roleName	
cla-manager-designee
scope	
project|organization
subject	
EasyCLA: Invitation to create LF Login and complete process of becoming CLA Manager with cla-manager-designee role
time	
2020-09-15T06:27:07Z
```

and there's some older error message which is like : 

```
Field	Value
@ingestionTime	
1599818781219
@log	
395594542180:/aws/lambda/cla-backend-go-api
@logStream	
2020/09/11/[$LATEST]6cc913c8bec74977ac511019e5198df3
@message	
{"level":"error","line":"CreateUserInvite failed","msg":"json: cannot unmarshal string into Go struct field Invite.created_at of type int64","time":"2020-09-11T10:06:12Z"}
@timestamp	
1599818772193
level	
error
line	
CreateUserInvite failed
msg	
json: cannot unmarshal string into Go struct field Invite.created_at of type int64
time	
2020-09-11T10:06:12Z
```

then seems we  return nil on error : https://github.com/communitybridge/easycla/blob/eb95f079d928d76df942c7539b6cc598f5466316/cla-backend-go/v2/acs-service/client.go#L125

I think this might be the issue here

* the service returning cryptic message not telling what's wrong
* us not handling the error condition

@dealako what do you think ?

**Comment by nirupamav** [comment]
@makkalot @dealako @wanyaland 
Observed that email is sent. Hence moving the ticket to QA Done
However observed that in UI request failed error is displayed and the issue is tracked in  #1815
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c45489fb-df3e-4273-ae27-d66f3d7a05f7)
