### ISSUE TITLE
V1 - Project Console - Not able to update project name

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1626]
1. Launch Project Console
2. Login
3. Create a CLA Group
4. Observed that not able to update CLA Group name
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c524a7d0-4abf-43a7-a522-336a58f3fe67)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a285d462-aade-41d5-b715-206086450656)

**Comment by dealako** [comment]
V1 - review and update the API and form handling logic.

**Comment by nirupamav** [comment]
**Verified that the issue is fixed**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a5567e1c-9f69-4456-8a76-468b31d92503)
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/68110b34-4480-4660-8495-df2edee3721d)
