### ISSUE TITLE
V2 - Company Not Signed - Authorization header is missing is displayed when user navigates back in browser and tried to proceed further

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1629]
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group
3. Generate template

**Steps to Follow**
1. Login to Github as corporate contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Select Company that has not signed CLA for the project
9. Click proceed
10. Click yes
11. Click proceed
12. Navigate back in browser without logging in to SSO
13. Select company
14. Click Proceed
15. Click Yes
16. Observed that Authorization header is missing message is displayed

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/6a6fd5d9-d340-4e78-9f09-c2bb3c69a12b)

**Comment by amolsontakke3576** [comment]
@dealako As per our discussion in standup, this is an issue from auth0.

**Comment by amolsontakke3576** [comment]
@vinod-kadam Verified and moved to QA done
