### ISSUE TITLE
V2 - Company Not Signed - Proceed button is disabled when user navigates back in browser

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1630]
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group
3. Generate template

**Steps to Follow**
1. Login to Github as corporate contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Select Company that has not signed CLA for the project
9. Click proceed
10. Click yes
11. Click proceed
12. Navigate back in browser without logging in to SSO
13. Observed that company name is displayed, however proceed button is disabled
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/f1eaec20-cd91-4e3c-9a62-3e5d70dfff4e)

**Comment by nirupamav** [comment]
@amolsontakke3576 
Now company is not selected after navigating back in browser, but Proceed button is enabled I am able to proceed further and Authorization Header is missing message is displayed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/e6fc9e50-d66b-4896-8683-feb9c9ac0406)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c6fadf75-17a4-45bc-b8dc-5a89594d8887)

**Click Yes**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/047d3a9e-ec9a-45bc-838e-c22d21d90d75)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/d0e81cc6-0069-4d4c-bfb1-202c6b02a908)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/b6601aa1-0174-423d-9536-a55bdb254df4)

**Comment by nirupamav** [comment]
**Issue is still reproducible**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/88bde6ae-d2b4-48fd-99b1-9ef2cc84e2f7)

**Comment by amolsontakke3576** [comment]
@dealako It looks like issue is from the Auth0 site. can you please look into this? 
This mostly happens when you redirect to the LF page and hit the browser back button.

**Comment by amolsontakke3576** [comment]
@vinod-kadam Verified on dev and moved to QA done.
