### ISSUE TITLE
V2 - Go Back and Close icon behavior is different in You will need to create an SSO account dialog

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1634]
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group
3. Generate template

**Steps to Follow**
1. Login to Github as corporate contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Select Company that has not signed CLA for the project
9. Click proceed
10. Click yes
11. Observed that Go Back and Close X behavior is different
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/e1827b75-66da-4617-8b34-e4d3adf23765)

**Comment by dealako** [comment]
Discussed with Pranab - current behavior is ok.  Closing ticket.
