### ISSUE TITLE
V2 - User is able to close the dialog when cla manager settings is in progress

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1635]
Observed that user is able to close the dialog by clicking on (X) close icon while cla manager settings is in progress
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/73aa487c-fd7b-4f96-ad16-bb0314ca3ccb)

**Comment by dealako** [comment]
Discussed with Pranab:

- Remove close icon when it is generating...
- Ok to keep close icon when generation is complete dialog.

**Comment by nirupamav** [comment]
Verified that Close(X) is not displayed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/cd525772-2c1d-4d8f-b3c4-e93b9ad74507)
