### ISSUE TITLE
V2 - Preview of templates is not available in Contributor Console dashboard

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1638]
**Observed that preview of templates is not available in Contributor Console dashboard. As mentioned in ticket #1604 preview should be available**

**_Both CCLA and ICLA enabled_**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/d8c31063-1f5b-4d62-9c42-3f311161305c)

**_Only CCLA enabled_**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/32ed98ee-66af-43b7-b76c-9a22bf346baa)

**_Only ICLA enabled_**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/7c19a5e2-0bd9-43b1-b4ab-ba201e206451)

**Comment by dealako** [comment]
@amolsontakke3576 let's get this integrated by scrum on Monday.

**Comment by nirupamav** [comment]
Observed that preview is still not available. Tested in both Firefox and Chrome in windows10. I am assuming that preview means viewing the template on the corporate console dashboard page itself, instead of downloading the pdf. If I my understanding is wrong please let me know the expected behavior for this

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/94027144-472e-45e3-bedc-ade081c34e48)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/bf7caa0c-76da-4229-ad94-45a525997247)

**Comment by amolsontakke3576** [comment]
@nirupamav Initially there were `Preview and Download` button but later it changed to the only `Download` so the no preview functionality and only download for now.

**Comment by nirupamav** [comment]
@amolsontakke3576 
Will this be implemented later or it is not supported at all

**Comment by amolsontakke3576** [comment]
I guess not supported at all but still confirm with @pranab-bajpai

**Comment by dealako** [comment]
Stakeholders have indicated that preview is not required for Contributor Console.  Closing this ticket.
