### ISSUE TITLE
V2 - Company Not Found - Usability Issue - Error message should include supported regex details

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1642]
Observed that error message is displayed when invalid Organization website and names are provided, however message does not have information of the accepted regex or characters

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/2ee13adf-22cf-434c-885a-3663e7d78aa6)

**Comment by nirupamav** [comment]
**_Tested and observed below issues_**
**Error message grammar needs to be corrected. are allowed should be removed or sentence should be corrected to included are allowed words**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/5e2f1de4-ca99-4287-84ce-ec2827b0b58c)

**Observed that error message does not include regex for website field**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/f739e133-d816-438d-8f2f-03c1f83a8433)

**Working scenarios**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/aa56ddc9-a6c0-42fb-a1f1-070feabbcd8b)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/6b194f41-a837-4607-a625-88dabfcad264)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/7fb553fe-16db-430f-b84d-48a90fb380dd)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/27d542aa-d3b9-4c62-a6fa-502e0674688e)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/f8b970e2-074a-4da8-a8e5-e8e668777f61)

**Comment by nirupamav** [comment]
**Tested and observed in below scenarios still regex is not displayed for Organization website**

**_Example1_**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/f2979583-558b-4385-b668-d7d8e27042d2)

**_Example2_**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/1eadd23f-7085-4a35-847e-2b9356adfe35)


**Grammar issue is resolved**
@pranab-bajpai Could you please confirm if this fine
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/5b09c0f6-fd87-4960-b450-d8372f2d932e)

**Comment by dealako** [comment]
@amolsontakke3576 let's make sure upper and lower cases are allowed. Let's allow dashes (-).  Please update and move to QA.

**Comment by amolsontakke3576** [comment]
@dealako For this, we need to change regex from org service for below endpoint 

Request URL: https://api.dev.lfcla.com/v3/organization/search?websiteName=WWW.ACTOFGOD.COM
Request Method: GET
Status Code: 422 

{"code":605,"message":"websiteName in query should match '^((http|https):\\/\\/)?(www.)?[a-z0-9]+(\\.[a-z]{2,}){1,3}(#?\\/?[a-zA-Z0-9#]+)*\\/?(\\?[a-zA-Z0-9-_]+=[a-zA-Z0-9-%]+\u0026?)?$'"}

**Comment by dealako** [comment]
@dealako will go to @niravpatel27 and ask why:

- Adding an uppercase URL works
- But, can't search for upper case URL...

**Comment by nirupamav** [comment]
@amolsontakke3576 
The ticket was to display regex information. I tried below and still regex is not displayed though I have given valid website url. 
As an end user I am not able to understand the mistake with the data I provided, as I have provided valid website url

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/267c5ede-02e0-4950-8807-7f608ac7f338)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/52759c00-5dc7-42cd-9839-40558944dea5)

**Comment by amolsontakke3576** [comment]
@dealako  @wanyaland org service updated regex to allowed some more characters
Below is the updated regex
`'^(?:http(s)?:\/\/)?[\\w.-]+(?:\\.[\\w\\.-]+)+[\\w\\-\\._~:/?#[\\]@!\\$&'\\(\\)\\*\\+,;=.]+$'`

**Comment by manishv09** [comment]
Verified today and found working fine, please find the below screencast for reference:
[Uploading... image (2).png ]
