### ISSUE TITLE
EasyCLA Python Emails

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#1649]
## Summary

Cleanup the Formatting in the EasyCLA Python Emails

## Background

Remove the unnecessary line breaks in the email:

![Screen Shot 2020-08-24 at 3.29.59 PM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/845d752a-9a17-4fae-8b02-82c3279e9491)

It looks like the new-lines in the python code are being carried over to the email. See [the alignment in the source code](https://github.com/communitybridge/easycla/blob/master/cla-backend/cla/controllers/signature.py#L433).

Review ALL emails that are generated by python to ensure spacing is correct.

## Expected behavior

A properly formatted email message.

## Screenshots

See above.

## Environment

Please complete the following information:

* Environment: DEV, STAGING and PROD 

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

\(Optional\) Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by nirupamav** [comment]
@dealako @wanyaland 
Could you please provide the list emails generated by Python, so that I can test the format issue in those emails

**Comment by wanyaland** [comment]
@nirupamav These are the emails that should be aligned
- Newly added CLA Manger -v1 
- Email sent to CLA Manager for users requesting to get added to the approval list  -v1 
- Email sent to prospective CLA Manager(identified by contributor) -v1

**Comment by nirupamav** [comment]
Tested and observed that the issue is still reproducible
![image](https://user-images.githubusercontent.com/60865903/91308767-61012b80-e7cd-11ea-9a9a-eaaf366fa25d.png)

**Comment by nirupamav** [comment]
**Issue is still reproducible**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/3f56324a-c618-4ab6-a1b4-2457787ffa92)

**Comment by nirupamav** [comment]
Testing Blocked due to #2032

**Comment by nirupamav** [comment]
Verified that the issue is fixed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/dfca42ca-a91d-4235-b7ba-5d6bacb184e2)
