### ISSUE TITLE
Github checks API uses variable "context"

### ISSUE THREAD

**Issue by emsearcy** [communitybridge/easycla#166]
**Summary**

The Github status API are creating statuses with a variable "context" using the author name or ID. This is problematic because you cannot use the protected branches feature to enforce CLA passing.

**Expected behavior**

There should be a consistent context name, like communitybridge/cla, which shows pass/fail and can be enabled as a required status check using protected branches.

Alternatively, *in addition to* the existing variable context, a "parent" context with a consistent name (e.g. communitybridge/cla) is set which only passes if all the variable statuses pass, and then the non-variable context can be enabled as a required status check using protected branches.

**References**

* https://developer.github.com/v3/repos/statuses/#parameters
* https://help.github.com/en/articles/about-required-status-checks

**Comment by jpalmerLinuxFoundation** [comment]
@dealako, this is something I'd like us to look into more closely once the commitments for this sprint are complete.

**Comment by jpalmerLinuxFoundation** [comment]
@dealako, I've confirmed with Shubhra and Vasu that this needs to take top priority. **Please shelve your current tasks and stories and let's get working on this**.

**Comment by jpalmerLinuxFoundation** [comment]
![image](https://user-images.githubusercontent.com/51214959/63957363-dc5ebe80-ca4d-11e9-8246-80b01ac7e0b6.png)

**Comment by jpalmerLinuxFoundation** [comment]
![image](https://user-images.githubusercontent.com/51214959/63957427-f4ced900-ca4d-11e9-89d3-cbe9103a8d71.png)
