### ISSUE TITLE
V2 - corporate console - Wrong email is sent to company admin when user contacts company admin

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1666]
1. Create CLA Group
2. Contact Company admin through cla-manager/requests endpoint
3. Observed that wrong email is sent to company admin. We are contacting the admin to sign CLA or to assign cla-manager-designee, but the email content says that contributor would like to contribute which is not what we are doing in the flow. Email content needs to be changed

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/f96dc7f3-55f5-4d2b-bb67-dd8da0c99c90)

**Comment by dealako** [comment]
@nirupamav can we discuss this one in our next standup - need clarification on the flow and who we are to notify....  let's ask @pranab-bajpai as well.

is this the case where we don't know who the CLA Manager or CLA Signatory is -> contact Company Admin only?

**Comment by dealako** [comment]
1. From Corporate Console
1. Start CLA Process
1. Not Authorized
1. Identity CLA Manager or Contact Admin -> problem is that we are sending the same email, but the content of the email -> remove the "I am a contributor..."/contributor notes (as the user may not be a contributor).

**Comment by nirupamav** [comment]
Verified that the issue is fixed however there is a minor issue in email and also as per 4th point in above comment by @dealako , the email has to be changed for Identified CLA Manager as well. I have logged another ticker #1866 for this

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/b4ba22ac-7194-4134-8f7e-0399d42245b1)
