### ISSUE TITLE
V2 - Project Console - Need API for Enable branch protection feature

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1667]
**_Need API for Enable branch protection feature for github and gerrit in project console_**

**wireframe** https://wireframepro.mockflow.com/view/administrative-console#/page/D3c036a1a1d2cf80d8ac83dae32036445/sidebar/off
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/74e49c52-0f8b-4db4-b470-60fa05ce5452)

**Comment by dealako** [comment]
@makkalot let's start investigating this feature.  Essentially, we:

1. we will need to adjust the permissions of the EasyCLA GitHub app to allow admin controls to be able to adjust the repository branch protection
2. Via the GitHub API - can we query to see if "branch protection" is set up on the "default" branch? Yes/No?
3. If not setup, can we add branch protection via the API? Yes/No?
4. If yes, can we specify 1) EasyCLA is a required check 2) admins can't by-pass

**Comment by dealako** [comment]
@makkalot I have reviewed your video. Excellent work.  Based on this, can you:

1) identify GH permissions required to 1) check and 2) set/adjust these settings. I need to understand and document these permissions changes...
2) develop a v2 API to determine the branch protection status (as you have done with your CLI example). Input: GH repository, Output: branch protection enabled on default branch true/false. If enabled, is: enforce admin enabled true/false, status checks for EasyCLA enabled true/false
3) develop a v2 API to add/adjust branch protection: Input. GH repository, branch name, enforce admin: true/false, enable status checks (accepts zero or more): [EasyCLA: on, Other check: off, Some other check: on].  If checks on GH repo set, but not in our input list, do not modify.

thoughts?

**Comment by makkalot** [comment]
yeah, makes sense @dealako

**Comment by makkalot** [comment]
Looks like the least perms we need are like : 

- repo
    - public_repo
- admin:org
    - write:org
    - read:org

For more info about the permissions can check : [https://docs.github.com/en/developers/apps/scopes-for-oauth-apps#available-scopes](https://docs.github.com/en/developers/apps/scopes-for-oauth-apps#available-scopes)

**Comment by nirupamav** [comment]
@makkalot @dealako 
Could you please provide the link to API Doc so that I can proceed with the testing of the ticket. I am not able to find the endpoint in https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#tag/github-organizations

**Comment by makkalot** [comment]
@nirupamav it's under `github-repositories` : 

- https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/getProjectGithubRepositoryBranchProtection
- https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/updateProjectGithubRepositoryBranchProtection

**Comment by nirupamav** [comment]
**_Tested and observed below issues_**

**_Get Action_**
**1. Able to fetch data of repository branch protection details when project Id that is not associated with the repository Id is provided in the URI or when invalid project Id is provided in the URI**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/2f97a5db-08be-4d3f-b977-d935194ebcd1)

**2. Error message is not returned in the response when invalid repository Id is provided**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/2eb430c0-581b-416d-b640-16ddff9b0137)

3. In github for the repository, when default branch is master. But when default branch is the branch that I created then status checks is returned with EasyCLA information
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c57bdebb-352d-4056-b3fb-e2dae868cb20)

**_Post Action_**
**1. Able to Post data of repository branch protection  when project Id that is not associated with the repository Id is provided in the URI or when invalid project Id is provided in the URI**

**2. Error message is not returned in the response when invalid repository Id is provided**

**3. When rule is not created in github, not able to enable branch protection**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/0c6c15fa-8e0b-4f92-83f6-833a7de7a760)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/d8ab0271-0c56-499b-825c-3cf6279aa41c)

**4. As per below comment in ticket discussion, Endpoint should accept branch name also as input so that protection can be enabled for that particular branch. As of now it works only for default branch**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/b2d13893-166d-4121-b532-81e49248e2b6)

**5. As per below comment in ticket discussion, existing rules set in github should not be modified. However few settings are removed**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/4891464f-73a3-4f8d-ad3b-d794bce6f217)
`Settings configured from github`
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/27752324-7f14-4552-a5d6-c3b0dd754c0e)

`After updating branch protection from endpoint`
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/cfc8afc0-c928-4248-b4f4-8196f09a5431)

**Comment by nirupamav** [comment]
@dealako @makkalot 
What is he expected behavior in below scenarios
**Payload1**
```
{
  "enforce_admin": false,
  "status_checks": [
    {
      "enabled": false,
      "name": "EasyCLA"
    }
  ]
}

**Payload2**
```
{
  "enforce_admin": false,
  "status_checks": [
    {
      "enabled": true,
      "name": "EasyCLA"
    }
  ]
}

**Payload3**
```
{
  "enforce_admin": true,
  "status_checks": [
    {
      "enabled": false,
      "name": "EasyCLA"
    }
  ]
}
```

**Payload4**
```
{
  "enforce_admin": true,
  "status_checks": [
    {
      "enabled": true,
      "name": "EasyCLA"
    }
  ]
}
```

**Comment by dealako** [comment]
1. PR is created
1. If branch protection is enabled if EasyCLA is true (required to pass before merging) if enforce admin is enabled => cannot bypass the EasyCLA check (unable to merge under all conditions/users)
1. If branch protection is enabled, if EasyCLA is true (required to pass before merging), if enforce admin is disabled => maintainers cannot bypass the EasyCLA check (unable to merge under all conditions/users), but Admins/Owners CAN.
1. If branch protection is enabled, if EasyCLA is false (required to pass before merging), if enforce admin is enabled => maintainers CAN bypass the EasyCLA check (unable to merge under all conditions/users)
1. If no branch protection, => maintainers CAN bypass the EasyCLA check (unable to merge under all conditions/users)

**Comment by dealako** [comment]
regarding #3 - Gerrit doesn't have an API for us to enable "Branch Protection". This is a GitHub only concept.  GitLab may be similar to GH, but Gerrit doesn't have anything like this.

AutoEnable for Gerrit - Gerrit currently does not have an API to allow us to configure this.

**Comment by dealako** [comment]
@nirupamav @makkalot I pushed and merged a PR which adds the branch protection endpoint to ACS-CLI, see: https://github.com/LF-Engineering/acs-cli/pull/313

**Comment by sudhakar-proxima** [comment]
@dealako as per the wireframe, the Enable Branch protection is at Github organization level. However the API needs the repositoryID as a required path parameter.

**Comment by dealako** [comment]
- Create GitHub Organization: https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/addProjectGithubOrganization
- Update GitHub Organization: https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/updateProjectGithubOrganizationConfig

please note the `branchProtectionEnabled` flag in the payload.

**Comment by nirupamav** [comment]
@makkalot @dealako 
Is the https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/updateProjectGithubRepositoryBranchProtection still valid. I am not able to perform any action as it returns 400 even for valid data
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/7d8f1f24-7d0a-4966-b786-1e32a73fa2e9)

**Comment by nirupamav** [comment]
This ticket is no more valid as Branch protection is enabled at org level. The new changes with below endpoints will be tested in #1914
Create GitHub Organization: https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/addProjectGithubOrganization
Update GitHub Organization: https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/updateProjectGithubOrganizationConfig
