### ISSUE TITLE
V2 - Project Console - Need API to un enroll project from CLA Group

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1668]
**Need an API to unenroll the project from CLA Group when user unchecks the project for a CLA Group from Project console** 
**wireframe** https://wireframepro.mockflow.com/view/administrative-console#/page/Da4a85257c8ecb5323c1ab7622bddcf70
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/71dd9156-6e4d-4e64-b1ea-96333ec02055)

**Comment by dealako** [comment]
Submitted PR: https://github.com/communitybridge/easycla/pull/1689

Needs testing still...

**Comment by dealako** [comment]
Deploying to DEV

**Comment by dealako** [comment]
Endpoint /v4//cla-group/{claGroupID}/unenroll-projects

**Comment by nirupamav** [comment]
**_Tested and observed below issues_**

1. Observed that 403 is returned for user with project manager role having scope for all projects. User should be able to unenroll project

2. Observed that 200 is returned. When there is no response 204 should be returned

3. Able to unenroll foundation when CLA group is at foundation level. User should be restricted from un enrolling foundation from foundation level CLA Group

4. Not able to un enroll projects and appropriate error message is not displayed when un enrolling a project from CLA Group
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/16c32bd7-321d-427c-aaa9-c4ca20912c21)

5. 200 without any response message is displayed when trying to un enroll a project which is a new project that is never enrolled with any CLA Group

**Comment by dealako** [comment]
For 2, 200 or 400 should be returned: success/bad input 
Addressed 3 with PR: https://github.com/communitybridge/easycla/pull/1758
Addressed 4 - should work now

**Comment by nirupamav** [comment]
Able to unenroll projects
Testing is still in progress for different scenarios

**Comment by nirupamav** [comment]
**_Tested and observed below issues_**
1. When a project is unenrolled, Sigantures are invalidated however roles are not removed
2. When a project is unenrolled all events related to unenroll are not fetched in the endpoint https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/getFoundationEvents
3. When projects are un enrolled, repositories are not disabled for the project
4. When un enrolle is successful, observed that 200 is returned. When there is no response 204 should be returned
5.

**Comment by dealako** [comment]
Generated PR: https://github.com/communitybridge/easycla/pull/1994 which hopefully will address:

- Add Project to CLA group -> ensures that the cla-manager role is assigned to existing CLA Managers

**Comment by dealako** [comment]
Resolved, closing the ticket.
