### ISSUE TITLE
V2 - Not able to create CLA Group at foundation level 

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1677]
**_Issue1 for foundation with no subprojects_**
We are not able to create CLA Group at foundation level for foundation with no subprojects. I am passing the foundationsfid in project_sfid_list to determine it is foundation level CLA Group

https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/cla-group
**Payload**
```
{
    "icla_enabled": true,
    "ccla_enabled": true,
    "ccla_requires_icla": true,
    "cla_group_description": "Description FoundationLevelWithNoSubProjects",
    "cla_group_name": "FoundationLevelWithNoSubProjects",
    "foundation_sfid": "a091700000AHptZAAT",
    "project_sfid_list": [
       "a091700000AHptZAAT"
    ],
    "template_fields": {
        "TemplateID": "fb4cc144-a76c-4c17-8a52-c648f158fded",
        "MetaFields": [
            {
            "description": "Project's Full Name.",
            "name": "Project Name",
            "templateVariable": "PROJECT_NAME",
            "value" : "Test"
            },
            {
                "description": "The Full Entity Name of the Project.",
                "name": "Project Entity Name",
                "templateVariable": "PROJECT_ENTITY_NAME",
                "value" : "test"
            },
            {
                "description": "The E-Mail Address of the Person managing the CLA. ",
                "name": "Contact Email Address",
                "templateVariable": "CONTACT_EMAIL",
                "value" : "Test@test.com"
            }                       
         ]
    }
}
```

**Response**
```
{
    "Code": "400",
    "Message": "EasyCLA - 400 Bad Request - bad request: invalid project_sfid_list. This project does not have subprojects"
}
```

**Issue2 - for foundation with  subprojects**
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/cla-group
**Payload**
```
{
    "icla_enabled": true,
    "ccla_enabled": true,
    "ccla_requires_icla": true,
    "cla_group_description": "Description Foundation27Aug",
    "cla_group_name": "Foundation27Aug",
    "foundation_sfid": "a091700000AHlbwAAD",
    "project_sfid_list": [
       "a091700000AHlbwAAD","a091700000AHlc1AAD"
    ],
    "template_fields": {
        "TemplateID": "fb4cc144-a76c-4c17-8a52-c648f158fded",
        "MetaFields": [
            {
            "description": "Project's Full Name.",
            "name": "Project Name",
            "templateVariable": "PROJECT_NAME",
            "value" : "Test"
            },
            {
                "description": "The Full Entity Name of the Project.",
                "name": "Project Entity Name",
                "templateVariable": "PROJECT_ENTITY_NAME",
                "value" : "test"
            },
            {
                "description": "The E-Mail Address of the Person managing the CLA. ",
                "name": "Contact Email Address",
                "templateVariable": "CONTACT_EMAIL",
                "value" : "Test@test.com"
            }                       
         ]
    }
}
```

**Response**
```
{
    "Code": "400",
    "Message": "EasyCLA - 400 Bad Request - bad request: invalid project_sfid: [a091700000AHlbwAAD]. These project is not under foundation"
}
```

**Comment by dealako** [comment]
Need to review the create CLA Group validation logic - and if foundation SDFID we need to handle the use-case and not fail...

**Comment by dealako** [comment]
Resolved Validation Issue for Standalone Projects

- Updated validation logic to allow standalone projects to either have no sub-projects as input or have the foundation SFID in the project list.  If the foundation SFID is not provided in the project list, I have automatically added it.

Created PR: https://github.com/communitybridge/easycla/pull/1687

**Comment by dealako** [comment]
@nirupamav I merged the PR - pushed to DEV.  Please review.

**Comment by nirupamav** [comment]
**_Tested and observed below issues_**

**1. Not able to create CLA Group for a project/Foundation without sub projects. Tried both ways by providing project_sfid_list and not providing project_sfid_list and in both cases 500 is returned even when CLA group does not exist. I created new project and tried.** 
```
FoundationName ParentNoSubProjects
FoundationSFID a091700000AHtHvAAL
```
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/25b0f5d3-d2b4-4657-8af2-f62ecf655887)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/e0e2e4c9-f04e-4b5c-acb3-e764288052a5)

**Observed that we are able to create CLA Group at foundation level when there are subprojects for the foundation**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/928cb201-7773-4422-96cd-667476e5a92c)

**Comment by dealako** [comment]
@nirupamav I have pushed an update which:

Added Additional Create CLA Group Validation Logic

- Added checks when we have new CLA Group request and there are existing Foundation Level CLA Groups for the same foundation
- Added checks for new Foundation CLA Group under a foundation when existing foundation sub-groups are already in another CLA Group
- Updated error handling for stand-alone projects
- Added debug log messages
- Added helper functions to clean-up the code

I've tested with a few simple scenarios. Can you assist with test scenario setup and validation?  Do you have PostMan code that you can share or execute for this directly?

**Comment by nirupamav** [comment]
** Able to create CLA Group for Stand alone project (Parent project without any sub projects) . Observed other validation issues which are tracked in #1716 and #1693**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a890cadf-1817-43dc-b3ff-6e49bb34622e)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/771e467e-b24d-4b50-9122-b64477ea8e7e)
