### ISSUE TITLE
V2 - Company Not Found - The Page you are looking for was not found message is displayed after user logins to SSO

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1678]
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group
3. Generate template

**Steps to Follow**
1. Login to Github as corporate contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Click on building icon
9. Click on Organization not listed? + Click Here
10. Enter company name and website that does not exist
11. Click Next
12. Click Proceed
13. Click Yes
14. Click Proceed
15. Login to SSO
16. After login, user is redirected to contributor console. However The Page you are looking for was not found message is displayed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/3558154d-51cc-4da1-acd1-01dd3001ed5b)

**Comment by amolsontakke3576** [comment]
@nirupamav I have tested flow as per the steps you mentioned but it's worked as per expectation (PFA). can you provide more details may be use-case will be different

![Screenshot from 2020-09-07 15-59-42.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/7d917aa1-2a76-4229-bf3c-cf118b2ca075)

**Comment by nirupamav** [comment]
I faced this issue again today. Looks like an intermittent issue
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/75735be1-6fa1-48a2-b5fd-c081a47fea3a)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/5ee688ae-c13d-4ea2-933c-671377daff23)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/1095d45e-1d91-4d19-b96f-8f79bcf68472)

**Comment by dealako** [comment]
@amolsontakke3576 is this related to an Auth0 redirect issue?  Can we move to QA if you are not able to reproduce?  Not the URL that @nirupamav has posted in the screenshot.

**Comment by amolsontakke3576** [comment]
I had made some changes in the flag which is used to show proper message after outh0 redirection.
It looks like working fine for now.

**Comment by nirupamav** [comment]
I tried couple of times today and was not able to reproduce the issue. Looks like it is intermittent issue. Will reopen the ticket if I face the issue again
