### ISSUE TITLE
V2 - Contributor Console - Contact Company Admin option is displayed when company admin does not exist for the company created from contributor console

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1679]
Prerequisite
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group
3. Generate template

Steps to Follow
1. Login to Github as corporate contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Click on building icon
9. Click on Organization not listed? + Click Here
10. Enter company name and website that does not exist
11. Click Next
12. Click Proceed
13. Click Yes
14. Click Proceed
15. Login to SSO
16. After login, user is redirected to contributor console. However The Page you are looking for was not found message is displayed
17. So navigated to github and again naviagted to contributo console
18. Click on Proceed as a Corporate Contributor
19. Search for the company created in Step10
20. Click Proceed
21. Click No
22. Observed that contactCompanyAdmin option is displayed and when clicked on the link below error message is dsiplayed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a32b3bd1-c23a-467f-b5ff-f6e163a2d3ce)

**Comment by amolsontakke3576** [comment]
@wanyaland Can we have any flag/endpoint to identify is the company having a `comapny-admin` assigned?

**Comment by wanyaland** [comment]
@amolsontakke3576 Ive created a new endpoint for getting external company admins and changes have been merged. 
API-DOC: https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/getCompanyAdmins

**Comment by nirupamav** [comment]
@pranab-bajpai 
When there is only company-owner, but no company admin, company owner is used in contact admin scenario. Is this expected behavior?
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/e894dae6-182b-40c6-95bd-64bde53aba1a)

**Comment by nirupamav** [comment]
As discussed in standup call, the current behavior of sending notification to company owner + company admin or either of them is fine. Hence closing the ticket
