### ISSUE TITLE
V2 - Company Not Found - Dialog box indicated user to create SSO account even when user is already signed into SSO

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1680]
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group
3. Generate template

**Steps to Follow**
1. Login to Github as corporate contributor **and also make sure that user is logged into SSO in the same browser session**
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Click on building icon
9. Click on Organization not listed? + Click Here
10. Enter company name and website that does not exist
11. Click Next
12. Click Proceed
13. Click Yes
14. Observed below dialog is displayed to indicate user to create SSO account
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/f7b62c2b-4d5c-42f3-8045-b46cce8557bb)

**Comment by amolsontakke3576** [comment]
@nirupamav as per latest discussion if the contributor doesn't have `lf_username` then we are showing the above dialog and I have been pickup this information from user-service. 
So userId mentioned in the URL if not having `lf_username` then we are showing this dialog so please confirm what is data cames for the user you used.

**Comment by nirupamav** [comment]
@amolsontakke3576 
I tried with the user having lf username. This is a scenario when I logged into SSO using lf username which I provided while creating account from LFX portal

**Comment by amolsontakke3576** [comment]
@nirupamav please check the user object data for your user I guess `lf_username` is empty or null.

**Comment by nirupamav** [comment]
@amolsontakke3576 Where should I check that

**Comment by amolsontakke3576** [comment]
Check the below endpoint on postmen.
Request URL: https://api.dev.lfcla.com/v2/user/<USER_ID>
Request Method: GET

**Comment by nirupamav** [comment]
@amolsontakke3576 
This scenario is when user has LFID with different email id. The userid will have github email. But I have logged into SSO with LFID created with different email.

**Comment by amolsontakke3576** [comment]
@dealako @nirupamav I have checked the above issue and found below conditions
**1. When a contributor has LFID  and the session does not exist in the browser**
No need to show the create SSO account screen and redirect the user to the LF login page. 

**2. When a contributor has LFID  and the session exist in the browser**
No need to show the create SSO account screen and show the Configure CLA manager setting screen.

**3. When a contributor has no LFID  and the session does not exist in the browser**
Show the create SSO account screen and redirect the user to the LF login page. (Here the user creates his account or maybe logged in if it is associated with another email).

**3. When a contributor has no LFID  and the session exist in the browser**
No need to show the create SSO account screen and redirect the user to the LF login page.

**Comment by amolsontakke3576** [comment]
@vinod-kadam Verified above conditions and works fine so moving to QA done
