### ISSUE TITLE
V2 - Contributor Console ICLA - User is still gated when user is logged in to SSO and then signs ICLA as individual contributor

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1681]
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group
3. Generate template

**Steps to Follow**
1. Login to Github as corporate contributor **and also make sure that user is logged into SSO in the same browser session**
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Individual Contributor
8. Docusign is opened with SSO logged in user details
9. Complete the docusign process
10. Observed that user is still gated even after signing ICLA. Looks like the issue is because of the SSO login
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/3b795d25-f532-41ee-b9aa-41e02c5a7174)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/84763028-5618-48d8-9807-7188e2eed7f3)

**Comment by dealako** [comment]
Worked with @makkalot on this issue today. During a troubleshooting session, it was observed that:

1. In GitHub, the user is gated.
1. User then executes the ICLA flow. 
1. User is then redirected back to GitHub.
1. User observed that he/she is still gated by GitHub.
1. Sometime later, the user refreshes the GitHub page and found the user is now passing the gating.

Reviewed/Observed the Docusign EasyCLA callback logs and found no issue associated with the ICLA flow.

Requested @makkalot to review the CloudWatch logs to determine which API calls/flows/logic is taking so long to execute.  Can we optimize without introducing python concurrency?

The Docusign flow callback accomplishes the following:

1. Decode the callback message (includes envelope ID and signature ID)
1. Loads the signature record by ID
1. Determines if the callback indicates "completed status", if so, sets the assigned=True flag (which triggers to the golang dynamodb signature updated event which is handled by the golang lambda)
1. If ICLA, loads the user record by user id (from the signature_reference_id value)
   1. Cleans up the meta data (not sure what this does...
   1. Sends a copy of the signed document to the user
   1. Saves a copy of the signed PDF document to S3
   1. Loads the CLA group and creates a new event log entry indicating the user signed the document
   1. Invokes update change request (github or gerrit)
      1. fetches the GH pull request details
      1. loads the commit author(s) information
      1. loads the CLA repo record, github org record, CLA Group record (again)
      1. Loops over the commuters - determines if commiters are signed or missing CLA authorization
      1. Updates the PR comments (if required)
      1. Updates the PR status (if required)

**Comment by makkalot** [comment]
Did some digging on this one 

Some timing on how long it takes : 

```
2020-09-21T18:51:05.627+03:00	START RequestId: d14588fa-afa7-49ce-9585-6cb0a2524d8c

REPORT RequestId: d14588fa-afa7-49ce-9585-6cb0a2524d8c	**Duration: 4158.30 ms**	Billed Duration: 4200 ms	Memory Size: 1024 MB	Max Memory Used: 179 MB

XRAY TraceId: 1-5f68cbe9-0867c6a606814e2c00c000ba	SegmentId: 2192f0191a028d99	Sampled: true
```

**Duration: 4158.30 ms**

When I looked in more detail on what each step took (this is for `post_individual_signed`):

- we fetch the document from docusign : ~ 1 sec
- sending email to the contributor : ~ 200ms
- we upload it to s3 : ~ 500ms
- then we connect to github and we do lots of checks before we update the status ~ 2.5 sec

Maybe we can do some of those as separate lambda in the background ? Also not sure why we do so many calls to github in order to update the status. Since I don't know the history of it can't really comment. @dealako let me know what you think ?

**Comment by nirupamav** [comment]
**Verified that SSO details are not auto filled in Docusign and after docusign process is complete status of CLA check is passed.** 
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/0a0c5240-9fec-4337-94bd-2b5d878439f1)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/f31a6412-410b-4d83-827e-b8c952a358bd)
