### ISSUE TITLE
V2 - Company Not Found - Company Owner role is assigned to contributor but Organization name is not set with the organization name

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1683]
Observed when company is created, company owner role is assigned to the contributor. However Organization name is not set for the user in ACS and because of this not able to access LFX UI from the link in notification email to complete company profile. Not sure if it is ACS issue or issue with the parameters passed to the ACS API from EasyCLA to assign role. Logging this ticket for tracking purpose
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/76bba89a-b460-4041-8e1d-16b8f6e39c6d)

**Comment by dealako** [comment]
@wanyaland - EasyCLA fix, set the organization for the user.

**Comment by dealako** [comment]
@rinkeshbhutwala can you review?

**Comment by rinkeshbhutwala** [comment]
@dealako I have verified this ticket company-owner role is assigned properly with proper organization.
![Screenshot from 2020-08-31 19-53-32.png](https://images.zenhubusercontent.com/5f20ee93f9a45844ef8dfce5/7561c766-a9de-44df-a5c2-134c870823cd)

**Comment by nirupamav** [comment]
@amolsontakke3576 @rinkeshbhutwala @wanyaland 
Issue is still reproducible. Not sure if it is UI issue are API issue
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c8111428-5290-468b-8fae-aa4f35bdcfee)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/2ee4134f-1834-430c-ab05-8f465319470c)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/e5bf142e-c9e8-4094-ba0d-fa8e45767e62)

**Comment by nirupamav** [comment]
Verified that the issue is fixed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/964c6a78-86cb-49e2-bad6-7d29faa1f3aa)
