### ISSUE TITLE
V2 - Company Not Found - Organization website is not auto populated with few url formats and free text

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1684]
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group
3. Generate template

**Steps to Follow**
1. Login to Github as corporate contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Click on building icon
9. Click on Organization not listed? + Click Here
10. When free text is provided website is not auto suggested. Also for few url formats website is auto suggested

**Example1 - samsung**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/ea968045-8203-47bb-8a50-50f0a6bc037c)

**Example2 - different url formats for same website**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/ef9edb96-8fbd-4a92-ac1f-a96675659b87)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/8f49eb99-df77-46ba-b239-79b8a3a4ae62)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/ea4d5e30-4c76-4768-bdc6-6bf64bd168fc)

**Comment by amolsontakke3576** [comment]
@nirupamav It is not possible because the `organization-website` input box value not only used for search but also creating organization. So there is a form validation used which makes sure not an invalid data pass while creating org.
As per the regex provided by org service for website there is min and max length validation with .com or .in suffix.

**Comment by dealako** [comment]
@amolsontakke3576 let's do a demo for @pranab-bajpai on Friday to showcase what we currently have. We need to update to match the desired behavior - let's get feedback from Pranab and either close this one out or update.

**Comment by amolsontakke3576** [comment]
As per our discussion with @pranab-bajpai it is fine to search the organization when the user types a valid URL.
There is a technical limitation as mentioned in my above comment.
