### ISSUE TITLE
V2 - Select Company - Bad request message is displayed for few organizations

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1685]
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group
3. Generate template

**Steps to Follow**
1. Login to Github as corporate contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Search and Select any of below companies and click Proceed
9. Observed that Bad Request message is displayed
RisingTek Electronics
BlackBean Ltda.

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/d6fd7303-4fc9-48c3-93e4-642ea894e14b)

**Comment by amolsontakke3576** [comment]
@dealako @wanyaland I guess it is from backend so can someone look at this?

**Comment by wanyaland** [comment]
@amolsontakke3576 This is due to the salesforce orgs having no association with the EasyCLA companies(company ExternalID missing) .can enable this by creating a company with the association

**Comment by wanyaland** [comment]
@amolsontakke3576  This issue was related to issue where no admins exists for salesforce companies. Since weve integrated the easycla endpoint that checks if admins exist that should cater for this scenario . Is that the case @amolsontakke3576 ?

**Comment by amolsontakke3576** [comment]
@wanyaland `get-company-admin-list` endpoint we have used on identify CLA manager screen and not on the search screen and also it is very complicated to run multiple endpoints on search as it has already called almost 3 endpoints on the Procced button.

**Comment by wanyaland** [comment]
Thanks. I shall refactor this to bypass no admins error being thrown at the organization service layer

**Comment by wanyaland** [comment]
@nirupamav . For this case we are trying to create an easyCLA company based on SF organization(ExternalID) . We use the first company-admin found to add him to companyACL and also make company manager(Easy CLA). For these organizations stated they dont have any admins hence the error response. Ive just cleaned up the response when no admins are found

**Comment by dealako** [comment]
@nirupamav can you re-test after @wanyaland has updated the response.

**Comment by nirupamav** [comment]
@wanyaland 
The message is still not user friendly as companySFID is displayed

@pranab-bajpai 
In this case should we display link to create service to contact support team to get the issue resolved

**Comment by wanyaland** [comment]
@nirupamav I can update this or @amolsontakke3576 . Just need to know the appropriate response

**Comment by dealako** [comment]
I have requested @pranab-bajpai to provide his comments on how to handle this situation.

If he doesn't provide feedback, please provide a note/dialog to indicate:

"The selected company {Company Name} has not been fully setup.  Please help us by [filing a support ticket](https://jira.linuxfoundation.org/servicedesk/customer/portal/4/create/143 target=_blank) to get the Organization Administrator assigned."

Button[File a Ticket new tab redirect to help page] Cancel[Close Dialog]

**Comment by nirupamav** [comment]
**Verified that the issue is fixed**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/defd84d6-280c-4c0f-9eec-d179e7ef1556)
