### ISSUE TITLE
v1 Project Console - Signature Table search query update.

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#1698]
When a project manager is searching through the list of signatures in the "Signatures" table, the manager will want to see every user type "Employee" who has verified with a company. When the manager selects "Company" and searches for the company name, the desired results are not found. They will only find the records of the actual company CCLA. Though technically correct, this is not the desired functionality.

I believe this query is looking at only CCLA records instead of also looking for signature_user_ccla_company_id field that is also populating the "company" column for employees. Can we please review this query?

**Comment by dmcbride64** [comment]
I spent some time looking at the interface and thinking about this issue and I think that I understand this problem a little better.  

The problem with the UX design is that it expects the user to understand the categories in advance, then know what data to enter into which search box, that is appropriate for that category.  

Instead, there should be just a single search box that returns all records where there is a hit. Then, categorize the search results into different sections (e.g., CLA manager, CLA individual signer, CLA company signer, company employing individual signers, etc.. I think that this would simplify the design and reduce a lot of confusion and frustration.
