### ISSUE TITLE
API Response getting LFID instead of LF Login

### ISSUE THREAD

**Issue by lokeshkondepudi** [communitybridge/easycla#1703]
Please refer the LFX **https://jira.linuxfoundation.org/browse/LFX-2221** ticket to get more idea about this issue

**Comment by nirupamav** [comment]
Issue2 testing blocked due to bug #1733
**Issue1 mentioned in ticket is resolved**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/3cf894b1-1ca5-4944-a371-395810632ece)

**Comment by nirupamav** [comment]
Verified that Issue2 is also fixed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/bf526c33-fe80-48b0-8f2f-319099bc3864)
