### ISSUE TITLE
Project Console - remove duplicate "View Companies" button.

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#1708]
## Summary
The "View Companies" option is duplicated in the project console. Please remove the button from the UI.

## Background

1. Go to project.lfcla.com and click on a project.
1. Observe a "View Companies" button and a "View Companies" link that do the exact same thing.

## Screenshots

![image](https://user-images.githubusercontent.com/46732999/91892621-fdf61580-ec60-11ea-9cac-c7cb8d8e90cc.png)

**Comment by WillsonHG** [comment]
confirmed the button is gone in dev.

**Comment by nirupamav** [comment]
Verified that the issue is fixed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/ac5f42e1-82a4-473e-b4f9-bb13eb5eb1d7)
