### ISSUE TITLE
V2 - Project Console - Issues with CLA Group post, get and enroll endpoints

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1716]
**Observed below issues with CLA Group endpoints**

**_Create CLA Group_**
**1. When trying to create CLA group for a standalone project that is already associated with a CLA Group, 500 is returned**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/b5238e62-8214-4f22-964a-dedb3270b679)

**2. When CLA Group exists at foundation level and if we try to add project level CLA group 500 is returned instead of 400**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/e4233da4-bb9a-43e0-8aa2-36cbb9b517e8)

**_Get CLA Group_**
**3. When trying to get CLA group for a standalone project that does not have any CLA Group, 500 is returned**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/4bd7062a-d195-4283-bdd6-adf024cef3fd)

**_Enroll CLA Group_**
**4. When trying to enroll a project to a cla group that is already associated with another cla group, 500 is returned instead of 400**

**Comment by dealako** [comment]
[Pushed some updates](https://github.com/communitybridge/easycla/pull/1757) which hopefully address all the use-cases.

**Comment by nirupamav** [comment]
**Tested and observed few issues are still reproducible and new issues are also observed**

**_Get CLA Group_**
3. When trying to get CLA group for a standalone project that does not have any CLA Group, 500 is returned
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/2465f573-d13a-43b1-b30e-d6ed170d256e)

5. Able to add CLA Group at foundation level when CLA Group already exists at project level and also observed that the CLA Group. Ticket #1759 is logged to track the issue

6. When trying to fetch CLA Group for projectSFID that does not exist, 500 is returned
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/7b2ec9dd-926b-410d-8396-e0c37b9b2390)

**Comment by dealako** [comment]
Regrading:

> 3. When trying to get CLA group for a standalone project that does not have any CLA Group, 500 is returned

Updated to return 404 HTTP response: 

```
{
    "Code": "404",
    "Message": "EasyCLA - 404 Not Found - unable to find foundation or project by ID: 0012M00002ALgHaQAL"
}
```

**Comment by dealako** [comment]
@nirupamav - I am unable to reproduce:

> 5 Able to add CLA Group at foundation level when CLA Group already exists at project level and also observed that the CLA Group. Ticket #1759 is logged to track the issue

In my PostMan test scenario, I am seeing 400 bad request when I create a new Foundation Level CLA with an existing CLA Group in place...

**Comment by dealako** [comment]
I will create a PR with my changes.

**Comment by dealako** [comment]
PR created: https://github.com/communitybridge/easycla/pull/1814

**Comment by nirupamav** [comment]
**_Issue3 is still reproducible_**
```
Name - bug1716standalone
SFID - a096s00000037biAAA
```
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/37a12a88-0c98-41d0-a709-17ed10f8c3c2)


**_Verified that the issue 5(verified in #1759) and 6 are fixed_**
**Issue6**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c919dcf2-5f60-4c3d-9ecb-2d5fb375c26f)

**Comment by nirupamav** [comment]
Verified that the issue is fixed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/88e683b8-6467-4b53-857c-6e77bd7e31b9)
