### ISSUE TITLE
V2 - Format issues in the email sent to Project Manager when github repo is disabled

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1721]
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group
3. Generate template
4. Create PR for the repository as a contributor
5. disable repository for the gihub organization in project console for the project
4. Observed format issue in the email sent to project manager
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/bd4b5af4-9e3b-404d-b39d-b14c99138b4d)

**Comment by vinod-kadam** [comment]
As discussed in the standup, any change to repo would be caught in the logging. So, this one seems to be not valid issue any more. So, closing it.
