### ISSUE TITLE
V2 - Corporate Console - Email of the CLA Manager is not mentioned in the email notification sent after CLA Manager is removed

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1734]
**Prerequisite**
1. Create a CLA group (I tried for Foundation level CLA Group where foundation has I 1 subproject)

**Steps to Follow**
1. Sign CLA
2. Add CLA Managers
3. Delete one of the CLA Manager
4. In the email sent to the removed CLA Manager, email of the other CLA Managers is not mentioned so that removed CLA Manager can contact them
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/ea650392-c0bd-4d9f-a03b-dec5b36e9275)

**Comment by nirupamav** [comment]
Issue is still reproducible
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/eaa71429-892c-4259-a2ad-001aa2ca18f0)

**Comment by nirupamav** [comment]
Issue is still reproducible
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/412c874a-41a2-4518-9b3d-9307704eed2c)

**Comment by manishv09** [comment]
Verified today and found below:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/1ca339ce-ca3d-43bd-bbe5-b026c5a30aa4)

@wanyaland  Is actual email id is expected in this issue? Please update so that if required will reverify.
CC: @vinod-kadam

**Comment by wanyaland** [comment]
Thanks @manishv09 . Actual email of the existing CLA Manager is expected and this can be pushed to rejected. I shall update this issue

**Comment by vinod-kadam** [comment]
As discussed, @wanyaland  to add email address as well.

**Comment by manishv09** [comment]
Verified on DEV Environment and found email id is appearing on email sent to the user, please refer the screencast below:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/cf1ea317-c13f-405e-b0d1-dea490459c7e)
