### ISSUE TITLE
V2 - CLA Not Signed - Identify Yourself as CLA Manager Designee - Error displayed after creating account

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1738]
**Prerequisite**
1. Create a CLA group with CCLA enabled (I tried the flow where CLA Group is at foundation level and there is only 1 subproject for the foundation)
2. Add github repository for the CLA group

**Steps to Follow**
1. Login to Github as corporate contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Select Company that has not signed CLA for the project
9. Click Proceed
10. Click Yes
11. Click Proceed
12. Create account
13. Complete Verification of email
14. Contributor is redirected to contributor console
15. Error is displayed however CLA Manager designee role is assigned. Also observed that CLA Manager designee role is assigned to both Foundation and Child project
Error message contains child project SFID though the CLA Group is at Foundation level
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/3726f61e-d6ea-43a0-afa7-3e929bd08b46)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/0c7c3441-8ac5-4bd6-9dc5-1c88a8f061fe)

**Comment by wanyaland** [comment]
@nirupamav could you kindly as well share the response via console just to quickly identify the issue ?

**Comment by nirupamav** [comment]
@wanyaland I tried the flow again and below is the console log
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/1a3c009c-d28d-47a6-a510-98976151d1de)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/6b155da9-a2bf-46b2-9e4a-b02f68da6489)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/128bd059-7bea-4c3a-ac94-4198e4b959ca)

**Comment by nirupamav** [comment]
Verified that the issue is fixed
