### ISSUE TITLE
V2 - Company Not Found - Organization website does not accept capital letters

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1739]
**Prerequisite**
1. Create a CLA group with CCLA enabled (I tried the flow where CLA Group is at foundation level and there is only 1 subproject for the foundation)
2. Add github repository for the CLA group

**Steps to Follow**
1. Login to Github as corporate contributor 
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Click on building icon
9. Click on Organization not listed? + Click Here
10. Enter capital letter for organization website
11. Organization website should be valid URL. error message is displayed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/2be111f0-63e5-47dd-a871-2c627eb7a289)

with small letters
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/bab758a6-8eeb-4d82-84d3-a3c506b11fed)

**Comment by amolsontakke3576** [comment]
@nirupamav As per regex mentioned on org-service, only small characters are allowed. If you want capital letters then we need to change regex from org-service itself.

**Comment by nirupamav** [comment]
Verified that the issue is fixed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/741703b5-95a2-4dfc-a5e0-89c031714d94)
