### ISSUE TITLE
V2 - Gerrit - While identifying CLA manager which is not is user service throw an error 'Your request is Failed due to internal server error please try later'.

### ISSUE THREAD

**Issue by amolsontakke3576** [communitybridge/easycla#1755]
## Summary

CLA manager name and email provided for identifying if it is not in user service then not able to identify it.

## Background
1. Login to the Gerrit `https://gerrit.linuxfoundation.org/`
2. Go to the Settings --> Agreements and click on `New Contributor Agreement`
3. Select `Test Project 2 CLA` and click on `Please review the agreement.`
4. changed word `individual` to `corporate` in URL and reload again.
5. Click on `Proceed To Corporate Authorization`
6. Click on  Corporate Contributor button
7. Search organization `Pinterest`
8. CLA NOT SIGN window will appear and click on No button
9. Enter entirely new user name and emailId which is not present is user-service.
10. Click on `Submit Requst` 
11. Error throw as `Your request is Failed due to internal server error please try later.`

## Expected behavior

Email should be sent to the provided email address and ask for create a new account,
## Screenshots

![Screenshot from 2020-09-04 12-51-09](https://user-images.githubusercontent.com/56335654/92212341-73572580-eeaf-11ea-82be-8b9f6f4580df.png)

**Comment by wanyaland** [comment]
@amolsontakke3576 verified this and this is working as expected. On testing got an email as shown below 
![Screenshot 2020-11-16 at 17.52.37.png](https://images.zenhubusercontent.com/5ed66fcc690afccc216f0ecb/31632b05-0c05-4597-871c-45c6e0a697c0)

**Comment by amolsontakke3576** [comment]
@dealako @vinod-kadam I have verified and looks good when tried with new user 
PFA.

![Screenshot from 2021-01-05 17-02-56.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/756e296a-6bdb-436f-88cf-45ada4ea53af)
