### ISSUE TITLE
V2 - Corporate Console - Email notification is not sent when user without LFID is identified as CLA Manager Designee

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1760]
Observed that email notification is not sent when user without LFID is identified as CLA Manager Designee. I tried for standalone project(Project without parent and child)

**Endpoint**
`https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company/{{CompanySFID}}/project/{{ProjectSFID}}/cla-manager/requests`

**httpMethod**
`POST`

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/e9c9d8a1-df7e-4837-bb6b-3d0cd7da72ef)

**Comment by dealako** [comment]
@makkalot can you review this one? Seems like a bit of logic assumes that we have/need an LF ID. We should be able to send the email regardless.  Work with @nirupamav on the scenario.

**Comment by nirupamav** [comment]
Verified in #1811 and observed that issue is fixed
