### ISSUE TITLE
V2 - All API endpoints which has role assignment step takes more than a minute to complete the request

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1761]
**Observed that all API endpoints which has role assignment step takes more than a minute to complete the request. However role is assigned. I tried couple of times and each time it took more than a minute. Below is example of that cla-manager/requests endpoint**

**Endpoint**
`https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company/{{CompanySFID}}/project/{{ProjectSFID}}/cla-manager/requests`

**httpMethod**
`POST`

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/3a64fee5-f31e-4c06-9eb3-1ff09016c61f)

**Comment by dealako** [comment]
Performed a number of optimizations on this API request. This request performs a lot of things...

1. Updated the signature query to look for specific CLA Group + Company CCLA signatures that were signed and approved - grabs the list of CLA managers. Previous query was searching for all CCLA records for a given company.
1. Change the LFX user query - from /users/search to /users?email=... which is much faster (this is performed twice in the current flow). See notes below.
1. Added logging for metrics collection.
1. Assigning CLA Manager Designee role for a given user takes 14 seconds :-(

Thanks - as a comparison for you:
https://api-gw.dev.platform.linuxfoundation.org/user-service/v1/users?email=ddeal+mgr-request@linuxfoundation.org - takes ~3.4 seconds
https://api-gw.dev.platform.linuxfoundation.org/user-service/v1/users/search?email=ddeal+mgr-request@linuxfoundation.org - takes ~24-49 seconds

**Comment by dealako** [comment]
Created PR: https://github.com/communitybridge/easycla/pull/1782

Old Time: 60s+ -> resulting in an API-GW Timeout
New time: 21.31 s

**Comment by dealako** [comment]
Merged PR. Still not fast, but quicker now.

**Comment by nirupamav** [comment]
Verified that the issue is fixed. It took around 20 secs and also 200 response was returned
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/417049fd-ab31-42d0-9f6f-ac6ba64a71b3)
