### ISSUE TITLE
V2 - Corporate console - CLA Manager Designee role is not removed after CLA is signed and CLA Manager role is assigned

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1762]
1. Create CLA Group (Tried for Standalone project, Foundation level and project level CLA Groups)
2. Identify other user as CLA Manager Designee from Corporate console
3. Identify logged in user itself as CLA Manager Designee
4. Sign CLA
5. Observed that CLA Manager role is assigned to the user that has signed CLA. However CLA Manager Designee role is not removed

**User that has signed CLA**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/989bcc37-df66-4370-97ba-dfd2f3038132)

**Other user identified as CLA Manager Designee**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/f6906e04-2e76-49dd-8d38-da6c172793d4)

**Comment by dealako** [comment]
Python v2 API -> Docusign Callback Logic. Ensure:

- CLA Designee is removed from all users
- CLA Manager is assigned

Review logs to see if we can identify any issues.  @nirupamav will give us some "strings" to search for.

**Comment by nirupamav** [comment]
@wanyaland @dealako 
Below is the test data. Let me know if you need any other details
I tried for foundation level CLA Group
**Foundation SFID** a0902000000A37SAAS
**Foundation Name** CLA_Foundation_1599742976272
**CLA Group Id** 67ffecd9-eda5-425e-b52d-c8a0eea5457e

**Comment by dealako** [comment]
Yeah, working on this one. Currently, we have no way of removing the roles for all users for a given project. Working with Nirav to see how this can be accomplished.

@wanyaland suggested this workaround which leverages a brute force and time-consuming approach:

{code}
-> List all users (user service)
-> Get AccountID (representing organization)
-> Use AccountID to get servicescopes (organization service)
-> Filter project or project|org scope with the given ProjectSFID
{code}

This approach would scan the entire user database and then looping through the Orgs to use the Org Service scope query finder to sub-filter down to the appropriate project ID.  Hopefully, @niravpatel27 can provide a more elegant solution.

**Comment by dealako** [comment]
I have received some additional notes from Nirav regarding the API calls. However, the query is not optimal - I would have to sub-filter down (it literally returns all the roles and mappings for the project|org scope which is around 297 entries today).  I have asked if there is a better way or if we can add an additional query parameter.

**Comment by dealako** [comment]
Awaiting fix from ACS team - Prabodh/Nirav

@Nirav also, I am still blocked on my ticket for CLA Group Delete Cleanup - I need to remove existing roles for cla-manager, cla-manager-designee, and cla-signatory to properly clean up (EasyCLA Ticket). I am hoping for an ACS API whereby I can query the Project|Organization object_type using only a Project ID.

Blocked by: JIRA: https://jira.linuxfoundation.org/browse/IAM-1072

**Comment by nirupamav** [comment]
@wanyaland @dealako 
This issue is still reproducible only for foundation level CLA Group

**Comment by dealako** [comment]
Assigned to @wanyaland

**Comment by nirupamav** [comment]
Executed automated scripts and observed that the issue is fixed
