### ISSUE TITLE
CLA check should use github status checks API to display CLA check result details.

### ISSUE THREAD

**Issue by jtattermusch** [communitybridge/easycla#177]
a new CLA check has bot has recently been enabled for the gRPC project (https://github.com/grpc/grpc), but the way the check results are being presented is interfering with our test results and making them less readable.

what the new bot does is that it displays "EasyCLA" status on each PR (same as the previous bot)  but also displays a separate check entry for each individual contributor (in the example "Steven E Wright" entry is added to the list of green tickmarks of that PR. This is probably done as an attempt to increase the amount of details provided by the bot, but it's not the right way to do this. In practice it means the names of contributors are thrown randomly into the list of test suites that run on each PR and they are making things look messy.
Ideally the bot would use the github status checks API (right now the "commit status API" is being used), there would be only one entry in the test result overview ("EasyCLA") and clicking on the "Details" link would display additional details about the individual contributors and their signing status (and links to the CLA details). This is exactly why status check API was introduced - to be able to display additional details around checks in a standard way.

https://github.com/grpc/grpc/pull/20123

example of a github status check:
https://github.com/grpc/grpc/pull/20123/checks

**Comment by jtattermusch** [comment]
CC @caniszczyk, @nicolasnoble

**Comment by dankohn** [comment]
Thanks for the detailed issue here. @jpalmerLinuxFoundation I believe this was already fixed, right, where EasyCLA now only posts into issues when it fails?

**Comment by jpalmerLinuxFoundation** [comment]
Yes, this commit happened last week before the changes were made. This
shouldn't be an issue going forward. Please let me know if you experience
any other issues.

Regards,



*Jacob Palmer*
Product Owner, Product Development | EasyCLA, Dev Analytics, and
Vulnerability Detection
Cell: 1.332.333.2863

Slack: @Jacob <https://linuxfoundation.slack.com/team/UJS0UD000>

**Comment by jtattermusch** [comment]
I can confirm that when CLA check passes, there's only one "EasyCLA" status on our PRs. That said,
it probably still would make sense to turn the github commit status into a "status check" and provide more details in the "Checks" tab on the PR. Right now the "Details" link leads to "https://lfcla.com/" which is not really that helpful. If it instead showed a status check tab with additional details, it would be much more informative and useful.

**Comment by jpalmerLinuxFoundation** [comment]
Hi Jen,

     That's really good feedback. I've created a ticket to improve the information available. If you could add to the ticket to help improve it that would be valuable: https://github.com/communitybridge/easycla/issues/169

**Comment by dealako** [comment]
This issue seems resolved with additional scope/discussion noted on #169.

Closing this issue during our backlog review. If additional help (be specific) is needed then please create a new ticket.
