### ISSUE TITLE
V2 - Company Not Found - Company owner role is not assigned to identified cla manager designee

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1789]
**Prerequisite**
1. Create a CLA group with CCLA enabled (I tried the flow where CLA Group is at foundation level and there is only 1 subproject for the foundation)
2. Add github repository for the CLA group

**Steps to Follow**
1. Login to Github as corporate contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8.Click on building icon
9. Click on Organization not listed? + Click Here
10. Enter new company details
11. Click Next
12. Click Proceed
13. Click No
11. Enter name and email of user who has LFID and is not company admin or company owner
12. Observed that CLA Manager designee role is assigned for the user but company owner role for new company is not assigned
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/7a9a4044-2905-453a-a736-bee3a10e3fa4)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/987b7c1a-2be5-447d-999b-20464cb0d078)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/1862a1f4-fbc1-4e66-8eae-7d443cf8c592)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/3fd551bb-de73-4e22-bc49-ef26ddfd8ab3)

**Comment by wanyaland** [comment]
@amolsontakke3576 . Since we have the endpoint that assigns the role. Could you invoke it at this stage. After the Identify company Admin endpoint (For users with LFIDS)

**Comment by amolsontakke3576** [comment]
@wanyaland To add the user as company owner we required an authorization token which is not present in identify CLA manager flow (edited)

**Comment by nirupamav** [comment]
**Issue is still reproducible for user with any role and for user without LFID**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/0e72c0cb-622b-4ab8-b280-52bf2a40fa08)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c0c59f43-836e-4e07-988a-01f61127b0af)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/87e1ac7a-d8ac-4793-80e4-f04e17b480b2)

**Comment by amolsontakke3576** [comment]
@nirupamav  I think we can not assign role if users don't have LFID right?

**Comment by nirupamav** [comment]
@amolsontakke3576 
For user without LFID invite link from email should assign the role
For user with LFID and not company owner for any company, company owner role should be assigned by API endpoint triggered from frontend

**Comment by amolsontakke3576** [comment]
@nirupamav Okay so it is related to emails. I guess @wanyaland is working on it.

**Comment by nirupamav** [comment]
@amolsontakke3576 
No Amol as I explaind above
**Related to email -** For user without LFID invite link from email should assign the role
**Related to API call made from frontend -** For user with LFID and not company owner for any company, company owner role should be assigned by API endpoint triggered from frontend

**Comment by nirupamav** [comment]
**_Issue is still reproducible_**

**1. User without LFID**
Only 1 invite email is sent and that is assigning cla manager designee role
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/d1fa61da-6872-437f-95c6-173ae5030ca0)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a803496b-d09e-4f33-8f2f-d66244ba7e99)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/b5c2d32a-dad3-47b5-bfad-9042b4512379)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/6fc7837a-956e-497d-a941-0a8b7e5b0000)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a84f10f9-9134-48f8-9738-30aec42bf077)

**2. User with LFID**
Only CLA Manager Designee role is assigned
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/5f258d5b-bd99-436b-b17d-1860691e5656)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/efd90369-97cb-4379-ac1b-2c11ab17901b)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/99312ce9-d932-4dda-9629-61a64bf57c79)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/dee882f2-eb83-4094-bbb5-4ab07e96cafe)

**Comment by amolsontakke3576** [comment]
@wanyaland If you see the second case **User with LFID** status code is missing and it returns the only list.
the list is required only when contactAdmin flag is true otherwise just a status code

**Comment by wanyaland** [comment]
@amolsontakke3576 this is a list of cla manager designees which in essence is a success and code 200

**Comment by nirupamav** [comment]
@amolsontakke3576 
Company owner role is still not assigned to the identified CLA Manager designee. Observed that github email is sent to company-owner API instead of the identified CLA Manager. This issue is observed in both the scenarios when email with LFID or email without LFID is provided
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c5ed3060-0b83-4c9f-a653-dfe0f39b1b51)

**Comment by nirupamav** [comment]
@wanyaland @amolsontakke3576 
Company owner role is not getting assigned when user does not have LFID. Only 1 invite email was sent and through that invite link only cla manager designee role is assigned
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/4e6330b9-7821-4471-bb12-a35ace9ee9b2)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/b3e3e7d3-7ef1-40e7-8b6f-f8b346b89fc5)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/5168d576-de01-4808-af13-b96d7011e8f9)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/09875ba1-7e31-4a3c-8f1b-9c3499631adc)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/1ef13da4-5eba-4c4c-b940-bcff51f9507e)


![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/4b422199-cf9d-4f78-823f-cf1907d4ac25)

**Comment by nirupamav** [comment]
@pranab-bajpai @wanyaland @dealako 
Observed that 2 invite emails are sent
one for CLA Manager designee role and other for company owner role. However When I accept invite link from one of the email(tried with company owner role email), both company owner and cla manager designee role is assigned. When user tried to accept invite in other email, there is no error and did not find any issues.
Wanted to check if the current behavior is fine?

Also email subject says cla manager designee role. Is that fine?
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/6e6f8cdd-3742-4026-bf75-92643ec93a68)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/be0d5f76-f122-4f43-9013-b1eec8302848)

**Comment by nirupamav** [comment]
Verified that the issue is fixed. However observed issues with email and logged ticket #1879 to track the issue
