### ISSUE TITLE
V2 - CLA Not Signed - There is no API call from frontend to assign cla manager designee role/company owner role

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1794]
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group

**Steps to Follow**
1. Login to Github as corporate contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Search and select company that has not signed CLA for the project
9. Click Proceed
10. Click Yes
11. Click Proceed
12. At this point user should be redirected to login page and after logging in API call should be made for cla manager designee role assignment/company owner role assignement
However this step is skipped and in current tab user is redirected to github and in another tab user is redirected to lfx

**Comment by amolsontakke3576** [comment]
@dealako @nirupamav I was removed LF login flow due to some misunderstanding of functionality but I guess that is required 
I will add that and raise PR.

**Comment by nirupamav** [comment]
Verified that the issue is fixed
