### ISSUE TITLE
V2 - CLA Not Signed - Company owner role is assigned for existing company that does not have company owner

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1795]
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group

**Steps to Follow**
1. Login to Github as corporate contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Search and select company that has not signed CLA for the project and that does not have company owner
9. Click Proceed
10. Click Yes
11. Click Proceed
12. Create new account
13. Observed that company owner role and cla manager designee role is assigned for the user. As discussed in the review meeting with @pranab-bajpai and @dealako , company owner role should not be assigned to existing companies

**Comment by dealako** [comment]
@amolsontakke3576 the endpoint is already there. Work with @wanyaland and ticket #1789 to complete this work.

**Comment by amolsontakke3576** [comment]
@nirupamav  As per discussion below is the frontend implementation for assigning the company owner role.
1. When a company/organization is created, `organizationId` and `CreatedBy` data store in local storage. (This is the array of the newly created organizations to handle scenario if user create multiple organization in the same browser)
2. While assigning the company owner role first we check the organization selected and the user claiming for the owner is the same which is in the local storage
3. If the user and organization is the same then only we assign the company owner role.
4. Using this approach if the user creates multiple organizations on the same browser or multiple users create organization using the same browser still it is working as per expectation.
5. The above use-case failed if the user performs hard cache clear.

**Comment by nirupamav** [comment]
**Verified that company owner role is not assigned to existing company in below scenarios**

**Company without owner**
```
identify user without LFID 
identify user with LFID and belong to same company and not admin/owner
identify user with LFID and belong to same company and is company admin
identify user with LFID and belong to other company and not admin/owner (passed)
identify user with LFID and who does not belong to any company
identify user with LFID and is company admin to other company
identify user with LFID and is company owner to other company
Create new account
Login as user who is company admin for same company
Login as user who is not company admin/owner for same company
Login as user who is company admin for another company
Login as user who is company owner for another company
Login as user who is not company admin/owner but has other role for another company
Login as user who is not associated to any company (user role with Individual account)
```
**Company with owner**
```
identify user without LFID 
identify user with LFID and belong to same company and not admin/owner
identify user with LFID and belong to same company and is company admin
identify user with LFID and belong to same company and is company owner
identify user with LFID and belong to other company and not admin/owner 
identify user with LFID and is company admin to other company
identify user with LFID and is company owner to other company
identify user with LFID and who does not belong to any company
Login as user who is company admin for same company
Login as user who is company owner for same company
Login as user who is company admin for another company
Login as user who is company owner for another company

```
