### ISSUE TITLE
V2 - CLA Not Signed - UI hangs while configuring CLA Manager settings for a company that does not have company owner

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1796]
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group

**Steps to Follow**
1. Login to Github as corporate contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Search and select company that has not signed CLA for the project and that does not have company owner but has company admin
9. Click Proceed
10. Click Yes
11. Click Proceed
12. Login as company admin of the same company or as company admin of another company
13. UI hangs while configuring CLA Manager settings as API call to assign company owner fails.
However CLA Manager designee role is assigned as expected
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/8c854d5f-68c8-4f64-90da-4c11a000bf48)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c1fde267-6097-467e-ba41-3cfd81811c1a)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/32f86d21-2853-4ef3-9c53-eb168d538dbf)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/4b45669b-0c15-4fb7-8a35-62d250865a15)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/e5f9783d-5491-4259-94b9-9b486692e2cb)

**Comment by wanyaland** [comment]
@nirupamav .
Could you verify this use case. Tested company-admin role and was able to assign company-owner role

**Comment by nirupamav** [comment]
Verified that the issue mentioned in the ticket is fixed
