### ISSUE TITLE
V2 - Corporate console - permission issues for cla-manager-designee endpoint

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1798]
Tested with below user roles and observed that they have access to the  cla-manager-designee endpoint. 403 should be returned when below users access the  cla-manager-designee endpoint
**Endpoint**
`https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company/{{companySFID}}/project/{{projectSFID}}/cla-manager-designee`

**httpMethod**
`POST`

**Payload**
```
{
"userEmail": "{{useremail}}"
}
```

**_User role with scope as Individual - No Account_**
`400 is returned instead of 403`
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/36a2326b-2b4d-48cf-a8a6-4794244a3e08)

**Comment by vinod-kadam** [comment]
@wanyaland  please check this - it might have already been fixed.

**Comment by dealako** [comment]
This issue has been resolved.
