### ISSUE TITLE
V2 - Project Console - Delete CLA Group endpoint does not delete CLA Group record from cla-dev-projects-cla-groups table

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1804]
1) Create CLA Group (I tried with standalone project)
2) Delete CLA Group using endpoint https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/cla-group/dea5b680-5c17-4162-a99d-6b0e162f3f7e. Observed that record is not deleted from cla-dev-projects-cla-groups table and due to this CLA service is not disabled in Project service and not able to create CLA Group again for the project

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/8b91431b-8449-4559-b8aa-52ded2869ddc)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/8aafacb1-8cf5-4484-a5ce-d1b3b76588df)

**Comment by rinkeshbhutwala** [comment]
@nirupamav Verified this ticket looks like the issue was fixed so moved this ticket to Ready For QA.

**Comment by nirupamav** [comment]
Verified that the issue is fixed
