### ISSUE TITLE
Move Assignment of Contributor Role to Docusign Callback Flow

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#1808]
## Summary

Move Assignment of Contributor Role to Docusign Callback Flow.

## Background

Currently, the assignment of the Contributor Role is handled by the Contributor Console UI CCLA flow only. We need to assign the Contributor role when we execute the CCLA + ICLA flow as well.  One option is to move this logic to the Docusign callback flow upon successful signing (in one place).

Assign Contributor Role logic

Questions:

1. Do we have the user's info (ID/Email)?
1. Do we know what the document type is? CCLA vs ICLA
1. Contributor Role with "Project|Company" scope for CCLA
1. Not required: Contributor Role with "Project" scope for ICLA????
1. If no LFID, then we don't assign the contributor role.  Should we send an invite? -> NO

## User Story

As a project manager, I want CCLA users to be assigned the Contributor role for CCLA and CCLA+ICLA flows.

## Assumptions

If you are assuming certain facts or scenarios, list them so we have a baseline to understand your request.

- [...] Assumption 1
- [...] Assumption 2

## Questions

List any questions or clarifications that are needed to addressed to satisfy this request.

1. [...] Question 1...
1. [...] Question 2...

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

\(Optional\) Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by dealako** [comment]
Harold - can we confirm that the contributor role is assigned under this flow?

**Comment by manishv09** [comment]
Verified today and found working fine for Staging environment, please refer the attached screencast for reference.
[https://app.zenhub.com/files/194341141/cb8d28fa-d96f-4486-bb48-4dc0c70043f5/download](https://app.zenhub.com/files/194341141/cb8d28fa-d96f-4486-bb48-4dc0c70043f5/download)
