### ISSUE TITLE
Notification email when assigning CLA Manager Designee and Company Owner roles

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#1812]
![Screen Shot 2020-09-15 at 9 09 19 AM](https://user-images.githubusercontent.com/57362064/93235170-cd26dd80-f742-11ea-8e0a-9cf2234b010c.png)

- [ ] Assign the CLA Manager Designee and Company Owner using invite flow, doesn't matter if the user has LFID or not.
- [ ] Send two invite flow emails to the user when user comes to selected area in the flowchart above. One invite flow email will be for assignment of CLA Manager Designee role and the other will be following...

Hello <clacontributor>,

This is a notification email from EasyCLA regarding the newly created Salesforce Organization <company name>. You have been assigned as the company owner for this new organization.

The organization profile can be completed via clicking this [link](url)

If you need help or have questions about EasyCLA, you can read the documentation or reach out to us for support.

Thanks,

EasyCLA support team

**Comment by wanyaland** [comment]
@pranab-bajpai Some clarification for users with no LFID. Since this is the invite flow they will need the user invite link as well which has not been specified in the email template you provided .

**Comment by nirupamav** [comment]
@wanyaland 
This ticket was for invite flow for both users with LFID and without LFID. Does this handle invite flow for user with LFID as well?

**Comment by nirupamav** [comment]
Closing this issue as Invite email is sent to only user without LFID and that flow is working as expected

Due to limitation with Invite flow, invite email cannot be sent user with LFID
