### ISSUE TITLE
EasyCLA V1 UI Rebranding

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#1813]
## Summary

EasyCLA V1 Rebranding - Navigation, Landing and Login Page Updates

## Background

As part of the rebranding initiative, the following changes should be made to the EasyCAL navigation, landing, and login pages for EasyCLA v1.  These changes will include updates to the:

1. v1 Landing Page - [cla-next/ folder structure](https://github.com/communitybridge/easycla/tree/master/cla-next).
    1. Test and validate locally
    1. Requires DNS and CircleCI/Serverless deployment updates to see this
1. v1 Project Console Navigation/Header
    1. Utilize feature flag
1. v1 Corporate Console Navigation/Header
    1. Utilize feature flag
1. v1 Contributor Console
    1. Utilize feature flag
1. v2 Contributor Console (easycla-contributor-console repo)
    1. No Feature Flag needed - just add the new header/auth0 lib update/login -> deploy to DEV directly

[See the Wireframe Diagram](https://wireframepro.mockflow.com/view/platform-style-guide#/page/D75314cb7d207653c4f2622b3a1c99167)

![Screen Shot 2020-09-15 at 3 19 31 PM](https://user-images.githubusercontent.com/519609/93270906-e6da1c00-f766-11ea-86af-8fda0bc877de.png)

![Screen Shot 2020-09-15 at 3 19 37 PM](https://user-images.githubusercontent.com/519609/93270916-eb063980-f766-11ea-9037-439f6ffc8913.png)

The landing and login page work can start immediately.  We are waiting for the Navigation Angular component to be completed by @niravpatel27 team.

## User Story

As a product owner, I want to see the EasyCLA v1 UI with the updated rebranding styles.

## Assumptions

The common angular navigation component will work with EasyCLA v1

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

- [See the Wireframe Diagram](https://wireframepro.mockflow.com/view/platform-style-guide#/page/D75314cb7d207653c4f2622b3a1c99167)
- [LFX Header Repository](https://github.com/LF-Engineering/lfx-header)

**Comment by dealako** [comment]
![Screen Shot 2020-09-22 at 8.59.39 AM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/81b75742-22d4-4c9f-a6be-023db1a6d513)

**Comment by amolsontakke3576** [comment]
@nirupamav  Icons are changed on the landing page. The below icons are given from designing team

![coding.svg](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/9c80d0d3-dd5a-4855-b1d5-0488e90cbd8f)

![building.svg](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/98a57f00-a217-4f9d-903e-b6e49c6ee3e3)

![user (1).svg](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/7ac27012-7fc5-4ba0-a689-99221fe245dd)

**Comment by pranab-bajpai** [comment]
@amolsontakke3576 I have added a few more tasks on this issue.
- [ ] Replace CommunityBridge with LFX in the lfcla landing page.
![Screen Shot 2020-10-07 at 2 31 25 PM](https://user-images.githubusercontent.com/57362064/95380119-e3d8d400-08ab-11eb-8ccc-30f7fc1d32c5.png)
- [ ] Replace CommunityBridge with LFX in the footer of the lfcla landing page
![Screen Shot 2020-10-07 at 2 37 38 PM](https://user-images.githubusercontent.com/57362064/95380192-010da280-08ac-11eb-8513-6a05022ab053.png)
- [ ] Replace the CLA diagram with the cla-diagram*.svg that I have emailed you

**Comment by nirupamav** [comment]
Testing In Progress and logged below bugs
#2081, #2080, #2063, #2061, #2060, #2059, #2058, #2057, #2056
