### ISSUE TITLE
V2 - Contributor Console - User already assigned cla-manager message is displayed for duplicate cla manager designee request 

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1816]
Observed that below message is displayed when cla manager request is sent to a user who is already assigned with cla manager designee for the same project and organization scope
@pranab-bajpai 
The message looks like an error. Shouldn't it be a success message with content like user is already CLA Manager and contact the manager for further process 
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/cdfa44c8-c8cb-4b44-b685-3ff8a77dbf80)

**Comment by pranab-bajpai** [comment]
Take out the "Request Failed" and change the message to following
This user is already a CLA Manager for this organization and project. Click here to send a reminder email to this user

**Comment by nirupamav** [comment]
@amolsontakke3576 @pranab-bajpai 
This user is already a CLA Manager for this organization and project. Please contact them to process your CLA Request.

**Comment by nirupamav** [comment]
Verified that the issue is fixed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/565d695d-e8f5-4fd1-b69d-55b16e02c0d0)
