### ISSUE TITLE
V2 - CLA Not Signed - No LFID - CLA Manager Designee role is assigned with Foundation scope and Project scope for project level CLA group and user is not redirected to project page

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1824]
**Prerequisite**
1. Create a CLA group at Project Level with CCLA enabled
2. Add github repository for the CLA group

**Steps to Follow**
1. Login to Github as corporate contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Select Company that has not signed CLA for the project
9. Click Proceed
10. Click No
11. Enter name and email of user who does not have LFID
12. Click Submit
12. Accept the invite link in the email and create account
13. **Issue1 -** Observed that user is assigned with cla manager designee role with foundation scope and not project scope. Due to this user has to start the CLA process for the project from the beginning 
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/b4896cdc-f9be-4660-b2f4-f8baea12ad20)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/926ab307-73df-4776-9d3d-424b6c407c16)

14. **Issue2 -** User is redirected to dashbaord instead of project page after clicking on invite link and creating account
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/ba64ffe2-01db-4f7c-adae-59ebb3e5a00d)

**Comment by wanyaland** [comment]
@nirupamav . Since multiple projects are associated with claGroups we cant tell which specific project to use when sending the userInvite email hence the reason to use foundationSFID which enables the users to select whichever project they would like to sign up for

**Comment by sudhakar-proxima** [comment]
@nirupamav In this entire process described above, the user doesnt have LFID and hence he clicks on the LFX link and then goes through "Create New Account" page. There is an additional step of Verifying email. All of these steps can happen in different browser sessions at different times. So whenever user does login after creating LFID, he will be taken to default landing page.
If you use the redirection link after creating a LFID and then login with your newly created credentials, it should take the user directly to the Project page.

**Comment by dealako** [comment]
Blocked on this one due to:
- When we send information through the invite flow, we are unable to share additional meta-data to redirect the user back to the console. For example, when provided a CLA Group, we don't know which Foundation or Project from the CLA Group to use...

**Comment by dealako** [comment]
Closing this issue as we are not able to direct user to the exact page due to a limitation on the invite flow logic.
