### ISSUE TITLE
V2 - Contributor Console - Invite email should be sent to user who is identified as CLA Manager designee

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1826]
When user selects No from below popup and then provides email if of user with LFID, email with invite link should be sent and role assignment should not happen via API enpoint invoked from frontend

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a51a5639-f1af-40fd-b824-f7a16650b811)

**Comment by wanyaland** [comment]
@nirupamav . I had a discussion with @prabodh about this use case and its not possible to send email for users with LFID and so the flow with assignment via endpoint will do

**Comment by dealako** [comment]
@wanyaland - I am not following your comment above.  We can send email from EasyCLA to any users with an email.  Is your point that we are limited to the email content based on the invite flow???

**Comment by wanyaland** [comment]
@dealako . Issue here was sending a user invite email with an action point of role assignment. Thats possible for users without LFIDs and not possible for users with LFID

**Comment by nirupamav** [comment]
Invite email cannot be sent to users with LFID and hence closing this ticket
