### ISSUE TITLE
V2 - CLA Signed - Error displayed while assigning contributor role when user already has contributor role for the project/foundation

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1827]
1. Create a CLA Group
2. Add GitHub org and enable repos
3. Sign CLA for the CLA Group from the Corporate console
4. Add GitHub user in the approval criteria
5. In GitHub create PR and proceed to contributor console and select corporate 
**NOTE The GitHub user should have LFID and should have a contributor role for this project**
6. Select company that has signed CLA, Acknowledge affiliation -> New Signature is created for Employee Acknowledgement, approved = true, signed = true, project_id=CLA Group ID, company_id=Organization (internal id)
7. Github user is acknowledged
8. Click proceed
9. Observed that error is displayed and the user is not redirected to GitHub
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a090780b-29dc-40f3-9472-a39b3885f6db)

**Comment by dealako** [comment]
harold - just confirm that your logic that assigns the contributor handles:

- New Signature - approved = true, signed = true (employee acknowledgement use-case)
- Updated Signature -> signed changes from false -> true (individual signature -> docusign flow, updated signature use-case)

Try to set the contributor role, if error...nothing we can do other than log an error message in CW.  Could be conflict - which just means that they already have the roles assigned for that scope, in that case, we are ok anyway.

**Comment by manishv09** [comment]
Verified today and found working fine on staging environment. Please refer attached screencast for more details.[https://app.zenhub.com/files/194341141/aebf2735-882d-4cf7-ad92-1566fd9d4c99/download](https://app.zenhub.com/files/194341141/aebf2735-882d-4cf7-ad92-1566fd9d4c99/download)

**Comment by manishv09** [comment]
Verified today and found the flow is working fine, please refer screencast below for reference:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/fb39287c-e685-479f-a16b-df95ebe3d82a)

**Comment by vinod-kadam** [comment]
As updated by @amolsontakke3576  & @manishv09, when gets directed to docusign for iCLA & if he/she clicks back button then the problem arises - the system consider icla as signed which should not happen. However, as this is a rare case, we decided to log a different ticket to tackle it after the 1st easycla release.

**Comment by vinod-kadam** [comment]
@dealako  & @pranab-bajpai  are good with above comment.
@Manish has logged #2411 for the above issue.
