### ISSUE TITLE
V2 - Corporate console - User is redirected to LFX dashboard instead for appropriate project/foundation from invite link

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1829]
**Prerequisite**
1. Create a CLA group at foundation level with CCLA enabled

**Steps to Follow**
1. Trigger endpoint to request cla manager designee for user without LFID
2. Click the AccpetLink from email notification
3. Create user account
4. Click Verify Email link from the email sent for verification of email for created account
5. User is redirected to LFX dashboard instead for appropriate project/foundation. User should be redirected to the project for which the user is assigned as cla manager designee
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/5a0633ec-ffbc-49ed-a5f7-137a33dc2c5e)

**Comment by dealako** [comment]
@wanyaland do we have any additional control on where the user arrives within LFX?

**Comment by wanyaland** [comment]
@deelako No we dont have control over that. What happens is user invite is sent with the scope 
project|organization scope in this case . And on clicking invite link user should be redirected based on the scope. Am guessing for project type of foundation they will be redirected to dashboard

**Comment by manishv09** [comment]
Verified today and there is issue when user clicks on verify email and gets navigated to LFX page keeps on spinning:

![image (3).png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/1a065396-165f-4afb-bc97-88b5f5a4d1d1)

**Comment by vinod-kadam** [comment]
As updated by Sudhakar, please note that redirection now happens to the dashboard page & not the project page.

**Comment by manishv09** [comment]
Verified it and found working fine post fix from Luis on above mentioned LFX login issue. Also this is not a valid scenario post the change on LFX side, hence closing this issue.
![image (4).png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/5580225a-bf13-4082-a378-3eef536e742a)
