### ISSUE TITLE
V2 - Corporate Console - User without LFID who is added as CLA Manager is not getting added to Signature_ACL in signatures table

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1850]
1. Create CLA Group with CCLA enabled
2. Sign CLA in Corporate Console
3. Add CLA Manager without LFID for the signed CLA project
4. Accept the invite link and create LFID for the user
5. Observed that CLA Manager role is assigned for the user with correct scope. However the CLA Manager is not added to Signature_ACL in signatures table

**Comment by dealako** [comment]
@nirupamav user without LFID is not allowed to be a CLA Manager.  This is a rule.

**Comment by nirupamav** [comment]
@dealako 
Actually through invite flow they are assigned with CLA Manager role, but the CLA Manager is not getting updated in the database after the role i sassigned

**Comment by nirupamav** [comment]
As discussed in standup call user without LFID cannot be added as CLA Manager. A ticket #1882 is logged to update the API response for this flow and also to not send invite email to the user
