### ISSUE TITLE
V2 - Gerrit - Company Not found - Observed error in background after creating company

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1853]
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add gerrit instance
3. Generate template
4. Clone the gerrit repository and commit an changes

**Steps to Follow**
1. Login to gerrit
2. Click on the New Contributor Agreement from Gerrit Agreements page
3. Click on Please review the agreement
4. Change the url accordingly to navigate to corporate contributor console (Require this step in dev environment)
5. Click Auhtorize link
6. Login with contributor LFID
7. Contributor is redirected to Select Company page
8. Create New company
10. Observer error in the background. However I am able to proceed with flow
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/f83d2745-fd03-4135-9a48-c1bede8cd66b)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a810c0ce-e2f0-4450-9561-4a825005d1d5)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/9326aa47-1333-4f4c-822d-f3ca6add0068)

**Comment by amolsontakke3576** [comment]
@nirupamav I have tested flow on dev environment and it is working fine PFA

Create Org 
![Screenshot from 2020-09-23 14-06-54.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/5e189acc-3f8f-486d-bb8e-2b13e5b645ef)

Get Org Details
![Screenshot from 2020-09-23 14-09-13.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/d86dc453-1cc9-4152-a5de-e538bd4b023f)

**Comment by nirupamav** [comment]
I am not able to reproduce the issue and hence moving the ticket to QA Done
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/73e305ba-9914-40ce-80e0-7160dec4b874)
