### ISSUE TITLE
QA: Performance Testing for Contributor Console

### ISSUE THREAD

**Issue by vinod-kadam** [communitybridge/easycla#1855]
The purpose of this Epic is to perform the performance testing for Contributor Console UI and API for V1 data on Stage environment.
For more detail, refer below mentioned Confluence Pages:
     - Project Plan: https://confluence.linuxfoundation.org/display/PROD/Project+Plan
     - Performance Test Cases for Contributor Console: 
       https://confluence.linuxfoundation.org/display/PROD/Performance+Test+Cases+for+Project+and+Contributor+Console

**Comment by dealako** [comment]
Performance testing work is complete. Closing ticket.
