### ISSUE TITLE
EasyCLA System Email - Update Formatting

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#1868]
## Summary

EasyCLA System Email - Update Formatting

## Background

The formatting is poor on this system email. Update to reduce spacing (see screenshot section below).

## Expected behavior

A clear and concise email layout.

## Screenshots

![Screen Shot 2020-09-25 at 8 18 30 AM](https://user-images.githubusercontent.com/519609/94284908-e29cc400-ff07-11ea-9a0c-9609b371a922.png)

## Environment

Please complete the following information:

* Environment: DEV 

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

\(Optional\) Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by nirupamav** [comment]
Spacing is fixed however still the email content is not formatted
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/2d73e624-f18d-4415-89d0-ea5fd05a37ef)

**Comment by nirupamav** [comment]
Verified that the issue is fixed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/6a0e81ba-27f7-4574-a329-e2c6d6621250)
