### ISSUE TITLE
Apache-Style CCLA and ICLA Template Address field alignment off slightly

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#1875]
## Summary

When a new 'apache-style' template is generated via the project console, the address lines 2 and 3 are not aligned properly.

## Background
Generate a CCLA for your project in project.lfcla.com
Log into the corporate console to your company and select to sign the new CCLA you just generated
Observe the address 2 and 3 fields are misaligned
![image](https://user-images.githubusercontent.com/46732999/94313700-34b40880-ff4d-11ea-9243-48d18d43bd6c.png)

## Expected behavior

Change the following values:

for the corporation_address2
change document_tab_anchor_y_offset - from 27 to 20

for the corporation_address3
change document_tab_anchor_y_offset - from 65 to 50

observe better alignment
![image](https://user-images.githubusercontent.com/46732999/94314676-059e9680-ff4f-11ea-80a9-46e1970d4118.png)

**Comment by WillsonHG** [comment]
The ICLA is also slightly off

For the mailing_address2 
change document_tab_anchor_y_offset - from 24 to 20

for mailing_address3
change document_tab_anchor_y_offset - from 60 to 48

**Comment by dealako** [comment]
@WillsonHG deployed, ready for QA

**Comment by nirupamav** [comment]
**Observed that the alignment is still not fixed**

**_CCLA_**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/9ab5518d-7dcc-4c18-b1f4-ebd5f1248790)

**_ICLA_**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/1a78f2c2-b186-4830-8b7a-60aa586f09cb)

**Comment by WillsonHG** [comment]
testing this morning, my alignments are just a bit different as well

icla
![image](https://user-images.githubusercontent.com/46732999/94699209-10b74500-0308-11eb-9e13-b1544e28007f.png)

ccla
![image](https://user-images.githubusercontent.com/46732999/94699481-5a079480-0308-11eb-983e-f41501f4a422.png)


Not sure why they are a bit different for each new project created, but I think they are in an acceptable range, much better than before.
