### ISSUE TITLE
V2 "get corporate contributors for project" API should be allowed for Organization scope.

### ISSUE THREAD

**Issue by sudhakar-proxima** [communitybridge/easycla#1878]
"get corporate contributors for project" API https://api-gw.dev.platform.linuxfoundation.org/v4/company/{companySFID}/project/{projectSFID}/contributors doesn't allow the user to fetch the contributors as the API is checking for "Project | Organization" scope. However, a corporate user in LFX who is associated with the organization can fetch the CLA Manager, Approval Criteria & events for a particular Project & Organization.
He is forbidden access to the above API as the scope is checked for Project | Organization.

`curl --location --request GET 'https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company/0012M00002OugBpQAJ/project/a096s00000037xlAAA/contributors' \
{
    "Code": "403",
    "Message": "EasyCLA - 403 Forbidden - user johndoe2 does not have access to get contributors with Project scope of a096s00000037xlAAA or Project|Organization scope of a096s00000037xlAAA | 0012M00002OugBpQAJ"
}`

**Comment by dealako** [comment]
Merged PR: https://github.com/communitybridge/easycla/pull/1887

Project:
- a096s00000037xlAAA - Barclay Architecture :: ProjectType: Project Group

Company:
- proxima - 0012M00002OugBpQAJ

**Comment by nirupamav** [comment]
@sudhakar-proxima
Issue is reproducible with both Project|Organization scope and only Organization scope for different roles. All corporate console endpoints permission related issues are tracked in #1975 and hence closing this ticket
