### ISSUE TITLE
V2 - Company Not Found - Email subject and content issue when invite emails are sent to company-owner and cla-manager-designee

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1879]
**Prerequisite**
1. Create a CLA group with CCLA enabled 
2. Add github repository for the CLA group

**Steps to Follow**
1. Login to Github as corporate contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8.Click on building icon
9. Click on Organization not listed? + Click Here
10. Enter new company details
11. Click Next
12. Click Proceed
13. Click No
14. Enter name and email of user who does not have LFID
15. Click Submit
16. Observed that invite email is sent to Company Owner and CLA Manager Designee. However observed below issues with the email
**Email subject says cla manager designee role. User need not know about role assignment. Subject has to be changed**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/6e6f8cdd-3742-4026-bf75-92643ec93a68)

**Email subject says becoming CLA Manager with company-owner role. User need not know about role assignment. Subject has to be changed. Also email content should inform user that they can access the link and complete Organization profile**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/be0d5f76-f122-4f43-9013-b1eec8302848)

**Comment by nirupamav** [comment]
Below is the comment from Steve
When the company is brand new, two emails are sent with the following subject lines:
EasyCLA: Invitation to create LF Login and complete process of becoming CLA Manager with cla-manager-designee role
Please remove “with cla-manager-designee role” from the end of this subject line. That is an internal detail that will not be meaningful to the user and will likely just be confusing.
EasyCLA: Invitation to create LF Login and complete process of becoming CLA Manager with company-owner role
This second email should not be sent, or at a minimum should be much clearer about what its purpose is. Currently the main relevant text just says “You have been identified as company owner” and has an “Accept Invite” link. 
Keep in mind that this scenario is most likely for a brand new company that has never contributed to or been engaged with the LF before, so this will be quite confusing to the recipient.
The “Accept Invite” link also doesn’t tell the CLA Manager Designee what they need to do. It is a generic link that goes to the LFX login page. The instructions should explain to them what they need to do (which may be e.g. create an LF Account, then navigate to this particular foundation or project page, etc.)

**Comment by pranab-bajpai** [comment]
@wanyaland 
For the first email following message should be added **above** "Accept Invite" link. 
This email will guide you to completing CLA Manager role assignment. 
1. Accept Invite link below will take you SSO login page where you can login with your LF Login or create a LF Login and then login. 
1. After logging in SSO screen should direct you to CLA Corporate Console page where you will see the project you a re associated with. 
1. Click on workflow steps to complete the signup process. Please follow this documentation to help you guide through the process - https://docs.linuxfoundation.org/docs/v/v2/communitybridge/easycla/cla-manager-designee-or-initial-cla-manager
1. Once you have completed CLA Manager workflow you will be able to manage the approved list of contributors

For the second email following message should be added **above** "Accept Invite" link.  
This email will guide you to completing Company Owner role assignment. 
1. Accept Invite link below will take you SSO login page where you can login with your LF Login or create a LF Login and then login. 
1. After logging in SSO screen should direct you to Organization Profile page where you will see your company. 
1. Please complete the company profile, you can follow this documentation to help you guide through the process - https://docs.linuxfoundation.org/docs/v/v2/communitybridge/company-dashboard/manage-your-organization

**Comment by nirupamav** [comment]
Verified that the issue is fixed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/274d6f7d-36dd-4712-824f-a2dfd383cd67)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/71b21cc3-4679-4359-874a-629c5192533e)
