### ISSUE TITLE
V2 - Project Console - Activity Log - Event summary field has SFID/internlaId details in few scenarios

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1880]
**1. When contributor role is assigned for github user, Event summary has project SFID and Company SFID details**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/018db3de-d732-4b37-b1ed-a161c8c60cc6)

**2. When CCLA is signed by company, internal projectId and internal company id are displayed**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/3eec99cb-6113-4cf3-9164-9a95f7134793)

**Comment by dealako** [comment]
Created and merged PR: https://github.com/communitybridge/easycla/pull/1884

**Comment by nirupamav** [comment]
**Issue is still reproducible**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/5bf5e6a2-8890-4816-a743-f5a6478541bf)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/ae03c61c-3c9d-417d-8d51-f35f66cbc2d6)

**Comment by dealako** [comment]
@nirupamav wanted to confirm - these updates to the event log only apply to _newly created_ log entries. We _do not_ go back and update existing log entries as they are write-only.

Given this, I am reviewing the assigned role scope [event log summary string](https://github.com/communitybridge/easycla/blob/master/cla-backend-go/events/event_data.go#L982-L986), which shows that I have removed the scope (with ID's) portion.

Additionally, the second screen shot should be fixed for _new_ event log entries as well, see [this bit of python magic](https://github.com/communitybridge/easycla/blob/master/cla-backend/cla/models/docusign_models.py#L1389-L1407).

**Comment by nirupamav** [comment]
Issues mentioned in the ticket are fixed. However in below summary userid is displayed and issue is tracked in ticket #1923. 
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/f2be83ca-fcbb-4e8d-a8c4-baf0cde12eb9)
