### ISSUE TITLE
Added repositories are not updating correctly in Project Console UI when added.

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#1898]
## Summary

When project manager adds a repository to their cla group - the repo is not shown in the UI even though it is successfully installed when checking the dropdown box. 

![image](https://user-images.githubusercontent.com/46732999/94698450-545d7f00-0307-11eb-8c4b-af05e49b37ad.png)

You can see the main UI does not match the 'Configure Repositories' list.

**Comment by WillsonHG** [comment]
![image](https://user-images.githubusercontent.com/46732999/94710720-2bdc8180-0315-11eb-9ded-8b5736d2ed8f.png)

**Comment by amolsontakke3576** [comment]
@WillsonHG  @dealako @wanyaland I have tested the above issue and it is from the backend. PFA

I have added `Avyukta-telecom` for `Aamla Group`.
![Screenshot from 2020-10-01 14-41-38.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/ec28f4d2-cf0a-4330-af45-d641d8525d9c)

But still in response, I get older records ( in this case empty array).
![Screenshot from 2020-10-01 14-49-15.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/12653c3c-0fd7-4416-ac87-c33f0d77c8cf)

On UI.
![Screenshot from 2020-10-01 14-42-05.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/1c55a06b-516d-404e-8b32-f09806680c9f)

**Comment by wanyaland** [comment]
@amolsontakke3576 . So the repositories returned are fetched from Github and the UI is unable to handle it properly. I added an enabled flag that determines whether the repo has been added or removed. So if its false the UI should show the ADD function otherwise REMOVE.
An example 
```
    {
      "auto_enabled": false,
      "branch_protection_enabled": false,
      "date_created": "2020-10-12T13:09:33.000000+0000",
      "date_modified": "2020-10-12T13:10:32.225915+0000",
      "organization_company_id": null,
      "organization_installation_id": "12349136",
      "organization_name": "alicia-org",
      "organization_name_lower": "alicia-org",
      "organization_project_id": null,
      "organization_sfid": "a09410000182dD2AAI",
      "project_sfid": "a09410000182dD2AAI",
      "version": "v1",
      "repositories": [
        {
          "repository_github_id": 303395377,
          "repository_name": "alicia-org/repo1",
          "repository_type": "github",
          "repository_url": "https://github.com/alicia-org/repo1",
          "enabled": false
        },
        {
          "repository_github_id": 303397415,
          "repository_name": "alicia-org/repo2",
          "repository_type": "github",
          "repository_url": "https://github.com/alicia-org/repo2",
          "enabled": true
        }
      ]
    } ```

**Comment by amolsontakke3576** [comment]
@wanyaland I have made the changes you suggested for the flag `enabled` and below are observation
1. When the user Remove the repo then the flag is changed from true to false (Correct behavior).
2. When the user Adds the repo then the flag is still false, it should be true.

can you please work on point 2 use-case?

**Comment by nirupamav** [comment]
**Before adding repos for V1repositoriesissue githuborg**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/d0aa1066-a353-42c3-a7f3-88bbffa63c15)

**After adding few repos for V1repositoriesissue githuborg**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/e4885c19-7083-4a66-b1da-d8077df585fe)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/7735a03c-63e5-4be6-920d-51e912c85ed8)

**After added repos for V1repositoriesissue githuborg**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/fb67f48e-0f30-4a06-a17d-b6c4ba89bc15)

**Comment by nirupamav** [comment]
@WillsonHG 
Could you please review before closing the ticket

**Comment by WillsonHG** [comment]
This should be reopened because I observed a few more issues today in dev. When adding a repo - it is creating a new database entry instead of changing the original one to enabled. This duplication is causing issues with the 'add/remove' options and is also causing issues with the display. The functionality is still mostly broken.

Also, once a repo has been added to a cla group and then removed, the user is unable to add it to another cla group. The logic for checking to see if a repo is being used on another cla group needs to be updated.

**Comment by dealako** [comment]
Added logic to prevent duplicates. If repo exists and is disabled, it will then be enabled.

**Comment by WillsonHG** [comment]
Thanks @dealako  Confirmed in Dev today that adding a repo and then removing does change it from enabled = true to enabled = false. Then confirmed that when reenabling it, that it was switched back to 'true' instead of creating a new row. Also tested the enable all and disable all features and they are also working as I was unable to break it in any combination.
