### ISSUE TITLE
V2 - Contributor Console - Not able to view downloaded templates

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1899]
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group

**Steps to Follow**
1. Login to Github as corporate contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Download CCLA or ICLA pdf 
8. Not able to open the file due to below error
{"Code":"NoSuchKey","Message":"NoSuchKey: The specified key does not exist.\n\tstatus code: 404, request id: EEA6120E648FE9FD, host id: KC5Q++dcAxm7P7QYCpt4dpZk4KjZNHl6YiNGYIsFF9SxeblFPI/nY4IqiQ+aChKjSuXVgqHaRuQ="}

**Issue reported by Steve**
The Download PDF buttons are not working correctly. Each one downloads a .pdf file which is empty, and consists of the following in plain text: 
{"Code":"NoSuchKey","Message":"NoSuchKey: The specified key does not exist.\n\tstatus code: 404, request id: 42922397AECB02C1, host id: UT1CykflO2wABPqncznHMZn+Fg9rDVLad19mw4PMxmSZXoN17u7/JA5bNb4+/gI+9koDrGmAsEk="}

**Comment by dealako** [comment]
Pushed PR: https://github.com/communitybridge/easycla/pull/1904 to resolve this issue.

**Comment by dealako** [comment]
Seems to be resolved in DEV... awaiting QA confirmation.

**Comment by nirupamav** [comment]
**Verified that the issue is fixed**
**_CCLA_**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/18f42932-6375-4987-8d67-3ffe8bd3e315)

**_ICLA_**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/d6113ef1-91ee-46f4-ba09-c3531864a038)
