### ISSUE TITLE
V2 - Company Not Found - Focus is moved out of New Organization popup when hit on TAB key

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1900]
**Prerequisite**
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group

**Steps to Follow**
1. Login to Github as corporate contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. 8.Click on building icon
9. Click on Organization not listed? + Click Here
10. Enter Organization website
11. Hit TAB key
12. Focus is moved out of popup. Focus should be on next field. User should be able to move to next fields with TAB key
**Issue reported by Steve**
When hitting the Tab key to go between text entry fields in the modal dialog, the Tab key actually goes to edit the text field in the disabled pane behind the modal.

**Comment by dealako** [comment]
@amolsontakke3576, simple fix, let’s use the HTML attributes to allow the user to properly tab through the form controls.

**Comment by manishv09** [comment]
Focus is shifted to next field i.e. "Enter Organization Name" but the suggestions are still displayed to the user, hence rejecting the issue fix:
Please refer the below screencast for more details:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/3a2fcf38-26f0-4a00-bcf8-3f688647ab3b)

**Comment by manishv09** [comment]
Verified successfully today. moving the ticket to QA Done for further review. Please refer the screencast as below:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/7850aa8d-a47c-4598-8b08-020c4ed729f7)
