### ISSUE TITLE
New GitHub Organization Branch Protection

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#1914]
## Summary

New GitHub Organization Branch Protection

## Background

Although the UI doesn't seem to provide a checkbox to enable branch protection when the GH Organization is created on the UI, we want to support the condition on the API.  As a result, we need to add the New GH Added dynamodb event trigger to ensure that we process the branch protection logic.

## Tasks

- [ ] Add a DynamoDB NEW GitHub Organization Event Handler
- [ ] Refactor the UPDATE and NEW logic to call a common routine enable branch protection when the flag is set

## User Story

- As a project manager, I want to enable branch protection when I create the GitHub repository in EasyCLA.

## Assumptions

- EasyCLA GitHub bot has admin access

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

\(Optional\) Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by nirupamav** [comment]
- Verified that user is able to enabled/disable branch protection
- When branch protection is enabled and later if repo is enabled, rule is added to the repo
- When rule already exists for repository and when branch protection is enabled for repo, existing rule is not overridden
- As discussed in EasyCLA standup call, we would not be removing the rule when branch protection is disabled

**When branch protection is enabled**

- Owner cannot make changes and commit directly. Owner is also gated by CLA. Can merge only after CLA check is passed
- Contributor cannot make changes and commit directly. Contributor is gated by CLA. Can merge only after CLA check is passed

**When branch protection is disabled**

- Owner can make changes and commit directly. 
- Contributor cannot make changes and commit directly. Contributor is gated by CLA. Can merge only after CLA check is passed
- Owner can commit contributors changes directly
