### ISSUE TITLE
V2 - Project Console - In UserAssociatedWithCompany event type event summary has userid and github id

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1923]
Observed that in UserAssociatedWithCompany event type event summary has userid and github id
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/9bc3bd32-6f91-4fe7-9102-fe8405c78938)

**Comment by dealako** [comment]
Rinkesh published PR: https://github.com/communitybridge/easycla/pull/2023 and I merged it.

**Comment by nirupamav** [comment]
Verified that the issue is fixed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/d4e120d3-ebbd-4e07-83d1-d5fee7bea861)
