### ISSUE TITLE
Export Project Signature

### ISSUE THREAD

**Issue by jpalmerLinuxFoundation** [communitybridge/easycla#193]
**Summary**

Many project managers want to see a full list of signatures related to their projects. CCLA Signatures, Confirmed Employee Affiliations, and Individual CLAs need to be accessible to project managers.

**Background**

When a user selects a project and clicks on a CLA group's "View Signatures," we want to display a link to a CSV for the most current list of signatures related to the CLA group (project_id)

**User Story**

As a project manager, I need to know who has signed a CLA so that I troubleshoot and report contributor participation.

Given a CLA group in EasyCLA Project console
When a user clicks the "View Signatures" button
Then an export button appears on the window overlay

![image](https://user-images.githubusercontent.com/51214959/65779685-da038900-e10d-11e9-9929-c4a568219078.png)

The export includes the following data:
**Project Name**
- CLA Group Name

**Type**
1. CCLA Manager (signature_type: ccla; signature_reference_type: company; signature_acl[x])
2. Employee (user_company_id: [cla_*_companies.company_id)
3. Individual (signature_type: cla; signature_reference_type: user)

**signature_signed (as Signature Status)**
1. Signed
2. Pending

**User Name, if it is blank show as blank**
- First Name and Last Name of the person who Signed (cla_*_users.user_name)

**Company**
1. If CCLA Manager, populate with Company Name
2. If Employee, populate with Company Name
3. If Individual, populate with N/A

**LF Email, if it is blank show as blank**
- cla_*_users.lf_email (as LF Email)

**LF id, if it is blank show as blank**
- cla_*_users.lf_username

**GitHub ID, if it is blank show as blank**

**CLA Version**
1. - v1.0
2. - v2.0, etc

**Date Signed**
"%m/%d/%Y"

**Acceptance Criteria**

The "done" criteria when this feature or problem is resolved.  Such as:
1. Unit Tests added and running in CI
2. Functional Tests updated to cover feature, if applicable
2. Demonstrate the set of capabilities to the product team while the code is
   running in the STAGING environment.

**Comment by jpalmerLinuxFoundation** [comment]
![image](https://user-images.githubusercontent.com/51214959/65096392-7bf6d900-d98a-11e9-9252-c2c3b9ab7f8a.png)

**Comment by jpalmerLinuxFoundation** [comment]
icon: 
![icon-download](https://user-images.githubusercontent.com/51214959/65096402-83b67d80-d98a-11e9-8b46-8cae5868f9fc.png)

**Comment by jpalmerLinuxFoundation** [comment]
Even though the sample export sheet has two projects, I'm only expecting one project to be exported at a time.

**Comment by CareyLF** [comment]
@jpalmerLinuxFoundation Vulnerability Detection uses this symbol for exporting to CSV:
![image](https://user-images.githubusercontent.com/52999704/65693380-10b3a380-e029-11e9-8d76-a015364fe9a1.png)
for example on this page: https://security.dev.platform.linuxfoundation.org/#/d0f8edd0-b233-407d-a929-9fc0d2a64fb4/licenses
Should the export symbol match across services?

**Comment by swinslow** [comment]
This sounds like a great feature for Project Managers to have access to. A few comments:

- Should only be accessible by project managers
- Should only cover the projects for which they are a project manager (e.g. if someone is a Project Manager for CNCF, then CNCF shows up in their report but e.g. ONAP doesn't)
- Limit the report data to what's relevant -- e.g. CLA signature status, name, company (where it's a CCLA). Email and LFID seems appropriate here too. Would omit e.g. phone numbers or physical addresses in this report though, for CLAs where those might be captured.

**Comment by jpalmerLinuxFoundation** [comment]
> @jpalmerLinuxFoundation Vulnerability Detection uses this symbol for exporting to CSV:
> ![image](https://user-images.githubusercontent.com/52999704/65693380-10b3a380-e029-11e9-8d76-a015364fe9a1.png)
> for example on this page: https://security.dev.platform.linuxfoundation.org/#/d0f8edd0-b233-407d-a929-9fc0d2a64fb4/licenses
> Should the export symbol match across services?

I've updated the mockups and the icon to use. Thanks for catching this.

**Comment by dealako** [comment]
Implemented in EasyCLA v2.  @nirupamav can we confirm that this feature is working for EasyCLA v2 Corporate Console?

**Comment by nirupamav** [comment]
@dealako 
We have an option to download ICLA's and as well CCLA's in Project Console of EasyCLA V2

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/0e32fedb-df5b-40cf-973d-70e970b1ff1b)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/0d9078db-a2d1-48bb-b0ae-7cee4d41c89f)
