### ISSUE TITLE
V2 - Foundation Level CLAGroup - CLA Not Signed - Proceed as CLA Manager designee - CLA Manager Designee role is assigned for both Foundation and child projects when CLA Group is at foundation level

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1937]
**Prerequisite**
1. Create a Foundation Level CLA group with CCLA enabled 
2. Add github repository for the CLA group

**Steps to Follow**
1. Login to Github as corporate contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. Select Company that has not signed CLA for the project
9. Click Proceed
10. Click Yes
11. Click Proceed
12. Login
13. Click Proceed
14. Click Proceed
12. Observed that CLA Manager desginee role is assigned for both foundation and child
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/5c713471-a09b-49ea-a038-53e7f9009d96)

**Comment by vinod-kadam** [comment]
As discussed, @wanyaland to look at the current code & describe what is the behavior now.
Then we will look at it to see if it is correct or some change is needed.

**Comment by tejasadg** [comment]
1) Verified that if CLA group is created at foundation level then CLA Manager Designee role is assigned to the specified foundation only and not its child/sub-projects.
2) Verified that if CLA group is created at project level then CLA Manager Designee role is assigned to all sub/child projects under that CLA group and not to parent/foundation.
cc: @vinod-kadam @wanyaland

**Comment by vinod-kadam** [comment]
As discussed in the standup, @tejasadg to test more cases.

**Comment by tejasadg** [comment]
## Foundation level CLA group
- If a CLA group is created at the foundation level then the CLA Manager Designee role is assigned to the specified foundation only and not to its child/sub-projects. (At group creation).

- If a CLA group is created at the foundation level with child projects enrolled. Then CLA Manager Designee role is assigned to the foundation and child projects which are enrolled in that CLA group.

- If a CLA group is created at the foundation level with one child project, and after group creation the child project is unenrolled then the CLA Manager Designee role **is removed** from the child project.

- If a CLA group is created at the foundation level and after group creation, one child project is enrolled, then the CLA Manager Designee role is **not assigned** to that child project.

## Project Level CLA group
-  If a CLA group is created at the project level then the CLA Manager Designee role is assigned to all sub/child projects under that CLA group and not to parent/foundation. (At group creation).

- If a CLA group is created at the project level, and after group creation, one project is unenrolled from the CLA group then the CLA Manager Designee role **is removed** from that project.

- If a CLA group is created at the project level and one project is enrolled in that CLA group then that project is **not assigned** a CLA Manager Designee role.

**Comment by dealako** [comment]
Spoke with @wanyaland and we reviewed the code. We agreed on a solution for the above use-cases. I added/committed some placeholder functions and comments to be implemented by Harold today.

**Comment by dealako** [comment]
@vinod-kadam @manishv09 @tejasadg - Deployed changes to DEV. Ready for QA.

**Comment by vinod-kadam** [comment]
Moved to "Ready for QA" as it is now available for QA testing.

**Comment by tejasadg** [comment]
CLA Manager Designee role is still not assigned for foundation level case 4 and project level case 3
Example screenshot for Project Level case 3:-
![Screenshot from 2021-01-07 15-42-00.png](https://images.zenhubusercontent.com/5ef5dcf0c63b2d6363eb509d/5d126923-1ee6-41f0-841b-82c252bac816)

**Child Project-001** is not assigned a CLA Manager Designee role
![Screenshot from 2021-01-07 15-41-45.png](https://images.zenhubusercontent.com/5ef5dcf0c63b2d6363eb509d/3a621624-6892-4bf3-bd3f-9dd7dd74216b)

cc: @dealako @wanyaland @vinod-kadam

**Comment by tejasadg** [comment]
Verified that foundation and project level CLA group above mentioned cases failed that's why rejecting this ticket
cc: @vinod-kadam

**Comment by vinod-kadam** [comment]
As discussed in the syncup call, @tejasadg  to make @Harold the program manager for the above projects so that he can use them for his testing.

**Comment by harold** [comment]
Hello - in case it helps, I suspect you meant to @-mention a different Harold.

Have a great day.

**Comment by vinod-kadam** [comment]
As updated by @manishv09 , he has verified it on Dev & found working fine.
He will verify it on Staging as well.

**Comment by manishv09** [comment]
Verified on staging and found them few of them are working fine and for rest I need to test again as there is an issue reported #2463 which is stopping me.
**Foundation level CLA group Use Cases**
**Just Foundation**
•	If a CLA group is created at the foundation level but no child projects are selected, then the CLA Manager Designee role is assigned to the specified foundation only and not to its child projects. (At group creation). - this needs to be tested again
**Foundation & Child Projects**
•	If a CLA group is created at the foundation level with child projects enrolled, then CLA Manager Designee role is assigned to the foundation and child projects which are enrolled in that CLA group. (At group creation). - this need to be tested again 
**Foundation with Child Projects & Unenrolment**
•	If a CLA group is created at the foundation level with one child project, and after group creation the child project is unenrolled then the CLA Manager Designee role is removed from the child project. - this is fine
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/2ea9e2ad-c44c-402f-bf41-c4caf5e7b4c7)
 
**Foundation with Child Projects & Enrolment**
•	If a CLA group is created at the foundation level and after group creation, one child project is enrolled, then the CLA Manager Designee role is not assigned to that child project. --> This is fine
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/2010b83a-35a4-489e-8520-0cee746bebc5)
 
**Project Level CLA group Use Cases**
**Multiple Child Projects**
•	If a CLA group is created at the project level, then the CLA Manager Designee role is assigned to all sub/child projects under that CLA group and not to parent/foundation. (At group creation). - this is fine
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/f97c2dd2-66a1-43db-bf91-3a9b959cff4f)
**Multiple Child Projects & Unenrolment**
•	If a CLA group is created at the project level, and after group creation, one project is unenrolled from the CLA group then the CLA Manager Designee role is removed from that project. - this is fine
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/1333804e-bf68-4d48-9e86-01ec9ca4315d)
 
**Multiple Child Projects & Enrolment**
•	If a CLA group is created at the project level and one project is enrolled in that CLA group, then that project is not assigned a CLA Manager Designee role. - This is fine 
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/14e53c50-2c24-45a5-ad00-af5a27f92a60)

**Comment by vinod-kadam** [comment]
As updated by Manish, "Multiple Child Projects & Enrolment" use case is working fine on Dev but not on Staging.

**Comment by vinod-kadam** [comment]
As updated by @manishv09 , this is working fine on Staging. So, marking it as QA Done.

**Comment by vinod-kadam** [comment]
This is also available on all PROD.
