### ISSUE TITLE
Infra: Add EasyCLA Stats to the Platform

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#1963]
## Summary

Add EasyCLA Stats to the Platform

## Background

Stakeholders have requested that the EasyCLA system reports stats to the platform which can be saved and used for system dashboards.

## User Story

- As a platform manager, I want the EasyCLA system to share stats with the entire platform.

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the DEV environment.

## References

- Platform Event Triggers [Stats](https://github.com/LF-Engineering/platform-events-triggers/tree/master/stats)

**Comment by swinslow** [comment]
Hi @dealako, which stats are being proposed to include here? Are these stats different from the EasyCLA metrics that have been previously discussed?

**Comment by dealako** [comment]
Craig Ross and @niravpatel27 - today (10/14/2020) we met with our stakeholders and presented the EasyCLA metrics identified in [this spreadsheet](https://docs.google.com/spreadsheets/d/1g8jrbOdFntouBjoB7vTIGZApF3wye1Iin9nmvOwUn0Q/edit#gid=1953813647): 

- Number of CLAs Signed
- Number of Repositories Covered
- Number of CLA Contributors

The stakeholders approved of these for public visibility…and also suggested that we add:

- Number of Communities (which is the # CLA Groups)

**Comment by vinod-kadam** [comment]
As updated by @David, closing this one as it has been completed & verified.
