### ISSUE TITLE
V2 - Corporate Console - requestcorporatesignature endpoint fails when authority name has digits

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1970]
Observed that requestcorporatesignature endpoint fails when authority name has digits. User service accepts digits, however authority name does not accept digits
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/request-corporate-signature
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c8be2150-ce18-4df8-9963-a7d3515b648e)

**Comment by dealako** [comment]
Allowing digits is fine.

**Comment by nirupamav** [comment]
Executed the automation script and observed that the issue is fixed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c42084fe-c4f9-4f6d-9123-37186f3d9d70)
