### ISSUE TITLE
V2 - Corporate Console - Permissions issues with few endpoints

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1975]
**Testdata used for testing**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c4e22cd0-8618-4885-b1b4-f59bcf8db8d1)

**_https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/createCLAManager_**
1. CLA Manager with only Organization scope is able to add CLA Manager

**_https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/deleteCLAManager_**
1. CLA Manager with only Organization scope is able to delete CLA Manager

**_https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/requestCorporateSignature_**
1. CLA Manager designee with only organization scope is able to access the endpoint
2. CLA Signatory with Project|Organization scope is able to access the endpoint 
3. CLA Signatory with only Organization scope is able to access the endpoint

**_https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/getCompanyProjectContributors_**
1. Contributor role. Project|Organization scope. Has access to same organization and only foundation. I am trying to fetch contributors of child project but 403 is returned instead of 200. Also observed this issue when user access access to different project as well
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/dbcf2787-3065-44fd-89d9-31fc178e8ddf)

2. Contact role. Organization scope. Has access to same organization. 403 is returned instead of 200
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/91c19cbe-c0fc-4ea9-ba6a-b8f9b88e642b)

3. Project Manager role. Project|Organization scope. Has access to same organization and only foundation. I am trying to fetch contributors of child project but 403 is returned instead of 200. Also observed this issue when user access access to different project as well
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/db3ce6b1-2861-4ab9-93ef-10af636939fe)

4. Community Program Manager role. Organization scope. Has access to same organization. 403 is returned instead of 200. Also observed this issue when user access access to different project as well
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/075abc73-89b9-45e8-abdb-6e17358337cc)

5. CLA Manager role. Project|Organization scope. Has access to same organization and only foundation. I am trying to fetch contributors of child project but 403 is returned instead of 200. Also observed this issue when user access access to different project as well
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/7b906084-a8e6-4e99-a987-5b14ac84c2ec)

6. CLA Manager role. Organization scope. Has access to same organization. 403 is returned instead of 200
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/11c233c1-2b6e-4c8c-8410-0afce5720cf4)

7. CLA Manager Designee role. Project|Organization scope. Has access to same organization and only foundation. I am trying to fetch contributors of child project but 403 is returned instead of 200. Also observed this issue when user access access to different project as well
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/671c2610-d7c1-44be-b0d2-f3c8889112d0)

8. CLA Manager Designee role. Organization scope. Has access to same organization. 403 is returned instead of 200
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/5e71587d-c29f-439e-9ce6-704cdfee0b4f)

9. CLA Manager Designee role. Project|Organization scope. Has access to same organization and only foundation. I am trying to fetch contributors of child project but 403 is returned instead of 200. Also observed this issue when user access access to different project as well
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/11ec9441-abf2-4051-9ee2-da332c9e6235)

10. Company Admin role. Organization scope. Has access to same organization. 403 is returned instead of 200
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/4413bf2a-c868-442a-ac2b-d45115716d6d)

**Comment by dealako** [comment]
@nirupamav - assigned to @rinkeshbhutwala. Rinkesh - coordinate with Niru on any questions.

My comments from above are:

- If the user doesn't have permission, return an unauthorized status code/message 403.  This is the best behavior.

https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/createCLAManager
1. CLA Manager with only Organization scope is able to add CLA Manager
David: CLA Manager with only Organization scope is able to add CLA Manager -> should only work with project|organization scope as the CLA Manager is tied to this scope and this scope only.  Why is Org only scope being allowed here?

https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/deleteCLAManager
1. CLA Manager with only Organization scope is able to delete CLA Manager
David: CLA Manager with only Organization scope is able to delete CLA Manager -> same as the previous comment

https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/requestCorporateSignature
1. CLA Manager designee with only organization scope is able to access the endpoint
2. CLA Signatory with Project|Organization scope is able to access the endpoint
3. CLA Signatory with only Organization scope is able to access the endpoint
David: scope should be project|org for sure. I forget which roles can execute this - [consult the permission matrix spreadsheet](https://docs.google.com/spreadsheets/d/1KffX1dmJEEMhXQYXDpe7RTsuFTkuEMgjYLak07b4nI4/edit?ts=5f352993#gid=756183687) and confirm with the acs-cli config.

For the others, consult the permission matrix. If they indeed don't have permission, return 403.

**Comment by nirupamav** [comment]
Verified that all issues are fixed
