### ISSUE TITLE
V2 - repositories are not disabled when github organization is deleted from the project

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#1995]
1. Launch admin console
2. Navigate to project that has CLA Group and github org configured
3. Navigate to repositories page of the project
4. Disassociate Githuborg from project
5. Github org was removed however repositories enabled status is still true in database
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/4a6acde4-e9da-4ece-9bae-698888163648)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/665a1964-fc22-4833-ba2d-d65b5f113d03)

**Comment by dealako** [comment]
Submitted PR: https://github.com/communitybridge/easycla/pull/2003

**Comment by dealako** [comment]
Merged - ready for QA.

**Comment by nirupamav** [comment]
Verified that the issue is fixed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/6ca4cb20-afd4-4388-bb97-4ced195e38f2)
