### ISSUE TITLE
V2 - Project Console - Not able to update description when CLA Group name of the project is also provided in the payload

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#2000]
1. Create CLA Group with Groupname as **oct08 FoundationLevel The Linux Foundation Parent** and description as **oct08 FoundationLevel The Linux Foundation Parent**
2. Now using edit cla group endpoint try to update description by providing both CLA Group name and description. Conflict Error is displayed but when cla group is of the same project conflict error should not be displayed
**{{baseurl}}/cla-service/v4/cla-group/7a5f98b0-41ac-4f28-9121-717aeea23b9f**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/b5360877-5e49-4495-98fc-11fbb337e23b)

**Comment by dealako** [comment]
Created another PR: https://github.com/communitybridge/easycla/pull/2120

**Comment by dealako** [comment]
@nirupamav test once more after deployment to DEV?

**Comment by nirupamav** [comment]
Verified that the issue is fixed
