### ISSUE TITLE
V1 - Project Console - Remove button is shown for the repository even if the repository is already removed for the CLA Group

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#2006]
1. Create CLA Group
2. Connect Github org
3. Add repos to CLA Group
4. Remove a repo for the CLA Group. Repo is removed but in UI Remove button is still shown for the repo
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/ccb23625-f4ac-4627-aeca-ef97c116fa2d)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/3ea62327-7dcc-49e6-b861-478b4cda40f4)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/2c01ceb2-7e54-4c4b-8bbe-91a616bd338e)

**Comment by dealako** [comment]
I believe this issue has been resolved.

**Comment by dealako** [comment]
The old v1 console is deprecated and removed.
