### ISSUE TITLE
V2 - Project Console - getCompanyProjectContributors endpoint does not have access to child projects

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#2014]
Observed that getCompanyProjectContributors endpoint does not have access to child projects. 
User with project-manager has access to only foundation and not child project. When trying to query the data using child project sfid in the endpoint 403 is returned, but 200 or appropriate response should be returned
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/getCompanyProjectContributors
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/bdc2b8c0-d9c0-4cf3-807d-b16fc2290704)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c43c3ff8-497d-4252-9edc-a017cdbd1288)

**Comment by dealako** [comment]
Updated permissions check - created PR: https://github.com/communitybridge/easycla/pull/2019

**Comment by nirupamav** [comment]
Verified that the issue is fixed. No error is displayed in UI
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/cbc4c224-e35c-4f36-b970-f8eebc7bdd09)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/6d15c7c2-892c-402f-ba65-4d22cc239282)
