### ISSUE TITLE
V1 - Not able to access V1 Project console and Corporate Console UI's

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#2032]
1. Launch V1 landing page
2. Click Proceed for Project Console
3. Login
4. User is redirected back to landing page
5. Clicked Proceed and again user is redirected back to landing page. Observed same issue for Corporate Console

**Comment by dealako** [comment]
@nirupamav this should be resolved now.

**Comment by nirupamav** [comment]
Verified that the issue is fixed
