### ISSUE TITLE
V2 - Project Console - Recently signed CCLAs are included in PDF zip file after few minutes

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#2033]
1. Create CLA Group with CCLA type
2. Around 5 companies have to sign CLA for the CLA Group
3. Trigger below endpoint. Observed that in the downloaded zip file recently signed CCLAs are not fetched. If we trigger same endpoint after about 15-20 mins then the CCLAs are fetched
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/downloadProjectSignatureCCLAs
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/0fac7aa1-487d-4d0d-807f-60e62a933272)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/3f388e8c-0367-41c0-821d-24375f3c53e6)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c7ca2994-467c-4c0b-9ed0-24feaee50d2c)

**Comment by dealako** [comment]
Based on my memory, the Zip file is re-created, if needed, every 15 minutes.

**Comment by dealako** [comment]
This is the expected behavior.  Closing this issue.
