### ISSUE TITLE
V2 - Project Console - Incorrect signatures count is fetched for cla group

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#2034]
1. Create CLA Group with both CCLA and ICLA type and configure github org
2. Few companies needs to sign CLA
3. Few Individual Contributors and Corporate Contributors should sign CLA
4. Observed that incorrect signatures count is fetched for cla group when endpoint https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/listClaGroupsUnderFoundation is triggered

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/70f6d1b8-5212-45ae-93b0-4dff93cd1eed)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/12215cfc-e156-4d59-9ef5-9cad3b883a1a)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/6cd2cf4a-2506-4223-baf8-285c4dc1ec0d)

**Comment by dealako** [comment]
Total = ICLA + ECLA + CCLA

**Comment by thakurveerendras** [comment]
Issue is tested on DEV & Staging env and found that API is fetching proper signatures count, So making issue status to QA-DONE

**API Endpoint** : 
https://api-gw.staging.platform.linuxfoundation.org/cla-service/v4/foundation/a096s0000003lycAAA/cla-groups
**API Response** 

> {
>     "list": [
>         {
>             "ccla_enabled": true,
>             "ccla_pdf_url": "https://cla-signature-files-staging.s3.amazonaws.com/contract-group/7d0d1cef-a523-42a9-817a-3d58a230364e/template/ccla-2020-12-23T13-19-56Z.pdf",
>             "ccla_requires_icla": true,
>             "cla_group_description": "Branch Protection Test",
>             "cla_group_id": "7d0d1cef-a523-42a9-817a-3d58a230364e",
>             "cla_group_name": "BranchProtection",
>             "foundationLevelCLA": false,
>             "foundation_name": "A-ManStage Foundation",
>             "foundation_sfid": "a096s0000003lycAAA",
>             "icla_enabled": true,
>             "icla_pdf_url": "https://cla-signature-files-staging.s3.amazonaws.com/contract-group/7d0d1cef-a523-42a9-817a-3d58a230364e/template/icla-2020-12-23T13-19-57Z.pdf",
>             "project_list": [
>                 {
>                     "project_name": "A-ManStage-Project009",
>                     "project_sfid": "a096s0000003lysAAA",
>                     "repositories_count": 2
>                 }
>             ],
>             "repositories_count": 2,
>             "root_project_repositories_count": 2,
>             "total_signatures": 2
>         },
>         {
>             "ccla_enabled": true,
>             "ccla_pdf_url": "https://cla-signature-files-staging.s3.amazonaws.com/contract-group/9eeef4f1-fd09-438c-a319-337fa4c5de20/template/ccla-2020-12-29T11-14-20Z.pdf",
>             "ccla_requires_icla": true,
>             "cla_group_description": "Bug-2296 Valiadtion-29122020 Verify ICLA, CCLA",
>             "cla_group_id": "9eeef4f1-fd09-438c-a319-337fa4c5de20",
>             "cla_group_name": "Bug-2296Valiadtion-29122020",
>             "foundationLevelCLA": false,
>             "foundation_name": "A-ManStage Foundation",
>             "foundation_sfid": "a096s0000003lycAAA",
>             "icla_enabled": true,
>             "icla_pdf_url": "https://cla-signature-files-staging.s3.amazonaws.com/contract-group/9eeef4f1-fd09-438c-a319-337fa4c5de20/template/icla-2020-12-29T11-14-20Z.pdf",
>             "project_list": [
>                 {
>                     "project_name": "A-ManStage-Project003",
>                     "project_sfid": "a096s0000003lyrAAA",
>                     "repositories_count": 1
>                 }
>             ],
>             "repositories_count": 1,
>             "root_project_repositories_count": 1,
>             "total_signatures": 2
>         },
>         {
>             "ccla_enabled": true,
>             "ccla_pdf_url": "https://cla-signature-files-staging.s3.amazonaws.com/contract-group/78d63fd7-da93-4142-8153-1f36dc0fcc01/template/ccla-2020-12-24T13-56-22Z.pdf",
>             "ccla_requires_icla": false,
>             "cla_group_description": "CLAGROUP001",
>             "cla_group_id": "78d63fd7-da93-4142-8153-1f36dc0fcc01",
>             "cla_group_name": "CLAGROUP001",
>             "foundationLevelCLA": false,
>             "foundation_name": "A-ManStage Foundation",
>             "foundation_sfid": "a096s0000003lycAAA",
>             "icla_enabled": true,
>             "icla_pdf_url": "https://cla-signature-files-staging.s3.amazonaws.com/contract-group/78d63fd7-da93-4142-8153-1f36dc0fcc01/template/icla-2020-12-24T13-56-22Z.pdf",
>             "project_list": [
>                 {
>                     "project_name": "A-ManStage-Project007",
>                     "project_sfid": "a096s0000003lz1AAA",
>                     "repositories_count": 17
>                 }
>             ],
>             "repositories_count": 17,
>             "root_project_repositories_count": 17,
>             "total_signatures": 1
>         },
>         {
>             "ccla_enabled": true,
>             "ccla_pdf_url": "https://cla-signature-files-staging.s3.amazonaws.com/contract-group/384e1912-473c-4af8-b3be-8d93b431ead8/template/ccla-2020-12-17T12-31-00Z.pdf",
>             "ccla_requires_icla": true,
>             "cla_group_description": "CLAGROUPFOR1307 Series of Test",
>             "cla_group_id": "384e1912-473c-4af8-b3be-8d93b431ead8",
>             "cla_group_name": "CLAGROUPFOR1307",
>             "foundationLevelCLA": false,
>             "foundation_name": "A-ManStage Foundation",
>             "foundation_sfid": "a096s0000003lycAAA",
>             "icla_enabled": true,
>             "icla_pdf_url": "https://cla-signature-files-staging.s3.amazonaws.com/contract-group/384e1912-473c-4af8-b3be-8d93b431ead8/template/icla-2020-12-17T12-31-00Z.pdf",
>             "project_list": [
>                 {
>                     "project_name": "A-ManStage-Project006",
>                     "project_sfid": "a096s0000003lyoAAA",
>                     "repositories_count": 1
>                 }
>             ],
>             "repositories_count": 1,
>             "root_project_repositories_count": 1,
>             "total_signatures": 2
>         },
>         {
>             "ccla_enabled": true,
>             "ccla_pdf_url": "https://cla-signature-files-staging.s3.amazonaws.com/contract-group/db86971f-9e95-49ac-bbc8-2848593d887d/template/ccla-2020-12-14T11-54-39Z.pdf",
>             "ccla_requires_icla": false,
>             "cla_group_description": "CLAGrp-Stage004 Series of Test",
>             "cla_group_id": "db86971f-9e95-49ac-bbc8-2848593d887d",
>             "cla_group_name": "CLAGrp-Stage004",
>             "foundationLevelCLA": false,
>             "foundation_name": "A-ManStage Foundation",
>             "foundation_sfid": "a096s0000003lycAAA",
>             "icla_enabled": true,
>             "icla_pdf_url": "https://cla-signature-files-staging.s3.amazonaws.com/contract-group/db86971f-9e95-49ac-bbc8-2848593d887d/template/icla-2020-12-14T11-54-39Z.pdf",
>             "project_list": [
>                 {
>                     "project_name": "A-ManStage-Project004",
>                     "project_sfid": "a096s0000003lynAAA",
>                     "repositories_count": 0
>                 }
>             ],
>             "repositories_count": 0,
>             "root_project_repositories_count": 0,
>             "total_signatures": 1
>         },
>         {
>             "ccla_enabled": true,
>             "ccla_pdf_url": "https://cla-signature-files-staging.s3.amazonaws.com/contract-group/91609405-6c4c-41a1-9a20-3dad5572090b/template/ccla-2020-12-11T16-13-24Z.pdf",
>             "ccla_requires_icla": false,
>             "cla_group_description": "Test-Staging-CLA Grp 001",
>             "cla_group_id": "91609405-6c4c-41a1-9a20-3dad5572090b",
>             "cla_group_name": "Test-Staging-CLAGrp-001",
>             "foundationLevelCLA": false,
>             "foundation_name": "A-ManStage Foundation",
>             "foundation_sfid": "a096s0000003lycAAA",
>             "icla_enabled": true,
>             "icla_pdf_url": "https://cla-signature-files-staging.s3.amazonaws.com/contract-group/91609405-6c4c-41a1-9a20-3dad5572090b/template/icla-2020-12-11T16-13-24Z.pdf",
>             "project_list": [
>                 {
>                     "project_name": "A-ManStage-Project001",
>                     "project_sfid": "a096s0000003lyhAAA",
>                     "repositories_count": 0
>                 }
>             ],
>             "repositories_count": 0,
>             "root_project_repositories_count": 0,
>             "total_signatures": 2
>         },
>         {
>             "ccla_enabled": true,
>             "ccla_pdf_url": "https://cla-signature-files-staging.s3.amazonaws.com/contract-group/db92d640-4c3d-48a0-a715-cd1975e719ed/template/ccla-2020-12-11T16-24-22Z.pdf",
>             "ccla_requires_icla": false,
>             "cla_group_description": "Test-Staging-CLA Grp-002",
>             "cla_group_id": "db92d640-4c3d-48a0-a715-cd1975e719ed",
>             "cla_group_name": "Test-Staging-CLAGrp-002",
>             "foundationLevelCLA": false,
>             "foundation_name": "A-ManStage Foundation",
>             "foundation_sfid": "a096s0000003lycAAA",
>             "icla_enabled": true,
>             "icla_pdf_url": "https://cla-signature-files-staging.s3.amazonaws.com/contract-group/db92d640-4c3d-48a0-a715-cd1975e719ed/template/icla-2020-12-11T16-24-21Z.pdf",
>             "project_list": [
>                 {
>                     "project_name": "A-ManStage-Project002",
>                     "project_sfid": "a096s0000003lymAAA",
>                     "repositories_count": 0
>                 }
>             ],
>             "repositories_count": 0,
>             "root_project_repositories_count": 0,
>             "total_signatures": 1
>         },
>         {
>             "ccla_enabled": true,
>             "ccla_pdf_url": "https://cla-signature-files-staging.s3.amazonaws.com/contract-group/c01831fc-fd96-4867-86ca-870db374a86c/template/ccla-2020-12-14T10-26-03Z.pdf",
>             "ccla_requires_icla": false,
>             "cla_group_description": "Test-Staging-CLAGrp-003 Series of Test",
>             "cla_group_id": "c01831fc-fd96-4867-86ca-870db374a86c",
>             "cla_group_name": "Test-Staging-CLAGrp-003",
>             "foundationLevelCLA": false,
>             "foundation_name": "A-ManStage Foundation",
>             "foundation_sfid": "a096s0000003lycAAA",
>             "icla_enabled": true,
>             "icla_pdf_url": "https://cla-signature-files-staging.s3.amazonaws.com/contract-group/c01831fc-fd96-4867-86ca-870db374a86c/template/icla-2020-12-14T10-26-03Z.pdf",
>             "project_list": [],
>             "repositories_count": 0,
>             "root_project_repositories_count": 0,
>             "total_signatures": 2
>         }
>     ]
> }
`
**Staging Env**
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/bdd95169-df50-4874-960e-3d296e41fbf6)

**DEV Env**
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/b022f082-cda3-4f69-8b10-c98b82ac1209)
