### ISSUE TITLE
V2 - Contributor Console - Document generation fails with CORS issue and unable to proceed with ICLA flow

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#2035]
1. Create CLA group with ICLA enabled
2. From github try to sign ICLA
3. Observed CORS issue while generating document and not able to proceed with ICLA flow. Tried with different projects and observed same issue
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/db53d6a1-4147-49b9-a602-12fc646355f3)

**Comment by dealako** [comment]
Should be resolved now.

**Comment by nirupamav** [comment]
Verified that the issue is fixed
