### ISSUE TITLE
API - Remove Extra v2 Metrics

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#2038]
## Summary

API - Remove Extra v2 Metrics

## Background

Per stakeholder requirements, remove extra/unused metrics from API response payload.

## Expected behavior

Only include approved metrics.

## Screenshots

![Screen Shot 2020-10-22 at 1.17.29 PM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/2b726c43-8199-43fc-b664-d62ebcda9cc3)

## Environment

All

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

- Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by dealako** [comment]
Created PR: https://github.com/communitybridge/easycla/pull/2039

**Comment by dealako** [comment]
@nirupamav to validate, ensure  GET /metrics/total-count only returns:

```
{
  "data": {
    "easyClaInsights": {
      "createdAt": "2020-10-22T18:30:57Z",

      "projectsCount": 475,

      "individualContributorsCount": 7157,
      "companiesProjectContributionCount": 900,

      "contributorsCount": 8550,
      "repositoriesCount": 129
    }
  }
}
```

**Comment by nirupamav** [comment]
Verified that only above mentioned data is returned
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/9502d07f-07bc-40ad-99be-e2c8c98b7185)

**Comment by swinslow** [comment]
@dealako Unless I'm misunderstanding, this still appears to have the individual vs. company breakout totals. Those shouldn't be broken out.
