### ISSUE TITLE
EasyCLA provides "Checks" tab in PR

### ISSUE THREAD

**Issue by jpalmerLinuxFoundation** [communitybridge/easycla#204]
**Summary**
The projects would like a way to understand better why the CLA check is failing. 
Which of the contributors is NOT covered by a signed CLA? 

**Background**
**Scenario**: CLA check fails: Not whitelisted
1. Go to a repo with EasyCLA configured, and you have **NOT** signed CLA covering you (ICLA or CCLA)
2. Create a PR
3. When the PR fails, click on the "Checks" tab of the PR
4. Check Run completes with the following displayed: (ref: https://developer.github.com/v3/checks/runs/)
- Status: Completed
- Conclusion: Action Required
- Annotations: Failure
- Filename: [filename]
- Title: "EasyCLA: Signed CLA not found"
- Message: "One or more committers are authorized under a signed CLA."
- Raw Output: "[email@address.com] is not authorized under a signed CLA."

**Scenario**: CLA check fails: whitelisted
1. Go to a repo with EasyCLA configured, and you have **NOT** signed CLA covering you (ICLA or CCLA)
2. Create a PR
3. When the PR fails, click on the "Checks" tab of the PR
4. Check Run completes with the following displayed: (ref: https://developer.github.com/v3/checks/runs/)
- Status: Completed
- Conclusion: Action Required
- Annotations: Failure
- Filename: [filename]
- Title: "EasyCLA: Signed CLA not found"
- Message: "One or more committers are authorized under a signed CLA."
- Raw Output: "[email@address.com] must confirm corporate affiliation."

**User Story**
As a project maintainer and committer
I need to see why the CLA is failing
so that I can effectively troubleshoot the issue and sign if necessary.

**Tasks**
1. Update EasyCLA App Permissions (https://developer.github.com/apps/quickstart-guides/creating-ci-tests-with-the-checks-api/#step-11-updating-app-permissions)
2. Add Event Handling (https://developer.github.com/apps/quickstart-guides/creating-ci-tests-with-the-checks-api/#step-12-adding-event-handling)
3. Create Check Run (https://developer.github.com/apps/quickstart-guides/creating-ci-tests-with-the-checks-api/#step-13-creating-a-check-run)
4. Enable check run updates (https://developer.github.com/apps/quickstart-guides/creating-ci-tests-with-the-checks-api/#step-14-updating-a-check-run)
5. Review and implement appropriate Security (https://developer.github.com/apps/quickstart-guides/creating-ci-tests-with-the-checks-api/#part-2-creating-the-octo-rubocop-ci-test)

**Acceptance Criteria**
The "done" criteria when this feature or problem is resolved.  Such as:
1. Unit Tests added and running in CI
2. Functional Tests updated to cover feature, if applicable
3. Demonstrate the set of capabilities to the product team while the code is
   running in the STAGING environment.

**References**
1. https://developer.github.com/apps/quickstart-guides/creating-ci-tests-with-the-checks-api/
2. https://developer.github.com/v3/checks/
3. https://github.com/communitybridge/easycla/issues/169
4. https://github.com/cncf/foundation/issues/26
5. https://github.com/cncf/foundation/issues/3

![image](https://user-images.githubusercontent.com/51214959/64664682-7c84f200-d415-11e9-8810-83b5a09bed81.png)

**Comment by jpalmerLinuxFoundation** [comment]
@dealako, please create a ticket and reference this one as prep for this development

**Comment by ngozi-ekekwe** [comment]
@pranab-bajpai @dealako. I need to clarify what to put under `Filename: [filename]` and context
