### ISSUE TITLE
V1 - Project Console - Incognito Mode - When navigated back in browser session expired message is displayed

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#2056]
1) Launch Landing page in Incognito mode
2) Click on Proceed for Project Console
3) Login
4) Click Get Help -> Docs
5) Docs page is opened in same tab, so to go back to CLA page, I navigated back in browser. Session expired message is displayed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a9c69dd8-84e2-4248-a73a-6e2454cdbdaa)

**Comment by amolsontakke3576** [comment]
As per the last discussion with @lguerralf 
```
Cookies is a new implementation added to fix it but it only works on linuxfoundation.org subdomains
not localhost
```
So to make it work I have to create a small PR's for every change to test on a specified domain,

**Comment by dealako** [comment]
Won't fix. Focus is on the v2 UX.
