### ISSUE TITLE
V1 - Project Console - Incognito Mode- User is logged out and redirected to Landing page when refreshed the project details page

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#2057]
1) Launch Landing page in Incognito mode
2) Click Proceed for Project Console
3) Login
4) Click on any Foundation/Project
5) Refresh the page after user is navigated to the project 
6) Observed that user is logged out and redirected to landing page

**Comment by amolsontakke3576** [comment]
As per the last discussion with @lguerralf 
```
Cookies is a new implementation added to fix it but it only works on linuxfoundation.org subdomains
not localhost
```
So to make it work I have to create a small PR's for every change to test on a specified domain,

**Comment by dealako** [comment]
Won't fix. Focus is on v2 UX.
