### ISSUE TITLE
V1 - User Profile Pic is not displayed as expected in Project Console and Corporate Console

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#2059]
1) Launch landing page
2) Click SignIn in header and Login
3) Observed that profile pic is displayed as expected in landing page
4) Click on Proceed for Project Console/Corporate Console
5) Observed that Profile pic is not displayed as expected in all pages of Project Console/Corporate Console. Issue is observed when user has profile pic and also when default profile pic is displayed
**Firefox**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/fa1c7463-1f71-4b79-8f8b-af93d37dede2)

**Chrome**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/891045b5-3687-453a-84e7-4972657982f0)

**Comment by nirupamav** [comment]
Verified in chrome and firefox and observed that the issue is fixed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/faf9622f-da55-444d-b1c4-8d7e9b2bfb51)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/1582c227-125b-45b2-81a9-84dc6eb70f4e)

**Comment by nirupamav** [comment]
@amolsontakke3576 
Sometimes still the profile pic is not displayed and hence reopening the ticket. 
![image](https://user-images.githubusercontent.com/60865903/97689694-fb2d6a80-1ac1-11eb-8f10-f850035643b7.png)

![image](https://user-images.githubusercontent.com/60865903/97689716-02547880-1ac2-11eb-855c-28f9dc2cc370.png)

**Comment by nirupamav** [comment]
Issue is still reproducible when default profile pic is displayed for the user
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/b4bfcbed-8745-436b-9d3d-3d78712d8de0)

**Comment by dealako** [comment]
The old v1 console is deprecated and removed.
