### ISSUE TITLE
V1 - Project Console - Scroll bar is hidden behind the header until user scroll downs a bit

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#2060]
1) Launch landing page
2) Click Proceed for project console
3) Login
4) Observed that scroll bar is not displayed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/36420bea-7cda-4823-8389-89aabdf5b592)
5) When we click on the scroll bar area for few times then we are able to see the scroll bar
Not sure if this issue exists in Corporate Console as I did not have much data in the UI
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/0138d974-c692-44f7-973c-5306e35cf15e)

**Comment by tejasadg** [comment]
@nirupamav If this is not reflecting then please reset the cache and try.

**Comment by nirupamav** [comment]
Verified that the issue is resolved
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a6217f0d-8ceb-433d-9809-0c70c6530ffd)
