### ISSUE TITLE
V1 - Corporate Console - There are duplicate links for Get Help and EasyCLA Documentation

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#2061]
1) Launch landing page
2) Click Proceed for Corporate Console
3) Login
4) Click on a company
5) Click Sign New CLA
6) Select a project
7) Observed that there are duplicate links for Get Help and EasyCLA Documentation
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/1ef15749-eace-4253-a6e2-8800e00facb7)

**Comment by dealako** [comment]
@amolsontakke3576: Pranab has recommended:

- Header: Should have two drop-down menu items:
  - Docs -> EasyCLA v1 Documentation -> Project/Corp/Contrib Help page (based on which console you are in)
  - File a Support Ticket -> link to support ticket page
- Footer: 
  - Change "Get Help" to say: "File a Support Ticket" -> link to support ticket page
- Remove duplicate documentation button

**Comment by amolsontakke3576** [comment]
@nirupamav @dealako 
In LFX header support menu in dropdown is named with '**Support**' so we can not change it to **File a Support Ticket**
So I kept same in footer as **Support**

**Comment by nirupamav** [comment]
**Verified**
**V2 Contributor Console**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/1361fd52-572b-4cb6-ab91-f1bc2967c9a6)

**V1 - Project Console - Verified in all pages**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/f6724ccc-63da-4816-a42d-45886ac6e6cc)

**V1 - Corporate Console - Verified in all pages**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/51f0b695-fa88-4db7-854d-772c3444d170)

**V1 - Contributor Console - Verified in all pages in github and gerrit**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/92c3315d-2d88-40b2-a987-10c2763c0693)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/ba50e6ea-f8f0-4bd9-9665-7e3efc6f0a6f)
