### ISSUE TITLE
V2 EasyCLA cannot replicate ASWF CLA Group configuration

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#2068]
I have following configuration 

- PB-Stage-Foundation project group with 3 sub projects PB-Stage-Project1, PB-Stage-Project2, and PB-Stage-Project3. 

- I wanted to create separate CLA Groups for each of the projects. I am able to create CLA Group for the first project without any issues.

- When I create CLA Group for second project I get the following error message
![image](https://user-images.githubusercontent.com/57362064/97447061-274bbe80-18fd-11eb-8ac0-6a7630635bf6.png)

**Comment by vinod-kadam** [comment]
David to take a look at it & see if it can be handled or not needed.

**Comment by dealako** [comment]
Pushed a fancy update that should resolve this issue. Needs more testing.

**Comment by manishv09** [comment]
Verified today and found user is able to add different repo to each child project. Please refer  the screencast for reference:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/695d55a3-acfe-4549-ab49-ee3ee00adc5e)
