### ISSUE TITLE
V1 - Contributor contact forms are not allowing "-" in email

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2069]
## Summary

A contributor or manager's email with a - included is being marked as an invalid email when trying to send a notification to their CLA manager. The - is a valid email domain character. 

## Background

Please review the v1 contributor console forms and make sure that the - is an accepted email character, 

![image](https://user-images.githubusercontent.com/46732999/97482460-912f8c80-192c-11eb-87f6-79ce996fd171.png)

**Comment by dealako** [comment]
@WillsonHG @amolsontakke3576 The EasyCLA API allows dashes, [see the swagger spec](https://github.com/communitybridge/easycla/blob/master/cla-backend-go/swagger/common/properties/email.yaml#L7).

**Comment by dealako** [comment]
@amolsontakke3576 need to review the UI regex and have it match the API

**Comment by dealako** [comment]
@amolsontakke3576 review all Angular email validators and make them consistent:

- Project Console
- Corporate Console
- Contributor Console - v1
- Contributor Console - v2

**Comment by WillsonHG** [comment]
verified on produciton
