### ISSUE TITLE
Contributor console new company flow

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#2071]
- [ ] Do not show this dialog after user has entered their new company information (i.e. URL and name)
![image](https://user-images.githubusercontent.com/57362064/97489449-8e816700-192d-11eb-8e08-e1645fec1a9f.png)
- [ ] Take user directly to "No Signed CLA Found" dialog box
![image](https://user-images.githubusercontent.com/57362064/97489554-af49bc80-192d-11eb-8ecd-888bb0d0479c.png)
- [ ] If the user selects "No" 
![image](https://user-images.githubusercontent.com/57362064/97489668-d56f5c80-192d-11eb-813d-492aaeeb73a2.png)
- [ ] Check if the designated user has a LF Login and if they do make them Company Administrator for the new company. Add the company to SFDB. Send out the invite flow email to this user.
- [ ] If the designated user doesn't have a LF Login. Add the company to SFDB. Send out an email telling the user to complete company profile and create a LF Login. 
![image](https://user-images.githubusercontent.com/57362064/97500994-8d0c6a80-193e-11eb-8b68-74e7ea53e253.png)
- [ ] If the user selects "Yes" at "No Signed CLA Found" dialog box. Take the user all the way to Corporate console login and after that where we show the dialog box of assigning roles and at that stage insert the company in SFDB.

**Comment by nirupamav** [comment]
Testing to blocked due to #2138

**Comment by nirupamav** [comment]
Testing blocked due to #2157

**Comment by manishv09** [comment]
Verified and found working fine. Please find the screencast attached for your reference.
[https://app.zenhub.com/files/194341141/2b0a6aea-ba71-419a-b666-804944a13293/download](https://app.zenhub.com/files/194341141/2b0a6aea-ba71-419a-b666-804944a13293/download)
