### ISSUE TITLE
[Regression] - V1 - Contributor Console - Company added from contributor console is not added to Companies database and CLA Manager not able to see the company in Corporate Console

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#2075]
**Prerequisite**
1. Create CLA Group
2. Configure Github repo for the project

**Steps to Follow**
1. Launch the Github repo
2. Edit file and create PR
3. User is gated by CLA
4. Click on CLA NOT SIGNED
5. Click Corporate
6. Click Company Not in List
7. Click No
8. Enter CLA Manager details and New company name and other details
9. Click Send
10. Email is sent to CLA Manager however company is not added to database and CLA Manager is not able to view Company to proceed with signing process

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c42a9545-e5e4-4ce2-ab0a-b301cde37b4a)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/6c5b4f84-46f1-4f65-8bfc-2a7768d365b6)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/7084bdeb-74d0-4473-882d-ca3dfbf15455)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/559e8b1b-f95f-4f65-8569-8a67b2c44ab5)

**Comment by dealako** [comment]
@rinkeshbhutwala - follow the workflow with Amol's help. Let's see if there's any errors in the /v2 python or /v3 golang logs.

**Comment by rinkeshbhutwala** [comment]
@dealako I have gone through the **workflow** and found that we are calling  **/v2 python** endpoint which is  [https://api.dev.lfcla.com/v2/user/{userID}/invite-company-admin]()  and checking the **logs** as well looks like I did not find any **error** over there and also tried from **postman** it returns 200 with **Null** response.

**Comment by dealako** [comment]
The old v1 console is deprecated and removed.
