### ISSUE TITLE
V2 - Contributor Console - CLA Not Signed - Observed Request Failed and Org not found issues

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#2078]
**_While executing automation scripts observed intermittent issues. Sometimes Created Organization is not fetched in Select Organization. Sometimes Request Failed message is displayed while requesting CLA Manager designee_**

**Issue1 - Select Organization issue**
```
Test Data1
CLAGroupId: aeaa5148-158c-464b-9eea-2b21683fe406
OrgName: autoclaorg1603959958226
UserID: 981a62a5-ab79-4275-939e-f79d0e394764
Execution Date: 29-Oct-2020
```
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/7be49e21-4b8d-42bb-a34d-529924b91286)

```
Test Data2
CLAGroupId: 4616c724-d81c-40bb-80f5-122c4e27a667
OrgName: autoclaorg1603779622278
UserID: 981a62a5-ab79-4275-939e-f79d0e394764
Execution Date: 27-Oct-2020
```
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/e2438a89-9c07-47a9-aaa2-615b30beb739)

```
Test Data3
CLAGroupId: 52945eb1-ba99-4ecb-992a-cbf4811918fb
OrgName: autoclaorg1603450556767
UserID: 981a62a5-ab79-4275-939e-f79d0e394764
Execution Date: 23-Oct-2020
```
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c8c76bb0-78fb-4a11-85b8-8e27715db7a9)

**Issue2 - Request Failed**
```
Test Data4
CLAGroupId: 0d0b50a9-973b-4070-a6fe-51fb394f4a73
OrgName: autoclaorg1603959641622
UserID: 981a62a5-ab79-4275-939e-f79d0e394764
Execution Date: 29-Oct-2020
```
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/3535ebc4-7612-43d3-8a15-013eddbf9b09)

**Comment by amolsontakke3576** [comment]
@wanyaland  can you please look at this? I have tested and looks like the issue is from the backend

Request URL: https://api.dev.lfcla.com/v3/organization/search?companyName=Test%20Data
Request Method: GET
Status Code: 200 

Response : {list: []}

**Comment by dealako** [comment]
@wanyaland can you check the v3 logs to see if we have any errors related to this API call? Why is it working sometimes and not others? Are we getting any errors from the org service API calls?  Happens in the v2 contributor console only???

**Comment by wanyaland** [comment]
@dealako . I checked and this looks fine and havent seen any errors when testing. The above example Amol used doesnt exist hence empty list. @nirupamav could you kindly reverify

**Comment by nirupamav** [comment]
@wanyaland 
The example that Amol shared does not exist because in automation script data will be deleted at the end of the script. For debugging I can share the test results with you. I am seeing this issue daily when I execute the scripts. I am able to use the org created for assign roles and scopes and also able to delete org, Sometimes only in contributor console or is not fetched
If requried we can sync up and I can walk you through the test results

**Comment by nirupamav** [comment]
@wanyaland 
I tried to debug the executions and observed that this issue occurs when company-owner role is assigned to user after organization is created but Organization name (AccountID) is not updated for the user

User is assigned with company-owner role but organization name is not updated

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/d2b1ca2d-1c2a-4f90-b322-a7e4c227d72d)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/13da537b-7725-4060-8bee-1c1424f780cb)

For the same org company-admin role was assigned and for the user organization name is updated
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/1fff91a1-1668-4eed-bbd5-c4f3fd8a5a42)

**Comment by tejasadg** [comment]
I have verified the above-mentioned scenario and didn't find any issue.
cc: @vinod-kadam @amolsontakke3576
