### ISSUE TITLE
[Regression] - V1 - Contributor Console - Not able to proceed with ICLA flow due to CORS issue

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#2079]
**Prerequisite**
1. Create CLA Group
2. Configure Github repo for the project

**Steps to Follow**
1. Launch the Github repo
2. Edit file and create PR
3. User is gated by CLA
4. Click on CLA NOT SIGNED
5. Click Individual
6. Observed CORS error and not able to proceed further
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/ad8f8ed0-2daa-4daf-97fd-e89422eeb653)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/d23b93ac-0584-4ba5-a48c-50dbd0e0ccc2)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/117981a9-bc1a-4a18-aba2-d25cc06a6771)

**Comment by dealako** [comment]
Should be resolved now.

**Comment by nirupamav** [comment]
Verified that the issue is resolved
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/18ee6187-5ff2-412c-b1f4-1b1ec9a4651b)
