### ISSUE TITLE
V1 - Landing Page - Request Access button is highlighted when clicked

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#2080]
1. Launch V1 landing page
2. Click Request Access for Project Console
3. Observed that the button is highlighted
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/bbb5b340-4b30-454f-9e51-519b00264164)

**Comment by dealako** [comment]
@amolsontakke3576 work with Atul and @pranab-bajpai on how this should look/feel when clicking.

**Comment by nirupamav** [comment]
Verified that the issue is fixed
