### ISSUE TITLE
Replace EasyCLA Footer with Community Bridge Logo with the EasyCLA LFX Logo

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#2084]
## Summary

Replace EasyCLA Footer with Community Bridge Logo with the EasyCLA LFX Logo. See `lfx-easy-cla-white.png` image attached to this ticket.

## Tasks

Review and necessary update the logo in the footer for the following consoles:

- [x] v1 Project Console
- [x] v1 Corporate Console
- [x] v1 Contributor Console
- [ ] v2 Contributor Console

## Background

As part of the rebranding, we want to replace the EasyCLA Community Bridge logo/image with the EasyCLA LFX Logo.

## References

![lfx-easy-cla-white.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/0bfeff7c-07a2-41de-88b7-df454a9f0c6c)

**Comment by dealako** [comment]
Per Amol: No footer for v2 Contributor Console.

**Comment by nirupamav** [comment]
**_Verifed for V1 consoles. As per above comment did not verify for V2 Contributor console as there is no footer_**
**V1 Project Console**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c8047602-b87d-4aef-8122-9c1d735062b2)

**V1 Corporate Console**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/0bef32cd-e0f8-4db6-aa57-2a3f6e68daff)

**V1 Contributor Console**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/197d7f93-d0a4-46e6-8124-d9ea8c3e0162)
