### ISSUE TITLE
V2 - Rebranding Issues - User is redirected to V1 UI when navigating to EasyCLA from LFX header

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#2087]
1. Launch any V2 url for e.g https://lfx.dev.platform.linuxfoundation.org/
2. Login
3. Select EasyCLA from LFX header dropdown
3. Observed that user is redirected to V1 UI
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/48390de9-c094-45a6-aec7-57d30b2a4d81)

**Comment by dealako** [comment]
@pranab-bajpai and @nirupamav can you collaborate/discuss on where this should go when in the v2 Corporate Console?

**Comment by dealako** [comment]
Known issue - closing for now. We'll coordinate with @pranab-bajpai on when to transition the links to v2.
