### ISSUE TITLE
V1 - Not able to navigate back to landing page from consoles when clicked on EasyCLA from LFX header

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#2089]
1. Launch V1 landing page
2. Login
3. Click Proceed for project console (Observed in other consoles as well)
4. Till yesterday we were able to click on EasyCLA option from header and user was redirected to landing page but now we are not able to click the selected option
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/059c7359-81d1-48bc-9b18-80cd363fae44)

**Comment by dealako** [comment]
@nirupamav can you confirm this is now resolved with the latest header updates.

**Comment by nirupamav** [comment]
Verified that the issue is fixed
