### ISSUE TITLE
Icon Update: PDF

### ISSUE THREAD

**Issue by jpalmerLinuxFoundation** [communitybridge/easycla#209]
**Summary**
In each CLA group, when a template was selected we need to update the icon that appears adjacent to the Corporate & Individual CLA headers.

**Background**
1. Navigate to project.*.lfcla.com
2. Select a project
3. Update the icon that appears next to the CLA headers for both ICLAs and CCLAs

**User Story**
As a project manager, I need it to be clear where I can find the current template so that I can share the template and review it easily.

**Acceptance Criteria**

The "done" criteria when the image is updated in staging in all 3 areas of the project console

**References**
As Is:
![image](https://user-images.githubusercontent.com/51214959/65095819-4f41c200-d988-11e9-843e-109eb95480d6.png)
To Be: 
![image](https://user-images.githubusercontent.com/51214959/65095824-51a41c00-d988-11e9-8fd2-5e5af62f8101.png)
![image](https://user-images.githubusercontent.com/51214959/65095829-57016680-d988-11e9-98c3-0d16c234a562.png)
As Is: 
![image](https://user-images.githubusercontent.com/51214959/65095866-7d270680-d988-11e9-9468-03e13819ede0.png)
To Be:
![image](https://user-images.githubusercontent.com/51214959/65095911-ac3d7800-d988-11e9-8bdf-031f844e316a.png)

**Comment by jpalmerLinuxFoundation** [comment]
icon: ![icon-pdf](https://user-images.githubusercontent.com/51214959/65096131-849adf80-d989-11e9-9e63-5abd040b0516.png)

**Comment by dealako** [comment]
![Screen Shot 2019-09-26 at 3 00 27 PM](https://user-images.githubusercontent.com/519609/65728017-678f9c00-e06e-11e9-8c41-6b0e127f4762.png)

**Comment by CareyLF** [comment]
@dealako @jpalmerLinuxFoundation 
Do you have the icon as a png file?
