### ISSUE TITLE
V1 - Not able to navigate back to previous page from browser back navigation in V1 consoles

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#2091]
1. Launch V1 landing page
2. Login
3. Click Project Login from Header Or proceed on Project Console card
4. Project Console is opened
5. Navigate back in browser to navigate back to landing page
5. User is always redirected to project console and not able to navigate back to landing page (Observed the issue in other consoles as well)

**Comment by dealako** [comment]
@nirupamav as per a discussion in the pmm and lfx-design slack channels, this is an issue with the lfx-header => they are working on a fix.  I'm placing this into the QA column. Please verify once the header changes are pushed and available to the product teams.

**Comment by dealako** [comment]
@nirupamav tested during standup on Brave/Chrome and appears to work as expected - can you confirm once more?

**Comment by nirupamav** [comment]
Tested and observed that issue is reproducible in Firefox browser

**Comment by dealako** [comment]
@amolsontakke3576 I have merged a PR for this. Ready for QA?

**Comment by dealako** [comment]
The old v1 console is deprecated and removed.
