### ISSUE TITLE
V1 - Rebranding - Tool tip issues for any link or logo or drop down item in header

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#2092]
1. Launch V1 landing page
2. Login
3. Click Proceed for Project Console card or Corporate Console card
**_Issue1_**
4. Mouser hover on logo or any link, or any drop down item
5. Observed that current page name is displayed as tool tip

**_Issue2_**
6. Tool tip is not displayed in Landing page. Not sure if tool tip is required, since the behavior was inconsistent between landing page and consoles, mentioned the issue here

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/be61d946-2bf5-43bf-9c25-166cadee1b97)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/8ffeefa8-020f-4515-8e5f-6f903f4b735b)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/149938e1-38a8-4e26-9793-b27f55a5a86a)

**Comment by dealako** [comment]
@nirupamav please confirm with @amolsontakke3576 that this is an issue with the lfx-header team and not EasyCLA.  If so, please document the issue there and help close this ticket.

**Comment by nirupamav** [comment]
Logged https://jira.linuxfoundation.org/browse/PMM-847 to track this issue and hence closing this ticket
