### ISSUE TITLE
V2 - Rebranding - There is no footer in Contributor Console

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#2093]
1. Navigate to V2 contributor console from github
2. Observed that footer is not displayed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/7a00fdad-1e05-47d9-832a-3c8e005db087)

**Comment by dealako** [comment]
@pranab-bajpai indicated that we do need a footer.
@amolsontakke3576: Use the same footer as V1

**Comment by nirupamav** [comment]
Verified that the issue is fixed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/79e59ecc-da7a-434c-9803-e77fb1622fa3)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/88236bba-9ea4-4ba0-8587-c63e0739410f)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/fbf1d4f8-baef-4a3b-abd2-7274a7a6cb91)
