### ISSUE TITLE
V1 - Rebranding - Gerrit/Github - Project Login, CLA Manager Login and Developer options are not displayed in header

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#2095]
1. Launch to Contributor Console from gerrit
2. Observed that Project Login, CLA Manager Login and Developer options are not displayed in header
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/ebd72771-9493-4da2-b95b-face3aef7305)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/4e7c0f04-dc32-4e4c-bb66-c1ae9af76202)

**Comment by dealako** [comment]
We are ok with the existing links - links at the top right are only presented with the landing page. Once on the Project Console, the user can click the LFX EasyCLA button on the left to navigate back to the landing page (once that is working):

![Screen Shot 2020-10-30 at 9.08.26 AM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/c6f073e7-5fd5-436e-8c17-71c3a35ea0ba)
![Screen Shot 2020-10-30 at 9.08.43 AM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/f255194c-ea13-4a19-ab4e-642e96b1e182)
![Screen Shot 2020-10-30 at 9.09.13 AM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/59f9adb5-de50-48e5-93b1-580023d0ec1a)
