### ISSUE TITLE
V1 - Rebranding - Gerrit - Footer is not displayed in Individual and Corporate option pages

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#2098]
**Issue1**
1. Navigate to Corporate Contributor Console from gerrit
2. Login
3. Observed that footer is not displayed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c18930f3-1d5e-41af-b501-a4cb7d1edd06)

**Issue2**
1. Navigate to Individual Contributor Console from gerrit
2. Login
3. Observed that footer is not displayed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/0ed3314b-65fd-4405-83a3-2e8542485a69)

**Comment by dealako** [comment]
@amolsontakke3576 - can we review and close this one?

**Comment by nirupamav** [comment]
Verified that the issue is fixed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/2437350b-5f3d-448f-8fcc-4be5e740fc32)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/9c5c3d4d-6006-4f19-88df-ee1f45381ec2)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/6e7145a3-f137-43bc-9629-c0effde00228)
