### ISSUE TITLE
V2 - Rebranding - User is redirected to V1 documentation when clicked on GetHelp > Docs

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#2099]
1. Navigate to V2 contributor console from github/gerrit
2. Click on GetHelp > Docs
3. Observed that user is redirected to V1 documentation link instead of V2 documentation link
**V2 Documentation** link https://docs.linuxfoundation.org/docs/v/v2/communitybridge/easycla
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/6bd02271-73c3-46b5-b121-24d68c2b9f00)

**Comment by nirupamav** [comment]
Still user is redirected to V1 docs link
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/0376e180-488c-46c6-b2c2-0ae3d68c5510)

**Comment by tejasadg** [comment]
Verified that the user is now redirected to docs v2 link, Hence moving this to QA done.
cc: @vinod-kadam
