### ISSUE TITLE
"Add All" repos to GitHub Config

### ISSUE THREAD

**Issue by jpalmerLinuxFoundation** [communitybridge/easycla#210]
**Summary**

More than one project will have 100+ repos they want to configure for EasyCLA checks. Currently, the project console requires users to add repos one-by-one which is not the best user experience. We need to add a button that will allow the user to add all of the listed repos in a single click.

**Scenarios**
**Scenario: Some or All Repos are not added to EasyCLA check**
1. Navigate to project.*.lfcla.com
1. Click on a project name
2. Create a CLA group (if not already created)
3. Click the corresponding "GitHub Repository Configuration" button in the CLA group
4. [CHANGE] A link to "ADD ALL REPOS" appears next to the Organization name (see screenshots)

**Scenario: _All listed_ Repos are added to EasyCLA check**
1. Navigate to project.*.lfcla.com
1. Click on a project name
2. Create a CLA group (if not already created)
3. Click the corresponding "GitHub Repository Configuration" button in the CLA group
4. [CHANGE] A link to "REMOVE ALL REPOS" appears next to the Organization name (see screenshots)

**NOTE**: This will only add repos of this Organization, not all organizations. There should be a link to add "All" repos next to the name of each organization

**User Story**

As a project manager of a CLA group
I need to be able to add many repos to the EasyCLA check at once
so that I can onboard a project in a reasonable amount of time.

**Acceptance Criteria**

The "done" criteria when this feature or problem is resolved.  Such as:
1. Unit Tests added and running in CI
2. Functional Tests updated to cover feature, if applicable
2. Demonstrate the set of capabilities to the product team while the code is
   running in the STAGING environment.

**References**
![image](https://user-images.githubusercontent.com/51214959/65172154-1f3f0100-da12-11e9-81b6-5a6c3c3803d4.png)
![image](https://user-images.githubusercontent.com/51214959/65172160-22d28800-da12-11e9-8d39-095fc7e09ff7.png)

**Comment by jpalmerLinuxFoundation** [comment]
Anticipated questions:
1. Can you "Remove" repos that were added by the "Add All" feature? **Yes**
2. Can you do a bulk "Remove" of all repos? **Yes**
3. When do I see the option to "Remove" all repos? **When ALL repos are being checked** To quickly arrive at this scenario, click the "Add All Repos" button, then when the link will be updated to "Remove All Repos"

**Comment by jpalmerLinuxFoundation** [comment]
- Add a spinner if the process takes more than half a second
- **Disable screen actions while the process runs.**

**Comment by dealako** [comment]
Added:
- Add All Repos
- Remove All Repos
- Disabled buttons/links when loading/working
