### ISSUE TITLE
V1 - REMOVE button is shown for disabled repos in Configure Github Repistories popup

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#2100]
1. Launch V1 project console
2. Login
3. Add github organization and configure the github organization
4. Add repos for a CLA Group
5. Remove repos for CLA Group
6. Observed that still REMOVE button is shown in Configure Github Repistories popup when repo is removed
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/0eb97817-4ce0-4128-82aa-3c1fd27f0428)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/030d96f1-8f30-4517-88f8-15c818ea59a0)

**Comment by dealako** [comment]
Please review this issue. Coordinate with @nirupamav

**Comment by dealako** [comment]
The old v1 console is deprecated and removed.
