### ISSUE TITLE
BUG[Stage]: Request Individual Signature API throws 502 Internal Server Error

### ISSUE THREAD

**Issue by ashav-test** [communitybridge/easycla#2104]
Steps:

1. Have a Github repo with EasyCLA enabled.
2. Login with a github user and create PR.
3. The PR is gated, click on the cross mark and click on 'Proceed as an Individual Contributor' button
4. Open the Developer Tool and check the Network tab

Actual Result: The request individual signature API throws 502 error

Expected Result: Error should not be thrown and user should be able to proceed to sign the ICLA.

**Comment by dealako** [comment]
related to #2035

**Comment by dealako** [comment]
Should be resoled now.

**Comment by ashav-github** [comment]
@dealako @wanyaland Verified on Stage and its working fine now. Thanks!

[Screenshot from 2020-11-03 13-08-01.png](https://images.zenhubusercontent.com/5f6b335ce9044e3973ea11f9/4d27d3a7-91c5-4407-a2ea-c940814c7ae1)
