### ISSUE TITLE
Request to add feature to perform an EasyCLA check via a pull request comment

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2110]
## Summary

There should be an option for a project maintainer, contributor, or administrator to run an EasyCLA check on an open pull request without a repository maintainer or the contributor having to close it and reopen it.

## Background
Sometimes, a contributor, administrator, or project maintainer would like for the EasyCLA to recheck for their authorization. Right now, only the original pull request author or a repo admin can close and reopen the pull request to restart an EasyCLA check. 

## Some examples of how this could be used:

- If the bot encountered an issue in checking or reporting its status the first time it was run and the issue was later resolved. (example: EasyCLA status = 'expected')
- If an EasyCLA admin wishes to run a check to troubleshoot in real time.
- If a contributor wishes to troubleshoot on their own before contacting support or escalating.

The LF CLA legacy bot already implements this via a check for the comments "/check-cla" and "i signed it" in the pull request. This allows better self service and less support tickets generated.

**Comment by WillsonHG** [comment]
Another reason to have this - when a user has 2 PRs open at once that are gated by EasyCLA, the callback only sends the signing event to one and not the other. The user has to close and reopen the other PR to rerun the check.

**Comment by dealako** [comment]
Currently, we process callback notification from GitHub on PR Open, Close, Reopen (possibly others). We possibly ignore comment updates from GitHub.

This task is to:
- [ ] Define a set of commands which will allow us to re-process a GitHub check
- [ ] Register an event handler for comments for a given PR
- [ ] Determine if EasyCLA is configured for the repo - load project/CLA Group details.
- [ ] Review the GitHub comment for known commands
- [ ] If matching command, re-process the GitHub check

**Comment by dealako** [comment]
Heather has commented:
> The v0 bot allows anyone to comment and recheck, I think ours should be the same way @David Deal
