### ISSUE TITLE
[Regression] - V2 - Project Console - 403 is returned when CLA Group does not exist for child projects

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#2113]
Fetch CLA group for child projects which is not enrolled in any CLA Group. Observed 403 is returned instead of 200 with empty list and API error is displayed in project console UI

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/f197b589-60c8-4afd-904e-cf474fe4a5af)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/50e666d9-5787-4611-a83b-924a691386de)

**Comment by dealako** [comment]
Should return 200 with empty list.

**Comment by nirupamav** [comment]
Issue is still reproducible
I have access to parent project Bug2374ProjectLevelParent (a096s00000037ZIAAY) but when I am trying to fetch cla groups for child project Bug2374ProjectLevelChild3 (a096s00000037aGAAQ) getting 403
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/64497448-be71-4a6b-9ec6-6a8b96fa9fa5)

**Comment by nirupamav** [comment]
Verified that the issue is resolved
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/10675898-9b56-4157-9c8a-a506a80bda94)
