### ISSUE TITLE
LFX Footer - Bottom Alignment Issue

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#2116]
## Summary

LFX Footer - Bottom Alignment

## Background

There is a white horizontal line at the bottom of the page - remove it.

## Expected behavior

No extra white line at the bottom of the page.

## Screenshots

![Screen Shot 2020-11-03 at 11.33.23 AM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/06b5b1aa-8c48-4c41-a12a-4f15a54145c1)

## Environment

Please complete the following information:

* Environment:
  - [X] DEV
  - [ ] STAGING
  - [ ] PROD 
* Browser:
  - [X] Chrome/Brave
  - [ ] Firefox
  - [ ] Edge
  - [ ] Lynx
* Version: v1.0.XX

## Additional Context

N/A

## References

N/A

**Comment by nirupamav** [comment]
Verified in windows 10 chrome and firefox
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/34ebc28b-0d93-48b3-a5e7-9c7b3a7a9bc7)
