### ISSUE TITLE
V1 - Rebranding - SignIn button is displayed for logged in user when user navigates back to landing page

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#2123]
1. Launch V1 cla landing page (I tried in normal firefox browser and not in incognito mode)
2. Click on Project Login in header/CLA Manager Login/Proceed in Project Console card/Proceed in Corporate Console card
3. Login
4. Click on EasyCLA menu option in LFX header
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/ffa30387-374c-485d-a13f-a23643179114)
5. Observed that SignIn button is displayed when user is navigated back to landing page
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/06919df1-2274-423b-bad1-ed201a48bb81)

**Comment by vinod-kadam** [comment]
Pranab verified it on v1 - the issue is not reproducible. @manishv09  please verify it.

**Comment by manishv09** [comment]
Verified on V1 and found working fine. Please find the screencast attached for reference:
![image](https://user-images.githubusercontent.com/74345613/100883879-d79d7b80-34d6-11eb-9d58-eb5556773b17.png)
![image](https://user-images.githubusercontent.com/74345613/100883921-e4ba6a80-34d6-11eb-92ca-988294a79beb.png)
When back button clicked:
![image](https://user-images.githubusercontent.com/74345613/100884038-0582c000-34d7-11eb-88f5-03e449a0c045.png)
