### ISSUE TITLE
V1 - Description should not be mandatory to create/edit CLA Group

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#2124]
1. Launch V1 Project Console
2. Login
3. Click on Foundation/Project
4. Click ADD CLA GROUP
5. Enter Name and select CLA Type. Do not enter description
6. Observed that Save button is disabled. Not able to create CLA Group until CLA Group is entered. Description should not be mandatory
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c20f9b57-9853-477e-be8e-234105aee5fb)
6. Also while editing CLA Group, description field is mandatory. Description should not be mandatory
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/f3ebe3a2-826c-4b96-8bd6-d47db2121254)

**Comment by dealako** [comment]
@amolsontakke3576 re-assigned to you. Can you add an input filter/validation to ensure the description is set? @pranab-bajpai  decided that this is required.

**Comment by dealako** [comment]
The old v1 console is deprecated and removed.
