### ISSUE TITLE
[Regression] - V1 - Add button is shown for repo when repo is added

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#2125]
**Tried with new CLA Group and new github org and repos**
1. Launch V1 project console
2. Login
3. Add and configure github organization
4. Create New CLA Group and generate templates
5. Add all repos for the CLA Group
6. Remove a repo from the CLA Group. Add the repo again for the CLA Group. Repo is added and still Add button is displayed for the repo
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/d63c4e72-225a-47cf-93af-40d73a62e6b1)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/ac078d36-ea6d-4634-b379-7de8717eeb97)

**Comment by WillsonHG** [comment]
this is related to #1898

**Comment by amolsontakke3576** [comment]
@wanyaland Have you run the script to change the flag for existing repo's?

**Comment by wanyaland** [comment]
@amolsontakke3576 . This can be taken to QA stage as this was fixed in #1898

**Comment by WillsonHG** [comment]
this issue was resolved in #1898
