### ISSUE TITLE
[Regression] V2 - Project Console - CLA Service is not enabled for the project when new CLA Group is created

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#2126]
1) Create CLA Group for a project (Tried with foundation level, Project Level with single project and Project Level with multiple projects)
2) Observed that CLA Group is created, but CLA service is not enabled
**_NOTE: When we enroll project to CLA Group, CLA Service is enabled in project service. And when we un enroll project from CLA Group, CLA Service is disabled in project service. Issue observed only when new CLA Group is created_**
**{{baseurl}}/cla-service/v4/foundation/a096s0000003fGJAAY/cla-groups**
**CLA Group is created for the project**
```
{
    "list": [
        {
            "ccla_enabled": true,
            "ccla_pdf_url": "https://cla-signature-files-dev.s3.amazonaws.com/contract-group/4c230a7c-e73b-4d49-9f4b-0f03df962095/template/ccla-2020-11-04T09-03-37Z.pdf",
            "ccla_requires_icla": false,
            "cla_group_description": "",
            "cla_group_id": "4c230a7c-e73b-4d49-9f4b-0f03df962095",
            "cla_group_name": "nbkdfnbkldf",
            "foundationLevelCLA": false,
            "foundation_name": "04NovTestPrjParent",
            "foundation_sfid": "a096s0000003fGEAAY",
            "icla_enabled": false,
            "icla_pdf_url": "",
            "project_list": [
                {
                    "project_name": "04NovTestPrjchild1",
                    "project_sfid": "a096s0000003fGJAAY",
                    "repositories_count": 0
                }
            ],
            "repositories_count": 0,
            "root_project_repositories_count": 0,
            "total_signatures": 0
        }
    ]
}
```
**https://api-gw.dev.platform.linuxfoundation.org/project-service/v1/projects/a096s0000003fGJAAY**
**CLA service is not enabled for the project**
```
{
    "AutoJoinEnabled": false,
    "DoNotInvoice": false,
    "LFMembershipRequired": false,
    "MembershipAutorenew": "Yes",
    "Name": "04NovTestPrjchild1",
    "Parent": "a096s0000003fGEAAY",
    "StartDate": "2020-11-04",
    "Status": "Formation - On Hold",
    "CreatedDate": "2020-11-04T09:00:12.000Z",
    "EndDate": null,
    "EntityType": "Subproject",
    "Foundation": {
        "ID": "a096s0000003fGEAAY",
        "Name": "04NovTestPrjParent"
    },
    "HerokuConnectID": "4a173817-2c02-4b97-8017-54a940cd0606",
    "ID": "a096s0000003fGJAAY",
    "LFSponsored": false,
    "ModifiedDate": "2020-11-04T09:00:12.000Z",
    "Owner": {
        "Email": "npatel@linuxfoundation.org.invalid",
        "FirstName": "Platform",
        "ID": "0052M0000093AMhQAM",
        "LastName": "Service"
    },
    "ProjectType": "Project",
    "Slug": "04novtestprjchild1",
    "SystemModStamp": "2020-11-04T09:00:12.000Z",
    "Type": "Membership",
    "ParentHierarchy": {
        "ID": "a096s0000003fGEAAY",
        "Name": "04NovTestPrjParent",
        "Slug": "04novtestprjparent"
    }
}
```

**Comment by rinkeshbhutwala** [comment]
@dealako I checked in **cla-stage-projects-cla-groups** table data is stored in it but looks like the triggers are not working as expected I also checked the logs I didn't get any logs for new cla-groups.
Can you please help me with this?

**Comment by dealako** [comment]
Created PR: https://github.com/communitybridge/easycla/pull/2136

**Comment by dealako** [comment]
@nirupamav I need time to test this more once merged.

**Comment by nirupamav** [comment]
**Project Level CLA Group with single project**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/b428b30a-dbb3-40cb-b369-5541e6f61c25)

**Project Level CLA Group with multiple project**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a111ee42-36a1-4046-af2b-b78be1cc69f8)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/2db248d4-c234-474a-bed8-04a392af3b80)

**Foundation Level CLA Group**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/f389c2ee-28ad-4c26-bb80-ecb6afe7fc5e)

**Standalone project**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/110c754f-efe4-4357-b904-ecf93a10f29e)
