### ISSUE TITLE
[Regression] - V2 - Corporate Console - Events are not fetched for company and project

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#2128]
1. Create CLA Group for a project with CCLA CLA type
2. Sign CLA for the project from Corporate Console
3. Perform few actions like adding/deleting CLA Manager, adding Approval criteria etc.,
4. Trigger endpoint to fetch the events. 200 with empty list is triggered. The issue is observed only for newly signed CLAs. For old data we are able to fetch the events. 
Also we are able to fetch events for only project with project console endpoints
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/getCompanyProjectEvents
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/8a4a4f95-7177-45c6-8bd5-8d9d23da5360)

**Events for old data**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/4d3a626d-c6e9-4f1d-a3a7-7ebe47648044)

**Comment by wanyaland** [comment]
@nirupamav Tested by signing new CLA for project - a096s0000003fSAAAY and company - 0012M00002OugBpQAJ
And on the events request response was
```
{
    "Events": [
        {
            "EventCompanyID": "1df614a0-7153-4802-8a08-d7d8fec951f2",
            "EventCompanyName": "proxima",
            "EventCompanySFID": "0012M00002OugBpQAJ",
            "EventData": "user [wanyaland / Harold Wanyama / wanyaland@gmail.com] was added as CLA Manager for Company: proxima, Project: Event test foundation",
            "EventFoundationSFID": "a096s0000003fSAAAY",
            "EventID": "3b0077e7-b79d-43cd-ab12-9ab1fb6334d0",
            "EventProjectExternalID": "a096s0000003fSAAAY",
            "EventProjectID": "8e6de07d-0a0d-40a3-a550-462a6e38da53",
            "EventProjectName": "Event test foundation",
            "EventProjectSFID": "a096s0000003fSAAAY",
            "EventProjectSFName": "Event test Found",
            "EventSummary": "user Harold Wanyama was added as CLA Manager for Company: proxima, Project: Event test foundation",
            "EventTime": "2020-11-06T12:51:25Z",
            "EventTimeEpoch": 1604667085,
            "EventType": "cla_manager.added",
            "LfUsername": "wanyaland",
            "UserID": "77422b75-cffe-11ea-854b-5e8def64b42f",
            "UserName": "Harold Wanyama"
        },
        {
            "EventCompanyID": "1df614a0-7153-4802-8a08-d7d8fec951f2",
            "EventCompanyName": "proxima",
            "EventCompanySFID": "0012M00002OugBpQAJ",
            "EventData": "corporate signature signed for project Event test foundation and company proxima by user Amol Santakke, params: project_id=8e6de07d-0a0d-40a3-a550-462a6e38da53, company_id=1df614a0-7153-4802-8a08-d7d8fec951f2",
            "EventFoundationSFID": "a096s0000003fSAAAY",
            "EventID": "f7d6b52d-8a4b-43d0-8d35-588149eae751",
            "EventProjectExternalID": "a096s0000003fSAAAY",
            "EventProjectID": "8e6de07d-0a0d-40a3-a550-462a6e38da53",
            "EventProjectName": "Event test foundation",
            "EventProjectSFID": "a096s0000003fSAAAY",
            "EventProjectSFName": "Event test Found",
            "EventSummary": "corporate signature signed for project Event test foundation and company proxima by user Amol Santakke",
            "EventTime": "2020-11-06T12:50:01.771658+0000",
            "EventTimeEpoch": 1604667001,
            "EventType": "CompanySignatureSigned",
            "UserID": "c209eb98-6379-11ea-9c3e-4e72898c626d",
            "UserName": "Amol Santakke"
        }
    ]
} ```

**Comment by thakurveerendras** [comment]
Issue is reproducible with below Test Data

- Tested by Adding/delete Approval Criteria at corporate console

Test Data :
```
Company name :proxima-z ,companySFID:0012M00002OugBpQAJ
Project name: Academy Software Foundation , ProjectSFID :a09410000182dD2AAI

GET API End point

https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company/0012M00002OugBpQAJ/project/a096s0000003kQeAAI/events

https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company/0012M00002OugBpQAJ/project/a09410000182dD2AAI/events

Refer Postman Screenshot : [https://prnt.sc/vyvhtn](https://prnt.sc/vyvhtn)
Corporate Console Screenshot : [https://prnt.sc/vyviuk](https://prnt.sc/vyviuk) , [https://prnt.sc/vyvr99](https://prnt.sc/vyvr99)
```

**Comment by wanyaland** [comment]
@thakurveerendras When I tried the flow with projectLevel CCLA case I was able to get events for the project and Company scope for both initial CLA Manager and approval criteria getting addded 
```
"Events": [
        {
            "EventCompanyID": "482f44b4-2354-4b14-8103-f697594d2066",
            "EventCompanyName": "waso new",
            "EventCompanySFID": "0016s000009DXxDAAW",
            "EventData": "CLA Manager: wasonew, Email: wanyaland+waso+new@gmail.com, LFID: 59b8e034-df39-430c-86d9-f45a5a30fe9f added Domain: andela.com to the approval list for Company: waso new, Project: cla-grp-test-harold.",
            "EventFoundationSFID": "a096s0000003mlUAAQ",
            "EventID": "726b0dc4-9872-4a56-ab69-a8618cd70c48",
            "EventProjectExternalID": "a096s0000003mlUAAQ",
            "EventProjectID": "98f918a9-14db-4dbc-8b39-ecace7ec57ef",
            "EventProjectName": "cla-grp-test-harold",
            "EventProjectSFID": "a096s0000003mlZAAQ",
            "EventProjectSFName": "Harold_Test_Foundation_Proj1",
            "EventSummary": "CLA Manager: wasonew added Domain: andela.com to the approval list for Company: waso new, Project: cla-grp-test-harold.",
            "EventTime": "2020-12-23T15:21:54Z",
            "EventTimeEpoch": 1608736914,
            "EventType": "cla_manager.approval_list_updated",
            "LfUsername": "wasonew",
            "UserID": "59b8e034-df39-430c-86d9-f45a5a30fe9f",
            "UserName": "Harold Wanyama"
        },
        {
            "EventCompanyID": "482f44b4-2354-4b14-8103-f697594d2066",
            "EventCompanyName": "waso new",
            "EventCompanySFID": "0016s000009DXxDAAW",
            "EventData": "corporate signature signed for project cla-grp-test-harold and company waso new by user Harold Wanyama, params: project_id=98f918a9-14db-4dbc-8b39-ecace7ec57ef, company_id=482f44b4-2354-4b14-8103-f697594d2066",
            "EventFoundationSFID": "a096s0000003mlUAAQ",
            "EventID": "d1c699f9-4886-4838-9cd4-4c5c6a5c0867",
            "EventProjectExternalID": "a096s0000003mlUAAQ",
            "EventProjectID": "98f918a9-14db-4dbc-8b39-ecace7ec57ef",
            "EventProjectName": "cla-grp-test-harold",
            "EventProjectSFID": "a096s0000003mlZAAQ",
            "EventProjectSFName": "Harold_Test_Foundation_Proj1",
            "EventSummary": "corporate signature signed for project cla-grp-test-harold and company waso new by user Harold Wanyama",
            "EventTime": "2020-12-23T14:24:52.324045+0000",
            "EventTimeEpoch": 1608733492,
            "EventType": "CompanySignatureSigned",
            "UserID": "59b8e034-df39-430c-86d9-f45a5a30fe9f",
            "UserName": "Harold Wanyama"
        }
    ]
} ```

**Comment by thakurveerendras** [comment]
Issue is fixed as expected & now Corporate Console - Events are properly fetched for company and project as expected, So making issue status to QA-Done

Issue Tested on dev environment 

**API endpoint** : https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company/{companySFID}/project/{projectSFID}/events


companySFID : 0012M00002MnADGQA3
foundation projectSFID : a096s0000003knrAAA
projectSFID : a096s0000003knwAAA

**API Status** : 200 OK
**API Response** body :
`{
    "Events": [
        {
            "EventCompanyID": "7c737082-4d47-4532-8bab-f97d76618c9d",
            "EventCompanyName": "Proxima",
            "EventCompanySFID": "0012M00002MnADGQA3",
            "EventData": "CLA Manager: veerendrat, Email: veerendrat@proximabiz.com, LFID: e1e147d8-35ec-11eb-a06a-a2eb8c0f56ab removed Domain test.com from the approval list for Company: Proxima, Project: VeerClaTest.",
            "EventFoundationSFID": "a096s0000003knrAAA",
            "EventID": "eaa3cf39-23d2-4027-822e-7119aeb956c1",
            "EventProjectExternalID": "a096s0000003knrAAA",
            "EventProjectID": "5db52023-cc06-4201-aed8-0326f5bc48cc",
            "EventProjectName": "VeerClaTest",
            "EventProjectSFID": "a096s0000003knwAAA",
            "EventProjectSFName": "Veer Foundation-Test-001",
            "EventSummary": "CLA Manager: veerendrat removed Domain: test.com from the approval list for Company: Proxima, Project: VeerClaTest.",
            "EventTime": "2020-12-24T05:35:41Z",
            "EventTimeEpoch": 1608788141,
            "EventType": "cla_manager.approval_list_updated",
            "LfUsername": "veerendrat",
            "UserID": "e1e147d8-35ec-11eb-a06a-a2eb8c0f56ab",
            "UserName": "Veerendra Thakur"
        },
        {
            "EventCompanyID": "7c737082-4d47-4532-8bab-f97d76618c9d",
            "EventCompanyName": "Proxima",
            "EventCompanySFID": "0012M00002MnADGQA3",
            "EventData": "CLA Manager: veerendrat, Email: veerendrat@proximabiz.com, LFID: e1e147d8-35ec-11eb-a06a-a2eb8c0f56ab added Domain: test.com to the approval list for Company: Proxima, Project: VeerClaTest.",
            "EventFoundationSFID": "a096s0000003knrAAA",
            "EventID": "9f053a3c-a810-448d-822a-705e2f3b4c2e",
            "EventProjectExternalID": "a096s0000003knrAAA",
            "EventProjectID": "5db52023-cc06-4201-aed8-0326f5bc48cc",
            "EventProjectName": "VeerClaTest",
            "EventProjectSFID": "a096s0000003knwAAA",
            "EventProjectSFName": "Veer Foundation-Test-001",
            "EventSummary": "CLA Manager: veerendrat added Domain: test.com to the approval list for Company: Proxima, Project: VeerClaTest.",
            "EventTime": "2020-12-23T15:57:16Z",
            "EventTimeEpoch": 1608739036,
            "EventType": "cla_manager.approval_list_updated",
            "LfUsername": "veerendrat",
            "UserID": "e1e147d8-35ec-11eb-a06a-a2eb8c0f56ab",
            "UserName": "Veerendra Thakur"
        },
        {
            "EventCompanyID": "7c737082-4d47-4532-8bab-f97d76618c9d",
            "EventCompanyName": "Proxima",
            "EventCompanySFID": "0012M00002MnADGQA3",
            "EventData": "corporate signature signed for project VeerClaTest and company Proxima by user Veerendra Thakur, params: project_id=5db52023-cc06-4201-aed8-0326f5bc48cc, company_id=7c737082-4d47-4532-8bab-f97d76618c9d",
            "EventFoundationSFID": "a096s0000003knrAAA",
            "EventID": "262cbfb4-937d-47cc-9f9c-675d09c266f7",
            "EventProjectExternalID": "a096s0000003knrAAA",
            "EventProjectID": "5db52023-cc06-4201-aed8-0326f5bc48cc",
            "EventProjectName": "VeerClaTest",
            "EventProjectSFID": "a096s0000003knwAAA",
            "EventProjectSFName": "Veer Foundation-Test-001",
            "EventSummary": "corporate signature signed for project VeerClaTest and company Proxima by user Veerendra Thakur",
            "EventTime": "2020-12-23T15:55:22.398687+0000",
            "EventTimeEpoch": 1608738922,
            "EventType": "CompanySignatureSigned",
            "UserID": "e1e147d8-35ec-11eb-a06a-a2eb8c0f56ab",
            "UserName": "Veerendra Thakur"
        }
    ]
}`

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/d99f5241-734c-4bfd-ab9c-3ce50196e473)
