### ISSUE TITLE
[Regression] - V1 - Contributor Console - Send button overlaps on X(close) icon

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#2131]
**Prerequisite**
1. Create CLA Group with CCLA enabled
2. Connfigure githuborg and add repo to the CLA Group
3. In corporate console sign cla for the CLA Group

**Steps to follow**
1. Login to github repo as contributor
2. Edit file and create PR
3. User is gated by CLA
4. Click on CLA NOT SIGNED
5. Click Corporate
6. Select the company that as signed CLA for the CLA Group
7. Observed that in the popup SEND button overlaps on X(close) icon. This issue was fixed in #764 and Cancel and Send buttons were move to bottom of the popup. Now buttons are displayed on top of the popup and overlap issue is observed
Observed same issue when creating new company
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/b6d468fa-cdcb-41a0-889a-fa9045d44867)

![image](https://user-images.githubusercontent.com/60865903/98130127-ee54b080-1edf-11eb-9113-d87318f815d9.png)

**Comment by dealako** [comment]
Merged PR from @amolsontakke3576: https://github.com/communitybridge/easycla/pull/2135 to address this issue.

**Comment by dealako** [comment]
@nirupamav ready to review/confirm

**Comment by nirupamav** [comment]
**_Verified that the issue is resolved_**
**Existing Company**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/1c0dd97a-4c62-44fc-b775-cec745c41b6c)

**New Company Request**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/01f876a3-2357-45b7-9be0-6126e71120ee)
