### ISSUE TITLE
[Regression] - V2 - Contributor Console - Not able to create company

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#2138]
**Prerequisite**
1. Create CLA Group for a project with CCLA enabled
2. Configure github organization and add repositories

**Steps To Follow**
1. Login to github as contributor
2. Edit file and create PR
3. User is gated by CLA
4. Click on CLA NOT SIGNED
5. Click Proceed as a Corporate Contributor
6. Click building icon
7. Click Organization not listed? + Click Here
8. Enter valid company name and website
9. Click Next
10. Request failed message is displayed. However I am able to create org with same details from org service endpoint
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/9e161634-4107-4db2-8920-eb5a64e4e65f)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/946013ba-885d-4701-b2e8-afc34f947b70)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/304eb10b-76e5-47cb-ad91-ee9a22827943)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/568b5292-03cf-4232-bb79-ba9d4f0fa941)

**Comment by manishv09** [comment]
Company is created though error message is thrown for the user, Please attached document for more details:

![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/ec3a2e79-0fe6-4a5a-967a-9a2a82f65cc1)
[https://app.zenhub.com/files/194341141/c415c03d-5a07-4f28-9c32-12dae322ec44/download](https://app.zenhub.com/files/194341141/c415c03d-5a07-4f28-9c32-12dae322ec44/download)

**Comment by wanyaland** [comment]
@manishv09 . The example claGroup here has no association with the salesforce project. It happens to be data integrity issue

**Comment by vinod-kadam** [comment]
As discussed in the standup, @wanyaland please add more details as how to probably the data integrity issue cropped in.
@manishv09  please test it with other data.

**Comment by wanyaland** [comment]
In this flow user is gated during PR creation. It so happens that claGroup is identified at this stage. In case a salesforce project is unenrolled the claGroup will happen to not have any associations hence causing this issue. In effect for testing one should ensure that claGroup being used has sf Project mapping relationship. So the solution would be to use existing CLA groups that have association or create one for testing purposes via admin console.
 @vinod-kadam @manishv09
