### ISSUE TITLE
V2 - Contributor Console - User is redirected to different url in Corporate console for standalone project(with/without parent as The Linux Foundation)

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#2142]
**Prerequisite**
1. Create CLA Group for standalone project with CCLA enabled
2. Configure github org for CLA Group and add repos

**Steps to follow**
1. Login to github as contributor
2. Edit a file in the repo and create PR
3. User is gated by CLA
4. Click CLA NOT SIGNED
5. Click Proceed as Corporate Contributor
6. Search and select company that has not signed CLA
7. Click Proceed
8. Click Yes
9. Click Proceed
10. Login
11. Click Proceed
12. User is navigated to Corporate Console. However redirection url is wrong and hence page keeps loading
**Current redirection url** https://lfx.dev.platform.linuxfoundation.org/foundation/a096s0000003fwFAAQ/cla
**Expected redirection url** https://lfx.dev.platform.linuxfoundation.org/foundation/LF%20Supported/project/a096s0000003fwFAAQ/cla
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/bf8e2426-872d-4a2c-948c-190cb4f0b459)

**Comment by wanyaland** [comment]
Following discussion with @amolsontakke3576 This case is thrown for standalone projects(no parent and no child projects). This needs refactoring on the api end to cater for this use case

**Comment by vinod-kadam** [comment]
@pranab-bajpai  to check whether the a standalone project will always have a parent & if yes then will the parent also need to be returned by the project service.

**Comment by manishv09** [comment]
Verified today and found working fine now user is redirected to Corporate console:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/636e49c1-f337-4296-a84c-75599341ee69)

The url as it appeared to be for the above screencast: 
https://lfx.dev.platform.linuxfoundation.org/foundation/a096s0000003k9pAAA/project/a096s0000003k9uAAA/cla
