### ISSUE TITLE
[Regression] - V2 - Project Console - When we delete Standalone CLA Group or Foundation Level CLA Group

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#2143]
1. Create CLA Group for Standalone project or Foundation Level CLA Group for project group
2. Delete the CLA Group
3. Observed that 404 error is returned while fetching CLA Groups
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/listClaGroupsUnderFoundation
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/52501866-839a-4f31-b0af-ed2bafc83109)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a008282c-78df-4ca4-bc96-c9d7447154d2)

**Comment by dealako** [comment]
Merged PR: https://github.com/communitybridge/easycla/pull/2147. Return 200 empty list now.

**Comment by nirupamav** [comment]
Testing blocked due to #2148

**Comment by manishv09** [comment]
CLAGroupDelete - 2143
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/a63047a6-b4ac-49b1-84d2-a02f385822ee)

No error is thrown to the user when CLA Group created for "HOME / TESTEASYCLA-BUGSTEST-001 / TOOLS / CLA / OVERVIEW"
Please refer the screencast attached.

**Comment by manishv09** [comment]
Discussed with @pranab-bajpai  and verified, hence closing the issue.
