### ISSUE TITLE
V2 - Project Console - Able to enroll foundation for a project level CLA Group

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#2150]
1. Create CLA Group at Project Level
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a02e6e87-8de2-489f-a4bb-67b8b07d7561)
2. Enroll foundation to existing CLA Group
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c570ef33-72b7-4153-b252-abab362c3d0a)
3. Observed that foundation is enrolled and project level CLA Group is converted to Foundation level CLA Group
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c1086261-f9f3-43e1-86c2-b85a695674b1)

**Comment by dealako** [comment]
To test/evaluate:

Create CLA Group A

Assign projects:

Foundation A -> not assigned to CLA Group A
---- Project A1 -> Assigned to CLA Group A
---- Project A2 -> Assigned to CLA Group A

User comes back to edit ‘CLA Group A’ project assignment: user should not be able to assign ‘Foundation A’ to the CLA Group. This can only happen initially (for now).  Need to update the validation logic for the enroll API endpoint to prevent users from selecting/adding the 'Foundation A' on when editing.

**Comment by thakurveerendras** [comment]
Now we are not able to enroll foundation for a project level CLA Group, So issue is fixed as expected 

**Test Data**:
foundation project_sfid : a096s0000003k9pAAA
Child project_sfid : a096s0000003kFRAAY
Child project_sfid : a096s0000003mDnAAI
Cla_group_id : f9dcf171-6e75-440b-bfad-6d22c12fb4ce

**Below Scenario covered** :
1.  Try to enroll foundation project to project level CLA Group
Results : As expected foundation project is not enroll in project level CLA group 
`Foundation project API Response : 400 Bad Request - Unable to enroll salesforce foundation project: a096s0000003k9pAAA in project level cla-group.
[https://prnt.sc/w267w3](https://prnt.sc/w267w3)`

2. Try to enroll existing project to project level CLA Group
`Enroll Existing project Response: 400 Bad Request - bad request: invalid project_sfid provided: [a096s0000003kFRAAY]. One or more of the provided projects are already enrolled in an existing cla_group
[https://prnt.sc/w26lsh](https://prnt.sc/w26lsh)`

3. Enroll fresh project to project level CLA Group
`Enroll new project  API Response: Getting 200 OK status & x-request-id in RESPONSE HEADERS
[https://prnt.sc/w26nyn](https://prnt.sc/w26nyn)`
