### ISSUE TITLE
V2 - Corporate Console - CLA Manager is not assigned with scope for projects that are enrolled to existing CLA Group

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#2151]
1. Create Project level CLA group  (for example, may only have 1+ project associated with the CLA Group)
2. Signatory signs the CLA for the project from the corporate console (CLA manager role is assigned, designee role is removed => works fine)
3. Admin Console -> Enroll other sibling projects to the same CLA group (a new record is added to the project CLA group table for each new project that is associated with the CLA Group)
4. Observed that CLA manager is not assigned with the scope for the enrolled project

**Comment by dealako** [comment]
@wanyaland 

- Let's confirm that permissions are set properly on create/initial
- Let's then review the logic that is triggered when new projects are added to an existing CLA Group that is already signed

**Comment by dealako** [comment]
Manish is mentioning that the PM does not have ListGerrits access as the PM for the sub-project. Need to verify...

**Comment by manishv09** [comment]
Please find attached the screencast in support to the comments mentioned above:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/e1d00f67-b7c1-43c1-8c0d-89152de2f714)

Also The IAM Permission user has:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/ff2fe163-dc8f-47d6-980a-2bb5a53a0f15)

**Comment by manishv09** [comment]
@dealako When I checked again for above mentioned scenario, If user add newly created project under PM's scope from IAM, he is able to view the added repositories of that CLA Group.
Please suggest if that works so that I mark it as QA Done.

**Comment by manishv09** [comment]
**Project Level CLA group Use Cases**
Multiple Child Projects
•	If a CLA group is created at the project level, then the CLA Manager role is assigned to all sub/child projects under that CLA group and not to parent/foundation. (At group creation). – It Works Fine
 ![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/aeed61e7-bf70-47e2-97e6-517518d6cc72)

**Multiple Child Projects & Un-enrolment**
•	If a CLA group is created at the project level, and after group creation, one project is unenrolled from the CLA group then the CLA Manager role **is removed** from that project. - It Works fine
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/78722e72-79a4-404a-95b8-8b93db0a7129)
 
**Multiple Child Projects & Enrolment**
•	If a CLA group is created at the project level and one project is enrolled in that CLA group, then that project is **not assigned** a CLA Manager. --> this is a problem; need to be fixed
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/b4110d9c-98db-4906-b678-7588d329610b)

**Comment by tejasadg** [comment]
## Foundation Level CLA
- If the CLA group is created at the foundation level with or without child projects enrolled. After completing the Signatory process with the corporate console "**CLA Manager**" role is assigned to 
**foundation only**.
- Enrollment or Unenrollment does not cause any changes to role assignment.
- After deleting the CLA group CLA manager role is removed from the foundation.

**Comment by dealako** [comment]
@tejasadg @manishv09 - do you have a test environment set up to run this scenario? @wanyaland and I added some additional logging to help test/validate this.  We need to execute this scenario again to cause the failure so we can review the logs to determine what happened.  Let's coordinate! Thanks!

**Comment by manishv09** [comment]
@dealako, @wanyaland  
Please find the fresh created today as follows:
Admin Portal
https://admin.staging.platform.linuxfoundation.org/apps/cla/project#id=a097c000007ny98AAA
Corporate Portal
https://lfx.staging.platform.linuxfoundation.org/foundation/a0941000002wBz9AAE/project/a097c00000[…]tyCompanyId=d6367896-27f0-4c06-9f9a-3420846e0ec9
8:36
Project name and hierarchy: 
HOME / THE LINUX FOUNDATION / FEB NEW FOUNDATION 2021 / TOOLS / CLA / OVERVIEW
User: manishv.comprmgr
Please let

**Comment by vinod-kadam** [comment]
This is deployed to DEV, Staging & PROD.

**Comment by vinod-kadam** [comment]
Multiple Child Projects & Enrolment
• If a CLA group is created at the project level and one project is enrolled in that CLA group, then that project is not assigned a CLA Manager.
--> In the past I had created a CLA group vinods9foundation_clagrp1 with projects vinods9foundation_child1 & vinods9foundation_child2. I had then signed CLA for company Proxima for this cla group - the user vinodkps1 (vinodk+proximasystems1@proximabiz.com) was added as CLA Manager on CCLA signing.
Today, I added project vinods9foundation_child7 in to the CLA group vinods9foundation_clagrp1 - I observed that  he user vinodkps1 (vinodk+proximasystems1@proximabiz.com)  was assigned the CLA Manger role for the project vinods9foundation_child7.
![image.png](https://images.zenhubusercontent.com/5e9e9952b186e1325cf5608a/efc8edc2-dfab-45ea-a080-0d4857403fff)
So, this scenario seems to be working fine,

**Comment by vinod-kadam** [comment]
## Foundation Level CLA Group
- CLA group is created at the foundation level (where foundation is certainly checked & child projects may be checked) - After completing the Signatory process with the corporate console "**CLA Manager**" role is assigned to **foundation only**.
--> This is the correct behavior since role given at foundation level percolates down to the child projects automatically; therefore enrollment or unenrollment of a child project from foundation level cla group will not cause any changes to the role assignment.

**Comment by vinod-kadam** [comment]
Based on the tests done above "Multiple Child Projects & Enrolment" and "Foundation Level CLA Group", the system seems to be working fine. So, marking this one as QA Done.
