### ISSUE TITLE
V2 - Corporate Console - Not able to add github username with hyphen in approval list

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#2154]
@sudhakar-proxima
**Prerequisite**
1. Create CLA Group with CCLA enabled
2. Sign CLA from corporate console

**Steps to follow**
1. Trigger below endpoint to add approval list with github username having special character
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/updateApprovalList
Below is the criteria provided by github for username
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/cc50c398-b31d-45cb-97a7-e6fd4e1fd102)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/16d5cbe9-082a-4b09-a83f-ec35c7ac825a)

![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/cfc2f572-19e6-42ec-951f-20781af61b76)

**Comment by manishv09** [comment]
Found Working fine hence marking as closed. Please refer screencast attached for more details.
