### ISSUE TITLE
V1 - Project Console - Page keeps loading forever when user does not have access to any projects

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#2156]
1. Launch V1 landing page
2. Login as user who does not have access to any projects
3. Click Proceed on project console card or click on Project Login
4. Project console keeps loading forever
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/4a4d6199-9ced-4c7a-820f-901e2fa63cb2)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/49401a62-3e7a-41cc-bbe8-e686433943a7)

**Comment by dealako** [comment]
The old v1 console is deprecated and removed.
