### ISSUE TITLE
V2 - Contributor Console - Error displayed while creating company

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#2157]
**Prerequisite**
1. Create CLA Group for a project with CCLA enabled
2. Configure github organization and add repositories

**Steps To Follow**
1. Login to github as contributor
2. Edit file and create PR
3. User is gated by CLA
4. Click on CLA NOT SIGNED
5. Click Proceed as a Corporate Contributor
6. Click building icon
7. Click Organization not listed? + Click Here
8. Enter valid company name and website
9. Click Next
10. Error is displayed. However company is created
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/0c63595c-0bbb-494c-915f-0afba2e99de4)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c95891ee-118a-405b-82a8-f8d40cdc2ac0)

**Comment by manishv09** [comment]
Retested and found working fine now. Contributor is moved to following popup to proceed with :
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/00fa1ea8-df41-4378-8918-b1f746fb2cd9)

Please refer attached screencast for more details, moving to QA Done.
[https://app.zenhub.com/files/194341141/c2f8d254-c64c-4e03-93a1-90300f1d01fa/download](https://app.zenhub.com/files/194341141/c2f8d254-c64c-4e03-93a1-90300f1d01fa/download)

**Comment by manishv09** [comment]
Discussed with @pranab-bajpai  and verified, hence closing the issue.
