### ISSUE TITLE
Wrong email sent to contributor when a cla manager approves OR denies the request from the corporate console.

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2162]
## Summary

The email for "you have been approved as a cla manager"  or "you have been denied" with instructions to log into the corporate console is being sent instead of the email to let the contributor know theyve been added or denied to the approved list and to try their PR again.

## Background

As a contributor, open a pull request and become gated by EasyCLA. Choose corporate CLA and choose your company from the list. SEe that you are not authorized and select to send a notification to your CLA manager. 

As cla manager, log into the corporate console and approve or deny the pending contributor request.

As the contributor, observe the email you receive is: 

![image](https://user-images.githubusercontent.com/46732999/98452623-1bdb6d00-211f-11eb-8d4a-a818c511f9c3.png)

or 

![image](https://user-images.githubusercontent.com/46732999/98454348-9ad9a100-2131-11eb-8693-779caf7e157b.png)

## Expected behavior

The email to alert the user that they have been added or denied to the approved list should be sent. Not the email alerting them they are approved or denied as a cla manager.

**Comment by WillsonHG** [comment]
@dealako  @wanyaland  This is still not correct for the approval email. 
![image](https://user-images.githubusercontent.com/46732999/98707601-347d9a00-234e-11eb-96c3-893177f110ad.png)

The email should not be telling them to log into the corporate console. This email is going to the contributor requesting to be added to the approved list, so the contributor will have no need to log into the corporate console. They only need to go back to their open PR and try to verify again. 

I checked the email docs https://docs.google.com/document/d/1jFlSq1tx66LbBwGbSfJm3QS4st68GblfzBEMZRya9gk/edit# and this email is also not correct in the list. It tells them to close and reopen their PR to pass the check, but this is not how it works.

**Comment by WillsonHG** [comment]
#2181

**Comment by WillsonHG** [comment]
The denial email is fixed, but the user is still getting told to go to the corporate console instead of user the contributor console to verify.

**Comment by dealako** [comment]
How about this:

> To get started, please navigate back to GitHub or Gerrit and start the authorization process.  Once you select the authorization link and you will be directed to the EasyCLA Contributor Console. GitHub users will need to authorize the tool to see your GitHub user name and email. Gerrit users will first need to log in. On the console landing page, select the corporate agreement option. To finish, search and select your company to acknowledge your association with your company.  This will complete the authorization process.  Follow the link back to GitHub or Gerrit to confirm that you
are now authorized.

**Comment by dealako** [comment]
Ready for review: https://github.com/communitybridge/easycla/pull/2353

**Comment by dealako** [comment]
Merged, deployed to DEV.

**Comment by vinod-kadam** [comment]
Fix is now available on Production env.

**Comment by WillsonHG** [comment]
Verified it is fixed on prod
