### ISSUE TITLE
Email sent to CLA manager uses 'Allow List' instead of 'Approved List'

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2163]
## Summary

When a user requests to be added to the Approved list for a company, the CLA manager receives an email. The email is using the wrong language for 'Approved List'

Please change the references to the "allow list" to the "Approved list".

![image](https://user-images.githubusercontent.com/46732999/98454398-176c7f80-2132-11eb-8ce7-5b1feb4a7434.png)

**Comment by dealako** [comment]
Merged PR: https://github.com/communitybridge/easycla/pull/2171#pullrequestreview-526453078

**Comment by WillsonHG** [comment]
This is not fixed in Production yet.

**Comment by vinod-kadam** [comment]
Fix is now available on Production env.

**Comment by WillsonHG** [comment]
![image](https://user-images.githubusercontent.com/46732999/103922661-0fa16b00-50e2-11eb-9374-90251a92ddb0.png)
This has not been fixed. @wanyaland can you please revew?
