### ISSUE TITLE
[Rebranding Update] Update the link in the comment in the "checks" section of a PR.

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2166]
## Summary

When EasyCLA checks a pull request for a CLA, it leaves an update in the "checks" section and there is a "details" link. This is linking to lfcla.com. This should be updated with a new LFX link.

![image](https://user-images.githubusercontent.com/46732999/98485573-6c1d0280-21e5-11eb-8a7f-7e8b9cd0d449.png)

**Comment by WillsonHG** [comment]
https://easycla.lfx.linuxfoundation.org/#/ is the link it should go to

**Comment by dealako** [comment]
Merged PR: https://github.com/communitybridge/easycla/pull/2167
Link previously goes to the lfcla.com landing page. Updated to go to the new easycla.lfx.linuxfoundation.org landing page.

**Comment by dealako** [comment]
Deployed to DEV

**Comment by WillsonHG** [comment]
confirmed fixed in prod
