### ISSUE TITLE
Review instructions sent in email to 'close and reopen' a pull request

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2181]
For example:

![image](https://user-images.githubusercontent.com/46732999/98713610-d3f25b00-2355-11eb-9c2f-b1557827238c.png)

The contributor only needs to verify with their company at this point. They just follow the bot comment again and select 'corporate' 'their company' and 'i verify'.  Closing and opening the pull request will accomplish nothing.

We need to rewrite this part in this email and also the email sent to contributors letting them know their request to be approved has been approved.

**Comment by dealako** [comment]
As a result of implementing the new check feature, we should update the instructions here.

**Comment by vinod-kadam** [comment]
I checked the email sent in case of v2 & it doesn't have the sentence pointed out in this ticket.
---------------
Hello Vinod Kadam,

This is a notification email from EasyCLA regarding the project vinods8standalone_clagrp1.

The EasyCLA approval list for Proxima for project vinods8standalone_clagrp1 was modified.

The modification was as follows:

Removed Domain: proximabiz.com
If you need help or have questions about EasyCLA, you can read the documentation or reach out to us for support.

EasyCLA Support Team
---------------
@WillsonHG , had you logged your ticket for v1 or v2?

**Comment by WillsonHG** [comment]
@vinod-kadam  This was an older ticket so we can close it out.
