### ISSUE TITLE
Spacing and formatting issues in email sent to the CLA Signatory.

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2183]
## Summary

When a CLA manager selects 'no' in the corporate console when signing a cla and designates a cla signatory, the cla signatory designee receives the following email:

![image](https://user-images.githubusercontent.com/46732999/98715021-95f63680-2357-11eb-90e1-e5099bd668c3.png)

**Comment by dealako** [comment]
@wanyaland can you inform us where this is being called?

**Comment by wanyaland** [comment]
@dealako This is being invoked in the signing process(docusign_mdoels.py) with the pydocusign.Signer object which in turn uses the Docusign template as shown below
![Screenshot 2020-11-17 at 18.31.53.png](https://images.zenhubusercontent.com/5ed66fcc690afccc216f0ecb/8431d747-9095-4abe-b282-678ab2ad7160)

**Comment by dealako** [comment]
Based on our discussion:

- We need to remove the HTML paragraph formatting.  This is not properly handled by the Docusign email template on their API
- We need to update the footer also - shouldn't have the HTML formatting
- We need to not introduce any line breaks for the paragraphs - this was previously implemented as a long string, such as:

```
            email_body = f'''Hello {signatory_name},

            This is a notification email from EasyCLA regarding the project {project_name}.

            {cla_manager_name} has designated you as being an authorized signatory for {company_name}. In order for employees of your company to contribute to the open source project {project_name}, they must do so under a Contributor License Agreement signed by someone with authority to sign on behalf of your company.
```

maybe use something like:

```
def append_email_help_sign_off_content_plain(body: str, project_version: str) -> str:
    return append_email_help_sign_off_content(body, project_version).replace("<p>", "").replace("</p>", "\n\n")
```

**Comment by WillsonHG** [comment]
@wanyaland  still not looking quite right on dev.
![image](https://user-images.githubusercontent.com/46732999/101101001-961fd580-3595-11eb-887e-c387ed654cc7.png)

**Comment by WillsonHG** [comment]
Verified this is fixed in produciton.
