### ISSUE TITLE
EasyCLA Bot Comments not updating when a contributor signs or verifies.

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2194]
## Summary

When a contributor verifies with a CCLA or signs an ICLA after being gated by the EasyCLA bot, the check passes at the bottom but the bot comment is not correctly updating to the passed status.

Current Example: 
https://github.com/grpc/grpc-java/pull/7613

Please review the logic where we look for a comment from our bot so that we can edit the comment with a passed message. Our bot comment images and wording have changed because of the rebranding.

**Comment by wanyaland** [comment]
@WillsonHG checking grpc/grpc-java#7613 update seems to suggest the comment is getting updated correctly. 
In addition what is the preferred image and comment to use for the passed and failed states ?
cc @dealako

**Comment by dealako** [comment]
Created PR: https://github.com/communitybridge/easycla/pull/2202

**Comment by dealako** [comment]
How to test:

1. Create PR on repo which has EasyCLA configured and user has not signed
1. Notice the user is gated and the EasyCLA status check fails. Note the comment indicates failure.
1. Sign the CLA to authorize the user.
1. Navigate back to GitHub. Observe that the status check passes and that the old comment is updated with a pass/success.

**Comment by WillsonHG** [comment]
Verified this is working in prod.
