### ISSUE TITLE
Organisation added into the database even error thrown.

### ISSUE THREAD

**Issue by amolsontakke3576** [communitybridge/easycla#2195]
When a contributor trying to add an organization and if he is already associated with another organization then API threw an error but when I tried to add the same organization next time, it shows the error website already exists. 

1. Adding Repeatme organization
![Screenshot from 2020-11-12 12-38-10.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/403c438d-cb96-4707-84c4-34367feafe41)

2. Got an error already associated with another organization
![Screenshot from 2020-11-12 12-38-25.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/c9f95c84-7986-41bc-92d1-731217441a67)

3. When tried with the same organization next time got error website aleady exist
![Screenshot from 2020-11-12 12-38-32.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/a070931d-b68c-4fe5-b5b9-edf30c5d7239)

**Comment by manishv09** [comment]
Verified today and user is able to register the New Company for Contributor console and receives email as well for completing the registration process. Please find the screencast as follows of email triggered and screens attached for reference in word doc
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/9d3a7441-a06c-48b9-bf73-f08ce5fe2e2e)
[https://app.zenhub.com/files/194341141/8e7a7473-e82d-44b1-8530-f6e302665f8e/download](https://app.zenhub.com/files/194341141/8e7a7473-e82d-44b1-8530-f6e302665f8e/download)
