### ISSUE TITLE
Project Console v1 - when a CLA manager removes a respository from one CLA group, it is disabled for use in another CLA group

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2204]
## Summary
A project manager should be able to remove a repository from one CLA group and add it to a different CLA group.

In Dev, go to A FINOS project and select to configure repositories.

Notice the repo CBTest is disabled:
![image](https://user-images.githubusercontent.com/46732999/99129328-41fb8400-25db-11eb-9590-5b8b7207d41f.png)

Notice in database that enabled = false
![image](https://user-images.githubusercontent.com/46732999/99129361-5dff2580-25db-11eb-8c81-3d12ad4f320c.png)

We should not stop a project manager from using a repo on another cla group after it has been disabled on one.
 Personally, I think that if a repo exists in the db, but it is 'disabled', then we should add another entry for it with the new cla group's information so that the old cla group's information is preserved.

**Comment by dealako** [comment]
Updated/merged changes via https://github.com/communitybridge/easycla/pull/2206

**Comment by dealako** [comment]
To test/validate:

1. Identify a Foundation, such as: DEV CNCF: https://project.dev.lfcla.com/#/project/a0941000002wBz4AAE/cla
1. Find a CLA Group, such as "A FINOS"
1. Add a GitHub Repository to the CLA Group, such as Healther's GitHub org/repo: "CLATestOrg/CBTest"
1. Observe that the GH repo is added to the "A FINOS" CLA Group
1. Edit the repository list, remove "CLATestOrg/CBTest" from the "A FINOS" CLA Group
1. Observe that the GH repo is now removed from the "A FINOS" CLA Group
1. Select a new CLA Group, such as "A FINOS(CCLA)"
1. Add the previously removed GitHub Repository "CLATestOrg/CBTest" to the "A FINOS(CCLA)" CLA Group
1. Observe that you were able to select the previously removed "CLATestOrg/CBTest" GitHub repository to the "A FINOS(CCLA)" CLA Group
1. Observe that the "CLATestOrg/CBTest" GitHub repository is now associated with the "A FINOS(CCLA)" CLA Group.
