### ISSUE TITLE
Allow hyphen (-) in organization website regex

### ISSUE THREAD

**Issue by amolsontakke3576** [communitybridge/easycla#2213]
For a certain website `-` also present which is currently not supported in org service 
Example: https://www.t-mobile.com/

Verified today and found working fine, user is able to register organization website having "-". Please refer below screencast as follows:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/be7a698a-272c-4fb0-9796-64e4ed91bad3)[https://app.zenhub.com/files/194341141/76f0521c-5310-4ef7-ac5e-b48ed6505537/download](https://app.zenhub.com/files/194341141/76f0521c-5310-4ef7-ac5e-b48ed6505537/download)

**Comment by dealako** [comment]
@amolsontakke3576 what is the status of this? Ready for QA?
