### ISSUE TITLE
Required descriptive error message for allowed/not allowed characters during add organization.

### ISSUE THREAD

**Issue by amolsontakke3576** [communitybridge/easycla#2214]
While adding a new organization with an invalid website below is the error message which shows us allowed regex which can not understand by the end-user.
```
{
    "code": 605,
    "message": "companyWebsite in body should match '^(?:http(s)?:\/\/)?[\\w.-]+(?:\\.[\\w\\.-]+)+[\\w\\-\\._~:/?#[\\]@!\\$&'\\(\\)\\*\\+,;=.]+$'"
}
```
can you make it more user friendly?

With reference to David comments stating to display message "Let's just put: "Please provide a valid organization URL." on the UI. Do not show the regex." I validated it today and same error message is received for an invalid website of a organization. Please refer below screencast as follows:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/a90a4807-a129-42fe-a005-1894f377fea8)

**Comment by dealako** [comment]
Let's just put: "Please provide a valid organization URL." on the UI. Do not show the regex.

**Comment by dealako** [comment]
@amolsontakke3576 please update this and move to QA.
