### ISSUE TITLE
Once contributor is added to approved list, Github doesn't replace the PR having 'Not Covered' tag with 'Covered' one rather, it shows another record for 'Covered'

### ISSUE THREAD

**Issue by ashav-test** [communitybridge/easycla#2218]
Pre-Condition: Have a CLA group created for a project with CCLA+ICLA option. Have CCLA signed for an Org. 

Steps:
1. Login to Github with a contributor and create a PR
2. The contributor is gated.
3. Click on the link and sign ICLA
4. Again click on the link and choose CCLA, select organization, select CLA Manager and submit
5. Login to corporate Console a CLA Manager and add the user in the approved list
6. Refresh the contributor Github page

Actual Result: The gated PR is still there with 'Not Covered' tag and Github shows another record with 'Covered' tag. Please find attached the screen shot.
![Screenshot from 2020-11-20 17-29-47.png](https://images.zenhubusercontent.com/5fa00bff91c622ed8feb9f29/2cc6748b-ee74-4670-acf1-427a4b494592)

Expected Result: Once contributor is added to approved list, Github should replace the 'Not Covered' tag with 'Covered' rather than creating a new record for 'Covered'. It may be confusing for the Contributors. 

**Test Data:** 
CLA Group Name: ashav-foundation-clagrp2
Github Org Name: ashav-test-devorg1
Github Repo Name: devorg1-repo1
Contributor Username(Github): ashishthakur42

**Comment by dealako** [comment]
Merged PR https://github.com/communitybridge/easycla/pull/2220 - please re-test.

**Comment by ashav-github** [comment]
@dealako Verified from Stage and its works fine.

![CLAGating-Covered.jpg](https://images.zenhubusercontent.com/5f6b335ce9044e3973ea11f9/2936bb3c-f7a9-4d9f-aa97-5349c78caf60)

**Comment by vinod-kadam** [comment]
Asha updated that she has verified the ticket & working fine. So, moving this ticket to QA Done.
