### ISSUE TITLE
"Project Not found" error in Gerrit when generating ICLA

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2223]
## Summary

When a customer tries to sign an ICLA for a Gerrit project, the button does not activate.

## Background

Go to https://gerrit.o-ran-sc.org
Settings
Agreements
New Contributor Agreement
ICLA
Login if prompted
Button doesn't activate and observe api error

![image](https://user-images.githubusercontent.com/46732999/99978300-c84e5d80-2d73-11eb-8b7f-71194665de05.png)

**Comment by dealako** [comment]
Pushed PR https://github.com/communitybridge/easycla/pull/2226 which resolves the redirect issue.

**Comment by dealako** [comment]
Seems resolved, redirect works - able to generate signing request:

![Screen Shot 2020-11-23 at 11.08.32 AM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/9fb17fc5-3e49-42e1-843f-f49fca9aac7d)
