### ISSUE TITLE
Project Console - Unable to add the CLA Group with the same name which got removed during un-enrollment of last project from the CLA Group

### ISSUE THREAD

**Issue by rinkeshbhutwala** [communitybridge/easycla#2224]
Pre-condition: Have a CLA group with one project in it.
Ex: CLA Group Name: asha-foundation-clagrp5

Steps:

1. Login to Admin Console and click on the project.
2. Open the newly designed CLA Overview page using this URL: https://admin.dev.platform.linuxfoundation.org/apps/cla/overview#id=<id>
3. From the left panel click CLA group having only one project. Un-enroll the project and click on Update button. I have unenrolled 'project4' from CLA group 'asha-foundation-clagrp5'
4. Go back to the CLA Overview screen, it doesn't show the CLA group 'asha-foundation-clagrp5'
5. Click on Add CLA Group button and try to add the same cla group name

Actual Result - It throws error 'CLA Group with name asha-foundation-clagrp4 already exist'

Expected Result: David Deal Pranab Bajpai I am not sure what should be expected behavior here ?
Either it should delete the CLA group so that same name can be reused OR if CLA Group is not deleted then it should display in the CLA Overview page.

**Comment by rinkeshbhutwala** [comment]
Reference ticket `https://jira.linuxfoundation.org/browse/LFX-2790`

**Comment by vinod-kadam** [comment]
Marking it as QA Done since Asha verified this one through LFX-2790.
