### ISSUE TITLE
EasyCLA Approval Request for contributor email should have link for Corporate Console.

### ISSUE THREAD

**Issue by ashav-github** [communitybridge/easycla#2225]
Pre-Condition: Have a project where CCLA is signed and the contributor is not added in approval list.
Steps:

1. Login to github and create a PR.
2. The contributor is gated, click on the 'Not Covered' button.
3. Select Organization, Select CLA Manager and submit for approval.
4. The CLA Manager receives an email with Subject line 'EasyCLA: Approval Request for contributor: <gh username>'. Check the email content.

Actual Result: The email doesn't have link to Corporate Console. PFA the email. ![Screenshot from 2020-11-23 22-51-24.png](https://images.zenhubusercontent.com/5f6b335ce9044e3973ea11f9/45103356-4f36-4611-968b-6e274175d93c)

Expected Result: The email should have link to Corporate Console. This is already discussed on Stand-up call with Pranab.

**Comment by dealako** [comment]
@makkalot can you review this one. Pretty easy. Not sure if the system email is generated from Python or Golan. Search for the email content to find where it is generated from the code.

We can [do something like this](https://github.com/communitybridge/easycla/blob/master/cla-backend/cla/controllers/gerrit.py#L135) which determines which version we are using (v1 vs v2) and grabs the console link we need and add a link to the email. Get @pranab-bajpai or @WillsonHG to confirm the email content/text.

**Comment by wanyaland** [comment]
@dealako so for this case email was generated from golang end in the v2 package. So just included the v2 link to the corporate console

**Comment by manishv09** [comment]
Verified for V2 today and found working fine now and user is able to see the corporate console link on the email. Please refer the screencast as below for reference:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/39e72ccc-7dd6-4927-9550-952f6ff6d067)
