### ISSUE TITLE
Company is being created from Contributor Console

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2229]
## Summary

A company is being created from the contributor console with the contributor's GitHub information. This is creating an incomplete company in the database. This incomplete company is causing issues when a person is trying to join it from the corporate console.

## Background

1. A contributor is gated by EasyCLA in github
2. The contributor selects "corporate" -> "company not in the list" ->"no" when asked if they can be CLA Manager -> Fills in CLA manager dialog and presses send.
3. A company is created in the database with the name the contributor used on the modal. It uses the contributor's information to create the company. If there is no name, it will create a company without a company_acl. If there is a public name on the contributor's profile, it creates the company with the user_name from the users table instead of the lf_username (because it doesn't yet exist).
4. CLA manager receives email to log into the corporate console to sign the CLA.
5. CLA manager logs into the corporate console and finds their company in the list (because it was incorrectly added by the contributor in step 3.)
6. The CLA manager requests to join, but the UI spins and the request email isn't sent.
11. An email is not sent to the current manager of the company, because the company was created by the contributor who did not have an email and probably not even a name. 
12. Both the CLA manager and the contributor are blocked.

## Expected behavior

The company should not be created from the contributor console. It should not be created by a contributor who selects "no" that they cannot be a cla manager. The contributor's information is being pulled from github without a LF SSO username, so the company will have an empty or bad company_acl. No one will be able to access the company created to approve join requests.

## Screenshots
New company created with a name instead of username when the contributor sends the email to the cla manager designee.
![image](https://user-images.githubusercontent.com/46732999/100035317-e21b8f00-2dcb-11eb-8a1f-e6408aae474a.png)

**Comment by amolsontakke3576** [comment]
@dealako  @WillsonHG 
 I and @rinkeshbhutwala debug this issue and it is working fine when the contributor having an LFID (PFA)
![Screenshot from 2020-11-24 11-51-46.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/99bf2f9b-f862-44f8-a9ac-82f7c2990c5b)

 The issue is when the contributor tried to create a new company and he is not having an LFID. It is mostly backend work and @rinkeshbhutwala is working on it.

**Comment by WillsonHG** [comment]
@amolsontakke3576  The contributor is not "trying" to create a company at all. The contributor is only sending an email to her potential CLA manager and asking the CLA manager to create the company. The screenshot above is not applicable to the situation.

To be clear, the issue is that the company is being created through the CONTRIBUTOR console when the contributor selects "company not in the list" from the CONTRIBUTOR console.
![image](https://user-images.githubusercontent.com/46732999/100121046-ab368f00-2e46-11eb-821e-d8ba07168fc7.png)
![image](https://user-images.githubusercontent.com/46732999/100121146-c903f400-2e46-11eb-9a28-abb47284371e.png)
![image](https://user-images.githubusercontent.com/46732999/100121329-f05ac100-2e46-11eb-8f1a-13a12baa51a6.png)


The company is being created in the database with the CONTRIBUTOR's name (and not lfid), the name the contributor listed (so it may be different from the actual legal name needed), no manager id, and no SF external ID.

The company should not be created at this step at all.

**Comment by vinod-kadam** [comment]
As updated by @WillsonHG , in V1, we should allow to create a company when the user says he is the cla-manager & he has LFID. This leads to access list issue.
However in v2,  this should not be a problem.
Anyway, Heather & Pranab to discuss it with David & update the ticket with details.

**Comment by amolsontakke3576** [comment]
I have updated the flowchart for the above change
![Add Company From Contributor Console.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/ef052318-76d5-40fc-b76b-e0b718d625f8)

**Comment by WillsonHG** [comment]
After speaking with Vinod and Amol, the above flowchart should be changed in the case of "contributor is a cla manager = yes"  to always redirect back to the corporate console. We won't create the company from the contributor console at all in v1.

I was unable to find an email with more explicit instructions about adding a company in the corporate console. I don't think we've ever had one. https://docs.google.com/document/d/1jFlSq1tx66LbBwGbSfJm3QS4st68GblfzBEMZRya9gk/edit#heading=h.i8xtxdsoybfh The current email being sent is fine since it directs them to the corporate console and they will either see their company listed or they'll see the "Get Started" button that is self documenting with instructions on how to join or add a company.

**Comment by WillsonHG** [comment]
Also, the documentation says to "Add your company to a project" https://docs.linuxfoundation.org/lfx/easycla/contributors/corporate-contributor#if-your-company-is-not-in-the-list

**Comment by amolsontakke3576** [comment]
Updated flow chart
![Add Company From Contributor Console (1).png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/326e20b4-3dfe-4519-b001-b5031be06ec5)

**Comment by dealako** [comment]
@amolsontakke3576 status? Ready for QA?

**Comment by dealako** [comment]
Resolved in DEV and STAGING.  Ready for QA - need review prior to pushing to PROD.

**Comment by WillsonHG** [comment]
Hi @amolsontakke3576  While testing this is in dev, when selecting "no" to send the email to the cla manager, I am getting this error:
![image](https://user-images.githubusercontent.com/46732999/101841250-9549ef00-3b13-11eb-9ca7-16567c12de48.png)

**Comment by WillsonHG** [comment]
this appears to have been resolved, the form no longer creates a company when the user selects either 'yes' or 'no' and the email looks correct.

**Comment by vinod-kadam** [comment]
As updated by @WillsonHG , moving it to QA done.

**Comment by WillsonHG** [comment]
fixed in prod
