### ISSUE TITLE
Notify when EasyCLA Privileges prevent CLA check on Repo

### ISSUE THREAD

**Issue by jpalmerLinuxFoundation** [communitybridge/easycla#223]
**Summary**
When an admin or maintainer modifies the privileges that the EasyCLA has to check GitHub PRs there's currently no notification of any kind. Project Managers need to know when their PRs are configured to get an EasyCLA check, but the check cannot be performed due to an access change.

**Background**
1. An admin/owner of a GitHub Repo/Organization goes into the "Settings" tab
2. Then clicks on "Integration & services" verticle navigation
3. Then clicks "Configure" associated with the EasyCLA App
4. Then disables some or all of the permissions that EasyCLA has to their repos

**User Story**
As a project manager,
I need to know when the CLA checks are not able to run
so that I can act appropriately and reinstate the checks as soon as possible

**Scenarios/Logic**
When a GitHub Repository is configured in EasyCLA Project Console the repos are added to our database in the `cla-*-repositories`
Given a PR on one of these repositories, if we get a permissions error
Then we send an email notification to the LFIDs who have the corresponding external project id listed in their `projects` list on `cla-*-user-permissions` table

Include the following details in the email body
1. `project_name`
2. `cla-*-repositories`.`repository_name`
3. Description: "EasyCLA is unable to check PRs on this repo due to permissions issue. Please contact the repository admin/owner to enable CLA checks.
Provide the Owner/Admin the following instructions:
- Go into the "Settings" tab of the GitHub Organization
- Click on "Integration & services" verticle navigation
- Then click "Configure" associated with the EasyCLA App
- Finally, click the "All Repositories" radio button option

**Acceptance Criteria**
The "done" criteria when this feature or problem is resolved.  Such as:
1. Unit Tests added and running in CI
2. Functional Tests updated to cover feature, if applicable
3. Demonstrate the set of capabilities to the product team while the code is
   running in the STAGING environment.

**References**
Tekton currently has this issue

**Comment by jpalmerLinuxFoundation** [comment]
`Notes for documentation`
- Scenario 1: GitHub Org Admin/Owner has disabled EasyCLA without notifying project leadership. EasyCLA should be reactivated immediately and permissions updated to prevent future activation. See https://github.com/communitybridge/easycla/blob/master/docs/CLA-Troubleshooting.md EasyCLA is Disabled #156 
- Scenario 2: Project has decided to stop checking for CLAs on one or more repos and modifies EasyCLA app on GitHub. The Project Manager for the corresponding project must also update the EasyCLA configuration to match the list of Repos being checked.

**Comment by dealako** [comment]
@prasannamahajan Possible fun one - the ticket already includes some details.

May want to implement/deploy a lambda on a schedule to run a task (daily) to check for
permissions (see `cla-prod-github-orgs` table entries, https://confluence.linuxfoundation.org/display/PROD/EasyCLA+Version+1+Database+Schema+Walkthrough#EasyCLAVersion1DatabaseSchemaWalkthrough-GithubOrgs) and when a GH org member
removes CLA permissions (by disabling/removing the App from GH) we discover this
by running a nightly permission check.

When doing this check and we fail, we need to lookup the Project associated with the repo/org and send the project manager(s) an email.  Coordinate with @pranab-bajpai on the email text/content. We simply need to send an email via the Platform Core Service SNS topic, see API: https://github.com/communitybridge/easycla/blob/master/cla-backend-go/swagger/cla.yaml#L294,which we can re-purposed (initially used for onboarding, but later abandoned, maybe rename the endpoint and package name) for sending generic emails (request payload: https://github.com/communitybridge/easycla/blob/master/cla-backend-go/swagger/cla.yaml#L1494).

The GH id/token we use for repo authentication/permissions is stored in the environment SSM config.

**Comment by pranab-bajpai** [comment]
Prasanna here is the Email to be sent:

Project Manager for <project_name>,

EasyCLA is unable to check PRs on this repo due to permissions issue.
 `cla-*-repositories`.`<repository_name?`
Please contact the repository admin/owner to enable CLA checks.
Provide the Owner/Admin the following instructions:
- Go into the "Settings" tab of the GitHub Organization
- Click on "Integration & services" vertical navigation
- Then click "Configure" associated with the EasyCLA App
- Finally, click the "All Repositories" radio button option
  
Thanks,
EasyCLA Support Team

**Comment by prasannamahajan** [comment]
Changes merged in master with pull request [#478](https://github.com/communitybridge/easycla/pull/478)
