### ISSUE TITLE
[Regression] - V2 - Identify CLA Manager - Focus is moved out of Identify CLA Manager popup when hit on TAB key

### ISSUE THREAD

**Issue by manishv09** [communitybridge/easycla#2232]
Prerequisite
1. Create a CLA group with CCLA enabled
2. Add github repository for the CLA group

Steps to Follow
1. Login to Github as corporate contributor
2. Navigate to the repository used in prerequisite
3. Create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Contributor is redirected to Contributor Console
7. Click on Proceed as a Corporate Contributor
8. 8.Click on building icon
9. Click on Organization not listed? + Click Here
10. Enter Organization website
11. Click On Submit Request
12. On "No CLA Found Popup" Click on No button
13. New Popup with Title "Identify CLA Manager" is shown
14. Hit TAB Kay
Expected: Focus should not move out of popup

Actual:  Focus is moved out of popup. Focus should be on next field. User should be able to move to next fields with TAB 

Please refer screencast & other workflow screencast attached for reference
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/6f40926b-a476-438e-9a30-8ef6d4e60923)
key[https://app.zenhub.com/files/194341141/a7916b0d-f85f-496f-9d1c-1cded15f7b38/download](https://app.zenhub.com/files/194341141/a7916b0d-f85f-496f-9d1c-1cded15f7b38/download)

**Comment by dealako** [comment]
@amolsontakke3576 in this case, you want to control the tab behavior to go from:

1. initial focus on the user input field 1
1. user hits <TAB>
1. user input field 2 should now have the focus
1. user hits <TAB>
1. go back button should now have the focus
1. user hits <TAB>
1. submit request button should now have the focus
1. user hits <TAB>
1. user input field 1 should now have the focus
... repeat

**Comment by manishv09** [comment]
Verified today on Staging and found working fine now, please follow below screencast for reference:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/a028b815-9e1c-4b7b-8985-18a251704b0b)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/885430f7-492e-4420-83b0-1b237e7309cc)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/b1a24e37-1739-48cb-9523-db8b91279f8b)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/fd299cfc-6fa2-420a-945a-ccdc0e30d323)
