### ISSUE TITLE
V2 - In the “configure repos” screen, if the org / repo name is longer than the table cell, it is cut off and doesn’t wrap or scroll

### ISSUE THREAD

**Issue by manishv09** [communitybridge/easycla#2238]
1.	In the “configure repos” screen, if the org / repo name is longer than the table cell, it is cut off and doesn’t wrap or scroll, and hovering doesn’t show it either -- see screenshot below. That means it isn’t possible to tell which repo is which without opening every link

![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/7abc2e09-eefe-4a1e-b4de-ee69bd126770)

**Comment by vinod-kadam** [comment]
@manishv09 , this is a Project Console issue, please log this issue in the Admin Console JIRA board.
And then delete or close this ticket from here.

**Comment by manishv09** [comment]
Raised this issue on LFX Admin Console Board hence closing this issue.
