### ISSUE TITLE
Create a new go lang endpoint for send a email to CLA manager regarding new company.

### ISSUE THREAD

**Issue by amolsontakke3576** [communitybridge/easycla#2241]
Create a new go lang endpoint `request-add-company` which sends an email to CLA manager.
Input body :
```
{
contributor_name: '<name>',
 contributor_email:  '<email>',
 cla_manager_name:  '<name>',
 cla_manager_email: '<email>',
 project_name:  '<name>',
 company_name:  '<name>'
}
```

Below is the email content which need to be send to CLA manager.
![image (2).png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/77e6ba14-a986-4c37-a0c3-97ca3f077849)

**Comment by vinod-kadam** [comment]
As updated by @amolsontakke3576 , this is not v2.
cc @pranab-bajpai , @dealako , @WillsonHG

**Comment by dealako** [comment]
Let's defer this to post v2 launch. I will create a new set of tickets for migrating the existing python APIs to golang.
