### ISSUE TITLE
After creating project level CLA group, the CLA overview page doesn't display CLA group, it shows empty page.

### ISSUE THREAD

**Issue by rinkeshbhutwala** [communitybridge/easycla#2248]
Steps:

1. Log in to the Admin console and create a project-level cla group by selecting any one child project.
2. Observe the CLA overview page after creation.

Actual Result: It shows an empty page. But if go to the CLA overview page by clicking the foundation name it shows the cla groups.
Expected Result: CLA Overview page should display the created cla group.

Reference: https://jira.linuxfoundation.org/browse/LFX-2851

**Comment by manishv09** [comment]
Verified and found working fine on DEV Environment, moving to QA Done status. Please refer screencast for more details:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/f4f16036-d3c7-4e67-95e7-dafec42b9dec)
