### ISSUE TITLE
Provide link to documentation faq when email is incorrect

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#2253]
In contributor console when the user types wrong email address, show the message " Email provided is incorrect, please check the faq section to see valid email format" and provide this link  - https://docs.linuxfoundation.org/lfx/easycla/getting-started/easycla-faqs

**Comment by vinod-kadam** [comment]
FAQs Link for V2 is https://docs.linuxfoundation.org/lfx/v/v2/easycla/getting-started/easycla-faqs
FAQs Link for V1 is https://docs.linuxfoundation.org/lfx/easycla/getting-started/easycla-faqs

**Comment by amolsontakke3576** [comment]
@vinod-kadam This is a ticket only related to the V2 contributor console however we have an FAQ link in the header for V1 consoles and it is redirected properly to the V1 link as mentioned above.
