### ISSUE TITLE
Same Github org is shown for the different CLA groups having different enrolled projects.

### ISSUE THREAD

**Issue by ashav-github** [communitybridge/easycla#2271]
Steps:

Pre-condition: Have a project group with multiple CLA groups having github org configured.

1. Login to Admin console, go to CLA Overview page and click on any CLA Grp->Manage button.

Actual Result: It shows same Github org everywhere i.e. 'ashav-test-renaultsedan' is shown for whatever project I select under any cla grp. 
Project Group: Renault-Foundation

Expected Result: Github page should display correct configured Github Org.

**Comment by dealako** [comment]
This is the expected behavior under a given Project Group.

**Comment by dealako** [comment]
Spoke to product owner @pranab-bajpai and decided to close this issue as it is the expected behavior.
