### ISSUE TITLE
Redo the Event Log text based on input by marketing

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#2275]
Please follow this document
https://docs.google.com/document/d/1hhOABIsf5n0IJxamkqcvPqOgNBby6Wf52aZykcu8o9s/edit?usp=sharing
There are some textual and language changes that need to be made to event log printf statements, please implement those. 

Please work with @dealako if you have any questions.

**Comment by dealako** [comment]
No data migration. Just update the text IAW the document recommendations.

**Comment by wanyaland** [comment]
@makkalot Could you kindly share specific changes that needed to be worked on that I would need to verify ?

**Comment by wanyaland** [comment]
Verified and as well raised a PR that was merged to DEV fixing activity log content for CCLA and ICLA signings.
