### ISSUE TITLE
Show a loading icon to denote that something is happening in the background

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#2289]
On contributor console, right before the user goes to corporate console there is a long wait at this screen.
![image](https://user-images.githubusercontent.com/57362064/101591569-6e27dc00-39b2-11eb-9ff0-63184b939411.png)
This wait is misleading to the user without any loading or activity icon, we should add one so that the user knows that something is happening in the background before the user is redirected.

**Comment by tejasadg** [comment]
Verified that Loading spinner is shown while processing.
![Screenshot from 2021-01-05 20-08-49.png](https://images.zenhubusercontent.com/5ef5dcf0c63b2d6363eb509d/6e8daa35-2962-44e6-b7ed-d42161586d77)
![Screenshot from 2021-01-05 20-09-03.png](https://images.zenhubusercontent.com/5ef5dcf0c63b2d6363eb509d/ff835380-cf15-46b5-b842-6ef6f75f522e)

cc: @vinod-kadam
