### ISSUE TITLE
While signing CCLA, the template says 'CLA Sign Request for None'

### ISSUE THREAD

**Issue by ashav-github** [communitybridge/easycla#2296]
While signing CCLA, the template says 'CLA Sign Request for None'.

Expected Result: It should say: 'CLA Sign Request for <company name>

![Screenshot from 2020-12-09 14-49-30.png](https://images.zenhubusercontent.com/5f6b335ce9044e3973ea11f9/3004cb84-e469-4396-a50c-bf6af1acceb5)

**Comment by ashav-github** [comment]
Expected Result: It should say: 'CLA Sign Request for 'company name'

**Comment by rinkeshbhutwala** [comment]
@vinod-kadam I have gone through the scenario and found it like it's set it from python back-end if we did not found any details for the given details from python side it's set it as **None**.

It is under docusign_model.py file line no. 1126.

**Comment by vinod-kadam** [comment]
@rinkeshbhutwala  please check the business logic in docusign_mode.py file.

**Comment by vinod-kadam** [comment]
Un-assigned Harold; @rinkeshbhutwala  please check the python file for the logic used & update it here.

**Comment by vinod-kadam** [comment]
As discussed, @dealako  to review it & decide the next course of action.

**Comment by vinod-kadam** [comment]
As discussed in the 18-Dec standup, Harold has made the fix, David to push it to Dev/Staging.

**Comment by vinod-kadam** [comment]
As updated by @wanyaland , the fix is deployed to Dev & Staging.

**Comment by manishv09** [comment]
@wanyaland 
Verified today and found "Unknown" in place of none:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/471f0601-8b3c-48dc-9ae4-a68760a58415)
Is this expected here?

CC: @dealako @vinod-kadam

**Comment by ashav-github** [comment]
@wanyaland @manishv09 I tested this flow with below mentioned scenario and it works fine. Manish, please add the exact steps when it shows 'Unknown'

'CCLA->Select existing org->identify yourself as CLA Manager and create new account'

![image.png](https://images.zenhubusercontent.com/5f6b335ce9044e3973ea11f9/8a7e7935-8561-48db-9cd3-8cdabf37bea9)

**Comment by ashav-github** [comment]
The issue mentioned by Manish above is on ICLA flow. Marking this fix as done because for CCLA its working fine.

**Comment by manishv09** [comment]
Verified today and found Company name is not appearing while signing CCLA on Docusign Page instead it should User name
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/1e1ecbc9-ca6e-4261-988a-999bf2932518)

**Comment by vinod-kadam** [comment]
As updated by  @wanyaland , he raised the PR - so now in case of CCLA company name will be returned while in case of ICLA user name or email address will be returned based on the availability.

**Comment by vinod-kadam** [comment]
Available on Dev env for QA testing.

**Comment by manishv09** [comment]
Verified on Staging environment and found working fine for ICLA as well as CCLA. Please refer the screencast as follows:
ICLA:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/e9d75bef-83a0-47bb-83a8-4b2db101ff38)

CCLA:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/402416f9-f5fc-4429-9695-2cd944ca6ce1)
