### ISSUE TITLE
ICLA Signature Check Fails Due to Multiple ICLA Table Entries

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#232]
**Summary**

ICLA Signature Check Fails Due to Multiple ICLA Table Entries

**Background**

Provide context to the issue - provide steps to reproduce the behavior:

1) The user makes a commit and creates a PR
2) The user fails the GitHub EasyCLA check
3) The user navigates through the signing process, selects ICLA, and decides not to finish the process. Note: a record is created, but `signature_signed` value is false.
4) The user changes their mind and decides to go ahead and sign the ICLA - navigates through the process once more and signs the document. Note: a second record is created with the `signature_signed` value is true.
5) At this point, we have two ICLA signature entries in the DB:
   - 1 not completed - `signature_signed` == false
   - 1 completed - `signature_signed` == true
6) EasyCLA check queries the database and attempts to pull the latest ICLA document. Since the major and minor versions are the same, the first record appears to be returned in this case.  Since the ICLA is not signed, the check fails.

**Expected behavior**

The user would pass the ICLA check since they have signed a CLA document.

**Screenshots**

N/A

**Environment**

Please complete the following information:
 - Environment: PROD 

** Work Around ***

Manually removing the record where `signature_signed` == false resolves the ICLA check issue.

**Additional Context**

Possible Fixes:
1) Avoid duplicate entries
2) Adjust document versioning logic to that the latest is used (but the document versioning was intended for something else - like editing that same document, not replacing it)
3) review the `created` date/time column and use the latest entry
4) loop through the ICLA signatures and select the first one that is completed/signed - ignoring the others

**Acceptance Criteria**

The "done" criteria when this feature or problem is resolved.  Such as:
1. Unit Tests added and running in CI
2. Functional Tests updated to cover feature, if applicable
2. Demonstrate the set of capabilities to the product team while the code is
   running in the STAGING environment.

**References*

(Optional) Provide any code or specification references that would be helpful
for the developer implementing this feature.

**Comment by WillsonHG** [comment]
This is still a lingering issue https://github.com/prestodb/tsc/pull/9
