### ISSUE TITLE
Cla-group is not deleted at project console when deleted by API

### ISSUE THREAD

**Issue by vinod-kadam** [communitybridge/easycla#2320]
Found through bug-bash on 11-Dec

Logged By: Veerendra Singh Thakur
Summary: Cla-group is not deleted at project console when deleted by API
Description/Steps to Reproduce: 
1. Login Admin portal
2. Add cla-group to child project 
3. Delete Cla-group using API 
cla-groups id : 95b4436b-90a2-42d0-a262-1ec2d086d97b
project sgId: a096s0000003knrAAA
End point URL : https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/cla-group/95b4436b-90a2-42d0-a262-1ec2d086d97b
--Run & check Cla-group is deleted or not through 
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/foundation/a096s0000003knrAAA/cla-groups
See-Empty list appears

4. Now go to admin portal & check, see-cla-group is still visible <Issue>
5. Check cla-group id is deleted at DB 

Actual Result: cla-group remain at admin portal
Expected Result:cla-group should be remove 
Screenshot: 
Get List after delete claGroup :https://prnt.sc/w0guzg
Response of Delete CLA-group : https://prnt.sc/w0gw7e
CLA-group at project console : https://prnt.sc/w0gx4l
DB Screenshot :https://prnt.sc/w0hirx

**Comment by thakurveerendras** [comment]
Issue is tested on Dev & staging environment & found that Cla-group is properly deleted at project console when deleted by API, So making issue status to QA-Done

**Refer below details for staging env**
```
baseUrl:  https://api-gw.staging.platform.linuxfoundation.org/cla-service/v4/
claGroupID: c6df3a6b-a200-4494-879b-d39e18dc9ce3
API Endpoints : {{baseUrl}}cla-group/{{claGroupID}}
```

**Staging before Run Delete endpoint**
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/875c507d-7f9b-443e-ba28-0ef30f343b34)
**Staging after Run Delete endpoint**
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/d6aad93d-9cae-405e-a672-f6509dd4fa4f)

**Refer below details for Dev env**
```
baseUrl:  https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/
claGroupID: 5db52023-cc06-4201-aed8-0326f5bc48cc
API Endpoints : {{baseUrl}}cla-group/{{claGroupID}}
```
**Dev before Run Delete endpoint**
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/413c7788-9608-4894-8147-ce634bbffe96)
**Dev after Run Delete endpoint**
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/1551ed91-a2ed-4d40-ad6a-5c6f6602f855)
