### ISSUE TITLE
Regression: Error 404 is shown to user when tries to navigate to GitHub Configuration by clicking Manage button

### ISSUE THREAD

**Issue by rinkeshbhutwala** [communitybridge/easycla#2328]
Error 404 is shown to the user when tries to navigate to GitHub Configuration by clicking the Manage button

Below error is observed :

query name:"getProjectGithubOrg"

error:"{"Code":"404","Message":"EasyCLA - 404 Not Found - github organization with project SFID not found: a096s0000003lyhAAA","x-request-id":"b1b99610-3eb3-11eb-ab11-47e2c5c93588"}"

**Comment by tejasadg** [comment]
Verified that Error 404 is not returned while navigating to the Github configuration page.
cc: @vinod-kadam
