### ISSUE TITLE
Gerrit Flow : Gerrit id is invalid when redirected to the contributor console

### ISSUE THREAD

**Issue by amolsontakke3576** [communitybridge/easycla#2329]
![Screenshot from 2020-12-15 19-32-17.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/951f6e7a-87cb-485d-826e-f17d45767009)

After click on '`Please review the agreement.`' it is redirected to the below URL 
https://api.staging.lfcla.com/v2/gerrit/4405798d-913c-4a8d-a906-dd61d91c2d62/individual/agreementUrl.html

and show this error
{'errors': {'gerrit_id': 'Gerrit Instance not found'}}

Root cause is Gerrit id is different than what is in the database. URL should be
https://api.staging.lfcla.com/v2/gerrit/7608d12f-80ec-4f03-8425-4e9e7d0af28a/individual/agreementUrl.html

**Comment by dealako** [comment]
@rinkeshbhutwala - @WillsonHG has provided a document to @amolsontakke3576 describing how to set this up properly.

**Comment by amolsontakke3576** [comment]
As per discussion with @WillsonHG on slack, @rinkeshbhutwala has changed Gerrit id to the one which is given by @WillsonHG and now it's working fine on stage. 

So look like it's the limitation of Gerrit so every time when anyone creates a new CLA group of Gerrit project he needs to update Gerrit instance id to `4405798d-913c-4a8d-a906-dd61d91c2d62` to works fine on staging.

**Comment by WillsonHG** [comment]
Since this was a setup issue, I'll close this ticket out.
