### ISSUE TITLE
V2 Contributor is navigated to V1 landing page when clicked "covered" on GitHub 

### ISSUE THREAD

**Issue by manishv09** [communitybridge/easycla#2330]
V2 Contributor is navigated to V1 landing page when clicked "covered" on GitHub. Please refer below screencast for more details:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/30c301e8-78ee-459e-9b6c-35a4e0d2ea1b)
When User click on covered (https://github.com/Test-Staging-Repo002/Repo001/pull/1) it navigates to V1 version URL whereas it should navigate the user to V2
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/8e1b0022-0527-44ff-b826-071afa5cfcb8)

V2 Version project Group and CLA Group project details are as follows in screenshot:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/ed2c8758-b535-4951-9af7-935f661d5d6b)

**Comment by dealako** [comment]
Add a new version query pameters (maybe: v=2, ver=2, version=2)

- If no version query parameter => v1 links
- If v1 query parameter => v1 links
- If v2 query parameter => v2 links
- If bad/junk => v1 links

**Comment by amolsontakke3576** [comment]
@makkalot I will write a code with query param `version=1 or version=2` please make changes accordingly on your side,

**Comment by vinod-kadam** [comment]
As updated by @amolsontakke3576 , Dev ETA: 16-Dec

**Comment by vinod-kadam** [comment]
Currently, available on Dev.

**Comment by vinod-kadam** [comment]
As updated by @wanyaland , code deployed to staging yesterday night. So, this ticket can be verified now on staging.

**Comment by manishv09** [comment]
I validated on DEV environment and the issue is reproducible. Please refer below screencast:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/a5f33a92-22ec-40e0-8677-e4df2cdcb390)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/3b05c2fc-e21e-4e42-8b1f-494eadf488b2)
https://github.com/Test2151EasyCLA/Test2151EasyCLA-Project001/pull/2
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/40226746-220a-4edb-9264-9c8bd65d89ea)

**Comment by manishv09** [comment]
@dealako It is discussed in today's Sync-up call with Amol & Vinod and others that this issue can only be verified successfully on production environment.
CC: @vinod-kadam @amolsontakke3576

**Comment by vinod-kadam** [comment]
@dealako to push the fix to Production & create a test cla group on production for v2.

**Comment by vinod-kadam** [comment]
As discussed in the morning syncup, @amolsontakke3576  please test it on Staging - do hardcoding for specific repo so that from from github it goes to staging (as discussed it should not impact any production users).

**Comment by vinod-kadam** [comment]
Comment as on 21-Dec: Earlier thought was that we can not test it Staging & will need PROD however after giving a bit of a thought, we think it can be tested on Staging. Amol to sync up with Denis as the fix is not working on v1 Staging.

**Comment by vinod-kadam** [comment]
As updated by @amolsontakke3576, @makkalot has deployed his changes to Dev. Amol to check from his side now.

**Comment by amolsontakke3576** [comment]
@vinod-kadam The task is almost done only the issue is with SSM parameter value for corporate console (missing HTTPS prototype) @wanyaland is working on it and once he done I will test and move to QA.

**Comment by amolsontakke3576** [comment]
@manishv09 to test on dev and staging use below URL and change version manually for now
Dev: https://dev.lfcla.com/#/?version=2
Staging: https://staging.lfcla.com/#/?version=2

**Comment by vinod-kadam** [comment]
As discussed in the standup, @dealako  to review github bot confiugration.

**Comment by dealako** [comment]
To resolve the GitHub bot link, I created PR: https://github.com/communitybridge/easycla/pull/2382 to resolve this issue.  This change pulls the landing page link from the configuration which includes separate links for DEV, STAGING, and PROD.

**Comment by manishv09** [comment]
Verified today on Staging environment and found working fine now, please refer screencast below:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/f876a8d8-ddac-48bd-a6d0-79386afbcc75)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/d54783b6-10ca-4e5c-b466-675c9bf97d70)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/2ae84518-8f64-4fc7-8b6e-a6d72a3b69e3)
