### ISSUE TITLE
Unable to enroll back the child project to CLA Group after unenrolling it.

### ISSUE THREAD

**Issue by ashav-github** [communitybridge/easycla#2337]
Steps:

1.  Have a project group with project level CLA Group created.
2.  On the CLA overview page, unenroll the project from CLA group and try to enroll back. 

Actual Result: It throws error: 

error:"{"Code":"500","Message":"EasyCLA - 500 Internal server error - error = cla_group project association already exist","x-request-id":"11bb8ee0-3fbf-11eb-ab11-47e2c5c93588"}"
errorLoggedTime:"Wed, Dec 16th 2020, 10:22:25 pm IST"

Expected Result: Enrollment should work fine.

**Comment by ashav-github** [comment]
Here is the screen shot:

![Enroll-ChildProject.jpg](https://images.zenhubusercontent.com/5f6b335ce9044e3973ea11f9/b91c7387-db74-42c2-ad1f-79e76edc6f96)

**Comment by dealako** [comment]
Related to updating repo count - creates a partial record...

**Comment by dealako** [comment]
Created PR: https://github.com/communitybridge/easycla/pull/2341

**Comment by ashav-github** [comment]
@dealako tested on Stage and it works fine. There is an additional issue observed related to enrollment and unenrollment and is reported as https://app.zenhub.com/workspaces/easycla-5ed619832c71a855a76ef404/issues/communitybridge/easycla/2346

**Comment by vinod-kadam** [comment]
Asha updated that she has verified the ticket & working fine. So, moving this ticket to QA Done.

**Comment by dealako** [comment]
Resolved - closing ticket.
