### ISSUE TITLE
Create EasyCLA v2 UI Repository

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#234]
**Summary**

Create the EasyCLA v2 UI GitHub Repository

**Background**

Possible code locations:
1. communitybridge/easycla-ui - public
   1. Advantages: repository contains just the new UI code - nothing else, promotes abstraction/separation from the backend and deployment services. Would allow a separate tag/release process.  Issues would be UI focused without backend or deployment or database issues intermixed. 
   1. Disadvantages: would have to manage another repository/permissions
1. communitybridge/easycla/cla-ui - public, under the current repository
   1. Advantages: code all in one place.
   2. Disadvantages: monorepo is getting out of hand - a jungle of old and new code
1. LF-Engineering/easycla-ui - private repository
   1. Advantages: none really, unless we want to keep it private for some reason
   2. Disadvantages: EasyCLA code should be made public per our previously shared vision

**User Story**

N/A

**Acceptance Criteria**

EasyCLA repository established with permissions, README, LICENSE and initial repo files.

**References**
github.com/communbitybridge/easycla

**Comment by dealako** [comment]
Created new repo: https://github.com/communitybridge/easycla-ui, mirrored easycla main repo settings.

**Comment by dealako** [comment]
Added initial files for the empty repo, license, package.json, circleci config. Setup circleci.  Added build status.

**Comment by jpalmerLinuxFoundation** [comment]
Is this forked and independent of v1?

**Comment by dealako** [comment]
Closing this issue as the new user interface will be part of the Community Bridge product offering.
