### ISSUE TITLE
Change Contributor Console documentation URL to the new lfx one 

### ISSUE THREAD

**Issue by vinod-kadam** [communitybridge/easycla#2343]
Dibya provided the new EasyCLA documentation URL.
The old URL being used in Contributor Console is https://docs.linuxfoundation.org/docs/communitybridge/easycla.
It need to be changed to https://docs.linuxfoundation.org/lfx/v/v2/easycla

**Comment by vinod-kadam** [comment]
Fix is available on Dev & Staging.

**Comment by ashav-github** [comment]
@vinod-kadam @amolsontakke3576 tested on Stage and document link works fine for contributor console: 

https://docs.linuxfoundation.org/lfx/v/v2/easycla

![ContributorConsole-DocLink.jpg](https://images.zenhubusercontent.com/5f6b335ce9044e3973ea11f9/b512d82a-9802-4ded-9704-adc86e56bb20)

**Comment by vinod-kadam** [comment]
@ashav-github , log separate tickets for Corporate Console in JIRA.
If Contributor Console is working fine then please close this one.

**Comment by ashav-github** [comment]
Marking as QA Done. For Corp Console Doc issue will report a separate ticket.

**Comment by vinod-kadam** [comment]
As updated by @pranab-bajpai, Admin Console & Corporate Console should also go to https://docs.linuxfoundation.org/lfx/v/v2/easycla
