### ISSUE TITLE
GitHub Repo's are duplicated giving Partial or no connection status on Repositories page of Admin Console

### ISSUE THREAD

**Issue by manishv09** [communitybridge/easycla#2345]
GitHub Repo's are duplicated giving Partial or no connection status on Repositories page of Admin Console
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/f4efaadc-6d57-4a48-952a-085ef04c8086)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/6a657d96-2e7d-41eb-ad50-ddfce8ec4360)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/139cee65-230d-440d-91b4-1f564e507fa8)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/4714f9a1-481a-49df-b24f-afcdd3365a6e)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/2910cc6b-95bf-448c-8308-f56a796956cd)

The GitHub Link for the Org is as follows:
https://github.com/Test-Staging-Repo001/Test-Staging-Repo-009
Breadcrumbs for the project as follows:
HOME / A-MANSTAGE FOUNDATION / A-MANSTAGE-PROJECT001 / TOOLS / CLA-TEST-STAGING-CLAGRP-001 / REPOSITORIES
Staging url: https://admin.staging.platform.linuxfoundation.org/apps/cla/project#id=a096s0000003lyhAAA

**Comment by rinkeshbhutwala** [comment]
@vinod-kadam @dealako I have verified the issue looks like that is a connection issue with GitHub I have done from my repo, as well as @manishv09, created repo it's working fine so moving this ticket to "Ready for QA".

**Comment by manishv09** [comment]
@dealako @vinod-kadam I tested this issue on DEV environment and added same organization to a different Project group and this time no duplicates were there. Also Checked the same Project group on Staging and found duplicates repo's are also not present.

As it is not reproducible on DEV environment, moving this ticket to QA Done.
