### ISSUE TITLE
On enrolling and unenrolling >=10 projects at a time throws network timeout error

### ISSUE THREAD

**Issue by ashav-github** [communitybridge/easycla#2346]
Test Data: Renault Foundation

Steps:

1. Have a project group with more than 10 projects.
2. Create a CLA group with one project.
3. On the CLA Overview page, enroll 10 projects at once OR unenroll 10 projects at once

Actual Result: It throws errors but on refreshing the page it shows the project enrolled/unenrolled correctly.
**Enrollment Error:**
error:"network timeout at: https://api-gw.staging.platform.linuxfoundation.org/cla-service/v4/cla-group/dd37ce0c-3793-4ea3-946d-572c4d19f75a/enroll-projects"

**Unenrollment Error:** 
error:"network timeout at: https://api-gw.staging.platform.linuxfoundation.org/cla-service/v4/cla-group/dd37ce0c-3793-4ea3-946d-572c4d19f75a/unenroll-projects"
errorLoggedTime:"Thu, Dec 17th 2020, 8:19:35 pm IST"

Expected Result: Error should not be thrown

![Stage-Unenroll-Project-Message.jpg](https://images.zenhubusercontent.com/5f6b335ce9044e3973ea11f9/22332f40-98fa-45a4-8846-2ecea11c0d37)

![Stage-Enroll-10-Projects-Error Message.jpg](https://images.zenhubusercontent.com/5f6b335ce9044e3973ea11f9/56801efa-aeab-4bfb-bf8f-b54326e0668b)

**Comment by vinod-kadam** [comment]
As updated by @tejasadg  in 18-Dec standup, he made the fix by increasing the api timeout to 30 seconds. He has tested the fix once and it works fine.

**Comment by ashav-github** [comment]
@tejasadg @vinod-kadam tested on Stage and I am still able to reproduce this issue:

![image.png](https://images.zenhubusercontent.com/5f6b335ce9044e3973ea11f9/fee560ec-63ef-4a72-a3e7-fd4f820c2c7e)

**Comment by ashav-github** [comment]
As @tejasadg informed that this fix is only on Dev now. I tested on Dev and it works fine. Error is not thrown. 
However, I observed that there is a delay of 15-20 secs on screen to apply the changes and till that time there is no way to know what is going on because the screen remains still.
Reported a separate bug for this on Jira:  https://jira.linuxfoundation.org/browse/LFX-2963
