### ISSUE TITLE
Red cross mark shown before LFX easyCLA logo even contributor has Covered.

### ISSUE THREAD

**Issue by amolsontakke3576** [communitybridge/easycla#2347]
![Screenshot from 2020-12-17 21-29-09.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/35f22754-a9a3-4da0-8470-b2ea72747c74)

**Comment by vinod-kadam** [comment]
Pranab to talk to Craig about it - red cross mark as well as alignment of covered in the box.

**Comment by dealako** [comment]
Obtained images from the design team:

![cla-notsigned_no_x.svg](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/b1ea27ba-e6a6-474e-a0bb-46a971a95ba5)
![cla-missing-id_no_x.svg](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/0b956bb0-497d-44b7-9979-de45f01ede9a)
![cla-confirmation-needed_no_x.svg](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/9b5f9294-99f2-4b5e-a519-1d97f1392f92)
![cla-signed_no_x.svg](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/a0c8f571-33d5-41eb-bb54-c60ada457fdb)

**Comment by dealako** [comment]
Updated images in DEV, STAGING, and PROD. Updated Python link to images - minor change to the not-signed image.  Pushed changes to DEV and STAGING.  Ready for test.

**Comment by manishv09** [comment]
Verified for Not Covered and Covered Statuses on DEV and Staging Environment. Please find the screencast as follows:
DEV Not Covered:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/c57141b2-176d-4c4d-a538-8d0d73d06d0b)

Staging Not Covered:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/5d207bb0-c016-4cbb-bf69-09459b230ba0)

DEV Covered:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/b778db05-937a-4113-9b2f-5121d5f2066b)

GitHub : https://github.com/A-Manish-Foundation/Project-001/pull/1

Staging Covered:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/0ab6def2-5aa4-4b30-8277-4e14fadeafff)

**Comment by vinod-kadam** [comment]
@manishv09  to re-execute on Dev with new PR.
@dealako  to add steps to execute the flows Missing ID on Commit & Confirmation Needed.

**Comment by manishv09** [comment]
Verified today for red cross when request is geted:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/124d61ab-b324-4552-807d-06023cc6dcf2)

**Comment by vinod-kadam** [comment]
@manishv09  as discussed, please create a separate ticket for verification of "Missing ID on Commit" and "Confirmation Needed" use cases - this one probably very rare one so mark Release as Post-EasyCLAv2Release and labelled it as tier-3.
And then you can mark this ticket as QA Done since the frequent use cases of "Covered" and "Not Covered" are verified and found to be working fine.
cc @dealako , @pranab-bajpai

**Comment by manishv09** [comment]
With reference to above comments, a separate ticket is being raised for verification of rare use cases.
https://app.zenhub.com/workspaces/easycla-5ed619832c71a855a76ef404/issues/communitybridge/easycla/2416
