### ISSUE TITLE
Clearbit Organization Name Validation

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#2351]
## Summary

Clearbit Organization Name Validation

## Background

When a contributor navigates to the v2 Contributor Console, selects the Corporate CLA workflow, and is unable to find their company, they are allowed to create a new company.  This form provides the company website and company name as input.  When the user provides the website and company name, the company name may be adjusted within the Organization Service based on the results of a Clearbit query to obtain the organization's legal name. Currently, this change of company name is done without notification to the user.  Subsequently, the user may have trouble identifying the Organization that was created.

## Tasks

1. Coordinate with the Organization service team - identify when the Clearbit API will be made available. Coordinate with @niravpatel27's team.
1. Define an EasyCLA v2 (/v4 endpoint) swagger spec, request, response, error models for a pass-thru API that allows the Contributor Console to query the Organization Service ClearBit organization website URL.  Allow this endpoint to pass through the API Gateway without authentication (API-GW config) since the v2 Contributor Console does not have a LF login session.
1. Update the v2 Contributor Console to query the new EasyCLA v2 endpoint on the create new organization web form.  When a user types in the website URL on the form (onBlur):
    1. the new endpoint will be invoked.
    1. If a matching website entry is found, the legal Organization name is returned.  The UI should add the Organization name into the Organization name input text box and mark the text box as read-only/not editable.
    1. If the website entry is NOT found the UI should make the organization name input text box editable allowing the user to input the Organization Name.

## Diagram

![Organization Name Validation.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/37a0e89a-69e1-4a8f-b83c-9d399dde635b)

## User Story

- As an EasyCLA contributor, I want the Contributor Console to fill in the appropriate organization legal name when the web site URL is provided.

## Acceptance Criteria

1. Demonstrate the set of capabilities to the product team while the code is running in the DEV environment.

## References

- None

**Comment by amolsontakke3576** [comment]
@dealako @vinod-kadam @pranab-bajpai I had a discussion with Prabodh and currently no such endpoint available at org-service. Prabodh will be going to discuss with @niravpatel27 and inform us final status.

**Comment by dealako** [comment]
Blocked until Clearbit service is made available by the Platform Organization Service team.

**Comment by vinod-kadam** [comment]
As updated by Prabodh, Core Service ticket for the API is as follows:
https://jira.linuxfoundation.org/browse/PMM-966
Prabodh is going to talk to Nirav about it in today's Core Services standup.

**Comment by vinod-kadam** [comment]
As discussed in the 18-Dec bug triage with @dealako , @kriva03 , @pranab-bajpai  & @niravpatel27, even though this ticket was initially marked for Post-EasyCLAv2Release it was felt that we should try to accomplish this ticket for the 1st EasyCLA release.

**Comment by vinod-kadam** [comment]
Below is update provided by @niravpatel27 on lfx-easycla slack channel.

Here is organization lookup endpoint for the UI https://api-gw.dev.platform.linuxfoundation.org/organization-service/v1/api-docs#tag/organizations
Its only deployed to DEV as testing has not been completed. It will be deployed to other environments once testing is done.

**Comment by amolsontakke3576** [comment]
@rinkeshbhutwala can you create the above endpoint without authorization?

**Comment by rinkeshbhutwala** [comment]
@vinod-kadam @amolsontakke3576 Below is the cla endpoint.
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/searchCompanyLookup

**Comment by vinod-kadam** [comment]
Available for QA testing on Dev env.

**Comment by dealako** [comment]
Held a conversation with Nirav via slack:

12/29/2020:
David: Regarding the Clearbit API - can we work to find partial matches? We have integrated into EasyCLA and it is working as expected, however, we are concerned that the user will type:

- https://lfcla.com => finds a match :white_check_mark:
- http://llfcla.com => does not find a match :x:
- lfcla.com => does not find a match :x:
- www.lfcla.com => does not find a match :x:

David: Can we strip the protocol and other non-domain name items from the provided website URL and then search for that???  Ideally, this will be done in the Org Service API

Update 01/04/2021 - Spoke to @niravpatel27. He will be updating the API endpoint to address several use-cases that came up when testing this feature:

```
David:
I wanted to follow up about the discussion above - ClearBit API to incorporate partial matches?  Are you considering updating the API to allow the above use-cases?

Nirav:
Yes, we will be releasing it this week. I will notify via slack channel

I am doing testing in a few mins.. but I am expecting the following combination will pass

- https://lfcla.com =>
- http://llfcla.com =>
- lfcla.com =>
- www.lfcla.com =>
```

**Comment by niravpatel27** [comment]
@dealako It's deployed to the Dev environment. I confirmed the following cases are supported and working. 

```
https://lfcla.com
http://lfcla.com
lfcla.com
www.lfcla.com
```

**Comment by amolsontakke3576** [comment]
@vinod-kadam Tested and works fine.

**Comment by vinod-kadam** [comment]
As updated by @amolsontakke3576, he has raised a PR for the situation when website is empty, don't make a call to clearbit api. He has raise a PR for it.

**Comment by manishv09** [comment]
Verified it again today and found working fine, please refer below screencast for more details:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/b74708db-fa04-4b2f-bfa8-a80bbc4b40c7)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/1f4ceb8d-b1b2-4002-ba8c-76a8750de8bd)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/99d11b9a-074f-4f81-bd19-67f421415250)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/958e0793-efa6-479d-94db-9a683e58aa7b)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/a2865d28-cb86-4094-be5d-d9c0f72f95c2)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/a2831cf3-1435-4fea-b139-1795d34b9b9b)
