### ISSUE TITLE
Fix Link in Email to potential CLA Manager v1

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2352]
## Summary
When an email is sent to a potential CLA Manager, the link to the corporate console is not correct.

## Background
A contributor comes from a pull request check and selects "corporate", "Company not in the list", "no", and sends the email to the person they designate as a cla manager. The link in the email the manager receives is bad.

![image](https://user-images.githubusercontent.com/46732999/102565749-16712b00-40ac-11eb-9f4d-b84079367774.png)

**Comment by wanyaland** [comment]
@amolsontakke3576 .. Payload for the above endpoint https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/requestCompanyAdmin has changed  and now requires version added to the payload detailing EasyCLA version which is either v1 or v2
Request Payload sample
 ```{
  "claManagerEmail": "user@linuxfoundation.org",
  "claManagerName": "Rinkesh Bhutwala",
  "companyName": "Linux Foundation",
  "contributorEmail": "user@linuxfoundation.org",
  "contributorName": "Harold Wanyama",
  "projectName": "OpenCue",
  "version": "v1"
} ```

**Comment by amolsontakke3576** [comment]
@wanyaland Sure I will make corresponding changes

**Comment by WillsonHG** [comment]
verified link is fixed in production
