### ISSUE TITLE
Corporate Console Link + New Menu changes

### ISSUE THREAD

**Issue by vinod-kadam** [communitybridge/easycla#2357]
## Summary

This ticket is to track Corporate Console's new menu changes.

## Background

Previously, the Contributor Console determined the Project type and dynamically built an inbound link for the Corporate Console.  This menu structure included the 'LF Supported' project grouping.  As a result of stakeholder feedback, this concept was abandoned/abolished.  Now, the Contributor Console link generation logic needs to account for this change as well.

Note: as discussed in bug triage, this is needed for 1st release. 

## Tasks

- [ ] Update the [corporate console link logic](https://github.com/communitybridge/easycla-contributor-console/blob/main/src/app/core/services/cla-contributor.service.ts#L196) to match the Corporate Console menu tree.

**Comment by vinod-kadam** [comment]
As updated by Sudhakar to Amol, LF%20Supported need to be replaced with SFID of The Linux Foundation.
e.g.
Earlier Link: https://lfx.dev.platform.linuxfoundation.org/foundation/LF%20Supported/project/a096s00000037emAAA/cla
New Link: https://lfx.dev.platform.linuxfoundation.org/foundation/a0941000002wBz9AAE/project/a096s00000037emAAA/cla

**Comment by vinod-kadam** [comment]
As updated by @wanyaland , he merged the PR to main so it got deployed to Dev env automatically.
So, moved to the ticket to Ready for QA.
@wanyaland  will check if it is deployed to Staging.

**Comment by manishv09** [comment]
Verified today on DEV environment and found working fine, please refer screencast below for reference:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/60ca1a6c-4171-482f-ba25-42e61df5203f)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/0ed28d20-315d-47bc-8e42-b2015c6c4cb3)
