### ISSUE TITLE
Replace CommunityBridge name on the v2 Contributor Console

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#2358]
## Summary

Replace CommunityBridge name on the v2 Corporate Console

## Background

After rebranding, we should have removed all references to CommunityBridge.  One reference still remains.

## Screenshots

![Screen Shot 2020-12-18 at 9.52.34 AM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/31563032-4404-4b15-8c3c-7a5dac546937)

## Environment

* Environment:
  - [x ] DEV
  - [ x] STAGING
  - [ x] PROD 

## Acceptance Criteria

1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

- Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by dealako** [comment]
Created PR: https://github.com/communitybridge/easycla-contributor-console/pull/162

Updated text says:

**Comment by manishv09** [comment]
Verified today and text is replaced with suggest one mentioned in above comment.
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/d8358d4b-3775-4ac0-8590-ca6429bfc4b2)
