### ISSUE TITLE
Staging: During CCLA when a new org is added and GH user identifies himself as a CLA Manager. Contributor console throws 400 error and spinner is keep on running

### ISSUE THREAD

**Issue by ashav-github** [communitybridge/easycla#2360]
Steps:

1. Have a PR which is gated
2. Click on it, select CCLA, enter a new org name which doesn't exists and identify yourself as CLA Manager.
3. Click Proceed

Actual Result: The spinner is keep on running and developer tool shows many 400 error.
![image.png](https://images.zenhubusercontent.com/5f6b335ce9044e3973ea11f9/982a8311-6e0e-4607-8e1d-3ce73720a8df)

Expected Result: CCLA sign-in process should work fine.

**Comment by wanyaland** [comment]
This is a regression issue on the platform API. The endpoint leverages the GET request for salesforce company and this is now returning an error response . On investigation the error thrown was 
```unable to get organization with params: &{DollarFilter:<nil> EmptyHeader: XREQUESTID:<nil> SalesforceID:0016s00000992XTAAY timeout:0 Context:context.Background HTTPClient:<nil> ```.  
This will be worked on by Yogesh according to communication held with Prabodh from the platform API service team.

**Comment by wanyaland** [comment]
I tested the use case with both Yogesh Chaudhari and ASHA VISHWAKARMA and this issue is not reproducible.

**Comment by dealako** [comment]
@ashav-github can we close this ticket?

**Comment by ashav-github** [comment]
@dealako @wanyaland This is working fine and issue is no more reproducible. Marking it as done.
