### ISSUE TITLE
While signing ICLA User email id / name doesn't appear on Docusign 

### ISSUE THREAD

**Issue by manishv09** [communitybridge/easycla#2361]
While signing ICLA User email id / name doesn't appear on Docusign and shows "Unknown"

![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/59e13727-d286-4730-b283-a8a5df0675a7)

**Comment by manishv09** [comment]
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/e4cb172f-fd79-4e64-9828-368d14f653bc)

**Comment by rinkeshbhutwala** [comment]
@vinod-kadam Verify this issue looks like it's a python side and @wanyaland made a change for CCLA so it's causing the issue on ICLA. Need to support for ICLA with GitHub-email or GitHub-username.

**Comment by dealako** [comment]
@ashav-github ready for QA

**Comment by manishv09** [comment]
Verified today and found working fine now, please refer screencast below:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/fdc03d93-9bd3-4ceb-9495-12daf9151f6e)
