### ISSUE TITLE
On Github curently there is no way to show the contributor that CCLA/ECLA/ICLA docs are signed/not-signed.

### ISSUE THREAD

**Issue by ashav-github** [communitybridge/easycla#2363]
As discussed with @dealako and @pranab-bajpai during 21-Dec Stand-up call, currently Github doesn't show any message/info. to the contributor the reason of gating and the status of signed/not-signed CCLA/ICLA/ECLA docs.

@pranab-bajpai to share the design/text for the same.

**Comment by dealako** [comment]
This feature has been completed in the v2. Signatures are shown that are incomplete, active and disabled. Both the company portal and the project control center can view/show the signatures.
