### ISSUE TITLE
Steve's Feedback - When designating someone else to be a CLA Manager in the contributor console, it doesn't allow a period ('.') in the name

### ISSUE THREAD

**Issue by ashav-github** [communitybridge/easycla#2366]
Reported by Steve:

Tier2 - 1C(2): When designating someone else to be a CLA Manager in the contributor console, it still prohibits a lot of things that would be valid names. For instance, someone whose name ends with “Jr.” would be prohibited because of the period at the end. Is there a reason we can’t just permit anything to be entered as a valid name?
This is also a problem with the screen where the CLA Manager Designee identifies the name and email address of the CLA Signatory.`

Expected Result: Period should be allowed in the name. @pranab-bajpai @dealako should it allow other special chars as well as mentioned by Steve: Is there a reason we can’t just permit anything to be entered as a valid name?

**Comment by ashav-github** [comment]
@amolsontakke3576 This has to be fixed on 2 places:
a) While adding CLA Manager Name on Contributor Console.
b) While adding CLA Signatory Name on Corporate Console.

**Comment by amolsontakke3576** [comment]
@ashav-github can you create a separate ticket for corporate console change?

**Comment by ashav-github** [comment]
@amolsontakke3576 Reported separate bug for corporate console: https://jira.linuxfoundation.org/browse/LFX-2984

As part of this ticket fix, did you allow only dot or other special chars as well as I asked in expected result ?

**Comment by manishv09** [comment]
I tried 3 CLA Manager names with 3 different combinations:
1. Hector's Sausage-Hausen.
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/2c22aa73-fe17-4c39-a4b1-db1974e2e095)
2. Hector's Sausage-Hausen
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/23033366-8e5c-4f7d-892b-eb3d1e345bc0)
3. Hector Sausage-Hausen
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/4515c286-e671-45d4-85c9-a6a84e2c3180)
All above 3 are working fine.

**Comment by amolsontakke3576** [comment]
@vinod-kadam below is the updated regex for cla manager
`^[a-zA-Z]+(([',. -][a-zA-Z ])?[a-zA-Z.]*)*$`
