### ISSUE TITLE
Steve's Feedback - Staging: Replace CommunityBridge name on the EasyCLA app on GitHub which has the name “STAGING CommunityBridge: EasyCLA”

### ISSUE THREAD

**Issue by ashav-github** [communitybridge/easycla#2367]
Reported by Steve:

Tier3 - 1A(4): The staging version of the EasyCLA app on GitHub has the name “STAGING CommunityBridge: EasyCLA”. Has “CommunityBridge” been changed to “LFX” for the production app?

Expected Result: @pranab-bajpai @dealako, please suggest the text. 

![Github-EasyCLA-App.jpg](https://images.zenhubusercontent.com/5f6b335ce9044e3973ea11f9/26f8f096-2307-478c-acd7-66d4a81dbfa6)

**Comment by vinod-kadam** [comment]
Assigned to @dealako  as this change is needed to be done the Github app which is installed in the Github - no one else knows how to do it.

**Comment by vinod-kadam** [comment]
As discussed in the standup, @dealako to review the impact of this change.

**Comment by dealako** [comment]
I recommend we defer any changes to the GitHub Bot naming scheme until a later date.  Changing the name of the GitHub App/Bot would change the URL/link to the bot.

- STAGING CommunityBridge: EasyCLA => https://github.com/organizations/LF-Engineering/settings/apps/staging-communitybridge-easycla
- STAGING LFX EasyCLA -> https://github.com/organizations/LF-Engineering/settings/apps/staging-lfx-easycla

This would break a number of things. We would need to assess the impact of this change and coordinate with the community GitHub organizations and repositories.

**Comment by vinod-kadam** [comment]
As details provided by @dealako, changing the name will need time & will need considerable testing. So, as updated by @pranab-bajpai marking it for Post-EasyCLAv2Release.

**Comment by mlehotskylf** [comment]
This is no longer applicable, closing.
