### ISSUE TITLE
Steve's Feedback - Staging: Admin Console->CLA Overview Page->Issues on Activity Log

### ISSUE THREAD

**Issue by ashav-github** [communitybridge/easycla#2369]
Reported by Steve:
https://docs.google.com/document/d/1RPrCH6U8RTFcBmdKEveUuXZhJt1QN-O7xpR99otAROA/edit#

Tier2 - 1A(8): A couple notes on the Activity Log:
1. It doesn’t appear to be recording the name of the person who performed certain actions -- note the missing name in the “Activity” and “Performed By” columns for rows 1, 2 and 4 in the screenshot below
2. For the 3rd row in the screenshot, instead of listing the random ID for the project, can it list the project name or some similar meaningful identifier?

![image.png](https://images.zenhubusercontent.com/5f6b335ce9044e3973ea11f9/1d20b070-3585-4cdd-b8be-757e985204f8)

3. Also seeing similar problems after signature of an ICLA:

![image.png](https://images.zenhubusercontent.com/5f6b335ce9044e3973ea11f9/d8083171-484a-4087-97c0-e0543b4663a9)

**Comment by vinod-kadam** [comment]
As updated by @tejasadg , for "Performed By", if user name (i.e. github username) is not there in the endpoint response then he made a change to use LF user name from the endpoint response.

**Comment by rinkeshbhutwala** [comment]
@vinod-kadam I have fixed the issue related to project SFID now it's showing project name instead of ID.
See the below-attached screenshot.

![Screenshot from 2020-12-23 18-29-27.png](https://images.zenhubusercontent.com/5f20ee93f9a45844ef8dfce5/91dcf95d-74f2-40da-ac52-54af24ba5ed1)

**Comment by manishv09** [comment]
"SFID" is replaced by Project Name, “Activity” and “Performed By” are appearing in activity log now, please refer below screencast:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/cfd254e3-76d6-456e-8835-86d25386fbe8)
