### ISSUE TITLE
Steve's Feedback - Staging: The email sent to the CLA Signatory lists the CLA group name in a few places, it should use project name rather than CLA group name.

### ISSUE THREAD

**Issue by ashav-github** [communitybridge/easycla#2372]
Reported by Steve(Ref doc:document https://docs.google.com/document/d/1RPrCH6U8RTFcBmdKEveUuXZhJt1QN-O7xpR99otAROA/edit#heading=h.cf1ae16ghz07:)
Tier3 - 1C(6): The email sent to the CLA Signatory lists the CLA group name in a few places, but calls it the “open source project”. This should probably use the name of the project itself rather than the CLA group name, since the CLA group name is more of an internal name:

Steps:

1. Login to Corporate console to sign CCLA
2. While signing CCLA, select someone else as CLA Signatory name
3. CLA Signatory will receive an email to sign the CLA
4. Observe the email content

Actual Result: The email sent to the CLA Signatory lists the CLA group name in a few places, but calls it the “open source project” calls it the “open source project”.
Example 1:
![image-2020-12-22-17-24-34-052.png](https://images.zenhubusercontent.com/5f6b335ce9044e3973ea11f9/d70a80ea-b1ce-4e20-aa3f-70f29715329f)

Example 2:
![CLA-SignatoryEmail.jpg](https://images.zenhubusercontent.com/5f6b335ce9044e3973ea11f9/fbb52a77-2f63-4c2b-8ef5-2de7d507467d)

Expected Result: This should probably use the name of the project itself rather than the CLA group name, since the CLA group name is more of an internal name.

**Comment by rinkeshbhutwala** [comment]
@vinod-kadam I have verified this ticket looks like we have used every where as cla-group if we have to change with project name then can you please confirm which project name we can select because we have multiple projects in one CLA group.

Can you please confirm on this one?

**Comment by dealako** [comment]
Let's get feedback from the Stakeholders.

**Comment by dealako** [comment]
Awaiting stakeholder feedback.

**Comment by vinod-kadam** [comment]
Assigned to @pranab-bajpai to follow up with stakeholder.

**Comment by vinod-kadam** [comment]
@pranab-bajpai to check today with stakeholders.

**Comment by vinod-kadam** [comment]
This was discussed over slack with stakeholders and as a result following ticket was created.
https://app.zenhub.com/workspaces/easycla-5ed619832c71a855a76ef404/issues/communitybridge/easycla/2441 
So, closing this ticket.
