### ISSUE TITLE
Steve's Feedback: Branch protection should automatically apply to all branches, including newly created branches.

### ISSUE THREAD

**Issue by ashav-github** [communitybridge/easycla#2374]
Reported by Steve (https://docs.google.com/document/d/1RPrCH6U8RTFcBmdKEveUuXZhJt1QN-O7xpR99otAROA/edit#):

Tier2 - 1A(9): Does branch protection automatically apply to all branches, including newly created branches? Or only to the “main” branch? It should apply to all branches, but I’m not sure that it is.

As mentioned by Pranab in the above mentioned doc 'If it does apply to newly created branches then the tool tip needs to be fixed.'

**Comment by vinod-kadam** [comment]
As updated by @ashav-github , @manishv09  is going to test whether branch protection is getting applied to all the branches.
Then Manish would also test for a newly added branch.

**Comment by dealako** [comment]
I provided a comment on the document:

> As designed, the branch protection applies only to the "default" branch as set by the repository owners (typically called the "master" or "main" branch). The "default" branch is generally considered the branch where most pull requests are merged.  We chose to limit the scope of this feature since large repositories may employ different merge strategies based on the software change control practices and policies.
> If we expand the scope of this to say, apply to all branches or apply to a subset, then we should evaluate the impact of this change - perhaps gather additional feedback from the community.
> I recommend limiting the scope of this feature to how it is currently implemented for the initial v2 launch

**Comment by dealako** [comment]
Given this is a feature change in scope and presented as a question in the document, I would consider this as a lower priority.

**Comment by vinod-kadam** [comment]
As updated by @manishv09  in 23-Dec standup, he has completed testing the use cases given in the branch protection test plan : https://confluence.linuxfoundation.org/display/PROD/EascyCLA-V2-+Enable+Branch+Protection+Test+Plan
He has completed testing the uses cases for the default branch & found the use cases working fine.

**Comment by vinod-kadam** [comment]
As updated by @pranab-bajpai , this will be Post-EasyCLAv2Release.

**Comment by mlehotskylf** [comment]
@nickmango @thakurveerendras I believe this can be closed.

**Comment by thakurveerendras** [comment]
It is working fine as expected, So closing this ticket
