### ISSUE TITLE
EasyCLA v2 UI - Demonstrate LFX Integration

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#238]
**Summary**

EasyCLA v2 UI - Demonstrate LFX Integration

**Background**

Provide context to the issue - provide steps to indicate how this feature would be realized, such as:
1. Package and build the EasyCLA v2 UI
1. Demonstrate EasyCLA "docked" within the Community Bridge LFX UI

**User Story**

A description from a user's perspective - e.g.:
As an EasyCLA administrator, when I log into the Community Bridge LFX UI, I see the EasyCLA tab with the content of a landing/splash page.

**Acceptance Criteria**

The "done" criteria when this feature or problem is resolved.  Such as:
1. User is able to log into the Community Bridge LFX UI and see the EasyCLA tab/content.

**References**
(Optional) Provide any code or specification references that would be helpful
for the developer implementing this feature.

**Comment by jpalmerLinuxFoundation** [comment]
![image](https://user-images.githubusercontent.com/51214959/65619077-1f487f00-df85-11e9-998e-1e8e5d487ef8.png)
