### ISSUE TITLE
Staging: CLA Group creation (at child project level) throws error if Admin has access to only the child project.

### ISSUE THREAD

**Issue by ashav-github** [communitybridge/easycla#2380]
Steps: 

1. Have a CPM role user who has access to only the child project in IAM. For ex: I have a foundation 'av foundation' having 3 childs 'av-childproj1, av-childproj2 and av-childproj3'. The cpm role user has given access to only av-childproj1

2. Login to Admin console and click on the child project->Tools->CLA

3. Click on '+Add new CLA group' button, enter cla group name, desc, select checkboxes

4. On the Edit/Review Template steps, fill the require detail and submit

Actual Result: It throws error:

error:"{"Code":"403","Message":"EasyCLA - 403 Forbidden - user ashav.lfstgadmin does not have access to create a CLA Group with project scope of: a096s0000003xV4AAI","x-request-id":"fb677d80-4517-11eb-9410-334a0d34d819"}"
errorLoggedTime:"Wed, Dec 23rd 2020, 5:41:26 pm IST"

![CLAGroup-Creation Fails.jpg](https://images.zenhubusercontent.com/5f6b335ce9044e3973ea11f9/5cad97f4-e037-4790-8487-83f144d62a3b)

Expected Result: CLA Group creation should be allowed.

**Comment by dealako** [comment]
@vinod-kadam Let's close this issue. As discussed during standup and our notes here, this is considered an error or invalid condition.
