### ISSUE TITLE
Organisation created with same name for different domain

### ISSUE THREAD

**Issue by amolsontakke3576** [communitybridge/easycla#2387]
When contributor tried to create a new organization with a completely new domain URL (website URL) and existing organization name it allows me to create it
Practically it should give me an error for `organization name already exist` 

![Screenshot from 2020-12-28 20-07-07.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/53adcfde-2360-4a92-b223-6124fe2312f5)

**Comment by vinod-kadam** [comment]
@amolsontakke3576  checked with Prabodh - Org Service is giving an error however CLA API is going ahead and creating the org.
@makkalot to look at it.

**Comment by vinod-kadam** [comment]
We marked it as Post-EasyCLAv2Release as this one an rare edge case.

**Comment by dealako** [comment]
I raised the topic with Nirav from the platform/SF perspective - awaiting feedback.

**Comment by dealako** [comment]
Closing this ticket due to lack of interest or rare edge-case.  The team relies on the platform services to identify and manage compan/org name conflicts associated with similar or different domains.
