### ISSUE TITLE
Changes for Gerrit Name regex pattern in v1 Project Console

### ISSUE THREAD

**Issue by vinod-kadam** [communitybridge/easycla#2392]
Identify in the v1 Project Console Gerrit Name regex pattern. Update it to match the PCC regex. If missing, please add. Add a tooltip to say: "Invalid Gerrit Name - allowed characters are: starts with alphanumeric, followed by alphanumeric, parentheses, brackets, period, comma, plus, minus, and underscore characters, min length 1, max length 99".

Note: this ticket was created out of LFX-2987.

**Comment by vinod-kadam** [comment]
This is merged to Dev so available for QA testing.

**Comment by dealako** [comment]
The old v1 console is deprecated and removed.
