### ISSUE TITLE
Sometime lookup endpoint failed to give proper result in absence of prototype.

### ISSUE THREAD

**Issue by amolsontakke3576** [communitybridge/easycla#2394]
Below are the example of a few domains and there results 

1. **websiteName=lfcla.com**
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company/lookup?websiteName=lfcla.com
{"Code":"404","Message":"EasyCLA - 404 Not Found - error occured while search orgname , websitename lfcla.com - error: [GET /v1/lookup][404] lookupNotFound  map[]","x-request-id":"15c51842-9776-448a-a604-4de569778954"}

2. **websiteName=https://www.lfcla.com**
https://api.dev.lfcla.com/v3/organization/search?websiteName=https://www.lfcla.com
Response :
{"Code":"404","Message":"EasyCLA - 404 Not Found - error occured while search orgname , websitename https://www.lfcla.com - error: [GET /v1/lookup][404] lookupNotFound  map[]","x-request-id":"681d0078-2bd0-4752-bbee-1318d61010be"}

3. **websiteName=https://lfcla.com**
`https://api.dev.lfcla.com/v3/organization/search?websiteName=https://lfcla.com`
Response :
{"list":[{"organization_id":"0012M00002NDacSQAT","organization_name":"cla linux","organization_website":"https://lfcla.com"}]}

**Comment by vinod-kadam** [comment]
This is a defect raised for #2351.

**Comment by dealako** [comment]
David Deal  11:54 AM
@niravpatel27 - Regarding the Clearbit API - can we work to find partial matches? We have integrated into EasyCLA and it is working as expected, however, we are concerned that the user will type:

- https://lfcla.com => finds a match :white_check_mark:
- http://llfcla.com => does not find a match :x:
- lfcla.com => does not find a match :x:
- www.lfcla.com => does not find a match :x:

Can we strip the protocol and other non-domain name items from the provided website URL and then search for that???  Ideally, this will be done in the Org Service API.

Nirav  12:19 PM on December 29th
Yeah let me see






Nirav  12:19 PM
Yeah let me see

**Comment by dealako** [comment]
Waiting for Organization Service updates to support partial searches.

**Comment by amolsontakke3576** [comment]
@vinod-kadam Resolved now so closing the ticket
