### ISSUE TITLE
v1 Project Console Signature View Issue

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#2402]
## Summary

v1 Project Console Signature View Issue

## Background

There appears to be an issue displaying the CLA signatures for the CFF project. Upon further investigation, some of the records are missing the `signatureCreated` record attribute.  As a result, the UI fails to parse the date/time value resulting in the following error:

```
ERROR TypeError: Cannot read property 'split' of undefined
    at cla-contract-view-signatures-modal.ts:142
    at Array.map (<anonymous>)
    at SafeSubscriber._next (cla-contract-view-signatures-modal.ts:140)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:238)
    at SafeSubscriber.next (Subscriber.js:185)
    at Subscriber._next (Subscriber.js:125)
    at Subscriber.next (Subscriber.js:89)
    at MapSubscriber._next (map.js:85)
    at MapSubscriber.Subscriber.next (Subscriber.js:89)
    at SwitchMapSubscriber.notifyNext (switchMap.js:126)
```

CloudFoundry.org Foundation, Inc.
[v1 Project Service Link](https://project.v1.easycla.lfx.linuxfoundation.org/#/project/a0941000002wBz5AAE/cla)

## Task

- Update UI code to handle missing values

## Expected behavior

Handle signatures with missing data.

## Screenshots

![Screen Shot 2021-01-04 at 3.03.01 PM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/302e9707-b760-4c3b-9939-fe0a28ecada2)

![Screen Shot 2021-01-04 at 3.03.11 PM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/4e955c10-2ba5-4507-98fa-1abbf3b09877)

## Environment

Please complete the following information:

* Environment:
  - [ ] DEV
  - [ ] STAGING
  - [x] PROD 
* Browser:
  - [x] Chrome/Brave
  - [ ] Firefox
  - [ ] Edge
  - [ ] Lynx
* Version: v1.0.XX

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

- Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by dealako** [comment]
Merged PR to DEV, ready for QA.

**Comment by dealako** [comment]
@amolsontakke3576 can you help resolve the issue of why the dates are not set in the data table?  Some values are present in the response object, in the signatureCreated attribute, but the values are not being shown on the table.

See: https://github.com/communitybridge/easycla/blob/main/cla-frontend-project-console/src/ionic/modals/cla-contract-view-signatures-modal/cla-contract-view-signatures-modal.ts#L152

**Comment by vinod-kadam** [comment]
As updated by @amolsontakke3576, he has raised the PR (minor typo issue). @wanyaland to review it.

**Comment by dealako** [comment]
Confirmed in PROD - issue is now resolved:

![Screen Shot 2021-01-05 at 7.53.05 AM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/8d851585-0717-49c0-8f9a-fb4c0a74ce0d)
