### ISSUE TITLE
ONAP SF Project ID Change script needed

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2404]
The ONAP project ID has changed from a0941000005ouJFAAY to a092M00001IV4BoQAL (The foundation ID for LF Networking did not change a094100000aErheAAC )

I do think we should change the project_id in the events tables because the old ID no longer exists as a project and we are changing the existing ONAP project ID, so we'll want to change it in all instances, even historical data. 

We need a script to go through the tables, find the old ID, and change it to the new ID in all fields applicable. A rough outline:

ccla-whitelist-requests - project_external_id
cla-manager-requests - project_external_id
companies - none
company-invites - none
events - event_data, event_summary, event_project_external_id, company_id_external_project_id, event_project_sfid
gerrit-instances - none
github-orgs - none
metrics (I don't quite understand this table, maybe we can skip) - project_sfid, external_project_id, salesforce_id, 
projects - date_modified, project_external_id, 
projects-cla-groups - project_sfid, 
repositories - none (it's a Gerrit project)
signatures - none
user-permissions - projects
users - none

**Comment by dealako** [comment]
@makkalot more details for you:

This is a one-off data migration where PM's have moved/renamed/migrated SalesForce data under a different Project SF ID.  Although this considered a one-off script, more of these data migration may come as a result of reorganizations, acquisitions, or mergers.  Thus, we can run this script when we are notified of such changes.

In addition to the above requirements:

- Develop an [easycla-tools](https://github.com/LF-Engineering/easycla-tools) python script to accomplish the data migration
- Script should accept the old SFID and the new SFID as command-line arguments
- Ensure it can run in DEV, STAGING, or PROD (like all the other scripts)
- This tool should have a `dry-run` mode that identifies the data files/records to migrate but does not perform the migration. This will allow the user to identify the impact before actually doing the migration.
- This tool should report a summary at the end of the migration (like many of our existing tools). The script should include a breakdown of the records updated in the variable tables.
- Run the linter before creating the PR to ensure we follow the coding standards

**Comment by vinod-kadam** [comment]
As discussed in the standup, this is not needed for the 1st easycla release.

**Comment by KennyPaul** [comment]
@dealako  said: _PM's have moved/renamed/migrated SalesForce data under a different Project SF ID_

If PM in this context means Program Manager, then for clarity I'm the ONAP PM and I did no such thing. Ever.   If it means something else then nevermind. :-)

@vinod-kadam said: _As discussed in the standup, this is not needed for the 1st easycla release_

All I know is that I no longer have access to EasyCLA for ONAP because something changed out from under me and I need that access restored.

Please and thank you!
-kenny

**Comment by WillsonHG** [comment]
This has been completed.
