### ISSUE TITLE
Script for CFF Github Organization and Repository Migration

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2407]
For the CFF migration to their new CLA group, we need a script that will take the current Github org and repository and move them to the new project id and salesforce id.

The current project id for CFF is eb1164b0-58c3-41f8-bb2a-8fd99f778f26
The current SFID for the project and the parent project is a0941000002wBz5AAE

This needs to be changed to the new project Id for Cloud Foundry - Series LLCs - ce29178c-2ecb-4666-943e-669652177144
The new SFID for project and foundation/parent is a092M00001IkUMrQAN

The tables affected will be:
github-orgs - organization_sfid, project_sfid
repositories - repository_project_id, repository_sfdc_id

projects-cla-groups does not have a listing for the new project, I am going to assume a row needs to be created for the new Cloud Foundry Series LLCs project.

**Comment by dealako** [comment]
Developed migration script and merged to easycla-tools repository. Ready to run when the CFF team is ready.

**Comment by WillsonHG** [comment]
This was run and the orgs and repos were updated successfully with no issues reported.
