### ISSUE TITLE
K8s Migration Enablement: Trigger EasyCLA checks on open PRs

### ISSUE THREAD

**Issue by jpalmerLinuxFoundation** [communitybridge/easycla#241]
**Summary**
In discussions with Kubernetes migrating to EasyCLA, they wanted EasyCLA to run its check on all open PRs (>1000). This is likely a blocker for the migration unless the check runs on open PRs already.

**Background**
When a contributor opens a PR, it is currently checked by CLABot v1.
After disabling the v1 webhooks and enabling EasyCLA GitHub App there will be thousand(s) of open PRs that need to be checked for CLAs.
The EasyCLA App only checks when the PR is opened.
We need a way to run the check on all open PRs.

**User Story**
As a repository manager,
I need all open PRs to go through a signed CLA check
so that I know that all contributors understand the implications and licensing of their contribution

**Acceptance Criteria**

The "done" criteria when this feature or problem is resolved.  Such as:
1. Unit Tests added and running in CI
2. Functional Tests updated to cover feature, if applicable
2. Demonstrate the set of capabilities to the product team while the code is
   running in the STAGING environment.

**References**
https://developer.github.com/v3/pulls/
_GET /repos/:owner/:repo/pulls_
**Parameters**
`state`: `open` (default value)

**Comment by jpalmerLinuxFoundation** [comment]
Considering the amount of time likely required to develop this feature, I think we need to consider alternatives:

I recommend that we use consider CLA v1 status checks valid for the pending PRs, if possible and only require EasyCLA checks on new PRs.

**Comment by dealako** [comment]
This request is asking for the following workflow:

1. develop an agent that could be triggered on a schedule or on-demand/manually
1. this agent would obtain a list of repositories for a given CLA Group
1. for each repository, get a list of open pull requests
1. for each pull request, run a check against the EasyCLA system. Based on the checks, update the pull request status.

**Comment by kriva03** [comment]
This is on the top of the priority from the list of features.

**Comment by dankohn** [comment]
This is no longer needed for Kubernetes according to @nikhita

**Comment by dealako** [comment]
Closing this issue during our backlog review. If additional help (be specific) is needed then please create a new ticket.
