### ISSUE TITLE
Verification required of "Missing ID on Commit" and "Confirmation Needed" use cases

### ISSUE THREAD

**Issue by manishv09** [communitybridge/easycla#2416]
A separate ticket for verification of "Missing ID on Commit" and "Confirmation Needed" use cases - this one probably very rare one, the frequent use cases of "Covered" and "Not Covered" are verified and found to be working fine. Please refer below ticket for information
https://app.zenhub.com/workspaces/easycla-5ed619832c71a855a76ef404/issues/communitybridge/easycla/2347

Please refer attached screenshot share by @dealako for reference.

**Comment by manishv09** [comment]
![EASYCLA-IMAGES-01.svg](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/3e0c2f89-97fd-40e0-8fa2-62788e413eb0)

**Comment by dealako** [comment]
This feature is completed. Won't fix. Out of scope of current product requirements/features.
