### ISSUE TITLE
V2 Production - Identify Authorized Signatory form does not accept a last name. (LFX-3013)

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2428]
## Summary

In the Corporate console, when a CLA Manager selects to send the CLA to the Signatory, the "Name" field in the form does not accept a last name, only a first name. 

![image](https://user-images.githubusercontent.com/46732999/104200880-27853180-53f7-11eb-8287-2f2aea09dc0c.png)

**Comment by sudhakar-proxima** [comment]
@WillsonHG are there any leading SPACE characters? irrespective, this should be fixed on corporate console.

**Comment by WillsonHG** [comment]
no leading spaces @sudhakar-proxima

**Comment by sudhakar-proxima** [comment]
LFX-3013 is created for tracking this.

**Comment by vinod-kadam** [comment]
Sudhakar has created a ticket in JIRA LFX board to fix this issue - that ticket is 
https://jira.linuxfoundation.org/browse/LFX-3013

**Comment by sudhakar-proxima** [comment]
Deployed to Dev & Staging. Will make prod release after the issues are verified.

**Comment by manishv09** [comment]
Verified on DEV environment and found working fine now. Please refer to the screencast attached for reference.[https://app.zenhub.com/files/194341141/6dda8ae1-0fc8-4960-9069-34b739cf6a68/download](https://app.zenhub.com/files/194341141/6dda8ae1-0fc8-4960-9069-34b739cf6a68/download)

**Comment by manishv09** [comment]
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/5f9bd289-7c4d-41b3-9899-b3f58c1e373b)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/bd8667f9-5a31-4413-800d-98c3ed8eed4d)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/41308d52-f3c2-4560-bd9e-05157fc1b04a)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/2420dfee-d428-41c8-9218-bd659c2bf057)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/1542d2c4-fadc-41de-80a2-7d38e1eda09b)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/38953dc7-4f90-47ba-8e1b-2e80a5b8cc08)

**Comment by WillsonHG** [comment]
verified this is fixed in production.
