### ISSUE TITLE
Stakeholder feedback: Add Signing Entity Name in Create New Organization work flow

### ISSUE THREAD

**Issue by vinod-kadam** [communitybridge/easycla#2429]
Following change is based on Legal Stakeholders - the change is for Create New Organization work flow.
![image.png](https://images.zenhubusercontent.com/5e9e9952b186e1325cf5608a/7320e9b5-a1d2-415d-b283-d7c52eae4b4f)

The response model from the search will include Entity Name values (list or CSV). We will need to provide the Entity name when we create/update the Company and also need to pass the user specified Entity value to the EasyCLA API for DocuSign.

UI design for Create New Organization:
https://wireframepro.mockflow.com/view/app-easycla#/page/D92ee4ed2a0017ba65d7cf2f149dcd399

**Comment by vinod-kadam** [comment]
Corresponding CLA backend ticket is as follows:
https://app.zenhub.com/workspaces/easycla-5ed619832c71a855a76ef404/issues/communitybridge/easycla/2435

**Comment by vinod-kadam** [comment]
Manish is testing this one on Staging.
Test cases & result: https://confluence.linuxfoundation.org/display/PROD/Contributor+Console+-+Signing+Entity+Name+Test+Cases

**Comment by manishv09** [comment]
Verification is done on dev and staging environment and found working fine except few of the cases wherein the roles assignment issues are observed because of which e2e verification is yet to be achieved. 
Open issues are #2455, #2463, #2468, #2460, #2462

**Comment by manishv09** [comment]
Verified today on DEV environment and found working fine except the emails which we need change. Please find attached the videos created while verification the new changes for Add signing entity name and corporate console page.

https://images.zenhubusercontent.com/194341141/b318303e-b890-4eed-874e-9afba4592b6e/singingnewcontriworlflow_02022021.mp4
https://images.zenhubusercontent.com/194341141/d090ab73-c4d3-4246-bd94-3847a0eaf173/signingnewclamgrdesig_02022021.mp4
https://images.zenhubusercontent.com/194341141/a2b7449e-8670-40f5-b4ef-c783e66c20ae/signingnewcorpworkflow_02022021.mp4
https://images.zenhubusercontent.com/194341141/cd1fa467-5c90-43a5-aa4a-a3edba1fc619/signingnewcorpclamgdesi_clasigna_02022021.mp4

**Comment by vinod-kadam** [comment]
Closing this ticket since it was updated on 2-Feb that signing entity name will not be shown on the UI anywhere - system will return to its old behavior.
