### ISSUE TITLE
V2 Production - No email sent to CLA Signatory

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2430]
## Summary
When a CLA Manager selects "no" to send an email to an authorized signer for their company, the dialog box says the email was sent, but no email was delivered. There is no record in Mandrill of the email being sent.

**Comment by wanyaland** [comment]
Currently blocked by ```requestCorporateSignature: {code: 400, message: "Post "/v1/request-corporate-signature": unsupported protocol scheme """,…}
code: 400
data: null
message: "Post "/v1/request-corporate-signature": unsupported protocol scheme """
success: false
__typename: "RequestCorporateSignatureResult" ``` response. It appears the api_base_url was not passed in the request for this use cas

**Comment by vinod-kadam** [comment]
David to syncup with Harold.

**Comment by WillsonHG** [comment]
Now I am getting:
![image](https://user-images.githubusercontent.com/46732999/104668399-ff6f2a00-56a5-11eb-9258-93eaf9121c69.png)

In the console the response:
{"data":{"requestCorporateSignature":{"code":400,"message":"[POST /v1/orgs/{salesforceID}/scopes][400] createOrgUsrRoleScopesBadRequest  &{Code:400 Message:organization-service - usernames: non zero value required XRequestID:f0b6c160-56cf-11eb-b583-697c69266abd}","success":false,"data":null,"__typename":"RequestCorporateSignatureResult"}}}

**Comment by WillsonHG** [comment]
When sent to hwillson+signatory2, a confirmation box that an email was sent, but still no email received.

**Comment by WillsonHG** [comment]
I also tried sending this to a signatory email with gmail so as to not cause any conflict with assigning the LF employee role. Same result. The email never arrived.

**Comment by vinod-kadam** [comment]
@dealako , fyi.. Asha checked this one on Staging and it working fine there.

**Comment by wanyaland** [comment]
Tested this in dev and received an email however there was a slight delay in receiving the email . Currently dont have access to prod projects for test purposes

**Comment by dealako** [comment]
@WillsonHG and I tested in PROD - observed successful email:

![Screen Shot 2021-01-26 at 1.53.19 PM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/20b169e9-d008-4114-ad47-3afb420e6269)

![Screen Shot 2021-01-26 at 1.53.31 PM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/aaad8a94-6ea9-44a6-b064-9a16f8f50c32)

**Comment by dealako** [comment]
@vinod-kadam - I recommend we either re-test one more time and/or close and possibly re-open if this pops up again.

**Comment by WillsonHG** [comment]
I have verified on production today that I received an email both to the signatory with an email/user in the system, and one without a user in the system.
