### ISSUE TITLE
V2 Production - Popup has "Whitelist" in it. (LFX-3014)

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2431]
## Summary

When a cla manager goes to sign a CCLA for a project, the popup still has the term "Whitelist".

![image](https://user-images.githubusercontent.com/46732999/104201690-05d87a00-53f8-11eb-8c94-adb4c225f61c.png)

**Comment by dealako** [comment]
Assigned to Sudukar and Corporate Console team.

**Comment by vinod-kadam** [comment]
Sudhakar created ticket in JIRA LFX board https://jira.linuxfoundation.org/browse/LFX-3014 to fix this issue.

**Comment by sudhakar-proxima** [comment]
Deployed to Dev & Staging. Will make prod release after the issues are verified.

**Comment by manishv09** [comment]
Verified it on DEV environment and found working fine now:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/4bd193d0-52aa-4b7f-a5e2-f08130896dd2)

**Comment by WillsonHG** [comment]
Verified the fix is in produciton.
