### ISSUE TITLE
"CCLA is not enabled to this project please contact to your administrator." error message is shown for every request on contributor console

### ISSUE THREAD

**Issue by manishv09** [communitybridge/easycla#2437]
"CCLA is not enabled to this project please contact to your administrator." error message is shown for every request on contributor console
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/b5066fb7-c1f9-46c6-a113-db3f155aa1ae)

**Comment by manishv09** [comment]
Same issue is observed on stage environment as well, please refer the screencast below:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/fc9de2c3-ad80-45e0-b57f-39770c4ef03a)

**Comment by amolsontakke3576** [comment]
it looks like the issue is with security headers, I have added below API base URLs in the whitelist.
'https://api.lfcla.staging.platform.linuxfoundation.org/',
'https://api.lfcla.dev.platform.linuxfoundation.org/'

**Comment by vinod-kadam** [comment]
As updated by Manish, it is verified for both Dev & Staging. So, moved the ticket to QA Done.
