### ISSUE TITLE
Conflict assigning cla manager role for Project error appears when user start the cla process

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#2439]
Steps:
1. Login corporates console 
2. Search & open project say : Veer project Staging 01
3. Click on easyCLA 
4. Click on **Start the cla Process** button
5. Click on Yes at "No Signed CLA Found" prompt
See-Activity CLAS for my account section appears
6. Now search & open easyCLA page of another project
7. Reopen easyCLA of project Veer project Staging 01
8. Now click on  **Start the cla Process** button then Yes

Actual Results :Conflict assigning cla manager role for Project error appears

Refer video clip for more details : https://images.zenhubusercontent.com/194341141/515d2252-41d4-416a-a7bf-5fd9444f7769/conflicterror.mp4

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/6c53fac8-ef89-4765-8a74-b2a84d1732af)

**Comment by dealako** [comment]
Updated logic to not fail on conflict/409 when the role is already set.  Will create PR shortly.

**Comment by vinod-kadam** [comment]
This should be available on Dev, Staging & PROD.

**Comment by thakurveerendras** [comment]
Issue is tested on Dev & staging site & found that issue is not reproducible , So making issue status to QA-Passed

Refer video clip for more details

https://images.zenhubusercontent.com/194341141/20411052-c103-4049-9e17-08c0d1c3c27b/2439_dev.mp4
https://images.zenhubusercontent.com/194341141/34e23398-6938-4780-8223-504a9719f1f8/2439.mp4
