### ISSUE TITLE
Include Project Name in Emails sent from CLA System

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#2441]
When sending emails to CLA Signatory, CLA Manager Invite, CLA Manager Designee Invite, update to CLA Manager List and update to approval list.
- [ ] Please use the CLA Group name and Project name for which you are sending the email.
- [ ] If it is a CLA group with multiple child projects use the parent (i.e. Foundation) project name. 
 Currently we just show the CLA Group name as in the image below
![image](https://user-images.githubusercontent.com/57362064/104344240-84015300-54c2-11eb-8425-839b5e71ad48.png)

Origin ticket: https://app.zenhub.com/workspaces/easycla-5ed619832c71a855a76ef404/issues/communitybridge/easycla/2372

**Comment by vinod-kadam** [comment]
As discussed in the SOS, this is not a release blocker.

**Comment by vinod-kadam** [comment]
This is deployed to DEV, Staging & PROD.

**Comment by makkalot** [comment]
The change was applied to CLA Signatory, CLA Manager Invite, CLA Manager Designee Invite, update to CLA Manager List and update to approval list.

**Comment by manishv09** [comment]
1. EasyCLA: Invitation to Sign the proxima Corporate CLA and add to approved list 
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/2439b4c7-edc1-4bbe-a999-5f6c4df10968)
2. EasyCLA: CLA Signature Request for A-Feb-10 Multi Level Projects-CHLD003
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/b0abe619-e499-4606-930e-7a07850adbc6

**Comment by manishv09** [comment]
Verified for following roles:
Verified on Staging today and found changes are getting reflected. Please follows below emails for reference:
1. CLA Manager
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/36a42045-6c3e-4bd4-8b0b-f6882e7f0e81)
2. CLA Signatory
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/9f1689e8-33b
7-448a-b5fe-49fbbad4fff5)
3. CLA Manager Designee
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/26a297cd-054e-48f2-8c9e-f114d1726358)

**Comment by manishv09** [comment]
4. Added as CLA Manager for Project
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/51cccd9c-3a82-4a62-b5f1-c1fc4f1a7bd2)
5. CLA Manager Added Notice
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/214ac256-56b8-4648-9eb9-ffc000f9af1b)
6. Approval List Update 
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/22b8432a-8931-412b-8b14-cf3a233ed4e4)
