### ISSUE TITLE
Getting error "CLA System is not able to support your request. Please Click here to open a support ticket." while signing CCLA

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#2443]
Reported by @manishv

Getting error "CLA System is not able to support your request. Please Click here to open a support ticket." while signing CCLA

> curl --location --request POST 'https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/request-corporate-signature' \
--header 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlJFWTNSVGcyTTBVMk5URTRSamcwTUVRNU9VSkZRMFpGTVVGRVJUaEVRVVF5TTBZeVF6QXhOQSJ9.eyJodHRwczovL3Nzby5saW51eGZvdW5kYXRpb24ub3JnL2NsYWltcy91c2VybmFtZSI6ImpvaG5kb2UyIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZU5ldyIsIm5pY2tuYW1lIjoiam9obmRvZTIiLCJuYW1lIjoiSm9obiBEb2VOZXciLCJwaWN0dXJlIjoiaHR0cHM6Ly9wbGF0Zm9ybS1sb2dvcy1teXByb2ZpbGUtYXBpLWRldi5zMy51cy1lYXN0LTIuYW1hem9uYXdzLmNvbS9qb2huLmRvZTEuMTU5OTQ2Mzc1MTE2OS5wbmciLCJ1cGRhdGVkX2F0IjoiMjAyMS0wMS0xM1QwODozNTozNi4xOThaIiwiZW1haWwiOiJzdWRoYWthcitqZG9lQHByb3hpbWFiaXouY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImlzcyI6Imh0dHBzOi8vbGludXhmb3VuZGF0aW9uLWRldi5hdXRoMC5jb20vIiwic3ViIjoiYXV0aDB8am9obmRvZTIiLCJhdWQiOiJxSUU0Tk1OcU9pdjY3MDZ0Rzl6eWdzZ3B3NFM3ZFJsMyIsImlhdCI6MTYxMDUyNzM5MSwiZXhwIjoxNjEwNTYzMzkxLCJub25jZSI6IlRHRkhRMkl3YmkxVmIwNDVjVk5FVkdKbWMyUkRXbHBGVVhZelZtRkhPRnAzTGpCT1pFRmFTVTAxWmc9PSJ9.DuC3Kv0lrXswxG_tqpqfu8YzFtPHE90soEN5aU6I7yt7klgG8yqgjQpeuts5-imPBg2-v1TQ5Ws6so8BrclUcp__7uhV3-Dg9ayEDdGF4J9Ys4QqsXTTonTrZ0YMnXUIgjpBOAwymknVhPZFWMkKn7Uv8tt1TAndCA1CeAG5tIqfoHZLfT8auTQzDKlr5d1weuACDHN0t0Q_7f8oQjr9umUQDAQRL_QJstXYNuCxhMvevZD0e-hmJJ9t3trFrh7mIYi8Guwdz50zqUAhJLsoftidSAz_xmUADZQyrw4APEEzfv5oay6xnaw1Te0WeW0uDzs7p20Tou3luzrBS_avnA' \
--header 'Content-Type: application/json' \
--data-raw '{
    "authority_email": "sudhakar+jdoe@proximabiz.com",
    "authority_name": "John DoeNew",
    "company_sfid": "0012M00002OugBpQAJ",
    "project_sfid": "a096s0000003l26AAA",
    "return_url": "https://lfx.dev.platform.linuxfoundation.org/foundation/a096s0000003iRnAAI/project/a096s0000003l26AAA/cla?cclaSigned=true",
    "send_as_email": false
}'
{
    "Message": "Post \"/v1/request-corporate-signature\": unsupported protocol scheme \"\"",
    "x-request-id": "e1a767d0-5588-11eb-bb55-41453cecede6"
}

![image-2021-01-13-16-12-21-675.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/c326b869-a116-4bf0-ba48-4efa7fc3aefe)

![image (3).png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/2833b9c0-36e2-4a4d-8b17-d9d18f0c0723)

**Comment by tejasadg** [comment]
Verified on dev
![Screenshot from 2021-01-14 17-13-59.png](https://images.zenhubusercontent.com/5ef5dcf0c63b2d6363eb509d/112ff9c8-b178-4875-8f4b-69c8b203ee74)

Verified on staging
![Screenshot from 2021-01-14 18-22-16.png](https://images.zenhubusercontent.com/5ef5dcf0c63b2d6363eb509d/154f8e1d-0e3a-4bce-85f7-bd8b29e9d45f)

cc: @vinod-kadam
