### ISSUE TITLE
Allow special character for Organization name but don't allow html injection

### ISSUE THREAD

**Issue by vinod-kadam** [communitybridge/easycla#2449]
Org Service has made a change on their side - it now all allows any character for Org Name however doesn't allow html injection <.+?>
So, we need to make a similar change on Contributor Console V2 for Organization Name - allow special chars but don't allow html injection (<.+?>).

Note: Amol, please get the exact regex from Sourabh.
David has made the CLA backend change and deployed.

**Comment by vinod-kadam** [comment]
As updated by @amolsontakke3576  in the standup, he has raised a PR for this one.

**Comment by thakurveerendras** [comment]
Issue is tested on dev & staging environment & found that special character are allowed for Organization name and **html injection are not allowed** as expected, So making issue status to QA-Done

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/b291d73f-c42b-4fe3-a70d-0daea642723b)
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/43f659ae-a019-447a-9137-db71731da259)

Refer video clip for more details : 
https://images.zenhubusercontent.com/194341141/e44d9e90-0771-4841-9416-e3f43ea1fab2/easycla2449.mp4
