### ISSUE TITLE
Organization name search and autofill on Create New Organization is not working as expected also messages needs to be changed

### ISSUE THREAD

**Issue by manishv09** [communitybridge/easycla#2450]
Organization name search and autofill on Create New Organization is not working as expected also messages needs to be changed

https://images.zenhubusercontent.com/194341141/523e7eef-b609-443c-8db1-980100f553b8/orgsearch_autofill_issues.mp4![image (6).png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/3f0a7508-e50d-44cb-a143-05432c7b5c4a)

**Comment by vinod-kadam** [comment]
Approach decided on 14-Jan to resolve this is as follows:
Initially keep org name disabled in create new org dialog, enable it only if org-service/clearbit api doesn't return valid value.

**Comment by manishv09** [comment]
Verified today on found search and auto fill is working fine now and also user is able to select from multiple options suggested to him for selection. Please find attached video for your reference.
https://images.zenhubusercontent.com/194341141/44c4356c-d541-4220-b9ba-16cda0927451/orgsearch_autofill_18012021.mp4
