### ISSUE TITLE
If website is found by clearbit validation should not take place as valid website is found

### ISSUE THREAD

**Issue by manishv09** [communitybridge/easycla#2454]
If website is found by clearbit validation should not take place as valid website is found

![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/494c7088-db4a-4ee1-a9dc-0c2d5912d63d)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/fec32a54-4428-4b92-96ee-3eed2ce0a792)

**Comment by manishv09** [comment]
Now the search is not taking place post the error fix. Please refer the screencast for your reference.
https://images.zenhubusercontent.com/194341141/f4561099-10fe-466f-9188-1e306c7b9ffc/nosearch_2454.mp4

**Comment by vinod-kadam** [comment]
As updated by @amolsontakke3576 , there was one file change which didn't get merged which gave rise to this issue. Now, that change has been merged and is available on Dev. So, QA can verify on Dev now.

**Comment by manishv09** [comment]
Verified today on DEV and found it is working fine now. Please refer the attached screencast for more information.

https://images.zenhubusercontent.com/194341141/a889f9ff-d266-4de7-aaa0-245be73dc87e/bug_2454_19_01_2021.mp4

**Comment by vinod-kadam** [comment]
This is now available on Staging & PROD.

**Comment by thakurveerendras** [comment]
Issue is tested on staging environment & found that it working fine as expected, So making issue status to QA-Done

https://images.zenhubusercontent.com/194341141/ed5fdac1-807e-4859-8954-ad332dad3e59/easycla2454.mp4
