### ISSUE TITLE
Identify CLA Manager box has "communitybridge" reference

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2458]
As a contributor who's company has not signed a cla for the project:

1. create a PR and get gated by Easycla
1. Choose Corporate
1. Choose 'no' you are not a cla manager
1. See "CommunityBridge Company Admin" in box.

![image](https://user-images.githubusercontent.com/46732999/104665677-fd09d180-569f-11eb-98f0-7419ae6ba728.png)

Please change to "LFX Company Admin".

**Comment by dealako** [comment]
Created PR: https://github.com/communitybridge/easycla-contributor-console/pull/181

**Comment by dealako** [comment]
Merged PR - ready for QA in DEV.

**Comment by manishv09** [comment]
Verified today and found the text is changed as per suggestion on staging environment. Please refer screencast below:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/69683e15-d84a-42ed-a85b-cc0a24ee0f83)

**Comment by vinod-kadam** [comment]
Deployed to Staging & PROD.

**Comment by WillsonHG** [comment]
Verified this is fixed in prod.
