### ISSUE TITLE
Organization already exit error message is being encountered to the user when tried to create Organization using website as "Yahoo.co.uk"

### ISSUE THREAD

**Issue by manishv09** [communitybridge/easycla#2462]
Organization already exit error message is being encountered to the user when tried to create Organization using website as "Yahoo.co.uk"

![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/7f89b9a0-c9ed-4cab-a310-ad0b452628bc)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/d7820000-a2f0-42dc-91f2-ca7b9e7054b8)

**Comment by amolsontakke3576** [comment]
Request URL: https://api-gw.staging.platform.linuxfoundation.org/cla-service/v4/user/843398e1-28e0-4a42-98b9-b69d1988b237/company

Request Method: POST
Status Code: 409 

Response 
{"Message":"organization already exists","x-request-id":"749acf33-d03a-4cbd-88a0-e07905bea445"}

**Comment by manishv09** [comment]
As comments received from **"@Sourabh Bhardwaj" from Org Service team** are as follows:
We already have the organization name in the DB https://linuxfoundation--dev.lightning.force.com/lightning/r/Account/0017c00000lMJ9zAAG/view
FYI: Organization service staging is pointing to Salesforce dev.

**Comment by vinod-kadam** [comment]
This ticket is dependent on https://jira.linuxfoundation.org/browse/OS-24.
Once OS-24 is implemented and deployed then make following change:
If org service returns Org SFID then call PATCH however if Org SFID is not returned (or returned null/empty/blank) then call PUT.

**Comment by vinod-kadam** [comment]
As updated by @manishv09 , this working fine now on Dev.

**Comment by vinod-kadam** [comment]
Closed this ticket since it was updated on 2-Feb that signing entity name will not be shown on the UI anywhere - system will return to its old behavior.
