### ISSUE TITLE
While creating new organization, if the new org doesn't exist in sfdc and clearbit, on clicking next button it goes back to the Select Organization page

### ISSUE THREAD

**Issue by ashav-github** [communitybridge/easycla#2464]
Steps:

1. Have a PR which is gated
2. Click on 'Not Covered' and select CCLA
3. Go to Create New Org page and enter an org url which doesn't exist on sfdc and clearbit, add org name and entity name, click on Next button.

Actual Result: The page goes back to the Select Org. screen and console shows 404 errors.

![image.png](https://images.zenhubusercontent.com/5f6b335ce9044e3973ea11f9/9d5bad54-814f-48f1-9cb0-fd6193fa2256)

Expected Result: On clicking next, it should go to 'CLA Not Found' page

**Comment by vinod-kadam** [comment]
As per release notes https://github.com/communitybridge/easycla-contributor-console/releases/tag/v1.0.34 this has been deployed to Dev, Staging & PROD.

**Comment by ashav-github** [comment]
Tested on Stage and it works fine.
