### ISSUE TITLE
Landing page changes for V1 to V2 migration - changes for Proceed buttons

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#2465]
- [ ] Here is the wireframe for V1/V2 redirection from landing page. 
https://wireframepro.mockflow.com/view/platform-style-guide#/page/Dfcc3e0be0361ae66dbf30f238a7814ad
- [ ] User will still click on the proceed button and that will open the dialog box which will give the user an option to choose between V1 and V2.
- [ ] If you already know that the user is coming from V1 or V2 you can put that logic and not show this option. Wherever you don't know what version the user is in, you should show this option.
- [ ] In the design where you have to show the text use the following text
        EasyCLA v1 - Choose this option for projects that have an existing CLA setup and have not been migrated to v2.  The v1 interface and APIs are not integrated into the LFX platform.
        EasyCLA v2 - Choose this option for projects that have recently been setup with a CLA or existing projects that have been migrated from v1.   The v2 interface and APIs are fully integrated into the LFX platform including a centralized single sign-on system with profile management, easy access to other LFX platform tools, and a refined user experience.

**Comment by dealako** [comment]
@pranab-bajpai - just to clarify on the new wireframe, what is the text that @amolsontakke3576 should add below the options (by the info icon) and above the Proceed button? This seems to be a placeholder for some meaningful text.

**Comment by vinod-kadam** [comment]
There is a separate ticket logged 2492 for the case of user coming from GitHub.
Manish confirmed that except for 2492, everything else is working fine.
So, marking this ticket as QA Done.
