### ISSUE TITLE
Contributor Console - During CCLA signup when user creates new org, elects himself as CLA Mgr. and creates a new LFID. After email verification it says 'Your session expired. Please try to log in again' and it doesn't redirects to corporate console.

### ISSUE THREAD

**Issue by ashav-github** [communitybridge/easycla#2468]
Steps:

   1. Create a PR, click on 'Not Covered', select CCLA, go to Create New Org., enter a new org. which doesn't exist on sfdc and clearbit.

    2. Complete the flow till creating new LFID.

    3. On the same browser open your email and verify email for newly created LFID.

Actual Result: It says 'Your session expired. Please try to log in again.'

![image.png](https://images.zenhubusercontent.com/5f6b335ce9044e3973ea11f9/713db9d6-21be-4111-b0d5-31b30e6d7179)

Expected Result: It should redirect to corporate console.

**Comment by ashav-github** [comment]
If I login on the same page with the same credential which I just verified, it says access_denied

![image.png](https://images.zenhubusercontent.com/5f6b335ce9044e3973ea11f9/d9a3ca52-b82a-44ed-b5f1-51aa4199ae9f)

**Comment by ashav-github** [comment]
I also observed that company association doesn't happen with LFID + CLA Manager role is also not assigned

**Comment by vinod-kadam** [comment]
Manish/Tejas/Veerendra tried around 10/2/1 times creation of new users respectively on Staging & it worked fine. We didn't encountered this issue. So marking it as QA Done however we will keep a watch on it.
