### ISSUE TITLE
Browser suggestion on Search Org. hides the suggestion from Org services

### ISSUE THREAD

**Issue by ashav-github** [communitybridge/easycla#2472]
Steps:

1. Have a PR which is gated
2. Click on 'Not Covered'
3. Search for an existing org. which you have already searched multiple times earlier

Actual Result: On typing existing org name, browser suggestion appears and on selecting browser suggestion it throws error message 'Could not find any matching organization.'. If you click on ESC button from keyboard, browser suggestion goes off and Org Service suggestion appears. 

![Browser-Suggestion.jpg](https://images.zenhubusercontent.com/5f6b335ce9044e3973ea11f9/b85f8e11-46ac-4df5-9204-285bacbc21ae)

Expected Result: Browser suggestion should not appear on typing org name because it can be confusing for users.

**Comment by ashav-github** [comment]
Please find below the videos:

https://images.zenhubusercontent.com/194341141/02dcd158-18b4-4790-8282-643410e28200/browsersuggestion.mp4

**Comment by vinod-kadam** [comment]
This is good to have as it will avoid confusion to the user. Even though we marked it as Post-EasyCLAv2Release we will work on it to get it fix.

**Comment by thakurveerendras** [comment]
Hi @amolsontakke3576 & @vinod-kadam 

Issue is tested on staging environment & found that it working fine,

Refer video clip for more details
https://images.zenhubusercontent.com/194341141/3dc32646-0623-44d0-a768-fe5fb85f1bb3/easycla2472.mp4

**Comment by vinod-kadam** [comment]
This is deployed to Dev, Staging & PROD.
