### ISSUE TITLE
On CCLA/ICLA Docusign page, uanble to remove the adopted signature after selecting 'Clear' option displayed on signature.

### ISSUE THREAD

**Issue by ashav-github** [communitybridge/easycla#2477]
Steps:

1. On CCLA/ICLA Docusign page, adopt the signature
2. Click on signature again and select option 'Clear'

Actual Result: It shows signature got cleared but the signature appears back.  Please find below the recording. 
https://images.zenhubusercontent.com/194341141/19487489-cbd5-449d-8ffc-7def7c674a0d/docusign_clearsignature.mp4

Expected Result: Either 'Clear' option should really clear the signature OR I think 'Clear' option can be removed and the existing option 'Change' option can remain to cater the need of signature change.

**Comment by vinod-kadam** [comment]
As discussed with @pranab-bajpai  & @dealako , this is marked as Post-EasyCLAv2Release considering this is not blocking anything & moreover it it something in Docusign where we don't have much control.

**Comment by dealako** [comment]
Won't fix. Out of scope of current product requirements/features.
