### ISSUE TITLE
Landing page changes for V1 to V2 migration - changes for Project Login & CLA Manager Login links on LFX Header

### ISSUE THREAD

**Issue by vinod-kadam** [communitybridge/easycla#2478]
- wireframe for V1/V2 redirection from landing page.
https://wireframepro.mockflow.com/view/platform-style-guide#/page/Dfcc3e0be0361ae66dbf30f238a7814ad
- User will click on Project Login & CLA Manager Login hyperlinks and that will open the dialog box which will give the user an option to choose between V1 and V2.
-  If you already know that the user is coming from V1 or V2 you can put that logic and not show this option. Wherever you don't know what version the user is in, you should show this option.

Note: This ticket has a dependency on https://jira.linuxfoundation.org/browse/IAM-1310 as there is a need of click event support on the LFX Header hyperlinks.

**Comment by vinod-kadam** [comment]
@amolsontakke3576  also do the following:
Change the option "LFX Version 1" to "EasyCLA Version 1" and 
change the option  "LFX Version 2" to "EasyCLA Version 2".

**Comment by thakurveerendras** [comment]
Issue is tested on dev/staging site & found below results 

- Dialog box open which will give the user an option to choose between V1 and V2 when user click on Project Login & CLA Manager Login hyperlinks.
- "LFX Version 1" text is properly updated to "EasyCLA Version 1"
- "LFX Version 2" text is properly updated to "EasyCLA Version 2".

Refer video clip for more details 
https://images.zenhubusercontent.com/194341141/44644110-46d7-44e9-becf-02b2ade17fc2/2492.mp4

**Comment by vinod-kadam** [comment]
Issue #2492 is opened for the case where user comes from GitHub & based on the parameter, user should directly be taken to corresponding version console if the user clicks on Proceed or the links on LFX Header. So, marking this as QA Done.

**Comment by vinod-kadam** [comment]
This one is deployed to PROD as well.
