### ISSUE TITLE
v1 PROD Cannot add new company in the Corporate console

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2479]
## Summary

Log into the corporate console at https://corporate.v1.easycla.lfx.linuxfoundation.org/
Click "Get Started"
Type in "Test"
Try to "Add Company"

Observe in console : 
Error Failed to load resource 
![image](https://user-images.githubusercontent.com/46732999/105188203-a36f3000-5b01-11eb-87f9-1d05b4038fdd.png)

Trying to join an already created company appears to work.

**Comment by WillsonHG** [comment]
@amolsontakke3576  Not resolved in prod today

**Comment by dealako** [comment]
Resolved - see: https://github.com/communitybridge/easycla/pull/2505

**Comment by dealako** [comment]
@WillsonHG was able to create a company in PROD

![Screen Shot 2021-01-21 at 7.13.45 PM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/1e90a8ed-5412-4dc9-842c-f50a094ab884)

**Comment by WillsonHG** [comment]
Have verified this is working in prod as well.
