### ISSUE TITLE
Support signing entity name in the email to CLA Signatory 

### ISSUE THREAD

**Issue by vinod-kadam** [communitybridge/easycla#2485]
This is specific use case of Signing Entity Name for CLA Signatory; he/she can sign CCLA without login to Corporate Console.
So when CLA Signatory clicks on link provided in email, docusign document which opens should have signing entity name.

Ticket for corresponding frontend change which is needed from Corporate Console is https://jira.linuxfoundation.org/browse/LFX-3050 
If there is any change needed in the CLA API which is used by Corporate Console (for Identify CLA Signatory work flow) then need to make that change.

**Comment by makkalot** [comment]
I think this one should be already working with new changes @vinod-kadam, don't think anything extra is needed.

**Comment by mlehotskylf** [comment]
I believe we can close this.

**Comment by thakurveerendras** [comment]
It is old ticket & working fine. So closing this ticket
