### ISSUE TITLE
User redirected from GitHub to EasyCLA Landing page & click on Proceed should take user to V2 console   

### ISSUE THREAD

**Issue by vinod-kadam** [communitybridge/easycla#2492]
User is on GitHub repo which is configured with V2 CLA group. 
User clicks on "Covered" for a PR which has passed the gating.
User get redirected to EasyCLA landing page.
User clicks on Proceed button of Project Console & Corporate Console.
Actual Result: the user is presented with option of Version 1 & Version 2.
Expected Result: the user should be taken to Version 2 consoles.

**Comment by makkalot** [comment]
Tested on : 

Failing case : https://github.com/penguinsoftltd/docusign-fields/pull/2
Passing case : https://github.com/penguinsoftltd/docusign-fields/pull/3

**Comment by thakurveerendras** [comment]
Issue is tested on Dev/staging site & found that issue is still reproducible, So making issue status to Rejected by QA

Refer PR
Dev : https://github.com/veerdev12jan/veerdev12jan_repo/pull/3
Staging : https://github.com/A-manishfoundation2021stage/Repo001/pull/2 

Refer video clip for more details
 https://images.zenhubusercontent.com/194341141/8faafcf2-789b-4e36-9f9b-b0ba3377c87b/2492.mp4

**Comment by vinod-kadam** [comment]
@thakurveerendras , when this issue is fixed and given back for QA testing, test it for both Proceed button & links on LFX header.

**Comment by makkalot** [comment]
In video looks like the version is appended properly (which was the fix I worked on the backend), seems like we need to handle that on frontend @amolsontakke3576 @vinod-kadam . Also make sure when testing to open new PR, old prs wouldn't be fixed.

**Comment by amolsontakke3576** [comment]
@makkalot Issue is with redirect URL you are redirecting to
`https://dev.lfcla.com/?version=2
`but it should be 
`https://dev.lfcla.com/#/?version=2
`

`#` is missing in the redirect URL.

**Comment by thakurveerendras** [comment]
Issue is retested on dev environment & found that it is still not fixed , Refer video clip for more details 

https://images.zenhubusercontent.com/194341141/006bbc7e-cd6a-4567-9df6-5502520f6d71/2492__2_.mp4

https://images.zenhubusercontent.com/194341141/15ba4beb-d914-4786-af3c-66b533ab9ae6/2492_1.mp4

**Comment by thakurveerendras** [comment]
Retested this issue on dev site & found that it is still reproducible. 

PR : https://github.com/27Janorg/27janrepo/pull/1

Refer video clip 
https://images.zenhubusercontent.com/194341141/7b051689-eea3-4a22-ac5c-37c131eccf91/2492_27jan.mp4

**Comment by makkalot** [comment]
Can we test again pls ? there was edge case with `#` sign in the url where the stdlib was not handling properly.

**Comment by thakurveerendras** [comment]
Issue is tested on dev site & found that issue is fixed as expected, So making issue status to QA-Done

Refer video clip for more details 
https://images.zenhubusercontent.com/194341141/3bf158dd-f0b9-4359-9574-eb7b5939bbc3/2492_verified.mp4

**Comment by vinod-kadam** [comment]
This is deployed to Staging & PROD on 3-Feb.

**Comment by manishv09** [comment]
Verified it on staging environment today and found working fine. Please refer attached video for your reference.

https://images.zenhubusercontent.com/194341141/a391a081-f054-4648-b09d-8e2ec0f56316/recording__71.mp4
