### ISSUE TITLE
Steve's Feedback: remove the quoted sentence from the email

### ISSUE THREAD

**Issue by vinod-kadam** [communitybridge/easycla#2497]
This is from Steve's feedback as result of testing on Staging.
https://docs.google.com/document/d/1RPrCH6U8RTFcBmdKEveUuXZhJt1QN-O7xpR99otAROA/edit#
1C(10): After an authorized contributor is added to the Approved List, the notification email sent to the CLA Manager says that “Contributors with previously failed pull requests to Jan11-Parent-CNCF-model can close and re-open the pull request to force a recheck by the EasyCLA system.” 
Remove the quoted sentence from the email as it is not needed.

**Comment by thakurveerendras** [comment]
Issue is tested on dev environment & found that mentioned quoted sentence are not present on mail body 

**Mail Subject** :

> `EasyCLA: Approval List Update for Proxima on VeerClaTest3`

**Mail Body** :

> `Hello Veerendra Thakur,
> 
> This is a notification email from EasyCLA regarding the project VeerClaTest3.
> 
> The EasyCLA approval list for Proxima for project VeerClaTest3 was modified.
> 
> The modification was as follows:
> 
> Added Email: veerendrat+1@proximabiz.com
> If you need help or have questions about EasyCLA, you can read the documentation or reach out to us for support.
> 
> Thanks,
> 
> The LF Engineering Team`

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/7acacc42-f590-4b1a-b075-1c58653073d3)

**Comment by vinod-kadam** [comment]
As discussed in the standup, the change should be there on Staging and PROD as well.

**Comment by thakurveerendras** [comment]
Issue is retested on staging environment & found that mentioned quoted sentence are not present on the notification email sent to the CLA Manager, So issue seems to fixed on dev/staging environment

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/4bf8c0bd-6899-4daf-9145-c85a0708dbb4)
