### ISSUE TITLE
Document process to manually delete a cla group 

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2498]
When a PM or Community PM would like to delete a cla group in v2 PCC, a ticket must be filed with support. 

https://admin.dev.platform.linuxfoundation.org/apps/cla/overview#id=a0941000002wBzBAAU
CLA Group: testfound12nov

Let's work to figure out the process to manually delete this CLA Group and document it for support desk.

**Comment by WillsonHG** [comment]
would depend on whether there were signatures for it or if it was a mistake/test

**Comment by dealako** [comment]
Currently, we need to open a support ticket to delete the CLA group. Is is documented in the public documentation at docs.linuxfoundation.org.
