### ISSUE TITLE
Signed CLA is showing up as not signed on Corporate Console  

### ISSUE THREAD

**Issue by vinod-kadam** [communitybridge/easycla#2515]
This issue is seen on Staging environment.

I signed a CCLA for vinodkfoundation_child1 project for "Proxima India" (it is a signing entity name in company Proxima) however the CCLA is shown as not signed on Corporate Console
![image.png](https://images.zenhubusercontent.com/5e9e9952b186e1325cf5608a/918b8488-9c7d-4803-b8c0-22c957200f04)

When I go from Contributor Console & select "Proxima India"; it gives presents me the list of CLA managers which means CLA is signed.
![image.png](https://images.zenhubusercontent.com/5e9e9952b186e1325cf5608a/0ad329fa-c7d0-49a7-bf6b-7cfc289a327b)

CLA group information can be found below:
![image.png](https://images.zenhubusercontent.com/5e9e9952b186e1325cf5608a/66653d80-a82c-47dc-9069-45cee6bce90d) 

I called the following API from postman:
https://api-gw.staging.platform.linuxfoundation.org/cla-service/v4/company/0012M00002MnADGQA3/project/a097c000007nhFnAAI/cla
I got the following response:
{
    "signed_cla_list": [],
    "unsigned_project_list": [
        {
            "can_sign": true,
            "ccla_enabled": true,
            "cla_group_id": "043637e9-1a8f-4082-9a45-db1fa7d7f0dd",
            "cla_group_name": "vinodkfoundation_clagroup1",
            "icla_enabled": true,
            "project_name": "vinodkfoundation_child1",
            "project_sfid": "a097c000007nhFnAAI",
            "sub_projects": []
        }
    ]
}

**Comment by vinod-kadam** [comment]
All CLA backend changes have been deployed to Dev.
Also, Corporate Console changes (https://jira.linuxfoundation.org/browse/LFX-3064) have been deployed to Dev.

**Comment by manishv09** [comment]
Working fine on DEV and found it is working. With existing data and found working as expected.
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/c6c8e4f2-24da-4526-bf30-19d1049cf4a8)

**Comment by vinod-kadam** [comment]
@manishv09  as discussed try it also for a new org after new org creation issue is resolved & deployed to Dev.

**Comment by vinod-kadam** [comment]
Closing this ticket since it was updated on 2-Feb that signing entity name will not be shown on the UI anywhere - system will return to its old behavior.
