### ISSUE TITLE
v2 Corporate Console - cannot add wildcard in domain approval list (LFX-3060)

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2519]
## Summary

When a cla manager tries to add a wildcard in the domain approval list for a cla, the * character is not allowed.

![image](https://user-images.githubusercontent.com/46732999/105731189-270f8f00-5efd-11eb-8a7b-68e43dc1a257.png)

![image](https://user-images.githubusercontent.com/46732999/105731274-41e20380-5efd-11eb-93b0-eeb431f0f0a1.png)

Both cases are valid.

**Comment by WillsonHG** [comment]
subdomains are also not being allowed

![image](https://user-images.githubusercontent.com/46732999/105732478-7a361180-5efe-11eb-8746-67e7b51691e4.png)

**Comment by vinod-kadam** [comment]
Created LFX ticket https://jira.linuxfoundation.org/browse/LFX-3060 so closing this one.
