### ISSUE TITLE
Duplicate event created for assigning contributor role.

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2523]
## Summary

For the v2 Corporate Console, a duplicate event is being recorded when a contributor chooses their company to contribute under. This event is recorded twice in the database and as a result, shows twice in the UI. 

![image](https://user-images.githubusercontent.com/46732999/105784426-cb69f380-5f46-11eb-9512-1eae9bd669c7.png)

![image](https://user-images.githubusercontent.com/46732999/105784604-200d6e80-5f47-11eb-9e1a-89a79ca81928.png)

**Comment by vinod-kadam** [comment]
As updated by @makkalot, the events are not duplicate - they have different scope.
