### ISSUE TITLE
Pranab reported: Email not sent to designated CLA Manager from contributor console in staging

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#2527]
Steps to reproduce
- [ ] Get blocked by EasyCLA check and go to contributor console 
- [ ] Select creating a new company and then click proceed
- [ ] When dialog box shows up asking if you can become CLA Manager for this company select "No"
- [ ] Fill out the information of designated CLA Manager and follow prompts to let the system exit CLA
- [ ] You will see that the designated CLA Manager never got any email. 
- [ ] @wanyaland I shared the video with you on slack

**Comment by vinod-kadam** [comment]
As updated by @wanyaland , this is deployed to Dev.

**Comment by amolsontakke3576** [comment]
Verified and look like fix on the dev 
 ![Screenshot from 2021-01-28 16-32-47.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/457f5431-3d7b-4c09-b306-28fe390f5ef8)

**Comment by vinod-kadam** [comment]
This is deployed to Staging & PROD on 3-Feb.

**Comment by manishv09** [comment]
Verified on Staging and found working fine here as well, please refer screencast and also video attached for reference.
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/d8d44a17-adf6-4dcb-abe7-98adeec1003c)

https://images.zenhubusercontent.com/194341141/202b8a67-7be7-4c73-8331-b544ef435ed9/bug2527_04022021.mp4
