### ISSUE TITLE
"User is already a CLA Manager..." message shown when a user creates a new company and identifies a CLA manager who has LFID

### ISSUE THREAD

**Issue by amolsontakke3576** [communitybridge/easycla#2529]
Steps to reproduce
1. Click on `Organization not listed? + Click Here`
2. Fill up CREATE NEW ORGANIZATION form
3. No Signed CLA Found screen come
4.  Select No
5. Enter CLA manager Email Id and name (make sure the email is already associated with LF).
6. `company does not exist` Error comes from API

Request URL: https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/user/92b965df-e77b-43b5-ada8-a8a914e523b8/invite-company-admin
Request Method: POST
Status Code: 400 

Payload
{"companyID":"900f1532-ee50-48bc-84cf-b35a3fd2c1e2","contactAdmin":false,"claGroupID":"56947ded-70c4-42c3-b90c-94f455707d83","name":"Yashoda","userEmail":"amols+yashoda@proximabiz.com"}

Response
`{"Code":"400","Message":"company does not exist","x-request-id":"9dd0b91e-ead7-4f74-945e-5292b3de2598"}`

**Comment by vinod-kadam** [comment]
As updated by @wanyaland , this is fixed and PR raised.

**Comment by vinod-kadam** [comment]
As updated by @wanyaland , this is deployed to Dev.

**Comment by amolsontakke3576** [comment]
Tested on dev and works fine PFA
![Screenshot from 2021-01-28 18-31-32.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/3cfb2a2a-7bed-430e-affd-7ca3dc5a5d8f)

**Comment by manishv09** [comment]
Verified on staging environment and found working fine on staging environment as well.
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/1c25ac33-87c4-4c4c-97ac-3d3b91b561a8)

**Comment by manishv09** [comment]
Also refer video as well for reference.
https://images.zenhubusercontent.com/194341141/60ebe1f1-c475-4d33-85bd-3536cd12ffdd/bug_2529_04022021.mp4
