### ISSUE TITLE
Not able to create new organisation in contributor console.

### ISSUE THREAD

**Issue by amolsontakke3576** [communitybridge/easycla#2535]
Steps to reproduce
1. Click on create a new organization
2. Fill up all the details and click Next
3. Click on Yes as you are authorized to sign CLA
4. Below error thrown on the screen.

Request URL: https://api-gw.staging.platform.linuxfoundation.org/cla-service/v4/user/843398e1-28e0-4a42-98b9-b69d1988b237/company
Request Method: POST
Status Code: 400 

Payload
{"companyName":"Malinga","companyWebsite":"malinga.com","signingEntityName":"Malinga 1","userEmail":"amols@proximabiz.com","createdBy":"843398e1-28e0-4a42-98b9-b69d1988b237"}

Response
{"Message":"[GET /v1/lookup][404] lookupNotFound  map[]","x-request-id":"45bf62e7-0713-44cc-aab6-d6f2b8b8b99f"}

**Comment by makkalot** [comment]
I think this was fixed in dev environment.

**Comment by vinod-kadam** [comment]
As discussed @amolsontakke3576 , check it on Dev.

**Comment by amolsontakke3576** [comment]
@makkalot Issue is persisted for newly created organization
Below is the API details

Request URL: https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company/324806d8-8838-4356-b53f-47aa626a8f59/claGroup/6af98db9-fd1e-48b9-9cb4-29652e473bc9/cla-manager-designee
Request Method: POST
Status Code: 400 

Payload
{"userEmail":"amols@proximabiz.com"}

Response
{"Code":"400","Message":"EasyCLA - 400 Bad Request - Creating cla manager failed for Foundation SFID: a096s00000041PdAAI  - error: fetching org model failed for companySFID : 0016s00000AhppsAAB : [GET /v1/orgs/{salesforceID}][404] getOrgNotFound  &{Code:404 Message:organization-service - not found XRequestID:ad9899e0-6196-11eb-ad52-3775bb5212b5}","x-request-id":"ad633200-6196-11eb-ad52-3775bb5212b5"}

**Comment by vinod-kadam** [comment]
As updated by @amolsontakke3576 , this is happening for complete new org as well as for new signing entity.

**Comment by wanyaland** [comment]
Tested this and org creation works as expected
I tried both cases for authenticated and newly created users(requiring account verification) and in both cases I was able to create the org with cla-manager-designee role assigned to the user

**Comment by amolsontakke3576** [comment]
@vinod-kadam Verified on Dev and working fine.

**Comment by vinod-kadam** [comment]
This is deployed to Staging & PROD on 3-Feb.

**Comment by manishv09** [comment]
Verified this on Staging environment and found working fine now. Please refer the attached video for more details.

https://user-images.githubusercontent.com/74345613/106903041-8486b580-671f-11eb-869d-02afcbe0e466.mp4
