### ISSUE TITLE
Wrong contributor email address in the email sent to designated CLA Manager

### ISSUE THREAD

**Issue by amolsontakke3576** [communitybridge/easycla#2536]
When the contributor identifies someone else as a CLA manager, the email goes to the designated CLA manager having a `xxxxxx@users.noreply.github.com` email rather than the actual one he registered on github.

PFA
![Screenshot from 2021-01-28 16-32-47.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/baab3542-9efc-4b6d-b323-2158a2ffae34)

**Comment by makkalot** [comment]
From my understanding this email is generated from https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/inviteCompanyAdmin endpoint and it accepts its email {`userEmail`} value from the client side. @amolsontakke3576 can you get me request/response details for that call ?

**Comment by amolsontakke3576** [comment]
@makkalot I have Checked and look like the issue is from the backend, this issue faced when the designated CLA manager
not associated with LF.

Below is the API details

Request URL: https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company/0016s000006Uq9VAAS/claGroup/6af98db9-fd1e-48b9-9cb4-29652e473bc9/cla-manager-designee
Request Method: POST
Status Code: 400 

Payload
{"companyID":"f6a6373a-2793-4a6d-9926-6d67de5f3535","contactAdmin":false,"claGroupID":"6af98db9-fd1e-48b9-9cb4-29652e473bc9","name":"Amol","userEmail":"amols+12323@proximabiz.com"}

{"Code":"202","Message":"User amols+12323@proximabiz.com has no LF Login account ","x-request-id":"07de4a1f-23fa-438a-9265-c6f4e2c475de"}

And below is the email content



![Screenshot from 2021-01-28 23-48-21](https://user-images.githubusercontent.com/56335654/106181209-522b0480-61c3-11eb-88d9-656bfc9d1ef6.png)

**Comment by manishv09** [comment]
Found working fine now on DEV environment, please refer the screencast below:
![image](https://user-images.githubusercontent.com/74345613/106900556-ab8fb800-671c-11eb-8e25-a3962d708f9a.png)

**Comment by vinod-kadam** [comment]
This is deployed to Staging & PROD.

**Comment by manishv09** [comment]
Verified on Staging environment and found working fine. Please refer the screencast below:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/dfafdde2-d294-45ac-8bd8-eff4cc0e4468)
