### ISSUE TITLE
Getting error "EasyCLA - 400 Bad Request - unable to lookup company by ID: 0014100000kgVkTAAU - error: company does not exist" while adding new signing entity name from Contributor console

### ISSUE THREAD

**Issue by manishv09** [communitybridge/easycla#2537]
Getting error "EasyCLA - 400 Bad Request - unable to lookup company by ID: 0014100000kgVkTAAU - error: company does not exist" while adding new signing entity name from Contributor console

Please refer attached screencast for workflow to reproduce the issue.

https://images.zenhubusercontent.com/194341141/89bb0491-064b-447d-b450-45c15c070b2f/recording__31.mp4

**Comment by makkalot** [comment]
seems the log comes from this endpoint : https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/createCLAManagerDesigneeByGroup  it now accepts internal company id instead of external salesforce id, please make the changes on frontend

**Comment by vinod-kadam** [comment]
This is available on Dev.

**Comment by manishv09** [comment]
Verified today on DEV environment and found it resolved. No error is received while navigating from Contributor Console. Please refer attached video for more details.

https://images.zenhubusercontent.com/194341141/9399afc8-9ed5-476e-a3f9-93f7be2bd1a7/bug_2537_29012021.mp4

**Comment by manishv09** [comment]
Getting Same Error for Adding Signing Entity Name to a newly created Org. Please refer the screencast below:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/3232810e-fbc2-4b35-b627-d40041435cf4)

**Comment by vinod-kadam** [comment]
As updated by @manishv09, this is working fine on Dev.

**Comment by vinod-kadam** [comment]
This is deployed to Staging & PROD on 3-Feb.
