### ISSUE TITLE
Multiple orgs shown at foundation level (in manage GitHub orgs) which should not be shown

### ISSUE THREAD

**Issue by vinod-kadam** [communitybridge/easycla#2539]
This issue is foundation on Staging.
Create a foundation level cla group. Then go to manage the foundation for GitHub orgs.
There are multiple GitHub orgs which are shown for the foundation - these orgs should not have been shown.

![image.png](https://images.zenhubusercontent.com/5e9e9952b186e1325cf5608a/7c83e9d8-524c-47de-9a57-26217bbc3fce)

![image.png](https://images.zenhubusercontent.com/5e9e9952b186e1325cf5608a/48565ac9-77ed-47a6-9c81-0be5bdd66e70)

API is returning those multiple orgs (the below response is for foundation vinodkfoundation2):
https://api-gw.staging.platform.linuxfoundation.org/cla-service/v4/project/a097c000007nhT0AAI/github/organizations

{
    "list": [
        {
            "auto_enabled": false,
            "branchProtectionEnabled": false,
            "connection_status": "connected",
            "github_organization_name": "cla-8162019-org",
            "repositories": [
                {
                    "cla_group_id": "",
                    "connection_status": "connected",
                    "enabled": false,
                    "parent_project_id": "",
                    "project_id": "",
                    "repository_github_id": 202772457,
                    "repository_id": "",
                    "repository_name": "cla-8162019-org/CLA-8162019-org1"
                },
                {
                    "cla_group_id": "2810786b-f449-4858-84b0-54f9b0904cc7",
                    "connection_status": "connected",
                    "enabled": true,
                    "parent_project_id": "a0941000002wBz9AAE",
                    "project_id": "",
                    "repository_github_id": 202772347,
                    "repository_id": "19c58e4b-b6d5-4c85-9a1f-ac5e50ff8edc",
                    "repository_name": "cla-8162019-org/CLA-8162019-repo"
                }
            ]
        },
        {
            "auto_enabled": false,
            "branchProtectionEnabled": false,
            "connection_status": "connection_failure",
            "github_organization_name": "cla-demo-org1",
            "repositories": []
        },
        {
            "auto_enabled": false,
            "branchProtectionEnabled": false,
            "connection_status": "connected",
            "github_organization_name": "cla-demo-pranab-org",
            "repositories": [
                {
                    "cla_group_id": "49ee2470-518f-47c4-a438-dbba0d9f135d",
                    "connection_status": "connected",
                    "enabled": true,
                    "parent_project_id": "a0941000002wBz9AAE",
                    "project_id": "",
                    "repository_github_id": 221327020,
                    "repository_id": "a5e68579-b315-4e0a-ad92-9b7adf330d57",
                    "repository_name": "cla-demo-pranab-org/-cla-demo-pranab-repo3"
                },
                {
                    "cla_group_id": "49ee2470-518f-47c4-a438-dbba0d9f135d",
                    "connection_status": "connected",
                    "enabled": true,
                    "parent_project_id": "a0941000002wBz9AAE",
                    "project_id": "",
                    "repository_github_id": 221323141,
                    "repository_id": "67a223f2-4922-46a3-a81a-44b29e8a1272",
                    "repository_name": "cla-demo-pranab-org/cla-demo-pranab-repo1"
                },
                {
                    "cla_group_id": "49ee2470-518f-47c4-a438-dbba0d9f135d",
                    "connection_status": "connected",
                    "enabled": true,
                    "parent_project_id": "a0941000002wBz9AAE",
                    "project_id": "",
                    "repository_github_id": 221323180,
                    "repository_id": "d1fddb3b-bbce-4e65-b7cc-4ae05aff7414",
                    "repository_name": "cla-demo-pranab-org/cla-demo-pranab-repo2"
                }
            ]
        },
        {
            "auto_enabled": false,
            "branchProtectionEnabled": false,
            "connection_status": "connected",
            "github_organization_name": "cla-demo-pranab-org2",
            "repositories": [
                {
                    "cla_group_id": "805b6fca-4d53-4212-8b9d-278cdefd4e0a",
                    "connection_status": "connected",
                    "enabled": true,
                    "parent_project_id": "a0941000002wBz9AAE",
                    "project_id": "",
                    "repository_github_id": 221327572,
                    "repository_id": "97f77041-05f5-4aa4-932e-435029da4172",
                    "repository_name": "cla-demo-pranab-org2/cla-demo-pranab-org2-repo1"
                }
            ]
        },
        {
            "auto_enabled": false,
            "branchProtectionEnabled": false,
            "connection_status": "connection_failure",
            "github_organization_name": "deal-test-org",
            "repositories": [
                {
                    "cla_group_id": "54efcf33-6786-4c81-a3a8-aecf8f7b40f6",
                    "connection_status": "connection_failure",
                    "enabled": true,
                    "parent_project_id": "a0941000002wBz9AAE",
                    "project_id": "",
                    "repository_id": "7a1ede85-dde6-4998-a720-392aa7123b59",
                    "repository_name": "deal-test-org/staging-test1"
                }
            ]
        },
        {
            "auto_enabled": false,
            "branchProtectionEnabled": false,
            "connection_status": "connected",
            "github_organization_name": "demo-11072019-org",
            "repositories": [
                {
                    "cla_group_id": "da407715-4838-4660-8065-575ebd6f438a",
                    "connection_status": "connected",
                    "enabled": true,
                    "parent_project_id": "a0941000002wBz9AAE",
                    "project_id": "",
                    "repository_github_id": 220303061,
                    "repository_id": "0cfc20f0-5159-4474-8be1-c683e567baa6",
                    "repository_name": "demo-11072019-org/demo-11072019-repo1"
                },
                {
                    "cla_group_id": "",
                    "connection_status": "connected",
                    "enabled": false,
                    "parent_project_id": "",
                    "project_id": "",
                    "repository_github_id": 220303159,
                    "repository_id": "",
                    "repository_name": "demo-11072019-org/demo-11072019-repo2"
                }
            ]
        },
        {
            "auto_enabled": false,
            "branchProtectionEnabled": false,
            "connection_status": "connection_failure",
            "github_organization_name": "demo-att-org",
            "repositories": [
                {
                    "cla_group_id": "fd535a25-6a15-420b-926a-fe99e1eea778",
                    "connection_status": "connection_failure",
                    "enabled": true,
                    "parent_project_id": "a0941000002wBz9AAE",
                    "project_id": "",
                    "repository_id": "3df6a60c-07b7-45bd-bdef-03fd07054f85",
                    "repository_name": "demo-att-org/demo-att-repo"
                }
            ]
        },
        {
            "auto_enabled": false,
            "branchProtectionEnabled": false,
            "connection_status": "connected",
            "github_organization_name": "Demo-Org-1127",
            "repositories": [
                {
                    "cla_group_id": "cd345e70-522f-42e9-9420-361864ffdf34",
                    "connection_status": "connected",
                    "enabled": true,
                    "parent_project_id": "a0941000002wBz9AAE",
                    "project_id": "",
                    "repository_github_id": 224465528,
                    "repository_id": "cd56afb7-58b0-4ad5-a908-794d39bc052b",
                    "repository_name": "Demo-Org-1127/Demo-Repo-1127"
                },
                {
                    "cla_group_id": "cd345e70-522f-42e9-9420-361864ffdf34",
                    "connection_status": "connected",
                    "enabled": true,
                    "parent_project_id": "a0941000002wBz9AAE",
                    "project_id": "",
                    "repository_github_id": 224465626,
                    "repository_id": "90c00fa5-6526-4283-923c-b6995b287e08",
                    "repository_name": "Demo-Org-1127/Demo-Repo2-1127"
                }
            ]
        },
        {
            "auto_enabled": false,
            "branchProtectionEnabled": false,
            "connection_status": "connected",
            "github_organization_name": "nirav-org",
            "repositories": [
                {
                    "cla_group_id": "0a95d012-62fb-44c6-b1a1-8aa6d21bf6f9",
                    "connection_status": "connected",
                    "enabled": true,
                    "parent_project_id": "a0941000002wBz9AAE",
                    "project_id": "",
                    "repository_github_id": 222778426,
                    "repository_id": "8cf1ef43-5771-4b3e-bed6-2ca972e57589",
                    "repository_name": "nirav-org/nirav-repo"
                }
            ]
        }
    ]
}

**Comment by vinod-kadam** [comment]
As observed in the morning, this is not seen on Dev.

**Comment by dealako** [comment]
@vinod-kadam @tejasadg 

This is the current situation for STAGING

The project for this scenario is:
[20210129T10:58:56-0800][INFO] -   a097c000007nhT0AAI - vinodkfoundation2 :: ProjectType: Project Group :: Parent: a0941000002wBz9AAE  The Linux Foundation

As you can see, we have a Project Group called vinodkfoundation2 with TLF as the parent. In this scenario, we should query the EasyCLA API for a list of GH organizations using the "Project Group", which is SFID: a097c000007nhT0AAI. The UI should NOT query the list of GitHub organizations of the "Project Group" parent...which in this case is 'The Linux Foundation'.

Please update the UI logic to:

1. If the current project "ProjectType" is a "Project Group", then query the GH organizations using the project's SFID (rather than his parent).
2. If the current project "ProjectType" is a "Project", then identify the project's parent.
    1. If the parent project "Project Type" is a "Project Group" then query the GH organizations using the parent SFID
    2. (we don't support this in the EasyCLA API) - If the parent project "Project Type" is not a "Project Group", then identify the parent project's parent. If the parent's parent project "Project Type" is a "Project Group" then query the GH organizations using the parent parent's SFID. Repeat until you get the situation where "Project Type" is a "Project Group".

Ultimately, we never want to query the GitHub Organizations API using a "Project Group"'s parent SFID.

**Comment by dealako** [comment]
I have cleaned up the STAGING GH Organization and Repository table - removed entries that were attached to the TLF SF record.

**Comment by vinod-kadam** [comment]
As updated by @wanyaland, the fix is deployed to Dev env.

**Comment by vinod-kadam** [comment]
Verified on Dev & it is working fine now. So, marking it as QA Done.

**Comment by vinod-kadam** [comment]
This is deployed to Staging & PROD on 3-Feb.

**Comment by vinod-kadam** [comment]
I verified it on Staging. It only shows the org which were configured in the child projects.
image.png](https://images.zenhubusercontent.com/5e9e9952b186e1325cf5608a/8d62c3cf-ff36-4584-a2b7-c6a485fd4082)
