### ISSUE TITLE
Corporate Console v2 emails sent to approved/removed user

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2544]
## Summary

When a cla manager adds a user's email to the approved list, the following email is sent to the contributor approved.
![image](https://user-images.githubusercontent.com/46732999/106227567-68cb5e80-61b7-11eb-996c-e9d85a3e233e.png)

- [x] Remove the sentence that instructs the user to close and reopen their pr and replace it with "If you had previously submitted a pull request to EasyCLA Test Group that had failed, you can now go back to it and follow the link to verify with your organization."

- [x] The sentence "This means that you are authorized to contribute to on behalf of EasyCLA Test Group" should read "This means that you are authorized to contribute to PROJECT NAME on behalf of ORG NAME."

When a cla manager removes a contributor's email from the approved list, the following email is sent.

![image](https://user-images.githubusercontent.com/46732999/106228022-7503eb80-61b8-11eb-9123-916d66e5b09c.png)

- [x] Remove the sentence that tells the contributor to close and open their pull request and replace it with nothing.
- [x] The sentence "This means that you are no longer authorized to contribute to on behalf of EasyCLA Test Group." should read "This means that you are no longer authorized to contribute to PROJECT NAME on behalf of ORG NAME."

**Comment by pranab-bajpai** [comment]
@wanyaland I would grep for "If you had previously submitted one or more pull requests to EasyCLA Test Group... close and re-open the pull request ... EasyCLA system." and delete it from every email sent out.

**Comment by WillsonHG** [comment]
The approved contributor email is using the cla group name and not the project name. is this okay?
![image](https://user-images.githubusercontent.com/46732999/107448072-e6279500-6b0e-11eb-8f7c-fe153d6935e5.png)

Also, "on behalf of" is repeated twice a the end of the middle paragraph. It should read "This means that you are authorized to contribute to PROJECT NAME on behalf of COMPANY NAME.

**Comment by WillsonHG** [comment]
Same issues with the removal email.

![image](https://user-images.githubusercontent.com/46732999/107448311-68b05480-6b0f-11eb-9c8e-dc2d614b3ae2.png)

Also, the sentence "If you had previously submitted a pull request .... " should be removed as it is not applicable in the REMOVAL notice.
