### ISSUE TITLE
EasyCLA Bug Report - username, role or scope conflict on company creation

### ISSUE THREAD

**Issue by makkalot** [communitybridge/easycla#2551]
## Summary

When user tries to create a company with new signing entity name we get the error.

## Background

The reason for the issue is we handle the user role/scope assignments for external company ids but adding a new signing entity name still uses the old external id.

## Expected behavior

Company creation should not fail because the role is already assigned to the user.

## Screenshots

![Screenshot from 2021-02-01 14-58-17.png](https://images.zenhubusercontent.com/5c5c1adbb76da5342d3d6916/984a7e94-5c93-4522-92bc-d4b031ab6516)

## Environment

Please complete the following information:

* Environment:
  - [x ] DEV

**Comment by vinod-kadam** [comment]
As confirmed by Youssef, he verified the fix on Dev &found it working fine.

**Comment by vinod-kadam** [comment]
This is deployed to Staging & PROD on 3-Feb.
