### ISSUE TITLE
Typos and wrong doc link in the invitation email received by an assigned CLA manager from Contributor Console

### ISSUE THREAD

**Issue by vinod-kadam** [communitybridge/easycla#2558]
This issue is raised by Dibya.
Typos and wrong doc link in the invitation email received by an assigned CLA manager from Contributor Console
 
I created a new company DocWorld while contributing to a project A-New Foundation with Multiple Child 003 on easycla staging, and assigned someone else as a CLA manager for my company. Her received an invitation email that has some typos and V1 (instead of V2) doc link.

The very first line, it alters the company and project name. Company name should be DocWorld and the project name should be A-New Foundation with Multiple Child 003. 
First point: log in instead of login. space between log and in as we are using login as a verb here.
Second point: are instead of a re
Third point: documentation link should be directed to V2 doc page: https://docs.linuxfoundation.org/lfx/v/v2/easycla/corporate-cla-manager-designee-or-initial-cla-manager/sign-corporate-cla-for-a-company

![image.png](https://images.zenhubusercontent.com/5e9e9952b186e1325cf5608a/580d1b53-4a8e-412d-9495-4d01807e351f)

**Comment by dibyaranjanlf** [comment]
Re-generated from dev and staging env. We are getting the below email. It looks good to me, and marking this ticket as QA done!

![image.png](https://images.zenhubusercontent.com/5ff7320002fff1248f0b8ae8/7d7ed6e2-cfcd-43a7-bc71-b278a1c0c96c)

**Comment by vinod-kadam** [comment]
This is deployed to PROD as well.
