### ISSUE TITLE
Error 400 occurred stating "updateOrgBadRequest &{Code:400...Please enter valid domain address." Post user tries to create new signing entity name from Contributor console DEV  

### ISSUE THREAD

**Issue by manishv09** [communitybridge/easycla#2560]
Error 400 occurred stating "updateOrgBadRequest &{Code:400...Please enter valid domain address." Post user tries to create new signing entity name from Contributor console DEV  

![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/2cea0572-7952-4ccb-b380-c28ac375af18)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/d5374957-c3c9-4368-9e2b-e6466963d332)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/036860e0-5192-42f8-a30d-545690428fab)https://images.zenhubusercontent.com/194341141/33f7b1fe-5142-4201-a8db-3024f4b22989/recording__47.mp4

Error Message Received: 
[PUT /v1/orgs/{salesforceID}][400] updateOrgBadRequest &{Code:400 Message:organization-service - service.UpdateOrganization: UpdateOrganization.Queryx: insert response err: FIELD_CUSTOM_VALIDATION_EXCEPTION: Please enter valid domain address. XRequestID:c8c0b7e0-6559-11eb-8d2a-216bc2325840}

Payload
{"companyName":"Google Inc","companyWebsite":"google.com","signingEntityName":"Google India","userEmail":"maan_vaidya@rediffmail.com","createdBy":"937b80ca-e4fe-4486-b563-945d4f4baff7"}

End Point:
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/user/937b80ca-e4fe-4486-b563-945d4f4baff7/company

**Comment by makkalot** [comment]
This error might not be relevant anymore with the latest changes because it was happening when we were adding a new signing entity (which was calling the upda method on org service). I think we need to retest this after the signing entity removal changes are in place.

**Comment by vinod-kadam** [comment]
This flow is no more applicable as signing entity changes have been reverted and system is back to old behavior.
Moreover when  Amol and Manish tried create org today, they didn't face this error. So, closed this issue.
