### ISSUE TITLE
Contributor Console - Hide Signing Entity Name in Create Organization Modal

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#2565]
## Summary

Contributor Console - Hide Signing Entity Name in Create Organization Modal

## Background

Stakeholders do not want users to see the Signing Entity name - just the company name. As a result, during the create company flow, do not provide a UI control for the user to enter the Signing Entity Name - just hide it.  Ensure the APIs work. You may set the Signing Entity Name value to the Company Name if the Signing Entity Name is required in API calls.

## User Story

- As a contributor, I do not need to fill out the Signing Entity Name when creating a new company in the Contributor Console.

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

- None

**Comment by vinod-kadam** [comment]
This is deployed to Dev, Staging & PROD on 3-Feb.

**Comment by manishv09** [comment]
Verified on Staging environment and found working fine, please refer the screencast below for more details:
https://images.zenhubusercontent.com/194341141/c50d163b-bd63-4dce-8128-bcabca96021b/newworkflowsigningentity_04022021.mp4
