### ISSUE TITLE
Gray-out/disabled "LFX Version 2" from Production EasyCLA landing page

### ISSUE THREAD

**Issue by vinod-kadam** [communitybridge/easycla#2569]
Grey-out/disabled "LFX Version 2" from Production EasyCLA landing page.
This need to done only for Production for now; LFX Version should not be grayed out and  disabled in Dev & Staging environment.

**Comment by vinod-kadam** [comment]
This is deployed to Dev, Staging & PROD.

**Comment by amolsontakke3576** [comment]
@vinod-kadam Fixed now and tested on dev and works as per expected need to deploy changes on Staging
