### ISSUE TITLE
Production Template Updates - Editable Corporate Name in DocuSign

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#2573]
## Summary

Production Template Updates - Editable Corporate Name in DocuSign

## Background

Stakeholders want to allow the EasyCLA system to allow CLA Signatories to change/update the company name for the CCLA.  Currently, the Company Name is set to the Company Name value from SF.  This ticket is to allow the CLA Signatory to update the company name.

## Tasks

- For each CLA Group CCLA template:
  - [ ] Review CCLA DocuSign tag configuration. Identify the Company/Corporation Name tag configuration.  Change FieldType from "text" to "text_unlocked"

```json
{
    ID:           "corporation_name",
    Name:         "Corporation Name",
    AnchorString: "Corporation Name:",
    FieldType:    "text_unlocked",  <<<< change value from: 'text' to 'text_unlocked'
    IsOptional:   false,
    IsEditable:   false,
    Width:        355,
    Height:       20,
    OffsetX:      130,
    OffsetY:      -5
}
```

## User Story

- As a CLA Signatory I want to update the company name field in the CCLA DocuSign document.

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Test validate changes by attempting to sign a CCLA

## References

- Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by WillsonHG** [comment]
verified all current cla groups are document_tab_type = text_unlocked and document_tab_is_required = true
