### ISSUE TITLE
Contributor and Corporate Console v1 - form not allowing TLD greater than 5 characters.

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2576]
From the contributor console, select corporate -> my company is not in the list - > no

CLA Manager email does not allow a tld greater than 5.
![image](https://user-images.githubusercontent.com/46732999/106951787-344b2b80-66fe-11eb-9f79-9e227dd34fb1.png)

From contributor console, select corporate -> Demo company -> No

![image](https://user-images.githubusercontent.com/46732999/106952073-9c017680-66fe-11eb-8c2b-c3e909f278c2.png)

From contributor console, select corporate -> company who has signed the cla for the project but not approved the contributor

![image](https://user-images.githubusercontent.com/46732999/106952260-dff47b80-66fe-11eb-96f9-0ef0daf93b75.png)

In the corporate console, attempt to add a cla manager

![image](https://user-images.githubusercontent.com/46732999/106952530-3b266e00-66ff-11eb-976a-8f432a9a9e2a.png)

Adding to the approved list by individual email and domain appear to allow this correctly.

**Comment by dealako** [comment]
@amolsontakke3576 consider reviewing this line: https://github.com/communitybridge/easycla/blob/main/cla-frontend-corporate-console/src/ionic/validators/email.ts#L8

**Comment by dealako** [comment]
Pushed PR: https://github.com/communitybridge/easycla/pull/2585

Updated to allow 12 characters in domain suffix.

**Comment by WillsonHG** [comment]
verified this is fixed on prod
