### ISSUE TITLE
Getting error Setup Required post org selection on from Contributor Console

### ISSUE THREAD

**Issue by vinod-kadam** [communitybridge/easycla#2579]
Getting error "Setup Required" post org selection from Contributor Console and proceed to sign CCLA
![image.png](https://images.zenhubusercontent.com/5e9e9952b186e1325cf5608a/e828ba6b-b21e-4bf6-970a-ce32894c4395)

Endpoint : 
https://api.lfcla.staging.platform.linuxfoundation.org/v3/company/external/0017c00000lMGfoAAG
Recording #60.mp4

Note: this issue was logged initially as LFX-3084 however the right place for the issue is in EasyCLA zenhub board.

**Comment by vinod-kadam** [comment]
As updated by @wanyaland  over slack, the fix is deployed to Dev.

**Comment by vinod-kadam** [comment]
The fix is deployed to Staging & PROD.

**Comment by manishv09** [comment]
Verified on staging and found working fine. Closing the ticket, please refer the video attached.[Uploading... Recording #64.mp4]
