### ISSUE TITLE
Getting error "EasyCLA - 400 Bad Request - problem adding github repositories for projectSFID" while Enforcing CLA for a repository

### ISSUE THREAD

**Issue by vinod-kadam** [communitybridge/easycla#2580]
Getting error "EasyCLA - 400 Bad Request - problem adding github repositories for projectSFID" while Enforcing CLA for a repository
![image.png](https://images.zenhubusercontent.com/5e9e9952b186e1325cf5608a/bcb00e0f-f258-431b-996e-8e2ef931d14d)
![image.png](https://images.zenhubusercontent.com/5e9e9952b186e1325cf5608a/c409e9da-a9f8-4f51-8596-2bf52bf496ed)

https://admin.staging.platform.linuxfoundation.org/api/pages/uuids/5e59fa86-b6b0-11ea-bcd3-ef37af4b1662/query?queryName=enableCla

{"statusCode":400,"error":"Bad Request","message":"\{\"Code\":\"400\",\"Message\":\"EasyCLA - 400 Bad Request - problem adding github repositories for projectSFID: a097c000007nz8gAAA - error: no repository found matching external repository ID: 336218994\",\"x-request-id\":\"d13b10c0-6791-11eb-a587-9d3f3a63a2ec\"}
","metadata":{"request":{"url":"https://api-gw.staging.platform.linuxfoundation.org/cla-service/v4/project/a097c000007nz8gAAA/github/repositories","method":"POST","body":"

{\"cla_group_id\":\"df21a2e3-f7ee-4019-9ea9-e11847b781c3\",\"github_organization_name\":\"FEB-PROJECT-LEVEL-CLA-2021-Child001\",\"repository_github_id\":\"336218994\"}
","headers":{"Content-Type":"application/json","User-Agent":"Retool/2.0 (+https://docs.tryretool.com/docs/apis)","Authorization":"Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik9UY3lOVUZFUkRrME1rTTVRMFUxT1Rjd01UQTVOemM0TVRGQk5rRkNNRFZGUlRWQ1FrSTNPQSJ9.eyJpc3MiOiJodHRwczovL2xpbnV4Zm91bmRhdGlvbi1zdGFnaW5nLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHxtYW5pc2h2LmNvbXBybWdyIiwiYXVkIjpbImh0dHBzOi8vYXBpLWd3LnN0YWdpbmcucGxhdGZvcm0ubGludXhmb3VuZGF0aW9uLm9yZy8iLCJodHRwczovL2xpbnV4Zm91bmRhdGlvbi1zdGFnaW5nLmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE2MTI1MTU1NDIsImV4cCI6MTYxMjUzNzE0MiwiYXpwIjoiYzFqVlVoMlBZME82V3IzNlpuQ3AyMkJWNGNCdDg2Y1QiLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGVtYWlsIG9mZmxpbmVfYWNjZXNzIn0.Dw0j_CR5dxZqFDqMCSM04DvPuP4XvMiynzTUTkaVFw0mEjyMEwhPG7tsFBYQ76lbmAv047YYzUPnmrtRY4ZLlliP_k3eXHiV436JhobDw8pOthwxPClfi2rJoHSp_m1o5lQnMATqlPPGma6JMtjbbBOlZ3mwDuit26NhHJ7oZl6_XZM845ZJ7fRQlLabppGcGAdKEErloMfxkvN7KweBfM66fMJ3vSYjqJTII_r749SOvXt2saH3dBU6ahdzZx7Z-pk2PK81VfVjghcBoaKKmJUYFci2xXBo0Ye5_DVaBbCcBacNkxsMNivusifbJF4jgv5jUzKdpYFLv5g2aqZj4w","X-Retool-Forwarded-For":"223.236.19.206"}},"headers":{"date":["Fri, 05 Feb 2021 09:09:14 GMT"],"content-type":["application/json"],"content-length":["252"],"connection":["keep-alive"],"vary":["Origin"]},"status":400,"statusText":"Bad Request"},"data":null}

https://admin.staging.platform.linuxfoundation.org/apps/cla/project#id=a097c000007nz8gAAA
https://github.com/FEB-PROJECT-LEVEL-CLA-2021-Child001/Repo001

Note: This issue was initially logged as LFX-3081 however the right place for this issue is in EasyCLA Zenhub board.

**Comment by manishv09** [comment]
Verified on Staging and found error is resolved now.

**Comment by vinod-kadam** [comment]
This is deployed to PROD as well.
