### ISSUE TITLE
Getting Error while fetching signatures of a CLA Group on Staging environment

### ISSUE THREAD

**Issue by manishv09** [communitybridge/easycla#2584]
error: "Bad Request"
message: "{"Code":"404","Message":"EasyCLA - 404 Not Found - unable to lookup company by ID: 0012M00002MnADGQA3 - error: no company matching company record - company ID: 0012M00002MnADGQA3","x-request-id":"b257e240-67ce-11eb-a587-9d3f3a63a2ec"}"
metadata: {request: {,…},…}
statusCode: 400

https://admin.staging.platform.linuxfoundation.org/api/pages/uuids/afbf9482-1a72-11eb-8554-b763d67d8e09/query?queryName=getEmployeeSignatures
Request Method: POST

Response
{"statusCode":400,"error":"Bad Request","message":"{\"Code\":\"404\",\"Message\":\"EasyCLA - 404 Not Found - unable to lookup company by ID: 0012M00002MnADGQA3 - error: no company matching company record - company ID: 0012M00002MnADGQA3\",\"x-request-id\":\"b257e240-67ce-11eb-a587-9d3f3a63a2ec\"}","metadata":{"request":{"url":"https://api-gw.staging.platform.linuxfoundation.org/cla-service/v4/company/0012M00002MnADGQA3/project/a097c000007ny98AAA/contributors","method":"GET","body":null,"headers":{"User-Agent":"Retool/2.0 (+https://docs.tryretool.com/docs/apis)","Authorization":"Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik9UY3lOVUZFUkRrME1rTTVRMFUxT1Rjd01UQTVOemM0TVRGQk5rRkNNRFZGUlRWQ1FrSTNPQSJ9.eyJpc3MiOiJodHRwczovL2xpbnV4Zm91bmRhdGlvbi1zdGFnaW5nLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHxtYW5pc2h2LmNvbXBybWdyIiwiYXVkIjpbImh0dHBzOi8vYXBpLWd3LnN0YWdpbmcucGxhdGZvcm0ubGludXhmb3VuZGF0aW9uLm9yZy8iLCJodHRwczovL2xpbnV4Zm91bmRhdGlvbi1zdGFnaW5nLmF1dGgwLmNvbS91c2VyaW5mbyJdLCJpYXQiOjE2MTI1MzkwNTQsImV4cCI6MTYxMjU2MDY1NCwiYXpwIjoiYzFqVlVoMlBZME82V3IzNlpuQ3AyMkJWNGNCdDg2Y1QiLCJzY29wZSI6InByb2ZpbGUgZW1haWwgb3BlbmlkIG9mZmxpbmVfYWNjZXNzIn0.dxPCYb0U6zGV4HQ2mxpSnwi-aUsGgX9j0QCGyZwB9dhX_K1uaSF_o5zbgVo0HyuQKjzwDxlrV1r3JPni3p1A5hCXeyKH4lc8gOG5G5kx_t8SDAxH-hrT22cH5dzKslKLl-6bPbb3ni8v90hDYgzMY2YK3GtUOeP1EDBgE2gaJCbot2uKl9_RzEEkQuXfhW4Y6C7veKFtczMa1SLR4Tvrn2Gabk30-hTuWfXJP2EQmdjh0IP37ZVDnOLuVZQcVk4nUFCTvms40i4I2OtpwoWutt_XrK7DQSUmXhkAaNW4Vn5JCQpSPHruMaTo0bZu32vDRB7w6toCbXqATGunnrNuRw","X-Retool-Forwarded-For":"223.236.19.206"}},"headers":{"date":["Fri, 05 Feb 2021 16:25:01 GMT"],"content-type":["application/json"],"content-length":["235"],"connection":["keep-alive"],"vary":["Origin"],"x-request-id":["b257e240-67ce-11eb-a587-9d3f3a63a2ec"]},"status":404,"statusText":"Not Found"},"data":null}

**Comment by wanyaland** [comment]
@manishv09  
For this use case endpoint path parameter for Company now uses internalID instead of External(salesforce) IDs. So change will have to be updated on the UI end. 
cc @dealako @vinod-kadam

**Comment by tejasadg** [comment]
@manishv09 You can QA this on DEV
PR link https://github.com/LF-Engineering/admin-console/pull/646

**Comment by vinod-kadam** [comment]
I closed this one as have created LFX ticket LFX-3088 as the fix is made on Console side.
