### ISSUE TITLE
After CCLA signing, Corporate Console page is still signing as not signed

### ISSUE THREAD

**Issue by vinod-kadam** [communitybridge/easycla#2586]
Environment: Staging
I signed CCLA for multiple projects however the Corporate Console project page after refresh showed as not signed. I tried refreshing the page however it still showed as not signed.

![image.png](https://images.zenhubusercontent.com/5e9e9952b186e1325cf5608a/8c7c8f30-fcb3-4481-aef8-50b67aaaca7a)
 
![image.png](https://images.zenhubusercontent.com/5e9e9952b186e1325cf5608a/01e31bed-96b2-45f0-a661-4e9581b2755e)

API responses for above are as follows:
{
	"data": {
		"claGroupsForProjectList": [
			{
				"signedClaList": [],
				"unsignedProjectList": [
					{
						"canSign": "false",
						"claGroupId": "dbbe456f-f942-4591-86c5-0a1bc3bfd468",
						"claGroupName": "vinodkfoundation3_clagrp1",
						"projectName": "vinodkfoundation3",
						"projectSfid": "a097c000007nhTeAAI",
						"cclaEnabled": true,
						"iclaEnabled": true,
						"subProjects": [
							"vinodkfoundation3_child1",
							"vinodkfoundation3",
							"vinodkfoundation3_child2"
						],
						"__typename": "UnsignedProject"
					}
				],
				"__typename": "ClaGroupsForProject"
			}
		]
	}
}

{
	"data": {
		"claGroupsForProjectList": [
			{
				"signedClaList": [],
				"unsignedProjectList": [
					{
						"canSign": "true",
						"claGroupId": "30d8953d-5bd4-49cb-ad80-2d936783895e",
						"claGroupName": "vinods1foundation_clagrp",
						"projectName": "vinods1foundation",
						"projectSfid": "a097c000007ny9jAAA",
						"cclaEnabled": true,
						"iclaEnabled": true,
						"subProjects": [
							"vinods1foundation_child2",
							"vinods1foundation",
							"vinods1foundation_child1"
						],
						"__typename": "UnsignedProject"
					}
				],
				"__typename": "ClaGroupsForProject"
			}
		]
	}
}

organizationId: 0012M00002MnADGQA3
organizationInternalId: d6367896-27f0-4c06-9f9a-3420846e0ec9

Note:: Though project page shows cla not signed however I received emails with subjects "EasyCLA: CLA Signature Signed for vinodkfoundation3_clagrp1" & "EasyCLA: CLA Signature Signed for vinods1foundation_clagrp".

**Comment by dealako** [comment]
Created PR: https://github.com/communitybridge/easycla/pull/2587

**Comment by dealako** [comment]
Note this set of changes will now ignore previously signed CCLA's done by the Signing Entity Names over the past couple of weeks.

**Comment by manishv09** [comment]
@dealako, @vinod-kadam  
Verified on DEV today and found working fine, please find the video attached for your reference.
[Uploading... Recording #70.mp4]

**Comment by vinod-kadam** [comment]
@manishv09  as updated over slack, please verify this on Staging once fix for LFX-3091 is deployed to Staging.

**Comment by vinod-kadam** [comment]
As updated by @manishv09 in 10-Feb standup, this can be marked as QA Done. So, moved the ticket to QA Done. Manish has completed his verification for ticket on Staging.
