### ISSUE TITLE
Prod corporate console Add a cla manager - User lookup for user by LFID failed 

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2593]
## Summary

A cla manager is unable to add a second cla manger in the v1 corporate console.
## Background

go to https://corporate.v1.easycla.lfx.linuxfoundation.org/ and login as a cla manager
select 'manage approved list" and try to add an aditional cla manager by name, username, and email
observe the action fails.
error in log - 
{
    "level": "warning",
    "msg": "User lookup for user by LFID:  failed ",
    "time": "2021-02-05T17:17:46Z"
}

User's username is found in auth0, but not in EasyCLA table.

**Comment by dealako** [comment]
This is a result of a new user not logging into EasyCLA yet. They have an auth0 account, but no local EasyCLA user record.

Adding logic to handle new users by:

1. Listening to new user signup events from user service
1. Sync user service users with EasyCLA

**Comment by dealako** [comment]
Merged: https://github.com/communitybridge/easycla/pull/2606

Process:

1. Lookup user in local database, if found: continue, otherwise:
1. Lookup user in User Service, if found: continue

**Comment by vinod-kadam** [comment]
This is deployed to DEV, Staging & PROD.

**Comment by WillsonHG** [comment]
the is verified on prod, user was able to add cla manager.
