### ISSUE TITLE
v2 project-cla-groups entry being created without date_created or date_modified

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2594]
## Summary
When a user creates a cla group from the PCC, the entry in the "projects-cla-groups" table has no event time/date associated with it.

![image](https://user-images.githubusercontent.com/46732999/107293361-7f847780-6a39-11eb-99a5-82e8aba5a459.png)

**Comment by dealako** [comment]
Created PR: https://github.com/communitybridge/easycla/pull/2595

**Comment by WillsonHG** [comment]
was this deployed to prod? It is still happening on prod
![image](https://user-images.githubusercontent.com/46732999/107788523-81db2000-6d1e-11eb-963d-3d1f6f000c30.png)

**Comment by WillsonHG** [comment]
confirmed fixed
