### ISSUE TITLE
Error is displayed while re-enforcing CLA for GitHub Organization

### ISSUE THREAD

**Issue by dibyaranjanlf** [communitybridge/easycla#2600]
## Error is displayed while re-enforcing CLA for GitHub Organization

1. On admin portal staging env, create a CLA group, connect a new GitHub organization to a project, and complete the process by installing EasyCLA.
2. Enforce CLA on all repositories, un-enforce, and try to re-enforce by switching the Enforce CLA toggle button. It shows the following error:

queryName:"enableCla"
error:"{"Code":"409","Message":"EasyCLA - 409 Conflict - unable to add repository - repository already exists for projectSFID: a097c000007oCARAA2 - error: GitHub repository already exists with repository name: LF-Documentation/Repo-1","x-request-id":"3897b840-6aee-11eb-9bf4-9d0fe35c4cdd"}"

## Expected behavior

Un-enforcing, and re-enforcing CLA on repositories should behave normal. 

## Screenshots

![image.png](https://images.zenhubusercontent.com/5ff7320002fff1248f0b8ae8/fb258342-e1aa-407b-9661-1f39408b550c)

* Environment:
  - [ ] STAGING

**Comment by vinod-kadam** [comment]
This is deployed to DEV, Staging & PROD.

**Comment by vinod-kadam** [comment]
This is deployed to DEV, Staging & PROD.

**Comment by manishv09** [comment]
Verified on Staging environment and found working fine as expected. Please refer the video attached for reference.
[Uploading... 2600-11022021.mp4]

**Comment by dibyaranjanlf** [comment]
Verified on both Dev and Staging environment and found working fine.
