### ISSUE TITLE
V2 email text changes (as provided by Pranab)

### ISSUE THREAD

**Issue by vinod-kadam** [communitybridge/easycla#2602]
Pranab reviewed the emails sent for EasyCLA v2 version. He has updated the below document with the text changes needed.
https://docs.google.com/document/d/1jFlSq1tx66LbBwGbSfJm3QS4st68GblfzBEMZRya9gk/edit#heading=h.4d2wud5ptbi2

**Comment by vinod-kadam** [comment]
This is deployed to DEV, Staging & PROD.

**Comment by ashav-github** [comment]
@vinod-kadam This is a huge list and time consuming verification. I will try to cover whatever I can. Today, I tested few scenarios where I received emails. Yet to validate the email content.
