### ISSUE TITLE
Allow CLA manager to opt out of "Approved List" updates.

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2604]
## Summary

A cla manager may not want to be alerted when other managers edit the approved lists.

## Background

In the corporate console, a cla manager adds or removes criteria from an approved list of contributors, the other cla managers are alerted. The other cla managers would like the option to opt out of the alerts.

## User Story

A cla manager, I may not want to receive an email every time the approved list is updated.

Ideas - 
Create link on the email to "Stop getting these notifications."
In the corporate console, implement a checkbox to "Opt out of Approved List notifications."

## References

- This was a suggestion from the community.

**Comment by dealako** [comment]
Won't fix. Out of scope of current product requirements/features.
