### ISSUE TITLE
"getProjectGithubOrganizations" returns 404 after adding new Organization in PCC

### ISSUE THREAD

**Issue by tejasadg** [communitybridge/easycla#2611]
Steps to reproduce:-
- Add a new GitHub Organization.
- Configure GitHub Organization using Bot.
- Return to the GitHub Organization page and click on the "I am done button"

The error returned from API
{"Code":"404","Message":"EasyCLA - 404 Not Found - github organization with project SFID not found: a096s00000045PTAAY","x-request-id":"019f2f70-6b99-11eb-8e86-472562d6efef"}"

API link
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/getProjectGithubOrganizations

**Comment by vinod-kadam** [comment]
This is deployed to DEV, Staging & PROD.

**Comment by manishv09** [comment]
Verified and found working fine. Please refer the attached video for your reference.

[Uploading... 2611-11022021.mp4]

**Comment by vinod-kadam** [comment]
Tejas faced this issue; contacted Harold & found that the issue was coming for old project. So Tejas created a new project & he didn't face the issue - so seems data issue for old project.

**Comment by tejasadg** [comment]
@wanyaland For standalone project After adding a GitHub org for a project (https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/addProjectGithubOrganization).
The newly added org is not returned as a response from the get GitHub org API (https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/getProjectGithubOrganizations).
Dev env details
Project : a096s00000045haAAA
