### ISSUE TITLE
V2 corporate console not loading projects with LF Projects, LLC as parent

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2616]
## Summary

When a corporate user clicks on 'osquery' or 'o-ran', the EasyCLA information does not load for them.

## Background
 In the member portal, click the listing under either 'project group' or 'No. of Projects' for the 2 projects O-RAN and OSquery. Neither project loads the easycla data. There are no errors in the console. The common factor for these projects is that LF Projects, LLC is the parent project.

## Expected behavior

A child project or project group of 'LF Projects, LLC' should display in the same manner as a child project of "The Linux Foundation"

## Screenshots
Does not load
![image](https://user-images.githubusercontent.com/46732999/107589530-3b79aa00-6bd4-11eb-8a4d-44b6914eee86.png)

**Comment by dealako** [comment]
Created PR to help resolve: https://github.com/communitybridge/easycla/pull/2617

- Added support for projects with 'LF Projects, LLC' parent

**Comment by dealako** [comment]
Deployed to DEV

**Comment by WillsonHG** [comment]
This appears to be resolved in Prod.
