### ISSUE TITLE
Run SFID migration script for projects

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2619]
The following projects need to be migrated to new SFID:

- [ ] CHIPS Alliance Fund a092M00001G4R7xQAF to CHIPS Alliance Project a092M00001IkUKqQAN
- [ ] GraphQL Foundation a092M00001G4R8CQAV to GraphQL Specification a092M00001JWs6vQAD
- [x] OPNFV Inc. - Archived a0941000002wBywAAE to OPNFV a092M00001IkOVbQAN

Using the script created here https://github.com/communitybridge/easycla/issues/2404

**Comment by dealako** [comment]
work is complete and/or covered under a migration task. closing ticket.
