### ISSUE TITLE
When selecting ONAP in v2 console, message "EasyCLA is not enabled"

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2620]
## Summary

When selecting the project ONAP under the LF Networking Fund group, the message "EasyCLA is not enabled for this project please work with the project manager to get EasyCLA enabled" appears.

ONAP is in the projects-cla-groups table with what appears to be the correct information: 
{
  "cla_group_id": "b71c469a-55e7-492c-9235-fd30b31da2aa",
  "cla_group_name": "ONAP",
  "date_created": "2020-10-13T17:48:00.539321+0000",
  "date_modified": "2021-01-20T15:52:26.990694+0000",
  "foundation_name": "LF Networking",
  "foundation_sfid": "a094100000aErheAAC",
  "note": "Added mapping as part of a database migration on: 2020-10-14 00:49:07.292277",
  "project_name": "Open Networking Automation Platform",
  "project_sfid": "a092M00001IV4BoQAL",
  "repositories_count": 0,
  "version": "v1"
}

This is the only project which shows this error when selected.

**Comment by dealako** [comment]
Resolved. Closing ticket.
