### ISSUE TITLE
Clicking on Enforce CLA is giving an error

### ISSUE THREAD

**Issue by vinod-kadam** [communitybridge/easycla#2623]
I created a new standalone project as follows on Dev environment:
TLF (Incorporated Entity)
	vinodd1standalone (Subproject); Legal Parent = TLF

And created a new org by name vinodd1standaloneorg.

In Admin Console, I created a CLA group for the above project and connected vinodd1standaloneorg with it.
Clicking on Enforce CLA gave the following error.
![image.png](https://images.zenhubusercontent.com/5e9e9952b186e1325cf5608a/d6768485-201d-4cba-bf17-78df18358a77)

Note: vinodd1standaloneorg is not connected with a CLA group of any other foundation/standalone projects.

**Comment by dealako** [comment]
Harold indicates that this issue is fixed as part of PR: https://github.com/communitybridge/easycla/pull/2621 which is currently deployed to DEV.

**Comment by mlehotskylf** [comment]
@wanyaland is this fixed? David indicated above this should be fixed as part of PR: https://github.com/communitybridge/easycla/pull/2621

**Comment by thakurveerendras** [comment]
Tested on dev site & prod environment and found that it is not reproducible as reported, So closing this ticket
