### ISSUE TITLE
Unable to configure Github Org. for a Standalone project Entity type=Series LLC, Legal and Parent project is 'LF Project, LLC'

### ISSUE THREAD

**Issue by ashav-github** [communitybridge/easycla#2624]
Steps:

1. Create a standalone project in Salesforce where Entity type=Series LLC, Legal and Parent project is 'LF Project, LLC'
2. Allow project scope to your user with the newly created project through IAM.
3. Login to Admin Console and locate the project, create CLA Group
4. Click on 'Manage' button, it takes you to the Github configuration page

Actual Result: On github configuration page, it throws below error:

**error:"{"Code":"403","Message":"EasyCLA - 403 Forbidden - user ashav.lfdevadmin does not have access to list projects with project scope of: a092M00001IkOVVQA3","x-request-id":"316da430-6d37-11eb-8d2a-216bc2325840"}"**

Expected Result: Github configuration should be allowed.

**Comment by ashav-github** [comment]
![image.png](https://images.zenhubusercontent.com/5f6b335ce9044e3973ea11f9/f272e530-d14f-4175-af47-52f97cc9c494)

**Comment by vinod-kadam** [comment]
I think this was fixed & merged to Dev/Staging/PROD on last Friday.
Please verify.

**Comment by vinod-kadam** [comment]
As confirmed by @ashav-github, she verified the fix on Staging & it is working fine. So, marked the ticket as QA Done.
