### ISSUE TITLE
PCC - Enrolled repositories are not being notated in repositories table.

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2630]
## Summary

When a repository is enabled for the first time, a note that the repository was created is made on the repository row in the repositories table.
When the repo is unenrolled, a note is appended.
When the same repo is reenrolled, a note is not appended.

The correct events are being created in the event logs each time the repo is enrolled or unenrolled.

It appears the act of reenabling a repository is not creating the note on an existing repo row in the database.

![image](https://user-images.githubusercontent.com/46732999/107835433-7c55f800-6d67-11eb-9e8a-8aad42e76cdb.png)

**Comment by dealako** [comment]
Created PR: https://github.com/communitybridge/easycla/pull/2631

![Screen Shot 2021-02-12 at 5.02.02 PM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/f43ce887-34fc-4d20-bb05-002118226d6b)

![Screen Shot 2021-02-12 at 5.02.08 PM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/4d4faa5e-a2ef-49df-9b8c-a5bee2c468c5)

**Comment by dealako** [comment]
Deploying to DEV

**Comment by vinod-kadam** [comment]
This is deployed to Staging.

**Comment by vinod-kadam** [comment]
This is deployed to PROD as well. @WillsonHG  please verify on PROD.

**Comment by WillsonHG** [comment]
I have verified that reenabling a repo creates a note on prod now
