### ISSUE TITLE
PCC - Renaming CLA group does not rename the group in the projects-cla-groups table.

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2632]
## Summary
In the PCC, when a user selects the pencil to edit the cla group, they are able to edit the name or description. When editing the name, only the name in the projects table changes, but the  name in the projects-cla-groups table does not.
![image](https://user-images.githubusercontent.com/46732999/107837014-1bc9b980-6d6d-11eb-9026-546ac5dc8d34.png)

**Comment by dealako** [comment]
Created PR: https://github.com/communitybridge/easycla/pull/2631

![Screen Shot 2021-02-12 at 5.02.02 PM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/d761cf0b-8e7d-4099-bd8c-95c968e1eb57)

![Screen Shot 2021-02-12 at 5.02.08 PM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/17acfb2f-33fd-482c-95ee-813b396d9063)

**Comment by vinod-kadam** [comment]
The fix is deployed to DEV & Staging.

**Comment by vinod-kadam** [comment]
I verified this on Staging for:
standalone project,
project level cla group (which has a child project)
foundation level cla group
And also check if it is reflected on Corporate Console.
So, marking it as QA Done.

**Comment by vinod-kadam** [comment]
This is also deployed to PROD.

**Comment by WillsonHG** [comment]
verified on prod
