### ISSUE TITLE
v2 Contributor Console PROD - broken links in header

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2633]
## Summary

When a contributor comes to the contributor console from a github pull request, the links in the head for "Project Login", "CLA Manager Login", and "Developer" are broken.

## Expected behavior

- [x] Project Login should link to https://projectadmin.lfx.linuxfoundation.org/

- [x] CLA Manager Login should link to https://member.lfx.linuxfoundation.org/

- [x] Developer  - currently linking to broken docs link, could go to https://docs.linuxfoundation.org/lfx/easycla/contributors

![image](https://user-images.githubusercontent.com/46732999/107839738-f55f4a80-6d7b-11eb-89a7-0b4cb0d460e8.png)

**Comment by dealako** [comment]
@amolsontakke3576 this one is for you...

**Comment by dealako** [comment]
Pushed @amolsontakke3576 changes to DEV, STAGING, and PROD.  Ready for QA.

**Comment by vinod-kadam** [comment]
@WillsonHG  please verify it.

**Comment by WillsonHG** [comment]
Hi @amolsontakke3576  The Docs are going to a page not found. You can use the link I provided https://docs.linuxfoundation.org/lfx/easycla/contributors

**Comment by amolsontakke3576** [comment]
I have raised PR for this.

**Comment by vinod-kadam** [comment]
This is deployed to DEV, Staging & PROD.

**Comment by WillsonHG** [comment]
confirmed this is fixed in prod
