### ISSUE TITLE
v2 Contributor Console - email sent to company admin needs changes

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2634]
## Summary

When a contributor is gated, selects corporate signature, and their company has not signed a ccla - the contributor selects to send email to company admin. An email is not received by the company admin.

sent message and api response
![image](https://user-images.githubusercontent.com/46732999/107840280-66543180-6d7f-11eb-8155-18c12e1145b4.png)

correct permissions in iam on user
![image](https://user-images.githubusercontent.com/46732999/107840291-88e64a80-6d7f-11eb-956e-f16899419c0c.png)

no email sent from mandrill, last one sent was to icla signer

![image](https://user-images.githubusercontent.com/46732999/107840305-b206db00-6d7f-11eb-9a14-dc158e08b887.png)

**Comment by dealako** [comment]
Assigned to Harold.

**Comment by wanyaland** [comment]
I have tested and this use case works fine on my end..
Attached is the email received (Tested on Staging env)
```
Hello Harold Wanyama,

This is a notification email from EasyCLA regarding the project(s) AshaStF3.

The following contributor is requesting to sign CLA for organization:

wanyaland (wanyaland@gmail.com)

Before the user contribution can be accepted, your organization must sign a CLA.

Kindly login to this portal https://lfx.staging.platform.linuxfoundation.org and sign the CLA for one of the project(s) AshaStF3.

Please notify the contributor once they are added to the approved list of contributors so that they can complete their code contribution.

If you need help or have questions about EasyCLA, you can read the documentation or reach out to us for support.

EasyCLA Support Team```

**Comment by wanyaland** [comment]
@WillsonHG , @dealako 
On further investigation I hadnt used the 'contactAdmin' link in the flow and happened to get email. For the contactAdmin flow email got from the organization-service for company Admins are masked in the form `s**************8@p********z.com` . So the endpoint doesnt know which email to use. I have alerted the core-services team about how to progress on this front

**Comment by vinod-kadam** [comment]
The fix is deployed to DEV & Staging.

**Comment by vinod-kadam** [comment]
This is deployed to DEV & Staging.

**Comment by vinod-kadam** [comment]
As updated by @manishv09, this is verified on Staging.

**Comment by WillsonHG** [comment]
I have verified the company admin now receives an email. However I am not satisfied with the content - Is this the exact email sent to the cla manager as well?
![image](https://user-images.githubusercontent.com/46732999/108453076-b4fa4380-7237-11eb-9360-60260344e44c.png)

**Comment by WillsonHG** [comment]
The one going to the cla manager from this flow instead of the admin is the same, yet different mistakes in it.

![image](https://user-images.githubusercontent.com/46732999/108453849-4e762500-7239-11eb-9268-4db119c2fd2a.png)

**Comment by vinod-kadam** [comment]
@pranab-bajpai to provide new content for company admin,

**Comment by pranab-bajpai** [comment]
**Scope: When Contributor Needs to get on approval list and doesn't know who is the CLA Manager for their company**
**Recipient: Company Admin
Subject: CLA: Invitation to Sign the {Company Name} Corporate CLA**
Body:
Hello {company admin for <company name>},
The following contributor would like to submit a contribution to {project_name} and is requesting to be added to the approval list as a contributor for your organization:
    {user_name} <{user_email}>
Before the contribution can be accepted, your organization must sign a CLA. Either you or someone whom to designate from your company can login to this portal <link> and sign the CLA for this project <project_name>. Please notify the contributor once they are added so that they may complete the contribution process.
lfcla.com
{cla help notice….} {cla signoff}
EasyCLA support team

**Comment by wanyaland** [comment]
@pranab-bajpai For the contributor console level the system is aware of cla-group ,which happens to be mapped to one or more SF Projects . Should we use the potential list of projects or just CLA Group
cc @dealako @vinod-kadam

**Comment by vinod-kadam** [comment]
This is deployed to DEV, Staging & PROD.

**Comment by vinod-kadam** [comment]
As updated by by @manishv09 in the standup today, he has verified this one.  So, marked it as QA Done.
