### ISSUE TITLE
Unable to sign CCLA with designated CLA Manager (who doesn't have LFID)

### ISSUE THREAD

**Issue by ashav-github** [communitybridge/easycla#2636]
Unable to sign CCLA. Also, CLA Manager and CLA Signatory role is not assigned in IAM to the user (doesn't have LF ID) who is elected as CLA Manager by a contributor while signing CCLA.

Pre-condition: Have a Standalone project created with Entity Type=Series LLC. Parent and Legal Parent = LF Projects, LLC

Steps:

1. Login to Admin Console and create a CLA group for the standalone project.
2. Configure Github org and install EasyCLA bot.
3. Login to Github as a contributor and create a new org, select someone else as CLA Manager who doesn't have LF ID.
4. The invited user will receive an email with subject line: 'EasyCLA: Invitation to create LF Login and complete process of becoming CLA Manager for project: LF Projects, LLC'
5. Accept the invite and create a new LF account, verify your email->this will take you to inside the corporate console
6. Search for the standalone project which you want to sign CCLA (Note: the email doesn't mention about the project name)
7. Click on Sign CCLA and proceed till you reach the 'Generating Document' step

Actual Result: It throws error message at this step 'CLA System is not able to support your request. Please Click here to open a support ticket.'
If you check IAM, the user doesn't get CLA Manager and CLA Signatory. He has cla-manager-designee role. 

![image.png](https://images.zenhubusercontent.com/5f6b335ce9044e3973ea11f9/49f48883-7598-47a5-806f-73ade84378c9)

Expected Result: CLA Manager should be able to sign CCLA without any error.

**Comment by dealako** [comment]
For helping track down these issues, it would be helpful to enumerate the details:

**Comment by dealako** [comment]
Trying to track this CCLA signging request down. Can't seem to find an error:

**Comment by wanyaland** [comment]
@David.. I happened to reproduce this issue and the root cause was getting cla-group for a project under LF Project, LLC. The child project used LFProject, LLC in the mappings records query

**Comment by vinod-kadam** [comment]
As updated by @wanyaland , this is deployed to DEV & Staging.

**Comment by vinod-kadam** [comment]
After Harold confirmed that fix is deployed to Staging, I tried it for a designed CLA Manager who has LFID & it worked fine for me on Staging,
@ashav-github  to try it for designed CLA Manager who doesn't have LFID.

**Comment by ashav-github** [comment]
@vinod-kadam @wanyaland I retested this on Stage and its working fine now. 
Test Data: New org created: Nykaa | NewLF ID: ashav.nykaa | LF Email: ashav+nykaa@proximabiz.com | GH Repo: ashav-test-stgfeb1-org1/stgfeb1-repo1

**Comment by vinod-kadam** [comment]
This is deployed to PROD as well.
