### ISSUE TITLE
Allow brackets in GitHub Username Whitelists

### ISSUE THREAD

**Issue by jpalmerLinuxFoundation** [communitybridge/easycla#264]
**Summary**

Describe the feature - a clear and concise description of what the feature is.

**Background**

Provide context to the issue - provide steps to indicate how this feature would be realized, such as:
1. Go to 'corporate.*.lfcla.com'
2. Click on a company
3. Click on a project
4. Click on the Pencil icon to the right of 'GitHub Whitelist'
5. Attempt to enter a username with open and/or closed brackets.
6. Currently, you cannot save the list if there is a user who exhibits open or closed brackets in the username [ ] 

**User Story**

As a Corporate CLA Manager or Signatory, I need to be able to whitelist username with open & close brackets in the username, so that I can add any type of user.

**Acceptance Criteria**

The "done" criteria when this feature or problem is resolved.  Such as:
1. Unit Tests added and running in CI
2. Functional Tests updated to cover feature, if applicable
2. Demonstrate the set of capabilities to the product team while the code is
   running in the STAGING environment.

**References**

![image](https://user-images.githubusercontent.com/51214959/66356021-16fe2580-e92f-11e9-90ea-d4b3a26e9ddc.png)

**Comment by dealako** [comment]
@jpalmerLinuxFoundation after some searching and attempting to create a new test GitHub username [via the GitHub signup page](https://github.com/join?source=header-home), I discovered:

- User names may only contain alphanumeric characters or single hyphens, and cannot begin or end with a hyphen
- User names maximum length is 39 characters

The current codebase contains a regular expression to test these rules, similar to https://github.com/shinnn/github-username-regex#githubusernameregex

My question: given that the above example doesn't appear to be valid, should we relax the form validation or keep it the same?  The bigger question is: how was this user name created in the first place?

References

1. [Our code's regex](https://github.com/communitybridge/easycla/blob/master/cla-frontend-corporate-console/src/ionic/modals/whitelist-modal/whitelist-modal.ts#L95) - missing the 39 character limit restriction
1. [Example Regex](https://github.com/shinnn/github-username-regex#githubusernameregex)

**Comment by jpalmerLinuxFoundation** [comment]
@dealako, I think there might be a nuance when it comes to bots. Users and bots may not be exactly the same thing and may have different rules for what's permitted in their username.
Ultimately, I get a response from GitHub's `users` endpoint for both `dependabot-preview[bot]` & `dependabot[bot]` and I'd like the flexibility to whitelist bots in the corporate CLA console

https://api.github.com/users/dependabot-preview[bot]
https://api.github.com/users/dependabot[bot]

**Comment by dealako** [comment]
@jpalmerLinuxFoundation - deployed, please validate and confirm this addresses the ticket.
