### ISSUE TITLE
Approved contributors detail in Admin console should display github username rather than numeric value

### ISSUE THREAD

**Issue by ashav-github** [communitybridge/easycla#2640]
Pre-conditon: Have a CLA group where CCLA is signed and approved contributor is added.

Steps:

1. Login to Admin console and locate the project.
2. Go to CLA group->Signatures->Signed CCLA->Click on 'View List' under 'Approved Contributors' column.

Actual Result: It shows github_id number.
![image.png](https://images.zenhubusercontent.com/5f6b335ce9044e3973ea11f9/0b45fa38-4f47-4b83-93ac-7ff5eb7e59cc)

Expected Result: It would make more sense for Admin if contributor's github username is displayed in place of github id.

**Comment by vinod-kadam** [comment]
@wanyaland  as discussed pass github username for github_id column. Don't change the API response to pass  github_username column name instead of  github_id since it may break UI - anyway in the very near future retool UI will be replaced by angularJS version.

**Comment by vinod-kadam** [comment]
I verified it on Staging. Now github username value is displayed which is correct.
![image.png](https://images.zenhubusercontent.com/5e9e9952b186e1325cf5608a/6a43142a-1eaa-4a96-8698-dfd988a5d7a1)
