### ISSUE TITLE
v2 corporate console - Event recorded for CLA signatory incorrect.

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2648]
When a CLA Manager sends the CLA to the CLA Signatory and the signing is complete, an event is created in the Event log that states "A corporate signature was signed for project PROJECT and company COMPANY by user CLA MANAGER."

Instead of the name of the CLA Manager, the name of the CLA Signatory should be recorded. The cla manager DID NOT sign the cla. This is an important legal distinction and should be recorded correctly.

![image](https://user-images.githubusercontent.com/46732999/108004123-e1595a00-6fc2-11eb-89ee-b71720afbb0f.png)

**Comment by makkalot** [comment]
I suggest we use signatory name from Docusign Form which we capture on callback

**Comment by vinod-kadam** [comment]
This is deployed to DEV.

**Comment by vinod-kadam** [comment]
This is deployed to Staging & PROD as well.

**Comment by ashav-github** [comment]
@vinod-kadam Tested on Stage and Activity Log captures the CLA Signatory name when CCLA was signed by Signatory who doesn't have LFID. PFB the screen shot.

![CLASignatory-ActivityLog.jpg](https://images.zenhubusercontent.com/5f6b335ce9044e3973ea11f9/4c148304-3941-4e0c-b91e-ab7045e68755)

**Comment by WillsonHG** [comment]
I have verified this is fixed in production.
