### ISSUE TITLE
v2 contributor console PROD - email sent to cla manager to be added to approved list has bad link

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2649]
## Summary

When a contributor sends an email to the cla manager to request to be added to the approval list, the email has a bad link to the member portal. It is also missing the cla group name.

![image](https://user-images.githubusercontent.com/46732999/108005735-84ac6e00-6fc7-11eb-9045-080b46f76f5f.png)
 

- [ ] In the sentence "The following contributor would like to submit a contribution to the CLA Group CLAGROUP and is requesting to be approved as a contributor for your organization:"  it is missing the cla group name.
- [x] I'm not sure what the "signing entity name" is referring to in the contributor information section and should just be "Name".
- [x] Approval can be done at https://member.lfx.linuxfoundation.org/

FWIW, this email is not in the master email list @pranab-bajpai The v2 section still refers to the "Allow List" email that is not correct. 
![image](https://user-images.githubusercontent.com/46732999/108006158-b7a33180-6fc8-11eb-91a7-46dbcfd16654.png)

**Comment by vinod-kadam** [comment]
PR raised

**Comment by vinod-kadam** [comment]
This is deployed to DEV, Staging & PROD. @WillsonHG  please verify it on PROD.

**Comment by WillsonHG** [comment]
The first sentence has the company name inserted incorrectly before "CLA Group ....".

![image](https://user-images.githubusercontent.com/46732999/108456648-c430bf80-723e-11eb-8c4c-c7ae48beacc9.png)

**Comment by vinod-kadam** [comment]
I am closing this ticket as I have logged a separate ticket for removing the organization name (which is appearing before CLA Group) - the ticket is https://app.zenhub.com/workspaces/easycla-5ed619832c71a855a76ef404/issues/communitybridge/easycla/2684
