### ISSUE TITLE
Make the CLA PDF available for download pre-Docusign

### ISSUE THREAD

**Issue by mkdolan** [communitybridge/easycla#265]
**Summary**

Make a downloadable PDF of the CLA available before going into the signature process.

**Background**

Companies decide they want to work on a project, independent of any PR. They want to be able to access the CLA they will be required to sign and get it pre-approved by their legal before making a first contribution. "Finding" the CLA is currently not obvious and requires starting a signature which presents a level of fear.

**User Story**

As a company, I'd like to have the CLA tool show a list of projects with an option to "View/Download CLA(s)" or "Sign CLA(s)". That allows a direct link to one page with all CLAs that can be signed.

**Acceptance Criteria**

1. User can be sent to a URL where there is an option to view/download the CLAs independent of going into the Docusign process.
2. User is able to review the exact CLA they will be signing in EasyCLA.

**References**
n/a

**Comment by jpalmerLinuxFoundation** [comment]
Hi @mkdolan, do you think we could offer this in the /docs area and maybe somewhere on the lfcla.com homepage?

**Comment by directionless** [comment]
I've been bumping into this as well.

I'm not sure what you mean by "offer this in the /docs area and maybe somewhere on the lfcla.com"

I imagine if I were trying to get my legal team to signoff on a CLA, I'd need to clearly show them a CLA specific to the project. As EasyCLA is hosted on lfcla.com, I expect this would be too. But I imagine it would look a lot more like lfcla.com/project/osquery, and offer options to view, download, or sign the CLA.

**Comment by caniszczyk** [comment]
friendly bump here as it's a common request

**Comment by swinslow** [comment]
+1, this is going to be important to a lot of signers so that their legal teams can give the OK to sign the CLA.

**Comment by mkdolan** [comment]
+1 as well. We had discussed this at one point, but @caniszczyk ping is a good reminder to make sure we get this into the next version update.

**Comment by dealako** [comment]
We've added and merged the preview feature to the v2 API. Working to integrate with the v2 Contributor Console.

**Comment by nirupamav** [comment]
@amolsontakke3576 
What should I test in this ticket

**Comment by nirupamav** [comment]
Verified in ticket #1604 and hence closing the ticket

**Comment by amolsontakke3576** [comment]
@nirupamav You need to verify the download PDF for ICLA and CCLA (PFA)

![Screenshot from 2020-09-08 15-21-31.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/b90647b1-89c7-4c10-b4b0-05ac81308cd7)
