### ISSUE TITLE
v2 member portal - document link went stale, does not refresh.

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2650]
When a corporate user clicks to download their copy of the CLA, the link is always stale. After clicking 'yes' to refresh it, the page does not refresh itself, it will spin until the user refreshes manually.

![image](https://user-images.githubusercontent.com/46732999/108007932-23879900-6fcd-11eb-995b-acee5507b3cc.png)

![image](https://user-images.githubusercontent.com/46732999/108007963-30a48800-6fcd-11eb-833e-4cfd9fccb2c5.png)
![image](https://user-images.githubusercontent.com/46732999/108007999-4a45cf80-6fcd-11eb-851c-50427e4f4354.png)

**Comment by dealako** [comment]
Recommend we promote this to tier-2 as I haven't been able to refresh and download.

**Comment by vinod-kadam** [comment]
Closing this as created corresponding ticket in LFX board
https://jira.linuxfoundation.org/browse/LFX-3127
