### ISSUE TITLE
v2 member portal - event log does not show who added or removed cla manager

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2651]
When a cla manager adds or removes another user as a cla manager, the event log does not show who performed the action. It has the 'user' as the cla manager that was added or deleted. The user who performed the action should be shown.

![image](https://user-images.githubusercontent.com/46732999/108009683-33a17780-6fd1-11eb-8a8b-02ea44397827.png)

**Comment by dealako** [comment]
Created PR: https://github.com/communitybridge/easycla/pull/2880

**Comment by manishv09** [comment]
Verified on Staging and found for Addition or removal log are showing different names. 
![image (12).png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/1d07dc10-bc63-4452-9075-44e3ff0cfc76)

On Staging Corporate console found that names are different for the CLA Manager added and removed as CLA Manager. Please refer screencast below highlighted in Red
Right corner is user who performed the action while on start of log statement is the user name who was added or removed

**Comment by dealako** [comment]
Deployed to DEV, STAGING, and PROD.

**Comment by vinod-kadam** [comment]
As discussed in the standup, @manishv09 please close this ticket as the main functionality is working fine however please log a separate minor ticket for showing full name instead of LFID for the user removed.

**Comment by manishv09** [comment]
Raised a minor issue for the mentioned names discrepancy on the activity log. 

https://app.zenhub.com/workspaces/easycla-5ed619832c71a855a76ef404/issues/communitybridge/easycla/2886
