### ISSUE TITLE
v2 - member portal - no email sent to contributor when added/removed from Approved list

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2652]
When a user is added or removed from an approved list, the user should receive an email notification.

User added and removed by email willsonhg2+ccla@gmail.com The user has no LF Account.

No email sent to the user as evidenced by the logs:

![image](https://user-images.githubusercontent.com/46732999/108011391-fc34ca00-6fd4-11eb-9a7e-d15b3fd5824d.png)

**Comment by vinod-kadam** [comment]
Pranab had tried with github user name and the contributor received an email.
Pranab to try with github email & Heather to try with email address.
