### ISSUE TITLE
Steve's Feedback: Change the sign-off line "The LF Engineering Team" to "EasyCLA Support Team" for EasyCLA emails

### ISSUE THREAD

**Issue by vinod-kadam** [communitybridge/easycla#2673]
Change the sign-off line "The LF Engineering Team" to "EasyCLA Support Team" in all the easycla emails. 
Some of the emails have "EasyCLA Support Team" while some have "The LF Engineering Team" - it should be  "EasyCLA Support Team".

**Comment by vinod-kadam** [comment]
This is deployed to DEV, Staging & PROD.

**Comment by manishv09** [comment]
Verified on Staging today and found changes are getting reflected. Please follows below emails for reference:
1. CLA Manager
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/36a42045-6c3e-4bd4-8b0b-f6882e7f0e81)
2. CLA Signatory
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/9f1689e8-33b
7-448a-b5fe-49fbbad4fff5)
3. CLA Manager Designee
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/26a297cd-054e-48f2-8c9e-f114d1726358)

**Comment by manishv09** [comment]
4. Added as CLA Manager for Project
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/33b9e74f-9675-41a4-9d45-140d88aae9d6)
5. CLA Manager Added Notice
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/f24dd0aa-ab01-4df6-ac58-8fee371a2776)
6. Approval List Update 
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/df8cf0f0-a809-4037-9c14-fe830905d06e)
