### ISSUE TITLE
Links in emails should take the user directly to the project page in Corporate Console

### ISSUE THREAD

**Issue by vinod-kadam** [communitybridge/easycla#2677]
Links in emails should take the user directly to the project page in Corporate Console & not the dashboard

**Comment by makkalot** [comment]
Possible Email Templates with instructions to sign cla

- V2DesigneeToUserWithNoLFIDTemplate : [https://github.com/communitybridge/easycla/blob/380be38330c2a4342d1d000cd7a39a08798dccc0/cla-backend-go/emails/v2_cla_manager_templates.go#L171](https://github.com/communitybridge/easycla/blob/380be38330c2a4342d1d000cd7a39a08798dccc0/cla-backend-go/emails/v2_cla_manager_templates.go#L171)
- V2OrgAdminTemplate : [https://github.com/communitybridge/easycla/blob/380be38330c2a4342d1d000cd7a39a08798dccc0/cla-backend-go/emails/v2_cla_manager_templates.go#L49](https://github.com/communitybridge/easycla/blob/380be38330c2a4342d1d000cd7a39a08798dccc0/cla-backend-go/emails/v2_cla_manager_templates.go#L49)
- V2ContributorToOrgAdminTemplate : [https://github.com/communitybridge/easycla/blob/380be38330c2a4342d1d000cd7a39a08798dccc0/cla-backend-go/emails/v2_cla_manager_templates.go#L77](https://github.com/communitybridge/easycla/blob/380be38330c2a4342d1d000cd7a39a08798dccc0/cla-backend-go/emails/v2_cla_manager_templates.go#L77)
- V2CLAManagerDesigneeCorporateTemplate : [https://github.com/communitybridge/easycla/blob/380be38330c2a4342d1d000cd7a39a08798dccc0/cla-backend-go/emails/v2_cla_manager_templates.go#L101](https://github.com/communitybridge/easycla/blob/380be38330c2a4342d1d000cd7a39a08798dccc0/cla-backend-go/emails/v2_cla_manager_templates.go#L101)
- V2ToCLAManagerDesigneeTemplate : [https://github.com/communitybridge/easycla/blob/380be38330c2a4342d1d000cd7a39a08798dccc0/cla-backend-go/emails/v2_cla_manager_templates.go#L148](https://github.com/communitybridge/easycla/blob/380be38330c2a4342d1d000cd7a39a08798dccc0/cla-backend-go/emails/v2_cla_manager_templates.go#L148)
- func (s *service) RequestCompanyAdmin : [https://github.com/communitybridge/easycla/blob/831c861b5fc6bb61d4b87c414bb93e1449f09356/cla-backend-go/v2/company/service.go#L1700](https://github.com/communitybridge/easycla/blob/831c861b5fc6bb61d4b87c414bb93e1449f09356/cla-backend-go/v2/company/service.go#L1700)

**Comment by makkalot** [comment]
```
const projectDetails = project.projects; // project object from GET_PROJECT endpoint
    // No SF Projects for this CLA Group
    if (projectDetails.length === 0) {
      // No SFID associated with project so redirect at corporate console dashboard.
      url = this.corporateV2Base + 'company/dashboard';
    } else if (project.signed_at_foundation_level) {
      // Signed at foundation level.
      url = this.corporateV2Base + 'foundation/' + projectDetails[0].foundation_sfid + '/cla';
    } else {
        // For standalone project we must redirect to the SFID of The Linux Foundation
        url = this.corporateV2Base + 'foundation/' + project.foundation_sfid + '/project/' + project.project_sfid + '/cla';
      }
    }
```

**Comment by vinod-kadam** [comment]
As updated by @manishv09 , the project links are working fine. so, marked this ticket as QA Done.
