### ISSUE TITLE
CLA Manager is unable to see sign CCLA option on Corporate Console. 

### ISSUE THREAD

**Issue by ashav-github** [communitybridge/easycla#2692]
Pre-condition: Have a CLA group created with 2 child projects and Github org is configured.

Steps:

1. Login to github as contributor,Create PR and proceed to sign CCLA by creating new org and electing himself as CLA Manager.
2. Create new LF account and verify email
3. The CLA Manager 'ashav.loadtest' is auto-logged to Corporate console. Click on a child project to sign CCLA

Actual Result: Corporate console says 'EasyCLA is not enabled for this project please work with the project manager to get EasyCLA enabled'

Expected Result: CLA Manager should get option to sign CCLA.

![image.png](https://images.zenhubusercontent.com/5f6b335ce9044e3973ea11f9/8ecd4226-18f6-44f9-a384-c71a14c27595)

Test Data: 
AshaLoadTestFoundation2021 [LP:TLF, P: TLF | Event Type = Subproject]
 - AshaLoadTest-Child1 [LP:LF Projects, LLC | Event Type: Series LLC]
 - AshaLoadTest-Child2 [LP:LF Projects, LLC | Event Type: Series LLC]

CLA Group: AshaLoadTest-ClaGroup1 (Child1+Child2) | CCLA+ICLA
Github Repo: ashav-test-loadtest/loadtest-repo1

Priyatham Maveric Created PR with Company 'loadtestorg' | www.loadtestorg.com
Priyatham maveric created new account: ashav+loadtest@proximabiz.com | ashav.loadtest

**Comment by vinod-kadam** [comment]
This is deployed to DEV & Staging.

**Comment by ashav-github** [comment]
@vinod-kadam @wanyaland Tested on Stage and now I can see CLA sign option. Able to complete the sign-in process.
