### ISSUE TITLE
Enroll project in CLA group fails for project with ONAP structure

### ISSUE THREAD

**Issue by tejasadg** [communitybridge/easycla#2697]
Project Structure
-> TLF
  -> ONAP Parent
    -> ONAP Child
      -> ONAP Subchild
Steps to reproduce:-
1) Create a CLA group for the ONAP child project.
2) After successful CLA group creation unenroll ONAP parent from the CLA group
3) CLA group is empty with 0 projects enrolled
4) Again try to enroll the same ONAP child project into the CLA group.

ERROR:
error:"{"Code":"400","Message":"EasyCLA - 400 Bad Request - Unable to enroll salesforce foundation project: a097c000007oywzAAA in project level cla-group.","x-request-id":"9ede3730-75d1-11eb-b349-996d2e15184c"}"

**Comment by vinod-kadam** [comment]
Fix is deployed to DEV, Staging & PROD.

**Comment by vinod-kadam** [comment]
As updated by @manishv09 , he has verified it on Staging by creating similar project hierarchy as LF Networking Fund & ONAP & did e2e testing for ONAP & it works fine. So, marked it as QA Done.
