### ISSUE TITLE
Steve's Feedback: pop-up blocker issue

### ISSUE THREAD

**Issue by vinod-kadam** [communitybridge/easycla#2701]
This feedback is provided by Steve in the document https://docs.google.com/document/d/1Mq7YWegCg3Zfq_RprtV0e1kaa-Jq0AQDo-wkjucgDj0/edit?ts=603547c9#

Contributor Console: Same screen as above - After logging in:
URL: https://easycla.staging.communitybridge.org/#/corporate-dashboard/ee4543ef-b8d3-43dd-a17d-cb4e036f4418/67d713f2-443d-4701-9dd5-aa64122d9e6b

![image.png](https://images.zenhubusercontent.com/5e9e9952b186e1325cf5608a/413b5062-fe61-4d8f-9406-26b29666dfe7)

Contributor Console: After clicking “Proceed” from the box above, the tab goes back to the GitHub page. It does not go to the corporate console. This means that for someone whose pop-ups are blocked (for instance, any default install of Chrome), the user will not be able to get to the CLA Manager console. This should be fixed so that the user is taken to the CLA Manager console no matter what, even if they later have to find their way back to the GitHub page.

Here’s a recording of the issue: https://drive.google.com/drive/folders/1aT_C-D_QvqdbmnWALNd35Nrja0EmNM4F

Do the following:
1. Before displaying the message, check whether pop-up blocker is disabled or [*.]communitybridge.org is present in Allow list of pop-up settings. If any of the above is true then display the following message.
You will be redirected to the CLA Manager console where you can sign the CLA (or send it to an authorized signatory) and approve contributors on behalf of your organization.

2. If pop-up blocker is not disabled & [*.].linuxfoundation.org is also not present in Allow list of pop-up settings then display the following message.
You will be redirected to the CLA Manager console where you can sign the CLA (or send it to an authorized signatory) and approve contributors on behalf of your organization.
Note: To continue please disable pop-up blocker or add [*.]communitybridge.org to Allow list of pop-ups settings. Click here to go to pop-ups settings of your browser. 
If user clicks Proceed button then check whether pop-up blocker is disabled or [*.]communitybridge.org is present in Allow list of pop-up settings - if not then show a toast message to the user "Your browser's pop-ups settings don't allow pop-ups, please set the pop-ups settings." & show the original message again.

**Comment by vinod-kadam** [comment]
This is deployed to all environments through https://github.com/communitybridge/easycla-contributor-console/releases/tag/v1.0.46

**Comment by manishv09** [comment]
Verified on chrome browser with pop blocked and allowed as both the options and found in both the cases it navigates to same window and user is able to proceed and login to corporate console. Please refer attached video for reference:
https://images.zenhubusercontent.com/194341141/dac98867-fd9b-4c81-b2e1-212bcb78cf53/2701_26022021_both.mp4
