### ISSUE TITLE
Steve's Feedback: Email sent to contributor when they are added to approval list needs a change

### ISSUE THREAD

**Issue by vinod-kadam** [communitybridge/easycla#2705]
Email which is sent to contributor when they are added to approval list needs a change.

Subject: EasyCLA: Approval List Update for [company name] on [CLA Group Name]

Body:
Hello [Recipient Name],

This is a notification email from EasyCLA regarding the CLA Group [CLA Group Name].
You have been added to the Approval List of [company name] for [CLA Group Name] by CLA Manager [cla manager name]. This means that you are authorized to contribute to any of the following project(s) associated with the CLA Group [CLA Group Name]: [comma separated list of projects]
If you had previously submitted a pull request to any any the above project(s) that had failed, you can now go back to it and follow the link to verify with your organization.

If you need help or have questions about EasyCLA, you can [read the documentation] or [reach out to us for support].
EasyCLA Support Team

read the documentation & reach out to us for support are links with same name.

Note: Currently, the email generated mentions cla group in place of project which is incorrect - that needs to be corrected.

**Comment by manishv09** [comment]
I am still getting below email with content as follows:

Hello Manish Vaidya,

This is a notification email from EasyCLA regarding the project TestCCLA+ICLA.

The EasyCLA approval list for Proxima for project TestCCLA+ICLA was modified.

The modification was as follows:

Added GithHub User: manishvdy
If you need help or have questions about EasyCLA, you can read the documentation or reach out to us for support.

EasyCLA Support Team

**Comment by manishv09** [comment]
I verified the changed email on Staging and needs change in email body, which is as follows:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/98422f97-3474-418f-9edc-70a3e8bc576c)

**Comment by vinod-kadam** [comment]
This is deployed to DEV, Staging & PROD.

**Comment by manishv09** [comment]
Verified and found working fine. Please refer below email for reference:

Hello Manish Tata Three,

This is a notification email from EasyCLA regarding the project A-LF NETWORKING FUND-MANISH-Child001.

You have been added to the Approval List of Proxima for A-LF NETWORKING FUND-MANISH-Child001 by CLA Manager manishv.comprmgr. This means that you are authorized to contribute to A-LF NETWORKING FUND-MANISH-Child001 on behalf of Proxima.

If you had previously submitted a pull request to EasyCLA Test Group that had failed, you can now go back to it and follow the link to verify with your organization.

If you need help or have questions about EasyCLA, you can read the documentation or reach out to us for support.

EasyCLA Support Team
