### ISSUE TITLE
Steve's Feedback: In Activity Log, don't show Undefined instead show "CLA Signatory" or title accordingly 

### ISSUE THREAD

**Issue by vinod-kadam** [communitybridge/easycla#2706]
Steve's Feedback document: https://docs.google.com/document/d/1Mq7YWegCg3Zfq_RprtV0e1kaa-Jq0AQDo-wkjucgDj0/edit?ts=603547c9#

Corporate Console: For the “Activity Log”, it should not show “Undefined” as the user on the right-hand side. For something like this where it was a CLA Signatory for whom we don’t have an LF Login, it should probably just show “CLA Signatory” or something similar if we don’t have the Signatory’s name.

![image.png](https://images.zenhubusercontent.com/5e9e9952b186e1325cf5608a/aa74d8bb-44f4-47e1-bb16-379d67d2f4e8)

Note: Harold. Youssef and Vinod discussed this and it was discussed that it is better to handle it on CLA backend side then Corporate Console frontend.

**Comment by vinod-kadam** [comment]
Fix for Corporate Console logs issue was deployed to DEV, Staging & PROD through https://github.com/communitybridge/easycla/releases/tag/v2.0.6

**Comment by manishv09** [comment]
Verified on staging environment and found duplicate logs getting generated for invite send to become a CLA Manager

**Comment by manishv09** [comment]
As the issue raised for activity log is getting generated now, hence closing the issue and raising another issue for duplicate records.
