### ISSUE TITLE
Steve's Feedback: Activity Log - User None, duplicate entries

### ISSUE THREAD

**Issue by vinod-kadam** [communitybridge/easycla#2707]
Steve's Feedback document: https://docs.google.com/document/d/1Mq7YWegCg3Zfq_RprtV0e1kaa-Jq0AQDo-wkjucgDj0/edit?ts=603547c9#

- “A corporate CLA was signed for project Feb2021-CNCF-style and company Legal_SW_Ucorp by Steve CLASignatory.”
- “The user None acknowledged the CLA affiliation for company Legal_SW_Ucorp and project Feb2021-CNCF-style.” -- what does “The user None” mean? Also note the “Undefined E” label again.
![image.png](https://images.zenhubusercontent.com/5e9e9952b186e1325cf5608a/3699aabf-64f1-40f3-bbdc-02922ac8b48a)
- This log entry appears twice:
![image.png](https://images.zenhubusercontent.com/5e9e9952b186e1325cf5608a/de680560-73df-4cd8-b5a5-cfca8fd37048)

**Comment by dealako** [comment]
Should not have any more duplicate entries.  Updated activity log text and removed duplicate logic. Needs QA and verification.

**Comment by vinod-kadam** [comment]
@dealako  is this deployed to DEV & Staging. I don't see it listed in the release notes & the last release I see is 2.0.15 which was made 4 days ago.

**Comment by vinod-kadam** [comment]
This is deployed to PROD through https://github.com/communitybridge/easycla/releases/tag/v2.0.19
