### ISSUE TITLE
Activity log is not captured if modifications are done to enroll or unroll of projects done on a CLA Group

### ISSUE THREAD

**Issue by manishv09** [communitybridge/easycla#2716]
Activity log is not captured if modifications are done to enroll or unroll of projects done on a CLA Group

Breadcrum of the group: HOME / THE LINUX FOUNDATION / A-FEB-10 MULTI LEVEL PROJECTS / TOOLS / CLA / OVERVIEW

url: https://admin.staging.platform.linuxfoundation.org/apps/cla/overview#id=a097c000007oIh7AAE

Please find attached video for more information as follows:

https://images.zenhubusercontent.com/194341141/cfc70f44-2d6b-4d73-8fb9-f3873296200e/recording__119.mp4

**Comment by wanyaland** [comment]
@manishv09  based on the videos you shared .. upon a manual refresh activity log is showcased. so this happens to be a UI issue that should auto refresh upon enroll/unenroll events
cc @vinod-kadam @dealako

**Comment by tejasadg** [comment]
PR link https://github.com/LF-Engineering/admin-console/pull/678
cc: @dealako @vinod-kadam

**Comment by dealako** [comment]
Created PR: https://github.com/communitybridge/easycla/pull/2725

**Comment by manishv09** [comment]
Verified on DEV and Staging both but still the activity log is not appearing for enroll and unenroll. Even after manual refresh log is not updated. Please refer attached video for reference.

https://images.zenhubusercontent.com/194341141/c1361667-7b9f-4d85-9a8e-f1114cb712b4/2716_02032021.mp4

**Comment by dealako** [comment]
@manishv09 I have now migrated the activity log data. Can you please re-test?

**Comment by dealako** [comment]
Actually, still testing - new indexes are deploying...

**Comment by vinod-kadam** [comment]
Deployed to DEV & Staging through https://github.com/communitybridge/easycla/releases/tag/v2.0.3

**Comment by manishv09** [comment]
Verified on Staging environment and found working fine. Please refer the attached video for reference.
https://images.zenhubusercontent.com/194341141/03fa68d3-3700-45db-8630-59509ed397df/_2716_10032021.mp4

**Comment by vinod-kadam** [comment]
Deployed to PROD through https://github.com/communitybridge/easycla/releases/tag/v2.0.5.
