### ISSUE TITLE
Email sent to a CLA Signatory needs a change

### ISSUE THREAD

**Issue by vinod-kadam** [communitybridge/easycla#2718]
Following email 
--------------------
Hello Vinod Kadam,

This is a notification email from EasyCLA regarding the project vinods15foundation_clagrp3. Vinod Kadam has designated you as being an authorized signatory for Proxima. In order for employees of your company to contribute to the open source project vinods15foundation_clagrp3, they must do so under a Contributor License Agreement signed by someone with authority to sign on behalf of your company.
After you sign, Vinod Kadam (as the initial CLA Manager for your company) will be able to maintain the list of specific employees authorized to contribute to the project under this signed CLA.
If you are authorized to sign on your company’s behalf, and if you approve Vinod Kadam as your initial CLA Manager for vinods15foundation_clagrp3, please review the document and sign the CLA.If you have questions, or if you are not an authorized signatory of this company, please contact the requester at vinodk+proximasystems1@proximabiz.com.
If you need help or have questions about EasyCLA, you can read the documentation or reach out to us for support.

Thanks,
EasyCLA Support Team
--------------------
should be changed as follows:
--------------------
Hello Vinod Kadam,

This is a notification email from EasyCLA regarding the project(s): [comma separated projects] associated with the CLA Group [CLA Group Name]. Vinod Kadam has designated you as being the authorized signatory for the organization Proxima. In order for the employees of your company to contribute to any of the above project(s), they must do so under a Contributor License Agreement signed by someone with authority on behalf of your company.
After you sign, Vinod Kadam (as the initial CLA Manager for your company) will be able to maintain the list of specific employees authorized to contribute to the project(s) under this signed CLA.
If you are authorized to sign on your company’s behalf, and if you approve Vinod Kadam as the initial CLA Manager, please review the document and sign the CLA. If you have questions, or if you are not an authorized signatory of this company, please contact the requester at vinodk+proximasystems1@proximabiz.com.
If you need help or have questions about EasyCLA, you can read the documentation or reach out to us for support.

Thanks,
EasyCLA Support Team
--------------------

**Comment by vinod-kadam** [comment]
This is deployed to DEV & Staging.

**Comment by manishv09** [comment]
Minor change is required highlighted in red below:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/379e6341-89fc-49e2-8df0-a610dcba9a80)

**Comment by vinod-kadam** [comment]
This is deployed to DEV, Staging & PROD.

**Comment by manishv09** [comment]
Verified and found proposed text change is reflected in email body. Please refer the same as follows:

Hello Manish Vaidya,

This is a notification email from EasyCLA regarding the project(s) CNCF-Structure-Child001 associated with the CLA Group A-CNCF Structure-Child001. manishv comprmgr has designated you as an authorized signatory for the organization Proxima. In order for employees of your company to contribute to any of the above project(s), they must do so under a Contributor License Agreement signed by someone with authority n behalf of your company.

After you sign, manishv comprmgr (as the initial CLA Manager for your company) will be able to maintain the list of specific employees authorized to contribute to the project(s) under this signed CLA.

If you are authorized to sign on your company’s behalf, and if you approve manishv comprmgr as your initial CLA Manager, please review the document and sign the CLA. If you have questions, or if you are not an authorized signatory of this company, please contact the requester at manishv+comprmgr@proximabiz.com.

If you need help or have questions about EasyCLA, you can read the documentation or reach out to us for support.

Thanks,

EasyCLA Support Team
