### ISSUE TITLE
Performance Testing - Corp Console - Add/Edit/Delete Approval Criteria throws 504 (Gateway Time Out) error for some requests.

### ISSUE THREAD

**Issue by ashav-github** [communitybridge/easycla#2720]
During performance testing for Corporate Console - Add/Edit/Delete Approval Criteria APIs, its been observed that it throws 504 (Gateway Time Out) error for some requests.

Scenario tested: Virtual Users = 20 Users | Ramp-up = 60 Sec

Please find attached the Executive Summary Report: [https://app.zenhub.com/files/194341141/4fdc5f7e-6a2f-403d-9ad2-54ad04886bd3/download](https://app.zenhub.com/files/194341141/4fdc5f7e-6a2f-403d-9ad2-54ad04886bd3/download)

For additional details please check https://confluence.linuxfoundation.org/pages/viewpage.action?pageId=54437859

**Comment by ashav-github** [comment]
Test Data: 
Project Group Name: AshaLoadTestFoundation2021
Child project for CLA Group: AshaLoadTest-Child1

**Comment by dealako** [comment]
Closing issue - performance testing is complete.
