### ISSUE TITLE
Email to signatory needs a very minor text change

### ISSUE THREAD

**Issue by vinod-kadam** [communitybridge/easycla#2733]
Currently following email is sent to CLA Signatory.

Hello Vinod Kadam,
This is a notification email from EasyCLA regarding the project vinods15foundation_clagrp3. Vinod Kadam has designated you as being an authorized signatory for Proxima. In order for employees of your company to contribute to the open source project vinods15foundation_clagrp3, they must do so under a Contributor License Agreement signed by someone with authority to sign on behalf of your company.
After you sign, Vinod Kadam (as the initial CLA Manager for your company) will be able to maintain the list of specific employees authorized to contribute to the project under this signed CLA.
If you are authorized to sign on your company’s behalf, and if you approve Vinod Kadam as your initial CLA Manager for vinods15foundation_clagrp3, please review the document and sign the CLA.If you have questions, or if you are not an authorized signatory of this company, please contact the requester at vinodk+proximasystems1@proximabiz.com.
If you need help or have questions about EasyCLA, you can read the documentation or reach out to us for support.
Thanks,
EasyCLA Support Team

Change "as being an" to "as an".

**Comment by vinod-kadam** [comment]
This is deployed to DEV, Staging & PROD.

**Comment by manishv09** [comment]
Verified and found changes are reflected which is as follows:

![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/3be7475e-4829-45ba-9a3d-740efa9609c7)
