### ISSUE TITLE
Email sent to present CLA Managers when a new person is added as a CLA Manager needs a change 

### ISSUE THREAD

**Issue by vinod-kadam** [communitybridge/easycla#2734]
Following is the current email sent to  present CLA Managers when a new person is added as a CLA Manager needs a change .

--------------
Subject: EasyCLA: CLA Manager Added Notice for vinods15foundation_clagrp1
Body:
Hello Vinod Kadam,
This is a notification email from EasyCLA regarding the project vinods15foundation_clagrp1.
The following user has been added as a CLA Manager from Proxima for the project vinods15foundation_clagrp1. This means that they can now maintain the list of employees allowed to contribute to vinods15foundation_clagrp1 on behalf of your company, as well as view and manage the list of company’s CLA Managers for vinods15foundation_clagrp1.
Vinod Kadam (vinodk+proximastaging3@proximabiz.com)
If you need help or have questions about EasyCLA, you can read the documentation or reach out to us for support.
EasyCLA Support Team

--------------

Change the above email as follows:
---------------
Subject: EasyCLA: CLA Manager Added Notice for vinods15foundation_clagrp1
Body:
Hello Vinod Kadam,
This is a notification email from EasyCLA regarding the project [specific project name] associated with the CLA Group vinods15foundation_clagrp1.
The following user has been added as a CLA Manager from Proxima for the project [specific project name]. This means that they can now maintain the list of employees allowed to contribute to [specific project name] on behalf of your company, as well as view and manage the list of company’s CLA Managers for [specific project name].
Vinod Kadam (vinodk+proximastaging3@proximabiz.com)
If you need help or have questions about EasyCLA, you can read the documentation or reach out to us for support.
EasyCLA Support Team

---------------

**Comment by pranab-bajpai** [comment]
Yes the email content looks good.

**Comment by vinod-kadam** [comment]
This is deployed to DEV, Staging & PROD.

**Comment by manishv09** [comment]
Verified and proposed text change is reflected in email body which is as follows:

Hello manishv comprmgr,

This is a notification email from EasyCLA regarding the project A-LF Networking Fund-Manish associated with the CLA Group A-LF NETWORKING FUND-MANISH-Child001.

The following user has been added as a CLA Manager from Proxima for the project A-LF Networking Fund-Manish. This means that they can now maintain the list of employees allowed to contribute to A-LF Networking Fund-Manish on behalf of your company, as well as view and manage the list of company’s CLA Managers for A-LF Networking Fund-Manish.

Manish Vaidya (manishv@proximabiz.com)
If you need help or have questions about EasyCLA, you can read the documentation or reach out to us for support.

EasyCLA Support Team
