### ISSUE TITLE
Email sent to CLA Managers for approval request from a contributor needs a change

### ISSUE THREAD

**Issue by vinod-kadam** [communitybridge/easycla#2736]
Following is the current email sent to CLA Managers for approval request from a contributor.
--------------------------
Subject: EasyCLA: Approval Request for contributor: bubba01202021
Hello Pranab Bajpai,
This is a notification email from EasyCLA regarding the organization 444.
The following contributor would like to submit a contribution to the 444 CLA Group Child2_SeriesLLC CLA Group and is requesting to be approved as a contributor for your organization:
Child2_SeriesLLC CLA Group - GitHub User Name: bubba01202021,GitHub ID: 77810174,Emails: bubba01202021@gmail.com
Approval can be done at https://lfx.staging.platform.linuxfoundation.org
Please notify the contributor once they are added to the approved list of contributors so that they can complete their code contribution.
If you need help or have questions about EasyCLA, you can read the documentation or reach out to us for support.
EasyCLA Support Team
-------------------------
Change the above email to the following:
--------------------------
Subject: EasyCLA: Approval Request for the contributor: bubba01202021
Hello Pranab Bajpai,
This is a notification email from EasyCLA regarding the organization 444.
The following contributor would like to submit a contribution to the project(s): [comma separated project names] associated with the CLA Group [CLA Group Name] and is requesting to be added to the approval list as a contributor for your organization:
GitHub User Name: bubba01202021,GitHub ID: 77810174,Emails: bubba01202021@gmail.com
Approval can be done at https://lfx.staging.platform.linuxfoundation.org. Visit any of the project(s): [comma separated links to the projects] and add the contributor to the approved list.
Please notify the contributor once they are added to the approved list of contributors so that they can complete their contribution process.
If you need help or have questions about EasyCLA, you can read the documentation or reach out to us for support.
EasyCLA Support Team
-------------------------

**Comment by makkalot** [comment]
This one needs frontend change as well because it's coming from here : https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/notifyCLAManagers and we only get `claGroupName`, we need claGroupID or projectSFID whatever is present on that screen for the frontend to be able to fetch all of the associated projects for that cla-group-name. @dealako @vinod-kadam

**Comment by vinod-kadam** [comment]
@wanyaland  & @amolsontakke3576  as discussed we will change the API to accept CLAGroupID instead of CLA Group Name (as what other APIs being called from Contributor Console do).
@wanyaland  please make the API change & the logic change for the email & inform @amolsontakke3576  so that he can verify from his end.

**Comment by vinod-kadam** [comment]
This is deployed to DEV, Staging & PROD.

**Comment by manishv09** [comment]
A minor change is required which is as follows and highlighted in red:

![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/b02886f6-8c21-4d38-9f7b-3d5f260fdd5e)

**Comment by vinod-kadam** [comment]
@wanyaland  the sentence should say " is requesting to be added to the approval list.." and not "is requesting to be approved..".

**Comment by dealako** [comment]
Deployed to DEV, STAGING, and PROD.

**Comment by vinod-kadam** [comment]
Verified on Staging - the sentence is appearing fine now.
-----------------------
Hello Vinod Kadam,

This is a notification email from EasyCLA regarding the organization Proxima.

The following contributor would like to submit a contribution to the projects(s): vinods15foundation_child6, vinods15foundation_child5 and is requesting to be added to the approval list as a contributor for your organization:

GitHub User Name: vinod-kadam,GitHub ID: 63305651,LF Login: vinodkp3,LF Email: vinodk+p3@proximabiz.com,Emails: vinodk@proximabiz.com

Approval can be done at https://lfx.staging.platform.linuxfoundation.org. Visit any of the project(s):vinods15foundation_child6,vinods15foundation_child5 and add the contributor to the approved list.

Please notify the contributor once they are added to the approved list of contributors so that they can complete their contribution.

If you need help or have questions about EasyCLA, you can read the documentation or reach out to us for support.

EasyCLA Support Team
-----------------------
