### ISSUE TITLE
Need more detail Instructions in the email sent to an added contributor 

### ISSUE THREAD

**Issue by vinod-kadam** [communitybridge/easycla#2740]
Following is the email which gets sent to a contributor who is added to the approved list.
----------------
Subject: EasyCLA: Approval List Update for Proxima on CheckActivitylog
Body:
Hello Manish Vaidya,
This is a notification email from EasyCLA regarding the project CheckActivitylog.
You have been added to the Approval List of Proxima for CheckActivitylog by CLA Manager manishv.comprmgr. This means that you are authorized to contribute to CheckActivitylog on behalf of Proxima on behalf of CheckActivitylog.
If you had previously submitted a pull request to EasyCLA Test Group that had failed, you can now go back to it and follow the link to verify with your organization.
If you need help or have questions about EasyCLA, you can read the documentation or reach out to us for support.
EasyCLA Support Team

----------------

Change the above email to following:
----------------
Subject: EasyCLA: Approval List Update for Proxima on CheckActivitylog
Body:
Hello Manish Vaidya,
This is a notification email from EasyCLA regarding the project CheckActivitylog.
You have been added to the Approval List of Proxima for CheckActivitylog by CLA Manager manishv.comprmgr. This means that you are authorized to contribute to CheckActivitylog on behalf of Proxima.

**If you had previously submitted a pull request to EasyCLA Test Group that had failed, you can now go back to it, re-click the “Not Covered” button in the EasyCLA message in your pull request, and then follow these steps
1. Select “Corporate Contributor”. 
2. Select your company from the organization drop down list
3. Click Proceed  
These steps will confirm your organization association and you will only need to do these once. After completing these steps, the EasyCLA check will be complete and enabled for all future code contributions for this project. **

If you need help or have questions about EasyCLA, you can read the documentation or reach out to us for support.
EasyCLA Support Team

----------------

Note: This came as feedback from Shubhra. We need to make the middle paragraph bold so that user knows it is the call to action. Remove the double " on behalf of CheckActivitylog"

**Comment by manishv09** [comment]
Verified and working fine, please refer below email with proposed changes showing up in email body:

Hello Manish Vaidya,

This is a notification email from EasyCLA regarding the project Feb2021-CNCF-style.

You have been added to the Approval List of Proxima for Feb2021-CNCF-style by CLA Manager manishv.comprmgr. This means that you are authorized to contribute to Feb2021-CNCF-style on behalf of Proxima.

If you had previously submitted a pull request to EasyCLA Test Group that had failed, you can now go back to it, re-click the “Not Covered” button in the EasyCLA message in your pull request, and then follow these steps

Select “Corporate Contributor”.
Select your company from the organization drop down list
Click Proceed
These steps will confirm your organization association and you will only need to do these once. After completing these steps, the EasyCLA check will be complete and enabled for all future code contributions for this project.

If you need help or have questions about EasyCLA, you can read the documentation or reach out to us for support.

EasyCLA Support Team

**Comment by dealako** [comment]
@manishv09 can you add a screenshot of the actual email that you received? Thanks!

**Comment by vinod-kadam** [comment]
Here is the email screenshot.
![image.png](https://images.zenhubusercontent.com/5e9e9952b186e1325cf5608a/fcded69b-8da3-453c-87db-dd582628f494)

Note that the instructions are not in bold. For that I will log a separate ticket.

**Comment by vinod-kadam** [comment]
This is deployed to PROD as well on 5-Mar.
