### ISSUE TITLE
GitHub User name & Github email address is missing from invitation is sent to CLA Manager for adding to approved list from Contributor Console

### ISSUE THREAD

**Issue by manishv09** [communitybridge/easycla#2756]
GitHub User name & GitHub email address is missing from invitation is sent to CLA Manager for adding to approved list from Contributor Console

![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/b191e027-8382-4fe6-a03c-99b639420350)

![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/ef742839-20b7-41ed-b771-52cabb7f7210)

**Comment by manishv09** [comment]
Verified on Staging environment and found working fine now. Github Username & email id is appearing on invite email. Please refer the screencast and video attached for reference.

![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/3d22ae95-e96a-4373-900b-d9eb876fd228)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/59b7a121-1f7d-40fb-a8f8-82839253f2ce)

https://images.zenhubusercontent.com/194341141/8f89941e-45dd-4a1f-926f-5a33236da778/_2756_2758_10032021.mp4

**Comment by vinod-kadam** [comment]
Deployed to PROD through https://github.com/communitybridge/easycla/releases/tag/v2.0.5
