### ISSUE TITLE
Emails for Adding, Removing CLA Manager from corporate console are not triggered

### ISSUE THREAD

**Issue by manishv09** [communitybridge/easycla#2757]
Emails for Adding, Removing CLA Manager from corporate console are not triggeredhttps://images.zenhubusercontent.com/194341141/5f45c18f-669d-4201-8253-78ba708cf912/recording__137.mp4

**Comment by manishv09** [comment]
Verified on staging environment and found emails are getting triggered for Adding & Removal of CLA Manager.

Removal:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/2d75c751-5e31-4e90-8b85-944384a523dd)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/82d5ace5-25ec-4e03-b41e-b7fc86558706)

Addition:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/f47dfb76-9807-4af3-9340-2ae2634e67af)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/ace15689-8e91-4382-8de9-eb608ec11567)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/327e1ad4-f649-469c-8003-88f3d948ff6e)
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/c3a46dca-0675-4916-bdf6-9fdce9967ffc)

**Comment by vinod-kadam** [comment]
Deployed to PROD through https://github.com/communitybridge/easycla/releases/tag/v2.0.5
