### ISSUE TITLE
Github Username is missing from email sent to be create LF Login and Become a CLA Manager from Contributor Console 

### ISSUE THREAD

**Issue by manishv09** [communitybridge/easycla#2758]
Github Username is missing from email sent to be create LF Login and Become a CLA Manager from Contributor Console 

![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/c2abddfc-8388-4dba-b429-a240a4e28a8f)

**Comment by manishv09** [comment]
Verified on Staging environment and found working fine now. Github Username & email id is appearing on invite email. Please refer the screencast and video attached for reference.
https://images.zenhubusercontent.com/194341141/930d9c0a-ec28-49b1-ad41-aa983a007448/_2756_2758_10032021.mp4

![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/6d4465e8-438b-4eb0-887c-dae6a38fe417)

**Comment by vinod-kadam** [comment]
Deployed to PROD through https://github.com/communitybridge/easycla/releases/tag/v2.0.5
