### ISSUE TITLE
Regression: Role Assignment doesn't work getting message "This portal is only available for corporate users" post new user creation

### ISSUE THREAD

**Issue by manishv09** [communitybridge/easycla#2759]
Regression: Role Assignment doesn't work getting message "This portal is only available for corporate users" post new user creation on staging environment
Steps to Reproduce: 
1. Create New User using the invite link
2. Verify the email address and proceed to login to corporate console

Expected: 
User should be navigated to project page to proceed with signing CCLA process

Actual:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/d4c30d04-b7b3-4142-99df-81d219f6cf3e)

**Comment by manishv09** [comment]
Verified and found working fine on staging environment. Hence closing this issue.

**Comment by vinod-kadam** [comment]
As understood in the 10-Mar standup, there was no fix made for this.
