### ISSUE TITLE
PDF Icons Sometimes Loading Project Page

### ISSUE THREAD

**Issue by jpalmerLinuxFoundation** [communitybridge/easycla#278]
**Summary**

**Background**

Provide context to the issue - provide steps to reproduce the behavior, such as:
1. Go to project.lfcla.com
2. Click on Academy Software Foundation
3. Scroll down to a CLA Group
4. Click on the PDF Icon
5. Click on the PDF Icon in the modal that appears
6. Undesired behavior sometimes occurs (please see video)

**Expected behavior**
The PDF for the corresponding CLA group and CLA type (CCLA/ICLA) should display or download

**Video**
https://zoom.us/recording/share/I_TQcd6nLjo38pc7OoBpY7iMrmn3n0ZAulwGa9ZJplCwIumekTziMw

**Environment**
 - Environment: PROD 
 - OS: iOS Catalina
 - Browser: Chrome 
 - Version 77.0.3865.90

**Acceptance Criteria**

The "done" criteria when this feature or problem is resolved.  Such as:
1. Unit Tests added and running in CI
2. Functional Tests updated to cover feature, if applicable
2. Demonstrate the set of capabilities to the product team while the code is
   running in the STAGING environment.

**Comment by directionless** [comment]
I think I'm bumping into this. Coupled with #265 it places someone in an unresolvable catch-22 if they need legal before they can touch github

**Comment by ngozi-ekekwe** [comment]
@dealako everything looks fine. Once the pdf icon is clicked, it downloads the CCLA / ICLA
