### ISSUE TITLE
Update EasyCLA Approval Criteria Confirmation Modal

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#2789]
## Summary

Update EasyCLA Approval Criteria Confirmation Modal

## Background

This task is to update the corporate modal text to account for Gerrit users.  See meeting video below, time 00:34:28 - Add Approval Criteria Confirmation Modal - Update text (Github text section, Gerrit text section) - @pranab-bajpai  can help with verbiage, I would like to see a GitHub section, horizontal bar, a Gerrit section, horizontal bar, ok button.

## Screenshots

See the video link referenced below at the specified time.

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

Meeting video/audio: copy the link below to share this recording with viewers:
https://zoom.us/rec/share/U7eGoOmvKlsN0MbSuumuFDPRA089ESL-InAH_OX18sI7hM4puDeCGkNXfBEt2BP3.LaKwvh4bw6vuD0mW

00:34:28 - Add Approval Criteria Confirmation Modal - Update text (Github text section, Gerrit text section) - Pranab can help with verbiage, I would like to see a GitHub section, horizontal bar, a Gerrit section, horizontal bar, ok button

**Comment by vinod-kadam** [comment]
Closing this one as created corresponding ticket in LFX board.
https://jira.linuxfoundation.org/browse/LFX-3143
