### ISSUE TITLE
Update User Information in Activity Log

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#2790]
## Summary

Describe the bug - a clear and concise description of what the bug is.

## Background

Update audit log user information - should include full name when available.

## Screenshots

See video/meeting link below at the specified time.

## Environment

Please complete the following information:

* Environment:
  - [x] ALL
  - [ ] DEV
  - [ ] STAGING
  - [ ] PROD 
* Browser:
  - [x] ALL
  - [ ] Chrome/Brave
  - [ ] Firefox
  - [ ] Edge
  - [ ] Lynx
* Version: v1.0.XX

## Assumptions

If you are assuming certain facts or scenarios, list them so we have a baseline to understand your request.

- Assumption 1
- Assumption 2

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

Meeting video/audio: copy the link below to share this recording with viewers:
https://zoom.us/rec/share/U7eGoOmvKlsN0MbSuumuFDPRA089ESL-InAH_OX18sI7hM4puDeCGkNXfBEt2BP3.LaKwvh4bw6vuD0mW

My Gerrit Video: https://cla-project-logo-prod.s3.amazonaws.com/20210316+Gerrit+Workflow+Video.mov

for the Gerrit discussion, start at around 00:31:38 time

- 00:36:02 - think the double audit log entry is resolved by Harold, but need to update the content to replace `The user ddea…` with `The user David Deal…`

**Comment by manishv09** [comment]
Verified and found working fine on Staging environment. Please refer attached activity log for reference.

![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/53e83adf-5498-47d2-891e-8a675f2b2a15)

**Comment by vinod-kadam** [comment]
This is deployed to PROD on 19-Mar.
