### ISSUE TITLE
Contributor Console Gerrit Notification

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#2791]
## Summary

Contributor Console Gerrit Notification.

## Background

Add contributor console notification for Gerrit that reminds the user to logout/login again to realize the updated permissions. See meeting video at the specified timeslot for the discussion on this topic.

## Screenshots

See video referenced below.

## Environment

Please complete the following information:

* Environment:
  - [x] ALL
  - [ ] DEV
  - [ ] STAGING
  - [ ] PROD 
* Browser:
  - [x] ALL
  - [ ] Chrome/Brave
  - [ ] Firefox
  - [ ] Edge
  - [ ] Lynx
* Version: v1.0.XX

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

Meeting video/audio: copy the link below to share this recording with viewers:
https://zoom.us/rec/share/U7eGoOmvKlsN0MbSuumuFDPRA089ESL-InAH_OX18sI7hM4puDeCGkNXfBEt2BP3.LaKwvh4bw6vuD0mW

My Gerrit Video: https://cla-project-logo-prod.s3.amazonaws.com/20210316+Gerrit+Workflow+Video.mov

for the Gerrit discussion, start at around 00:31:38 time

00:37:53 - add contributor console notification for Gerrit that reminds the user to logout/login again to realize the updated permissions

**Comment by vinod-kadam** [comment]
Show the following message for a Gerrit user
You have completed the CLA steps necessary to contribute. Please note that you will need to logout and login on Gerrit to get the updated permissions. You can now return to writing awesome stuff.
instead of the regular message
You have completed the CLA steps necessary to contribute. You can now return to writing awesome stuff.

Note there is no change needed for GitHub case.

**Comment by vinod-kadam** [comment]
As discussed in the standup, this need to be handled in both CCLA & ICLA flows.

**Comment by amolsontakke3576** [comment]
For the case of only ICLA in Gerrit flow I have added the below message. @pranab-bajpai can you please confirm the same?
title = 'Important Note';
message = 'Please note that after you have signed the CLA, you will need to logout and login on Gerrit to get the updated permissions. After completing this, the EasyCLA check will be complete and enabled for all future code contributions for this project.'

**Comment by vinod-kadam** [comment]
Please note that after you have signed the CLA, you will need to logout and log back in to your Gerrit account to get the updated permissions. After completing this, the EasyCLA check will be complete and enabled for all future code contributions for this project.

**Comment by manishv09** [comment]
Verified on Staging environment and found the new proposed message is getting displayed to the user when user proceed to sign ICLA and is as follows:

![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/2c78ef67-142c-4945-9082-87d3f5a90ebf)

**Comment by vinod-kadam** [comment]
This has been deployed to PROD on 19th March.
