### ISSUE TITLE
Invalidate Gerrit Contributors

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#2793]
## Summary

Invalidate Gerrit Contributors

## Background

Invalidate Gerrit Contributors by removing the permissions from the LDAP configuration.

## Screenshots

See the video discussion below.

## Environment

Please complete the following information:

* Environment:
  - [ ] DEV
  - [ ] STAGING
  - [ ] PROD 
* Browser:
  - [ ] Chrome/Brave
  - [ ] Firefox
  - [ ] Edge
  - [ ] Lynx
* Version: v1.0.XX

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

Meeting video/audio: copy the link below to share this recording with viewers:
https://zoom.us/rec/share/U7eGoOmvKlsN0MbSuumuFDPRA089ESL-InAH_OX18sI7hM4puDeCGkNXfBEt2BP3.LaKwvh4bw6vuD0mW

My Gerrit Video: https://cla-project-logo-prod.s3.amazonaws.com/20210316+Gerrit+Workflow+Video.mov

for the Gerrit discussion, start at around 00:31:38 time

00:40:00 - as part of Harold’s ticket to invalidate corporate contributors, we need to remove Gerrit user LDAP permissions - for both employee ack and ICLA for Gerrit users (create a separate ticket - or set of tickets)

**Comment by vinod-kadam** [comment]
I think this single ticket is good enough as the changes are on the backend.

**Comment by vinod-kadam** [comment]
This was deployed to DEV & STAGING on 25th March.

**Comment by vinod-kadam** [comment]
This is deployed to DEV, Staging & PROD through https://github.com/communitybridge/easycla/releases/tag/v2.0.19

**Comment by manishv09** [comment]
Verified on Staging environment and found working fine. Please refer the video attached for reference.

https://images.zenhubusercontent.com/194341141/e4a2c3e9-3966-4871-b9db-a984ac602a3b/_2793_06032021.mp4

**Comment by vinod-kadam** [comment]
Deployed to PROD through https://github.com/communitybridge/easycla/releases/tag/v2.0.23

**Comment by manishv09** [comment]
Though comments were updated but missed to mark them as QA Done. Also this issue is verified using only email domain and not the email address so kept it open.
