### ISSUE TITLE
Change needed in the email sent to the approved contributor in regard to the steps for Gerrit

### ISSUE THREAD

**Issue by vinod-kadam** [communitybridge/easycla#2795]
Following is the email which gets sent to a contributor who is added to the approval list.
--------------------
Hello ,
This is a notification email from EasyCLA regarding the project vinods15foundation_clagrp4.
You have been added to the Approval List of Proxima for vinods15foundation_clagrp4 by CLA Manager vinodkps1. This means that you are authorized to contribute to vinods15foundation_clagrp4 on behalf of Proxima.
If you had previously submitted a pull request to EasyCLA Test Group that had failed, you can now go back to it, re-click the “Not Covered” button in the EasyCLA message in your pull request, and then follow these steps
1. Select “Corporate Contributor”.
2. Select your company from the organization drop down list
3. Click Proceed
These steps will confirm your organization association and you will only need to do these once. After completing these steps, the EasyCLA check will be complete and enabled for all future code contributions for this project.
If you need help or have questions about EasyCLA, you can read the documentation or reach out to us for support.
EasyCLA Support Team
------------------------------------

Change the above email to the following.
--------------------
Hello ,
This is a notification email from EasyCLA regarding the project vinods15foundation_clagrp4.
You have been added to the Approval List of Proxima for vinods15foundation_clagrp4 by CLA Manager vinodkps1. This means that you are authorized to contribute to vinods15foundation_clagrp4 on behalf of Proxima.

**If you are a GitHub user & if you had previously submitted a pull request to EasyCLA Test Group** that had failed, you can now go back to it, re-click the “Not Covered” button in the EasyCLA message in your pull request, and then follow these steps
1. Select “Corporate Contributor”.
2. Select your company from the organization drop down list
3. Click Proceed

**If you are a Gerrit user & if you had previously submitted a pull request to EasyCLA Test Group** that had failed, then navigate to Agreements Settings page on Gerrit, click on "New Contributor Agreement" link under Agreements section, select the radio button corresponding to Corporate CLA, click on "Please review the agreement" link, and then follow these steps
1. Select “Corporate Contributor”.
2. Select your company from the organization drop down list
3. Click Proceed

These steps will confirm your organization association and you will only need to do these once. After completing these steps, the EasyCLA check will be complete and enabled for all future code contributions for this project.
If you need help or have questions about EasyCLA, you can read the documentation or reach out to us for support.
EasyCLA Support Team
------------------------------------

**Comment by pranab-bajpai** [comment]
Email is good. I would bold the first sentence for GitHub and Gerrit paragraphs.

**Comment by vinod-kadam** [comment]
This is deployed to DEV, Staging & PROD.

**Comment by manishv09** [comment]
Verified and found working fine on Staging environment. Please refer to email sent to the added contributor as follows:

Hello Manish Vaidya,

This is a notification email from EasyCLA regarding the project A-Man PCC Foundation- Child003 CLA Group.

You have been added to the Approval List of Proxima for A-Man PCC Foundation- Child003 CLA Group by CLA Manager manishv.comprmgr. This means that you are authorized to contribute to A-Man PCC Foundation- Child003 CLA Group on behalf of Proxima.

If you are a GitHub user and If you had previously submitted a pull request to EasyCLA Test Group that had failed, you can now go back to it, re-click the “Not Covered” button in the EasyCLA message in your pull request, and then follow these steps

Select “Corporate Contributor”.
Select your company from the organization drop down list
Click Proceed
If you are a Gerrit user and if you had previously submitted a pull request to EasyCLA Test Group that had failed, then navigate to Agreements Settings page on Gerrit, click on "New Contributor Agreement" link under Agreements section, select the radio button corresponding to Corporate CLA, click on "Please review the agreement" link, and then follow these steps

Select “Corporate Contributor”.
Select your company from the organization drop down list
Click Proceed
These steps will confirm your organization association and you will only need to do these once. After completing these steps, the EasyCLA check will be complete and enabled for all future code contributions for this project.

If you need help or have questions about EasyCLA, you can read the documentation or reach out to us for support.

EasyCLA Support Team
