### ISSUE TITLE
v1 PROD - Individual Contributors sent the wrong email after signing icla with bad link to pdf

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2806]
After a user has signed the ICLA for a v1 project, they are being sent this email:

![image](https://user-images.githubusercontent.com/46732999/111847940-4f55b180-88e0-11eb-9524-7da821351245.png)

1) The pdf link is bad in this email. it is linking to https://api.easycla.lfx.linuxfoundation.org/v3/signatures/9e34f107-9fdc-4a82-981a-7159c4305665/29d41826-2b3e-457d-8a52-42646d649324/icla/pdf which 404s

2) The above might be because this is the wrong email entirely to send to an ICLA signer since it is linking to the corporate console. 

Please review the emails being sent to both individual contributors and corporate cla managers after signing v1 projects to make sure the emails are correct according to the email document.

**Comment by dealako** [comment]
@WillsonHG - @makkalot and I reviewed the logs associated with this issue. For some reason, the API attempted to set all the DocuSign details, set the signed=True flag, but.....the database record was NOT saved.  No error was thrown or returned to the API from DynamoDB save request.  It may be an issue with the current version of the DynamoDB library we are using (which is old), a networking issue, or some other underlying exception that was not properly caught.  The EasyCLA API attempted to do the correct thing. Unfortunately, we were not able to trap or see the underlying error.  As a result, the signature save/update was not performed and the user is still not authorized.

**Comment by dealako** [comment]
The PDF is there, however, when accessing through our API, we first query for the signature record. The query parameters/filters are:

```
	// These are the keys we want to match for an ICLA Signature with a given CLA Group and User ID
	condition := expression.Key("signature_project_id").Equal(expression.Value(claGroupID)).
		And(expression.Key("signature_reference_id").Equal(expression.Value(userID)))
	filter := expression.Name("signature_type").Equal(expression.Value(utils.SignatureTypeCLA)).
		And(expression.Name("signature_reference_type").Equal(expression.Value(utils.SignatureReferenceTypeUser))).
		And(expression.Name("signature_approved").Equal(expression.Value(aws.Bool(true)))).
		And(expression.Name("signature_signed").Equal(expression.Value(aws.Bool(true)))).
		And(expression.Name("signature_user_ccla_company_id").AttributeNotExists())
```
which returns no matches due to the signed=False signature value in the database.  As a result, the API returns 404 without even checking s3.

**Comment by dealako** [comment]
I bet:

- User signs the ICLA in DocuSign
- DynamoDB save failed, signature NOT updated, signed=False remains on the record
- PDF upload occurs, no issue (although, EasyCLA API query fails since signed=False)
- GitHub PR update occurs, the user passes GitHub status check, no issue

...and then, the next PR comes in the future

- user will be blocked since the signature record still indicates signed=False

**Comment by dealako** [comment]
After a discussion with @WillsonHG we decided to set the signed=True flag as the user has successfully executed the ICLA.  This resolves the PDF download issue.

@makkalot - Regarding the email - please remove the "or from the CLA Manager Console." from the emails that are sent.

**Comment by vinod-kadam** [comment]
As updated by Denis, this is deployed to DEV.

**Comment by manishv09** [comment]
Verified on Staging environment (V2) and found working fine also link to login to the specific environment which is sent to Corporate contributor's email is removed now. Please refer the attached email received to Individual contributor as follows:

Hello Contributor,

This is a notification email from EasyCLA regarding the project A-MAN PCC FOUNDATION-CLA GROUP.

The CLA has now been signed. You can download the signed CLA as a PDF here.

If you need help or have questions about EasyCLA, you can read the documentation or reach out to us for support.

Thanks,

EasyCLA Support Team

https://images.zenhubusercontent.com/194341141/0e734363-4ed3-4048-9d83-b045b2bb9505/_2806_24032021.mp4

**Comment by amolsontakke3576** [comment]
@vinod-kadam Verified on DEV. PDF download started automatically and also a new window open with Download option (PFA)

![Screenshot from 2021-03-24 19-03-52.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/dabe058f-700a-430f-bc1e-8d7e5a4e59a3)

**Comment by vinod-kadam** [comment]
This is deployed to PROD through https://github.com/communitybridge/easycla/releases/tag/v2.0.19
@WillsonHG  please verify it on PROD.

**Comment by WillsonHG** [comment]
Verified on both v1 and v2 versions in production
