### ISSUE TITLE
CCLA Signature Signed On Date Not Shown

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#2814]
## Summary

CCLA Signature Signed On Date Not Shown for older signatures.

## Background

PCC is using the `signedOn` field for displaying the signed on the date. This is a new field that is not always set for older signatures.  Need to update logic to use the signature created date as a fall-back (generally the created and signed date/time are close/similar).

![Screen Shot 2021-03-24 at 4 04 17 PM](https://user-images.githubusercontent.com/519609/112394859-9bc33780-8cba-11eb-9a5e-1346b8b1c2b7.png)

## Expected behavior

Signed on date should always appear.

## Screenshots

See above.

## Environment

Please complete the following information:

* Environment:
  - [ ] DEV
  - [ ] STAGING
  - [x] PROD 
* Browser:
  - [X] All
  - [ ] Chrome/Brave
  - [ ] Firefox
  - [ ] Edge
  - [ ] Lynx
* Version: v1.0.XX

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

- Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by dealako** [comment]
Created PR

**Comment by dealako** [comment]
Ready for QA

**Comment by manishv09** [comment]
Verified on Staging environment and found Signed Date is appearing correct on PCC now.

![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/49e04440-36ab-4274-b201-8344efad206c)

Please refer video attached for reference.

https://images.zenhubusercontent.com/194341141/f7fb6c7e-87db-4e56-8fed-f2eacf66c7e3/_2814_25032021.mp4

**Comment by vinod-kadam** [comment]
This is deployed to PROD through https://github.com/communitybridge/easycla/releases/tag/v2.0.19
