### ISSUE TITLE
Getting Error 400 Bad Request while creating CLA Group when Preview of template is shown to the user

### ISSUE THREAD

**Issue by manishv09** [communitybridge/easycla#2817]
[Uploading... Recording #172.mp4]Getting Error 400 Bad Request while creating CLA Group when Preview of template is shown to the user

![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/46d3893c-81b0-48ce-a605-0b60bdbba3a4)

{
	"statusCode": 400,
	"error": "Bad Request",
	"message": "{\"Message\":\"http: read on closed response body\",\"x-request-id\":\"a9c0f5e0-8d44-11eb-8a2d-fde44bcebf25\"}",
	"metadata": {
		"request": {
			"url": "https://api-gw.staging.platform.linuxfoundation.org/cla-service/v4/template/preview?template_for=ccla",
			"method": "POST",
			"body": "{\"MetaFields\":[{\"description\":\"Project's Full Name.\",\"name\":\"Project Name\",\"templateVariable\":\"PROJECT_NAME\",\"value\":\"A-Man PCC Foundation\"},{\"description\":\"The Full Entity Name of the Project.\",\"name\":\"Project Entity Name\",\"templateVariable\":\"PROJECT_ENTITY_NAME\",\"value\":\"A-Man PCC Foundation\"},{\"description\":\"The E-Mail Address of the Person managing the CLA. \",\"name\":\"Contact Email Address\",\"templateVariable\":\"CONTACT_EMAIL\",\"value\":\"manishv@proximabiz.\"}]}",
			"headers": {
				"User-Agent": "Retool/2.0 (+https://docs.tryretool.com/docs/apis)",
				"Content-Type": "application/json",
				"Authorization": "---sanitized---",
				"X-Retool-Forwarded-For": "182.77.77.222"
			}
		},
		"headers": {
			"date": [
				"Thu, 25 Mar 2021 08:32:43 GMT"
			],
			"content-type": [
				"application/json"
			],
			"content-length": [
				"103"
			],
			"connection": [
				"keep-alive"
			],
			"vary": [
				"Origin"
			],
			"x-request-id": [
				"a9c0f5e0-8d44-11eb-8a2d-fde44bcebf25"
			]
		},
		"status": 400,
		"statusText": "Bad Request"
	},
	"data": null
}

**Comment by vinod-kadam** [comment]
This is deployed to PROD through https://github.com/communitybridge/easycla/releases/tag/v2.0.19
