### ISSUE TITLE
Getting error 400 while fetching CLa Groups created on staging environment

### ISSUE THREAD

**Issue by manishv09** [communitybridge/easycla#2818]
Getting error 400 while fetching CLa Groups created on staging environment

{"error":true,"message":"network timeout at: https://api-gw.staging.platform.linuxfoundation.org/cla-service/v4/foundation/a097c000007p4zBAAQ/cla-groups","source":"resource"}

https://images.zenhubusercontent.com/194341141/ca26cb44-f1ca-4151-beac-7d3ec771fd44/recording__176.mp4

**Comment by vinod-kadam** [comment]
This was fixed by David and deployed to DEV & Staging.
Manish has verified it on Staging and found it to be working fine now.
So, marking this ticket as QA Done.

**Comment by vinod-kadam** [comment]
This is deployed to PROD through https://github.com/communitybridge/easycla/releases/tag/v2.0.19
