### ISSUE TITLE
Parent SFID and Parent Project Name Not Set in Event Logs

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#2837]
## Summary

Parent SFID and Parent Project Name Not Set in Event Logs

## Background

In order for event logs to be displayed properly on the PCC, event log entries should include both the parent_project_sfid and project_sfid should be set on each event log.

## Tasks

- Review the event log creation logic. Confirm that when a project_sfid is provided that the logic properly looks up the project parent and sets the parent_project_sfid/name.
- Review where we create event log entries in the PCC.  Ensure that the project_sfid is set properly.  Identify and resolve any gaps where the parent_project_sfid is not set.

## Expected behavior

Event logs created by the child should be visible at the parent level.

## Screenshots

N/A

## Environment

Please complete the following information:

* Environment:
  - [ ] ALL
  - [ ] DEV
  - [ ] STAGING
  - [x] PROD 
* Browser:
  - [x] Chrome/Brave
  - [ ] Firefox
  - [ ] Opera
  - [ ] Vivaldi
  - [ ] LibreWolf
  - [ ] SRware Iron
  - [ ] Dissenter
  - [] Slimjet
  - [ ] Midori
  - [ ] Edge
  - [ ] Lynx
* Version: v1.0.XX

## Additional Context

This was observed under several projects in production. Contact @WillsonHG for examples in PROD.

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

- Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by vinod-kadam** [comment]
This is deployed to DEV & Staging through https://github.com/communitybridge/easycla/releases/tag/v2.0.20

**Comment by vinod-kadam** [comment]
Deployed to PROD through https://github.com/communitybridge/easycla/releases/tag/v2.0.23

**Comment by manishv09** [comment]
Verified on staging and found working fine. Please refer the attached video for reference on PCC Retool version.

https://images.zenhubusercontent.com/194341141/8a5b5646-0345-4156-9530-1e27d77df579/_2837_06042021.mp4
