### ISSUE TITLE
JanusGraph/OpenJS/OSQuery Organization Not Displayed on PCC

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#2838]
## Summary

JaniceGraph Organization Not Displayed on PCC

## Background

The JanusGraph project (a0941000002wBybAAE) is a child of LF AI & Data Foundation (a0941000012Y73ZAAS). Currently, the PCC/EasyCLA API performs a query for the GitHub Organizations using the parentSFID. In this case, along with 3 other use-cases listed below, we are allowing the GitHub Organization to be anchored to the child project as the GitHub organization is only relevant to the child project.  Normally we would anchor the GitHub organization only to the parent (project group) project.

This task is to add logic to allow UI to fetch the GitHub organization from either the parent or the child project.
1. If the GitHub organization is anchored to the parent project, then the results should show the GitHub organization on the child page (current behavior)
1. If the GitHub organization is anchored to the child project, then the results should show the GitHub organization on the child page (this is the issue for this use case).
1.  If a GitHub organization is anchored to the parent project and another GitHub organization is anchored to the child project, then both GitHub Organizations should be shown on the child page (union of the two, no duplicates).

The following projects in PROD are impacted:
- JanusGraph
- OpenJS Foundation CLA
- OSQuery

## Expected behavior

The GitHub organization should be displayed in the PCC for the JanusGraph project.

## Screenshots

![Screen Shot 2021-03-31 at 4.59.24 PM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/713ade49-8ba9-4950-b4a2-bd76771951a9)

## Environment

Please complete the following information:

* Environment:
  - [ ] ALL
  - [ ] DEV
  - [ ] STAGING
  - [x] PROD 
* Browser:
  - [ ] Chrome/Brave
  - [ ] Firefox
  - [ ] Opera
  - [ ] Vivaldi
  - [ ] LibreWolf
  - [ ] SRware Iron
  - [ ] Dissenter
  - [ ] Slimjet
  - [ ] Midori
  - [ ] Edge
  - [ ] Lynx
* Version: v1.0.XX

## Assumptions

If you are assuming certain facts or scenarios, list them so we have a baseline to understand your request.

- Assumption 1
- Assumption 2

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

- API Query: {{EASYCLA_v2_API_PROD}}/project/a0941000002wBybAAE/github/organizations
- PCC Link: https://projectadmin.lfx.linuxfoundation.org/apps/cla/project#id=a0941000002wBybAAE
- Janus Graph SFID: a0941000002wBybAAE (child, type: subproject)
- LF AI & Data Foundation: a0941000012Y73ZAAS (parent)

**Comment by vinod-kadam** [comment]
This is deployed to DEV, Staging & PROD through https://github.com/communitybridge/easycla/releases/tag/v2.0.23

**Comment by vinod-kadam** [comment]
The fix for githuborg/repo display issue deployed to DEV, STAGING & PROD through https://github.com/communitybridge/easycla/releases/tag/v2.0.24
@WillsonHG  please verify.

**Comment by vinod-kadam** [comment]
As updated by @WillsonHG  in 8th April standup, this has been verified on PROD and is working fine. So marked the ticket as QA Done.
