### ISSUE TITLE
Send Email to Contributor When ICLA or ECLA is Invalidated

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#2842]
## Summary

Send Email to Contributor When ICLA or ECLA is Invalidated

## Background

When the system invalidates a contributor signature (ICLA or employee acknowledgment) a confirmation email should be sent to the contributor.

Work with @pranab-bajpai on the text/content of the email.
 
## User Story

- As a project manager, when I invalidate an individual signature, an email should be sent to the contributor notifying them that they are no longer authorized.
- As a CLA Manager, when I remove an entry from the approval list, an email should be sent to the contributors who are no longer authorized.

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.
1. System emails are sent during the above scenarios defined in the user stories.

## References

- Stakeholder meeting notes on 03/31/2021.

**Comment by pranab-bajpai** [comment]
Email should be thus.
Scope: Invalidating ICLA of a user
Recipient: EasyCLA user whose ICLA has been invalidated
Subject: EasyCLA: ICLA invalidated for <user> on <Project Name(s)>
Body:
Hello <user (could be userid or email)>,
This is a notification email from EasyCLA regarding the project(s) <Project Name(s)>.
The ICLA signature for <user> has been invalidated. 
Please contact Project Manager for the project <project name(s)> and/or CLA Manager from your company if you have more questions.  
EasyCLA Support Team

**Comment by vinod-kadam** [comment]
Deployed to DEV, Staging & PROD through https://github.com/communitybridge/easycla/releases/tag/v2.0.23

**Comment by manishv09** [comment]
@nickmango I verified this on staging environment and found email is not sent to the user when ICLA is invalidated.
Please refer the attached video for reference.

https://images.zenhubusercontent.com/194341141/22c1b4d7-60be-4fc7-bd88-477d202614be/_2842_06042021.mp4

**Comment by manishv09** [comment]
Verified on staging environment today and found email is triggered. Please refer the screencast as below:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/d72fa185-640e-4f36-8e46-6e80448bc8d6)

**Comment by vinod-kadam** [comment]
David has sent the draft to Steve on 7-Apr; awaiting his feedback.

**Comment by vinod-kadam** [comment]
Deployed to PROD through https://github.com/communitybridge/easycla/releases/tag/v2.0.28

**Comment by dealako** [comment]
We have received an update from our stakeholders on the email content. Please see below:

Thanks David, apologies again for the delay in circling back. Here's what I would suggest:

Case 1: CLA Manager removes someone; project where CCLA+ICLA combination is NOT required (e.g. the normal case)

Hello {{.RecipientName}},

This is a notification email from EasyCLA regarding the CLA Group {{.CLAGroupName}}.

You were previously authorized to contribute on behalf of your company {{COMPANY-NAME}} under its CLA. However, a CLA Manager has now removed you from the authorization list.

As a result, you will no longer be able to contribute until you are again authorized under another signed CLA.

Please contact one of the CLA Managers from your company if you have questions about why you were removed. The CLA Managers from your company for this CLA are:
{{LIST CLA-MANAGERS - names and email addresses}}
{normal CLA signoff}

(If we are able to track which specific CLA Manager made the change, I would change this line: "However, a CLA Manager has now removed you from the authorization list." to: "However, a CLA Manager ({{CLA-MANAGER-NAME}}) has now removed you from the authorization list."


Case 2: CLA Manager removes someone; project where CCLA+ICLA combination IS required (e.g. the rare case)

Hello {{.RecipientName}},

This is a notification email from EasyCLA regarding the CLA Group {{.CLAGroupName}}.

You were previously authorized to contribute on behalf of your company {{COMPANY-NAME}} under its CLA. However, a CLA Manager has now removed you from the authorization list. This has additionally resulted in invalidating your current signed Individual CLA (ICLA).

As a result, you will no longer be able to contribute until you are again authorized under another signed CLA.

Please contact one of the CLA Managers from your company if you have questions about why you were removed. The CLA Managers from your company for this CLA are:
{{LIST CLA-MANAGERS - names and email addresses}}
{normal CLA signoff}

(Same change as above if we can track the specific CLA Manager that made the change)

Case 3: Project Manager invalidates an ICLA

Hello {{.RecipientName}},

This is a notification email from EasyCLA regarding the CLA Group {{.CLAGroupName}}.

You had previously signed an Individual CLA (ICLA) to contribute to the project on your own behalf. However, the Project Manager has marked your ICLA as invalidated. This might be because the ICLA may have been signed in error, if your contributions should have been on behalf of your employer rather than on your own behalf.

As a result, you will no longer be able to contribute until you are again authorized under another signed CLA. You may need to arrange for your employer to sign a Corporate CLA (CCLA) for the project, or to add you to their authorization list if they have already signed one.

Please contact the Project Manager for this project if you have questions about why you were removed. The Project Manager is {{PROJECT MANAGER - name and email address}}.

{normal CLA signoff}

Let me know if you have any questions. Thanks!
Steve

**Comment by vinod-kadam** [comment]
As discussed in the standup, adding the case no. 4.
Case 4: CLA Manager removes someone; project where CCLA+ICLA+ECLA combination IS required (e.g. the rare case)

Hello {{.RecipientName}},

This is a notification email from EasyCLA regarding the CLA Group {{.CLAGroupName}}.

You were previously authorized to contribute on behalf of your company {{COMPANY-NAME}} under its CLA. However, a CLA Manager has now removed you from the authorization list. This has additionally resulted in invalidating your current signed Individual CLA (ICLA) and your acknowledgement.

As a result, you will no longer be able to contribute until you are again authorized under another signed CLA.

Please contact one of the CLA Managers from your company if you have questions about why you were removed. The CLA Managers from your company for this CLA are:
{{LIST CLA-MANAGERS - names and email addresses}}
{normal CLA signoff}

(Same change as above if we can track the specific CLA Manager that made the change)

**Comment by vinod-kadam** [comment]
Please note that for case 3 (Invalidation of ICLA from Project Manager Console). following ticket has been created.
https://app.zenhub.com/workspaces/easycla-5ed619832c71a855a76ef404/issues/communitybridge/easycla/2897

**Comment by manishv09** [comment]
Verified for Case 1 & 2 today on staging and found 2 differences over the sent email to the user for invalidation which is highlighted in red boxes as in below screenshot:
1. Subject title is changed and not same as mentioned in the ticket
2. Last paragraph of the email is matching as described in Case -1 & 2.
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/0085d0b4-3ce9-46e6-8ce4-5540c48382ce)

**Comment by vinod-kadam** [comment]
Harold investigated the issue & reported in 27-Apr standup that the problem was coming due to "lfid doesn't exist". @manishv09 please try with an LFID which is working fine right now.

**Comment by vinod-kadam** [comment]
@manishv09  the fix for gerrit issue has been resolved and deployed to Staging through https://github.com/communitybridge/easycla/releases/tag/v2.0.45
Please verify.

**Comment by manishv09** [comment]
Verified successfully for ICLA's and Employee acknowledgement and found working fine now. Only change required is the Invalidation email subject line.
