### ISSUE TITLE
Enhancement: Add more details to Activity Log for CLA-group name & Description update

### ISSUE THREAD

**Issue by vinod-kadam** [communitybridge/easycla#2850]
When CLA Group Name or Description or both are updated then Activity Log captured doesn't show any details indicating it.
Currently, the activity log is as follows:
![image.png](https://images.zenhubusercontent.com/5e9e9952b186e1325cf5608a/39ce6889-e6bd-4347-a5ba-545aec425c1e) 

Need to add more details which will indicate whether name was updated or description or both.

Comment given by David:
We can simply add/update the text to say:
The CLA Group name was updated to “XXXX” by "User Name".
or perhaps:
The CLA Group description was updated to “Blab blah blah” by "User Name"
or perhaps:
The CLA Group name was updated to “XXX” and the description was updated to “YYYYY” by "User Name".

Note: This ticket originated from https://jira.linuxfoundation.org/browse/PCC-832

**Comment by vinod-kadam** [comment]
Deployed to DEV, Staging & PROD through https://github.com/communitybridge/easycla/releases/tag/v2.0.23

**Comment by manishv09** [comment]
Verified on PCC Angular and found that on CLA group update, detailed event logs are captured.

https://images.zenhubusercontent.com/194341141/49180c03-ddaa-4950-b28a-955d67b7dd2f/_2850_06042021.mp4

**Comment by manishv09** [comment]
@makkalot  Activity log is not generated when CLA Group name or description is updated. Please refer attached video for reference.
[Uploading... Recording #209.mp4]

**Comment by manishv09** [comment]
Verified on Staging Angular version and found the updates made on CLA Group name or description is getting logged in Activity log now. Please refer the video attached for more information.

https://images.zenhubusercontent.com/194341141/2709e726-742f-44cc-800d-cfe955d48a85/_2850_07042021.mp4

**Comment by vinod-kadam** [comment]
This is deployed to PROD.
