### ISSUE TITLE
Not able to Un-enforce CLA on all repositories

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#2866]
Related Issue PCC-887
Steps :

1. Open repository page : HOME / VEER_ITX_DOMAIN_04 / TOOLS / EASYCLA - VEERANG_CHILD004 / REPOSITORIES
2. Now go to GitHub repository.
3. Click on enforce All CLA radio button
- See-Success prompt appears  

Actual Results : All the repository remain CLA enforced & enforce All CLA radio button remain checked.

API Response : 
`{"list":[{"auto_enabled":false,"branchProtectionEnabled":false,"connection_status":"connected","github_organization_name":"AngularStagingTest09","installationURL":"https://github.com/organizations/AngularStagingTest09/settings/installations/16084715","repositories":[{"cla_group_id":"d4d7a033-6479-49a2-944e-d837a129bd76","connection_status":"connected","enabled":true,"parent_project_id":"a097c000007q2DCAAY","project_id":"a097c000007q2DCAAY","repository_github_id":356149973,"repository_id":"0002c340-ddd5-4bff-b652-6484295c1c47","repository_name":"AngularStagingTest09/repo01"}]}]}`

Refer Video clip : 
https://images.zenhubusercontent.com/194341141/7ebb6ee2-497f-4a1d-bf16-094e3f402c05/un_enforce_cla__1_.mp4
https://images.zenhubusercontent.com/194341141/1c371e73-34c3-4cc9-bdb7-82c78197d638/un_enforce_cla.mp4

**Comment by thakurveerendras** [comment]
Same issue is also reproducible on Staging Retool site

Refer Video clip for more details 
https://images.zenhubusercontent.com/194341141/0f2f7b34-a438-456a-8595-f893b133beb6/2866.mp4

**Comment by manishv09** [comment]
Also verified on Angular when user enables Enforce CLA All foreign repositories are added to that CLA Group
https://images.zenhubusercontent.com/194341141/deff9113-2726-41d0-b7b2-3e667ef90214/_2866_ang_12042021.mp4

**Comment by manishv09** [comment]
Verified on Staging and found working fine on PCC Angular. Please refer video for reference:

https://images.zenhubusercontent.com/194341141/244e164e-9249-410f-a62c-e79e25934aee/_2866_16042021.mp4

**Comment by vinod-kadam** [comment]
Deployed to PROD through https://github.com/communitybridge/easycla/releases/tag/v2.0.33
