### ISSUE TITLE
Even if CLA Group description is not updated still the log shows it & same for CLA Group Name

### ISSUE THREAD

**Issue by manishv09** [communitybridge/easycla#2869]
Even if CLA Group description is not updated still the log shows it & same for CLA Group Namehttps://images.zenhubusercontent.com/194341141/acb96d15-d59d-4a98-9701-b39cde888922/pcc_895_13042021.mp4

**Comment by manishv09** [comment]
Verified on Staging angular and found working as expected. Please refer the attached video for reference

https://images.zenhubusercontent.com/194341141/ef0f0f7a-8bbc-42d3-b0cb-d751df31f82a/_2869_16042021.mp4

**Comment by vinod-kadam** [comment]
Deployed to PROD through https://github.com/communitybridge/easycla/releases/tag/v2.0.33
