### ISSUE TITLE
Improvement : Activity-log event should not fire when click on OK or Cancel button at Delete CLA Group prompt.

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#2870]
Steps :

1. Open easyCLA page : https://pcc.staging.platform.linuxfoundation.org/project/a097c000007pundAAA/tools/easycla/overview
2. Now click on Delete CLA group icon.
- See-API event fired at network tab
3. Now Click on Cancel or Ok button at Delete CLA group prompt
- **Actual Results** : Activity-log event fired while Delete CLA group is just information dialog 

`{"Events":[{"EventCLAGroupID":"3a946a78-4397-4a83-b93c-463c0c615ca8","EventCLAGroupName":"Veer_LLC_CLA","EventCLAGroupNameLower":"veer_llc_cla","EventCompanyID":"0702ab0b-5d3d-433c-9fde-d0352a2e6e80","EventCompanyName":"Proxima","EventCompanySFID":"0012M00002MnADGQA3","EventData":"CLA Manager: veerendrat, Email: veerendrat@proximabiz.com, LFID: ff9f1a52-bc43-4257-8b4d-ef21330c2854 added GitHub Username: vrthakur to the approval list for Company: Proxima, Project: Veer_Staging_Standalone_LLC.","EventID":"25d8e348-9a12-444e-bcfc-0a549cf3d7ba","EventProjectID":"a097c000007pundAAA","EventProjectName":"Veer_Staging_Standalone_LLC","EventProjectSFID":"a097c000007pundAAA","EventSummary":"The CLA Manager veerendrat added the GitHub username vrthakur to the approval list for the CLA Group Veer_LLC_CLA for the project Veer_Staging_Standalone_LLC for the company Proxima.","EventTime":"2021-03-22T09:51:36.000000+0000","EventTimeEpoch":1616406696,"EventType":"cla_manager.approval_list_updated","UserID":"ff9f1a52-bc43-4257-8b4d-ef21330c2854","UserName":"Veerendra Thakur"},{"EventCLAGroupID":"3a946a78-4397-4a83-b93c-463c0c615ca8","EventCLAGroupName":"Veer_LLC_CLA","EventCLAGroupNameLower":"veer_llc_cla","EventCompanyID":"0702ab0b-5d3d-433c-9fde-d0352a2e6e80","EventCompanyName":"Proxima","EventCompanySFID":"0012M00002MnADGQA3","EventData":"User: Veerendra Thakur was assigned Scope: a097c000007pundAAA|0012M00002MnADGQA3 with Role: cla-manager-designee for Project: Veer_Staging_Standalone_LLC with ID: a097c000007pundAAA.","EventID":"f8ced66d-68c8-4460-a199-90a2fa0af786","EventProjectID":"a097c000007pundAAA","EventProjectName":"Veer_Staging_Standalone_LLC","EventProjectSFID":"a097c000007pundAAA","EventSummary":"The user Veerendra Thakur was added to the role cla-manager-designee for the CLA Group Veer_LLC_CLA for the project Veer_Staging_Standalone_LLC for the company Proxima.","EventTime":"2021-03-22T09:47:38.000000+0000","EventTimeEpoch":1616406458,"EventType":"lfx_org_service.assign_user_role_scope","UserID":"0037c00000xsDTPAA2"}]}`

Refer Video clip : 
https://images.zenhubusercontent.com/194341141/24ac2c15-7099-40be-8553-5a3af07e5c39/deleteclaprompt.mp4

**Comment by makkalot** [comment]
This issue looks like it's related to the frontend. If an event log is generated this means we received some backend request. When clicked OK or Cancel the frontend should avoid sending the request to the backend in this case.

**Comment by vinod-kadam** [comment]
It was discussed in the 16-April standup that as it is a front-end issue, we should close this ticket and log a PCC ticket.
Following PCC ticket has been logged.
https://jira.linuxfoundation.org/browse/PCC-921
So closing this ticket.
