### ISSUE TITLE
If there is only 1 CLA Group and if user updates the Projects covered and remove them all the CLA Group is removed from CLA Overview page

### ISSUE THREAD

**Issue by manishv09** [communitybridge/easycla#2871]
If there is only 1 CLA Group and if user updates the Projects covered and remove them all the CLA Group is removed from CLA Overview page

Please refer the attached video for reference.

https://images.zenhubusercontent.com/194341141/967860a3-cf51-48f8-a0e4-c865129f3b00/activitylog_clagroupremovedissue_14042021.mp4

**Comment by makkalot** [comment]
Here we call https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/unenrollProjects endpoint when we uncheck the box and click Udate Cla Group. What happens after that is we disassociate the projecSFID with the cla group ID (on easyCLA side) and also we disable CLA service for that projectSFID (on project Service side.). As a user experience when the last entry is unenrolled from CLA Group is something to be defined and implemented accordingly on the frontend. Backend is working as expected imo.

**Comment by thakurveerendras** [comment]
Hi @makkalot ,

Issue is still reproducible as reported. I will discuses this issue in today's PCC standup call & will raise your concerns & suggestion to team 

Refer Video clip : https://images.zenhubusercontent.com/194341141/e42ef5ad-7b37-4d5c-9bfb-9862fe48799c/2871.mp4

CC: @vinod-kadam , @pranab-bajpai 
Thanks

**Comment by vinod-kadam** [comment]
As discussed in the standup with Pranab, it was decided to add a warning message that you can unenroll the last project. @pranab-bajpai  to add a message for it.

**Comment by pranab-bajpai** [comment]
When the user is about the unenroll the last project in a CLA Group we should not let them do that and show the following message in a dialog box.
CLA Group needs to have at least one project. If you are trying to delete this CLA Group please file a JIRA ticket here (embed this link within here - https://jira.linuxfoundation.org/plugins/servlet/theme/portal/4/create/143).

**Comment by vinod-kadam** [comment]
Closing this ticket as following PCC ticket has been logged.
https://jira.linuxfoundation.org/browse/PCC-922
