### ISSUE TITLE
Activity log issue is again appearing on PCC Angular version. "The CLA Group was updated by the user manishv comprmgr."

### ISSUE THREAD

**Issue by manishv09** [communitybridge/easycla#2872]
Activity log issue is again appearing on PCC Angular version. "The CLA Group was updated by the user manishv comprmgr."

https://images.zenhubusercontent.com/194341141/a4c31707-352a-4a4a-b1b0-e3f431f907fe/activitylog_clagroupremovedissue_14042021.mp4

https://images.zenhubusercontent.com/194341141/e97de879-a43e-46a8-af47-857576c1decc/activitylogissue_14042021.mp4

**Comment by vinod-kadam** [comment]
@manishv09  please verify on STAGING.

**Comment by dibyaranjanlf** [comment]
Added project to PCC staging through PCC, and updated through SF. Data issues in Activity Log. Incorrect and missing data on the highlighted sections.
![image.png](https://images.zenhubusercontent.com/5ff7320002fff1248f0b8ae8/10d73a5b-cbc6-432e-aac9-46e7cab170c1)

**Comment by manishv09** [comment]
Verified on Angular Staging today and found that the incomplete logs are still getting generated. Please refer the screencast below:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/21037c31-74e5-4aa7-90c0-5ccbda15d01b)

**Comment by vinod-kadam** [comment]
Deployed to DEV, STAGING & PROD through https://github.com/communitybridge/easycla/releases/tag/v2.0.34

**Comment by manishv09** [comment]
Verified on Staging environment and found no extra logs are generated when user tries to update the CLA Group.

https://images.zenhubusercontent.com/194341141/1bfc602c-fff9-411e-9405-2e06d987dc8b/_2872_20042021.mp4
