### ISSUE TITLE
Unable to add approval criteria for Gerrit project

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2882]
When adding either an individual email or domain, the request times out.

![image](https://user-images.githubusercontent.com/46732999/115267803-987b6a00-a107-11eb-8b65-bed1983b8804.png)

**Comment by vinod-kadam** [comment]
Deployed to DEV, Staging & PROD through https://github.com/communitybridge/easycla/releases/tag/v2.0.38

**Comment by manishv09** [comment]
Verified on staging and found user is again encountered with error 400. Please refer the screencast below:

![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/ccae6048-8606-4341-a0f2-b153aa550862)

**Comment by manishv09** [comment]
I verified this issue on Staging today and found working fine now. 

Please refer the attached video for reference.

https://images.zenhubusercontent.com/194341141/61cffb98-ae5d-4bd8-be8d-8e8d471b04fa/_2882_26042021_approvalcrt.mp4

**Comment by vinod-kadam** [comment]
@WillsonHG  confirmed in 23-April's standup that it is working fine even on PROD. So closing the ticket.
