### ISSUE TITLE
Addition or removal log are showing different names.

### ISSUE THREAD

**Issue by manishv09** [communitybridge/easycla#2886]
Addition or removal log are showing different names.

![IncorrectUserName.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/66bf96e0-a44f-47a1-a958-3cacf3298258)

**Comment by vinod-kadam** [comment]
Deployed to DEV, Staging & PROD through https://github.com/communitybridge/easycla/releases/tag/v2.0.38

**Comment by manishv09** [comment]
The logs still not appearing correct now the user who is added as CLA Manager is appearing as the same name of the CLA Manager who added him. 
Please refer the screencast below: 
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/df2976b9-8b67-46b0-9742-e4e77d68d271)

https://images.zenhubusercontent.com/194341141/378dc344-3825-4a8f-8260-6676a9e63bda/_2886_23042021.mp4

**Comment by dealako** [comment]
Created new PR with updated event log info: https://github.com/communitybridge/easycla/pull/2902

Please re-test.

**Comment by dealako** [comment]
Created new PR for updating the event log for CLA managers: https://github.com/communitybridge/easycla/pull/2904

**Comment by manishv09** [comment]
Verified it is still reproducible. Please refer screencast below: 
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/3a962c29-e5aa-4240-ad91-e205aac34e0b)
Is PR merged to staging environment?

**Comment by manishv09** [comment]
Verified on staging environment and found working fine. Please refer the attached video and email screencast as follows:
![image.png](https://images.zenhubusercontent.com/5face8c0a2ad18653594316c/e48af882-5fc0-4349-8206-b0e0d411b564)

https://images.zenhubusercontent.com/194341141/863f7011-de67-4f20-a8c9-87016bcabbed/_2886_05052021.mp4

**Comment by vinod-kadam** [comment]
This is also deployed to PROD.
