### ISSUE TITLE
Search is not working for ICLA's on signatures tab under EASY CLA Overview page

### ISSUE THREAD

**Issue by manishv09** [communitybridge/easycla#2891]
Search is not working for ICLA's on signatures tab under EASY CLA Overview page

Please refer the video attached for reference.

[Uploading... Recording #286.mp4]

**Comment by nickmango** [comment]
@manishv09 the video link you shared points to a PR. Could you kindly reshare ?

**Comment by vinod-kadam** [comment]
As updated by @nickmango over slack, changes has been pushed to Staging & PROD & ready for verification.
@manishv09  please verify on Staging.

**Comment by manishv09** [comment]
Verified on staging and found search criteria is working fine for the project group having 100+ signature. As per discussion with @nickmango it needs UI cleanup for progress bar on the progress of search.
Please refer the attached video for reference.

https://images.zenhubusercontent.com/194341141/a28c48df-8baa-4d5d-bdb8-2f5c7fee9781/_2891_28042021.mp4

**Comment by vinod-kadam** [comment]
Deployed to PROD through https://github.com/communitybridge/easycla/releases/tag/v2.0.44
