### ISSUE TITLE
Signatory email not being sent

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2938]
From the v2 Organization portal, the initial cla manger selects to send the CLA to the signatory to sign. After filling in the name and email of the authorised signatory, clicking proceed results in the dialog remaining open. Fields remain filled in (name & email). The only difference is that a hash or other code is displayed in red on the dialog.

There are no indicators of success, and the designated person has indicated that they haven't received any emails despite the process being done several times.

In the logs:

  "emailID": "redacted@foundry.com",     "error": "[POST /v1/orgs/{salesforceID}/scopes][400] createOrgUsrRoleScopesBadRequest  &{Code:400 Message:organization-service - usernames: non zero value required XRequestID:638f3090-b248-11eb-9715-0146c7c583f6}",     "functionName": "organization_service.CreateOrgUserRoleOrgScopeProjectOrg",     "level": "warning",     "msg": "CreateOrgUserRoleScope failed",     "organizationID": "0014100001qbycqAAA",     "projectID": "a092M00001If9ujQAB",     "roleID": "5ef9f673-1219-46cc-a90a-89b9db10d5a9",     "time": "2021-05-11T11:02:34Z",     "x-request-id": "63627b40-b248-11eb-a161-b3aeee8fc39e" } | {"emailID":"redacted@foundry.com","error":"[POST /v1/orgs/{salesforceID}/scopes][400] createOrgUsrRoleScopesBadRequest \u0026{Code:400 Message:organization-service - usernames: non zero value required XRequestID:638f3090-b248-11eb-9715-0146c7c583f6}","functionName":"organization_service.CreateOrgUserRoleOrgScopeProjectOrg","level":"warning","msg":"CreateOrgUserRoleScope failed","organizationID":"0014100001qbycqAAA","projectID":"a092M00001If9ujQAB","roleID":"5ef9f673-1219-46cc-a90a-89b9db10d5a9","time":"2021-05-11T11:02:34Z","x-request-id":"63627b40-b248-11eb-a161-b3aeee8fc39e"}

https://us-east-2.console.aws.amazon.com/cloudwatch/home?region=us-east-2#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fcla-backend-go-api/log-events/2021$252F05$252F11$252F$255B$2524LATEST$255D39eb65b67a714cd0ac351e489b9e1e7a$3Fstart$3D1620730954068$26refEventId$3D36143508044271981437708149896757863150368728846343471119

**Comment by nickmango** [comment]
This issue is raised by the org service endpoint that performs role association for a given user. If the user does not have username set that will raise the above issue.

**Comment by WillsonHG** [comment]
@wanyaland  In the cases of the CLA signatory, they should not need a username/LFID/entry in the database. All they do is sign the CLA via email.

And in this case, the email was was not found in either our SSO systems or in the EasyCLA database.

**Comment by nickmango** [comment]
@WillsonHG the error is thrown by core services and not EasyCLA. On EasyCLA it works as expected . Issue happens when a user is getting assigned a role ie User X getting assigned cla-manger-designee role but missing out the username attribute

**Comment by dealako** [comment]
Deployed a fix to DEV, STAGING, and PROD. Logic was updated to not hard fail if we are not able to assign the cla-signatory role.
