### ISSUE TITLE
V1 Contributor Console Typo fix in Error message

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#2955]
When a user is gated by EasyCLA in their pull request and select corporate, company not in list, and "no" to being cla manager - they are asked to fill in a form to ask their cla manager to sign the cla. 

If they provide a company name that is already in EasyCLA, an error message appears with a typo.

"Comapny already exist with the name: ..."

Please change the error message to read "Company already exists with the name: " and fill in the name. 

![image](https://user-images.githubusercontent.com/46732999/119044824-acc1b980-b988-11eb-8316-c75076316ea4.png)

**Comment by dealako** [comment]
Created PR: https://github.com/communitybridge/easycla/pull/2956
Merged to DEV
Ready for QA

**Comment by dealako** [comment]
This update will be included in the next release.
