### ISSUE TITLE
403 Forbidden status for icla signatures request when CLA group is created with only CCLA type

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#2960]
**Project Details** 
- Environment : Staging 
- Project SFiD : a097c0000081ZSQAA2
- Project Name : SKTEST01
- claGroupId : 0b75a0f8-3689-4405-b74f-26cbefd9cd6d

**Steps** :

1. Add CLA group with only CCLA CLA type is selected 
2. Go to cooperate console portal & sign CCLA
3. Request icla signatures API : {{baseUrl}}signatures/project/{{claGroupID}}/icla/signatures

Actual Results : 403 Forbidden status appears in response 
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/976d6824-5307-4eef-ab67-56ec5269256b)

**Comment by dealako** [comment]
@thakurveerendras I am not experiencing this error.  With the recent query updates, would you mind testing once more?

![Screen Shot 2021-06-01 at 11.11.31 AM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/eff9d956-790b-4fbe-9fe6-56a45d85d4d2)

My user in staging has the PM role:

![Screen Shot 2021-06-01 at 11.19.02 AM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/ee6f4ead-0707-4163-a792-2f44a10d0dd7)

I have removed a seemingly invalid entry in your IAM permissions (not sure this will effect the results of this test):

![Screen Shot 2021-06-01 at 11.23.11 AM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/d733b903-6678-4303-af62-55b02f075875)

**Comment by thakurveerendras** [comment]
Hi @dealako 
Retested API & found it return 200 status with 0 results as expected. 

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/a1de7ff5-696b-4316-aaf1-3eeae2cfedc6)

For invalid entry : I am not sure how it added on IAM, Will take care of this next time. I will let know you with reproducible steps

Thanks

**Comment by vinod-kadam** [comment]
@thakurveerendras  reported that he is not able to reproduce the issue anymore.
