### ISSUE TITLE
Can't set up the dev environment.

### ISSUE THREAD

**Issue by hwchiu** [communitybridge/easycla#299]
**Summary**

I followed the document **DEV.md** to set up the local environment and failed in backend part.

**Background**

I would like to set up a local environment to test it and I found a document `DEV.md.
I followed that document to setup the `cla-backend` and `cla-backend-go` and didn't have a correct config file.

In `cla-backend`.

For the forth command `make add_project_manager_permission username=<username> project_sfdc_id=<sfdc_id> bearer_token=<token> base_url=http://localhost:5000`.

What is `sfdc_id` and `token` and how should I generate those values?

In `cla-backend-go`.

I followed the golang config struct to set up a basic env.json.
```json=
{
  "aws": {
    "region":"us-east-1"
  }
}
```
and it still be error when I run `./cla server --config env.json`
```bash=
Logging format not defined - setting value to default: 'text'
Logging configured with level: debug, format: text
INFO[2019-10-24T18:05:56Z] Running init...
FATA[2019-10-24T18:05:56Z] AWS_REGION environment variable cannot be empty
```

I tried to use the env var to override the `AWS_RESION` and it seems I still missed some values.
```bash=
AWS_REGION=us-east-1 ./cla server --config env.json
...
INFO[2019-10-24T18:06:41Z] Service CLA_SERVICE starting...
INFO[2019-10-24T18:06:41Z] Name                    : CLA_SERVICE
INFO[2019-10-24T18:06:41Z] Version                 : aa087325
INFO[2019-10-24T18:06:41Z] Git commit hash         : aa087325
INFO[2019-10-24T18:06:41Z] Branch                  : master
INFO[2019-10-24T18:06:41Z] Build date              : 2019-10-22T21:52:55+0000
INFO[2019-10-24T18:06:41Z] Golang OS               : linux
INFO[2019-10-24T18:06:41Z] Golang Arch             : amd64                                                                                             INFO[2019-10-24T18:06:41Z] GH_ORG_VALIDATION       : true
INFO[2019-10-24T18:06:41Z] COMPANY_USER_VALIDATION : true
INFO[2019-10-24T18:06:41Z] STAGE                   : dev
INFO[2019-10-24T18:06:41Z] Service Host            : k8s-dev
INFO[2019-10-24T18:06:41Z] Service Port            : 8080
INFO[2019-10-24T18:06:41Z] Loading local config...
PANI[0000] Unable to setup docraptor client - Error: invalid key
panic: (*logrus.Entry) (0x12146e0,0xc0002bb900)
...
```

**Expected behavior**

Could we have an example configuration files for cla-backend and cla-backend-go?
like serverless.yml, env.json.

**Screenshots**

NA

**Environment**

Please complete the following information:

Related software version:
- go version go1.13.1 linux/amd64
- OS:    Ubuntu 18.04.1 LTS, 4.15.0-29-generic
- Serverless:
```
serverless --version
Framework Core: 1.54.0
Plugin: 3.1.2
SDK: 2.1.2
Components Core: 1.1.1
Components CLI: 1.4.0
```
- nodejs: v8.16.2
- Python 3.6.8

**Additional Context**

NA
**Acceptance Criteria**

1. Anyone can follow the DEV document to easily set up a local environment for testing.

**References**

[DEV.md](https://github.com/communitybridge/easycla/blob/master/DEV.md#cla-local-development)

**Comment by wanyaland** [comment]
Verified
