### ISSUE TITLE
Random approval list notification mail

### ISSUE THREAD

**Issue by leoluk** [communitybridge/easycla#2998]
I received this email:

![image](https://user-images.githubusercontent.com/859697/122623188-71a3ca80-d09b-11eb-922f-48d15a4d9cb0.png)

Why did I get an approval list notification update for Snowflake Inc, which I'm not affiliated with?

CC @sfc-gh-jallie

**Comment by dealako** [comment]
@leoluk thanks for reporting this. This email was sent in error as a result of migrating CNCF k8s/gRPC data from the current CLA system to EasyCLA.  The issue has been resolved. Sorry for any inconvenience this may have caused.
