### ISSUE TITLE
Not able to update name of the cla group at easyCla overview page & 400 error appears on API response

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3035]
Steps:
1. Sign in to the Admin console.
2. Create a CLA group.
3. Update that group name.
Actual Results : 400 error appears 

- API Endpoint:  {{baseUrl}}cla-service/v4/cla-group/{{cla_group_id}}
- baseUrl : https://api-gw.staging.platform.linuxfoundation.org/
- cla_group_id : ceda17b1-9b0b-44f6-bd15-0e17a6215911

API Response : 400 Bad Request
API Response body :
````
{
    "Code": "400",
    "Message": "EasyCLA - 400 Bad Request - unable to update CLA Group by ID: ceda17b1-9b0b-44f6-bd15-0e17a6215911 - error: problem updating CLA Group - changing CLA templates is not allowed - project: Veer Foundation-Test 02 with ID: ceda17b1-9b0b-44f6-bd15-0e17a6215911 - previous template:  updated template: ",
    "x-request-id": "b4e6f730-e8a7-11eb-bc5a-0b9281dee6cb"
}
````

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/d090a098-ad8d-4558-ae9e-e59bf815a219)

**Comment by dealako** [comment]
Deployed updates to resolve this issue to DEV, STAGING, and PROD. Please confirm/re-test to confirm the fix.

**Comment by thakurveerendras** [comment]
Hi @dealako ,
Issue is tested on dev & staging site & found that it is fixed as expected on API & UI, So making issue status QA-Done

**Here is API Results** : 
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/3d249434-875d-4183-9611-c28cdc2b6d28)

- API Endpoint: {{baseUrl}}cla-service/v4/cla-group/{{cla_group_id}}
- baseUrl : https://api-gw.staging.platform.linuxfoundation.org/
- cla_group_id : ceda17b1-9b0b-44f6-bd15-0e17a6215911

**API Response** : 200 OK
API Response body :

```
{
    "ccla_enabled": true,
    "ccla_pdf_url": "https://cla-signature-files-staging.s3.amazonaws.com/contract-group/ceda17b1-9b0b-44f6-bd15-0e17a6215911/template/ccla-2021-07-16T17-02-50Z.pdf",
    "ccla_requires_icla": true,
    "cla_group_description": "CLA group created for Veer API Foundation-Test",
    "cla_group_id": "ceda17b1-9b0b-44f6-bd15-0e17a6215911",
    "cla_group_name": "Veer Foundation-Test 02",
    "foundationLevelCLA": true,
    "foundation_name": "Veer ApiTest Standalone Project",
    "foundation_sfid": "a097c0000081POIAA2",
    "icla_enabled": true,
    "icla_pdf_url": "https://cla-signature-files-staging.s3.amazonaws.com/contract-group/ceda17b1-9b0b-44f6-bd15-0e17a6215911/template/icla-2021-07-16T17-02-50Z.pdf",
    "project_list": [
        {
            "project_name": "Veer ApiTest Standalone Project",
            "project_sfid": "a097c0000081POIAA2",
            "repositories_count": 0
        }
    ],
    "repositories_count": 0,
    "root_project_repositories_count": 0,
    "setup_completion_pct": null,
    "total_signatures": 0
}
```

**Here is PCC UI Results** : 
-Able to update CLA group name & Activity logs are updated for recent change , Refer video clip 
https://images.zenhubusercontent.com/194341141/72f3fc8e-3d9c-4981-9610-1f775770c8e1/_3035.mp4
