### ISSUE TITLE
FINOS : Approved contributor entry is missing for "Adaptive Financial Consulting" organization at FINOS project

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3056]
Steps :

1. Navigate to Signature tab : https://projectadmin.lfx.linuxfoundation.org/project/a092M00001JwBlEQAV/tools/easycla/overview/5564f18f-3252-40fc-a65b-2eef1ad45fcd/signatures
2. Open Signed CCLAs tab
3. Search Organization "**Adaptive Financial Consulting**"
4. Click on View All Approved Contributors

Actual :
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/0f9e0ee3-7d5d-4330-86ea-88a6db7b9bb1)

Expected :
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/42493f48-f774-474c-9ca3-3a4b9c342140)

**Comment by nickmango** [comment]
@thakurveerendras  Adaptive Finance Consulting is using domain approval list rather than user approval list. The domain in this use case is weereadaptive.com
cc @vinod-kadam @dealako

**Comment by thakurveerendras** [comment]
@nickmango , could you please let me how can I verify user data which are mentioned on Finos sheet.

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/124cdb0c-bebd-4730-be57-1720f70905d2)
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/7791e9e7-8ca2-4d4c-9352-a4b3c983508b)

**Comment by thakurveerendras** [comment]
@nickmango All User entry found (checked only email, GitHub ID & LFID) under approval contributor list, So making issue status QA-Done

Actual :
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/09858d4b-1f93-41fa-85d2-1768d4fc0e94)
Expected : 
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/ce81dc1e-579d-4d1a-a4f7-ad9f2c684f79)
