### ISSUE TITLE
FINOS : "Eddie Knight" & "Ian Tivey" user entry is missing under APPROVED CONTRIBUTORS list for "Citihub Consulting" organization at FINOS project 

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3060]
Steps :

1. Navigate to Signature tab : https://projectadmin.lfx.linuxfoundation.org/project/a092M00001JwBlEQAV/tools/easycla/overview/5564f18f-3252-40fc-a65b-2eef1ad45fcd/signatures
2. Open Signed CCLAs tab
3. Search Organization "Citihub Consulting"
4. Click on View All Approved Contributors

Actual
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/a4b3c8ec-cd4b-4a2e-9b8b-f45f4abcf0b9)

Expected : 
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/742d48b8-68f8-41ff-adc4-7b51ab58009a)

**Comment by nickmango** [comment]
@thakurveerendras Kindly verify

**Comment by thakurveerendras** [comment]
User details is still missing 
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/ac9e485a-75c8-45be-9ea6-78cfd18ddea1)
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/36d6ebde-42e8-412e-b9ff-7041b191690c)
