### ISSUE TITLE
FINOS : Found duplicate entry under APPROVED CONTRIBUTORS list for "Epam" organization at FINOS project

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3061]
Steps :

1. Navigate to Signature tab : https://projectadmin.lfx.linuxfoundation.org/project/a092M00001JwBlEQAV/tools/easycla/overview/5564f18f-3252-40fc-a65b-2eef1ad45fcd/signatures
2. Open Signed CCLAs tab
3. Search Organization "**Epam**"
4. Click on View All Approved Contributors

Actual : 
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/65141c91-932f-467d-8a1a-2a94f54706d5)

**Comment by nickmango** [comment]
@thakurveerendras Kindly verify

**Comment by thakurveerendras** [comment]
Still duplicate entry appears for "Epam" org 
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/75f4e47a-6ddb-434e-96c3-a217e87e6265)
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/2517c9fc-d0d9-454a-8c7b-09ac4ca8773a)

**Comment by wanyaland** [comment]
@thakurveerendras Kindly review

**Comment by thakurveerendras** [comment]
Now duplicate data are removed form "Epam" organization, So making issue status QA-Done

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/ce384e50-ad7c-4925-95c6-66e92017d5ea)
