### ISSUE TITLE
 FINOS : "Kevin Barresi" user entry is missing under APPROVED CONTRIBUTORS list for "Fintech Studios" organization at FINOS project

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3062]
Steps :

1. Navigate to Signature tab : https://projectadmin.lfx.linuxfoundation.org/project/a092M00001JwBlEQAV/tools/easycla/overview/5564f18f-3252-40fc-a65b-2eef1ad45fcd/signatures
2. Open Signed CCLAs tab
3. Search Organization "**Fintech Studios**"
4. Click on View All Approved Contributors

Actual 
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/5028746f-1977-423d-8cae-2bda11a281f6)

Expected : 
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/4f807730-1287-4161-8838-8ca6eee1a99c)

**Comment by nickmango** [comment]
@thakurveerendras Kindly review

**Comment by thakurveerendras** [comment]
"Kevin Barresi" user entry is still missing
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/083ab9b2-39df-468e-a6c9-e56b22249dc5)
