### ISSUE TITLE
FINOS : up-to 66 user entry is missing under APPROVED CONTRIBUTORS list for "Goldman Sachs" organization at FINOS project

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3063]
Steps :

1. Navigate to Signature tab : https://projectadmin.lfx.linuxfoundation.org/project/a092M00001JwBlEQAV/tools/easycla/overview/5564f18f-3252-40fc-a65b-2eef1ad45fcd/signatures
2. Open Signed CCLAs tab
3. Search Organization "Goldman Sachs"
4. Click on View All Approved Contributors

Actual
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/6d550052-1362-45a6-abdd-2d7dc714df7e)

Expected :
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/3a81d787-b380-4b37-8525-c93adbd11f4a)

**Comment by nickmango** [comment]
@thakurveerendras Kindly review

**Comment by thakurveerendras** [comment]
Checked all missing data are added under approved contributor list but "GS OSS Bot" user data is still missing 
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/71483f13-d326-4600-aff9-d565c1c72b55)
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/a9633f4c-1f73-4733-9ed4-71a806178591)


-----------------------------------------------------------------------------------------------------------------
**One concerns** :  Goldman Sachs & Co. LLC also listed while no such org mentioned in Finos sheet
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/7730af26-df8f-4852-b7bd-559240c8d517)

**Comment by thakurveerendras** [comment]
Now "GS OSS Bot" user data appears on list, So making issue status QA-Done
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/a4d7d894-4738-406e-813a-11a297cab49f)
