### ISSUE TITLE
FINOS : Found duplicate entry under APPROVED CONTRIBUTORS list for "Red Hat" organization at FINOS project

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3069]
Steps :

1. Navigate to Signature tab : https://projectadmin.lfx.linuxfoundation.org/project/a092M00001JwBlEQAV/tools/easycla/overview/5564f18f-3252-40fc-a65b-2eef1ad45fcd/signatures
2. Open Signed CCLAs tab
3. Search Organization "Red Hat"
4. Click on View All Approved Contributors

Actual Results : 
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/a45df37e-508c-428c-81cb-7e34143d5d45)

**Comment by nickmango** [comment]
@thakurveerendras resolved. Kindly verify

**Comment by thakurveerendras** [comment]
Still duplicate data found for "Red Hat" organization, So making issue status QA-Failed 
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/882ddc38-2450-47f9-ae68-1c8a794dca17)
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/07146e8c-de81-4431-8f78-80b01e3083fe)

**Comment by nickmango** [comment]
@thakurveerendras kindly review

**Comment by thakurveerendras** [comment]
Now duplicate entry is removed but "Alessandro Petroni" user details is missing

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/6299bd57-91e2-4c83-b6f5-6f6a2c370430)

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/1bab029d-27ee-4360-abf2-0d4572c28efb)

**Comment by thakurveerendras** [comment]
Now again found duplicate entry for organization

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/c838c3a1-8a43-4391-994e-19e6c9d9d237)

**Comment by thakurveerendras** [comment]
**Alessandro Petroni** user Name filed is missing 

- Now **Diane Mueller-Klingspor** user have LFID 

**Actual :**
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/bb1e915d-3b0e-487a-b688-873b367b7c76)
**Expected :**
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/ab7396d8-d08b-4d6b-9abf-3f8783199721)

**Comment by nickmango** [comment]
@thakurveerendras kindly verify.. 
I updated Alesandros details
For mueller that could have been an update on their part to add lfid. The other records are correct as script didnt add random lfid

**Comment by thakurveerendras** [comment]
Now missing Name field is also added for user, So making issue status QA-Done
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/36d87360-e7ce-4a47-8385-df245cb550a3)
