### ISSUE TITLE
FINOS : "Nigel Cobb" user entry is missing under APPROVED CONTRIBUTORS list for "Regnosys" organization at FINOS project

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3070]
Steps :

1. Navigate to Signature tab : https://projectadmin.lfx.linuxfoundation.org/project/a092M00001JwBlEQAV/tools/easycla/overview/5564f18f-3252-40fc-a65b-2eef1ad45fcd/signatures
2. Open Signed CCLAs tab
3. Search Organization "Regnosys"
4. Click on View All Approved Contributors

Actual :
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/97bf0c99-fc97-474b-9a29-fc0135f27780)

Expected : 
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/031ef9b6-9ad0-4f04-bd26-97e201ec0aa9)

**Comment by nickmango** [comment]
@thakurveerendras Kindly verify

**Comment by thakurveerendras** [comment]
"Nigel Cobb" user details is added but email & GitHub details is wrong

Actual : 
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/efb1217b-0985-4868-951b-3f8a6030d360)

Expected  :
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/f51b7b3a-37c7-4d93-9ff5-fcf4b5cadaa5)

**Comment by nickmango** [comment]
This user was previously created so didnt change that. @thakurveerendras 
<img width="608" alt="Screenshot 2021-07-30 at 18 56 47" src="https://user-images.githubusercontent.com/81645226/127679681-eff06868-ee5f-4180-9a53-e23a5975dd44.png">

**Comment by vinod-kadam** [comment]
@wanyaland  as discussed in the standup, please update the github username in easycla with nigelcobb
No need to change the email address since email address domain is same as company domain.

**Comment by nickmango** [comment]
Updated as discussed. @thakurveerendras kindly verify
cc @vinod-kadam

**Comment by thakurveerendras** [comment]
User details is updated as mentioned above, So making issue status QA-Done

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/8b00e052-8270-4b43-af1d-af29daf93911)
