### ISSUE TITLE
FINOS : "Andrew So & Rajesh Taparia " user entry is missing under APPROVED CONTRIBUTORS list for "Royal Bank of Canada" organization at FINOS project

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3071]
Steps :

1. Navigate to Signature tab : https://projectadmin.lfx.linuxfoundation.org/project/a092M00001JwBlEQAV/tools/easycla/overview/5564f18f-3252-40fc-a65b-2eef1ad45fcd/signatures
2. Open Signed CCLAs tab
3. Search Organization "Royal Bank of Canada"
4. Click on View All Approved Contributors

Actual Results : "Andrew So & Rajesh Taparia " user entry is missing
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/653754bd-8c54-437b-bfb5-0c390659ad28)

**Comment by nickmango** [comment]
@thakurveerendras  Kindly verify

**Comment by thakurveerendras** [comment]
Issue seems to fixed & all user data added , So making issue status QA-Done

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/dfa60392-a23d-4d20-b0bb-91d9ed02d034)
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/17269cdc-960c-4c55-9485-2fa65dbdb3fe)
