### ISSUE TITLE
FINOS : Duplicate entry appears for foreign user (peterschrammel) under APPROVED CONTRIBUTORS list for "Scott Logic" organization at FINOS project

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3073]
Steps :

1. Navigate to Signature tab : https://projectadmin.lfx.linuxfoundation.org/project/a092M00001JwBlEQAV/tools/easycla/overview/5564f18f-3252-40fc-a65b-2eef1ad45fcd/signatures
2. Open Signed CCLAs tab
3. Search Organization "Scott Logic"
4. Click on View All Approved Contributors

Actual Results  : Duplicate entry appears for foreign user (peterschrammel) 
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/015e179d-e49b-4253-a3da-84107d10b9da)
Expected : 
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/1c2778db-429c-4022-80f8-509f8a197b77)

**Comment by thakurveerendras** [comment]
Same results for **Symphony LLC** organization 
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/90f33f01-3605-4023-9810-9cf7fadd4979)

**Comment by thakurveerendras** [comment]
Same results for **UBS** organization
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/3f6f04c9-3d48-4c51-aff9-29dd4be0ab54)

**Comment by thakurveerendras** [comment]
Same results for **JP Morgan Chase** organization
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/3d73a3c3-9ead-4316-abbc-79dd4495c187)

**Comment by nickmango** [comment]
@thakurveerendras Kindly verify .Removed these records that happened to be related to LinuxFoundation bot.

**Comment by thakurveerendras** [comment]
**peterschrammel** user information is removed as expected , So making issue status QA-Done
**JP MORGAN CHASE**
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/46b40df5-1e12-4ebe-b04e-f660be6cabfd)

**openfin**
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/c03c9e95-ea46-46d1-8321-7c3b9db2d06b)

**UBS**
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/d37499d5-5c13-4601-a814-b216aee15f93)

**SYMPHONY LLC**
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/477480b2-af46-4cb5-86de-079a86180bab)

**Scott Logic**
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/c6b1f32f-accc-40e3-8b42-7d586c51d224)
