### ISSUE TITLE
FINOS : "Nigel Hyde" user entry is missing under APPROVED CONTRIBUTORS list for "Skylight IPV" organization at FINOS project

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3074]
Steps :

1. Navigate to Signature tab : https://projectadmin.lfx.linuxfoundation.org/project/a092M00001JwBlEQAV/tools/easycla/overview/5564f18f-3252-40fc-a65b-2eef1ad45fcd/signatures
2. Open Signed CCLAs tab
3. Search Organization "Skylight IPV"
4. Click on View All Approved Contributors

Actual :
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/3569318e-0ed4-4196-b25e-54b69d86f85c)
Expected :
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/b9cd94e1-aa4a-4a16-8187-807646e3f1b7)

**Comment by nickmango** [comment]
@thakurveerendras Kindly verify

**Comment by thakurveerendras** [comment]
User details is added on above organization, So making issue status QA-Done
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/18a611ca-7485-4bcc-a110-66f9b19b3e11)
