### ISSUE TITLE
FINOS : up-to 43 user entry is missing under APPROVED CONTRIBUTORS list for "JP Morgan Chase" organization at FINOS project

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3076]
Steps :

1. Navigate to Signature tab : https://projectadmin.lfx.linuxfoundation.org/project/a092M00001JwBlEQAV/tools/easycla/overview/5564f18f-3252-40fc-a65b-2eef1ad45fcd/signatures
2. Open Signed CCLAs tab
3. Search Organization "JP Morgan Chase"
4. Click on View All Approved Contributors

Actual Results :  Below user data is missing 

1. Abdullah Garcia
2. Andrew Stein
3. Brody Wacker
4. Edward Dushak
5. Elena Sparks
6. Emy Calder
7. Gavin Lauchlan
8. Ian Miller
9. Ilya Slavin
10. Jack Higgs
11. James Winnifrith
12. Jarrod Spillers
13. Jasmine Feng
14. Jason Foster-Bey
15. Jason Nelson
16. Jim Adams
17. Jon Dey
18. Jonathan Eiten
19. Jonathan Meadows
20. Jonathan Teper
21. Joshua Hawkins
22. Jun Tan
23. Karthik Kondappan
24. Lawrence Drake
25. Luke Sheard
26. Malcolm Chedzoy
27. Martina Sturdikova
28. Matthew Judy
29. Max Klein
30. Michael Slade
31. Minh Nguyen
32. Minh Nguyen
33. Misha Tselman
34. Mudit Gupta
35. Nick Suttle
36. Nigel Phelan
37. Nilesh R. Bhattad
38. Rhyddian Olds
39. Ron Orsi
40. Seb Insua
41. Sebastian Moser
42. Sergei Lewis
43. Sergio Garcia

**Comment by nickmango** [comment]
@thakurveerendras Kindly verify

**Comment by thakurveerendras** [comment]
Only "**jondey**" user information is missing for  "JP Morgan Chase" organization 
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/f02b1eca-47cc-4680-a27d-3fffe328b97c)

**Comment by nickmango** [comment]
@thakurveerendras Kindly verify "jondey" user

**Comment by thakurveerendras** [comment]
Issue is still reproducible as reported. @nickmango , Please check

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/106b5f3a-8e50-4e6b-acc9-421fe8d4722e)

**Comment by thakurveerendras** [comment]
Below user details missing

1. Name : Jon Dey | GitHub : jondey
2. Name : Malcolm Chedzoy | GitHub : chedzoir

Unknown user found 

1. Name : Max Hoefl | GitHub :peterschrammel

Duplicate entry found :

1. Wenxin Wu
2. William Stamatakis

**Comment by nickmango** [comment]
@thakurveerendras Kindly verify

**Comment by thakurveerendras** [comment]
Now mentioned user details is added but **Name** field is missed to add

1. Name : Jon Dey | GitHub : jondey
2. Name : Malcolm Chedzoy | GitHub : chedzoir
3. chedzoir

Duplicate user details is still found

- Max Hoefl
- Minh Nguyen (Seems correct as Name field is same but having different email & GitHub Address)

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/3efd2aee-31d1-44f9-9989-707ce781860c)

**Comment by nickmango** [comment]
@thakurveerendras 
Users Jon Dey and Malcom have names . 
I did not add Max Hoefl user record as its not associated with JPMorgan
For user Minh Nguyen. He had 2 separate records(meaning 2 users)  in the existing sheet

**Comment by thakurveerendras** [comment]
Now duplicate record are removed for user **Max Hoefl**, So making issue status QA-Done
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/6d59c338-ff8c-4322-998d-a835bc9e8750)
