### ISSUE TITLE
FINOS : "Johnathon Lam & Christopher Taormina" user entry is missing under APPROVED CONTRIBUTORS list for "OpenFin" organization at FINOS project

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3077]
Steps :

1. Navigate to Signature tab : https://projectadmin.lfx.linuxfoundation.org/project/a092M00001JwBlEQAV/tools/easycla/overview/5564f18f-3252-40fc-a65b-2eef1ad45fcd/signatures
2. Open Signed CCLAs tab
3. Search Organization "OpenFin"
4. Click on View All Approved Contributors

Actual : "Johnathon Lam & Christopher Taormina" user entry is missing

**Comment by nickmango** [comment]
@thakurveerendras This also uses domain approval list under openfin.co

**Comment by thakurveerendras** [comment]
@nickmango, Making issue status QA-Done by considering above issue added through domain approval criteria 

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/8026de57-9498-4f5b-8596-c5ecf9798da9)

**Comment by thakurveerendras** [comment]
Now both the user added with wrong GitHub ID ,So reopening this issue Refer below screenshot for more details .

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/6b57e38a-6b9d-4b58-bd1d-0c791abc487b)

**Comment by thakurveerendras** [comment]
Wrong GitHub id (plexus-user) appears for user Johnathon Lam & Christopher Taormina

**Comment by nickmango** [comment]
@thakurveerendras Kindly verify.. Rechecked the records in the db and they are okay.

**Comment by thakurveerendras** [comment]
Found blank row at top & still GitHub id (plexus-user) appears for user Johnathon Lam & Christopher Taormina

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/7f1403af-9070-4443-bcfe-56efd14ff243)

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/9b1e8e28-998b-40eb-88a9-fcc368df07a9)

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/0aa99e4d-e5b2-48ed-b730-eb879efd3810)

**Comment by thakurveerendras** [comment]
Checked reported user details added & As per instruction ignoring extra records like plexus-user, Making issue status QA-Done
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/043e8eb7-b213-41ad-9394-78bc23e189c1)

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/16a05510-ecca-4a84-84e5-5ccc7ba8231b)

**Comment by thakurveerendras** [comment]
Blank row still appears 
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/cf8bf1e0-6411-4ab0-985e-76b8935e3a77)
**plexus-user** GitHub irrelevant id also appears
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/b087b8ee-b0ec-4bc8-a67b-c3c5957bc703)

**Comment by nickmango** [comment]
@thakurveerendras . Kindly review

**Comment by thakurveerendras** [comment]
All the reported case above are fixed, So making issue status QA-Done 
- Blank row at top are also removed 
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/564e5421-04bc-4273-b659-678a45e80b22)
- Johnathon Lam
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/1406be54-bf0d-4490-90f3-60950d98cec2)

- Christopher Taormina
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/c101fa34-de51-4077-858c-f22177f26f3f)
