### ISSUE TITLE
FINOS : Multiple user entry is missing under APPROVED CONTRIBUTORS list for "Scott Logic" organization at FINOS project

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3078]
Steps :

1. Navigate to Signature tab : https://projectadmin.lfx.linuxfoundation.org/project/a092M00001JwBlEQAV/tools/easycla/overview/5564f18f-3252-40fc-a65b-2eef1ad45fcd/signatures
2. Open Signed CCLAs tab
3. Search Organization "Scott Logic"
4. Click on View All Approved Contributors

Actual Results : Below user data is missing

1. Alex Birch
2. Andy Smith
3. Henry Chapman
4. Herb Williams
5. Neil Miles
6. Richard Strange

**Comment by nickmango** [comment]
@thakurveerendras  Scott Logic uses domain approval lists of scottlogic.com and scottlogic.co.uk

**Comment by nickmango** [comment]
Kindly re-verify @thakurveerendras

**Comment by thakurveerendras** [comment]
Irrelevant & multiple entry appears for below user

- Name : Andrey Kozlov | GitHub :peterschrammel

**Comment by nickmango** [comment]
@thakurveerendras could verify users listed on the FINOS sheet related to "Scott Logic" Updated some missing records

**Comment by thakurveerendras** [comment]
Name field is missing & multiple entry appears for "Andrey Kozlov"

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/d8d3c4c2-21c0-4738-bd81-9972808b4dea)

**Comment by thakurveerendras** [comment]
Irrelevant & multiple entry for user "Andrey Kozlov" are removed 

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/9f33217b-4035-42ab-96f6-a10e020a44a9)
