### ISSUE TITLE
FINOS : Multiple user entry is missing under APPROVED CONTRIBUTORS list for "Symphony LLC" organization at FINOS project

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3079]
Steps :

1. - Navigate to Signature tab : https://projectadmin.lfx.linuxfoundation.org/project/a092M00001JwBlEQAV/tools/easycla/overview/5564f18f-3252-40fc-a65b-2eef1ad45fcd/signatures
2. - Open Signed CCLAs tab
3. - Search Organization "Symphony LLC"
4. - Click on View All Approved Contributors

Actual Results : Below user data is missing

1. Antoine Clerget
2. Brock Durham
3. JIRA - Symphony LLC
4. Juan Pablo Acosta Arreaza
5. Laurențiu Florin Moisă
6. Roland ??
7. Russel Stringer

**Comment by nickmango** [comment]
@thakurveerendras This company uses domain name as approval list `symphony.com` with no email approval criteria . 
cc @vinod-kadam @dealako

**Comment by nickmango** [comment]
Kindly re-verify on approval section
![Screenshot 2021-07-31 at 00 24 12](https://user-images.githubusercontent.com/81645226/127712936-055701fe-bed7-4002-bc35-8f70d54db7da.png)

**Comment by thakurveerendras** [comment]
plexus-user appears as GitHub Username on "Symphony LLC" organization
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/167183db-d075-425e-bbf0-f310f58cf7bf)

**Comment by thakurveerendras** [comment]
Below user entry is missing 

1. Juan Pablo 
2. Acosta Arreaza
3. Laurențiu Florin Moisă
4. Roland ??
5. Russel Stringer 

Not listed under finos sheet user appears 

- Name : Andrey Kozlov | GitHub :peterschrammel

**Comment by nickmango** [comment]
Kindly verify the missing users

**Comment by nickmango** [comment]
Kindly verify the missing users

**Comment by thakurveerendras** [comment]
1. User name field is missing all user which are recently added
2. Multiple Entry appears for user "Andrey Kozlov"

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/fca1cc79-ae70-4d2b-ba53-d994eabc95bb)

**Comment by thakurveerendras** [comment]
Name field are added but duplicate entry is still persist 
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/a8c45f10-aefa-41b9-9b25-1884a59e650e)
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/a7b4779f-0da6-45f6-8200-c188a0bc21c9)

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/e292fa7c-5167-426f-b9ec-70be6e86e928)

**Comment by thakurveerendras** [comment]
Duplicate records are removed & now only single records available for user Andrey Kozlov, So making issue status QA-Done

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/36e2ad3b-d574-4b5a-b36b-a0d1e912bf3d)
