### ISSUE TITLE
Alternate PR Comment when commit has `id: None`

### ISSUE THREAD

**Issue by jpalmerLinuxFoundation** [communitybridge/easycla#308]
**Summary**
Inform the GitHub Commiter when their commits are not attached to their GitHub User Profile

**Background**
Given a PR CLA Check failure
When  id: None appears in the commit
Then post an alternate CLA Not Signed Comment to the PR in question

**User Story**
As a GitHub Contributor, I want to know how to resolve a CLA check failure on my own if possible, so that I can quickly perform my commits. (See user story section for details)

- [x] Use [New Comment Badge](https://cla-project-logo-prod.s3.amazonaws.com/cla-missing-id.png) "Missing ID on Commit"
- [x] Use verbiage on comment: "The commit ([SHA]) is missing the user's ID, preventing the EasyCLA check. [Consult GitHub Help](https://help.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user) to resolve."
- [x] Display comment and badge only when a commit is missing user's ID

**Acceptance Criteria**
The "done" criteria when this feature or problem is resolved.  Such as:
1. Unit Tests added and running in CI
2. Functional Tests updated to cover feature, if applicable
2. Demonstrate the set of capabilities to the product team while the code is
   running in the STAGING environment.

**References**
This pull previously did not have a username populated in the commit: https://github.com/AcademySoftwareFoundation/OpenCue/pull/502
https://jira.linuxfoundation.org/browse/SUPPORT-662
https://cla-project-logo-prod.s3.amazonaws.com/cla-missing-id.png

**Comment by WillsonHG** [comment]
This is still a reoccurring point of confusion for contributors.

**Comment by dealako** [comment]
@wanyaland this is in the python side - this maybe an issue with the GH User's info not being found. we've tried to resolve this before by looking up the GH user's id and email (fail-over).  Here's the process:

**Comment by pranab-bajpai** [comment]
Following message can be displayed:

Information for the following users could not be matched against signature table. This is preventing the EasyCLA check and corresponding commit requests.

GH email |  GH id | GH Username
<email>  | <id >  | <username>

If you believe you have configured EasyCLA, and you are still facing problems please go to: https://support.linuxfoundation.org and file a ticket

**Comment by dealako** [comment]
@wanyaland Reopening to add additional detail on the GH status message/comment that is shown to the user. Need to add the link to the GitHub article which instructs the user on how to set their userid/username etc. See @WillsonHG for details.

**Comment by WillsonHG** [comment]
Amending Pranab's comment:
Display the "[Missing ID on commit](https://cla-project-logo-prod.s3.amazonaws.com/cla-missing-id.png)" badge. 

along with the following message:

Information for the following users could not be found. 
GH email | GH id | GH Username

This is preventing the EasyCLA check and corresponding commit requests. Please refer to [GitHub documentation](https://help.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user) for instructions to link your commit to your GitHub user.

If you are still facing problems, please go to: https://support.linuxfoundation.org and file a ticket

**Comment by dealako** [comment]
Looks like the PR comment is correct and the logic check is in place for missing ID. Closing issue.
