### ISSUE TITLE
FINOS : "Name" field for user entry is missing under APPROVED CONTRIBUTORS list for all organization at FINOS project

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3082]
Steps :

Navigate to Signature tab : https://projectadmin.lfx.linuxfoundation.org/project/a092M00001JwBlEQAV/tools/easycla/overview/5564f18f-3252-40fc-a65b-2eef1ad45fcd/signatures
Open Signed CCLAs tab
Search Organization "REGNOSYS"
Click on View All Approved Contributors

Actual Results : "Name" field for user entry is missing
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/53fb1bfa-40be-427d-bb3e-ec071c1d4a85)

Expected : 
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/33bb8957-71f7-47c2-9578-1f74752a2c87)

**Comment by nickmango** [comment]
@thakurveerendras Kindly verify

**Comment by thakurveerendras** [comment]
Issue is tested with multiple organization & found that Name field is still missing as reported 

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/f9196e5d-60b0-4600-b80d-6255849cd132)

**Comment by thakurveerendras** [comment]
Still user name details is missing for below organization

1. Symphony Communication Services LLC
2. Scott Logic Ltd
3. OpenFin

**Comment by thakurveerendras** [comment]
Still Name field is missing for multiple user
1. Symphony Communication Services LLC
2. Scott Logic Ltd
3. OpenFin

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/9a95d7b9-5798-4cfc-b25f-19723ce3eba2)

**Comment by nickmango** [comment]
@thakurveerendras verified for the above names except strangerich and AndySmith as those are not given in the excel sheet

**Comment by thakurveerendras** [comment]
- Scott Logic Ltd
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/82d35654-97f8-4fce-b507-7689fad9e713)

- OpenFin
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/2f99a7f2-e3f6-497a-a6c6-5c223540c0f5)

**Comment by nickmango** [comment]
@thakurveerendras . Kindly review. 
Updated Name for Chapman and Williams for Scott Logic
And as stated earlier for stangerich and AndySmith those are outside the FINOS migration data
Cleaned empty record for Open FIn

**Comment by thakurveerendras** [comment]
Open FIn
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/c09eec3e-0a98-4de7-803e-4fa9ef4146cf)
