### ISSUE TITLE
FINOS : multiple user entry is missing under APPROVED CONTRIBUTORS list for "Goldman Sachs & Co. LLC" organization at FINOS project

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3111]
Steps :

1. Navigate to Signature tab : https://projectadmin.lfx.linuxfoundation.org/project/a092M00001JwBlEQAV/tools/easycla/overview/5564f18f-3252-40fc-a65b-2eef1ad45fcd/signatures
2. Open Signed CCLAs tab
3. Search Organization "Goldman Sachs & Co. LLC"
4. Click on View All Approved Contributors

Actual Results : Below user data is missing
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/f8a6fe91-fb33-47f0-acc4-7c379846f40a)

**Comment by nickmango** [comment]
Kindly verify
