### ISSUE TITLE
FINOS : "Andrey Kozlov" user appears with "peterschrammel" GitHub id at multiple organization on Finos project 

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3112]
Steps :

1. Navigate to Signature tab : https://projectadmin.lfx.linuxfoundation.org/project/a092M00001JwBlEQAV/tools/easycla/overview/5564f18f-3252-40fc-a65b-2eef1ad45fcd/signatures
2. Open Signed CCLAs tab
3. Search & open Organization listed below
4. Click on View All Approved Contributors

**Here is organization details** 
1. Daitan Group
2. Determined.ai Inc
3. Deutsche Bank AG
4. Diffblue Ltd
5. AquaQ Analytics Limited
6. Cloud9 Technologies LLC
7. JPMorgan Chase
8. Scott Logic Ltd
9. Symphony Communication Services LLC
10. UBS AG

**Comment by nickmango** [comment]
@thakurveerendras 
This user detail was not added by the script . The existing records on the sheet should at least exist for each company as listed. And this can be considered as external ecla . Checking the records didnt reveal any data for the eclas for the above companies

**Comment by thakurveerendras** [comment]
Making QA-Done by referring above comments
