### ISSUE TITLE
FINOS : "Antone" user missing under "AquaQ Analytics Limited" organization on Finos project

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3113]
Steps :

1. Navigate to Signature tab : https://projectadmin.lfx.linuxfoundation.org/project/a092M00001JwBlEQAV/tools/easycla/overview/5564f18f-3252-40fc-a65b-2eef1ad45fcd/signatures
2. Open Signed CCLAs tab
3. Search Organization "AquaQ Analytics Limited"
4. Click on View All Approved Contributors

Actual Results : "Antone" user missing

**Comment by nickmango** [comment]
Kindly verify

**Comment by thakurveerendras** [comment]
Missing user is added

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/a6d0dc91-1a00-41e8-bc35-dfd83728fe3b)
