### ISSUE TITLE
FINOS : "Zeno Lee" user detail missing under "Cloud9 Technologies LLC" organization on Finos project

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3114]
Steps :

1. Navigate to Signature tab : https://projectadmin.lfx.linuxfoundation.org/project/a092M00001JwBlEQAV/tools/easycla/overview/5564f18f-3252-40fc-a65b-2eef1ad45fcd/signatures
2. Open Signed CCLAs tab
3. Search Organization "Cloud9 Technologies LLC"
4. Click on View All Approved Contributors

Actual Results : "Zeno Lee" user detail is missing

**Comment by nickmango** [comment]
Kindly verify

**Comment by thakurveerendras** [comment]
Missing User is added, So making issue status QA-Done
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/657408df-4847-4271-b56c-d227eadde592)
