### ISSUE TITLE
FINOS : "Lucas Costa" user detail missing under "Daitan Group" organization on Finos project

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3115]
Steps :

1. Navigate to Signature tab : https://projectadmin.lfx.linuxfoundation.org/project/a092M00001JwBlEQAV/tools/easycla/overview/5564f18f-3252-40fc-a65b-2eef1ad45fcd/signatures
2. Open Signed CCLAs tab
3. Search Organization "Daitan Group"
4. Click on View All Approved Contributors

Actual Results : "Lucas Costa" user detail is missing

**Comment by nickmango** [comment]
Kindly verify

**Comment by thakurveerendras** [comment]
plexus-user github id appears for "Lucas Costa" user
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/9c0fea2c-da38-450d-be2c-a4ba7676b9b7)

**Comment by thakurveerendras** [comment]
Still plexus-user github id appears for "Lucas Costa" user
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/0fa7bc86-13f9-4861-a039-70aae81fa280)

**Comment by nickmango** [comment]
@thakurveerendras . Kindly verify

**Comment by thakurveerendras** [comment]
plexus-user github id record for "Lucas Costa" user are removed , So making issue status QA-Done
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/0c8300d9-30ab-4ad4-8fc5-5ecaa2333fe9)
