### ISSUE TITLE
FINOS : "Ryan Beethe" user detail missing under "Determined.ai Inc" organization on Finos project

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3116]
Steps :

1. Navigate to Signature tab : https://projectadmin.lfx.linuxfoundation.org/project/a092M00001JwBlEQAV/tools/easycla/overview/5564f18f-3252-40fc-a65b-2eef1ad45fcd/signatures
2. Open Signed CCLAs tab
3. Search Organization "Determined.ai Inc"
4. Click on View All Approved Contributors

Actual Results : "Ryan Beethe" user detail is missing

**Comment by nickmango** [comment]
Kindly verify

**Comment by thakurveerendras** [comment]
Now missing user details is added, So making issue status QA-Done
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/038c8984-7f73-4a89-805d-36f3cde522f0)
