### ISSUE TITLE
FINOS : "Plexus Bot" user detail missing under "Deutsche Bank AG" organization on Finos project

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3117]
Steps :

1. Navigate to Signature tab : https://projectadmin.lfx.linuxfoundation.org/project/a092M00001JwBlEQAV/tools/easycla/overview/5564f18f-3252-40fc-a65b-2eef1ad45fcd/signatures
2. Open Signed CCLAs tab
3. Search Organization "Deutsche Bank AG"
4. Click on View All Approved Contributors

Actual Results : "Plexus Bot" user detail is missing

**Comment by nickmango** [comment]
Kindly verify

**Comment by thakurveerendras** [comment]
User details added , So making issue status QA-Done
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/65f335da-4e9a-4a32-ad0a-6b4d72b03569)
