### ISSUE TITLE
FINOS : "Leslie Spiro" user detail missing under "Tick42" organization on Finos project

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3118]
Steps :

1. Navigate to Signature tab : https://projectadmin.lfx.linuxfoundation.org/project/a092M00001JwBlEQAV/tools/easycla/overview/5564f18f-3252-40fc-a65b-2eef1ad45fcd/signatures
2. Open Signed CCLAs tab
3. Search Organization "Tick42"
4. Click on View All Approved Contributors

Actual Results : "Leslie Spiro" user detail is missing

**Comment by nickmango** [comment]
Kindly verify

**Comment by thakurveerendras** [comment]
@nickmango, Tick42 organization is missing under Finos project

**Comment by thakurveerendras** [comment]
Organization is added & missing user is also added, So making issue status QA-Done

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/24e2a77f-20b2-4fcf-86ac-3aa80abd06ae)

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/cece0bd6-a879-4cca-821e-a64e9765779d)
