### ISSUE TITLE
Add GitLab Repository Endpoints

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#3122]
# Summary

Add GitLab Repository Endpoints

# Description

In order to support GitLab onboarding, we need to add GitLab repository CRUD operations via the API. This task is to create the API endpoints, handlers, service layer and database logic for creating, reading, updating, and deleting repositories to/from a project.

# Acceptance Criteria

Demonstrate GitLab repository CRUD operations to the team.

# References

- This task is similar to the GitHub repository API.

**Comment by thakurveerendras** [comment]
Story is tested on Dev site & found that below GitLab repository API work as expected & also cross verify functionality at GUI site

- ### Get the GitLab repositories of the project : 
**API Endpoint** :  
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/project/:projectSFID/gitlab/repositories
**API Reponses status** : 200 OK
**Response Body** :
```
{
    "list": [
        {
            "date_created": "2021-09-13T07:34:49Z",
            "date_modified": "2021-09-13T07:35:00Z",
            "enabled": true,
            "note": "created on 2021-09-13T07:34:49Z.  Updated enabled flag to true on 2021-09-13T07:35:00Z by user: vthakur.",
            "repositoryID": "fbd5f170-63d9-40fc-a4c4-9b8e8fe5d145",
            "repository_cla_group_id": "a5e2552b-ee76-4157-a414-9f0264122942",
            "repository_external_id": 29564857,
            "repository_full_path": "gitlabeclaiclagroup/testproject01",
            "repository_name": "gitlabeclaiclagroup/testproject01",
            "repository_organization_name": "GitLabEclaIclaGroup",
            "repository_project_sfid": "a092h000003hprCAAQ",
            "repository_type": "gitlab",
            "repository_url": "https://gitlab.com/gitlabeclaiclagroup/testproject01",
            "version": "v1"
        }
    ]
}
```

- ### Enrolls GitLab repositories for the CLA Group
**API Endpoint** :  
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/project/:projectSFID/gitlab/repositories
**API Reponses status** : 200 OK
**Response Body** :
```
{
    "list": [
        {
            "date_created": "2021-09-13T07:34:49Z",
            "date_modified": "2021-09-13T09:10:57Z",
            "enabled": true,
            "note": "created on 2021-09-13T07:34:49Z.  Updated enabled flag to true on 2021-09-13T07:35:00Z by user: vthakur.  Updated enabled flag to false on 2021-09-13T09:09:34Z by user: vthakur.  Updated enabled flag to true on 2021-09-13T09:10:57Z by user: vthakur.",
            "repositoryID": "fbd5f170-63d9-40fc-a4c4-9b8e8fe5d145",
            "repository_cla_group_id": "a5e2552b-ee76-4157-a414-9f0264122942",
            "repository_external_id": 29564857,
            "repository_full_path": "gitlabeclaiclagroup/testproject01",
            "repository_name": "gitlabeclaiclagroup/testproject01",
            "repository_organization_name": "GitLabEclaIclaGroup",
            "repository_project_sfid": "a092h000003hprCAAQ",
            "repository_type": "gitlab",
            "repository_url": "https://gitlab.com/gitlabeclaiclagroup/testproject01",
            "version": "v1"
        }
    ]
}
```
- ### Unenrolls GitLab repositories for the CLA Group
**API Endpoint** :  
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/project/:projectSFID/gitlab/repositories
**API Reponses status** : 200 OK
**Response Body** :
```
{
    "list": [
        {
            "date_created": "2021-09-13T07:34:49Z",
            "date_modified": "2021-09-13T09:09:34Z",
            "enabled": false,
            "note": "created on 2021-09-13T07:34:49Z.  Updated enabled flag to true on 2021-09-13T07:35:00Z by user: vthakur.  Updated enabled flag to false on 2021-09-13T09:09:34Z by user: vthakur.",
            "repositoryID": "fbd5f170-63d9-40fc-a4c4-9b8e8fe5d145",
            "repository_cla_group_id": "a5e2552b-ee76-4157-a414-9f0264122942",
            "repository_external_id": 29564857,
            "repository_full_path": "gitlabeclaiclagroup/testproject01",
            "repository_name": "gitlabeclaiclagroup/testproject01",
            "repository_organization_name": "GitLabEclaIclaGroup",
            "repository_project_sfid": "a092h000003hprCAAQ",
            "repository_type": "gitlab",
            "repository_url": "https://gitlab.com/gitlabeclaiclagroup/testproject01",
            "version": "v1"
        }
    ]
}
```
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/343ec984-bb2f-486a-a5ad-ca005fdf621f)
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/fb06447e-4967-4521-8d0c-1e17384eeae7)
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/6b3d7603-bec4-4904-b1ef-14dde0f503d4)
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/55a61a66-533a-4e27-a1e2-2793d06f2a9d)

**Comment by dealako** [comment]
these are good @thakurveerendras

**Comment by dealako** [comment]
Resolved
