### ISSUE TITLE
Failed to sign corporate CLA due to configuration of cors settings in api service

### ISSUE THREAD

**Issue by MartinForReal** [communitybridge/easycla#314]
**Summary**

Failed to open the CLA process for the corporation due to the configuration of cors settings
**Background**

Provide context to the issue - provide steps to reproduce the behavior, such as:
1. Go to 'https://corporate.lfcla.com/#/company/xxxxxx
2. Click on 'new CLA'
3. Click on 'Cloud foundry foundation'
4. Click on 'Yes'
5. See an error in the console

Failed to load resource: the server responded with a status of 502 ()
Access to XMLHttpRequest at 'https://api.lfcla.com/v1/request-corporate-signature' from origin 'https://corporate.lfcla.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
https://corporate.lfcla.com/#/company/xxxxxxx
vendor.js:1 ERROR e
(anonymous) @ vendor.js:1

**Expected behavior**

No error should occur

**Screenshots**

<img width="1274" alt="截屏2019-11-0511 37 24" src="https://user-images.githubusercontent.com/5207478/68176649-a7786600-ffc0-11e9-9532-e715faa23d2c.png">

**Environment**

Please complete the following information:
 - Environment: PROD 
 - OS: Macos
 - Browser chrome
 - Version 78.0.3904.87

**Acceptance Criteria**
I can sign the CLA as corporation manager

**Comment by dealako** [comment]
Needs investigation as most CORS errors are not actual CORS errors but related to session timeout or backend server-side errors.

**Comment by MartinForReal** [comment]
<img width="537" alt="截屏2020-04-15 01 22 34" src="https://user-images.githubusercontent.com/5207478/79254687-ade80380-7eb7-11ea-9cfe-be99bfda7ac3.png">

**Comment by MartinForReal** [comment]
header:

```
POST /v1/request-corporate-signature
Accept: application/json
Content-Type: application/json
Origin: https://corporate.lfcla.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15
```

body:
```
{
  "project_id": "face2577-329e-448c-a316-b923fbfb1800",
  "company_id": "ab31b9cb-b625-4f99-ad12-3aa1f6a09ae8",
  "send_as_email": true,
  "authority_name": "Sun Man",
  "authority_email": "sunman@cmbc.com.cn"
}
```
result: 

```
< HTTP/2 502
< content-type: application/json
< content-length: 36
< date: Wed, 15 Apr 2020 10:23:58 GMT
< x-amzn-requestid: 7f51613f-8e86-4c25-8803-31b42daf4a49
< x-amzn-errortype: InternalServerErrorException
< x-amz-apigw-id: LBgNqG2vIAMF1Ow=
< x-amzn-trace-id: Root=1-5e96e0bd-a4d8f0ba5105349e8d19a29c
< x-cache: Error from cloudfront
< via: 1.1 d94d6fed5c5370730dedb521e73dd40a.cloudfront.net (CloudFront)
< x-amz-cf-pop: NRT12-C3
< x-amz-cf-id: IPoB8y4nRs1LxBuZ9sVsUPyiBes9Ovxs8sjsS85uthlSl51MHJNwBA==
<
* Connection #0 to host api.lfcla.com left intact
{"message": "Internal server error"}* Closing connection 0
```

@dealako Could you please help us initiate a request to manually sign the CLA? Thanks!
