### ISSUE TITLE
PCC - Approved Contributors empty.

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#3171]
In the Project control center, when selecting "Approved Contributors", the UI shows "No CLA data available" even when there are contributors who have verified under the company's CCLA.

![image](https://user-images.githubusercontent.com/46732999/130114111-d40de0b7-d938-48e9-b51d-95aef62094e6.png)

**Comment by dealako** [comment]
I believe this was for Tungsten Fabric: https://projectadmin.lfx.linuxfoundation.org/project/a092M00001F1Yv4QAF/tools/easycla/overview/57854295-e49d-4a28-a0ff-2d6d3163378c/signatures

/cla-group/{claGroupID}/corporate-contributors for CLA Group ID: 57854295-e49d-4a28-a0ff-2d6d3163378c

**Comment by dealako** [comment]
Issue is related to old records where the `sigtype_signed_approved_id` column is not set.

**Comment by dealako** [comment]
Resolved by writing a migration script for PROD signatures table that has a missing `sigtype_signed_approved_id` column value.  No code changes are required.

Ready for re-test @WillsonHG

**Comment by WillsonHG** [comment]
Looks to be correct now.
