### ISSUE TITLE
PCC - View Criteria failing in some cases.

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#3242]
As a program manager, I want to view the "Approval Criteria" for a certain organization's CLA. I click the button and nothing happens. In the console, the following error is reported:

![image](https://user-images.githubusercontent.com/46732999/131920382-b4821c9f-0189-437d-9cc2-4eed44df2bb5.png)

This happens in the project 'Tungsten Fabric' with all companies except Mirantis and Telstra 
https://projectadmin.lfx.linuxfoundation.org/project/a092M00001F1Yv4QAF/tools/easycla/overview/57854295-e49d-4a28-a0ff-2d6d3163378c/signatures

**Comment by dealako** [comment]
Let's have someone from the PCC team review this issue.

@asithade

**Comment by asithade** [comment]
Yeah we can take a look at this. @thakurveerendras can you file a ticket for this please?

**Comment by WillsonHG** [comment]
verified this was resolved
