### ISSUE TITLE
Invalidate ICLA does not remove user from ldap group for Gerrit projects

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#3263]
When a program manager invalidates an ICLA in the PCC for a Gerrit project, the user is not removed from the LDAP group and therefore will not be asked to resign/verify.

**Comment by mlehotskylf** [comment]
@nickmango @WillsonHG is this still an issue?

**Comment by nickmango** [comment]
This was resolved with another ticket earlier this year. @jarias-lfx verified with both icla and ccla flows

**Comment by mlehotskylf** [comment]
This LDAP addition/invalidate logic was updated and tested with previous Gerrit LDAP issue https://github.com/communitybridge/easycla/issues/3946. Discussed this with @jarias-lfx and there are no more tickets reported in this area and he agreed to close this and open new tickets in case issue reoccurs.
CC: @WillsonHG
