### ISSUE TITLE
Project Console: Easily find who has signed for a company.

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#327]
**Summary**

In the project console, a project manager should be able to easily find signatures for a particular company.

**Background**

1. The project manager logs into https://project.lfcla.com and selects the project.
2. In the CLA Groups section, the project manager selects "View Signatures"
3. The project manager must scroll through an unknown number of signatures, only being able to sort by columns on the current page and only able to search via the browser on the current page. 

**User Story**

A description from a user's perspective - e.g.:
As a project manager, 
I want to be able to search for an employee or company throughout all pages of signatures, navigate through pagination, and/or sort by type and company for ALL signatures,
so that I can find company and employee authorized signatures quickly.

**Acceptance Criteria**

The "done" criteria when this feature or problem is resolved.  Such as:
1. Unit Tests added and running in CI
2. Functional Tests updated to cover feature, if applicable
2. Demonstrate the set of capabilities to the product team while the code is
   running in the STAGING environment.

**References**
(Optional) Provide any code or specification references that would be helpful
for the developer implementing this feature.
https://confluence.linuxfoundation.org/display/PROD/EasyCLA+ERs

**Comment by nirupamav** [comment]
**_Test Cases Link_** https://confluence.linuxfoundation.org/display/PROD/View+Signatures

@pranab-bajpai Could you please clarify the below queries
**_Queries_**
1. In which order data is displayed initially when View Signatures popup window is opened
2. How many rows are displayed per page

**_Bugs Logged_**
#733, #734, #735, #737

**Comment by nirupamav** [comment]
Issues logged #757 , #758
Tested all scenarios and logged the bugs for the failed cases. Closing the ticket
