### ISSUE TITLE
Request Authorization to Contribute appears for GitLab Group URL which is added under approval list on employee acknowledgement flow

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3271]
- Preconditions : CLA group on which Require corporate contributors to sign Individual CLAs options is not selected

Steps :

1. Go to corporate console & add GitLab Group URL to approval list
2. Create MR form approval list GitLab Group 
3. See-MR is gated
4. Click on Not Covered
5. Click on Proceed as a Corporate Contributor options
6. Select Microsoft Corporation organization
7. Click on Procced button

Actual Results : Request Authorization to Contribute appears for GitLab Group URL
https://images.zenhubusercontent.com/194341141/bb4f6621-8223-4dd9-8f45-a3d668f3af23/empack_failed.mp4

**Comment by thakurveerendras** [comment]
Hi @nickmango 
Issue is retested with fresh setup & found following behavior 

1. Nothing happen when click on Procced button at first time
2. Procced work on second attempt but commit is not authorized 

https://images.zenhubusercontent.com/194341141/12e2337f-fe0a-4f78-ae06-2eeacc0f53d8/_3271.mp4

**Comment by thakurveerendras** [comment]
Hi @nickmango 
Commit is not authorized(Not Covered button not updated to Covered) , Issue is still reproducble
https://images.zenhubusercontent.com/194341141/edefae3e-c576-4642-b028-804ffb51acde/_3271__1_.mp4

**Comment by thakurveerendras** [comment]
Hi @nickmango 
Merge Request is not updated on GitLab Group URL case, Refer video clip 
https://images.zenhubusercontent.com/194341141/336aca32-5cf6-4c57-a92a-1289cfe84014/3271_14sep.mp4

**Comment by vinod-kadam** [comment]
As updated by @nickmango , the fix is deployed to Dev. @thakurveerendras please verify.

**Comment by nickmango** [comment]
@thakurveerendras ticket is ready for verification

**Comment by thakurveerendras** [comment]
@nickmango , Employee Acknowledgement which doesn't required ICLA flow (ECLA) through GitLab Group URL working fine & now Merge request is properly updated to Covered after complete flow

Refer Video clip :
https://images.zenhubusercontent.com/194341141/5fc2124f-bd87-403a-8021-a55afe59e1ca/_3271__2_.mp4
