### ISSUE TITLE
Remove v1/v2 Options From Landing Page

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#3276]
## Summary

Remove v1/v2 Options From Landing Page

## Background

The product owner decided we can now remove the v1 product console and v1 company portal links from the landing page.
 
## Tasks

1. Remove the pop-up modal dialog which allows the user to select v1 or v2 for Project Console.  Proceed button should replace the current page with the v2 project console. 
1. Remove the pop-up modal dialog which allows the user to select v1 or v2 for Corporate Console.  Proceed button should replace the current page with the v2 corporate console.
1. Clean up and remove all unused code. 

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Only v2 landing page links are available from the landing page

## References

![Screen Shot 2021-09-13 at 2.09.59 PM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/35c80f63-92af-4ea7-9112-8a100c262a2d)

**Comment by WillsonHG** [comment]
@dealako  @amolsontakke3576  Can we get this done soon, this is causing some issues with people trying to use v1.

**Comment by amolsontakke3576** [comment]
@WillsonHG I had already raised the PR.

**Comment by dealako** [comment]
This issue is resolved. Closing ticket.
