### ISSUE TITLE
Corporate Console: tag cla managers of large companies for specific projects.

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#328]
**Summary**

As a CLA manager of a large company, I want to pick which project I manage and get notifications for.

**Background**
Company CLA managers in large companies aren't able to pick which projects they manage CLA approvals for. Think about a company like IBM, and how they participate in a ton of LF projects. Some of the participation is within the same group within IBM, but some is in completely distinct parts of the org. There should be a "default" option for one or more default CLA admins, but the company should be able to tag certain CLA admins as only being responsible for specific projects. 

**When notifications go out, it should only notify those that care about the specific request.**

**User Story**

A description from a user's perspective - e.g.:
As a cla manager,
I only want to manage and be notified about contributions to my specific project,

**Acceptance Criteria**

The "done" criteria when this feature or problem is resolved.  Such as:
1. Unit Tests added and running in CI
2. Functional Tests updated to cover feature, if applicable
2. Demonstrate the set of capabilities to the product team while the code is
   running in the STAGING environment.

**References**
(Optional) Provide any code or specification references that would be helpful
for the developer implementing this feature.
https://confluence.linuxfoundation.org/display/PROD/EasyCLA+ERs

**Comment by dealako** [comment]
Won't fix. Out of scope of current product requirements/features.
