### ISSUE TITLE
All Address 3 lines on templates need to be optional.

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#3304]
Please change the templates' address 3 line to optional. For both the Apache style and ASWF templates, the address line 3 should be document_tab_type =  text_optional

**Comment by dealako** [comment]
We have address field 3 defined in 4 places in this file: https://github.com/communitybridge/easycla/blob/main/cla-backend-go/template/repository.go#L527  Will update the type to be text_optional.

**Comment by dealako** [comment]
Created PR: https://github.com/communitybridge/easycla/pull/3305

**Comment by dealako** [comment]
@thakurveerendras this change allows DocuSign signers to skip the third address line (address line 3), if desired.

To test:
1. Create a new CLA CLA Group - choose Template (either Apache Style or ASWF template)
1. Connect one or more repositories to the CLA Group
1. Create PR and observe user is blocked
1. Execute ICLA CLA workflow for the user who does not have a CLA on file
1. Observe the user is directed to the DocuSign website to sign a CLA
1. In the DocuSign template, observe that address line 3 is not required.
1. Pass = address 3 is not required to fill out, Fail is when the user is required to fill out address line 3.

**Comment by thakurveerendras** [comment]
Hi @dealako ,
Issue is tested on Dev with CCLAs & ICLAs on **Apache Style & ASWF 2020 v2.1** templet and found that 3rd address line is optional at DocuSign template
ICLAs : 
https://images.zenhubusercontent.com/194341141/e5775b6c-f2ff-4691-8aee-25303c8c57fb/3304_icla.mp4
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/4fd5a9b6-dc58-4ba2-a7bd-05a67618ac8c)
CCLAs:
https://images.zenhubusercontent.com/194341141/f6c960f1-b886-42ec-9e8a-1fda92a03646/cclas_newproject.mp4
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/e14c1946-cf74-45eb-b480-31e00250a516)

**Comment by dealako** [comment]
Confirmed - issue reviewed and resolve. Closing ticket.
