### ISSUE TITLE
unable to fetch access token for user appears when click on Not covered button

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3320]
Steps :
1. Add GitLab group
2. Enabled CLA enforced GitLab project
3. Add new branch & create New Merge Request
See-Not covered (or Missing Id on Commit) button appears
4. Now click on Not covered button
5. Click on Authorized button

Actual results :  unable to fetch access token for user appears
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/32680a4d-4323-4605-8bb3-41475fb21583)
https://images.zenhubusercontent.com/194341141/3c98a8d7-ca6c-4d3e-9cbc-5fdbe06ee3fe/unable_to_fetch_access_token_for_user.mp4

**Comment by thakurveerendras** [comment]
Hi @vinod-kadam , @dealako 
Issue is reproducible very first time when Authorization prompt appears. Cross check this issue on different browser.
https://images.zenhubusercontent.com/194341141/b0c23867-208b-4fa0-a9dc-eb8324045d16/firfox_.mp4

**Comment by dealako** [comment]
Resolved - issue was related to creating a new user in the EasyCLA Database and the error handling. Deployed fix to DEV and STAGING. Ready for QA.

**Comment by thakurveerendras** [comment]
Issue is tested on staging site with new user & found that user properly redirected to contributor console after click on Authorized button

Refer Video clip for more details :  
https://images.zenhubusercontent.com/194341141/8d4f303e-24e1-4b74-a9e1-2a465a20d4d9/_3320.mp4
