### ISSUE TITLE
EasyCla Gated MR div info appears for GitLab Group owner while on GitHub is comes form  easyCla bot

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3337]
### Gated MR on GitLab case 
Steps :
1. Add GitLab Group by user @thakurveerendras 
2. Create MR request by another user @vrthakur

Actual Results : EasyCla Gated MR div info appears for GitLab Group owner (@thakurveerendras)
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/f6e1d0cb-bf0e-4aa6-9906-4d61ac864ee0)

### Gated MR on GitHub case
EasyCla Gated MR div info appears form easyCla bot 
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/db977eea-7578-4240-b7ff-4aec88977c35)

**Comment by makkalot** [comment]
@thakurveerendras for Gitlab we post the comments on behalf of the group owner(user who authorized easyCLA bot), for Github we do that via the bot since Github supports that. It's expected to have different behaviour for different platforms.

**Comment by dealako** [comment]
Agree with @makkalot. This works as expected. Closing ticket.
