### ISSUE TITLE
Redirecting to contributor/Authorization app progress window is not user friendly 

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3341]
Steps :

1. MR is Gated
2. Click on Not Covered button

Actual Results : Redirecting to contributor/Authorization app progress window is not user friendly 
### **GitLab** :
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/51e12fd1-e7da-4147-b353-36d240eb195d)
### **GitHub** :
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/b9168732-dd1e-4049-8b37-afacbfa3efe2)

**Comment by dealako** [comment]
this issue is related to GitHub's redirect design. We are unable to change this behavior. Closing this ticket.
