### ISSUE TITLE
GitLab MR is not authorized after successfully ICLA sign up

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3348]
Steps :

1. MR is gated
2. Click on Not Covered
3. Sign as ICLA
4. Click on Finish button at docusigned page

Actual results : GitLab MR is not authorized after successfully ICLA sign up

Refer video clip :
https://images.zenhubusercontent.com/194341141/2b1f5b90-b3f2-4162-9927-e9b5c7d7b11a/not_authorized_.mp4

**Comment by mlehotskylf** [comment]
This is ready for QA Testing, according to @thakurveerendras.

**Comment by thakurveerendras** [comment]
Tested issue on dev site & found that it is not reproducible as reported, It is properly fixed 

![image](https://github.com/communitybridge/easycla/assets/75417507/013bc226-28a0-4182-b722-1fef0d05f26e)

**Comment by thakurveerendras** [comment]
Tested on prod and found that it is working fine, So closing this ticket
Refer PR link: https://gitlab.com/feb15prod/repo01/-/merge_requests/1
![image](https://github.com/communitybridge/easycla/assets/75417507/d0dc2eac-b56b-40e9-b8f8-eedbc5506d91)
