### ISSUE TITLE
Easycla expected status on open pull request

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#3349]
A user's pull requests are not returning an easycla status. it is showing as 'expected'. All other PRs in the repository appear to be returning a status. 

https://github.com/open-telemetry/opentelemetry-collector/pull/4329

**Comment by nickmango** [comment]
Investigated this issue and noted it only happening for a single user , in this case  `shree007`. EasyCLA is using the 3rd party package (pygithub) to access user details. For some reason this happens to fail for this specific user throwing an exception when updating the PR status. Currently still troubleshooting the resolution as this happens to be a first time case 
cc @WillsonHG @dealako

**Comment by WillsonHG** [comment]
We've got another similar case https://github.com/webdriverio/webdriverio/pull/7680 Expected status, but the author isn't properly linked to the GitHub account either. I received no notifications in the logs from EasyCLA. I've asked the user to fix the commit author so that it will link, but they still should be receiving a 'missing ID on commit' message.

**Comment by facusantillo** [comment]
Hi, In order to fix it I had to change my primary mailing address with other one, and run `git commit --amend --reset-author` using a new name that matches my github account name.

**Comment by shree007** [comment]
@WillsonHG My issue has been resolved by resetting the author name and email id in commit id.
Thanks.

**Comment by dealako** [comment]
Pushing update to resolve this issue.
