### ISSUE TITLE
CLA Corporate Console - Error when signing ccla

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#3356]
organization.lfx.linuxfoundation.org When a user navigates to choose a project and then selects 'yes' to be cla manager and 'yes' to be cla signatory, when generating the document, it fails with " CLA System is not able to support your request. Please Click here to open a support ticket."

The only failed api is ""requestCorporateSignature":{"code":403,"message":"EasyCLA - 403 Forbidden - user <redacted> does not have access to Request Corporate Signature with Project|Organization scope of <redacted>","success":false,"data":null,"__typename":"RequestCorporateSignatureResult"}}}"

This issue is seen even when manually adding the cla-signatory, cla-manager, or both roles, before trying to sign the document.

**Comment by WillsonHG** [comment]
{data: {requestCorporateSignature: {code: 422,…}}}
data: {requestCorporateSignature: {code: 422,…}}
requestCorporateSignature: {code: 422,…}
code: 422
data: null
message: "authority_name in body should match '^[a-zA-Z0-9][a-zA-Z0-9 ',.;:-_&@\\#\\$\\(\\)\\+]*$'"
success: false
__typename: "RequestCorporateSignatureResult"

**Comment by dealako** [comment]
Created PR: https://github.com/communitybridge/easycla/pull/3394

**Comment by dealako** [comment]
Deployed to DEV. Included as part of the release: https://github.com/communitybridge/easycla/releases/tag/v2.0.102

**Comment by WillsonHG** [comment]
this is resolved.
