### ISSUE TITLE
Easycla unable to post status - shows as 'expected'

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#3366]
Easycla is reporting a status as passed successfully in the logs, but there is no status showing on the PRs. 

https://github.com/prestodb/presto/pull/16981
Missing id on commit message for 3 commits, 1 passed
Status posted
User updated 3 commits
Status expected
Cloud watch logs show 3 commits fixed, yet posting old status of missing id on commit
https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fcla-backend-prod-githubactivity/log-events/2021$252F11$252F12$252F$255B$2524LATEST$255D28a32c2914b44fefb8348011aa38c18a

https://github.com/grpc/grpc/pull/27975
Odd, EasyCLA logs show the PR successfully passed the check and we posted an update back to GitHub:

cla: EasyCLA App checks pass for PR: 27975 with authors: [('f5fabdbc7a7e216150a035330e352dcdd4c1e596', 'Yash Tibrewal'), ('0cfdad83b6d54add6177ed239a03abb1e9df9c67', 'Yash Tibrewal'), ('7ce03fae7dbe1cc137656b5ae4ae69d2d630bd77', 'Yash Tibrewal'), ('0c5f6f9afe6a70af6cd31dd1314e714253cc57d8', 'Yash Tibrewal'), ('abed7a0cb12f55365bbfeb000fe394c4bbf851df', 'Yash Tibrewal'), ('3b817204609c65310de98fdebdc0f7d539717aec', 'Yash Tibrewal'), ('03edbdd4c9f75fe15645b44454059f0f356b7d28', 'Yash Tibrewal'), ('00090182dd5cdcb6055d6fd5224afa9b23946363', 'Yash Tibrewal'), ('df04a85776e7d80c7017643215de1d41294156a7', 'Yash Tibrewal'), ('2a0ed4e20d2eb1a33e818869ecd786c4ab1e41f2', 'Yash Tibrewal'), ('ff0d8f884372a8541d045bc9de14cb135ee6180b', 'Yash Tibrewal')]
cla: Successfully posted status success on PR 27975: Commit f5fabdb

**Comment by WillsonHG** [comment]
probably related to the fix for Issue 3365

**Comment by jpkrohling** [comment]
OpenTelemetry repositories as are also affected, including the Collector core and contrib.

**Comment by dealako** [comment]
Pushing update to resolve this issue. See PR: https://github.com/communitybridge/easycla/pull/3368

**Comment by dealako** [comment]
Deploying to DEV, STAGING, and PROD: https://app.circleci.com/pipelines/github/communitybridge/easycla/6227/workflows/8908eab8-94e4-47d5-ae1d-6b0b75da1aa0
