### ISSUE TITLE
PCC - AWSF Unable to add new cla group 

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#3369]
At OpenTimelineIO in the PCC https://projectadmin.lfx.linuxfoundation.org/project/a092M00001If9uZQAR/tools/easycla/overview

Unable to add new cla group
![image](https://user-images.githubusercontent.com/46732999/142041504-8f6ceaa5-7598-4190-bca9-9ea4c71f3a62.png)

This is incorrect, since all cla groups are at the project level, and not the foundation level.

To troubleshoot, i have made the following observations/changes in the following tables:
Tables
GitHub-orgs = good, no changes
	organization_sfid - appears to be project sfid
	project_sfid - set to aswf, appears correct

Projects = set them all to their project_external_id
	project_external_id = changed all to their project sfid
	foundation_sfid = all correct

Projects-clan-groups = deleted awsf row
	project_sfid = correct except extra row for awsf project id (deleted)
	foundation_sfid = all set to ASWF SFID

Repositories = good, no changes
	repository_sfdc_id == foundation sfid - good
	project_sfid = good

Please investigate why we are still getting the error when trying to add a new cla group at the project level.

**Comment by dealako** [comment]
Resolved by unsetting the Enabled Services = CLA for the ASWF project.

**Comment by WillsonHG** [comment]
thanks!
