### ISSUE TITLE
Status not reporting or updating correctly on PR

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#3378]
https://github.com/open-telemetry/opentelemetry-dotnet/pull/2677

The user's EasyCLA comment status is showing 
![image](https://user-images.githubusercontent.com/46732999/143270595-393db414-e273-4a72-9937-5592860ffd28.png)

This has a mixed message that 1) the user isn't authorized but 2) the copy tells them they are missing id on commit.

The second issue is that the bot posted twice instead of editing the original comment

The third issue is that the status did not update to 'authorized' once the user authorized themselves, only the 'checks' section was updated.

**Comment by ktmitton** [comment]
I ended up resolving it by changing the email address (even on the commit), and doing a merge of recent changes from main. Not exactly sure which thing triggered the fix to work, that's just what changed between it failing and passing.

Let me know if there's anything else I can help with!

**Comment by WillsonHG** [comment]
https://github.com/prestodb/presto/pull/17055 another example @dealako  Need to check the response when a user has a missing ID on commit, the cla bot is not showing correct messaging.

**Comment by WillsonHG** [comment]
https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/4823

**Comment by WillsonHG** [comment]
https://github.com/grpc/grpc/pull/28307

**Comment by WillsonHG** [comment]
Hi @dealako  any updates for this?

**Comment by WillsonHG** [comment]
https://github.com/kubernetes-sigs/controller-runtime/pull/1750

**Comment by WillsonHG** [comment]
https://github.com/appium/appium/pull/16312

**Comment by WillsonHG** [comment]
https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/203

**Comment by dealako** [comment]
Created PR: https://github.com/communitybridge/easycla/pull/3418. Let's QA this set of changes:

- Updated filter to identify missing IDs from the commit list
- Updated logic that checks for previous missing IDs
- Added logic to stop processing GitHub PR when the repository is disabled

**Comment by thakurveerendras** [comment]
"Missing ID on Commit " PR is not authorized when user successfully signing DocuSign as ICLA  

Issue is tested on Dev site 

Refer video clip :
 https://images.zenhubusercontent.com/194341141/7be2249e-f984-4dd2-ac8d-6cadd36399ca/3378.mp4

**Comment by dealako** [comment]
This should be resolved now. Ready for QA.
