### ISSUE TITLE
Feature Request: Endpoint to query CLA status for a given commit

### ISSUE THREAD

**Issue by mrbobbytables** [communitybridge/easycla#3380]
## Summary

An endpoint that returns the EasyCLA status for a given commit, preferably with additional information to troubleshoot (e.g. email, individual/corp+who if corp CLA etc)

## Background

Multiple issues have been encountered during the Kubernetes EasyCLA migration where it is not clear what is wrong. For example a PR from a single author with multiple commits where some of the commits are throwing a bad EasyCLA status. There is no indication as to why it thinks it's wrong, which kind of CLA the person has signed or the employer associated with it.

Tracking issue here: https://github.com/kubernetes/org/issues/3068

## User Story

- As a contributor I would like to understand why EasyCLA believes I have not signed a CLA

## Acceptance Criteria

When an endpoint returns the CLA status for a given commit
When an endpoint returns the information for a given commit

## References

Kubernetes Org Migration Feedback thread: https://github.com/kubernetes/org/issues/3068

**Comment by dealako** [comment]
Example of a confusing commit status:

![Screenshot 2023-02-07 at 7 50 01 AM](https://user-images.githubusercontent.com/519609/217293957-fbfd1d2d-3ffa-4103-b72a-74bc0929dca0.png)

*Observations*
1. Each commit should be a link represented in blue.
2. Why is the first commit a short SHA value, while the others are long?

**Comment by dealako** [comment]
This is reported a long time ago. I know we did some updates on the status update logic. I wonder if this issue continues to exist.

**Comment by nickmango** [comment]
@mrbobbytables this is not reproducible currently. Kindly confirm 
cc @mlehotskylf

**Comment by mlehotskylf** [comment]
This i fixed, closing.
