### ISSUE TITLE
EasyCLA Corporate Console fails to load

### ISSUE THREAD

**Issue by djaglowski** [communitybridge/easycla#3391]
## Summary

The Corporate Console fails to load. I'm unable to manage my organization's CLA. The page hangs indefinitely.

## Background

Steps to reproduce:
1. From `https://easycla.lfx.linuxfoundation.org`, click the "Proceed" button within the Organizations card.
2. If not logged in, log in.
3. Page fails to load. Developer Console shows errors:
  - `[GraphQL error]: Message: Cannot return null for non-nullable field Organization.id., Path: myOrganization,id`
  - `Cannot get unsaved property from storage => notifications`
  - `Throttling navigation to prevent the browser from hanging. See <URL>. Command line switch --disable-ipc-flooding-protection can be used to bypass the protection`

## Expected behavior

Either load the console or show a clear error explaining what's wrong.

## Environment

macOS

* Browser:
  - [X] Chrome/Brave
  - [X] Firefox
  - [X] Safari

**Comment by dealako** [comment]
@djaglowski would you mind sharing some additional details? LF login ID and company Name?

**Comment by WillsonHG** [comment]
Hi @djaglowski  Thank you for opening this and providing these details. During troubleshooting this for you, I've made a small change to your user permissions that I think might solve this. Can you please try the steps you enumerated again? You will probably want to clear your cache and cookies/hard refresh before trying again.

**Comment by djaglowski** [comment]
Hi @WillsonHG, thank you. Whatever change you made seems to have resolved the page loading issue. 

Unfortunately, I'm not seeing one of the organizations on which I am a CLA manager (observIQ). The org I do see lists me as a CLA manager, but it does not appear that I can actually manage contributors, or anything else on the page.

**Comment by WillsonHG** [comment]
Hello @djaglowski  The Corporate CLA portal assumes that you would only be associated with one organization to manage their CLAs. In this case, you are already associated with Blue Medora and we don't have a built in self serve option to swap to observIQ. Are you hoping to manage them both at this time? 

Also, please check again for Blue Medora - when choosing the CNCF option, you should now see a white +Add Approval Criteria button and +Add CLA manager buttons in those sections to manage.

I can also manually switch your permissions to the observIQ CLA if you'd like. Going forward - if you hope to manage both without manual adjustments, you may need to create another LF account for one of them.

**Comment by djaglowski** [comment]
Thank you @WillsonHG. If you can make observIQ my primary, that would solve my immediate issue. Thank you for the help!

**Comment by WillsonHG** [comment]
@djaglowski Done! You should be able to manage the CNCF CLA for observIQ now.

**Comment by djaglowski** [comment]
Thank you @WillsonHG!
