### ISSUE TITLE
Fix Docs links on landing page and in emails.

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#3411]
https://easycla.lfx.linuxfoundation.org/#/

- [x] On the EasyCLA landing page, the link from the Developers box 'Learn More' takes you to the v1 documentation. The link in the top right menu 'Developer' also needs to be changed to v2

- [x] In all EasyCLA emails, please change the link in the docs from v1 to v2

**Comment by dealako** [comment]
Created PR: https://github.com/communitybridge/easycla/pull/3413 to update documentation links throughout the application.

**Comment by dealako** [comment]
Merged - deploying as part of this release: https://github.com/communitybridge/easycla/releases/tag/v2.0.106

**Comment by WillsonHG** [comment]
confirmed resolved in production.
