### ISSUE TITLE
EasyCla bot status is not updated correctly when user add comments with valid GitHub id while first commit done with invalid id 

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3419]
### **Setup :**

1. Add non existing email address under the system .getconfig file
2. Provide admin access at GitHub repo to test user say : thakurveerendras1
3. Get “Personal access tokens” for test user "Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information."
4. Git Clone repository on local machine

### **Setup on PCC :**

1. Add EasyCLA group
2. Configure GitHub EasyCLA App
3. CLA enforced GitHub repo

Steps :

1. Make changes on local repository say update README.md
2. Git Push changes on branch
```
a.      git checkout -b <branchName>
b.	git add .
c.	git status
d.	git commit -m “commit text”
e.	git push origin <branchName>
i.	add test user name : thakurveerendras1
ii.	add token key : ghp_jzCsHsxvxxxxxxxxxxxx
f.	Copy pull request url from cmd : https://github.com/VeerNoGithubIDOrgTest/repo02/pull/new/testbranch5
```
3. Past PR url on browser & create pull request
4. Update the email address which associated GitHub user (thakurveerendras1) under the system .getconfig file 
5. Repeat above steps 1 to 3 

Actual results : comment is updated correctly & added on previous missing IDs section 

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/a6e54a19-1cdf-4af0-968d-5be4e4fc5f08)

**Comment by dealako** [comment]
This issue is now resolved as part of this release: https://github.com/communitybridge/easycla/releases/tag/v2.0.109. Closing this issue.
