### ISSUE TITLE
Remove ‘NOT COVERED’ label when the second user signs the CLA & authorized commit details is missing

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3431]
Setup :

1. Add non existing email address under the system .getconfig file
2. Provide admin access at GitHub repo to test user say : thakurveerendras1
3. Get “Personal access tokens” for test user "Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information."
4. Git Clone repository on local machine

Setup on PCC :

1. Add EasyCLA group
2. Configure GitHub EasyCLA App
3. CLA enforced GitHub repo

Steps :

1. Make changes on local repository say update README.md
2. Git Push changes on branch
a.      git checkout -b <branchName>
b.	git add .
c.	git status
d.	git commit -m “commit text”
e.	git push origin <branchName>
i.	add test user name : thakurveerendras1
ii.	add token key : ghp_jzCsHsxvxxxxxxxxxxxx
f.	Copy pull request url from cmd : https://github.com/VeerNoGithubIDOrgTest/repo02/pull/new/testbranch5
11. Past PR url on browser & create pull request
12. Update the email address which associated GitHub user (thakurveerendras1) under the system .getconfig file
13. Repeat above steps 1 to 3
14. Now  The second user signs the CLA.

Actual results : ‘NOT COVERED’ label still present & authorized commit details is missing
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/24cfe9bb-0443-4f4f-803d-5ddd0ce0ff8c)

**Comment by dealako** [comment]
This is the expected behavior. Closing this issue.
