### ISSUE TITLE
The PR  should indicates ‘NOT COVERED’ when user resolved there GitHub id problem

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3432]
Setup :
1. Add non existing email address under the system .getconfig file
2. Provide admin access at GitHub repo to test user say : thakurveerendras1
3. Get “Personal access tokens” for test user "Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information."
4. Git Clone repository on local machine

Setup on PCC :

1. Add EasyCLA group
2. Configure GitHub EasyCLA App
3. CLA enforced GitHub repo

Steps :

1. Make changes on local repository say update README.md
2. Git Push changes on branch
a. git checkout -b
b. git add .
c. git status
d. git commit -m “commit text”
e. git push origin
i. add test user name : thakurveerendras1
ii. add token key : ghp_jzCsHsxvxxxxxxxxxxxx
f. Copy pull request url from cmd : https://github.com/VeerNoGithubIDOrgTest/repo02/pull/new/testbranch5

1. Past PR url on browser & create pull request
See-Missing ID on commit appears

1. Now user resolved there GitHub id problem

Actual results : Missing ID on commit appears & old message appears at body
Expected : The PR  should indicates ‘NOT COVERED’ when user resolved there GitHub id problem
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/63fa9456-0562-471f-80f5-2470b6d483d9)
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/3fcd15be-d1ab-48b4-8c96-905c8f811d07)

**Comment by dealako** [comment]
This is the expected behavior. Closing this issue.
