### ISSUE TITLE
Missing ID on commit : commit body information is not appears as expected when both user signed cla 

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3433]
Setup :

1. Add non existing email address under the system .getconfig file
2. Provide admin access at GitHub repo to test user say : thakurveerendras1
3. Get “Personal access tokens” for test user "Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information."
4. Git Clone repository on local machine

Setup on PCC :

1. Add EasyCLA group
2. Configure GitHub EasyCLA App
3. CLA enforced GitHub repo

Steps :

1. Make changes on local repository say update README.md
2. Git Push changes on branch
a. git checkout -b
b. git add .
c. git status
d. git commit -m “commit text”
e. git push origin
i. add test user name : thakurveerendras1
ii. add token key : ghp_jzCsHsxvxxxxxxxxxxxx
f. Copy pull request url from cmd : https://github.com/VeerNoGithubIDOrgTest/repo02/pull/new/testbranch5
1. Past PR url on browser & create pull request
See-Missing ID on commit appears
1. second user signed cla
1. Now user resolved there GitHub id problem & signed cla

Actual results :  GitHub status is now passing but comment message is missing
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/a6dc2b31-0d78-4460-a30e-4cff7f2d8a7c)

**Comment by dealako** [comment]
This is the desired behavior. Closing this ticket.
