### ISSUE TITLE
allow a project to accept DCO or EasyCLA

### ISSUE THREAD

**Issue by kapilt** [communitybridge/easycla#3447]
as a configuration option for a project, enable it to accept either DCO or easy cla, if a pr / commits are already signed off with DCO then disable the easycla status check.

**Comment by dealako** [comment]
Generally, the community Project Manager, with support from the legal team, determines if a project will support DCO signoffs and/or Contributor License Agreements (CLA). DCO's are configured within GitHub itself. If a CLA is selected, then the Project Manager configures the project to use a CLA from the Project Control Center (https://projectadmin.lfx.linuxfoundation.org/) by selecting the appropriate CLA documents/templates, if a corporate and/or individual agreement is necessary, and which GitHub organizations/repositories the CLA agreement applies to.  In all cases, the decision to use a DCO or CLA is determined by the Project Manager - not contributors.

**Comment by WillsonHG** [comment]
I'll mark this as closed since DCO/EasyCLA can work together or separately. As David said, the call to use one or the other or both is typically the project's call and usually defined in the project's charter.
