### ISSUE TITLE
EasyCLA not updating PRs with status check

### ISSUE THREAD

**Issue by mrbobbytables** [communitybridge/easycla#3458]
## Summary

EasyCLA is not posting status to PRs from author @chendave even after using `/easycla` to refresh status.
It still lists PRs as "Expected — Waiting for status to be reported"

Examples:
https://github.com/kubernetes/kubernetes/pull/108270
https://github.com/kubernetes/kubernetes/pull/108246

## Expected behavior

EasyCLA to post status

## Environment

* Environment:
  - [x] PROD 

## Acceptance Criteria

EasyCLA to update status reliably

**Comment by chendave** [comment]
@mrbobbytables thanks for following this!

Do you have any idea on why I am not authorized? Is that expected with easycla? I am pretty sure I have signed CLA long time ago and this issue is only happened with easycla.

**Comment by WillsonHG** [comment]
I think we can call this resolved, I see that both of the linked PRs reported a passed EasyCLA status for @chendave on Feb 23rd, 2022 and his most recent PR in Kubernetes also passed.
