### ISSUE TITLE
EasyCLA status comment not properly updated when there are 2 or more authors

### ISSUE THREAD

**Issue by jarias-lfx** [communitybridge/easycla#3464]
Noticed EasyCLA status comment not updating when there are 2 or more authors. Example on PR: https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/pull/102, the status is marked as:

![image](https://user-images.githubusercontent.com/93140557/156028298-6ef95fae-6a32-4bbf-bebb-64cc2978fc9a.png)

This PR, however, has two authors kewang-equinix and wangxin311 on different commits, only the first commit author is showing on the status comment.

The logs on the other hand is checking for both:

![image](https://user-images.githubusercontent.com/93140557/156028696-b385f1b6-21b8-4dbf-902d-cab3dcf7e9c4.png)

```
2022-02-26T19:55:21 DEBUG cla: utils.user_signed_project_signature - ICLA signature check passed for User: id: d5e8addf-86b3-4add-b492-f6bca69ec7ff, username: kewang-equinix

2022-02-26T19:55:21 DEBUG cla: utils.user_signed_project_signature - ICLA signature check passed for User: id: fe7fc57f-ee4e-4de3-81a1-706e38466e3d, username: wangxin311
```

Logs AWS Link:
https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fcla-backend-prod-githubactivity/log-events/2022$252F02$252F26$252F$255B$2524LATEST$255Dec0a79e4170f454bbe54d6cea96a1a08$3Fstart$3D1645905300000$26end$3D1645905360000

**Comment by jarias-lfx** [comment]
Adding Logs in Text:
[issue-EasyCLA.txt](https://github.com/communitybridge/easycla/files/8155389/issue-EasyCLA.txt)

**Comment by dealako** [comment]
Working on refactoring how we display user details in the comment section. In this case, the GitHub user has the same name with different logins.

**Comment by dealako** [comment]
Deploying fix as part of this release: https://github.com/communitybridge/easycla/releases/tag/v2.0.111
