### ISSUE TITLE
Tag users in bot messaging

### ISSUE THREAD

**Issue by nate-double-u** [communitybridge/easycla#3479]
## Summary

Please tag users associated with commits that have failed the easyCLA check in the bot message.

## Background

During the Kubernetes release cycle, the docs team regularly updates an 'integration' branch with commits from the 'main' branch to keep things updated and create less work on release day.

These maintenance PRs are filled with commits from folks who may not be aware that these maintenance PRs are being made.

An example of this kind of PR: https://github.com/kubernetes/website/pull/32118

The @linux-foundation-easycla bot generates a message (https://github.com/kubernetes/website/pull/32118#issuecomment-1061280903), and lists problem commits, and provides a committer name for the commit that's caused the check to fail, but doesn't tag the user, so they may not be aware of an issue unless someone subsequently tags them and asks them to take a look.

<img width="871" alt="Screen Shot 2022-03-15 at 1 53 06 PM - edit" src="https://user-images.githubusercontent.com/4453979/158471690-f02331af-5f0d-49e7-abc9-a26f7f7f7889.png">

## User Story

- As a project manager, I want to notify users that they may no longer be authorized so that they can begin the authorization process.

**Comment by dealako** [comment]
I think, for this use case, we just need to tag the user by placing an '@' symbol in front of their name.

**Comment by dealako** [comment]
Created and merged PR. Ready for QA. @thakurveerendras can I get a quick QA on this ticket.

To test/validate:

Test 1 scenario:
1. Create a PR where one or more committers _are not_ authorized
1. Verify/Confirm users who are not authorized are @ tagged (GitHub will make a link and viewers can click on the link which will take them to the user's profile). Additionally, users will be notified when they are tagged (typically via email).

Test 2 scenario:
1. Create a PR where one or more committers _are_ authorized
1. Confirm that authorized users are NOT tagged.

**Note**: the tagging logic will not apply to users who are missing their GitHub ID (e.g. git user with mismatched GitHub ID).

**Comment by thakurveerendras** [comment]
Thanks @dealako for providing test scenario 

Issue is tested on dev site & found that both the scenario are fixed as expected , So making issue status QA-Done

### Here are test results :

- Verified users who are not authorized are listed with @ tagged & link redirect to the user's profile
- Verified authorized users are NOT appears with tagged.

### Refer screenshot for Test scenario  1 : 
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/81a2a958-0923-46e1-9971-9e9b9bd628f1)
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/42007183-e93a-4c3c-9069-1edd9e413cd3)
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/94d5dd6f-bfda-4e2e-9ad9-bf391347cbcb)
https://images.zenhubusercontent.com/194341141/f4844017-4076-45d0-8097-2e914d2d28b8/3479_taggeduser.mp4

### Refer screenshot for Test scenario  2 : 
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/57fd3b15-5f69-4941-b14d-3a99fbe3cf39)
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/7232bd0f-3f8a-4f77-9a6f-5e5734fbcb18)

**Comment by dealako** [comment]
Deployed to PROD. Closing issue.
