### ISSUE TITLE
Contributor Console - Request CLA Manager to Whitelist

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#348]
## Summary

In the Contributor Console, the Request CLA Manager to whitelist a corporate developer experience is confusing and lacks clarity on who will be notified.

## Background

The current workflow supports two use-cases (use-case 1 and 2) - use case 1 works well and does not need modifications.  Use case 2 needs refinement.

Summary:

Use Case 1

Setup: CLA Manager has signed a CCLA for a Company under a given Project

1. Corporate Developer is blocked by the EasyCLA check-in GitHub
1. Corporate Developer follows the link to Contributor Console
1. Corporate Developer selects Corporate from the two options (CCLA vs ICLA)
1. Corporate Developer selects his/her Company from the List
1. Corporate Developer selects his/her email address from pick-list
1. Corporate Developer sends an email (note: recipient/CLA Manager of the email is not identified, but will go to the FIRST CLA Manager listed for the company)
1. CLA Manager will receive the email
1. CLA Manager will log into the Corporate Console
1. CLA Manager will whitelist the Corporate Developer based on one of domain/email/GHID/GH Org
1. CLA Manager notifies CLA Developer (not via EasyCLA, probably via separate email) that they have been whitelisted
1. Corporate Developer notices that they are still blocked
1. Corporate Developer follows the link to Contributor Console
1. Corporate Developer selects his/her Company from the List
1. Corporate Developer is asked to confirm their association with the Company
1. Corporate Developer is redirected back to GitHub
1. Corporate Developer observes that they pass the EasyCLA check-in GitHub

Use Case 2 (current behavior and not optimal):

Setup: CLA Manager has **NOT** been identified for the Company under a given Project

1. Corporate Developer is blocked by the EasyCLA check-in GitHub
1. Corporate Developer follows the link to Contributor Console
1. Corporate Developer selects Corporate from the two options (CCLA vs ICLA)
1. Corporate Developer selects his/her Company from the List
1. Corporate Developer selects his/her email address from pick-list
1. Corporate Developer sends an email (note: recipient/CLA Manager is not identified - so I believe the system currently emails on of the Project Admins)
1. The wrong person will receive the email

Use Case 2 (to be built):
    
Setup: CLA Manager has **NOT** been identified for the Company under a given Project

1. Corporate Developer is blocked by the EasyCLA check-in GitHub
1. Corporate Developer follows the link to Contributor Console
1. Corporate Developer selects Corporate from the two options (CCLA vs ICLA)
1. Corporate Developer selects his/her Company from the List
1. (**New Behavior**) Corporate Developer selects a recipient from a list of existing Project/Company CLA Managers **OR** (new behavior) is allowed to input a name/email recipient
1. Corporate Developer selects his/her email address from the pick-list (Corporate Developer may have more than one email associated with their user record).
1. Corporate Developer sends an email to the desired CLA Manager recipient

## User Story

See above.

## Acceptance Criteria

1. Workflow executes the to be built workflow when the CLA Manager has not been identified
1. Unit Tests added and running in CI
2. Functional Tests updated to cover feature, if applicable
2. Demonstrate the set of capabilities to the product team while the code is
   running in the STAGING environment.

## References

N/A

**Comment by dealako** [comment]
@ngozi-ekekwe I've started work on this task, but since I'll be working with the team at KubeCon, I am going to ask that you finish it for me.  I will push my changes now to master/dev - but I need you to complete the work.  I'll coordinate with you on Monday.

**Comment by dealako** [comment]
To recap the steps forward:

**Comment by WillsonHG** [comment]
https://github.com/communitybridge/easycla/issues/355

**Comment by amolsontakke3576** [comment]
@dealako I have checked this ticket and look's like it is already implemented or may be look like flow has changed. Can you please confirm the current behaviour as per your expectation or not ?

**Comment by nirupamav** [comment]
This flow has been tested in Sanity testing performed on 14-Jul-2020 and is working as expected
