### ISSUE TITLE
PR showing authorized with not covered status for project which don't have ICLA/CCAL records(fresh setup)

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3481]
Steps : 

1. Add new project under PCC
2. Add cla group
3. Add GitHub organization & enabled cla enforced
4. Go to GitHub & commit changes on new branch
5. Create pull request

Actual Results -No ICAL/CCAL records & PR showing authorized with not covered status

- New project : VEER_CLA_MISSINGIDCASE2_PROJECT
- PR : https://github.com/veer-missingid2/repo02/pull/1

`❌ login: @thakurveerendras (2931104). This user is authorized, but they must confirm their affiliation with their company. Start the authorization process by clicking here, click "Corporate", select the appropriate company from the list, then confirm your affiliation on the page that appears. For further assistance with EasyCLA, please submit a support request ticket.`

https://images.zenhubusercontent.com/194341141/8fcc7a40-5317-4cd7-9b2e-50e55f5e6b2d/this_user_is_authorized.mp4
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/48462f7c-ae65-42a2-ac16-54222b163d8c)

**Comment by dealako** [comment]
@thakurveerendras ready for QA. Deployed to DEV.

**Comment by thakurveerendras** [comment]
Thanks @dealako 
Issue is teste on dev site & found that it not reproducible as reported, So making issue status QA-Done

- PR : https://github.com/veer-missingid2/repo06/pull/1
- Body message on PR

`❌ - login: @thakurveerendras . The commit (2049080) is not authorized under a signed CLA. Please click here to be authorized. For further assistance with EasyCLA, please submit a support request ticket.` 
![image](https://user-images.githubusercontent.com/75417507/159226685-cb3a46a1-524f-45f0-8912-ab55c197cf73.png)

**Comment by dealako** [comment]
Deployed to PROD on 02/21/2022.
