### ISSUE TITLE
EasyCLA Bug Report: Corp CLA console times out

### ISSUE THREAD

**Issue by mrbobbytables** [communitybridge/easycla#3492]
## Summary

As a Googler, when viewing the [corp CLA console](https://organization.lfx.linuxfoundation.org/foundation/a0941000002wBz4AAE/cla), it times out trying to load, or takes a long time to load (going on 15min now).

## Expected behavior

It to load a list of CLAs and CLA manager.

## Screenshots

<img width="1616" alt="Screen Shot 2022-03-29 at 2 11 29 PM" src="https://user-images.githubusercontent.com/6500863/160689276-f54b52e7-951b-4074-a340-9eaa5e5885ca.png">

## Environment

* Environment:
  - [ x] PROD 
* Browser:
  - [x] Chrome/Brave
  - [x] Firefox

**Comment by jarias-lfx** [comment]
Hi @mrbobbytables, thanks for reporting this bug. The issue has been fixed, would you please try again and confirm that is working for you?. Thanks.

**Comment by mrbobbytables** [comment]
That did it, thanks!
Now to sort out the CLA managers listed issue....

**Comment by dealako** [comment]
Resolved.
