### ISSUE TITLE
REQUEST: Dump of *Google.com orgs and  CLA Manager

### ISSUE THREAD

**Issue by mrbobbytables** [communitybridge/easycla#3493]
Googlers who have not signed the CLA have reported multiple google orgs listed and CLA managers that don't exist or have names like "vegemite cheese toast". I would like a dump of orgs and active CLA managers to audit.

**Comment by jarias-lfx** [comment]
Hi @mrbobbytables, thanks for reporting this issue. Allow me review all Google information in our systems and will update you with my findings.

**Comment by mrbobbytables** [comment]
@jarias-lfx thanks! something definitely seems fishy with the primary google one right now...only 4 CLA Managers and 3/4 aren't Googlers.

**Comment by jarias-lfx** [comment]
@mrbobbytables do you mind if I contact you directly at killen.bob@gmail.com to handle this information?. This to avoid exposing private information. Thanks.

**Comment by mrbobbytables** [comment]
Thanks!
Dump was provided and current CLA Managers updated.
There is some follow up to learn how some of these folk became CLA Managers, but that's a separate issue.
