### ISSUE TITLE
EasyCLA Bug Report: Does not load or partially loads contributor acknowledgements from my organization

### ISSUE THREAD

**Issue by mrbobbytables** [communitybridge/easycla#3501]
## Summary

List of contributor acknowledgements  is empty / partially populated depending.
This is potentially related to #3500

## Expected behavior

For it to load the list of contributor acknowledgements

## Screenshots
![Screen Shot 2022-04-06 at 10 56 34 AM](https://user-images.githubusercontent.com/6500863/162017238-765601d8-17fe-475b-8634-f1c22c584339.png)

## Environment

Please complete the following information:

* Environment:
  - [ ] ALL
  - [ ] DEV
  - [ ] STAGING
  - [x] PROD 
* Browser:
  - [x] Chrome/Brave
  - [x] Firefox
  - [ ] Opera
  - [ ] Vivaldi
  - [ ] LibreWolf
  - [ ] SRware Iron
  - [ ] Dissenter
  - [ ] Slimjet
  - [ ] Midori
  - [ ] Edge
  - [ ] Lynx

## Acceptance Criteria

Fully load the list of contributor acknowledgements, or change the behavior to paginate and display something like 20/50/100/500 at a time.

**Comment by dealako** [comment]
Added pagination to the API as part of PR: https://github.com/communitybridge/easycla/pull/3497 - awaiting UX team updates to add pagination client side support.

**Comment by mrbobbytables** [comment]
Is there a rough ETA on when the UX side will add pagination?

**Comment by WillsonHG** [comment]
We're working to get an ETA for when the pagination can be added to the acknowledgement section in the UI.

**Comment by mlehotskylf** [comment]
@nickmango please validate if this is fixed.

**Comment by mlehotskylf** [comment]
This issue is fixed. Closing this ticket.
