### ISSUE TITLE
Request: Dump of Google  CLAs

### ISSUE THREAD

**Issue by mrbobbytables** [communitybridge/easycla#3513]
As there appears to be no timeline for for the UX to be fixed. Could you please send me (bobkillen@google.com) a dump of the Google CLAs to be audited.  I'll update the list and get back to you with the people who should be removed.

**Comment by dealako** [comment]
The API issue is resolved (added pagination support). The UI team is scheduled to work on the front-end updates this week (week of April 18th).

**Comment by dealako** [comment]
Shared Google Employee Ack record dump via Slack.

**Comment by dealako** [comment]
@mrbobbytables LMK if this update is satisfactory. If so, we can close this issue.

**Comment by dealako** [comment]
Closing issue.
