### ISSUE TITLE
Query EasyCLA for CLA Manager info

### ISSUE THREAD

**Issue by dmcbride64** [communitybridge/easycla#353]
**Summary**

In the short period of time that EasyCLA has been operating, we have found the need to find out who the CLA Manager is for a given project and organization.

**Background**

1. This would be an administrative or management feature having separate credentials from typical users.
2. Select "CLA Manager Search" from a list of available functions.
3. Select the project from a list of projects using EasyCLA
4. Optional:  Select the organization from a list of organizations
5. If the user entered a project and organization, display the contact info for the CLA Manager
6. If the user only entered a project, then display all of the CLA Managers and their contact info in table format

**User Story**

As a project manager, I want to be able to find out who the CLA manager is for a particular project and organization, or a list of all CLA managers for a project.

**Acceptance Criteria**

Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

**Comment by dealako** [comment]
We may be able to incorporate additional details in the Project Console -> CLA Group -> Signatures View to show which companies have signed CCLAs and, to this point, who are the CLA managers for that company and who signed (the CCLA Signatory).  Using this approach, we would limit WHO could see this information by using the current project access control list rules.

**Comment by dmcbride64** [comment]
Yes, in fact I created this ticket based on a conversation that I had with
Kenny.

David

**Comment by dealako** [comment]
@prasannamahajan and @asithade  for v1, could you both please review this ticket? On the current project console, we have a view for “Project Signatures” including a table and search which @asitha has added.

I would like to add a similar link with a pop-up data table which allows the Project Manager (with his existing permissions) to generate a report (table view) that lists the companies and corresponding CLA manager(s). This will search the selected/current CLA Group (signatures table -> project_id == current project/cla group -> `signature_reference_type` == 'company', => signature_type == 'ccla' -> `signature_reference_id` not empty, -> `signature_user_ccla_company_id` == null) only.

@prasannamahajan we will need a specific API request that returns this information. =>

1. Review the search signatures API endpoint - leverage the existing search terms/pattern
Search Corporate Signatures for a given project id.
2. Extract the values from the signature_acl column
3. Lookup the signature_acl user details in the user's table
4. Generate a response data model
5. Return the model to the user

@asithade
1. Establish a link and data table for the Front End Work
2. Columns should include Company + User ID/LFID  + User Name + Email
3. Figure out a nice way to include companies with multiple CLA managers (Company + CLA Manager per row might be the best option)
4. Provide search/sort features (sort by company or user name)

## References

https://confluence.linuxfoundation.org/display/PROD/EasyCLA+Version+1+Database+Schema+Walkthrough#EasyCLAVersion1DatabaseSchemaWalkthrough-Signatures

**Comment by dealako** [comment]
This feature has been implemented in DEV and STAGING. Awaiting additional testing (EasyCLA as a whole) before we roll out all these changes to PROD.

**Comment by dealako** [comment]
To test/validate:

**Comment by nirupamav** [comment]
**_Observed that CLA Manager who has signed the CLA for the project is displayed in the VIEW COMPANIES_**
![image](https://user-images.githubusercontent.com/60865903/78104593-0ece0100-740d-11ea-9b2e-03ea76ef7c8f.png)

![image](https://user-images.githubusercontent.com/60865903/78104612-19889600-740d-11ea-9d45-8e9851ca47a2.png)

**Comment by nirupamav** [comment]
Verification of display of multiple CLA Managers of a Company for a project is blocked due to bugs #782 and #790. Hence keeping the ticket open
