### ISSUE TITLE
EasyCLA checks not working on Gitlab repos.

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#3537]
## Summary

ONAP GitLab checks are not working.

## Background
After installing EasyCLA on Gitlab via PCC, a test merge request is not showing an EasyCLA Check. https://gitlab.com/onap/integration/test/-/merge_requests/2

## Environment
PROD 

## Additional Context
For troubleshooting, reporter has uninstalled and reinstalled on both Gitlab and PCC side.

**Comment by dealako** [comment]
It seems the authorization token we get from GitLab expires in 7200 seconds or 2 hours. 

Previously, the auth0 token lasted forever. Something has changed and now the auth0 token only lasts 2 hours.  As a result, the EasyCLA GitLab integration is experiencing token expired errors.
Ref:
- https://stackoverflow.com/questions/39229186/gitlab-refresh-oauth-token
- Issue: https://gitlab.com/gitlab-org/gitlab/-/issues/21745
- Docs: https://docs.gitlab.com/ee/integration/oauth_provider.html

**Comment by tykeal** [comment]
BTW GitLab 15 was released on May 22 (or at least announced as released) https://about.gitlab.com/releases/2022/05/22/gitlab-15-0-released/ which is when the non-expiring tokens stopped being a thing.

**Comment by jarias-lfx** [comment]
Update:
Sylva project is requiring EasyCLA for their GitLab project. Ticket: [SUPPORT-15596](https://jira.linuxfoundation.org/browse/SUPPORT-15596). Waiting on fix ETA.

**Comment by nickmango** [comment]
@dealako 
A solution that I considered was updating the `cla-dev-gitlab-orgs` table with `expires_in` column and `refresh-token` that can be used to check for the validity of the token. In case its not valid we can update our auth_info taken by making another auth call with the refresh_token value
A more ideal solution would be to shift from dynamodb storage to redis cache setting. a TTL value for auth_info based on expires_in value

**Comment by dealako** [comment]
Understood. As discussed in our standup, let's work to:

1. Add expires_in/expires_on/expires_at column (you decide on the naming convention) to the database. We may need to update EasyCLA DynamoDB terraform to account for the new column. I can assist with this if desired.   I think this would be valuable to have.  We'll want to update the data model, repository layer, and query projections.
2. Work to add the logic to check the expiration value, add logic to execute the token refresh logic, and save the value back into the database.

A Redis cache solution could assist with this solution. However, this will take some time to add this integration. Until then, let's proceed with the simple token check/refresh logic.

**Comment by thakurveerendras** [comment]
@nickmango , Tested issue on dev site & found that merger request are still not gated 
![image](https://user-images.githubusercontent.com/75417507/218700367-7cdde23d-f39f-440a-8158-7cb9a255b344.png)
![image](https://user-images.githubusercontent.com/75417507/218700527-64c2d525-5c3d-4ed0-b82b-709ccd19d624.png)

**Comment by thakurveerendras** [comment]
Issue is not reproducible as reported. Now merge request are properly gated, So making issue status QA-Done
Refer video clip : 
[#3537.webm](https://user-images.githubusercontent.com/75417507/220548834-de79d688-528c-46c9-8a68-51f2df0a6455.webm)
