### ISSUE TITLE
No escalation path for non-response corporate CLA admin

### ISSUE THREAD

**Issue by directionless** [communitybridge/easycla#355]
Hi, I'm not sure if this is a bug, or what. But I'm one of the osquery maintainers. And I've had a couple of users reach out to me trying to get the corporate CLA setup. For one of them, they _have_ a corporate CLA setup with EasyCLA, but internally they're not sure who the admin is, and they are stymied. 

What is the recovery process for this? How can end users self service?

**Comment by nyanshak** [comment]
Thanks @directionless. I'm currently blocked on contributing to osquery due to this. I've been trying for over a week to try to track down the admin, but can't find who it is. At minimum, it would be great to expose some sort of name / email for the admins, and some way to start a recovery flow.

**Comment by WillsonHG** [comment]
We definitely agree with that. The recovery flow for having no company signature on file for a particular project is currently being revamped to show who the current CLA managers are for the company, and to allow you to send them an email. If there are no managers, then you will have the option to send an email to the person who you think it should be - with instructions on how to login and sign. 

Until that redesign is finished, I can manually add a signatory's LFID to the system so they can get in to sign, it just takes the extra step of getting that LFID to me. I've reached out to Brendan via the JSD ticket he created, so hopefully we can get that signatory in soon.

**Comment by pranab-bajpai** [comment]
Hi @directionless, @nyanshak. I am the new product manager for EasyCLA, we are improving the current interface to explain out the steps and allow users to file a support case from the site (if they don't find what they are looking for). Within the next two weeks we will have these changes implemented and I am sure it will improve your experience.

**Comment by WillsonHG** [comment]
@directionless I'd like to help any other users who are blocked as well. The other users you mentioned, do you know what companies they work for? Are there any pull requests you can direct me to?

**Comment by pranab-bajpai** [comment]
This issue is duplicated by #361  and #362

**Comment by directionless** [comment]
@WillsonHG I haven't been tracking blocked users. But I've recently learned about the jira install. That's been a good route for getting help for a user. 

I'll follow #361 for the underlying UX issues. Thanks @pranab-bajpai
