### ISSUE TITLE
Should be able to handle pending applicants for Org CLAs entirely through the dashboard

### ISSUE THREAD

**Issue by jberkus** [communitybridge/easycla#3551]
## Summary

As an Organization administrator, I should be able to see a list of applicants to join our corporate CLA who were not automatically approved.  However, there appears to be no element in the UI for this.

## Background

1. Log into https://organization.lfx.linuxfoundation.org
2. Go to any CNCF project
3. See headings including the following: Active CLAs, CLA Managers, Approved List, Contributor Acknowledgements, Recent Activity
4. There is no "Pending Applications"

## Expected behavior

There should be a "Pending Applications" section of CLA requests that have not been approved by the organization yet.

## Environment

Not Applicable

**Comment by jberkus** [comment]
Additionally:

* Emails to approved or refused applicants should be automatically sent by EasyCLA.

**Comment by dealako** [comment]
Notes on the tasks required:

1. Create a new DB table to catalog requests, included columns might be CLA Group ID (project_id), Organization ID, Requestor, Date/time, Status {Pending, Approved, Denied}, Notes.
2. Develop an internal API to support Add/Update/Delete/Get/List for corporate approval requests.
3. When sending the request to CLA managers to get added to the approval list, a new entry into the new approval requests table
4. Update the Corporate Console to show the approval requests in a table view, allow filtering based on status and/or user info
5. Allow CLA managers to transition the pending request to Approval or Denied. Allow them to make a note
6. Possibly, when the approval action is pressed, allow the CLA manager to add an entry into the email, email domain, github username, gitlab username approval list.
7. Have the system auto-repond with a form email notifying the requestor that the request has been processed (approved or denied with the note).

**Comment by WillsonHG** [comment]
I have added this to our internal tracking and will ask the team to investigate and provide us an estimation for the work involved [LFX-3200](https://jira.linuxfoundation.org/browse/LFX-3200).

**Comment by nickmango** [comment]
The contributor acknowledgement section has a status column detailing the pending approvers as requested
@jberkus Kindly verify on your end.

**Comment by jberkus** [comment]
I can verify that the column is there.  We haven't had any pending applications since this issue was updated; I'll let you know as soon as we do so that we can confirm this end-to-end.

**Comment by jberkus** [comment]
There is a missing feature here.  Currently, contributor acknowledgements are randomly sorted.  This means that finding the one or two pending entries involves an hour of scrolling.

They should be sorted in reverse date order, with the most recent on top.

**Comment by nickmango** [comment]
@thakurveerendras kindly verify the sorting of the contributor list on the org dashboard

**Comment by jberkus** [comment]
Cool, let me know when this change is copied to production so I can test.

**Comment by mlehotskylf** [comment]
This is already in PROD, closing this ticket.
