### ISSUE TITLE
Add help/support button missing on EasyCLA main page.

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#3552]
On the main splash page for EasyCLA - https://easycla.lfx.linuxfoundation.org/#/ we need a link to docs and support. The top navigation ribbon is missing the ? Get Help dropdown that links to the Docs and Product support that all of the lfx tools have.

![image](https://user-images.githubusercontent.com/46732999/176003273-32dc6cbf-5ea7-48bb-97ad-994fda32463f.png)

**Comment by dealako** [comment]
@amolsontakke3576 here is the EasyCLA landing page. Please coordinate with @WillsonHG to implement the links.

https://github.com/communitybridge/easycla/tree/main/cla-landing-page

**Comment by dealako** [comment]
@amolsontakke3576 resolved this ticket via [pull request 3561](https://github.com/communitybridge/easycla/pull/3561). @WillsonHG can you QA this in DEV?

**Comment by dealako** [comment]
QA complete. Closing issue.
