### ISSUE TITLE
Corporate Console - EasyCLA - Removing contributors who signed a CCLA

### ISSUE THREAD

**Issue by dgoubin** [communitybridge/easycla#3576]
Story: 
When a contributor signed a CCLA,
I want to be able to remove one or more user(s) from the list,
So I can keep the list up-to-date

Context:
Some contributors could have changed companies and/or could have used a wrong email address.

**Given** I am Member user
**When** A user is present in the SIGNED CCLAs section
- then a "Remove" button is presented
- then I am being presented a confirmation box that ask for confirmation to remove the user from the list
- then an automatic email is being sent to the user to inform his CCLA has been revoked.

![Image](https://user-images.githubusercontent.com/3006701/182096560-53cae776-aeac-4f07-be1d-3b448230522b.png)

**Comment by dealako** [comment]
We are closing this old ticket. We can re-open/re-create at a later date if needed.
