### ISSUE TITLE
PCC - Repos being installed at the foundation level are being displayed at the fund level and duplicated.

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#3578]
For the Sonic project.
Sonic project members reported issues with Easycla running on some repos. Investigating showed duplicated repos in database. Checking logs and fullstory, the sequence of events were:

Formation team created CLA group (icla only) at the foundation level and installed repos at foundation level. Shortly after, repos were switched to 'enabled = false' and new entries were created with 'enabled = true' showing at the fund level. This duplicated all repositories in the database, but all entries had the same correct project_sfid and respository_sfid in the table. They were exact duplications, yet some were showing in the UI as installed at the fund level and some were at the foundation level. (The audit log captured these actions, but did not capture an associated user.)

Image of PCC after duplication issue.
![image](https://user-images.githubusercontent.com/46732999/183450901-4bc06136-f886-479e-9945-9a5ebf77b3ea.png)

After testing a few repos that were not running or showing 'expected' status (sonic-mgmt, sonic, and sonic-frr) I removed duplicates entries for those 3 repos and tested via /easycla comment that they were indeed running again, so I backed-up and deleted the remainder of the 31 duplicate entries. 

Now all repos seem to be running easycla correctly and linking to the correct icla group for SONiC foundation, but the PCC UI is showing it as installed at the Fund level instead of the lower Foundation level. This doesn't seem to have any impact except displaying it incorrectly in the PCC since the CLA document is correct for contributors.

1) How did this happen, is there an issue now in the PCC with installing new CLA groups with this project structure?
2) We need to review the projects and projects-cla-groups tables for correct values for SONiC to resolve the display issue.

**Comment by WillsonHG** [comment]
For more info [SUPPORT-11667](https://jira.linuxfoundation.org/browse/SUPPORT-11667)

**Comment by WillsonHG** [comment]
changing repository_sfdc_id fixes the association in PCC.
Also need to investigate why the 'projects' table had fund for both project/foundation id values

**Comment by mlehotskylf** [comment]
@nickmango @WillsonHG is this still an issue?

**Comment by nickmango** [comment]
@mlehotskylf The duplication of the repositories has been resolved and this isnt an issue

**Comment by mlehotskylf** [comment]
@WillsonHG this is not an issue anymore, closing. Please let us know if you have any concerns. Thanks!
