### ISSUE TITLE
Update OnBoarding Forms

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#358]
## Summary

Update the OnBoarding forms to include the EasyCLA branding and colors.

## Task

- [ ] Update colors to match EasyCLA branding
- [ ] Include EasyCLA logo

## Acceptance Criteria

Showcase form updates to stakeholders: @kriva03, @pranab-bajpai, and @WillsonHG 

## References

- [Project Onboarding Form]( https://docs.google.com/forms/d/e/1FAIpQLSdnTk_9xjk7YoiX_FcPEqsFytsLMcT8OzYUbK6TsYopR1XhdA/viewform)
- [Corporate Manager/CLA Admin](https://docs.google.com/forms/d/e/1FAIpQLSdr92JpPEVWBleNbIB41WWzVuktcD9uOj9nzaZV0SkhTNo_Rw/viewform)
- <a href="https://lfcla.com" target="_blank">EasyCLA</a>

**Comment by dealako** [comment]
@ngozi-ekekwe I think this task is complete. Any other feedback from @kriva03 or @pranab-bajpai?  If no, then let's close.

**Comment by ngozi-ekekwe** [comment]
> @ngozi-ekekwe I think this task is complete. Any other feedback from @kriva03 or @pranab-bajpai? If no, then let's close.

No other feedback

**Comment by dealako** [comment]
Resolved.
