### ISSUE TITLE
Github organization configured to the child should be shown to the parent CLA groups manage screen.

### ISSUE THREAD

**Issue by amolsontakke3576** [communitybridge/easycla#3605]
- Go to the PCC dev https://pcc.dev.platform.linuxfoundation.org/
- Create one parent project (PCC-Parent-Project)
- Add two child projects to the parent (PCC-Child-Project-1 and PCC-Child-Project-2)
- Create CLA group to first child project and configured github org.
- Create CLA group to second child project and configured github org.
- Go to the parent project 
- You can see both the CLA groups
- click on manage button 
- No github organisation shown.

![Image](https://user-images.githubusercontent.com/56335654/195831218-3d987f5e-25a8-460f-9ec5-15c01feb5298.png)
![Image](https://user-images.githubusercontent.com/56335654/195831219-38fc3ff4-cb40-4038-b2c4-64c0878040c7.png)

**Comment by thakurveerendras** [comment]
Issue is tested & found that it is fixed as expected on dev site, related frontend tickets are already moved to QA-Done state , So moving this tickets status QA-Passed on dev site 
Related ticket : [PCC-2479](https://jira.linuxfoundation.org/browse/PCC-2479) : Easycla : Wrong GitHub organization appears at child project

**Comment by thakurveerendras** [comment]
Now able to see GitHub organization at child1 & child 2 projects as expected, Reported issue is properly fixed & deployed at prod end.

**Comment by mlehotskylf** [comment]
Done.
