### ISSUE TITLE
EasyCLA - Allow users to create new cla group at grand child project

### ISSUE THREAD

**Issue by amolsontakke3576** [communitybridge/easycla#3626]
In PCC, we should be able to use the existing pages for configuring CLA Group on a grandchild.

Description :
A/C: As a PM, I can add new cla group at grandchild project via parent project
A/C: As a PM, I can add new cla group at grandchild project via grandchild
A/C: As a PM, I can't add new cla group at grandchild project when cla group is already exist at parent group
A/C: As a PM, I can enroll parent project CLA group to grandchild project
A/C: As a PM, I can unenroll parent project CLA group to grandchild project
A/C: As a CLA manager, I can manage grandchild project from parent project easycla page
A/C: As a CLA manager, I can manage grandchild project from grandchild project easycla page

**Comment by thakurveerendras** [comment]
Tested issue on dev site & found that it is implanted as expected , Refer related ticket [PCC-1996](https://jira.linuxfoundation.org/browse/PCC-1996)  
ID | Summary | Status | Comments
-- | -- | -- | --
1 | As a PM, I can add new cla group at grandchild project via parent project | Passed |  
2 | As a PM, I can add new cla group at grandchild project via grandchild | Passed |  
3 | As a PM, I can't add new cla group at grandchild project when cla group is already exist at parent group | Invalid | Use case is invalid after finos implementation
4 | As a PM, I can enroll parent project CLA group to grandchild project | Passed | As per requirement ,-User can enroll grandchild project only on parent project Cla group.-Foundation project cla group are not allowed to enrolled
5 | As a PM, I can unenroll parent project CLA group to grandchild project | Passed |  
6 | As a CLA manager, I can manage grandchild project from parent project easycla page | Passed | PCC-955, Manage button enabled only for CLA selected project
7 | As a CLA manager, I can manage grandchild project from grandchild project easycla page | Passed |  

</div>

**Comment by mlehotskylf** [comment]
Done, closing.
