### ISSUE TITLE
Add Help Desk links on *.lfcla.com

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#363]
Currently, there are no links on the EasyCLA site pages for users to get help. The product support desk at https://jira.linuxfoundation.org/servicedesk/customer/portal/4 should be easily accessible for users. There are also a few links that are deprecated.

-Adding a support link to the console footer section on lfcla.com, project.lfcla.com, and corporate.lfcla.com would make it visible on every page. This would probably be the most efficient solution if possible.

lfcla.com- The "Get Help" button at the top currently links to the confluence docs, which are now obsolete. That button could link to the service desk instead, or at the very least link to the current docs on GitHub.

**Comment by dealako** [comment]
@pranab-bajpai please review and validate/verify. Should be an easy fix which will help @WillsonHG

**Comment by pranab-bajpai** [comment]
I agree, this is a small change with wide impact and should be implemented quickly.

**Comment by dealako** [comment]
> After logging in to https://project.lfcla.com/ The "Get Access" link gives a 404 error. Currently, it points to:https://github.com/communitybridge/easycla/blob/master/docs/get-access-to-easycla.md
The page is now missing - where is it in gitbook?

**Comment by dealako** [comment]
Merged PR #391 which resolves these issues.
