### ISSUE TITLE
Allow for child CLA with existing Foundation Umbrella CLA

### ISSUE THREAD

**Issue by nickmango** [communitybridge/easycla#3638]
## Summary
Allow for a child project to create a separate CLA at the project level in the case theres the foundation Umbrella CLA

## Background
The original design of EasyCLA includes a concept where a parent project (typically a Project Group) can establish a CLA group. This CLA Group would allow the project and any child projects who enroll in EasyCLA to leverage a single common CLA. Today, this is used and implemented in Academy Software Foundation, FINOS, and a few other projects. The EasyCLA API and UI consoles were implemented to honor this setup and to protect against accidental CLA Group creation at the child project level.

Recently, the FINOS community encountered a scenario where they continue to want the common CLA Group at the FINOS project group level, but one or more child projects need to have a completely different CLA

## User Story
As a project manager , I should be able to create CLA for a child project thats covered under an existing Foundation CLA

## Acceptance Criteria
Unit Tests added and running in CI
Functional tests updated to cover feature, if applicable
Demonstrate the capability to create child CLA initially configured with a foundation Umbrella CLA

## References
https://confluence.linuxfoundation.org/display/PROD/EasyCLA+-+Foundation+Umbrella+CLA+With+Separate+Child+CLA

**Comment by thakurveerendras** [comment]
One round of testing is already done on above feature & it is implemented as expected.

**Comment by mlehotskylf** [comment]
Done, so closing.
