### ISSUE TITLE
Provide an API Endpoint to Set/Unset the Auto-Enable Employee Acknowledgements

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#3640]
## Summary

Provide an API endpoint to Set/Unset the Auto-Enable Employee Acknowledgements

## Background

The EasyCLA team has rolled out a new feature that allows CLA managers to decide if employee contributions should be auto-enabled/created when adding and removing entries from the approval list. This capability is under a new feature flag which is on the CCLA signature record. Currently, we do not support setting/resetting this value via the API or UI.  This task is to add a new API endpoint that will allow CLA managers (from the CLA Corporate Console) to set/unset this option.

## Tasks

1. Review the CCLA signature record structure and the new (optional) `auto_create_ecla` column.
2. Develop a new API endpoint to allow CLA Managers to set/unset this value (input should be CLA Group ID, Organization ID).  Must validate that user is authorized to change CCLA signature record.
3. Add a new handler and service to process the request.
4. Ensure an event is generated to indicate the CLA Manager has enabled/disabled auto_create_ecla (must show up in the event log)
5. Add the ACS-CLI configuration to support this request (scope is project + organization) - same as the other CLA Manager endpoints.
6. Test and validate
7. Demonstrate to the team

## Acceptance Critieria

1. CLA Manager is able to enable/disable the `auto_create_ecla` feature via an API call.

## References

1. [Confluence Documentation](https://confluence.linuxfoundation.org/display/PROD/EasyCLA+-+Auto-Enable+Employee+Acknowledgments)

**Comment by thakurveerendras** [comment]
API Endpoint to Set/Unset the Auto-Enable Employee Acknowledgements is already added & implemented UI/UX using api point , So movie status review completed 

{{baseUrl}}cla-service/v4/signatures/company/:companyID/clagroup/:claGroupID/ecla-auto-create
![image](https://github.com/communitybridge/easycla/assets/75417507/ae537c6d-fdb6-4c4a-a13b-6413f44dc1d0)
![image](https://github.com/communitybridge/easycla/assets/75417507/fbac173c-5563-46a2-ae15-ec56a54fd0ac)
