### ISSUE TITLE
CCLA signature email address limit

### ISSUE THREAD

**Issue by jarias-lfx** [communitybridge/easycla#3649]
Ticket: [SUPPORT-13758](https://jira.linuxfoundation.org/browse/SUPPORT-13758)
Reporter: Jo Spencer
Organization: Sezoo
Project: Trust over IP (ToIP)

Issue Summary:

Jo Spencer was trying to initiate the Corporate CLA signature process for the organization Sezoo. The user was unable to continue the initial process due to a email address domain limitation. 

![image](https://user-images.githubusercontent.com/93140557/202012778-5e8cceff-f85f-49b0-8b9a-aebb3d798314.png)

The user email address is jo@sezoo.digital and we have a limit of {2,5}, digital has 7 digits. Making the API call to fail.

Is it viable to expand this limit to 10 digits?

**Comment by dealako** [comment]
Awaiting PR review
