### ISSUE TITLE
Update *.lfcla.com console landing pages

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#366]
**lfcla.com**
The link at the bottom of the page to "request to add project." Should we link to new intake form https://docs.google.com/forms/d/e/1FAIpQLSdnTk_9xjk7YoiX_FcPEqsFytsLMcT8OzYUbK6TsYopR1XhdA/viewform ?

**corporate.lfcla.com**
![corporatebox1](https://user-images.githubusercontent.com/46732999/69564922-e7a88400-0f81-11ea-9e5c-7d74a7da4abf.jpg)
The last line is struck through because it is out of order, the third box addresses this step.

**project.lfcla.com**
![Inkedprojectbox1_LI](https://user-images.githubusercontent.com/46732999/69565716-8d102780-0f83-11ea-9579-8570f6605c94.jpg)

The HERE link could go to https://docs.google.com/forms/d/e/1FAIpQLSdnTk_9xjk7YoiX_FcPEqsFytsLMcT8OzYUbK6TsYopR1XhdA/viewform

![projectbox2](https://user-images.githubusercontent.com/46732999/69566744-c9dd1e00-0f85-11ea-8d63-0f9db437b495.jpg)

The LFID should have been created during the application process or before by the user. So this whole bullet point could be rewritten to say "Log in to your Linux Foundation ID using the sign in link above. If you do not know your Linux Foundation ID, you can recover it by following the help links on that page."

**Comment by WillsonHG** [comment]
@dealako the changes on dev look good!

**Comment by WillsonHG** [comment]
These changes are not in prod yet.

**Comment by dealako** [comment]
This will be pushed to PROD on our next release.  Closing this issue as part of our product backlog meeting.
