### ISSUE TITLE
Wrong project name appears under email received for Approval Request for contributor

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3689]
Steps :

1. Login admin portal
2. Add Cla group at child project name "easycla finos child 1"
3. Add GitHub org
4. Cla enforced GitHub Repo
5. Go to company dashboard & sign cclas
6.  Go GitHub repo & create PR 
7. Now click on Not covered button
8. Select ecla process & request to cla manger for approval contributor  

Actual results : on email wrong project name i.e. easycla+finos+child+1 with link & it redirect user to foundation project
Expected : Project name should be "easycla finos child 1"

[https://app.zenhub.com/files/194341141/30e3906f-6a06-4167-a345-3cf8cf947d9a/download](https://app.zenhub.com/files/194341141/30e3906f-6a06-4167-a345-3cf8cf947d9a/download)
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/8d3f3d6b-8d2e-423b-9c77-188efa898b63)

**Comment by nickmango** [comment]
@thakurveerendras kindly review

**Comment by thakurveerendras** [comment]
Now correct child project name appears & user properly redirected to child project cla page , So making issue status QA-Done
Refer testing results on issue https://github.com/communitybridge/easycla/pull/3692
