### ISSUE TITLE
CloudFoundry CCLA and ICLA Template Update

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#369]
## Summary

CloudFounry template updates.

**Background**

CloudFoundry has a revised CCLA/ICLA template which includes changes to the instructions.

## User Story

As a project manager, I want to view the CCLA and ICLA templates from the project console.

## Acceptance Criteria

Updated templates for CF in prod. Able to view templates from the project console.

## References
Updated CCLA/ICLA here: https://jira.linuxfoundation.org/projects/SUPPORT/queues/custom/84/SUPPORT-700

**Comment by dealako** [comment]
@WillsonHG Uploaded new templates for CFF to S3 - now available/viewable in the Project Management Console.

Still todo: need to verify/validate the docusign field mappings

**Comment by WillsonHG** [comment]
The blank docs are viewable in the project console and the fields are aligned with docusign.
