### ISSUE TITLE
"Approval can be done at" paragraph need to update on "Approval Request for contributor" email 

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3692]
Steps :

1. Login admin portal
2. Add Cla group at child project name "easycla finos child 1"
3. Add GitHub org
4. Cla enforced GitHub Repo
5. Go to company dashboard & sign cclas
6. Go GitHub repo & create PR
7. Now click on Not covered button
8. Select ecla process & request to cla manger for approval contributor

**Issue 1**: Below paragraph need to modification as it not applicable after finos easycla update

- Approval can be done at https://lfx.dev.platform.linuxfoundation.org. **Visit any of the project(s)**:easycla finos child 1 and add the contributor to the approved list.

**Issue 2** : "easycla finos child 1" project link is wrong , it redirect user to foundation project & expected is it should redirect user to child named project

[https://app.zenhub.com/files/194341141/5d9919be-68aa-45c5-b78c-38005eaa5416/download](https://app.zenhub.com/files/194341141/5d9919be-68aa-45c5-b78c-38005eaa5416/download)

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/b63700a4-3a20-4230-bcf5-0d6ff4b711d4)

**Comment by dealako** [comment]
@nickmango I recommend we update the paragraph to read:

> CLA Managers can visit the EasyCLA corporate console page for {project name and link} and add the contributor to one of the approval lists.

Update the API logic to direct the user to the appropriate CLA corporate project page.  The logic should not default to the foundation view.

**Comment by nickmango** [comment]
> @nickmango I recommend we update the paragraph to read:
> 
> > CLA Managers can visit the EasyCLA corporate console page for {project name and link} and add the contributor to one of the approval lists.
> 
> Update the API logic to direct the user to the appropriate CLA corporate project page. The logic should not default to the foundation view.

Noted

**Comment by thakurveerendras** [comment]
Tested issue on dev site & found that paragraph is updated as mentioned above & user properly redirected to mentioned child project , So closing this issue
Refer screenshot 
![image](https://user-images.githubusercontent.com/75417507/207833450-f23264cb-f399-44ea-af37-b7694aadf696.png)
