### ISSUE TITLE
Update EasyCLA Landing Page Header

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#3701]
## Summary

Update EasyCLA Landing Page

## Background

The design team has updated the standard header and footer for the LFX products.  This task is to update the EasyCLA landing page navigation/header.

## Tasks

- [x] Update the EasyCLA landing page to leverage the updated/new header and footer (with navigation)
- [ ] Tests and validate the updates

## Acceptance Criteria

- The new LFX header, footer, and navigation are integrated with the EasyCLA landing page.

## References

**Comment by luismoriguerra** [comment]
code in review 
https://github.com/communitybridge/easycla-contributor-console/pull/296
https://github.com/communitybridge/easycla/pull/3700

**Comment by dealako** [comment]
Updated SSM configuration for DEV:
![Screenshot 2023-01-25 at 2 06 32 PM](https://user-images.githubusercontent.com/519609/214702413-fdfd4baa-e43b-4ebf-bac8-a48f6eb87d32.png)

**Comment by luismoriguerra** [comment]
https://dev.lfcla.com/#/
Dev stage implementation is completed.
@dealako , also we don't need the ssm param cla-lfx-header-{stage} anymore , we are getting the value from the same repository
https://github.com/communitybridge/easycla/blob/cc1e31a9db5491ca9d38a74ba5eb9c187d388618/cla-landing-page/src/environments/environment.prod.ts#L6

**Comment by dealako** [comment]
I need to deploy to prod.

**Comment by dealako** [comment]
Deployed to PROD:
![Screenshot 2023-02-06 at 8 07 22 AM](https://user-images.githubusercontent.com/519609/217023325-7bdc8859-4209-4254-8c60-dfc6c567d608.png)

Closing out this issue.
