### ISSUE TITLE
Bug when switching repositories between CLA Groups

### ISSUE THREAD

**Issue by jarias-lfx** [communitybridge/easycla#3762]
## Summary

Discovered an issue when switching repositories between CLA Groups, the **repository_project_id** in the back-end doesn't switch, causing the issue.

## Background

Due to the recent developed feature that allow the creation of CLA Groups when the parent project have an existing CLA Group. Part of the process is to switch the repositories from the parent CLA Group to a child CLA Group. Discovered an issue when switching repositories between CLA Groups, the **repository_project_id** in the back-end doesn't switch.

## Expected behavior

Disconnecting CLA Group from the parent project should update project_sfid | repository_sfdc_id | repository_project_id to their respective CLA Groups.

## Screenshots

N/A

## Environment

Please complete the following information:

* Environment:
  - [*] ALL
  - [ ] DEV
  - [ ] STAGING
  - [ ] PROD 
* Browser:
  - [*] Chrome/Brave
  - [ ] Firefox
  - [ ] Opera
  - [ ] Vivaldi
  - [ ] LibreWolf
  - [ ] SRware Iron
  - [ ] Dissenter
  - [ ] Slimjet
  - [ ] Midori
  - [ ] Edge
  - [ ] Lynx

**Comment by dealako** [comment]
@nickmango created PR: https://github.com/communitybridge/easycla/pull/3763. Merged - will need to test in DEV @thakurveerendras.

**Comment by thakurveerendras** [comment]
Tested issue on dev site & found that repository_sfdc_id remain same after switch project , So rejecting this tickets 
  

- **Before switch** :

project_sfid |  a092h000004x5tVAAQ
`repository_sfdc_id | a092h000004x5tVAAQ`
repository_project_id | 9976cd29-aa87-4699-b03d-499bef7287a3

- **After disable cla enforced**  : Above field removed 

- **After switch** : 

project_sfid |  a092h000004x5taAAA
`repository_sfdc_id | a092h000004x5tVAAQ`
repository_project_id | 88ee12de-122b-4c46-9046-19422054ed8d

![image](https://user-images.githubusercontent.com/75417507/219653303-97525560-fe47-484c-873c-44bd1a238dee.png)
![image](https://user-images.githubusercontent.com/75417507/219653415-cf72d04b-98ce-4228-ac2b-804e34c99370.png)

**Comment by jarias-lfx** [comment]
The repository_sfdc_id is expected to remain the same as is for parent project. The main issue was for repository_project_id, which is changing successfully. This can be moved as Done once deployed to PROD.
