### ISSUE TITLE
Update GitLab cla gated bot style similar to GitHub

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3769]
Steps :

1. Login admin portal
2. Add cla group on project
3. Add GitLab group & cla enforced GitLab project
4. Go to GitLab & create MR

Actual results : 
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/96423792-6b63-421c-839a-9cc58fc4874b)
Expected : 
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/24ccd77c-d02d-405c-8696-c9fe26c08799)

**Comment by nickmango** [comment]
@thakurveerendras with GitLab API email and name are the supported fields in the MR payload returned with no functionality in fetching the username detail

**Comment by thakurveerendras** [comment]
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/4590a968-c0f3-4ed4-bfca-eeeff03239f9)

**Comment by thakurveerendras** [comment]
As discussed in easycla Standup call, current implementation is okay for GitLab. @nickmango will investigate below case
1. Commit id is missing 
2. @userName link is missing
