### ISSUE TITLE
Unable to add approval criteria when there is a parent CLA Group

### ISSUE THREAD

**Issue by jarias-lfx** [communitybridge/easycla#3779]
## Summary

The new Feature where a CLA Group can be created for a child project when there is an existing CLA Group for the parent project. In the CLA Corporate Console, the CLA Managers are unable to add approval criteria.

Created: [LFX-3206](https://jira.linuxfoundation.org/browse/LFX-3206)

## Background

1- Access the CLA Corporate Console under The Linux Foundation as CLA Manager
2- Select FDC3 project from the search option
3- Add approval Criteria
4- The CLA Corporate Console provides error: "Cannot read properties of undefined (reading 'claGroupId')"

## Expected behavior

The approval criteria is added accordingly

## Screenshots

![image](https://user-images.githubusercontent.com/93140557/218510936-bbb0edb2-3a88-4400-9c54-62f1793f25e1.png)

## Environment

* Environment:
  - [x] ALL
  - [ ] DEV
  - [ ] STAGING
  - [ ] PROD 
* Browser:
  - [x] Chrome/Brave
  - [ ] Firefox
  - [ ] Opera
  - [ ] Vivaldi
  - [ ] LibreWolf
  - [ ] SRware Iron
  - [ ] Dissenter
  - [ ] Slimjet
  - [ ] Midori
  - [ ] Edge
  - [ ] Lynx

## Additional Context

After investigating further. This is related to the issue reported on https://github.com/communitybridge/easycla/issues/3773. The foundation_sfid was changed to the child project. However, it seems the CLA Corporate Console is unable to match the SFID. 

## Assumptions

The reason for this is: changing the value for foundation_sfid to the parent project, the flow in the CLA Corporate Console works, the approval criteria can be added, but if we do so, the issue reported on *https://github.com/communitybridge/easycla/issues/3773* is triggered.

**Comment by dealako** [comment]
@nickmango let's diagnose and post an update for this ticket to be shared for standup on Feb 16, 2023.

**Comment by dealako** [comment]
Related to CLA Corporate Console JIRA issue: https://jira.linuxfoundation.org/browse/LFX-3206

**Comment by thakurveerendras** [comment]
Tested issue on dev site and found that I am able to add user in approval contributor list using GitHub/GitLab user & email 

Refer video clip : 

https://user-images.githubusercontent.com/75417507/220613971-61b852c6-3e40-4045-a127-492bff6df9c5.mp4
