### ISSUE TITLE
Redirect URL in the contributor flow is not properly structured when there is a parent project CLA Group

### ISSUE THREAD

**Issue by jarias-lfx** [communitybridge/easycla#3780]
## Summary

Using the contributor flow once the cla-manager-designee role is added, the flow will re-direct to the CLA Corporate Console, the redirect URL is structured to use the SFID of the project. Due to the new feature where we can create child project CLA Groups when there is an existing parent project CLA Group, the URL in these scenarios is not working.

## Background

1- Access the CLA contributor flow: https://contributor.easycla.lfx.linuxfoundation.org/#/corporate-dashboard/a49a37c7-1506-4cc8-9080-5bc34d675f85/04581041-79ab-401b-96be-6b44c85c3a46
2- Select Corporate
3- Search for organization
4- Select YES to become cla manager
5- Select Proceed to redirect to the CLA Corporate Console
6- The URL is structured as https://organization.lfx.linuxfoundation.org/foundation/a092M00001IkUafQAF/cla. where a092M00001IkUafQAF is the child project SFID. Causing a timeout.

## Expected behavior

The redirection should provide the URL as: https://organization.lfx.linuxfoundation.org/foundation/a092M00001JwBlEQAV/project/a092M00001IkUafQAF/cla

## Screenshots

Issue:
![image](https://user-images.githubusercontent.com/93140557/218524285-7c73126d-fb02-4e12-8223-451aea894aa5.png)

Expected Behavior or how it should be:
![image](https://user-images.githubusercontent.com/93140557/218524233-038d066c-609d-4144-8e29-c00e64897f13.png)

## Environment

* Environment:
  - [x] ALL
  - [ ] DEV
  - [ ] STAGING
  - [ ] PROD 
* Browser:
  - [x] Chrome/Brave
  - [ ] Firefox
  - [ ] Opera
  - [ ] Vivaldi
  - [ ] LibreWolf
  - [ ] SRware Iron
  - [ ] Dissenter
  - [ ] Slimjet
  - [ ] Midori
  - [ ] Edge
  - [ ] Lynx

**Comment by dealako** [comment]
Created and deployed PR to the DEV environment: https://github.com/communitybridge/easycla-contributor-console/pull/321

**Comment by dealako** [comment]
@thakurveerendras ready for validation.

**Comment by thakurveerendras** [comment]
Tested issue on dev site & found that it is fixed as expected, So making issue status QA-Done

- Now user properly redirected to child project when parent project have cla group too : https://lfx.dev.platform.linuxfoundation.org/foundation/a092h000004x5tVAAQ/project/a092h000004x5taAAA/cla
- User properly redirected to parent project from contributor console : https://lfx.dev.platform.linuxfoundation.org/foundation/a092h000004x5tVAAQ/cla
- User properly redirected to cla grandchild project via contributor console : https://lfx.dev.platform.linuxfoundation.org/foundation/a092h000004x5tVAAQ/project/a092h000004xCR2AAM/cla
- User properly redirected to standalone project cla page properly via  contributor console :https://lfx.dev.platform.linuxfoundation.org/foundation/a092h000004x5sBAAQ/cla

Refer video clip : 
**Child project** 
[3780_Child.webm](https://user-images.githubusercontent.com/75417507/218718512-d35b3549-2c99-45bf-b496-6cf083fd8fa5.webm)

**Parent project :**
 
[3780_ParentProject.webm](https://user-images.githubusercontent.com/75417507/218718793-16d1422f-5d54-478f-bcab-8455196d97f4.webm)

**Grand child project :**
[3780_Grandchild.webm](https://user-images.githubusercontent.com/75417507/218718971-2568a369-e5d7-444b-9c4b-2adb801e65b3.webm)

**Standalone project :**

[3780_standalone.webm](https://user-images.githubusercontent.com/75417507/218721471-d311c800-7bd7-41dd-b711-202a7c4901ad.webm)

**Comment by jarias-lfx** [comment]
Confirmed fix in PROD, using a different test account. The URL provided was: https://organization.lfx.linuxfoundation.org/foundation/a092M00001JwBlEQAV/project/a092M00001IkUafQAF/cla
