### ISSUE TITLE
Unable to create CLA Groups under LF Projects, LLC umbrella

### ISSUE THREAD

**Issue by jarias-lfx** [communitybridge/easycla#3786]
## Summary

Trying to create a CLA Group for one of the child projects from LF Projects, LLC fails with a 400 error:
```
URL: https://projectadmin.lfx.linuxfoundation.org/project/a092M00001MaGqmQAF/tools/easycla/create-group

Time: February 14, 2023 at 11:32:43 AM GMT-6

Error: {"headers":{"normalizedNames":{},"lazyUpdate":null},"status":400,"statusText":"OK","url":"https://pcc-bff.platform.linuxfoundation.org/production/api/cla-services/create-group","ok":false,"name":"HttpErrorResponse","message":"Http failure response for https://pcc-bff.platform.linuxfoundation.org/production/api/cla-services/create-group: 400 OK","error":{"status":400,"stack":"","details":null,"message":"EasyCLA - 400 Bad Request - validation failure - one of the input projects is the root Linux Foundation project","code":"400","requestId":"93d772d0-ac8d-11ed-bba4-275ec91db05b","data":{"ccla_enabled":true,"ccla_requires_icla":false,"cla_group_name":"Nephio CLA Group","cla_group_description":"CLA Group for Nephio","foundation_sfid":"a092M00001IkOVVQA3","icla_enabled":true,"project_sfid_list":["a092M00001MaGqmQAF"],"template_fields":{"MetaFields":[{"description":"Project's Full Name.","name":"Project Name","templateVariable":"PROJECT_NAME","value":"Nephio Project"},{"description":"The Full Entity Name of the Project.","name":"Project Entity Name","templateVariable":"PROJECT_ENTITY_NAME","value":"Nephio Project a Series of LF Projects, LLC"},{"description":"The E-Mail Address of the Person managing the CLA. ","name":"Contact Email Address","templateVariable":"CONTACT_EMAIL","value":"cla-admin@nephio.org"}],"TemplateID":"fb4cc144-a76c-4c17-8a52-c648f158fded"}}}} 

Additional Information: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
```

## Background

Creating Nephio Project which is under LF Projects, LLC umbrella is failing
1- Access EasyCLA for Nephio Project in the PCC: https://projectadmin.lfx.linuxfoundation.org/project/a092M00001MaGqmQAF/tools/easycla/overview
2- Select Add new CLA Group
3- Fill all the necessary information: Name, Description, ICLA, CCLA, Template and email
4- Select Finish
5- The page returns the 400 error

## Expected behavior

The CLA Group should be created

## Screenshots

![image](https://user-images.githubusercontent.com/93140557/218829519-99bd50f1-031a-49fd-ab55-21d2a8f7bb1b.png)

## Environment

* Environment:
  - [ ] ALL
  - [ ] DEV
  - [ ] STAGING
  - [x] PROD 
* Browser:
  - [x] Chrome/Brave
  - [ ] Firefox
  - [ ] Opera
  - [ ] Vivaldi
  - [ ] LibreWolf
  - [ ] SRware Iron
  - [ ] Dissenter
  - [ ] Slimjet
  - [ ] Midori
  - [ ] Edge
  - [ ] Lynx

## Additional Context

Based on previous information, the LF Projects, LLC. project is a hosting entity and CLA Groups should not be linked to it. The problem is, creating a CLA Group for one of the "child" projects the create-group function will call LF Projects, LLC. foundation_sfid causing the error message.

If possible and for discussion, we should exclude LF Projects, LLC foundation_sfid during the create-group call.

**Comment by dealako** [comment]
There seems to be logic that we added a long time ago to prevent projects from creating new CLA Groups directly under the parent projects of "The Linux Foundation" and "LF Projects, LLC". I don't recall why we added this logic - it may have been related to the old consoles.

We should review if/when this is called during the CLA creation: https://github.com/communitybridge/easycla/blob/main/cla-backend-go/v2/project-service/client.go#L321-L352

Here is the project structure:
![Screenshot 2023-02-24 at 10 26 21 AM](https://user-images.githubusercontent.com/519609/221263073-e53cdc67-d4cf-4997-b891-5b8dfb012229.png)

**Comment by dealako** [comment]
Deployed to DEV. Ready for QA.

**Comment by dealako** [comment]
Deployed to PROD. Ready for QA.

**Comment by jarias-lfx** [comment]
Update:
- Was able to create Nephio CLA Group in the PCC https://projectadmin.lfx.linuxfoundation.org/project/a092M00001MaGqmQAF/tools/easycla/overview
- No issues found during the Group creation

New Issues in the CLA Corporate Console:
- When trying a test signature in the CLA Corporate Console found:
1. Selectin Nephio Project from the Dashboard it redirects to the following URL: https://organization.lfx.linuxfoundation.org/foundation/a092M00001IkOVVQA3/project/a092M00001MaGqmQAF/cla, the page never loads:
![image](https://user-images.githubusercontent.com/93140557/223522424-cf1763cd-75ae-4172-9697-beb8e6c5f925.png)

2. When using the left side search option it redirects to the following URL: https://organization.lfx.linuxfoundation.org/foundation/a0941000002wBz9AAE/project/a092M00001MaGqmQAF/cla, this page loads correctly:
![image](https://user-images.githubusercontent.com/93140557/223522781-6196e6c3-793d-40ba-a960-4b7c4a80ec74.png)

3. When trying to sign using the URL https://organization.lfx.linuxfoundation.org/foundation/a0941000002wBz9AAE/project/a092M00001MaGqmQAF/cla, the process fails with:
```
{"data":{"requestCorporateSignature":{"code":400,"message":"provided project is not associated with cla_group","success":false,"data":null,"__typename":"RequestCorporateSignatureResult"}}}
```
![image](https://user-images.githubusercontent.com/93140557/223522134-fcda7083-4aab-459a-9cb5-48df775a25bd.png)

**Comment by jarias-lfx** [comment]
Created UI Issue [LFX-3212](https://jira.linuxfoundation.org/browse/LFX-3212)

**Comment by jarias-lfx** [comment]
Confirmed issues have been resolved in the PCC and the CLA Corporate Console for LF Projects, LLC projects ([LFX-3212](https://jira.linuxfoundation.org/browse/LFX-3212)). Closing this issue.
