### ISSUE TITLE
GitLab Merge request remain not covered after docu-signed 

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3795]
Steps :

1. Go to gated Easycla PR
2. Click on Not covered
3. Proceed as an Individual Contributor 
4. Click on Sing CLA
5. Fill docusign pdf form 

Actual results : GitLab Merge request remain not covered after docu-signed 

Refer video clip :
 https://images.zenhubusercontent.com/194341141/464fc3e1-b6a5-432d-8939-b673edf2d172/notcovered.mp4

**Comment by thakurveerendras** [comment]
Tested issue on dev site & found that it is reproducible as reported, So making issue status QA-Failed
Refer video clip : 

https://user-images.githubusercontent.com/75417507/220549895-683583ca-bb3a-4952-93e8-56cfbe8f12b8.mp4

**Comment by thakurveerendras** [comment]
MR : https://gitlab.com/marsgitlabgroup/repo01/-/merge_requests/32

**Comment by thakurveerendras** [comment]
Tested issue with multiple user & found that it is working fine except veerendrat user

- Added separate tickets for failed user : https://app.zenhub.com/workspaces/easycla-5ed619832c71a855a76ef404/issues/gh/communitybridge/easycla/3816

Refer screenshot for more details : 
![image](https://user-images.githubusercontent.com/75417507/221578106-c1843128-3936-499f-9051-da320c6abd9b.png)


![image](https://user-images.githubusercontent.com/75417507/221577929-54df9ba2-703f-4e1c-bed7-c6c5bdc1b431.png)

**Comment by shyam-goshike** [comment]
@thakurveerendras confirmed its working as expected. Hence closing
