### ISSUE TITLE
PCC shows "No CLA data available" for Approved Contributors

### ISSUE THREAD

**Issue by jarias-lfx** [communitybridge/easycla#3806]
## Summary

Accessing the PCC to check/confirm the Approved Contributors for an organization with CCLA signed, the PCC shows "No CLA data available". 
Issue was reported to PCC on ticket: [PCC-2699](https://jira.linuxfoundation.org/browse/PCC-2699)
After further investigation it seems the issue is with EasyCLA API.

## Background

To reproduce the issue.
1- Access the PCC for any project: https://projectadmin.lfx.linuxfoundation.org/project/a092M00001JwBlEQAV
2- Select EasyCLA
3- Select Signatures
4- Select Signed CCLAs
5- Search or select a listed organization
6- Expand "View List" under Approved Contributors
7- The PCC shows No CLA data available (See screenshot below)

## Expected behavior

The PCC should list the approved contributors for the organization under the project.

## Screenshots

![image](https://user-images.githubusercontent.com/93140557/220941628-6e4db2ca-8053-4e46-b0d9-544c08c0e2ab.png)

## Environment

* Environment:
  - [ ] ALL
  - [ ] DEV
  - [ ] STAGING
  - [x] PROD 
* Browser:
  - [x] Chrome/Brave
  - [ ] Firefox
  - [ ] Opera
  - [ ] Vivaldi
  - [ ] LibreWolf
  - [ ] SRware Iron
  - [ ] Dissenter
  - [ ] Slimjet
  - [ ] Midori
  - [ ] Edge
  - [ ] Lynx

## Additional Context

After further investigation, we have an organization on which the auto-acknowledgement flag was enabled: Goldman Sachs & Co. LLC. The PCC shows the approved contributors just for the ones added after the auto-acknowledgment was enabled:
![image](https://user-images.githubusercontent.com/93140557/220942357-7ec76859-3f82-41ed-ad49-e53db678e942.png). The previous approved contributors for the organization don't show as expected.

**Comment by thakurveerendras** [comment]
Tested issue on dev site & found that it is not reproducible as reported 
**Case 1 : When ecla-auto-create is false**

- User added on approval list & not available on contributor list

![image](https://user-images.githubusercontent.com/75417507/222113014-056318ea-1866-4f5c-a903-ce16dd84bf16.png)

- After add user contributor console by complete ECLA flow 

![image](https://user-images.githubusercontent.com/75417507/222112771-1f61cc30-87ff-4c32-b1a8-eddb0500a40e.png)
![image](https://user-images.githubusercontent.com/75417507/222112900-8510fc37-8587-4d45-8f33-3c195ffebf69.png)

**Case 2 : After enabled ecla-auto-create options to organization** 

- Note that few user added under approval list before ecla-auto-create options enabled for organization ,After enabled all approval list user added automatically on contributor list (Refresh page for get latest records)

![image](https://user-images.githubusercontent.com/75417507/222114369-e2b1c194-654c-47c3-91e2-34a957121f38.png)
![image](https://user-images.githubusercontent.com/75417507/222114442-d2ec0663-540c-48ca-add0-38faef075653.png)

**Comment by thakurveerendras** [comment]
![image](https://user-images.githubusercontent.com/75417507/222115799-16de3b47-87e8-4a18-a6d1-cdc590c39e1f.png)
