### ISSUE TITLE
GitLab Merge request remain not covered after docu-signed on veerendrat user

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3816]
GitLab user details :

- id : 9810034
- Full name : vthakur singh
- user : veerendrat
- Email : vthakur@contractor.linuxfoundation.org

Steps :

1. Go to gated Easycla PR : https://gitlab.com/marsgitlabgroup/repo01/-/merge_requests/32
2. Click on Not covered
3. Proceed as an Individual Contributor
4. Click on Sing CLA
5. Fill docusign pdf form

Actual results : GitLab Merge request remain not covered after docu-signed
Note that ICLA records created for same user at PCC
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/93bef14a-7855-4cec-bf66-6d48377ab62d)
https://images.zenhubusercontent.com/194341141/2469f248-fa77-40a3-bf5a-f1d0f2b620cd/easyclacovered.mp4

**Comment by thakurveerendras** [comment]
Able to replicate issue with below steps 

Steps :

1. Remove user records from cla-Dev-users table
2. Create new Merge Request
3. Click on not covered

> - I select Individual Acknowledgement options
> - I click on "Sign CLA" button 
> - See-Docu-signed open
> - Fill Docu-signed prompt & do not click on finish button
> - Close docu-signed form (incomplete state) 

9. Now Repeat step 3 & complete ICLA process (means click on finish button at docu-signed form)

Results obtains

> - At GitLab-MR remain not covered : https://gitlab.com/sungitlabtest/repo1/-/merge_requests/7
> - PCC : Proper ICLA record created at signature table for user

> - AWS : Two record created
> - One records with email / full name and without GitLab id
> - 2nd records with GitLab id .email address/GitLab user

> - Gitlab User : veerendrat email : [vthakur@contractor.linuxfoundation.org](mailto:vthakur@contractor.linuxfoundation.org)

![image](https://user-images.githubusercontent.com/75417507/223084115-cfcbca5e-1d96-415a-9a2e-35408b64d576.png)
![image](https://user-images.githubusercontent.com/75417507/223084246-765b4054-81fc-4414-a267-aa750789a791.png)
![image](https://user-images.githubusercontent.com/75417507/223085287-bf2e2b06-9ebc-4953-b035-f788a01681f1.png)
![image](https://user-images.githubusercontent.com/75417507/223085437-871eaf32-519c-4668-b6ad-e4d15e9a23ba.png)

**Comment by thakurveerendras** [comment]
Issue is still reproducible with below steps 

- Precondition : Remove user records from cla-Dev-users table

Steps :

1. Login company dashboard  
2. Singed cclas 
3. Create GitHub PR (easycla Gated) : https://github.com/Sun-lfxfoundationOrgTest/Repo01/pull/1
4. Click on Not covered button at GitHub PR
5. See-User records created with email address at cla-Dev-users table
6. Create GitLab Merger request  (easycla Gated) : https://gitlab.com/sungitlabgroup/repo01/-/merge_requests/1
7. Click on Not covered button at GitLab MR
8. Complete ICLA flow 

**Actual results** : 

- GitLab user created at cla-Dev-users table but still MR is not gated 
- ICLA records created at PCC signature table  

Refer GitLab user details : 

- User : veerendrat
- Email : vthakur@contractor.linuxfoundation.org

Refer video clip : 

https://user-images.githubusercontent.com/75417507/224542305-717e5472-e7a0-4d66-8099-7978c978225c.mp4

**Comment by jarias-lfx** [comment]
@nickmango @thakurveerendras would you confirm if the issue here is during the gitlab user search is: 
if you have another user in the users table with lf_username, GitLab will use that user instead of the one with GiltLab account information, also, the current user is not getting updated with the GitLab account information when trying to sign, it will just create a new record. Due to this, even signed EasyCLA check won't pass for GitLab?

**Comment by nickmango** [comment]
@jarias-lfx this happens to be the case. Currently the payload from gitlab upon gating by easycla returns author details of email and name which isnt sufficient enough to load the gitlab_id details. Trying to handle that use case as its failing on the user search

**Comment by nickmango** [comment]
@thakurveerendras I followed the above steps and was able to pass using the same github account. The search is finding the right user 
Kindly reverify

![Screenshot 2023-03-16 at 20 04 09](https://user-images.githubusercontent.com/81645226/225697232-d36d778d-20e1-4ab2-937a-1e6acf873403.png)

**Comment by thakurveerendras** [comment]
Hello @nickmango 
Issue is with GitLab & it is still reproducible as reported steps above. 
 Refer MR : https://gitlab.com/sungitlabgroup/repo01/-/merge_requests/7
Kindly refer video clip : https://images.zenhubusercontent.com/194341141/0e8e9d51-4d37-4457-8a17-f1c89c0df9b5/2816.mp4

**Comment by thakurveerendras** [comment]
Tested issue with the steps mentioned above & found that issue is not reproducible & now MR are properly gated & covered when singed ICLA. So making issue status QA-Done

- Refer MR for more details : https://gitlab.com/sungitlabgroup/repo01/-/merge_requests/20
- Refer video clip : 
https://images.zenhubusercontent.com/194341141/a93ccc36-bb4b-432a-b01e-48655f7e7a6d/3816__2_.mp4

**Comment by shyam-goshike** [comment]
Deployed to PROD
