### ISSUE TITLE
Child project cla group should hide/remove for parent project when parent project removed from child project

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3820]
Related PCC tickets : https://jira.linuxfoundation.org/browse/PCC-2553 
Project setup 

- Parent project A
- Child 1 project 
- Child 2 project

Steps :

1. Login admin portal
2. Add CLA group at child 1 project , refer screenhot
3. At Child 1 project 
4. Go to Basic –> Legal page
5. Edit legal page
6. Update parent project to LF research
7. Save changes
8. At parent project A
9. Go to easycla page

Actual results : CLA group created for child project still visible 

Expected :CLA group should remove at parent project after step 3
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/739f053b-73f8-432e-83a1-c30ad66f5ccc)
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/48c45e70-8773-4a5e-b474-38c7a7297059)
https://images.zenhubusercontent.com/194341141/531e72fd-7936-42ba-9cbd-64a6563f3f68/untitled__1_.mp4

**Comment by thakurveerendras** [comment]
Hello @shyam-goshike , @nickmango 
Unable to verify this issue due to OPA issue reported at PCC

- PCC-2859 : Unable to update project details at basic & legal edit prompt

**Comment by mlehotskylf** [comment]
@thakurveerendras can you please confirmed this has been tested? If yes then please change the status. Thanks!

**Comment by thakurveerendras** [comment]
Tested issue on dev site & found that it is fixed as expected, So closing this issue 

![image](https://github.com/communitybridge/easycla/assets/75417507/ae3d07cc-14b4-49a8-b530-ef5ad5cc927e)

![image](https://github.com/communitybridge/easycla/assets/75417507/f77865ff-c712-4bd6-9d58-315b025b0d27)
