### ISSUE TITLE
"This page isn't working" appears on very first when I click on not covered button after clear user records from cla-dev-users

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3833]
Steps :

1. Clear user records from cla-dev-users table
2. Go to GitLab MR 
3. Click on Not covered button

Actual results :  "This page isn't working" appears
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/a7d83d81-836c-472e-a07a-842cd9fa6e4b)
![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/484b134c-0799-44d6-9d25-79b73045455d)

**Comment by nickmango** [comment]
@thakurveerendras when you cleared the user records did you happen to delete the corresponding signature records that had the associated user_ids ?
Could you as well add details for the MR and user_id youd deleted ?

**Comment by thakurveerendras** [comment]
Retested issue on dev site & found that it is not reproducible as reported, look like it automatic fix after fix of some GitLab issue , So closing this issue as can't reproducible 

Refer video clip: [3833.webm](https://user-images.githubusercontent.com/75417507/229414514-a2a6ee8d-c96e-4775-aa68-80d234fa5e8a.webm)
