### ISSUE TITLE
EasyCLA status not being updated on GitHub

### ISSUE THREAD

**Issue by nikhita** [communitybridge/easycla#3843]
## Summary

The EasyCLA status on GitHub is stuck in a `EasyCLA Expected — Waiting for status to be reported ` state in https://github.com/kubernetes/kubernetes/pull/116370

## Background

Please see https://github.com/kubernetes/kubernetes/pull/116370. We tried the following but they didn't help:

- Triggering the EasyCLA check through `/easycla`
- Closing and reopening the PR
- Force pushing a new commit on the PR

## Expected behavior

EasyCLA status context should be set.

## Screenshots

![Screenshot 2023-03-09 at 10 27 01 AM](https://user-images.githubusercontent.com/16105680/223922999-fb51d79a-9c5e-4847-80e3-1fd88689cdb7.png)

cc @mrbobbytables @MadhavJivrajani

**Comment by MadhavJivrajani** [comment]
Another instance of this: https://github.com/kubernetes/autoscaler/pull/5576

**Comment by WillsonHG** [comment]
Hello @MadhavJivrajani  and @nikhita Thank you for reporting this issue, we are looking into this today with priority.

**Comment by nikhita** [comment]
Thanks for the update, @WillsonHG!

**Comment by WillsonHG** [comment]
As an update, @nikhita @MadhavJivrajani  we are seeing the problem from those PRs opened by new contributors who don't yet have an EasyCLA ack on file, it is failing to grab all of the user information from GitHub. We are able to manually supplement the user info for those PRs we know about that are failing - https://github.com/kubernetes/autoscaler/pull/5576 and https://github.com/kubernetes-sigs/kwok/pull/368 are now showing EasyCLA statuses.

We are hoping to have a hotfix up shortly for this. In the meantime, if there are any blocking that you know of, we can fix those manually. Thanks for your patience!

**Comment by nikhita** [comment]
For both PRs, we had manually applied the `cncf-cla: no` to stop the Kubernetes cla bot checker from spamming the PR with a comment triggering easycla.

I removed the manually applied label and commented with `/easycla`. The bot re-added the `cncf-cla: no` label and the status was updated 👍 

I wanted to confirm if this was expected per:

> don't yet have an EasyCLA ack on file, it is failing to grab all of the user information from GitHub. We are able to manually supplement the user info for those PRs we know about that are failing 

Does these mean that these contributors have signed the CLA and you've supplemented this info for the specified PRs? If yes, I would expect the bot to add the `cncf-cla: yes` label.

**Comment by WillsonHG** [comment]
@nikhita  it would be users who have NOT signed a cla yet, so the :no status is expected. 

We have tested and deployed a hotfix and are monitoring these results in production. We think this is fixed, but please let us know if you see any new 'expected' status today, or see any that still need updates. We're also trying to check for any current PRs that need an update.

**Comment by dealako** [comment]
This issue should now be resolved.

**Comment by shyam-goshike** [comment]
Closing as per @dealako

**Comment by MadhavJivrajani** [comment]
@WillsonHG @dealako @shyam-goshike - this seems to be happening again, please see https://github.com/kubernetes-sigs/cloud-provider-kind/pull/1

**Comment by shyam-goshike** [comment]
@thakurveerendras can you please review this issue. 
CC: @nickmango @jarias-lfx

**Comment by thakurveerendras** [comment]
Tested issue on dev site with fresh user(user don't have any records at dynamodb) and found that GitHub PR are properly Gated & covered after docu signed (ICLA) process , 

@nickmango , Kindly check why it is not working on Prod 

- PR : https://github.com/sun-test-org/repo1/pull/9
- GitHub User : vrthakur
- Kindly refer video clip for more details : 

https://user-images.githubusercontent.com/75417507/227938851-32e6004e-6348-4168-8ded-82a04c72975c.mp4

**Comment by nickmango** [comment]
@MadhavJivrajani upon investigation I noted that this repository has not been enabled hence the PR check fails
cc @thakurveerendras @shyam-goshike

**Comment by mrbobbytables** [comment]
@nickmango we haven't had to manually enable it on a repo before,  do you know why that is happening now?

**Comment by mrbobbytables** [comment]
@nickmango we haven't had to manually enable it on a repo before,  do you know why that is happening now?

**Comment by mrbobbytables** [comment]
@nickmango we haven't had to manually enable it on a repo before,  do you know why that is happening now?

**Comment by mrbobbytables** [comment]
@nickmango we haven't had to manually enable it on a repo before,  do you know why that is happening now?

**Comment by mrbobbytables** [comment]
@nickmango we haven't had to manually enable it on a repo before,  do you know why that is happening now?

**Comment by mrbobbytables** [comment]
Okay, github freaked out there lol sorry for the multiple posts

**Comment by nickmango** [comment]
@MadhavJivrajani upon investigation I noted that this repository has not been enabled hence the PR check fails
cc @thakurveerendras @shyam-goshike 

> Okay, github freaked out there lol sorry for the multiple posts

No i

> Okay, github freaked out there lol sorry for the multiple posts

@mrbobbytales no worries. Anyhow it appears via the project console. PCC someone could have mistakenly disabled the repo as theres the feature of enable/disable. A solution would be to just search and enable the repo viz PCC

**Comment by nickmango** [comment]
Noted. This should have been resolved though @mrbobbytables

**Comment by nikhita** [comment]
> Additionally, we would require assistance from the Community to confirm if the installation id 20677499 is correctly attributed to EasyCLA https://github.com/organizations/kubernetes-sigs/settings/installations/20677499, if so, we would like to confirm if all the repos or specific repos are selected. 


Here you go:

<img width="1009" alt="Screenshot 2023-03-27 at 8 11 14 PM" src="https://user-images.githubusercontent.com/16105680/227974123-b9b7700a-efa4-4801-a553-d49470fe3719.png">

**Comment by jarias-lfx** [comment]
Thank you @nikhita
