### ISSUE TITLE
Add "/easycla" trigger for GitLab

### ISSUE THREAD

**Issue by jarias-lfx** [communitybridge/easycla#3844]
## Summary

Please add "/easycla" action for GitLab

## Background

The use of "/easycla" comment in GitHub is a critical feature used by maintainers, contributors and support to trigger EasyCLA bot when required. The use of this feature is very important to have for GitLab as well as we would have no other way to trigger EasyCLA checks in a MR.

**Comment by dealako** [comment]
1. Need to ensure we are subscribed to receive comment events from GitLab via the webhook
2. Need to add a comment handler routine to review the comments to determine if the current/most-recent comment includes the `/easycla` command.
3. If the `/easycla` command is recognized, then the logic should execute the merge request check logic which would re-evaluate the authorized users and ultimately update the GitLab status on the GitLab UI.

**Comment by thakurveerendras** [comment]
As confirmed by @jarias-lfx over slack , issue is properly fix & deployed to production too, So moving issue status Done
![image](https://user-images.githubusercontent.com/75417507/229024534-0b7e411f-32b1-45b6-933a-e0ad4c0f2a26.png)

**Comment by shyam-goshike** [comment]
Closing as per comments from @jarias-lfx
