### ISSUE TITLE
Corollary to #383 Allow CCLA Managers to view (read only access) CCLA Managers (from their company) for other projects 

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#385]
## Summary

Issue #383 is fixing the case where CCLA Managers from a particular company can whitelist corporate contributors from their company that are affiliated to projects other than their own. We also want to allow CCLA Managers to see the names of CCLA Managers from their company assigned to other projects. This will be a read only access without any whitelist or update permission.

## Background

This is an enhancement request

## User Story

As a CCLA Manager I want to see who all are other CCLA Managers from my company that are assigned to different projects..

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

**Comment by nirupamav** [comment]
Since this ticket is tested as part of #383, closing this ticket
