### ISSUE TITLE
CLA Corporate Console - enhance message when unable to access console

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#3854]
To access the CLA Corporate Console, a user must be associated with their company via openprofile.dev and that company must have signed a previous CLA. Once these two criteria are satisfied, a user can access the console. If the above is not met, the user is shown this message.
![image](https://user-images.githubusercontent.com/46732999/224727667-ee5bc9a9-6bb0-475f-9793-8b70f0c5fbc1.png)

Sorry your permissions don't seem to be right please click [here](https://jira.linuxfoundation.org/servicedesk/customer/portal/4) to file a support ticket

We should enhance this error message to be more descriptive. A suggestion from Mao is : Your org is still not enrolled on EasyCLA, for security reasons, we kindly ask you to raise a ticket on <URL>.

I think we should also mention to the user that they need to make sure they've associated themselves with their company in their profile at openprofile.dev.

**Comment by WillsonHG** [comment]
The CLA Corporate console is accessible to users who have associated themselves with their organization at openprofile.dev. If you have done so and you are seeing this message, then your organization is not yet enrolled in EasyCLA. For security, please click here to open a support ticket.

**Comment by nickmango** [comment]
@ah-med could you kindly look into this ?
