### ISSUE TITLE
CHIPS Alliance repos not showing in PCC.

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#3857]
In Production:
We have two CHIPS Alliance CLA groups. When clicking on 'Manage' on their respective sections, we get no repos showing for them.
https://projectadmin.lfx.linuxfoundation.org/project/a092M00001KWmbPQAT/tools/easycla/repositories/a092M00001KWmbPQAT#5a74c3ca-8c50-4b32-8ec2-f94bda5481dd
We have 3 repos installed on this group. 

https://projectadmin.lfx.linuxfoundation.org/project/a092M00001KWmbUQAT/tools/easycla/repositories/a092M00001KWmbUQAT#c592af39-2950-417f-826a-278f7fe36e86
We have one repo installed on this group.

**Comment by dealako** [comment]
@nickmango - assigned to you, please diagnose and report your findings here.

**Comment by nickmango** [comment]
@dealako  On checking via postman I happen to get the repositories 
For https://projectadmin.lfx.linuxfoundation.org/project/a092M00001KWmbPQAT/tools/easycla/repositories/a092M00001KWmbPQAT#5a74c3ca-8c50-4b32-8ec2-f94bda5481dd 

`{
    "list": [
        {
            "date_created": "2021-05-06T21:43:13Z",
            "date_modified": "2021-05-06T21:43:13Z",
            "enabled": true,
            "note": "created on 2021-05-06T21:43:13Z",
            "repository_cla_group_id": "5a74c3ca-8c50-4b32-8ec2-f94bda5481dd",
            "repository_external_id": 23950406,
            "repository_id": "b85a5ec4-468f-46f3-a9bf-d8d0003943ca",
            "repository_name": "chipsalliance/rocket-chip",
            "repository_organization_name": "chipsalliance",
            "repository_project_sfid": "a092M00001KWmbPQAT",
            "repository_type": "github",
            "repository_url": "https://github.com/chipsalliance/rocket-chip",
            "version": "v1"
        },
        {
            "date_created": "2020-11-20T22:11:13Z",
            "date_modified": "2020-11-20T22:11:13Z",
            "enabled": true,
            "note": "created on 2020-11-20T22:11:13Z",
            "repository_cla_group_id": "5a74c3ca-8c50-4b32-8ec2-f94bda5481dd",
            "repository_external_id": 314582396,
            "repository_id": "dcf99db5-b36f-4b73-97e3-3e4d3dc7af6a",
            "repository_name": "chipsalliance/EasyCLA-code_only",
            "repository_organization_name": "chipsalliance",
            "repository_project_sfid": "a092M00001KWmbPQAT",
            "repository_type": "github",
            "repository_url": "https://github.com/chipsalliance/EasyCLA-code_only",
            "version": "v1"
        },
        {
            "date_created": "2021-05-06T21:43:05Z",
            "date_modified": "2022-04-06T20:10:29Z",
            "enabled": true,
            "note": "created on 2021-05-06T21:43:05Z. repository was renamed externally. DD: Updated repository URL to chipsalliance/cde on 2022-09-06T10:49:06 PT.",
            "repository_cla_group_id": "5a74c3ca-8c50-4b32-8ec2-f94bda5481dd",
            "repository_external_id": 200312837,
            "repository_id": "29e68d2b-2ae2-4515-838d-526d3c1cc0b7",
            "repository_name": "cde",
            "repository_organization_name": "chipsalliance",
            "repository_project_sfid": "a092M00001KWmbPQAT",
            "repository_type": "github",
            "repository_url": "https://github.com/chipsalliance/cde",
            "version": "v1"
        }
    ]
}`

For https://projectadmin.lfx.linuxfoundation.org/project/a092M00001KWmbUQAT/tools/easycla/repositories/a092M00001KWmbUQAT#c592af39-2950-417f-826a-278f7fe36e86 
`{
    "list": [
        {
            "date_created": "2021-05-06T17:33:27Z",
            "date_modified": "2021-05-06T17:33:27Z",
            "enabled": true,
            "note": "created on 2021-05-06T17:33:27Z. DD: Updated project_sfid and repository_sfid_id",
            "repository_cla_group_id": "c592af39-2950-417f-826a-278f7fe36e86",
            "repository_external_id": 314582661,
            "repository_id": "f2f7e64e-b1e0-459d-969b-317aff16765a",
            "repository_name": "chipsalliance/EasyCLA-specs_and_code",
            "repository_organization_name": "chipsalliance",
            "repository_project_sfid": "a092M00001KWmbUQAT",
            "repository_type": "github",
            "repository_url": "https://github.com/chipsalliance/EasyCLA-specs_and_code",
            "version": "v1"
        }
    ]
}`

**Comment by nickmango** [comment]
@dealako Upon investigation I noticed the github org name stored in the github-org table happens to be saved as `CHIPSAlliance` and in the repository table its lower case `chipsalliance`. So the query against the repositories table returns empty values. This can be resolved by updating the name to lowercase. cc @WillsonHG

github-org table
<img width="1018" alt="Screenshot 2023-03-14 at 06 29 23" src="https://user-images.githubusercontent.com/81645226/224888390-3a0fc6b4-9080-4f8a-9bb4-8ac245de6228.png">

 repositories table
<img width="1000" alt="Screenshot 2023-03-14 at 06 36 50" src="https://user-images.githubusercontent.com/81645226/224888405-a3298ff6-0942-4163-9f69-cf74196c46c7.png">

**Comment by jarias-lfx** [comment]
@nickmango we have other projects, example JanusGraph is capitalized for the GitHub org and still not showing in the PCC. Also we have the lower case option in the DB repository_organization_name_lower
![image](https://user-images.githubusercontent.com/93140557/225045186-33697b4f-0ed7-4866-84df-a47fc2c51e32.png)

**Comment by dealako** [comment]
@nickmango let's work to prevent this issue moving forward.  Given that we have org_name_lowercase, we can also add repository_name_lowercase column/index to the repository table as well. When querying for the repository by name, we should use the lowercase comparison.

I will defer to @WillsonHG and @jarias-lfx on the quick fix of renaming and consolidating duplicate records.

**Comment by jarias-lfx** [comment]
Confirmed the issue is the data from the GitHub organization table. Correcting organization_sfid fixes the issue:
![image](https://user-images.githubusercontent.com/93140557/225439457-d148b656-0bd7-4ecb-9e43-eb5087ee86e3.png)

**Comment by WillsonHG** [comment]
Can confirm the issue has been resolved by @jarias-lfx  thanks!
