### ISSUE TITLE
Wrong project name appears for approval list under activity log

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3858]
Steps :

1. Login CD portal
2. Navigate to url : https://lfx.dev.platform.linuxfoundation.org/foundation/a092M00001IkOVVQA3/project/a092M00001IUjZPQA1/cla
3. Add user under approval list

Actual results : Wrong project name appears for approval list under activity log

![image.png](https://images.zenhubusercontent.com/5fc8abbc87345c4b3bd7aace/6cd37559-e597-4f2a-9811-192dff94b148)

**Comment by thakurveerendras** [comment]
![Screenshot 2023-03-15 at 17 10 52](https://user-images.githubusercontent.com/75417507/225334930-8114cea4-b812-4a10-b690-f0204e5c2507.png)
@thakurveerendras as shown here both ORAN and ProjectsLLC share the same clagroup Bellisa CLA . In addition the activity log for approval list and cla manager has been added

**Comment by thakurveerendras** [comment]
@nickmango ,
Kindly check , No cla group available for ProjectsLLC &  clagroup name Bellisa is only associated with ORAN project  
![image](https://user-images.githubusercontent.com/75417507/225344878-186d8575-0412-48bd-bac1-d177107b3730.png)
![image](https://user-images.githubusercontent.com/75417507/225345444-363f01ab-b955-4a49-aafc-978bc4117645.png)

**Comment by wanyaland** [comment]
@thakurveerendras this should be related to another issue for fetching cla-groups. Ive had a discussion with with @amolsontakke3576 for a PCC issue

**Comment by umeshlumbhani247** [comment]
@thakurveerendras 
Please find below PR:
https://github.com/communitybridge/easycla/pull/3955

**Comment by thakurveerendras** [comment]
Retested issue on dev site & found that it is still reproducible as reopened 
![image](https://github.com/communitybridge/easycla/assets/75417507/fe3fe7b7-61d3-4d79-a273-46cfe8f33a0c)

Refer video clip : [3858.webm](https://github.com/communitybridge/easycla/assets/75417507/af0eda1e-544a-4b84-a114-bcabb44c44bb)

**Comment by umeshlumbhani247** [comment]
@thakurveerendras 
Deployment was failed, Please test it again,

**Comment by thakurveerendras** [comment]
Tested issue on dev site & found that it is fixed as expected, Now shared child project name appears as expected. 
Refer video clip : [3858_Fixed.webm](https://github.com/communitybridge/easycla/assets/75417507/4978c938-47ef-4a1c-84f7-c59021fef6b9)

**Comment by mlehotskylf** [comment]
QA in DEV done, waiting for PROD deployment.

**Comment by thakurveerendras** [comment]
As discussed in stand-up call , We don't have same setup at prod so issue not required to validate at prod
