### ISSUE TITLE
Production : Recent activity logs are not generated for O-RAN Software Community project

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3860]
Steps :

1. Login company dashboard
2. Navigate to url : https://organization.lfx.linuxfoundation.org/foundation/a092M00001IkOVVQA3/project/a092M00001IUjZPQA1/cla
3. Add new cla manager to project 
4. See-Cla manager added

Actual results : recent activity logs are not generated for O-RAN Software Community project

**Comment by umeshlumbhani247** [comment]
@thakurveerendras 
I have resolved this issue and raised PR: https://github.com/communitybridge/easycla/pull/3989
CC: @mlehotskylf

**Comment by thakurveerendras** [comment]
Hi @umeshlumbhani247 
Tested issue on dev site & found that activity logs are properly appears for new cla manager added on child project but wrong project name appears on recent activity table 

- Project link : https://lfx.dev.platform.linuxfoundation.org/foundation/a09P000000DsCE5IAN/project/a09P000000DsCEFIA3/cla

![image](https://github.com/communitybridge/easycla/assets/75417507/3e54e8e3-f0b4-4e32-8b0f-de6a14b2c1f0)

**Comment by umeshlumbhani247** [comment]
@thakurveerendras 
Deployment was failed, Please review again,
It's working fine in dev

**Comment by thakurveerendras** [comment]
Tested issue on dev site & found that it is fixed as expected, So making issue status QA-Passed
Refer screenshot :
![image](https://github.com/communitybridge/easycla/assets/75417507/f2858b14-e1c4-4783-87a0-b98b772b9233)

**Comment by thakurveerendras** [comment]
Tested issue on production & found that it is fixed as expected, So making issue status QA-Passed
Refer screenshot : 
![image](https://github.com/communitybridge/easycla/assets/75417507/00c5e640-40fc-4853-a40f-74ec7430ed6a)
