### ISSUE TITLE
GitLab Merge request remain not covered after docu-signed

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3863]
Steps :

1. Go to gated Easycla PR : https://gitlab.com/sungitlabgroup/repo01/-/merge_requests/10
2. Click on Not covered
3. Proceed as an Individual Contributor
4. Click on Sing CLA
5. Fill docusign pdf form

Actual results : GitLab Merge request remain not covered after docu-signed
Refer video clip : 
https://images.zenhubusercontent.com/194341141/6d0cd67e-e2ea-4b02-aa0b-8bbbfb751a61/gitlabmr.mp4

**Comment by shyam-goshike** [comment]
Deployed to PROD
