### ISSUE TITLE
Contributor Console: Update Organization listing

### ISSUE THREAD

**Issue by jarias-lfx** [communitybridge/easycla#3872]
## Summary

Open for discussion: we need to update the Contributor Console organization listing, It would be good to have a first list all the organizations with an active CCLA on the project, where the contributor can easily search and choose their organization. 

1.  If the organization is listed, they would select it and sent the request to the CLA Managers or complete the contribution acknowledgement.
2.  If the organization is not listed, have the option at the bottom saying: "Is your Corporation not listed?", when selected, the contributor will be sent to the current service organization listing, where they can search or create a new organization, and proceed with the CCLA signature process.

## Background

Currently, when a new corporate contributor uses the Contributor Console, the system will list all the current organizations available in the Platform. However, the contributor is unable to identify if the organization has an active CCLA. Usually, they will pick the organization name which most accurately represents them and start a new process or get confused if the chosen organization is the company that has a CCLA.

A clear example of this is Google. On the current service if we search "google", the system will list all the organizations that contain google, still the contributor won't be able to identify the organization with the active CCLA is named "Google LLC" causing confusion.

![image](https://user-images.githubusercontent.com/93140557/227288066-d244c408-d1f0-4fc9-a68a-1e209edbe18b.png)

**Comment by amolsontakke3576** [comment]
@nickmango Done
PR : https://github.com/communitybridge/easycla-contributor-console/pull/367

**Comment by mlehotskylf** [comment]
@thakurveerendras please verify this.

**Comment by thakurveerendras** [comment]
Tested the fixes on dev site & found that a Green checkmark was added with CCLA-signed tooltip text.
![image](https://github.com/communitybridge/easycla/assets/75417507/5cd18b6d-92b3-4535-90dc-cc147378ea94)

**Comment by thakurveerendras** [comment]
Working fine on prod too, So closing this ticket
![image](https://github.com/communitybridge/easycla/assets/75417507/5fe1ff86-34ea-4cb8-9ac2-63387b47c780)
