### ISSUE TITLE
PR remain not covered after add GitHub user email address under approval list on Auto-Ecla case

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3910]
## Summary

PR remain not covered after add GitHub user email address under approval list on Auto-Ecla case

## Steps

1. Create easycla gated PR 
2. Go to CD board 
3. Enabled Auto-Ecla options
4. Add GitHub user email address under approval list 
5. See-User added under contributor list too
6. Go to PR again & add /easycla comment

## Actual behavior
PR remain not covered after add GitHub user email address under approval list on Auto-Ecla case
## Expected behavior
PR should covered after add user contributor list
## PR link
https://github.com/sun-test-org/repo1/pull/52
## Video

https://user-images.githubusercontent.com/75417507/233578586-77153fe3-f868-449d-ab9f-c368733b649d.mp4

## Environment

Please complete the following information:

* Environment:
  - [ ] ALL
  - [ ] DEV
  - [ ] STAGING
  - [ ] PROD

**Comment by nickmango** [comment]
@thakurveerendras I verified this and found its working as expected.

**Comment by thakurveerendras** [comment]
Tested issue on reported PR and found that it is fixed as expected, So making issue status QA-Done at Dev site
![image](https://github.com/communitybridge/easycla/assets/75417507/8d0f5c2b-82f4-4c2d-8a12-36798fd5792c)
