### ISSUE TITLE
EasyCLA Integration with GitLab

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#392]
## Summary

Members of the open source project community would like EasyCLA integration and support with Gitlab, just as there is with Github and Gerrit. 

## References

This conversation was started from a request in the LF product service desk. https://jira.linuxfoundation.org/servicedesk/customer/portal/4/SUPPORT-690 (for reference for those with access)
This ticket is to track the priority and timeline for this request.

**Comment by KennyPaul** [comment]
Back in November (Prior to SUPPORT-690 being closed), it was logged that the community was requesting support for this in the April 2020 timeframe.  
What is the current status of this request?
Thanks! 
-kenny

**Comment by dealako** [comment]
Still on the roadmap for post v2 release => target v2.1 for late 2020 inclusion.

Use cases:
- OPNFV is going to GitLab
- previously FINOS -> but they have decided to say on GitHub

Need to sync with Steve Ira on timelines.

**Comment by dplanella** [comment]
What is required specifically to complete this integration? Is there a roadmap or a set of issues the GitLab team or the wider community could contribute to? Thanks!

**Comment by dealako** [comment]
Currently in-progress.

**Comment by dealako** [comment]
The initial implementation of GitLab integration is complete. There is an open ticket on Token refresh - we'll track the status there.
