### ISSUE TITLE
Second commit on an Authorized PR fail EasyCLA check

### ISSUE THREAD

**Issue by jarias-lfx** [communitybridge/easycla#3925]
## Summary

In a PR when the first contributor commit had a previous EasyCLA signature/authorization, EasyCLA doesn't add the "COVERED" comment and just pass the PR. The bug seems when a second commit is being added, even when is the same contributor, this second commit doesn't have EasyCLA Authorization.
Two issues:

1. EasyCLA comment doesn't show when it fails the second commit
2. An already authorized user EasyCLA is not passing for the second commit

## Background

Some examples of this issue are:

1- PR https://github.com/istio/istio.io/pull/13152
The first commit [45796525e2cd5a2509e24f45da824dbb64b57e93 ](https://github.com/istio/istio.io/pull/13152/commits/45796525e2cd5a2509e24f45da824dbb64b57e93) passed EasyCLA authorization
Then the same contributor created a second commit [500c426a38fe8f89b6f038f9e816e3045eefc383
](https://github.com/istio/istio.io/pull/13152/commits/500c426a38fe8f89b6f038f9e816e3045eefc383) the second commit, even when it was created by the same contributor, didn't have EasyCLA authorization
When the user opened a third commit, the second commit got authorized. Also adding "/easycla" comment the commit gets authorized.
Checking the [logs](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fcla-backend-prod-githubactivity/log-events/2023$252F05$252F02$252F$255B$2524LATEST$255D6e495250a4f24c48ad8f0fe5f03756f7$3Fstart$3D2023-05-02T14$253A35$253A05.944Z) we see the authorization
```
2023-05-02T14:35:07 INFO cla: utils.get_comment_body SHAs for signed users: ['45796525e2cd5a2509e24f45da824dbb64b57e93', '500c426a38fe8f89b6f038f9e816e3045eefc383']

2023-05-02T14:35:08 DEBUG cla: cla.models.github_models.update_pull_request - EasyCLA App checks pass for PR: 13152 with authors: [UserCommitSummary(commit_sha='45796525e2cd5a2509e24f45da824dbb64b57e93', author_id=10537847, author_login='ericvn', author_name='Eric Van Norman', author_email=None, authorized=True, affiliated=False), UserCommitSummary(commit_sha='500c426a38fe8f89b6f038f9e816e3045eefc383', author_id=10537847, author_login='ericvn', author_name='Eric Van Norman', author_email=None, authorized=True, affiliated=False)]

2023-05-02T14:35:08 DEBUG cla: cla.models.github_models.update_pull_request - Creating new CLA 'success' status - 2 passed, [] failed, signing url: https://easycla.lfx.linuxfoundation.org/#/?version=2

2023-05-02T14:35:08 INFO cla: Updating status with state 'success' on PR 13152 for commit 500c426a38fe8f89b6f038f9e816e3045eefc383...

2023-05-02T14:35:09 INFO cla: Successfully posted status 'success' on PR 13152: Commit 500c426a38fe8f89b6f038f9e816e3045eefc383 with SignUrl : https://easycla.lfx.linuxfoundation.org/#/?version=2 with response: CommitStatus(state="success", id=22882252220, context="EasyCLA")
```

2- PR https://github.com/cloudfoundry/community/pull/509
The first commit [b109c14a19028c83ec0f582b4f732861a542f106](https://github.com/cloudfoundry/community/pull/509/commits/b109c14a19028c83ec0f582b4f732861a542f106) has EasyCLA authorization.
When the contributor added a second commit [aa284a3dd842035734f6a9f6559cc409f612da2a](https://github.com/cloudfoundry/community/pull/509/commits/aa284a3dd842035734f6a9f6559cc409f612da2a) the second commit didn't have EasyCLA authorization, even when is the same contributor as the first commit.
Adding "/easycla" comment fixed the issue

## Expected behavior

1- When there is a second commit and the user is not authorized the EasyCLA comment should be added.
2- The commits when the contributor has a previous authorization should all pass EasyCLA check

## Environment

Please complete the following information:

* Environment:
  - [ ] ALL
  - [ ] DEV
  - [ ] STAGING
  - [x ] PROD 
* Browser:
  - [ x] Chrome/Brave
  - [ ] Firefox
  - [ ] Opera
  - [ ] Vivaldi
  - [ ] LibreWolf
  - [ ] SRware Iron
  - [ ] Dissenter
  - [ ] Slimjet
  - [ ] Midori
  - [ ] Edge
  - [ ] Lynx

**Comment by therealmitchconnors** [comment]
Is there any update on this work?

**Comment by nickmango** [comment]
@therealmitchconnors am looking into this with an ETA of Friday

**Comment by thakurveerendras** [comment]
Thanks @nickmango , @jarias-lfx 
Tested issue on dev site & found that it is working fine , easycla checks are properly appears on 2nd commit.
Refer PR below for more details 

1. https://github.com/sun-test-org/repo1/pull/82
2. https://github.com/sun-test-org/repo1/pull/85
3. https://github.com/sun-test-org/repo1/pull/86

**Comment by thakurveerendras** [comment]
Tested issue on prod & found that it is also working fine , So making issue status QA-Done
Refer PR : https://github.com/CLATestOrg/VulDetect1/pull/39

**Comment by jarias-lfx** [comment]
@thakurveerendras could you confirm the 3 scenarios in PROD from https://github.com/communitybridge/easycla/issues/3925#issuecomment-1593295403?

**Comment by thakurveerendras** [comment]
@jarias-lfx , Kindly refer tested 3 scenario PR details below , They are working fine on Prod

1. Authorized user added two commit  : https://github.com/CLATestOrg/VulDetect1/pull/39
2. Unauthorized user added two commit : https://github.com/CLATestOrg/VulDetect1/pull/41
3. Authorized & Unauthorized user added commit : https://github.com/CLATestOrg/VulDetect1/pull/42
![image](https://github.com/communitybridge/easycla/assets/75417507/c62f5b71-b95e-480d-ad87-0dfdc7c33bce)

**Comment by jarias-lfx** [comment]
Thank you @thakurveerendras
