### ISSUE TITLE
Shared User : GitLab MR page open after I singed ICLA on GitHub PR

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3934]
## Summary

Shared User : GitLab MR page open after I singed ICLA on GitHub PR

## Background

- Create GitHub & GitLab user which having user name & email address same 
- user : thakurveerendras1
- Email : veerendrat+1@proximabiz.com

Steps : 
1. Have GitLab records at "cla-dev-signatures" table
2. Create GitHub PR 
3. singed ICLA on GitHub PR
## Actual behavior

- After docu-signed , GitLab "signature_return_url" page open & PR remain uncovered 

## Expected behavior

- PR should covered & landing page should be GitHub

## Screenshots
[WrongClient.webm](https://user-images.githubusercontent.com/75417507/236748286-ac82faee-7e19-4184-b3a2-90086304fd68.webm)

## Environment
  - [ ] ALL
  - [ ] DEV
  - [ ] STAGING
  - [ ] PROD

**Comment by umeshlumbhani247** [comment]
@thakurveerendras 
Can you please confirm, same scenario is there, when you sign CLA on gitlab and redirecting it to github ?

**Comment by thakurveerendras** [comment]
@umeshlumbhani247 , On reverse case GitLab MR are automatic appears covered 

- MR :  https://gitlab.com/sungitlabgroup/repo01/-/merge_requests/36

![image](https://user-images.githubusercontent.com/75417507/236856098-c1451cb2-e82e-4515-8d85-80a1f1342a8f.png)

**Comment by umeshlumbhani247** [comment]
Yes you can delete and chek the same case ?

**Comment by umeshlumbhani247** [comment]
@thakurveerendras 
As per our discussion, it is working as expected. Let me know, if you are facing same case again ?

**Comment by umeshlumbhani247** [comment]
@thakurveerendras 
Can you prepare required steps for the duplicate case once you get time?

**Comment by thakurveerendras** [comment]
Tried several times with the steps mentioned in descriptions & found that it is not reproducible, Let me find reproducible steps for it

**Comment by umeshlumbhani247** [comment]
@thakurveerendras 
Can you please provide me steps for reproduce the same case ?

**Comment by mlehotskylf** [comment]
@thakurveerendras can you please confirmed this has been tested? If yes then please change the status. Thanks!

**Comment by thakurveerendras** [comment]
Issue is not reproducible as reported on the dev site, Tested by the reported user. So making the issue status Done
PR: https://github.com/sun-test-org/repo1/pull/129
MR:https://gitlab.com/childearthgroup/project1/-/merge_requests/2
