### ISSUE TITLE
Auto-ecla : Existing contributor duplicated when add new approval list 

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3936]
## Summary

Existing contributor duplicated when add new approval list 

## Background

Steps :
1. Login corporate console 
2. Search & open sun project cla page
3. Enable auto-ecla options 
4. Get contributorsList count say : 45239
5. Get approval list count : 300
6. Now add new approval list 
 
## Expected behavior

Now contributorsList count increase to 301 i.e. 45540 , expected 45240

## Screenshots

![image](https://github.com/communitybridge/easycla/assets/75417507/d34c7cff-f0dd-4b15-a30d-2719e438bc53)

## Environment

Please complete the following information:

* Environment:
  - [ ] ALL
  - [ ] DEV
  - [ ] STAGING
  - [ ] PROD

**Comment by mlehotskylf** [comment]
@nickmango what is the latest for this issue? Thanks!

**Comment by mlehotskylf** [comment]
We have a PR in the review.

**Comment by thakurveerendras** [comment]
Testing is blocked due to issue #3960
504 error appears when try to add GitHub user under approval list #3960

**Comment by nickmango** [comment]
@thakurveerendras kindly verify

**Comment by thakurveerendras** [comment]
Tested issue multiple times on dev site with below project & found that reported case above are not reproducible , So updating issue status 

- Parent project : https://lfx.dev.platform.linuxfoundation.org/foundation/a09P000000DsCE5IAN/cla
- Child project : https://lfx.dev.platform.linuxfoundation.org/foundation/a09P000000DsCE5IAN/project/a09P000000DsCEFIA3/cla 

Use below steps to verify issue 
1. Get CompanyContributorAcknowledgements total count 
2. Add new GitHub user under approval list , 
`Expected` Verified count should be increase by 1
4. Deleted existing user from approval list, 
`Expected:` Verified count should remain same
6.  Re-added same user on approval list, 
`Expected:` Verified count should remain same

**Comment by thakurveerendras** [comment]
Verified issue on production , Duplicate records are not created after apply above steps
