### ISSUE TITLE
Please add a Kanban column to track the v2 release

### ISSUE THREAD

**Issue by dankohn** [communitybridge/easycla#396]
Could you please modify the [Kanban](https://github.com/communitybridge/easycla/projects/6) board to split the `To do` column into a `v2` column and a `later` column such that when every issue in the `v2` column is finished, we will be ready to onboard Kubernetes on to EasyCLA. You might model on the [events](https://github.com/LF-Engineering/lfevents/projects/1) board.

Cc @ShubhraKar @timfong888 @jzemlin

**Comment by dealako** [comment]
Updated kanban board, see: https://github.com/communitybridge/easycla/projects/7
