### ISSUE TITLE
504 error appears when try to add GitHub user under approval list 

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3960]
## Summary

504 error appears when try to add approval list 

## Steps
1. Login company portal
2. Search & open SUN project
3. Click on Easycla link
4. Add GitHub user under approval list
## Actaul behavior
- 504 error appears when try to add approval list & user not added on list
## Expected behavior

User should add on list

## Screenshots
![image](https://github.com/communitybridge/easycla/assets/75417507/57bcc21b-eb9b-4815-9126-a1356485f939)

**Comment by thakurveerendras** [comment]
Issue is not reproducible after fix & PR raises by @nickmango 

- refer slack thread for more details : https://linuxfoundation.slack.com/archives/C04M4D4PDC5/p1685092993954709

![image](https://github.com/communitybridge/easycla/assets/75417507/57ff563b-33e8-482b-bb4d-e1f76a62042f)

**Comment by mlehotskylf** [comment]
QA in DEV done, waiting for PROD deployment.

**Comment by thakurveerendras** [comment]
Tested issue on production & found that it is reproducible

- Cannot return null for non-nullable field ApprovalListResult.message." error appears when try to add GitHub user in approval list,

![image](https://github.com/communitybridge/easycla/assets/75417507/0ff4225e-5438-4f40-95e6-b7aa600fd23e)

**Comment by nickmango** [comment]
@thakurveerendras in prod you are not able to add an approval criteria item ?
