### ISSUE TITLE
User is not authorized but his cla PR appears covered

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3969]
## Summary
User is not authorized but his cla PR appears covered

## Background
1. Login company dashboard
2. enabled Auto-Ecla
3. Removed user from approval list 
4. Create GitHub PR
See-User is not authorized but his cla PR appears covered

## Expected behavior
For not authorized user, cla PR should not covered

## Screenshots
![image](https://github.com/communitybridge/easycla/assets/75417507/f5f70d69-0f7c-4709-bc38-5060abc4d259)
![image](https://github.com/communitybridge/easycla/assets/75417507/03c0fce1-963e-4e84-9765-1cf1f0be77d6)

**Comment by nickmango** [comment]
@thakurveerendras Kindly verify. This was fixed earlier
