### ISSUE TITLE
Review and adjust the "DocuSign" integration for EasyCLA

### ISSUE THREAD

**Issue by mlehotskylf** [communitybridge/easycla#3970]
In August, DocuSign will be officially removing its old-style authentication strategy (currently it’s deprecated).  This will likely impact our DocuSign workflow. We need to update, and test this.  
It may be related to this Python bits: https://github.com/communitybridge/easycla/blob/main/cla-backend/cla/models/docusign_models.py#L36-L40

**Comment by thakurveerendras** [comment]
Story implementation will be tracked on the below issue, So moving status Done

- Upgrade DocuSign Integration for EasyCLA #4002

**Comment by mlehotskylf** [comment]
We switched to Golang instead of Python so this ticket in no longer relevant, so closing. Ticket related to Golang is here: https://github.com/communitybridge/easycla/issues/4002
