### ISSUE TITLE
Email is missing under recant activity log table at PCC cla page

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3979]
## Summary

Email is missing under recant activity table at PCC cla page

## Background

1. Login admin portal
2. Search & open SUN project 
3. Open Easycla page
4. Go to Activity log table

## Actual behavior
Email is missing under recant activity table at PCC cla page
## Expected behavior

Email address should show for activity log records at PCC cla page
## Screenshots
![image](https://github.com/communitybridge/easycla/assets/75417507/abd55402-7c7a-49b8-bc63-a71d3431ce43)

**Comment by thakurveerendras** [comment]
Tested issue on dev site . Now email address added under activity log table at PCC easycla
Project Link : https://pcc.dev.platform.linuxfoundation.org/project/a09P000000DsCE5IAN/tools/easycla/overview
![image](https://github.com/communitybridge/easycla/assets/75417507/c3d6de35-bf47-4a60-86c2-63121502b42d)

**Comment by mlehotskylf** [comment]
This is done, so closing.
