### ISSUE TITLE
Auto-ECLA : GitHub/GitLab Contributor remain authorized after remove from approval list

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#3996]
## Summary

Auto-ECLA : Contributor remain authorized after remove from approval list

## Steps
1. Login CD portal 
2. Search & open project SUN
3. Enabled Auto-ecla options (if not enabled)
4. Add GitLab user : thakurveerendras1 under approval list
5. See-User added under contributor list with authorized status
6. Now remove user from approval list

## Actual behavior
User status is remain authorized

## Expected behavior
User status should be updated to Not Authorized

## Screenshots

![image](https://github.com/communitybridge/easycla/assets/75417507/0d017496-7024-4cf2-acc6-10a621900ea7)

**Comment by umeshlumbhani247** [comment]
@thakurveerendras 
I have raised below PR for fixing this bug.

**Comment by thakurveerendras** [comment]
Tested issue on dev site & found that it is fixed as expected, Now **Not Authorized** appears after remove GitLab user from approval list
Refer video clip : 
[3996.webm](https://github.com/communitybridge/easycla/assets/75417507/bb3386c6-6f1a-47b0-b4f0-7fd722468611)

**Comment by thakurveerendras** [comment]
Tested issue on production & found that it is fixed as expected, So making issue status QA-Done

**Comment by thakurveerendras** [comment]
Tested the issue & found that it is reproducible with the below GitLab user

Refer GitLab User :

1. thakuveerendras
2. thakuveerendras1
3. vthakurgitlab
4. vthakur.lflegal

Refer PR: https://gitlab.com/childearthgroup/project1/-/merge_requests/5

**Comment by umeshlumbhani247** [comment]
@thakurveerendras @nickmango 
I have resolved this issue, Please find PR: [4053](https://github.com/communitybridge/easycla/pull/4053)
CC: @mlehotskylf

**Comment by thakurveerendras** [comment]
Failed case on this issue will be covered on the issue https://github.com/communitybridge/easycla/issues/4001, So making this issue status QA-Done
