### ISSUE TITLE
EasyCLA dashboard not working after admin disables bot on github - [CDF/Tekton]

### ISSUE THREAD

**Issue by danlopez00** [communitybridge/easycla#400]
## Summary

EasyCLA dashboard not working after admin disables bot on github. EasyCLA manager level user can see and list repositories, but can no longer administer the repositories if a developer who has admin rights on github disables the bot.

## Screenshots

![image](https://user-images.githubusercontent.com/727396/70455053-6e6c5f00-1a60-11ea-8d3e-8bcf9bfdb289.png)

![image](https://user-images.githubusercontent.com/727396/70455064-72987c80-1a60-11ea-9d99-44914d5e949a.png)

**Comment by dealako** [comment]
@danlopez00 the Project Manager will need to navigate to the EasyCLA Project Console and re-authorize/re-connect the GitHub Bot under the project.  Once this is complete, project managers will be able to administer the repositories.

**Comment by dealako** [comment]
@danlopez00 Instructions are here: https://lf-docs-linux-foundation.gitbook.io/easycla/getting-started/project-managers/add-github-repositories-to-cla-monitoring-or-remove-them-from-cla-monitoring

**Comment by dealako** [comment]
Closing this issue during the product backlog review meeting.  @danlopez00 ping the EasyCLA team if you need further assistance.
