### ISSUE TITLE
Upgrade DocuSign Integration for EasyCLA

### ISSUE THREAD

**Issue by umeshlumbhani247** [communitybridge/easycla#4002]
Upgrade authorisation strategy with new version as well as Replace **PyDocusign** with [docusign-esign](https://pypi.org/project/docusign-esign/) SDK in order to implement Auth as well as other docusign functionalities.

**Comment by umeshlumbhani247** [comment]
@mlehotskylf 
Working on preparing the stand alone demo including all required functionalities for the project.

**Comment by thakurveerendras** [comment]
@nickmango, Kindly review the below issue 
1. request-individual-signature API is failed with 502 status on ICLA sign-in process 
2. CLA System is not able to support your request that appears on CCLA sign-in process 
Refer screenshot for more details 
![image (87)](https://github.com/communitybridge/easycla/assets/75417507/a7674f8b-7720-4ecb-8eb7-ce35268c9c4b)
![image (88)](https://github.com/communitybridge/easycla/assets/75417507/642bc37a-d9dc-4c76-a254-cf83c2f94f80)

**Comment by mlehotskylf** [comment]
@thakurveerendras this ticket is for re-writing DocuSign API.

**Comment by thakurveerendras** [comment]
Tested Upgrade DocuSign Integration for EasyCLA flow on dev site & found that it is fixed as expected. So moving this ticket status tp review completed.

**Comment by thakurveerendras** [comment]
Tested ICLA/CCLAs flow on production and found that DocuSign is working as expected
