### ISSUE TITLE
Invalid GitLab/GitHub Username appears when user name contains dots

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#4006]
## Summary

Invalid GitLab/GitHub Username appears when user name contains dots
## Related bug frontend bug : 
[CD-1943](https://jira.linuxfoundation.org/browse/CD-1943) : Invalid GitLab/GitHub Username appears when user name contains dots

## Steps :

1. Login company cla portal
2. Search & open "Test Project IT"
3. Click on easycla link
4. Go to an approval list 
5. Add vthakur.lflegal in GitLab/GitHub user

## Actual results: 
Enter Valid GitHub Username" validation appears at UI

## API Response : 
`{
    "Message": "invalid add approval list GitHub Username vthakur.lflegal - invalid GitHub username: vthakur.lflegal",
    "x-request-id": "28d34940-1a52-11ee-9f90-87a8e69ad965"
}`

## Expected: 
GitLab/GitHub contains a name with dots so we should accept this as a valid name
![image](https://github.com/communitybridge/easycla/assets/75417507/a0026153-809b-4c12-8c6c-806414fa2bb3)

**Comment by thakurveerendras** [comment]
Tested the issue at the API side & found that it is fixed but Still, we have an issue with the frontend side
Refer API response : 

> {
    "autoCreateECLA": false,
    "claType": "ccla",
    "companyName": "Infosys Limited",
    "created": "2023-03-09T06:46:33.818329+0000",
    "domainApprovalList": null,
    "emailApprovalList": [
        "vthakur@contractor.linuxfoundation.org",
        "veerendrat@proximabiz.com"
    ],
    "githubOrgApprovalList": null,
    "githubUsernameApprovalList": [
        "nickmango",
        "vthakur",
        "thakurveerendras",
        "vthakur.lflegal"
    ],
    "gitlabOrgApprovalList": null,
    "gitlabUsernameApprovalList": [
        "umeshlumbhani"
    ],
    "modified": "2023-05-18T10:35:35Z",
    "projectID": "01af041c-fa69-4052-a23c-fb8c1d3bef24",
    "signatureACL": [
        {
            "companyID": "fcf59557-9708-4b2f-8200-4e6448761c0a",
            "dateCreated": "2021-05-25T20:22:52.000000+0000",
            "dateModified": "2022-10-13T01:47:29.552978+0000",
            "emails": [
                "ddeal@linuxfoundation.org",
                "dealako@gmail.com"
            ],
            "githubID": "519609",
            "githubUsername": "dealako",
            "gitlabID": "2369544",
            "gitlabUsername": "dealako",
            "lfEmail": "ddeal@linuxfoundation.org",
            "lfUsername": "ddeal",
            "note": "auto assign companyID from CLA Manager adding user to the company approval list with auto_create_ecla feature flag set to true on 2023-02-10T22:47:45Z.. auto assign companyID from CLA Manager adding user to the company approval list with auto_create_ecla feature flag set to true on 2023-02-23T19:26:38Z.. auto assign companyID from CLA Manager adding user to the company approval list with auto_create_ecla feature flag set to true on 2023-03-20T12:54:32Z.",
            "userExternalID": "0032M00002ntWBYQA2",
            "userID": "fb9e0ea4-bd96-11eb-9643-66bd4d90c263",
            "username": "David Deal",
            "version": "v1"
        },
        {
            "admin": true,
            "companyID": "fcf59557-9708-4b2f-8200-4e6448761c0a",
            "dateCreated": "2023-03-16T14:06:29Z",
            "dateModified": "2023-03-16T14:06:29Z",
            "emails": null,
            "lfEmail": "wanyaland@gmail.com",
            "lfUsername": "hwanyama",
            "note": "auto assign companyID from CLA Manager adding user to the company approval list with auto_create_ecla feature flag set to true on 2023-03-21T08:14:26Z.",
            "userExternalID": "0014100000Te0G7AAJ",
            "userID": "bf3236eb-c403-11ed-9752-ca6610e3755e",
            "username": "Harold Wanyama",
            "version": "v1"
        },
        {
            "companyID": "f7c7ac9c-4dbf-4104-ab3f-6b38a26d82dc",
            "dateCreated": "2023-03-22T10:31:40Z",
            "dateModified": "2023-03-22T10:31:40Z",
            "emails": null,
            "lfEmail": "vthakur@contractor.linuxfoundation.org",
            "lfUsername": "vthakur",
            "note": "auto assign companyID from CLA Manager adding user to the company approval list with auto_create_ecla feature flag set to true on 2023-04-04T16:41:48Z.",
            "userID": "bbaafb33-c89c-11ed-bb8c-12da8d3ce790",
            "username": "(vthakur)  Singh@Thakur",
            "version": "v1"
        },
        {
            "admin": true,
            "companyID": "f7c7ac9c-4dbf-4104-ab3f-6b38a26d82dc",
            "dateCreated": "2023-05-18T07:39:27Z",
            "dateModified": "2023-05-18T07:39:27Z",
            "emails": null,
            "lfEmail": "hwanyama@contractor.linuxfoundation.org",
            "lfUsername": "wanyama",
            "userExternalID": "0014100000Te0G7AAJ",
            "userID": "1e069c96-f54f-11ed-b63e-ea40cd106cd0",
            "username": "Harold Wanyama",
            "version": "v1"
        }
    ],
    "signatureApproved": true,
    "signatureCreated": "2023-03-09T06:46:33.818329+0000",
    "signatureID": "28de28e0-e9d2-42fd-96cd-f747ad16a06f",
    "signatureMajorVersion": "2",
    "signatureMinorVersion": "1",
    "signatureModified": "2023-05-18T10:35:35Z",
    "signatureReferenceID": "f7c7ac9c-4dbf-4104-ab3f-6b38a26d82dc",
    "signatureReferenceName": "Infosys Limited",
    "signatureReferenceNameLower": "infosys limited",
    "signatureReferenceType": "company",
    "signatureSigned": true,
    "signatureType": "ccla",
    "signedOn": "2023-03-09T06:47:47Z",
    "signingEntityName": "Infosys Limited",
    "userDocusignDateSigned": "2023-03-08T22:47:01.887",
    "userDocusignName": "vthakur Thakur",
    "version": "2.1"
}

![image](https://github.com/communitybridge/easycla/assets/75417507/00a8d339-7918-41e6-b92d-d3c2e36bd821)

![image](https://github.com/communitybridge/easycla/assets/75417507/fdade3ef-a15c-468b-abce-a9ede8a6c619)

**Comment by nickmango** [comment]
Backend is completed so closing this issue on easycla Project
