### ISSUE TITLE
EasyCLA - no instruction on how companies could sign it [CDF/Tekton]

### ISSUE THREAD

**Issue by danlopez00** [communitybridge/easycla#401]
## Summary

EasyCLA - no instruction on how companies could sign it

## Background

End User submits issue post-onboarding:

"there was no instruction on how companies could sign it"

Need to provide end user onboarding instructions on how companies sign EasyCLA

**Comment by danlopez00** [comment]
An updated list of users who have signed the CLA via EasyCLA for Tekton provided to @dlorenc

**Comment by swatimayur** [comment]
The documentation link that you are looking for is here: 
https://lf-docs-linux-foundation.gitbook.io/easycla/getting-started/ccla-managers-and-ccla-signatories/sign-a-corporate-cla-on-behalf-of-the-company

This documentation is currently in the DEV environment. It will be pushed to Staging and PROD soon.
