### ISSUE TITLE
Duplicate EasyCLA Bot added for every /easycla Comment

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#4011]
## Summary

EasyCLA Bot added for every Comment

## Background
1. Create GitHub PR with missing ID
2. See-EasyCLA Bot added for commit
3. Now add /easycla comment
## PR Link
https://github.com/sun-test-org/repo1/pull/101
## Actual results 
EasyCLA Bot added for every Comment
## Expected behavior
Comment details should update on the existing bot

## Screenshots
![image](https://github.com/communitybridge/easycla/assets/75417507/130e9aab-4003-437f-947b-7abaf952b676)

**Comment by thakurveerendras** [comment]
Hello @WillsonHG , @jarias-lfx 

- Kindly let us know the expected behavior & your feedback for this case

CC: @mlehotskylf 
Thank you

**Comment by jarias-lfx** [comment]
Related to this, the community reported PR: https://github.com/AcademySoftwareFoundation/OpenColorIO/pull/1812, EasyCLA check passed but the comment didn't update.

**Comment by thakurveerendras** [comment]
Tested the issue on the dev site & found that it is fixed as expected
Refer video clip:[4011.webm](https://github.com/communitybridge/easycla/assets/75417507/669f5c0a-99fe-43af-90e3-271b72a17792)

Refer screenshot 
![image](https://github.com/communitybridge/easycla/assets/75417507/c93ec1ad-86f4-4732-a4d6-dabc47353c05)

**Comment by thakurveerendras** [comment]
Verified the issue on production after deployment and found that it is properly fixed
Refer PR: https://github.com/CLATestOrg/VulDetect1/pull/44
![image](https://github.com/communitybridge/easycla/assets/75417507/bf853120-98a4-4370-b04a-8fdb8b761619)
