### ISSUE TITLE
Docs describing onboarding do not have valid links to gitbooks pages

### ISSUE THREAD

**Issue by danlopez00** [communitybridge/easycla#402]
## Impacted Docs

Docs describing onboarding do not have valid links to gitbooks pages

- https://github.com/communitybridge/easycla/tree/master/getting-started#contributor
- https://github.com/communitybridge/easycla/tree/master/getting-started#corporate-cla-manager
- https://github.com/communitybridge/easycla/tree/master/getting-started#corporate-cla-signatory

**Comment by swatimayur** [comment]
The broken links have been fixed. Will be available in PROD and Staging soon.
