### ISSUE TITLE
EasyCLA Bug Report

### ISSUE THREAD

**Issue by xumia** [communitybridge/easycla#4052]
## Summary

Describe the bug - a clear and concise description of what the bug is.
EasyCLA does not post the check result. Waiting for status to be reported.
See PR: https://github.com/sonic-net/sonic-buildimage/pull/15887

![image](https://github.com/communitybridge/easycla/assets/59720581/49009544-c296-4d23-8353-5a8a251e8002)

## Background

Provide context to the issue - provide steps to reproduce the behavior, such as:

1. Click on '....'
1. Scroll down to '....'
1. See error

## Environment

Please complete the following information:

* Environment:
  - [ ] ALL
  - [ ] DEV
  - [ ] STAGING
  - [ ] PROD 
* Browser:
  - [ ] Chrome/Brave
  - [ ] Firefox
  - [ ] Opera
  - [ ] Vivaldi
  - [ ] LibreWolf
  - [ ] SRware Iron
  - [ ] Dissenter
  - [ ] Slimjet
  - [ ] Midori
  - [ ] Edge
  - [ ] Lynx
* Version: v1.0.XX

## Assumptions

If you are assuming certain facts or scenarios, list them so we have a baseline to understand your request.

- Assumption 1
- Assumption 2

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

- Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by jarias-lfx** [comment]
Correct @nickmango. The root cause is: the EasyCLA app was uninstalled from sonic-net organization, after reinstalling the app and updating EasyCLA DB with the installation ID resolved the issue. We went through all the opened PRs and ran /easycla to update EasyCLA status as required.

I am marking this ticket as closed.
