### ISSUE TITLE
EasyCLA check fails with multiple commits in a PR

### ISSUE THREAD

**Issue by jarias-lfx** [communitybridge/easycla#4087]
## Summary

Currently when there is a large amount of commits in a PR, EasyCLA fails to report the PR.
Examples:
- https://github.com/kubernetes-sigs/cluster-api/pull/9087
- https://github.com/open-telemetry/opentelemetry-android/pull/3
We have asked the Community to squash the commits or Admin merge the PR without EasyCLA check due to this limitation.

This relates to: 
https://github.com/communitybridge/easycla/issues/4071
https://jira.linuxfoundation.org/browse/SUPPORT-19806

## Expected behavior

EasyCLA should handle the PR regardless of the amount of commits.

## Environment

Please complete the following information:

* Environment:
  - [ ] ALL
  - [ ] DEV
  - [ ] STAGING
  - [x] PROD 
* Browser:
  - [x] Chrome/Brave
  - [ ] Firefox
  - [ ] Opera
  - [ ] Vivaldi
  - [ ] LibreWolf
  - [ ] SRware Iron
  - [ ] Dissenter
  - [ ] Slimjet
  - [ ] Midori
  - [ ] Edge
  - [ ] Lynx

**Comment by jarias-lfx** [comment]
Adding PR: https://github.com/grpc/grpc/pull/35296

**Comment by malfet** [comment]
PyTorch instance where EasyCLA generation failed with no feedback to the users: https://github.com/pytorch/pytorch/pull/114309

**Comment by mlehotskylf** [comment]
We will be release performance improvement which should increase number of commits EasyCLA can handle in next release.

**Comment by mlehotskylf** [comment]
@thakurveerendras please let us know if you had a chance this test this. Thanks!

**Comment by thakurveerendras** [comment]
Tested on reported PR and found that easycla check is working fine in the expected time
PR: https://github.com/open-telemetry/opentelemetry-android/pull/3
![image](https://github.com/communitybridge/easycla/assets/75417507/0696d356-1e4c-40fc-9e13-40b6b65d36eb)
CC: @umeshlumbhani247 , @mlehotskylf , @jarias-lfx

**Comment by mlehotskylf** [comment]
Closing as this is done and deployed to PROD.
