### ISSUE TITLE
Going Forward Document the Release Process, Tagging Releases as Done

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#409]
## Summary

Start tagging release for: https://github.com/communitybridge/easycla/releases as being done here: https://github.com/LF-Engineering/easycla-private/releases (ASAP maybe for next immediate commit)
and bump up the release number to annotate to GA equivalent. I suggest start with 0.8 or 0.9 and jump to 1.0.0 very quickly it can’t express alpha/beta notion, its in production and there is 15+ project use it to enforce CLA.

## Background
I belive this is a simple change in release process and not necessarily a software defect or enhancement, per se. I suppose we can write the ticket up as “Document the Release Process” if desired - I have notes and a diagram somewhere. I don’t think we need to go back and re-tag the public repo based on old tags. This will be a lot of work.  I recommend we update the process going forward only.

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

\(Optional\) Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by dealako** [comment]
Migrating CI/CD CircleCI configuration and serverless + pulumi deployment scripts to the public repo in PR# 436. Awaiting on IT to migrate the AWS deployment credentials in the CommunityBridge EasyCLA CircleCI project: https://circleci.com/gh/communitybridge/easycla/edit#env-vars.  Once the credentials are migrated over we will support deployments to the DEV, STAGING, and PROD environments.

**Comment by dealako** [comment]
Migrated deployment scripts/configs and functional tests to public repo. Releases and DEV, STAGING, and PROD deployments will now be managed under the public repository tagging CI/CD pipeline.

**Comment by dealako** [comment]
DEV and STAGING roll out nice upon a master merge (DEV) and a tag (STAGING). Once we are ready to push to PROD, I'll need to:

**Comment by dealako** [comment]
Completed task. Closing this ticket as part of the product backlog review meeting.
