### ISSUE TITLE
Internal server error appears for requestCorporateSignature call

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#4095]
## Summary

Internal server error appears for requestCorporateSignature call

## Background

1. Login company dashboard
2. Search project & open easycla page : https://lfx.dev.platform.linuxfoundation.org/foundation/a09P000000DsNGsIAN/project/a09P000000DsNH2IAN/cla
3. Now try to sign cclas  
See-Internal server error appears for requestCorporateSignature call

> {
    "data": {
        "requestCorporateSignature": {
            "code": 500,
            "message": "internal server error",
            "success": false,
            "data": null,
            "__typename": "RequestCorporateSignatureResult"
        }
    }
}

## Expected behavior

Users should allowed to sign cclas

## Screenshots
![image (85)](https://github.com/communitybridge/easycla/assets/75417507/fafb8d5b-ac60-49f8-8f41-05bf90557352)

**Comment by mlehotskylf** [comment]
According to @nickmango, this is fixed so moving to QA.

**Comment by thakurveerendras** [comment]
Tested issue on dev site & it is working fine as expected. So moving this issue status to ready for deployment

**Comment by thakurveerendras** [comment]
Tested issue on dev site & it is working fine as expected. So moving this issue status to ready for deployment

**Comment by thakurveerendras** [comment]
This issue is not reproducible on prod, So moving issue status QA-Done

**Comment by mlehotskylf** [comment]
This is done, closing.
