### ISSUE TITLE
Bug when re-creating the same repository when Auto Enable New Repositories is enabled

### ISSUE THREAD

**Issue by jarias-lfx** [communitybridge/easycla#4137]
## Summary

Found a bug with "Auto Enable New Repositories" feature. When this is enabled, all the repositories created in the same GitHub organization should automatically be enforced with EasyCLA. However, when the same repository is deleted and recreated, this repository will have the same name but different repository id.

in the DB we record the repository ID and the repository name and mark it as enabled false when the repository was removed. However, when the new repository was created, it didn't update the status and the repository id.

Additionally, re-enforcing the repository manually, the DB updates the status as enabled true, but keeps the old repository id, making EasyCLA not working until we manually update the repository id.

## Background

This happened with CNCF https://github.com/knative-extensions/serving-progressive-rollout, PR: https://github.com/knative-extensions/serving-progressive-rollout/pull/1 the "Auto Enable New Repositories" feature was enabled for this organization and when the repository was re-created, and the record in the DB contained the old repository id 693815515. I had to manually enforce EasyCLA and update the repository id to 694349889 for EasyCLA to work 

## Expected behavior

When "Auto Enable New Repositories" feature is enabled, re-creating the repository the following should happen:

1- Mark the repository as enabled=false on deletion.
2- Update or Create the record in the repositories table with the new repository.
     a- If Update:
          i. Update enabled=true
          ii. Update the repository id
    b- If Create:
          i. Create a new record in the repositories with the repository name, id and enabled=true once the repository is created.

## Environment

Please complete the following information:

* Environment:
  - [ ] ALL
  - [ ] DEV
  - [ ] STAGING
  - [x] PROD 
* Browser:
  - [x] Chrome/Brave
  - [ ] Firefox
  - [ ] Opera
  - [ ] Vivaldi
  - [ ] LibreWolf
  - [ ] SRware Iron
  - [ ] Dissenter
  - [ ] Slimjet
  - [ ] Midori
  - [ ] Edge
  - [ ] Lynx

**Comment by mlehotskylf** [comment]
@nickmango please update the status of this ticket and add the link to the PR, if exists.

**Comment by mlehotskylf** [comment]
Fix done in DEV testing will be done soon.

**Comment by jarias-lfx** [comment]
@thakurveerendras have the following scenario being considered?:
1- Rename the GitHub organization.
2- Check PCC if the organization name is updated.
3- Have EasyCLA enforced auto-enable in PCC.
4- Add a new repository.
5- Confirm the repo gets added to EasyCLA automatically.

**Comment by mlehotskylf** [comment]
@umeshlumbhani247 is working on this.

**Comment by umeshlumbhani247** [comment]
@thakurveerendras 
Please test this issue, Also need to confirm the icla/ccla sign flows as well

**Comment by thakurveerendras** [comment]
Tested issue on dev site & found following behaviour 

1- Rename the GitHub organization.
2- Check PCC if the organization name is updated

> Issue: Old organization name remain

3- Have EasyCLA enforced auto-enable in PCC.
4- Add a new repository.
5- Confirm the repo gets added to EasyCLA automatically.

> Issue: EasyCLA remain unchecked 

![image](https://github.com/communitybridge/easycla/assets/75417507/b63e5d71-e7d4-4f6e-94f0-2c5c6753fc4f)

**Comment by nickmango** [comment]
@umeshlumbhani247 has raised a PR for this.. Kindly verify. The icla/ccla sign flows need to get verified as well as there was an update on this fix

**Comment by umeshlumbhani247** [comment]
@thakurveerendras 
It's a different scenario, I have fixed according to the issue description.

**Comment by thakurveerendras** [comment]
Tested the original case mentioned in the descriptions & found that it is fixed as expected. 
Added separate ticket for failed case https://github.com/communitybridge/easycla/issues/4272

**Comment by thakurveerendras** [comment]
Tested issue on prod & found that it is fixed, So closing this ticket
Refer to the video clip:  [4137.webm](https://github.com/communitybridge/easycla/assets/75417507/a737bbb7-3445-45dd-9548-2ed0beb3d4e1)
