### ISSUE TITLE
Cla groups are not loading on PCC cla page

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#4202]
## Summary

Cla group is not loading on PCC

## Background

1. Login admin portal
2. Search & open SUN project
3. Go to tools --> easycla page

## Expected behavior

cla page should load with full details

## Actual behavior

An error occurred while fetching CLA Groups

## Screenshots

![image](https://github.com/communitybridge/easycla/assets/75417507/02ec35af-c63d-4ce3-875c-cc18d5e4266e)

`URL: https://v1.pcc.dev.platform.linuxfoundation.org/project/a09P000000DsCE5IAN/tools/easycla/overview

Time: December 1, 2023 at 2:05:44 PM GMT+5

Error: {"headers":{"normalizedNames":{},"lazyUpdate":null},"status":501,"statusText":"OK","url":"https://pcc-bff.dev.platform.linuxfoundation.org/development/api/cla-services/cla-groups/a09P000000DsCE5IAN","ok":false,"name":"HttpErrorResponse","message":"Http failure response for https://pcc-bff.dev.platform.linuxfoundation.org/development/api/cla-services/cla-groups/a09P000000DsCE5IAN: 501 OK","error":{"status":501,"stack":"","details":null,"message":"","code":"error","requestId":"","data":{}}} 

Additional Information: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36`

**Comment by thakurveerendras** [comment]
Retested the issue on the dev site and found that it is fixed as expected. So making issue status QA-Done

**Comment by mlehotskylf** [comment]
This is resolved, so closing.
