### ISSUE TITLE
Duplicate ICLAs records added at signature table 

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#4210]
## Summary

Duplicate ICLAs records added at the signature table 

## Background

1. Create GitHub PR 
2. Docu-signed IClA 
3. See-Signature records are created at PCC 
4. Repeat Steps for another PR
5. See-Duplicate ICLAs records added at the signature table 

- Link: https://v1.pcc.dev.platform.linuxfoundation.org/project/a09P000000DsCE5IAN/tools/easycla/overview/01af041c-fa69-4052-a23c-fb8c1d3bef24/signatures

## Screenshots
![image](https://github.com/communitybridge/easycla/assets/75417507/3605be1c-fd93-4773-a45f-f2108d6f8595)

**Comment by mlehotskylf** [comment]
According to @nickmango, this is fixed so moving to QA.

**Comment by thakurveerendras** [comment]
Issue is not reproducible on dev site as reported, So updating issue status

**Comment by thakurveerendras** [comment]
It is not reproducible on prod env, So closing this ticket 
![image](https://github.com/communitybridge/easycla/assets/75417507/8efd9cba-5fea-466a-bf2b-1fa2a36f344e)
