### ISSUE TITLE
EasyCLA GitLab: after docu-signed MR remains uncovered in the ICLA flow 

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#4222]
## Summary

EasyCLA GitLab: after docu signed MR remains uncovered in the ICLA flow 

## Background

1. Create a new GitLab branch
2. Create new MR(cla gated)
3. Click on the Not Covered button
4. proceed as 'Individual Contributor'
5. Fill document & finish it
6. Add /esycla comment on MR

## Actual behavior

EasyCLA GitLab: after docu signed MR remains uncovered in the ICLA flow 

## Screenshots
![image](https://github.com/communitybridge/easycla/assets/75417507/6adbc1fb-3e2a-4c87-871b-0586b42a11c9)

**Comment by nickmango** [comment]
@thakurveerendras kindly verify this

**Comment by thakurveerendras** [comment]
@nickmango , Issue is still reproducible as reported on dev site
Refer the MR: https://gitlab.com/gitlabcommenttest/repo/-/merge_requests/14
![image](https://github.com/communitybridge/easycla/assets/75417507/526a726a-fce4-405f-b11b-5cd7c3fc0215)

**Comment by mlehotskylf** [comment]
@nickmango please review this fix.

**Comment by thakurveerendras** [comment]
Issue is not reproducible as reported, Now status is properly updated after docusigned 
![image](https://github.com/communitybridge/easycla/assets/75417507/dafe41cc-aeb4-43b3-aa32-b73df3bbebc5)

**Comment by thakurveerendras** [comment]
Tested on prod & it is working fine. So closing this ticket
Refer PR: https://gitlab.com/feb15prod/repo01/-/merge_requests/1#notes
