### ISSUE TITLE
Setup Gerrit instance for testing

### ISSUE THREAD

**Issue by mlehotskylf** [communitybridge/easycla#4226]
Setup Gerrit instance for testing

**Comment by nickmango** [comment]
The gerrit instance is setup for testing

**Comment by thakurveerendras** [comment]
Tested the setup on the dev site & found that it is fixed as expected.
Refer to the video clip: [GerritiCLA.webm](https://github.com/communitybridge/easycla/assets/75417507/11079314-9d4e-4fae-8e7f-259295b04804)
