### ISSUE TITLE
EasyCLA : Permissions need to be updated while adding Github org.

### ISSUE THREAD

**Issue by PoojaPanjwani204** [communitybridge/easycla#4227]
## Summary

Whenever user tries to add any Github Org to a project, dashboard is throwing an error.

## Background
1. Open EasyCla GitHub Tab by click on Manage button
2. Enter GitHub Org URL & click on connect button

## Actual Behavior
Its not accepting the any org name & throwing error.
![image (16)](https://github.com/communitybridge/easycla/assets/87165074/a1d25274-de7d-4d8b-9a93-699f1699bf25)
cc : @thakurveerendras

**Comment by mlehotskylf** [comment]
@thakurveerendras we missed updating GitHub token for `US East 2` in DEV. We fixed it and now this should be working as expected.

**Comment by thakurveerendras** [comment]
Tested the issue on the dev site & found that it is working fine after fixing the GitHub token key as mentioned above, So moving this ticket to Done state
![image](https://github.com/communitybridge/easycla/assets/75417507/4f995772-0d5b-465f-87fb-78bb2ae684a4)

**Comment by mlehotskylf** [comment]
This is done, so closing.
