### ISSUE TITLE
EasyCLA: User added under approval list not display under approval list at corporate console 

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#4228]
## Summary

EasyCLA: User added under approval list not displayed under approval list at the corporate console 

## Background

1. Login the corporate console 
2. Signed CCLA
3. Go to approval list 
4. Add new GitHub user under approval list
5. See-Conformation prompt appears

## Actual behavior
User not listed under approval list

Tested on project 
https://lfx.dev.platform.linuxfoundation.org/foundation/lfkauxIKb6zTkiS3B0/cla
https://lfx.dev.platform.linuxfoundation.org/foundation/a09P000000DsCE5IAN/project/a09P000000DsCEtIAN/cla?cclaSigned=true

## Screenshots
[approvalList_01.webm](https://github.com/communitybridge/easycla/assets/75417507/594d0b2f-6e62-435b-a1ab-51d28c40da28)

**Comment by mlehotskylf** [comment]
@nickmango to investigate if this is UI or backend issue.

**Comment by nickmango** [comment]
@mlehotskylf this happens to be a UI issue as the backend is returning the approval list criteria for the Venus project as evidenced below

{
    "projectID": "032a4e39-c5c9-4653-8bdd-202c7257ed45",
    "resultCount": 1,
    "signatures": [
        {
            "autoCreateECLA": false,
            "claType": "ccla",
            "companyName": "Infosys Limited",
            "created": "2024-02-02T12:50:02Z",
            "domainApprovalList": null,
            "emailApprovalList": null,
            "githubOrgApprovalList": null,
            "githubUsernameApprovalList": [
                "thakurveerendras1",
                "vrthakur",
                "proximapooja",
                "thakurveerendras",
                "nickmango"
            ],
            "gitlabOrgApprovalList": null,
            "gitlabUsernameApprovalList": null,
            "modified": "2024-02-02 12:51:09.606180366 +0000 UTC m=+82.901083284",
            "projectID": "032a4e39-c5c9-4653-8bdd-202c7257ed45",
            "signatoryName": "vthakur lf",
            "signatureACL": [
                {
                    "companyID": "f7c7ac9c-4dbf-4104-ab3f-6b38a26d82dc",
                    "dateCreated": "2023-03-22T10:31:40Z",
                    "dateModified": "2023-03-22T10:31:40Z",
                    "emails": null,
                    "lfEmail": "vthakur@contractor.linuxfoundation.org",
                    "lfUsername": "vthakur",
                    "note": "auto assign companyID from CLA Manager adding user to the company approval list with auto_create_ecla feature flag set to true on 2023-04-04T16:41:48Z.",
                    "userID": "bbaafb33-c89c-11ed-bb8c-12da8d3ce790",
                    "username": "(vthakur)  Singh@Thakur",
                    "version": "v1"
                }
            ],
            "signatureApproved": true,
            "signatureCreated": "2024-02-02T12:50:02Z",
            "signatureDocumentMajorVersion": "2",
            "signatureDocumentMinorVersion": "1",
            "signatureID": "70dfd215-16a0-4529-91dc-9618820c0917",
            "signatureModified": "2024-02-02 12:51:09.606180366 +0000 UTC m=+82.901083284",
            "signatureReferenceID": "0014100000Te0G7AAJ",
            "signatureReferenceName": "Infosys Limited",
            "signatureReferenceNameLower": "infosys limited",
            "signatureReferenceType": "company",
            "signatureSigned": true,
            "signatureType": "ccla",
            "signedOn": "2024-02-02T12:51:10Z",
            "signingEntityName": "Infosys Limited",
            "userDocusignDateSigned": "2024-02-02T04:50:46.237",
            "version": "2.1"
        }
    ],
    "totalCount": 1
}
I added `nickmango` under the `githubUsernameApprovalList` which is not getting shown on the UI . Will need to touch base with Sudahakars team to assist in resolving this

**Comment by mlehotskylf** [comment]
I reached out to Sudhakar and team in Slack: https://linuxfoundation.slack.com/archives/C058V7Z2BTR/p1707170988023899

**Comment by sudhakar-proxima** [comment]
I added myself as CLA Manager for this same Project | Organization combination. Then added one my github username as approval criteria. I was able to add it successfully. Also, I see all the previous entries of other approval criteria that were added by others. So I am not sure what is the issue here. Please note that there are no changes to master branch for a long time.
![image](https://github.com/communitybridge/easycla/assets/60137699/9d58989c-f2d5-4ce7-8160-b9e6c9b8a024)

![image](https://github.com/communitybridge/easycla/assets/60137699/15c1fd81-923f-43c7-8865-6ee569ac2e54)

**Comment by mlehotskylf** [comment]
@thakurveerendras and @nickmango to verify this issue as issue may be related to the timestamp format.

**Comment by sudhakar-proxima** [comment]
![image](https://github.com/communitybridge/easycla/assets/60137699/7f0129b9-0c24-4a34-892c-3cb762dcafa4)
Please check if there is any changes in the response wrt Date format.

**Comment by thakurveerendras** [comment]
The root cause of this issue is the wrong "date_modified" format. it will automatically fix after fixes of the issue https://github.com/communitybridge/easycla/issues/4231

-  #4231

**Comment by nickmango** [comment]
This was a backend issue with the wrong format of date_modified when creating a new ccla signature. This has been fixed and is ready for testing

**Comment by thakurveerendras** [comment]
Tested with newly configured cclas project & found that it is working fine, So moving issue status 
![image](https://github.com/communitybridge/easycla/assets/75417507/dbaf8a46-a50d-486c-8c6d-c95a2e547b26)
