### ISSUE TITLE
Wrong GitLab user name added under the "Approval Request for contributor" email notification

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#4236]
## Summary

The wrong GitLab user name was added under the "Approval Request for Contributor" email notification

## Setup
Add a GitLab user with a different user name & full name say

- Full name: vthakur singh
- User name: vthakurgitlab 

## Background

1. Create Cla gated MR
2. Click on not covered 
3. click on Proceed as a corporate contributor 
4. Search company & select company 
5. See-Existing cla-manager list appears
6. Select cla-manager & request for Approval

## Expected behavior

The correct user name should added under the "Approval Request for contributor" email notification

## Screenshots
![image](https://github.com/communitybridge/easycla/assets/75417507/de9fce6b-6d85-4b0f-9fc0-b8251a345d94)
![image](https://github.com/communitybridge/easycla/assets/75417507/513eccb5-9ebc-46bf-8ee1-8b9670d0c466)

**Comment by nickmango** [comment]
@thakurveerendras this is not the user name per se of the Gitlab user.. But full names of the User

**Comment by nickmango** [comment]
Yes the email body says Username but it refers to the name in the easyCLA records and not the Gitlab user. Kindly verify in the db records

**Comment by mlehotskylf** [comment]
We believe nobody is using GitLab in PROD, @thakurveerendras can we decrease the priority of this issue? Thanks.

**Comment by mlehotskylf** [comment]
@nickmango is looking into this ticket.

**Comment by mlehotskylf** [comment]
We are blocked with invalid AWS key. @nickmango will work with DevOps to resolve it.

**Comment by mlehotskylf** [comment]
@nickmango was able to get new AWS key and deployed to DEV. @thakurveerendras please verify this fix.

**Comment by thakurveerendras** [comment]
Now proper string appears as discussed in the standup call, So updating this issue status

> Name/User Name: thakurveerendras1, GitLab User Name: thakurveerendras1, Emails: [veerendrat+1@proximabiz.com](mailto:veerendrat%2B1@proximabiz.com)

![image](https://github.com/communitybridge/easycla/assets/75417507/d9a13b92-0c6c-4969-8a47-3e53f1ca5cfc)

**Comment by thakurveerendras** [comment]
Verified the issue on prod & it is properly fixed
![image](https://github.com/communitybridge/easycla/assets/75417507/833208cb-3971-43b7-961c-eb02d170c88d)

**Comment by mlehotskylf** [comment]
This is done, closing.
