### ISSUE TITLE
EasyCLA Bug : Easycla bot comment missing at conversation tab

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#4243]
## Summary

- Easycla bot comment missing at conversation tab

## Background

1. Go to GitHub 
2. Add a new commit on the branch
3. Create PR
4. Add /easycla comment

## Expected behavior
![image](https://github.com/communitybridge/easycla/assets/75417507/b3afc746-7c07-4c74-ac2a-62014d7e4cfd)

## Actual
![image](https://github.com/communitybridge/easycla/assets/75417507/de4a0bf6-b3a0-4ad3-935f-7a9e7cb2de21)

**Comment by mlehotskylf** [comment]
@thakurveerendras is this still reproducible?

**Comment by mlehotskylf** [comment]
Correct behavior (it will not create the comment if EasyCLA passes on first time), so this is working as expected. @thakurveerendras already verified this so closing this ticket.
