### ISSUE TITLE
EasyCLA doc redirect from communitybridge.org produces 404

### ISSUE THREAD

**Issue by KennyPaul** [communitybridge/easycla#425]
## Summary

Following the EasyCLA doc link from the communitybridge site results in a 404.

## Background

- go to https://communitybridge.org/

- Click the "Docs" link from the menu bar at the top

- Either: 

1.  try to follow the getting started links in the blog entry and try to follow the "EasyCLA documentation is now available in GitHub"
**OR**

2. select CommunityBridge EasyCLA from the confluence menu and try to follow the links to the "The latest EasyCLA documentation is in GitHub"

Either one will produce a 404 error.

## Expected behavior

User should be redirected here: https://github.com/communitybridge/easycla/blob/master/getting-started/README.md

## Environment

Please complete the following information

* Environment: PROD
* OS: \[e.g. iOS\] all
* Browser \[e.g. chrome, safari\] any
* Version \[e.g. 22\] any

## Acceptance Criteria

The 404 error goes away.

**Comment by WillsonHG** [comment]
Both links have been changed to https://lf-docs-linux-foundation.gitbook.io/easycla/getting-started
