### ISSUE TITLE
Prod: Process stuck at "Configuring CLA Manager Settings" on contributor flow

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#4250]
## Summary

Prod: Process stuck at "Configuring CLA Manager Settings" on contributor flow

## Background
1. Create GitHub PR
2. Click on the **Not Covered** button
3. Click on "Process as a Corporate Contributor" button
4. Search & select the organization
5. Select 'YES' at "No Signed CLA Found"

> {
>     "errors": {
>         "missing_ccla": "Company does not have CCLA with this project.",
>         "company_id": "83f61e34-4457-45a6-a7ab-449ad6efcfbb",
>         "company_name": "Test_NDC",
>         "signing_entity_name": "Test_NDC",
>         "company_external_id": "0012M00002SAW0RQAX"
>     }
> }

## Expected behavior

User should procced to next step

## Screenshots

![image](https://github.com/communitybridge/easycla/assets/75417507/9bc4d7e8-2446-4a30-99ef-83961812d36d)

## Video
[Configuring CLA Manager Settings.webm](https://github.com/communitybridge/easycla/assets/75417507/aac09078-203c-410c-b37e-240d8c20f02b)

## Environment

* Environment:
  - [ ] ALL
  - [ ] DEV
  - [ ] STAGING
  - [x] PROD

**Comment by mlehotskylf** [comment]
@nickmango is looking into this.

**Comment by nickmango** [comment]
Assigning this to @amolsontakke3576 as the backend is returning the same result as in dev. However upon further investigation with @thakurveerendras and @amolsontakke3576  Amol was able to proceed while Veerendras user wasnt. This comes down to a possible data issue that needs investigation from the UI side
cc @mlehotskylf

**Comment by mlehotskylf** [comment]
Thank you @amolsontakke3576 for looking into this High Priority issue. Please keep us posted.

**Comment by amolsontakke3576** [comment]
Yes @mlehotskylf, it is working fine on prod with my user so checking in deeply with @thakurveerendras users where it was reproduced.

**Comment by mlehotskylf** [comment]
Thank you @amolsontakke3576 and @thakurveerendras . This seem to be specific for @thakurveerendras 's user and should not impact other customers so moving this back to the backlog.

**Comment by mlehotskylf** [comment]
@thakurveerendras does this issue still exist?

**Comment by mlehotskylf** [comment]
@thakurveerendras can you please review this? Thanks!

**Comment by thakurveerendras** [comment]
Hello @mlehotskylf 
I have confirmed that this is a data issue with my user Thakurveerendras on production, and all steps it work fine with another user vthakur, so we can close this ticket as a data issue.
CC: @nickmango , @amolsontakke3576
