### ISSUE TITLE
GitHub user also added when add new GitLab user under 'approved list'

### ISSUE THREAD

**Issue by thakurveerendras** [communitybridge/easycla#4258]
## Summary

GitHub user also added when GitLab user under 'approved list'
Existing GitHub user details also updated when add GitLab user

## Background

1. Go to the corporate CLA console 
2. Add a GitLab user under the approval list

## Expected behavior

Only GitLab users should be added to in list

## Screenshots

![image](https://github.com/communitybridge/easycla/assets/75417507/46b25f6c-48c2-4dd4-b374-d1b614c3dad6)

**Comment by mlehotskylf** [comment]
This is corner case so we will fix this in next release.

**Comment by nickmango** [comment]
@thakurveerendras this was an issue with the same date_added value which has been resolved in in #3750 . Kind verify

**Comment by thakurveerendras** [comment]
The issue is not reproducible as reported on the dev site, So closing this ticket
Refer to the screenshot
 
![image](https://github.com/communitybridge/easycla/assets/75417507/b3074711-c5b6-484d-880c-b3f852a7a4de)

**Comment by mlehotskylf** [comment]
Closing this ticket based on last comment.
