### ISSUE TITLE
Corporate Console: Clicking the pencil edit icon next to company name creates a NEW company

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#427]
## Summary

Corporate Console: Clicking the pencil edit icon next to company name creates a NEW company. This is unexpected behavior and may be contributing to unwanted duplicate companies in the system.

## Background

Log into corporate.lfcla.com as a cla manager. 
Click your company name
Click the pencil icon next to the company name.
Pop-up shows dialog to create a new company with the company name, manager name, and email. The button to submit shows the text "Add".
When Add is pressed, the dialog closes, you remain in your current company.
Going back to "All Companies" in the console shows the new company just created in the list.
Any signature or whitelisting data is not carried over from the previous company.

## Expected behavior

The pencil next to the name commonly indicates an edit. This should edit the current company's name, not create an entirely new company in the database.

Question: Is it acceptable for the CLA manager to edit the company's name?

**Comment by dealako** [comment]
Only the Company Manager (user must be in the `company_acl` list) should be allowed to change the company name.  Otherwise, the icon/feature should be hidden.

**Comment by dealako** [comment]
Currently - no user can edit the company name, which is fine for now. If users want to change the company name - then they can open a support ticket via https://support.linuxfoundation.org
