### ISSUE TITLE
Getting 502 during CCLA flow for Gerrit

### ISSUE THREAD

**Issue by jarias-lfx** [communitybridge/easycla#4273]
## Summary

Executing an ECLA (Acknowledgement) process for Gerrit, the user is getting a 502 error and is unable to process.

## Background

Steps:
1- Access project GerriT:
2- Select Configuration.
3- Select agreements.
4- Select new contributor agreement.
5- Select CCLA.
6- Select Please review the agreement.
7- Select Proceed to Corporate Authorization.
8- Search for the organization.
9- Select the organization and select proceed.
10- The user is unable to process.

## Expected behavior

The contributor should be prompted with the acknowledgement confirmation and be added to the CCLA LDAP group.

## Screenshots

Error:
![image](https://github.com/communitybridge/easycla/assets/93140557/707d6bc0-0346-4c9b-a47c-62b411e2e669)
![image](https://github.com/communitybridge/easycla/assets/93140557/2a555836-3817-4e27-a954-a00935416c45)

## Environment

* Environment:
  - [ ] ALL
  - [ ] DEV
  - [ ] STAGING
  - [x] PROD 
* Browser:
  - [x] Chrome/Brave
  - [ ] Firefox
  - [ ] Opera
  - [ ] Vivaldi
  - [ ] LibreWolf
  - [ ] SRware Iron
  - [ ] Dissenter
  - [ ] Slimjet
  - [ ] Midori
  - [ ] Edge
  - [ ] Lynx

**Comment by thakurveerendras** [comment]
Unable to replicate the same issue on the dev site, So updating this issue status.

- Tested on Gerrit client link: https://gerrit.linuxfoundation.org/infra/settings/new-agreement

> ![image](https://github.com/communitybridge/easycla/assets/75417507/4a373ce4-effd-4d42-9061-d03ee49dcb44)

**Comment by thakurveerendras** [comment]
Closing this ticket as it is working fine prod, Confirmed by [jarias-lfx](https://github.com/jarias-lfx) over the slack
![image](https://github.com/communitybridge/easycla/assets/75417507/d8367c4f-dc12-470b-9aa7-98a083eaabc3)
