### ISSUE TITLE
Enable Merge Queue feature

### ISSUE THREAD

**Issue by mlehotskylf** [communitybridge/easycla#4277]
Document and Enable Merge Queue feature

**Comment by nickmango** [comment]
Reviewing the test cases with @mlehotskylf in preparation for the release

**Comment by mlehotskylf** [comment]
@mlehotskylf is working with @nickmango on this.

**Comment by mlehotskylf** [comment]
I sent notification on Slack on Friday, May 3rd and I will sent another reminder by end of this week. We are planning to enable this feature on the week of May 20th.

**Comment by thakurveerendras** [comment]
Verified use case mentioned in documents on prod & found that feature is properly working on prod, So updating this ticket status

**Comment by mlehotskylf** [comment]
This is done, closing.
