### ISSUE TITLE
Project Console - GitHub Organization Card Problem

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#428]
## Summary

The Project Console has an issue rendering the GitHub Organization Card - shows duplicate cards.

## Background

While testing in DEV, it was discovered that the GitHub Organization card now renders multiple times.

Broken Screen Shot:
![image](https://user-images.githubusercontent.com/519609/70837669-938f0380-1db9-11ea-9ccf-3bcc98054801.png)

Typical/Desired ScreenShot:
![Screen Shot 2019-12-13 at 3 04 25 PM](https://user-images.githubusercontent.com/519609/70837743-e49ef780-1db9-11ea-8427-dd495f7493fb.png)

My guess is that the response model with the GitHub org details has changed slightly or the page rendering (HTML) has an issue.

## Expected behavior

See the above screen shots.

## Environment

Please complete the following information:

* Environment: DEV

## Additional Context

N/A

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities and fixes to the product team while the code is running in the DEV environment.

## References

N/A

**Comment by amolsontakke3576** [comment]
@dealako  It is an old ticket and now it's working fine so closing it.
