### ISSUE TITLE
Comment /easycla not working in tektoncd

### ISSUE THREAD

**Issue by jarias-lfx** [communitybridge/easycla#4303]
## Summary

Adding /easycla comment in a tektoncd PR is not triggering the EasyCLA bot.

## Background

The PR https://github.com/tektoncd/pipeline/pull/7892 has EasyCLA status as Expected. Adding /easycla didn't trigger any changes and the there is no information on the logs.
This is a filter since April 16th 2024 to April 26th 2024 9:40AM MT
https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:logs-insights$3FqueryDetail$3D~(end~'2024-04-26T15*3a40*3a00.000Z~start~'2024-04-16T15*3a00*3a00.000Z~timeType~'ABSOLUTE~tz~'LOCAL~editorString~'fields*20*40timestamp*2c*20*40message*2c*20*40logStream*2c*20*40log*0a*7c*20filter*20*40message*20like*20*22https*3a*2f*2fapi.github.com*2frepos*2ftektoncd*2fpipeline*2fpulls*2f7892*22*0a*7c*20sort*20*40timestamp*20asc*0a*7c*20limit*202000~queryId~'3810713df55691-193aeae-4ef3089-bcfa7e3-4b3d4e9986fc2f3c74bfc69~source~(~'*2faws*2flambda*2fcla-backend-prod-githubactivity))
![image](https://github.com/communitybridge/easycla/assets/93140557/d3ac4670-400e-4190-99fb-5eb02e30fd28)

## Expected behavior

Adding the comment /easycla should trigger the bot.

## Screenshots

![image](https://github.com/communitybridge/easycla/assets/93140557/4a6661f9-2676-4b1d-a4db-a0e07d1cd97e)

## Environment

Please complete the following information:

* Environment:
  - [ ] ALL
  - [ ] DEV
  - [ ] STAGING
  - [x] PROD 
* Browser:
  - [x] Chrome/Brave
  - [ ] Firefox
  - [ ] Opera
  - [ ] Vivaldi
  - [ ] LibreWolf
  - [ ] SRware Iron
  - [ ] Dissenter
  - [ ] Slimjet
  - [ ] Midori
  - [ ] Edge
  - [ ] Lynx

**Comment by mlehotskylf** [comment]
According to @jarias-lfx, this issue is happening only for this project and we have this issue for at least 2 years. @jarias-lfx already checked DB and all data looks ok.

**Comment by nickmango** [comment]
@mlehotskylf currently unable to reproduce this issue and identify the root cause as logs arent reflecting for this specific project so leaving this in blocked state

**Comment by nickmango** [comment]
Moved this to Later as issue is currently not reproducible

**Comment by nickmango** [comment]
@jarias-lfx the query is if there has been a configuration on the tektoncd project , either via a bot ,script or Github Action workflow, that has been configured to ignore comments from an external service like easycla .

**Comment by mlehotskylf** [comment]
@jarias-lfx to communicate to the customer that comments are probably not allowed for repo which is causing this issue.

**Comment by jarias-lfx** [comment]
User requested to close the issue.
