### ISSUE TITLE
Consider EasyCLA acceptance for private accounts

### ISSUE THREAD

**Issue by jarias-lfx** [communitybridge/easycla#4337]
## Summary

Currently EasyCLA fetches the user details from Github, where the GitHub account needs to be in some form public. Please consider adding private details from the contributor EasyCLA approval, especially for CCLA.

For example in CCLA approval criteria the email address is not specific to the GitHub account it just says, email address, which could apply for private accounts.
![image](https://github.com/communitybridge/easycla/assets/93140557/88213122-b513-4509-ab23-21368d898bfa)

**Comment by nickmango** [comment]
@jarias-lfx kindly expound on this. For private emails we cant fetch the details from the repository provider
cc @mlehotskylf

**Comment by mlehotskylf** [comment]
@nickmango If this can't be implemented as requested I would suggest to close this as "Won't do".

**Comment by mlehotskylf** [comment]
Closing.
