### ISSUE TITLE
Investigate the discrepancy between authorized users in LDAP and EasyCLA

### ISSUE THREAD

**Issue by mlehotskylf** [communitybridge/easycla#4394]
Investigate the discrepancy between authorized users in LDAP and in EasyCLA

More info: https://docs.google.com/document/d/1WFBjBC-_EYBNmaVTWIvAJ3ygMI0C-npV9GMXF2CgPYg/edit#heading=h.dopp1s54sg26

**Comment by nickmango** [comment]
Resolved the issue regarding ecla fetches for users that was a part cause for the discrepancy. This is to be verified by Eric in his script file that checks the authorized api.
cc @mlehotskylf

**Comment by mlehotskylf** [comment]
@nickmango to review EasyCLA event log and find if any of these users (which are on LDAP only) have any records there being added as contributors or CLA managers.

**Comment by mlehotskylf** [comment]
See [4451](https://github.com/communitybridge/easycla/issues/4451) for more details.

**Comment by mlehotskylf** [comment]
We already know the discrepancy between LDAP and EasyCLA and its reason so closing this ticket. Next step will be review users which are not authorized by EasyCLA one by one and fix their record in DynamoDB and ask them to fix it. This will be tracked in separate ticket.
