### ISSUE TITLE
Unable to add CLA Managers via CLA Corporate Console

### ISSUE THREAD

**Issue by jarias-lfx** [communitybridge/easycla#4404]
## Summary

Adding a CLA Manager is failing in the CLA Corporate Console

## Background

Previous report on https://github.com/communitybridge/easycla/issues/4373 the CLA Managers and other issues with users service was reported. While the issue was resolved, we found our that adding a CLA Manager is failing:
```
{
    "data": {
        "addNewClaManager": {
            "code": 400,
            "message": "User <redacted for PII> has no LF Login account. User can be added as CLA Manager after LF Login is created",
            "success": false,
            "newManager": null,
            "__typename": "AddClaManagerResult"
        }
    }
}
```
Payload:
```
{"operationName":"addNewClaManager","variables":{"input":{"projectId":"a0941000002wBz4AAE","companyId":"644b311e-a7d9-4060-b6df-a264a2479332","firstName":"<REDACTED>","lastName":"<REDACTED>","userEmail":"<REDACRED>"}},"query":"mutation addNewClaManager($input: AddClaManagerInput!) {\n  addNewClaManager(input: $input) {\n    code\n    message\n    success\n    newManager {\n      existingUser\n      approvedOn\n      lfUsername\n      name\n      email\n      claGroupName\n      organizationName\n      organizationSfid\n      projectId\n      projectName\n      projectSfid\n      userSfid\n      __typename\n    }\n    __typename\n  }\n}\n"}
```
Frontend: https://linuxfoundation.atlassian.net/browse/CD-2587

## Expected behavior

CLA Manager should be added

## Environment

Please complete the following information:

* Environment:
  - [ ] ALL
  - [ ] DEV
  - [ ] STAGING
  - [x] PROD 
* Browser:
  - [x] Chrome/Brave

**Comment by thakurveerendras** [comment]
Tested on the dev site and found that it is working fine

Refer screenshot for more details
![image](https://github.com/user-attachments/assets/2a16f749-af58-49c1-82d5-3787f48a2bbb)

**Comment by thakurveerendras** [comment]
Tested on production and found that it is working fine, So updating this issue status

**Comment by mlehotskylf** [comment]
This is in PROD now. Closing.
