### ISSUE TITLE
Corporate Console>>Request new CLA manager :User is unable to create new CLA manager

### ISSUE THREAD

**Issue by kdhaigud** [communitybridge/easycla#455]
## Summary

Getting error status as 400 while creating new CLA manager 

https://api.dev.lfcla.com/v3/onboard/notification

Reponse :
`{  
   "Code":"400",
   "Message":"Bad Request - unable to send notification to recipients: [kdhaigud@proximabiz.com], error: AuthorizationError: User: arn:aws:sts::395594542180:assumed-role/cla-backend-dev-us-east-1-lambdaRole/cla-backend-dev-apiv3 is not authorized to perform: SNS:Publish on resource: arn:aws:sns:us-east-1:395594542180:lfx-topic-dev-email-events\n\tstatus code: 403, request id: d31d24eb-8e99-5444-b5c0-72906df2945b"
}`

## Background

Provide context to the issue - provide steps to reproduce the behavior, such as:

1. Go to 'Corporate Console'
2. Click on 'Get started'
3. Enter all the details in 'Request new CLA manager'
4. Click on submit

## Expected behavior

User should be able to create new CLA manager

## Screenshots

[create CLA manager.zip](https://github.com/communitybridge/easycla/files/3998829/create.CLA.manager.zip)

**Comment by dealako** [comment]
This is related to a missing set of permissions for the backend lambdas -> SNS Topic Publish.  I have added the required permission via PR #456. @kdhaigud, how that this PR is merged and deployed to DEV can you re-test (in DEV)?

**Comment by kdhaigud** [comment]
@dealako 'Request new CLA manager' pop up is not getting open after clicking on 'Get started'
[CLA manager pop up.zip](https://github.com/communitybridge/easycla/files/4009712/CLA.manager.pop.up.zip)

**Comment by dealako** [comment]
Resolved - closing issue.
