### ISSUE TITLE
Project Console >>CLA Groups : “View Companies” CTA is displayed two times

### ISSUE THREAD

**Issue by kdhaigud** [communitybridge/easycla#464]
## Summary

“View Companies”  CTA  is coming multiple times

## Background

Provide context to the issue - provide steps to reproduce the behavior, such as:

1. Install the EasyCLA Application.
2. Add a CLA Group.
3. Add Contributor License Agreements.

## Expected behavior

“View Companies” CTA  should be displayed only once

## Screenshots

![View Companies](https://user-images.githubusercontent.com/52558085/71640385-e79d5180-2cae-11ea-9930-26e67568a189.png)

**Comment by WillsonHG** [comment]
this is fixed in prod.
