### ISSUE TITLE
Project Console >>View CLA PDF : CLA PDF should get open after user click on PDF icon

### ISSUE THREAD

**Issue by kdhaigud** [communitybridge/easycla#465]
## Summary
 CLA PDF  is getting download but blank screen is getting open after clicking on the pdf icon 

## Background

1. Install the EasyCLA Application.
2. Add a CLA Group.
3. Add Contributor License Agreements.
4. Click on PDF icon

## Expected behavior
It should display pdf preview instead of blank page or if its only going to download pdf then don't show blank page 

## Screenshots
[pdf download.zip](https://github.com/communitybridge/easycla/files/4013950/pdf.download.zip)

**Comment by dealako** [comment]
Need to confirm/validate.

**Comment by dealako** [comment]
@hnexokonkwo this one is a non-critical bug but would appreciate your opinion on this issue. Within the project console, Project Managers can create and view the legal documents they generate or have on file. When the Project Manager clicks on a previously generated PDF document (or a newly generated PDF document), in our world these are called CCLA or ICLA, different browsers behave differently. Ideally, we would have a consistent user experience for our users.  A previous implementation used iframes to embed the PDF into the page for viewing.  Now, iframes are being blocked by some browsers in different contexts and do not always work across all platforms.  The iframe logic was removed and replaced with default browser handling/behavior.

If possible, research a technique or library to render the PDF within the browser with an option to download.

@WillsonHG or I can help you with examples/use-cases/feedback if needed.

**Comment by hnexokonkwo** [comment]
@nirupamav  pushed to DEV, ready for review/QA.

**Comment by nirupamav** [comment]
@hnexokonkwo @dealako 
Tested and observed that the files are downloaded or viewed based on the browser settings 

**When the pdf is previewed in the browser, pdf is opened in the same browser tab and user has to navigate back to Project Management console.
Can the pdf be displayed in another tab for usability purpose**

_NOTE:,When browser setting is Always Ask for Pdf file, and when user clicks on PDF download and selects open the file is opened in new tab_

**Comment by nirupamav** [comment]
@dealako  @hnexokonkwo 

**_Observed that in Mac Safari browser, generated template is embedded within the UI. But in Windows machine Chrome/FF/Edge below error is displayed in the console and template is not embedded in the UI. 
Also based on the issue raised in above comments, template is opened in another tab when clicked in download. If template is embedded in the UI displaying the template i another tab does not make sense. Should we just download the template in this scenario or could you please let me know how the flow should be based in browser settings for downloading files_**
![image](https://user-images.githubusercontent.com/60865903/77907830-fa242880-72a7-11ea-8b53-3ab73a89b93d.png)

**Comment by dealako** [comment]
The old console is deprecated and removed.
