### ISSUE TITLE
Corporate Console>>Request new CLA manager:Pop up title should be “Request new CLA manager” instead of  “Request CLA manager Request”

### ISSUE THREAD

**Issue by kdhaigud** [communitybridge/easycla#466]
## Summary

Text Request is displayed multiple times in pop up title

## Expected behavior

Pop up title should be “Request new CLA manager” instead of  “Request CLA manager Request”

## Screenshots

![Screenshot from 2020-01-01 15-19-58](https://user-images.githubusercontent.com/52558085/71640486-fab12100-2cb0-11ea-953d-7ccad52cdb26.png)

**Comment by WillsonHG** [comment]
This page has been completely redesigned.
