### ISSUE TITLE
Fix support links on lfcla.com

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#470]
## Summary

Get Access link gives Error 404 on contributor, project and corporate console. This link needs to be fixed. 
![image](https://user-images.githubusercontent.com/57362064/71743053-2a833480-2e29-11ea-9c25-faf35af00dea.png)

## Expected behavior

Please update the hyperlink to the following url
https://lf-docs-linux-foundation.gitbook.io/easycla/getting-started/get-access-to-easycla

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. when we click on "Get Access" link it works.

## References

\(Optional\) Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by dealako** [comment]
This appears to be fixed in DEV and STAGING. This fix will be included in the next PROD release.
