### ISSUE TITLE
Track CCLA Whitelist Requests

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#477]
## Summary

Track CCLA Whitelist Requests

## Background

Currently, an email is sent when a corporate user navigates to the contributor console and requests to be whitelisted. Once this email is sent, the EasyCLA system is unable to track the process of the request. Stakeholders have requested that we add the ability to save the request details and later present the request to the Project/Company CLA Managers for review/action.

## User Story

As a corporate contributor, I would like the Project/Corporate CLA manager to review my whitelist request.
As a CLA Manager, I would like to see my Project/Corporate whitelist requests within the Corporate Console.
As a CLA Manager, I would like to dismiss/delete a given whitelist request within the Corporate Console.

### Backend
- [x] Create a database table, index, infra config for DEV, STAGING, and PROD deployment. Suggested table columns include: Project ID/Project Name, Repository, Company ID/Company Name, Requestor info (such as ghid, gh email, and any other details we can grab from GH auth flow), status (pending, dismissed), version, date/time created, date/time updated, dismissed
Type of request (e.g. whitelist request)
- [x] Create an API endpoint to add/create whitelist requests
- [x] Create an API endpoint to search/fetch requests (to support UX for LF Admin and CLA Managers)
- [x] Create an API endpoint to delete/dismiss requests (to support UX for LF Admin and CLA Managers)
- [x] Update API event log with the request and dismissal actions

### Frontend
- [x] Update the CLA service interface to allow the UX to create a new whitelist request for a given Project/Company
- [x] Update the CLA service interface to allow the UX to fetch the whitelist requests for a given Project/Company
- [x] Update the CLA service interface to allow the UX to dismiss/delete a whitelist requests for a given Project/Company
- [x] Update the contributor console to save the whitelist request when a contributor makes the request
- [x] Update the corporate console to show the list of whitelist requests for a given project/company
- [ ] Update the corporate console to allow the CLA manager to dismiss/delete a whitelist request for a given project/company

## Acceptance Criteria

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

N/A

**Comment by dealako** [comment]
@ngozi-ekekwe the backend is merged - you can now work on the UI side.

**Comment by dealako** [comment]
@ngozi-ekekwe - work with @prasannamahajan as he wrote the backend changes necessary for the frontend.

**Comment by dealako** [comment]
@prasannamahajan - I think we still need to add a hook to add an entry on the Contributor Console - correct?  This issue is:

1. Users are not authenticated in the Contrib Console
2. Because of this, we can not make the authenticated API request to create WL request

Please confirm.  We need to figure out a solution to this.

**Comment by prasannamahajan** [comment]
Yes. @dealako 
We cannot make authenticated request as we do not use lf authentication on contributor console.
We do use github authentication on contributor console during signing flow. But that is present in python backend where as addCclaWhitelist Request is present in go backend.

**Comment by prasannamahajan** [comment]
@dealako We also have to create api to accept cclaWhitelistRequest.
This can be done by whitelisting user by email or github_username.

**Comment by nirupamav** [comment]
Testing In Progress 
Logged bugs #782, #780, 779, #768, #657, #596, #593, #588, #581,
