### ISSUE TITLE
Add Diagram for EasyCLA Release Process

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#491]
## Impacted Docs

Update documentation to include the EasyCLA release process.

## Tasks

* [ ] include the attached image in the public documentation

## Verbiage

"The following diagram illustrates the EasyCLA release process"

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Documentation changes submitted as a Pull Request
1. Pull Request Reviewed and Approved by Product Owner
1. Documentation changes merged to 'master' branch

## Images

![EasyCLA Software Development and Release Process](https://user-images.githubusercontent.com/519609/72281081-99614a00-35ee-11ea-8c76-8088de0b3d37.png)

**Comment by WillsonHG** [comment]
@dibyaranjanlf this release diagram and the architecture diagram 
![image](https://user-images.githubusercontent.com/46732999/73697540-d039f580-46ac-11ea-9cb2-97f0ad2bd380.png) would be best moved to https://lf-docs-linux-foundation.gitbook.io/easycla/

**Comment by WillsonHG** [comment]
@dibyaranjanlf  Thanks for moving the architecture diagram. Please also move the release process diagram to https://lf-docs-linux-foundation.gitbook.io/easycla/ and put it underneath the architecture diagram and I think that will be it :)

**Comment by WillsonHG** [comment]
thank you!
