### ISSUE TITLE
Documentation - Architecture README Fix

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#512]
## Summary

There is an issue with several of the documentation pages (see references). The links/diagrams within the documents appear to be broken.

## Task

- [ ] Update the architecture readme links/diagrams.

## Acceptance Criteria

Documentation links in this folder work rendered properly and all links are valid.

## References

- https://github.com/communitybridge/easycla/blob/master/docs/architecture.md
- https://github.com/communitybridge/easycla/blob/master/docs/whitelist-github-bots.md

**Comment by WillsonHG** [comment]
@dibyaranjanlf 
looks like the github Bot whitelist link at the bottom is still returning a 404. 
https://github.com/communitybridge/easycla/blob/master/docs/whitelist-github-bots.md

**Comment by WillsonHG** [comment]
@dealako I think everything is fixed, do you want to review the diagram and make sure?

**Comment by dealako** [comment]
Closed issue.
