### ISSUE TITLE
EasyCLA console UI unresponsive (on-going caching issues)

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#526]
## Summary

A user clicks a button or another part of the UI in any of the consoles and it is unresponsive. A user must do one of the following: clear their browser cache, right click --> inspect --> network tab --> disable cache, open a private/incognito browser, etc. for the UI to respond. 

## Background
This is an ongoing, intermittent issue for users of EasyCLA. This Issue is to track and document occurrences as they happen with screenshots of the errors from inspecting the page and looking at the console or network sections.

## Screenshots

I will add screenshots as the issue happens. Anyone is welcome to add screenshots.

## Environment

Please complete the following information:

* Environment: DEV, STAGING and PROD 
* OS: any/all
* Browser : any/all

## References

https://github.com/communitybridge/easycla/blob/master/docs/cla-troubleshooting.md

CLA Management Console Data Does Not Load
The CLA Management Console data may not load due to a bug in the Auth0 implementation.

**Comment by WillsonHG** [comment]
@pranab-bajpai

**Comment by WillsonHG** [comment]
Navigated to corporate.lfcla.com
Spinning UI, nothing loads until cache is disabled and page refreshed
![image](https://user-images.githubusercontent.com/46732999/73690124-ad541500-469d-11ea-8d2f-c9daa78e5e62.png)

**Comment by WillsonHG** [comment]
After release https://github.com/communitybridge/easycla/releases/tag/v0.1.81.p16

corporate console: 
Select company -> select any signed CLA 
![image](https://user-images.githubusercontent.com/46732999/74179599-c6b01080-4c0b-11ea-9faf-a79f36c0e82d.png)

**Comment by WillsonHG** [comment]
corporate console:
Select company - > Sign new cla - > select project -> select "no" 
![image](https://user-images.githubusercontent.com/46732999/74293515-145e7300-4d09-11ea-9ba4-b771f8515140.png)

**Comment by dealako** [comment]
@WillsonHG thinks this may be correlated to new releases.
1. Use EasyCLA in DEV, STAGING or PROD
2. Publish a new release to DEV, STAGING, PROD
3. Continue using the application after the release - BOOM - see this error

We do attempt to invalidate the CloudFront cache when we deploy.  Is this related to login session/auth0 - or...is this related to the infrastructure serving up the application from CF?
