### ISSUE TITLE
EasyCLA system should send an email to all CLA Managers when whitelist is updated

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#531]
Email shall be sent to all existing CLA Managers whenever whitelist is changed by any CLA Manager. This change could be insert/update or delete of whitelist. 
Email should be as follows:

-----------------------------------------------

This is the notify that EasyCLA whitelist for your organization <company name>was modified. The modification was as follows:
`If addition to the whitelist
   following value was added to the whitelist <value>
if update to the whitelist
  record <old value> was updated to <new value>
if delete from the whitelist
  following value was deleted from the whitelist <value>`

Thanks,
EasyCLA System

**Comment by dealako** [comment]
@prasannamahajan please review the API call where we add/delete corporate console whitelist entries (go backend, I believe). Here, I am currently adding additional functionality to audit the event. We can also use this point in the code to send an email to the contributor (via the Platform Core Service email service) for both types of events (for example):
1) email that says: you were added to Project X Company Y Whitelist by CLA Manager Z
2) email that says: you were removed from Project X Company Y Whitelist by CLA Manager Z

Please coordinate with @pranab-bajpai on the exact details of the email (subject, body).

**Comment by dealako** [comment]
This was merged as part of PR https://github.com/communitybridge/easycla/pull/557. Ready to test in DEV.

**Comment by dealako** [comment]
Reviewed - Closing during sprint backlog review meeting.
