### ISSUE TITLE
Project Console: View Signatures shows signatures that == false 

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#543]
## Summary

In the "View Signatures" table in the project console, the table displays signatures that have not been completed and show signature as "false" in database. These signature entries do not have a cla or icla on file and do not pass a pull request check.

## Background

Provide context to the issue - provide steps to reproduce the behavior, such as:

1. Go to project.lfcla.com
1. Click on a project of interest --> CLA group --> and select "View Signatures"

## Expected behavior

This table should only show those signature entries that have been completed and are valid.

## Screenshots

Database entries 
![image](https://user-images.githubusercontent.com/46732999/73571345-556aa380-443c-11ea-8402-894119d4bf1d.png)
Console view
![image](https://user-images.githubusercontent.com/46732999/73571559-dd50ad80-443c-11ea-8c74-aae4f6bc47e9.png)

## Environment

Please complete the following information:

* Environment: PROD

**Comment by dealako** [comment]
@wanyaland Please review the Python and Golang Backend for ensuring that signatures are always returned approved == true and signed == true.

See https://github.com/communitybridge/easycla/tree/master/cla-backend-go/signatures for Gobackend.
