### ISSUE TITLE
Corporate Console : New user is not able to login in corporate console

### ISSUE THREAD

**Issue by kdhaigud** [communitybridge/easycla#552]
## Summary

In corporate console, A new user is trying to login, he is getting redirected to login page again. 

## Background
Create new user and login to corporate console

## Expected behavior

User should be able to login

## Screenshots

![Screenshot from 2020-02-04 19-27-21](https://user-images.githubusercontent.com/52558085/73754683-c1297500-478a-11ea-9370-0224f2044c6b.png)
[Corporate_new_user.zip](https://github.com/communitybridge/easycla/files/4154043/Corporate_new_user.zip)

**Comment by dealako** [comment]
We need to ensure new users are able to authenticate with auth0 then navigate into EasyCLA - during the first time, a new user record should be created in cla-{stage}-users.

**Comment by dealako** [comment]
@ngozi-ekekwe can we re-test this.  Scenario:
- Create a test LFID account in DEV
- Remove the LFID user from the cla-dev-users table
- Attempt to login
- Confirm that the user record was re-created (or not)

**Comment by amolsontakke3576** [comment]
@dealako @prasannamahajan @wanyaland Error while creating new user.
Request URL: https://api.dev.lfcla.com/v3/users
Request Method: POST
Status Code: 401 

Input : 
```
{
  "lfUsername": "amolsontakke",
  "username": "Amol Santakke",
  "lfEmail": "amols@proximabiz.com"
}
```

Response : 

`{"Message":"auth - UsersAddUserHandler - user &{UserID: Name: Emails:[] LFEmail: LFUsername:amolsontakke LfidProvider:{ProviderUserID:} GithubProvider:{ProviderUserID:} ProjectIDs:[] ClaIDs:[] CompanyIDs:[]} not authorized to add users - missing UserID"}`

**Comment by dealako** [comment]
@prasannamahajan please review and resolve as part of your ticket/issue.

**Comment by prasannamahajan** [comment]
@dealako raised pull request https://github.com/communitybridge/easycla/pull/658
@amolsontakke3576 we need to check if it is resolved from UI side.

**Comment by nirupamav** [comment]
@dealako @amolsontakke3576 @prasannamahajan 
Verified that new user is able to login to Corporate Console.
But observed that companies are not displayed for the new users. Have logged bug #665 to track the issue

**Comment by dealako** [comment]
Closing issue as this was resolved and confirmed.
