### ISSUE TITLE
Contributor console "Verify Your Permission of Access" modal needs be elucidated

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#561]
## Summary
![image](https://user-images.githubusercontent.com/57362064/73994691-0335f080-491c-11ea-84bc-aeda2fe99a18.png)
Need to change the copy of this modal window

## Background

A contributor might not know what a CLA Manager is so we need to change the text on this modal.

## Expected behavior
Add this sentence to the bottom before the buttons.

Can you manage CLAs on behalf of your company. Are you authorized to whitelist people who contribute on behalf of your company
<YES>    <NO>

**Comment by dealako** [comment]
Reviewed - Closing during sprint backlog review meeting.
