### ISSUE TITLE
Add Company / Join Company button is not disabled when the company field is empty

### ISSUE THREAD

**Issue by ngozi-ekekwe** [communitybridge/easycla#575]
## Summary

"**Add Company**" / "**Join Company**" button is not disabled when the company field is empty

## Background

Go to the corporate console then click on "Get Started". A modal with options to "Add Company" or "Join company" is presented. The user should not be able to trigger the buttons if the field is empty 

## Expected behavior

Once the "Select Company" field has been filled, the buttons should be activated

<img width="802" alt="Screen Shot 2020-02-13 at 1 13 02 PM" src="https://user-images.githubusercontent.com/11598255/74434743-4daaf600-4e63-11ea-9877-48d07ad9fa3d.png">

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

https://corporate.dev.lfcla.com/#/companies

**Comment by dealako** [comment]
Issue resolve. Closing ticket.
