### ISSUE TITLE
Gerrit Agreement Links issue

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#577]
## Summary

When a user clicks on the link to their ICLA or CCLA agreement, the URL generated is bad, leading contributors to believe they haven't signed a cla.

## Background

Go to gerrit.opnfv.org
log in with lfid
click the settings cog in the top right
scroll down to "Agreements" section
If a previously signed CLA exists, there will be a link
![image](https://user-images.githubusercontent.com/46732999/74484741-2b2ad400-4e87-11ea-9157-5a46f4639a2d.png)
Clicking on either agreement link creates an invalid url for example: 
https://gerrit.opnfv.org/gerrit/https://api.lfcla.com/v2/gerrit/6cb3aa25-a6ad-44e9-b510-3066c59c5e5d/corporate/agreementUrl.html
and in the browser a message is displayed "Not Found"

There are two problems.
1) Gerrit is prepending the https://gerrit.opnfv.org/gerrit to the cla api link. This is a Gerrit bug and cannot be fixed by EasyCLA team. 

2)If the user removes the gerrit url, the url https://api.lfcla.com/v2/gerrit/6cb3aa25-a6ad-44e9-b510-3066c59c5e5d/corporate/agreementUrl.html takes the user to the beginning of the signing process, which logically should not happen since they've already signed the agreement. 

## Expected behavior

The user would assume this link would take them to a copy of their ICLA, or to information about the CCLA they have verified their association with. The expected behavior is not found in the documentation.

## Additional Context

If this link can be fixed or redirected by a gerrit admin, we should think about where we want this link to go. Either show information about the signed cla or show a simple message that it's on file.

## References

https://jira.linuxfoundation.org/servicedesk/customer/portal/4/SUPPORT-925

**Comment by dealako** [comment]
@pranab-bajpai can you take a peek at this issue - see the Additional Context section notes.  I would like your opinion on this.

**Comment by dealako** [comment]
@pranab-bajpai responded with (via Slack thread):

> I see the problem and this seems to be a valid defect.
We should not take the user to a screen where they have to sign a new cla.

**Comment by WillsonHG** [comment]
@pranab-bajpai  Where should we take them then? What should the behavior be?

**Comment by bramwelt** [comment]
Gerrit issue being tracked here: https://bugs.chromium.org/p/gerrit/issues/detail?id=11153 Someone has stated they can't reproduced and I've asked that they try again as this is affecting all our Gerrit systems enrolled with EasyCLA.

**Comment by dealako** [comment]
Possible options for the links:

**Comment by dealako** [comment]
Closing the Gerrit issues for now due to inactivity. If necessary, re-open this ticket with additional information and details.
