### ISSUE TITLE
New View Companies table in project console issues

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#580]
Search function - (wack) Does not return matches, just seems to shuffle the companies randomly. The full match switch itself works, but makes no difference in the results.

Managers - this should list the information from the signature_acl field. Currently lists nothing.

The table is including employee signatures - it should only include signature_reference_type = company.

The table is including unfinished and abandoned signatures - it should only include signature_signed = true

Sorting behavior - Click "Date Signed" to sort by date - works correctly. Then click "Company" to sort by company - breaks the join between the dates and their company. Companies get shuffled into an unknown order. Also breaks the same way  if you sort by company first and then date.

**Comment by dealako** [comment]
@hnexokonkwo can you add sorting to this view?  I will assign the backend search API to another developer.

**Comment by nirupamav** [comment]
**Testing is still Inprogress**
_**Verified and observed that Search is not working. With any search criteria and with Full Match enabled/disabled always all companies are returned**_
![image](https://user-images.githubusercontent.com/60865903/77746355-d44a1a00-7042-11ea-9fe7-a5b04d51c961.png)

![image](https://user-images.githubusercontent.com/60865903/77746401-e7f58080-7042-11ea-9ec6-c5f72bec7e9e.png)


![image](https://user-images.githubusercontent.com/60865903/77746445-f479d900-7042-11ea-8b34-a8b2c4e87663.png)


![image](https://user-images.githubusercontent.com/60865903/77746484-fe9bd780-7042-11ea-8581-9db7371c2156.png)
