### ISSUE TITLE
Not able to post through ccla_whitelist_requests endpoint as the developer/employee(github user) username is not available in dynamodb

### ISSUE THREAD

**Issue by automationframework508** [communitybridge/easycla#581]
## Summary

Not able to request for whitelist to a company as the username of the developer/employee(github user) is not available in dynamodb

## Background

Provide context to the issue - provide steps to reproduce the behavior, such as:

**Pre-requsite data**
     -Github organization automationframeworkui with a apiFramework should exist
     -Github org should be installed for the project "CloudFoundry.org Foundation, Inc."
     -CLA group "APIFramework" should be exist for both ccla and icla. Templates should be generated and "apiFramework"  repository of github oreganization "automationframeworkui" should be added to APIFramework cla group
     -User with CLA Manager role should exist
     -An Employee/developer(github user) to get whitelisted for contribution should exist

**Steps To Follow**
1. Launch https://github.com/automationframeworkui/apiFramework
2. Login as employee/developer
3. Edit some files perform Pull Request
4. All checks fail and requests for CLA Sign
5. Click on CLA Sign
6. Github user will be redirected to Contributor console and github user details will be added to dynamodb. 
7. Observed that except github username other guthub user details were added dynamodb
8. Now try to request for ccla whitelisting through api using ccla_whitelist_requests end point
<Dev Environment base url>/v3/company/{{companyid}}/ccla_whitelist_requests/{{projectid}}
9. Observed below reponse and was not able to post whitelist request
{
    "Code": "ValidationException",
    "Message": "ValidationException: One or more parameter values were invalid: An AttributeValue may not contain an empty string\n\tstatus code: 400, request id: 8TB6EPON7TCTKS9MSEQ5HO4ULBVV4KQNSO5AEMVJF66Q9ASUAAJG"
}

## Expected behavior

When user is redirected to contributor console from github while trying to sign the CLA, all required github user details should be stored in dynamodb and we should be able to request for whitelisting from api end point ccla_whitelist_requests

## Environment

Please complete the following information:

* Environment: DEV
* OS: \[e.g. iOS\]
* Browser \[e.g. chrome, safari\]
* Version \[e.g. 22\]

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

\(Optional\) Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by dealako** [comment]
@wanyaland is this related to your task #589 ? Please review and confirm.

**Comment by wanyaland** [comment]
@automationframework508 . I just wanted to verify at which point the referred api endpoint was being called. Because that error got could be an issue with the payload being invalid/empty. Payload format {'userId': <user_id>' } could have had an issue.

**Comment by nirupamav** [comment]
Verified that able to request whitelisting of developer(github user) through API and able to see the details in UI
![image](https://user-images.githubusercontent.com/60865903/76066478-b2192b00-5fb3-11ea-9202-52e28a8ce463.png)

![image](https://user-images.githubusercontent.com/60865903/76066505-bfceb080-5fb3-11ea-83d5-504af8d49016.png)
