### ISSUE TITLE
Error while adding new company

### ISSUE THREAD

**Issue by automationframework508** [communitybridge/easycla#582]
## Summary

Error while adding new company

## Background

Provide context to the issue - provide steps to reproduce the behavior, such as:

1. Launch Corporate Console in dev environment
2. Login as CLA manager
3. Click on Get Started under "Associate yourself with a company in Easy CLA" section to add company 
4. Type the company name in Select Company field for e.g "Framework"
5. Click on ADD COMPANY button
6. Observed the spinning icon keeps spinning and page is stuck there
7. Also observed errors in console and also post request for add company failed. Please see the screenshot for the errors

**NOTE: Company was added successfully even if there were errors and cla manager could view the company in the companies page**

## Screenshots

![image](https://user-images.githubusercontent.com/61135378/74652902-10b96900-51ad-11ea-9b4d-cd1f98ad918a.png)

![image](https://user-images.githubusercontent.com/61135378/74652935-2169df00-51ad-11ea-82d0-77835b4667bf.png)

**Comment by dealako** [comment]
@ngozi-ekekwe can you review/confirm. Maybe we simply need to confirm the response is good or bad, and then update the user by showing a message or continue/close?

**Comment by nirupamav** [comment]
**_Verified that user is able to add Company from Corporate console without any issues. Verified in FF, Chrome and IE_**
![image](https://user-images.githubusercontent.com/60865903/77411122-f133e280-6de1-11ea-8987-5e29bf277511.png)

![image](https://user-images.githubusercontent.com/60865903/77411154-fa24b400-6de1-11ea-9d33-134aed45e9b2.png)
