### ISSUE TITLE
Pending CLA Manger request is not displayed in the Corporate Console for the company

### ISSUE THREAD

**Issue by automationframework508** [communitybridge/easycla#584]
## Background

1. Launch Corporate Console in dev environment
2. Login as CLA Manager
3. Select a Company which has not signed CLA
4. Click on Sign New CLA
5. Select the Project for which CLA has to signed
6. Click on SUBMIT
7. Select option "NO" for CLA Signing Requirement
8. Enter the CLA Manager details
9. Click on Send
10. Email Sent message is displayed
11. Navigate to All Companies page
12. Click on the company for which CLA Manager request was sent
13. Observed the CLA Manager pending request is not visible eventhough email was sent to the user.

## Expected behavior

Pending CLA Manager requests should be displayed for the company

**Comment by pranab-bajpai** [comment]
Tested out your steps, at step 9 the message is sent to CLA Signatory and once CLA Signatory signs the document, user sees the project in their associated project list.
This is working as expected, I think you are mixing CLA Manager and CLA Signatory.
