### ISSUE TITLE
Initially when logged in "Sign Out" and "Sign In" menu options are displayed instead of actual options

### ISSUE THREAD

**Issue by automationframework508** [communitybridge/easycla#585]
## Background

1. Launch Project Management Console in Dev Environment
2. Login as Project Manager
3. Observed "Sign Out" and "Sign In" menu options are displayed instead of "All Projects" and "Sign Out" options.
![image](https://user-images.githubusercontent.com/61135378/74655956-46615080-51b3-11ea-96c1-1bc2185a2669.png)

4. When refreshed the page actual menu options are displayed
![image](https://user-images.githubusercontent.com/61135378/74655983-54af6c80-51b3-11ea-93e3-c87a431e2619.png)

## Expected behavior
Actual menu options should always be displayed

**Comment by dealako** [comment]
@ngozi-ekekwe can you review this one? It seems like a timing issue after we log in. Should only see:
- Log In link should only be displayed when we are logged out
- Log Out link should only be displayed when we are logged in
- Log In/Log Out - should not be displayed at the same time
- View Projects - should only be displayed when we are logged in.

**Comment by dealako** [comment]
Confirmed - Based on testing (DEV and PROD as well), we see this issue when you first log in.  Once you refresh the page, the menu is correct.

**Comment by dealako** [comment]
@automationframework508 can you re-test in DEV?

**Comment by nirupamav** [comment]
Verfied in Dev environment and issue is fixed
