### ISSUE TITLE
Employee/Developer pending request count not updated and requests not visible for the project in UI

### ISSUE THREAD

**Issue by automationframework508** [communitybridge/easycla#588]
## Summary

Employee/Developer pending request count not updated and requests not visible for the project in UI. However able to retrieve pending requests from API and as well as in UI when navigated to the project, in network tab able to see the get request and the response of pending requests

## Background

**Pre-requsite data**
-Github organization automationframeworkui with a repository apiFramework should exist
-Github org should be installed for the project "CloudFoundry.org Foundation, Inc."
-CLA group "APIFramework" should be exist for both ccla and icla. Templates should be generated and "apiFramework" repository of github oreganization "automationframeworkui" should be added to APIFramework cla group
-User with CLA Manager role should exist
-An Employee/developer(github user) to get whitelisted for contribution should exist

**Steps To Follow**
1. Through API using ccla_whitelist_requests endpoint request for whitelisting to a project
https://api.dev.lfcla.com/v3/company/{{companyid}}/ccla_whitelist_requests/{{projectid}}
2. Login to Corporate Console as CLA manager that has access to the company used in step1
3. Click on the Company
4. Observed the Pending Request count is 0. However if we observe in network tab a get request to ccla_whitelist_requests end point is fetching the pending requests
5. Also Pending request details of the user are not displayed in the Manage Whitelist page
![image](https://user-images.githubusercontent.com/61135378/74662661-5c294280-51c0-11ea-8bff-f9ed4f0ff3a0.png)

## Expected behavior
Pending Whitelist count should be increased and whitelist details should be displayed in the Manage Whitelist page

**Comment by dealako** [comment]
@ngozi-ekekwe indicated that we fixed this - need to confirm. @nirupamav can you re-test in DEV?

**Comment by nirupamav** [comment]
@dealako @ngozi-ekekwe 
I have tested the issue and observed that Pending count is updated. However there is another issue where the count is fetched based on the company and displayed for all the projects. Instead count has to be fetched for the project. Have logged bug #593 to track the issue

**Comment by nirupamav** [comment]
Issue was fixed when I last tested 15 days ago but it is again reproducible now
![image](https://user-images.githubusercontent.com/60865903/76071589-83ec1900-5fbc-11ea-8106-72f38b83bd34.png)

![image](https://user-images.githubusercontent.com/60865903/76071637-91a19e80-5fbc-11ea-909e-ae86ca7362e8.png)

**Comment by nirupamav** [comment]
Verified that Pending whitelist count is updated and the requests are visible in Manage Whitelist -> Pending Whitelist Request
![image](https://user-images.githubusercontent.com/60865903/77413357-37d70c00-6de5-11ea-95be-6b71fe467615.png)


![image](https://user-images.githubusercontent.com/60865903/77413333-2c83e080-6de5-11ea-8549-12e38b63f09e.png)
