### ISSUE TITLE
Project Management Console: Method needed to view a whitelist member

### ISSUE THREAD

**Issue by KennyPaul** [communitybridge/easycla#591]
## Summary
A method is needed to view the members of a whitelist from the management console.
This is a feature I requested in a recorded usability session before the ONAP go-live. It is still necessarry.

## Background
Community Members reachout to their Project Manager for assistance on many things.  One of these requests we get is "I know I've been whitelisted, but I still can't commit."  These may come in real-time via slack or other instant messaging app. Usually this the the result of the user working under an email address that is different from the one that was added to the whitelist.  This should be a 2 minute exercise for the PM to help the user, however the PM has no ability to find this information to quickly help the user.
- A user search of "view signatures" could be attempted, however there is no search capability there
- There is no email address information listed in "view signatures" even if there was a search criteria
- This information is also not available from the "view companies" screen

As such the PM must either refer the committer to open a support ticket or the PM needs to do so themself on the user's behalf.  This introduces unnecessarry delays and frustration on the part of someone trying to add code for what should be a very trivial issue the PM to solve by saying, "Oh, just use your xyz address instead because that is what is on the list."

## User Story
A logical usecase scenario would be:
-login to Management Console as the project manager
-select the project
-select view company 
-search for company
-select company
-select "show whitelist"
-results are a list of names, LFIDs and email addresses associated with that company's whitelist

An alternate approach might be:
-login to Management Console as the project manager
-select the project
-select view signatures
-search for user by Name, LFID or email address
-results are a list of matching names, LFIDs and email addresses and the company associated with each

## Acceptance Criteria
The PM has the capability to search and look up someone's whitelisted address via the Management Console.

**Comment by dealako** [comment]
This feature will be incorporated into the LFX CommunityBridge v2.

**Comment by dealako** [comment]
This feature is provided by the current v2 Company Portal and the PCC project console. Closing ticket.
