### ISSUE TITLE
Employee/Developer pending request count is displayed based on the company and not the project

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#593]
## Summary

Employee/Developer pending request count is displayed based on the company and not the project. There is company which has signed CCLA for 2 projects. Developer has requested for whitelist through API for each project. Observed in UI count 2 is displayed for each project instead of 1 and in Manage Whitelist developer pending request is displayed twice for each project

## Background

**Pre-requsite data**
-Github organization automationframeworkui with a repository apiFramework and hybridFramework should exist
-Github org should be installed for the project "CloudFoundry.org Foundation, Inc."
-CLA group "Issue588Test" should be exist for both ccla and icla. Templates with ProjectName "Issue588" should be generated and "apiFramework" repository of github organization "automationframeworkui" should be added to Issue588Test cla group
-CLA group "Issue588Test1" should be exist for both ccla and icla. Templates with ProjectName "Issue5881" should be generated and "hybridFramework" repository of github organization "automationframeworkui" should be added to Issue588Test1 cla group
-User with CLA Manager role should exist
-An Employee/developer(github user) to get whitelisted for contribution should exist
-A company "Issue588Comp" should exists for the CLAManager and CCLA should be signed for projects "Issue588" and "Issue5881"

Steps To Follow

1. Through API using ccla_whitelist_requests endpoint request for whitelisting os developer to projects "Issue588" and "Issue5881"
**https://api.dev.lfcla.com/v3/company/{{companyid}}/ccla_whitelist_requests/{{projectid}}**
2. Login to Corporate Console as CLA manager that has access to the company used in step1
3. Click on the Company
4. Observed the Pending Request count is 2 for CLA Group "Issue588Test" and "Issue588Test1". And, in Manage whitelist there are 2 pending requests for same developer. In Network tab observed that all pending requests of the company are fetched and displayed for each company. Instead Pending request for each project has to fetched and displayed.

**Company Dashboard**
![image](https://user-images.githubusercontent.com/60865903/74902667-bd256600-53cc-11ea-9a5d-7fd663a5b48b.png)

**Manage Whitelist for CLA Group "Issue588Test"**
![image](https://user-images.githubusercontent.com/60865903/74902769-0970a600-53cd-11ea-828a-6acb5fb7d9ad.png)

**Manage Whitelist for CLA Group "Issue588Test1"**
![image](https://user-images.githubusercontent.com/60865903/74902803-34f39080-53cd-11ea-8664-3ad81b8e14d5.png)

**Data fetched in Newtork Tab for CLA Group Issue588Test**
![image](https://user-images.githubusercontent.com/60865903/74902893-6d936a00-53cd-11ea-8060-9fb05f7d527c.png)

**Data fetched in Newtork Tab for CLA Group Issue588Test1**
![image](https://user-images.githubusercontent.com/60865903/74902928-8a2fa200-53cd-11ea-9691-7a0dc921baa3.png)

## Expected behavior
Pending request for the Project of the company should be displayed

**Comment by nirupamav** [comment]
**_Issue is still reproducible and hence reopening the ticket_**

![image](https://user-images.githubusercontent.com/60865903/77413835-06ab0b80-6de6-11ea-91e6-23f30dd80f43.png)


![image](https://user-images.githubusercontent.com/60865903/77413736-d499a980-6de5-11ea-9312-17e643763a03.png)

**_Manage Whitelist UI for both Project Issue666CCLA_ICLA and Project Issue666CCLA display same data_**
![image](https://user-images.githubusercontent.com/60865903/77413868-162a5480-6de6-11ea-97d7-a949f51c04f6.png)

**Comment by dealako** [comment]
@amolsontakke3576 and @wanyaland please review and determine if this is an API or UI issue? Please coordinate and resolve.

**Comment by wanyaland** [comment]
@deelako @amolsontakke3576  so the backend returns ccla whitelist requests for a given company & project .. So one workaround is filtering on the frontend returning count per project. Another would be for the backend to add the count info

**Comment by dealako** [comment]
Verified fix.
