### ISSUE TITLE
Not able to view/download CLA Templates in Firefox while generating templates

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#594]
## Background

**Firefox Version - 73.0.1 (64-bit)**

1. Launch Project Management Console in Firefox and login as Project Manager
2. Click on a Project
3. Click on Select Template for a CLA Group which has opted for both CCLA and ICLA
4. Enter project details and CLA Manager email
5. Click on Generate and Review PDFS button
6. **Observed CLA templates are not downloaded nor displayed embedded in the UI.  Also observed that when clicked in Open CCLA and Open ICLA templates are not downloaded nor displayed embedded in the UI. Observed there was 206 response**
![image](https://user-images.githubusercontent.com/60865903/74907799-1778f380-53da-11ea-9389-bbca4bd3c975.png)
7. Click Done
8. **Click on the PDF for CCLA/ICLA to download the PDF from PDF History window. Observed a blank page is displayed and closed automatically within few seconds**

## Expected behavior
Project Manager should be able to download/view CCLA and ICLA templates in Firefox while generating templates
Also Project Manager should be able to view the templates from template history

**Comment by WillsonHG** [comment]
duplicates #499

**Comment by dealako** [comment]
@amolsontakke3576 - re-assigning to @hnexokonkwo since he is working on the PDF viewer/download related task: #465

**Comment by hnexokonkwo** [comment]
@nirupamav pushed to DEV, ready for review/QA.

**Comment by nirupamav** [comment]
Verified that user is able to preview in browser or download pdf files in firefox while generating pdf's and also while downloading from PDF history window

**Observed below issue in firefox which is tracked in #465, hence closing this issue** 
_When the pdf is previewed in the browser, pdf is opened in the same browser tab and user has to navigate back to Project Management console.
Can the pdf be displayed in another tab for usability purpose_

**When Downloaded/opened when prompted to user**
![image](https://user-images.githubusercontent.com/60865903/77293959-641d5a80-6d09-11ea-99f8-bdfdbc9b36f5.png)


![image](https://user-images.githubusercontent.com/60865903/77294007-75fefd80-6d09-11ea-85a7-feb5ab402aa4.png)


![image](https://user-images.githubusercontent.com/60865903/77294040-89aa6400-6d09-11ea-8373-728996df6341.png)

**When previewed from Browser**
![image](https://user-images.githubusercontent.com/60865903/77294194-d0985980-6d09-11ea-8a6c-a411eb639373.png)
