### ISSUE TITLE
CCLA/ICLA templates keeps downloading until Done button is clicked in Chrome

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#595]
## Background
**Chrome - Version 80.0.3987.116 (Official Build) (64-bit)**
1. Launch Project Management Console in Chrome and login as Project Manager
2. Click on a Project
3. Click on Select Template for a CLA Group which has opted for both CCLA and ICLA
4. Enter project details and CLA Manager email
5. Click on Generate and Review PDFS button
6. A CCLA template is downloaded
7. User is prompted to with the message to allow for download of multiple files
![image](https://user-images.githubusercontent.com/60865903/74908547-1c3ea700-53dc-11ea-9669-990fcd8cf66d.png)

8. Click Allow
9. Observed pdf's keep downloading whenever we close the download progress bar which shows the downloaded files. This keeps repeating until we click on Done button.
![image](https://user-images.githubusercontent.com/60865903/74908693-966f2b80-53dc-11ea-9bae-6c430c76a404.png)

![image](https://user-images.githubusercontent.com/60865903/74908710-9e2ed000-53dc-11ea-9468-f8f57c0bca61.png)

**Comment by dealako** [comment]
Possibly related to #594

**Comment by dealako** [comment]
@amolsontakke3576 re-assigning to @hnexokonkwo since this is related to his current tasking: #465

**Comment by hnexokonkwo** [comment]
@nirupamav pushed to DEV, ready for review/QA.

**Comment by nirupamav** [comment]
**Verified and observed that there is only 1 api call for the template download and only 1 template is downloaded.** 
![image](https://user-images.githubusercontent.com/60865903/77293482-6d59f780-6d08-11ea-96ee-3bfe18e0ae60.png)


**Observed below issues in chrome for pdf download and is tracked in #465 , hence closing this ticket**
![image](https://user-images.githubusercontent.com/60865903/77293518-84004e80-6d08-11ea-907e-61f9e958feaf.png)
