### ISSUE TITLE
CLA Manager is not able to Accept/Decline the pending whitelist request from UI

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#596]
## Background
**Pre-requsite data**
-Github organization automationframeworkui with a repository framework should exist
-Github org should be installed for the project "CloudFoundry.org Foundation, Inc."
-CLA group "TemplateTest" should exist for both ccla and icla. Templates should be generated and "framework" repository of github organization "automationframeworkui" should be added to TemplateTest cla group
-User with CLA Manager role should exist
-An Employee/developer(github user) to get whitelisted for contribution should exist
-A company "TemplateTestComp" should exists for the CLAManager and CCLA should be signed for project "TemplateTest"

**Steps To Follow**

1. Through API using ccla_whitelist_requests endpoint request for whitelisting os developer to project "TemplateTest"
https://api.dev.lfcla.com/v3/company/{{companyid}}/ccla_whitelist_requests/{{projectid}}
2. Login to Corporate Console as CLA manager that has access to the company used in step1
3. Click on the Company
4. Click on Manage Whitelist
5. Click Accept. Click ACCEPT REQUEST in the alert message
6. Observed no action is performed and CLA Manager is not able to Accept the request
7. Try to decline and observed same behavior
**Tested in both firefox and chrome**

## Expected behavior
CLA Manager should be able to accept or decline pending whitelist request

**Comment by nirupamav** [comment]
Will test the issue in ticket #908 and hence closing the ticket

**Comment by amolsontakke3576** [comment]
@dealako  this is an old ticket and working as per expectation, so closing this ticket

**Comment by mlehotskylf** [comment]
This is resolved, closing.
