### ISSUE TITLE
Corporate Console: "Get Started" button should show pending requests to join a company

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#597]
## Summary

On Corporate Console when you click on Get Started and then select a company from the modal, after clicking submit
- [ ] The modal should show a message "Notification Sent to - email id".
- [ ] The web page should update with name of company and say "Request to Join Pending". 

This is important so that the user knows that their request has been sent to an existing CLA Manager from that company

**Comment by nirupamav** [comment]
Company with Request to Join Pending is not displayed
1. Launch Coporate Console
2. Login as nirupamavmentee2
3. Click Get Started
4. Search and Select company Issue327Comp123
![image](https://user-images.githubusercontent.com/60865903/78241945-d9094500-74fe-11ea-8b1d-82881d4e1a77.png)

5. Click JOIN COMPANY
![image](https://user-images.githubusercontent.com/60865903/78241973-e292ad00-74fe-11ea-8108-482111e94c9b.png)

6. Company is not displayed after refresh 
![image](https://user-images.githubusercontent.com/60865903/78242062-0229d580-74ff-11ea-8b85-41a1cffd869c.png)

**Comment by nirupamav** [comment]
@amolsontakke3576 
**Observed that issue is fixed. Moving it to Review Complete**
![image](https://user-images.githubusercontent.com/60865903/78863584-993ee200-7a57-11ea-8755-125a4dd5e71e.png)

![image](https://user-images.githubusercontent.com/60865903/78863606-a3f97700-7a57-11ea-83fe-6e123e9178ae.png)
