### ISSUE TITLE
URL and data overlaps when more than 27 characters are entered in the GitHub Organization Url field

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#602]
## Background

1. Launch Project Management Console in dev environment
2. Login as Project Manager
3. Click on a project
4. Click on "CONNECT GITHUB ORGANIZATION" button
5. Enter value greater than 27 characters for Github Organization url
6. Observed that the value and url overlaps
![image](https://user-images.githubusercontent.com/60865903/75134405-3641f780-5704-11ea-842e-e40814ef56b5.png)

**Comment by dealako** [comment]
I suggest the placeholder text/hint should be below the input text box or come up with a better way to display the URL.

**Comment by nirupamav** [comment]
Verified that the URL placeholder is displayed below the input text field
Verified in chrome, firefox and edge browsers
![image](https://user-images.githubusercontent.com/60865903/75950045-26799e80-5ece-11ea-86b1-ede26648e357.png)
