### ISSUE TITLE
No validation for invalid github organization while connecting Github Organization

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#603]
## Background
1. Launch Project Management Console in dev environment
2. Login as Project Manager
3. Click on a project
4. Click on "CONNECT GITHUB ORGANIZATION" button
5. Enter invalid organization name (the organization that does not exist in github)
6. There is no validation and any github user is able to login to github and install/configure the app for any existing organizations
7. When we navigate back to Project Management console we see "Not Configured..." message
![image](https://user-images.githubusercontent.com/60865903/75135558-e9602000-5707-11ea-9a95-99ec93f5d6b7.png)

## Expected behavior
Due to human errors there could spelling mistakes in the github organization entered. Validation for invalid github organization should exist else user will not be able to understand why the github organization was not configured.

**Comment by dealako** [comment]
UI can do a quick API call to GH to ensure the Org/Repo exists.

**Comment by hnexokonkwo** [comment]
@nirupamav pushed to DEV, ready for review/QA.

**Comment by nirupamav** [comment]
**Verified and observed that api call is added to check if github org exists and error message is displayed in the UI**
![image](https://user-images.githubusercontent.com/60865903/77290465-40a2e180-6d02-11ea-9fac-c76143c0b30b.png)

![image](https://user-images.githubusercontent.com/60865903/77290502-52848480-6d02-11ea-890d-dcc439c6b2d3.png)
