### ISSUE TITLE
UI issues when CLA group name is more than 93 characters

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#608]
## Background
1. Launch Project Management Console url in dev environment
2. Login as Project Manager
3. Click on a project
4. Click ADD CLA GROUP button
5. CLA Group popup window is displayed
6. Create CLA Group with name more than 93 characters.
**Issue 1**
7. Observed that CLA Group name overlaps with buttons SELECT TEMPLATE, VIEW SIGNATURES and VIEW COMPANIES
![image](https://user-images.githubusercontent.com/60865903/75218242-a06ba280-57bf-11ea-8de3-5a519911f42b.png)

**Issue2**
8. When CLA Group name is more than 157 characters group name is displayed outside the CLA Group card
![image](https://user-images.githubusercontent.com/60865903/75218391-2daef700-57c0-11ea-8313-aa1cbbdc2f29.png)

**Comment by dealako** [comment]
Two Options:
1) constrain the project/cla group name to a maximum value
2) update the UI to display longer project/cla group names (support wrapping?)

**Comment by nirupamav** [comment]
Verified in chrome, firefox and edge browsers
1. Verified that the text is wrapped when the text is more than 55 characters
![image](https://user-images.githubusercontent.com/60865903/75951456-1499fa80-5ed2-11ea-9f1d-7a41f9ec0410.png)

2. Verified that the CLA group name accepts only 150 characters
![image](https://user-images.githubusercontent.com/60865903/75951491-27143400-5ed2-11ea-85da-7853e7dd15d6.png)

3. Verified that the setting icon always top (Edit group icon)
![image](https://user-images.githubusercontent.com/60865903/75951566-59be2c80-5ed2-11ea-9a4e-60dcb06d9e90.png)

@dealako @pranab-bajpai 
Observed that when CLA group name is small there is a gap between the name and the Edit Gorup icon. Is this fine?
![image](https://user-images.githubusercontent.com/60865903/75952106-c4bc3300-5ed3-11ea-9e69-5b37f348e905.png)

**Comment by nirupamav** [comment]
**_Observed the issue has occurred again and hence reopening the issue. Text wrapping fixed in this issue is now not working_**
![image](https://user-images.githubusercontent.com/60865903/77901374-1f5f6980-729d-11ea-8220-28abac02d5cf.png)

**Comment by dealako** [comment]
@amolsontakke3576 please review/resolve.

**Comment by amolsontakke3576** [comment]
@dealako @nirupamav : Issue was when CLA group name having long single word (without space). Ideally it should not be happened but still I have made provision by breaking word.

**Comment by nirupamav** [comment]
**Verified that the issue is fixed**
![image](https://user-images.githubusercontent.com/60865903/79108075-2f924100-7d93-11ea-9e41-7db8988cdad9.png)

![image](https://user-images.githubusercontent.com/60865903/79108124-4d5fa600-7d93-11ea-9ded-f070bc76a4f1.png)
