### ISSUE TITLE
User is able to create CLA Group and generate templates when CLA type (CCLA and ICLA) is not checked

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#609]
## Background
1. Launch Project Management Console url in dev environment
2. Login as Project Manager
3. Click on a project
4. Click ADD CLA GROUP button
5. CLA Group popup window is displayed
6. Enter CLA Group name
7. **Do not check the check boxes for CCLA and ICLA**

**Issue 1**
8. Observed user is able to create CLA group when the CLA type is not selected
![image](https://user-images.githubusercontent.com/60865903/75219209-2be63300-57c2-11ea-9004-8882458ee96d.png)

**Issue 2**
9. Also observed that user is able to generate CCLA and ICLA templates when CCLA and ICLA checkboxes are not checked while creating CLA Group
![image](https://user-images.githubusercontent.com/60865903/75219309-710a6500-57c2-11ea-9b1c-c65d90798d2f.png)

![image](https://user-images.githubusercontent.com/60865903/75219335-81224480-57c2-11ea-9b21-c6dfde546cf5.png)

**Comment by dealako** [comment]
Let's update this logic to allow Project Managers to set/unset these checkboxes as they see fit.  Let's confirm with @swinslow first... We have a long history of debate on this topic.

**Comment by swinslow** [comment]
@dealako Happy to discuss this during the call later today.

**Comment by dealako** [comment]
Discussed this issue with @swinslow on the weekly EasyCLA Sync meeting:

**Comment by nirupamav** [comment]
Verified and observed that the issue is fixed
Observed that the error message "Please select atleast one checkbox." is displayed and user is not able to Save the CLA Group if none of the CCLA type check boxes are checked
Verified in Chrome, Firefox and IE

**While Adding CLA Group**
![image](https://user-images.githubusercontent.com/60865903/76063687-3c5e9080-5fae-11ea-838c-a3200b87f8a8.png)


**While Updating/Editing CLA Group**
![image](https://user-images.githubusercontent.com/60865903/76063927-aaa35300-5fae-11ea-95cb-909f2186f783.png)

**Comment by nirupamav** [comment]
Also Verified below behavior
1. Corporate CLA checkbox IS selected and - Individual CLA checkbox IS NOT selected - 'Contributors under Corporate CLA must also sign individual CLA' is disabled and NOT checked.
![image](https://user-images.githubusercontent.com/60865903/76064321-6b293680-5faf-11ea-9303-41961504800a.png)


2. Corporate CLA checkbox IS NOT selected and - Individual CLA checkbox IS selected - 'Contributors under Corporate CLA must also sign individual CLA' is disabled and NOT checked.
![image](https://user-images.githubusercontent.com/60865903/76064367-82682400-5faf-11ea-9580-7f8d646863da.png)


3. Both Corporate CLA checkbox and Individual CLA checkbox are checked - the 'Contributors under Corporate CLA must also sign individual CLA' is enabled and Project Managers can check/uncheck this checkbox.
![image](https://user-images.githubusercontent.com/60865903/76064471-bba09400-5faf-11ea-8d54-9655a9135901.png)

![image](https://user-images.githubusercontent.com/60865903/76064505-d07d2780-5faf-11ea-9c37-99ff32284208.png)
