### ISSUE TITLE
User is able to create duplicate CLA Groups

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#610]
## Background
1. Launch Project Management Console url in dev environment
2. Login as Project Manager
3. Click on a project
4. Click ADD CLA GROUP button
5. CLA Group popup window is displayed
6. Enter CLA Group name as 1clagroup
7. Click Save
8. Click ADD CLA GROUP button
9. CLA Group popup window is displayed
10. Enter CLA Group name as 1clagroup
11. Click Save
12. Observed user is able to create duplicate cla groups
![image](https://user-images.githubusercontent.com/60865903/75219567-23422c80-57c3-11ea-8cea-07cad2a81338.png)

**Comment by dealako** [comment]
Two things that need to be done:
1. Create Project v3 backend should return a conflict if the CLA Group/Project Name is a duplicate
2. Update the UI so that it detects the response code and shows the user the error.

**Comment by nirupamav** [comment]
Verified and observed the user is still able to create duplicate CLA Groups and hence reopening the bug
![image](https://user-images.githubusercontent.com/60865903/76063321-82672480-5fad-11ea-8121-409545e7ac06.png)

**Comment by dealako** [comment]
@wanyaland can you review - what did we miss? We check for conflicting Project/CLA Group names.... (golang API).  I think the API tests cover this issue??

**Comment by wanyaland** [comment]
@deelako When I tested it works fine and the backend indeed returns a 409. Yes the project tests cover creating duplicate project names

![Screenshot 2020-04-08 at 16 14 36](https://user-images.githubusercontent.com/2846731/78788318-4fe98680-79b4-11ea-9894-98e13315e9f3.png)
![Screenshot 2020-04-08 at 16 14 57](https://user-images.githubusercontent.com/2846731/78788345-5841c180-79b4-11ea-99ae-15c4bfd6b7fa.png)

**Comment by dealako** [comment]
@nirupamav Can you re-test please?

**Comment by nirupamav** [comment]
@dealako  @wanyaland 
**_Tested and observed duplicate CLA group is created when text case is different_**
for e.g **ask test** and **ASK TEST**
![image](https://user-images.githubusercontent.com/60865903/78865391-27689780-7a5b-11ea-81f2-cc31f1989a40.png)

![image](https://user-images.githubusercontent.com/60865903/78865462-49fab080-7a5b-11ea-888f-eb605836af5d.png)


**_However if I try create CLA group with same text case then error is displayed_**
![image](https://user-images.githubusercontent.com/60865903/78865258-e2446580-7a5a-11ea-88ea-cb34f7b019eb.png)

![image](https://user-images.githubusercontent.com/60865903/78865497-5979f980-7a5b-11ea-90e7-065962819e50.png)

**Comment by nirupamav** [comment]
**_Observed that the user is able to edit a CLA Group with exisiting CLA group name and due which duplicate CLA groups created_**
![image](https://user-images.githubusercontent.com/60865903/79547537-b0ae4880-80b1-11ea-97ac-a7bff7330bad.png)

**_Observed that the user is able to create duplicate CLA group in different foundations_**
In Cloud Native Foundation 
![image](https://user-images.githubusercontent.com/60865903/79547682-e5220480-80b1-11ea-996e-e5034b7f787b.png)
In CloudFoundry.org Foundation, Inc. 
![image](https://user-images.githubusercontent.com/60865903/79547744-fe2ab580-80b1-11ea-81bb-c6badf420209.png)

**Comment by nirupamav** [comment]
**Tested and observed that we are still able to update the CLA Group with duplicate CLA group name**
![image](https://user-images.githubusercontent.com/60865903/79827389-c9717380-83bb-11ea-8225-cf504ce5ac77.png)

Observed that issue related to creation of duplicate CLA Groups across foundations(or external projects) is fixed

**Comment by nirupamav** [comment]
Testing blocked due to #986 986

**Comment by nirupamav** [comment]
**_Verified  below scenarios and observed that the issue is fixed_**
1. Create Duplicate CLA Group with different text cases in same Foundation
2. Update existing CLA Group with different text cases to create duplicate CLA Group in same Foundation
3. Create Duplicate CLA Group with different text cases in another Foundation
4. Update existing CLA Group with different text cases to create duplicate CLA Group in another Foundation
