### ISSUE TITLE
Text displayed for Corporate CLA and Individual CLA should be consistent when templates are not generated

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#611]
## Background
1. Launch Project Management Console url in dev environment
2. Login as Project Manager
3. Click on a project
4. Click ADD CLA GROUP button
5. CLA Group popup window is displayed
6. Enter CLA Group name as 1clagroup
7. Select check boxes for Corporate CLA and Individual CLA
8. Click Save

**Issue 1**
9. Observed that text for Corporate CLA card is displayed in proper case but text for Individual CLA card text is not displayed in proper case. The text style should be consistent
![image](https://user-images.githubusercontent.com/60865903/75223719-14607780-57cd-11ea-80ae-761eb292f15f.png)

**Issue 2**
Observed that text for Corporate CLA card is displayed as "No Template **Created**." but text for Individual CLA card text is displayed as "No template **selected**.". The text displayed should be consistent as we are generating pdf's for both CCLA and ICLA. Either it should be displayed as "No template selected" for both or for both it should be displayed as "No template generated"

**Comment by dealako** [comment]
Simple text update

**Comment by nirupamav** [comment]
Verified that the text is consistent 
Verified in Chrome, Firefox and IE
![image](https://user-images.githubusercontent.com/60865903/76062311-7712f980-5fab-11ea-9067-bb2b5c5ca88d.png)
