### ISSUE TITLE
Github Organizations are not aligned properly and the card looks clumsy when too many github organizations are connected 

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#612]
## Background

**Prerequisite**
1. Valid user with project Manager role should exist
2. Valid project should exist
3. More than 10 Github Organizations should be connected to the project

**Steps To Follow**
1. Launch Project Management Console in deb environment
2. Login as Project Manager
3. Click on Project which has more than 10 github organizations
4. Observed that github organizations are not aligned properly and Github Organizations card looks clumsy. Also observed that github Organizations are not displayed in any particular order
![image](https://user-images.githubusercontent.com/60865903/75231116-eda93d80-57da-11ea-9ec0-26428d901d1e.png)

**Comment by dealako** [comment]
UI cleanup/CSS cleanup/spacing optimization.

**Comment by nirupamav** [comment]
Issue is still reproducible and hence reopening the ticket. Github Organizations are not aligned properly and are not displayed in any particular sort order
![image](https://user-images.githubusercontent.com/60865903/77416500-eb41ff80-6de9-11ea-81da-bc418a28256e.png)

**Comment by nirupamav** [comment]
**_Verified that UI issue is resolved. However the sorting order is not yet fixed. Logged bug #788 to track the sorting order_**
![image](https://user-images.githubusercontent.com/60865903/78101473-4042ce80-7405-11ea-81d8-ace84fbb1875.png)

![image](https://user-images.githubusercontent.com/60865903/78101498-505aae00-7405-11ea-9cef-fc303e69ff08.png)


![image](https://user-images.githubusercontent.com/60865903/78101521-60728d80-7405-11ea-834d-b760aa65bfb6.png)
