### ISSUE TITLE
User is able to generate templates when project details are not provided

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#613]
## Background
1. Launch Project Management Console in dev environment
2. Login as project manager
3. Click on a project
4. Click SELECT TEMPLATE button for a CLA group which has not generated templates
5. Select APACHE Style button
6. Do not enter any data for "Project Name", "Project Entity Name" and "Contact Email Address"
7. Click on "GENERATE AND REVIEW PDFS" button
8. Observed that templates are generated even when project details are not provided
![image](https://user-images.githubusercontent.com/60865903/75237682-c7d56600-57e5-11ea-823e-18916f640d1f.png)

**Comment by dealako** [comment]
UI - add form validation

**Comment by nirupamav** [comment]
**_Verified user is not able to generate templates when project details are not provided_**
![image](https://user-images.githubusercontent.com/60865903/77418429-e2066200-6dec-11ea-8920-6282c578a791.png)

![image](https://user-images.githubusercontent.com/60865903/77418475-f2b6d800-6dec-11ea-8fcc-85ca5a88929a.png)

![image](https://user-images.githubusercontent.com/60865903/77418532-06623e80-6ded-11ea-9b12-97de18b4ea97.png)


![image](https://user-images.githubusercontent.com/60865903/77418566-111cd380-6ded-11ea-8016-4f53120c6d47.png)
