### ISSUE TITLE
Generate Templates - Email Address field accepts any free text and there is no validation for email address format

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#618]
## Background
1. Launch Project Management Console in dev environment
2. Login as project manager
3. Click on a project
4. Click SELECT TEMPLATE button for a CLA group which has not generated templates
5. Select APACHE Style button
6. Enter valid data for "Project Name" and "Project Entity Name"
7. Enter free text for e.g **template** for "Contact Email Address" field
7. Click on "GENERATE AND REVIEW PDFS" button
8. Observed that templates are generated and there is no validation for the email address field. Email address accepts any free text
![image](https://user-images.githubusercontent.com/60865903/75325199-6ae9b680-589e-11ea-8fcd-81b42b74e6de.png)

**Comment by dealako** [comment]
UI - need to add email validator to the input field.

**Comment by nirupamav** [comment]
**Tested and observed that for few scenarios email address is still not validated**
![image](https://user-images.githubusercontent.com/60865903/80565100-4a101f80-8a0d-11ea-89c7-41d047c49541.png)

![image](https://user-images.githubusercontent.com/60865903/80565304-cacf1b80-8a0d-11ea-8951-0cae1ddbc14c.png)

**Comment by nirupamav** [comment]
**Verified below formats and observed that the issue is fixed**
![image](https://user-images.githubusercontent.com/60865903/81400408-a4665a00-914a-11ea-981e-046c9dffaa9d.png)

![image](https://user-images.githubusercontent.com/60865903/81400430-b47e3980-914a-11ea-93e9-796377484148.png)

![image](https://user-images.githubusercontent.com/60865903/81400439-be07a180-914a-11ea-820a-57662b213d24.png)

![image](https://user-images.githubusercontent.com/60865903/81400453-c65fdc80-914a-11ea-83b8-44dacd2d0c9a.png)

![image](https://user-images.githubusercontent.com/60865903/81400542-fe671f80-914a-11ea-8ca3-e9bde8841eb7.png)


**Format with no errors**
nirupama@proxima.in
nirupama@proxima.com
nirupama@proxima.co
