### ISSUE TITLE
Both CCLA and ICLA templates are generated when CLA group has only ICLA or only CCLA type selected

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#619]
## Background
1. Launch Project Management Console in dev environment
2. Login as project manager
3. Click on a project
4. Add a CLA group with only ICLA checked and CCLA unchecked
5. Click SELECT TEMPLATE button for a CLA group which has not generated templates
6. Select APACHE Style button
7. Enter valid data for "Project Name", "Project Entity Name" and "Contact Email Address"
8. Click on "GENERATE AND REVIEW PDFS" button
9. Observed that CCLA template is also generated when the CLA group has selected only ICLA

![image](https://user-images.githubusercontent.com/60865903/75326715-1f84d780-58a1-11ea-992e-de10c5217ef2.png)

![image](https://user-images.githubusercontent.com/60865903/75326754-31ff1100-58a1-11ea-9af2-5876c6723f7a.png)

**NOTE: Also Observed that CCLA and ICLA templates are generated when the CLA group has selected only CCLA**
![image](https://user-images.githubusercontent.com/60865903/75327051-c0739280-58a1-11ea-96e7-9236dddbf429.png)

![image](https://user-images.githubusercontent.com/60865903/75327027-b782c100-58a1-11ea-9b20-2c952023d0e6.png)

**Comment by dealako** [comment]
We should confirm:

1. Is this a UI display issue only?
2. Is the backend truly generating both and ignoring the flag/parameters? It should respect the form values and only generate what is needed.

**Comment by amolsontakke3576** [comment]
@dealako @pranab-bajpai  @prasannamahajan It's seem like backend API generate both the PDF even either CCLA or ICLA selected.

Request URL: `https://api.dev.lfcla.com/v3/clagroup/7d5f7eee-10ab-4f7c-96d4-779a3699b569/template`
Request Method: POST
Status Code: 200 

Response : 
```
{
   "corporatePDFURL":"https://cla-signature-files-dev.s3.amazonaws.com/contract-group/7d5f7eee-10ab-4f7c-96d4-779a3699b569/template/ccla.pdf",
   "individualPDFURL":"https://cla-signature-files-dev.s3.amazonaws.com/contract-group/7d5f7eee-10ab-4f7c-96d4-779a3699b569/template/icla.pdf"
}
```

**Comment by dealako** [comment]
@amolsontakke3576 - thanks will assign ticket to API dev.

**Comment by dealako** [comment]
@wanyaland can you review this ticket and let me know your thoughts and approach?

**Comment by wanyaland** [comment]
@dealako Based on the flags(icla,ccla,both) raised in selecting CCLA/ICLA the endpoint should be able to create the appropriate signature. Currently the create service just creates both irrespective of the selection

**Comment by wanyaland** [comment]
> @dealako @pranab-bajpai @prasannamahajan It's seem like backend API generate both the PDF even either CCLA or ICLA selected.
> 
> Request URL: `https://api.dev.lfcla.com/v3/clagroup/7d5f7eee-10ab-4f7c-96d4-779a3699b569/template`
> Request Method: POST
> Status Code: 200
> 
> Response :
> 
> ```
> {
>    "corporatePDFURL":"https://cla-signature-files-dev.s3.amazonaws.com/contract-group/7d5f7eee-10ab-4f7c-96d4-779a3699b569/template/ccla.pdf",
>    "individualPDFURL":"https://cla-signature-files-dev.s3.amazonaws.com/contract-group/7d5f7eee-10ab-4f7c-96d4-779a3699b569/template/icla.pdf"
> }
> ```

This has been fixed on the backend

**Comment by nirupamav** [comment]
**_Observed that only CCLA is generated when Project has only CCLA enabled and vice versa. But observed other issues and bug #750 has been logged to track those issues_**
![image](https://user-images.githubusercontent.com/60865903/77615504-8e635800-6f55-11ea-9611-64755fd3558d.png)

![image](https://user-images.githubusercontent.com/60865903/77616818-940e6d00-6f58-11ea-9ce7-72bd1c1b73f8.png)
