### ISSUE TITLE
Project Entity is not visible in both ICLA and CCLA templates

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#620]
## Background
1. Launch Project Management Console in dev environment
2. Login as project manager
3. Click on a project
4. Add a CLA group with both  ICLA and CCLA checked
5. Click SELECT TEMPLATE button for a CLA group which has not generated templates
6. Select APACHE Style button
7. Enter valid data for "Project Name", "Project Entity Name" and "Contact Email Address"
8. Click on "GENERATE AND REVIEW PDFS" button
9. Open downloaded CCLA and ICLA templates
10. Observed that Project Entity is not visible. Project Entity is behind the watermark
![image](https://user-images.githubusercontent.com/60865903/75327871-18f75f80-58a3-11ea-9dfb-1db0513cd52e.png)

**Comment by dealako** [comment]
This is a product of us using a non-production account for DocRaptor in the DEV environment. We use the proper account in PROD so this banner is not visible.

We are closing issue as this is working as we expect.
