### ISSUE TITLE
Project logo is not displayed in CLA project page

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#622]
## Background
1. Launch Project Management Console in Dev Environment
2. Login as Project Manager
3. Observed that logo is displayed for the projects in All Projects page
4. Click on any project which has logo
5. Logo for the project is not displayed in CLA Project page

![image](https://user-images.githubusercontent.com/60865903/75348860-9afa7f00-58c9-11ea-9fe0-8bea0747c41b.png)

![image](https://user-images.githubusercontent.com/60865903/75348841-8ddd9000-58c9-11ea-9092-ecf2fce00b1f.png)

**Comment by dealako** [comment]
@amolsontakke3576 you will need to pull the logo:

**Comment by nirupamav** [comment]
Verified that the project logo is now displayed in CLA Project page
![image](https://user-images.githubusercontent.com/60865903/75949306-cf72ca00-5ecb-11ea-9118-6b8728c7e677.png)

![image](https://user-images.githubusercontent.com/60865903/75949329-e1546d00-5ecb-11ea-834f-815dda0b8d48.png)

![image](https://user-images.githubusercontent.com/60865903/75949360-fc26e180-5ecb-11ea-8889-f807486d046a.png)

**Comment by nirupamav** [comment]
Verified in chrome, firefox and edge browsers
