### ISSUE TITLE
EasyCLA V2 API for Usage Metrics + Adoption page - EasyCLA Service Statistics (All Time)

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#624]
## Summary

![image](https://user-images.githubusercontent.com/57362064/75410349-45ca6780-58e1-11ea-94e3-62fabe35e63a.png)

Need EasyCLA API that will get the statistics for this section. This for overall EasyCLA.

Moving from top left to right and then down left to right.

- [x] Number of Projects where EasyCLA is enforced. 
- [x] Number of Corporate Contributors that are contributing to the projects that use EasyCLA.
- [x] Number of GitHub and Gerrit repositories on which EasyCLA is enforced.
- [x] Total number of Individual Contributors that are contributing to the projects where EasyCLA is enforced.
- [x] Total number of Companies (i.e. Organizations) that use LF projects for which the EasyCLA is used for CLA management
- [x] The total number of CLA Managers who manage or maintain LF projects that use EasyCLA.

- [x] This information will also populate the following table
![image](https://user-images.githubusercontent.com/57362064/75411879-69dc7780-58e6-11ea-844d-25268d89f206.png)

## Background

This data is needed for lfx-dev to implement this page.
Step 1 and 12 in the following PRD

https://confluence.linuxfoundation.org/pages/viewpage.action?pageId=42993133

## User Story

As an employee of a company when I browse "Services" in CommunityBridge, I would like to see EasyCLA service, list out key relevant usage and adoption metrics related to that service. 

## Acceptance Criteria

API returns the metrics and information is rendered on LFX-Dev

**Comment by prasannamahajan** [comment]
https://github.com/communitybridge/easycla/pull/667

**Comment by prasannamahajan** [comment]
API: GET {{apiserver}}/v4/metrics/total-count

**Comment by nirupamav** [comment]
**Testing In Progress**
**_Test Plan Link_** https://confluence.linuxfoundation.org/display/PROD/total-count
