### ISSUE TITLE
EasyCLA V2 API for Usage Metrics + Adoption page - Contributor Leaderboard by Projects with CLAs

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#625]
## Summary

Check the chart in Step 2 of following PRD
https://confluence.linuxfoundation.org/display/PROD/EasyCLA+-+Service+Landing+Page+PRD

Need EasyCLA API that will get the statistics for this section. This for overall EasyCLA.

Each tab will invoke a separate API on EasyCLA.

- [ ] API to get TOP COMMITTERS - To invoke this API, EasyCLA will send the list of projects on which EasyCLA is enforced to Developer Analytics (DA). DA will return names of top three contributors (top three sorted by number of commits) for each of the project on which EasyCLA is enforced. 
- [ ] API to get TOP COMPANIES - To invoke this API, EasyCLA will send the list of projects on which EasyCLA is enforced to Developer Analytics (DA). DA will return names of top three companies (top three sorted by number of commits by that company) for each of the project on which EasyCLA is enforced. 

## Background

This data is needed for lfx-dev to implement this page.
Step 2 in the following PRD

https://confluence.linuxfoundation.org/pages/viewpage.action?pageId=42993133

## User Story

As an employee of a company when I browse "Services" in CommunityBridge, I would like to see EasyCLA service, list out key relevant usage and adoption metrics related to that service. 

## Acceptance Criteria

API returns the metrics and information is rendered on LFX-Dev

**Comment by prasannamahajan** [comment]
@aegixx @pranab-bajpai 
CLA can only give partial information for this story and that part is implemented.

CLA can give list of all projects in CLA.
You can use api https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/metrics.
Then this info needs to use to call DA to get required data

**Comment by dealako** [comment]
@pranab-bajpai can we close this ticket out?

**Comment by pranab-bajpai** [comment]
LF Staff pages were de-prioritized and redesigned with minimal metrics. Closing it.
