### ISSUE TITLE
EasyCLA V2 API for Usage Metrics + Adoption page - EasyCLA Service Insights (All Time)

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#626]
## Summary
![image](https://user-images.githubusercontent.com/57362064/75411100-ae1a4880-58e3-11ea-991d-fcb52d7d3acf.png)

Need EasyCLA API that will get the statistics for this section. This for overall EasyCLA.

For rendering this graph the web page will need four pieces of data. 

- [ ] Total number of projects under Linux Foundation.
- [x] Total number of projects where EasyCLA is enforced.
- [ ] Total number of contributors for all projects under Linux Foundation.
- [x] Total number of contributors for all projects where EasyCLA is enforced.
- [ ] EasyCLA API can get #1 and #3 from Developer Analytics (DA), it can get #2 and #4 from EasyCLA database. This information can then be rendered as a graph. 

## Background

This data is needed for lfx-dev to implement this page.
Step 3 in the following PRD

https://confluence.linuxfoundation.org/pages/viewpage.action?pageId=42993133

## User Story

As an employee of a company when I browse "Services" in CommunityBridge, I would like to see EasyCLA service, list out key relevant usage and adoption metrics related to that service. 

## Acceptance Criteria

API returns the metrics and information is rendered on LFX-Dev

**Comment by prasannamahajan** [comment]
@aegixx @pranab-bajpai 
CLA can only give partial information for this story and that part is implemented.

CLA can give total number of projects and total contributors in cla.
You can use api : https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/metrics/total-count

**Comment by dealako** [comment]
@pranab-bajpai can we close this ticket out?

**Comment by pranab-bajpai** [comment]
LF Staff pages were de-prioritized and redesigned with minimal metrics. Closing it.
