### ISSUE TITLE
EasyCLA V2 API for Usage Metrics + Adoption page - Total Number of CLA Managers Across Companies

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#627]
## Summary

![image](https://user-images.githubusercontent.com/57362064/75411264-3c8eca00-58e4-11ea-82d9-0f002e29a4a8.png)

For rendering this bubble graph the web page will following data from EasyCLA API. 

- [x] Frequency distribution that gives count of Companies that have

- 1 CLA Manager,

- 2 CLA Manager,
 
- 3 CLA Managers,
 
- 4 CLA Manager and
 
- more than 4 CLA Managers.
 

## Background

This data is needed for lfx-dev to implement this page.
Step 4 in the following PRD

https://confluence.linuxfoundation.org/pages/viewpage.action?pageId=42993133

## User Story

As an employee of a company when I browse "Services" in CommunityBridge, I would like to see EasyCLA service, list out key relevant usage and adoption metrics related to that service. 

## Acceptance Criteria

API returns the metrics and information is rendered on LFX-Dev

**Comment by prasannamahajan** [comment]
pull request : https://github.com/communitybridge/easycla/pull/667

**Comment by prasannamahajan** [comment]
API : GET {{apiserver}}/v4/metrics/cla-manager-distribution

**Comment by nirupamav** [comment]
Tested In Progress
**Verified below scenarios**
_**API URL**_  https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/metrics/cla-manager-distribution
1. Count for **oneClaManager** is 357 in the response. As a CLA Manager added a company and signed CLA for the company. Checked the in the api response the count was increased and count for **oneClaManager** is 358

**Comment by nirupamav** [comment]
@pranab-bajpai @dealako @prasannamahajan 
**Completed Testing and below is the status. Could you please review the test plan and let me know if I missed to test any scenarios**
**_Test Plan Link_** https://confluence.linuxfoundation.org/display/PROD/cla-manager-distribution

**_Test case execution status_**
![image](https://user-images.githubusercontent.com/60865903/78977651-1b9dd380-7b36-11ea-91f9-c5bb4b2be2f2.png)

**Bugs for failed and blocked  test cases are updated in the testplan**

**Comment by pranab-bajpai** [comment]
Reviewed the test cases for this diagram. 
All the tests that are failing are capturing the situation where a user has been added as a CLA Manager but that user hasn't signed the CLA yet. I think those test cases are right.
All other test cases also look correct.

**Comment by dealako** [comment]
@pranab-bajpai can we close this ticket out?

**Comment by pranab-bajpai** [comment]
LF Staff pages were de-prioritized and redesigned with minimal metrics. Closing it.
