### ISSUE TITLE
EasyCLA V2 API for Usage Metrics + Adoption page - My Organization Vs. The Top 5 Organizations

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#628]
## Summary

![image](https://user-images.githubusercontent.com/57362064/75411560-436a0c80-58e5-11ea-9951-dba4fc741b6c.png)

Need EasyCLA API that will get the statistics for this section. This for overall EasyCLA.

- [x] Number of projects on EasyCLA from user's company Vs. other top 5 companies with an average line showing average number of projects for each company. API will take the user's company name to look up this information.

![image](https://user-images.githubusercontent.com/57362064/75411615-76140500-58e5-11ea-84e0-f458b09a7ef6.png)

- [x] Number of Corporate Contributors on EasyCLA from user's company Vs. other top 5 companies with an average line showing average number of projects for each company.

![image](https://user-images.githubusercontent.com/57362064/75411642-89bf6b80-58e5-11ea-82b9-f840a82877d8.png)

- [x] Number of CLA Managers on EasyCLA from user's company Vs. other top 5 companies with an average line showing average number of projects for each company.

## Background

This data is needed for lfx-dev to implement this page.
Steps 8,9 and 10 in the following PRD

https://confluence.linuxfoundation.org/pages/viewpage.action?pageId=42993133

## User Story

As an employee of a company when I browse "Services" in CommunityBridge, I would like to see EasyCLA service, list out key relevant usage and adoption metrics related to that service. 

## Acceptance Criteria

API returns the metrics and information is rendered on LFX-Dev

**Comment by prasannamahajan** [comment]
pull request : https://github.com/communitybridge/easycla/pull/667

**Comment by dealako** [comment]
@pranab-bajpai ready to review

**Comment by prasannamahajan** [comment]
To get top companies by claManagers, corporateContributors, projectCount.
API : GET {{apiserver}}/v4/metrics/top-companies 

To get company metrics for particular company
API : GET {{apiserver}}/v4/metrics/company/{{companyID}}

**Comment by nirupamav** [comment]
**Testing In Progress**
**_Test Plan Link_** https://confluence.linuxfoundation.org/display/PROD/top-companies

**Comment by nirupamav** [comment]
@pranab-bajpai  @prasannamahajan 
As per the user story and the PRD, user's company VS other top 5 companies data has to be fetched. But as of now the API {{apiserver}}/v4/metrics/top-companies is fetching top 5 companies from the system irrespective of user's company. So if the user's company is fetched in the top 5 companies, I think there will be duplicate records in the UI, one record on the top for user's company and again the same record might be displayed in top 5 companies. Could please let me know how the behavior should be in this scenario

**Comment by dealako** [comment]
Regarding #3 - EasyCLA will not provide the logo - this is the responsibility of LFX UI (via the Project or Org/Company Service).

**Comment by nirupamav** [comment]
Observed that response message is **Metric not found** when invalid companyID is provided for API {{apiserver}}/v4/metrics/company/{{companyID}}. 
As per the discussion in Standup call on 9-Apr-2020, this is expected behavior and hence not logging a bug for this
![image](https://user-images.githubusercontent.com/60865903/78915497-a684bc80-7aa9-11ea-94ef-2f1f4e700924.png)

**Comment by nirupamav** [comment]
@dealako @pranab-bajpai 
If below counts are less than the top 5 companies data I think there could be issue in displaying the average count in the UI. Not sure if it is something LFX will handle in the UI or if change is required in the API. Could you please review this scenario
averageCompanyClaManagers
averageCompanyCorporateContributors
averageCompanyProjectCount

**Comment by mkdolan** [comment]
This is not a priority or anything we should be doing.

**Comment by dealako** [comment]
@pranab-bajpai can we close this ticket out?

**Comment by pranab-bajpai** [comment]
LF Staff pages were de-prioritized and redesigned with minimal metrics. Closing it.
