### ISSUE TITLE
EasyCLA V2 API for Usage Metrics + Adoption page - Activity Log

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#629]
## Summary

![image](https://user-images.githubusercontent.com/57362064/75411750-eb7fd580-58e5-11ea-9542-8377b9f26fcd.png)

- [x] Top 5 recent activity log messages from projects that are enforced under EasyCLA.
- [x] Notice that we will show 10 most recent messages with a pagination of 5 projects on each page. 
- [ ] Web page will invoke EasyCLA API that will return top 10 latest activity log messages after removing messages that give away contributor names or CLA Manager names.

## Background

This data is needed for lfx-dev to implement this page.
Step 11 in the following PRD

https://confluence.linuxfoundation.org/pages/viewpage.action?pageId=42993133

## User Story

As an employee of a company when I browse "Services" in CommunityBridge, I would like to see EasyCLA service, list out key relevant usage and adoption metrics related to that service. 

## Acceptance Criteria

API returns the metrics and information is rendered on LFX-Dev

**Comment by prasannamahajan** [comment]
API: GET {{apiserver}}/v4/events/recent

**Comment by nirupamav** [comment]
Bugs Logged #821

**Comment by nirupamav** [comment]
@pranab-bajpai 

As per discussion with @prasannamahajan , understood that events with **contains_pii=false** should be fetched for the Activity log. Could you please let me know which events  (for e.g create project, generate templates etc.,)  should have **contains_pii=false** that needs to be fetched for Activity log

**Comment by dealako** [comment]
Will get additional clarification on this - will ask Steve Winslow (legal) during our Wednesday meeting.

**Comment by dealako** [comment]
Will, once again, discuss with stakeholders. Plan to show them a few examples and get feedback.

**Comment by dealako** [comment]
@prasannamahajan @nirupamav @pranab-bajpai - regarding this topic, no need to filter by the PII flag. We will use the database query to filter and show event records:

- Project Manager perspective/views: select * from events where project id == "<project id value>" - so this will show all project-related event records. OK to see events from individuals or companies or project config stuff here. No restriction on seeing user names or emails.
- Company Admin/CLA Manager perspective/views: select * from events where project id == "<project id value>" and company id = "<company id value>". Ok to see all events from the company. No restriction on seeing user names or emails. Not ok to see event records from other companies. No ok to see events from individual contributors (users with no company).

**Comment by nirupamav** [comment]
Since the API is not fetching data as per above comments reopening the ticket

**Comment by dealako** [comment]
@pranab-bajpai can we close this ticket out?

**Comment by pranab-bajpai** [comment]
LF Staff pages were de-prioritized and redesigned with minimal metrics. Closing it.
