### ISSUE TITLE
Not able to see other companies when a company is added with too many characters

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#631]
## Background
1. Launch Corporate Console in dev environment
2. Login as CLA manager
3. Click on Get Started button
4. Enter company name with too many characters in Select Company field
5. Click ADD Company
6. Due to bug #582 the spinning icon keeps spinning so refresh the page to see the company
7. Observed that other companies are not visible and scroll bar is also not available to see other companies
![image](https://user-images.githubusercontent.com/60865903/75433344-ce92e300-5975-11ea-94a3-76d37ff41e36.png)

**List of other companies for the CLA Manager**
![image](https://user-images.githubusercontent.com/60865903/75433390-e1a5b300-5975-11ea-9239-c7647250727f.png)

**Comment by nirupamav** [comment]
The alignment of the companies changes when there are too many characters in the Company name. Initially the companies are center aligned and when the company name is too long the companies display is left aligned. Alignment of companies should be consistent and same in any scenario. Reopening the issue due to alignment issue
**_Initially Center aligned_**
![image](https://user-images.githubusercontent.com/60865903/77417177-07926c00-6deb-11ea-94e0-76360bcc7191.png)

**_Left aligned due to long company name_**
![image](https://user-images.githubusercontent.com/60865903/77417400-50e2bb80-6deb-11ea-8b88-741abf4ac3bb.png)


**Below scenarios are working as expected**
- Company name accepts only 150 characters
- Under "Company you are Associated with in EascyCLA", Company name with 100 characters and ellipsis is displayed when company name is more than 100 characters

**Comment by amolsontakke3576** [comment]
@nirupamav text is left aligned but width of the row depends on text length. and as per my suggestion it is right specially for mobile view.
let me know your thoughts.

**Comment by nirupamav** [comment]
@pranab-bajpai  @dealako 
This is a GUI issue. Alignment looks different based on the length of the company name. Based on above comments by Amol, could you please let us know if the alignment issues needs to be fixed

**Comment by dealako** [comment]
@amolsontakke3576 please:
- truncate the company name in the UI to 25 characters (show ellipsis if more, e.g. ...)
- tools tip/mouseover should show the entire name to the user
- center align always

**Comment by nirupamav** [comment]
**_Verified below scenarios in FF, Chrome and IE in windows 10 machine_**
1. Company name field accepts only 150 characters
2. When company name is more than 25 characters, Only first 25 characters are displayed along with ellipsis
3. When mouse hovered on the company, Irrespective of company name length, tool tip with entire company name is displayed
4. Companies are always center aligned
![image](https://user-images.githubusercontent.com/60865903/77618726-d639ad80-6f5c-11ea-8f80-dcb55e31566c.png)

![image](https://user-images.githubusercontent.com/60865903/77619133-93c4a080-6f5d-11ea-8507-dede8901d853.png)
