### ISSUE TITLE
Not able to Sign CLA for a project from corporate console

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#637]
## Background
1. Launch Project Management Console in dev environment and login as project manager
2. Click on a project
3. Add CLA Group "ProjMar02" and generated PDF's for CCLA and ICLA
4. Add a repository for the project
5. Launch Corporate console in dev environment and login as CLA Manager
6. Add a new company "March02Comp" 
7. Navigate to All Companies page and click on company "March02Comp"
8. Click on SIGN NEW CLA button
9. Select Project "ProjMar02" and click Submit
10. Click "Yes" for CLA Requirement prompt message
**NOTE:** The issue is also observed  when "No" is selected and request is sent to CLA Signatory
11. Observed error message is displayed and not able to sign CLA
![image](https://user-images.githubusercontent.com/60865903/75699302-43e41800-5cd6-11ea-983c-fe74d5e6995d.png)

**Request and payload for the request**
![image](https://user-images.githubusercontent.com/60865903/75699353-56f6e800-5cd6-11ea-8f0f-0501cbada331.png)

**Though response is 200, observed error message in the response content**
![image](https://user-images.githubusercontent.com/60865903/75699429-74c44d00-5cd6-11ea-8b28-86cea0708cd1.png)

**Comment by dealako** [comment]
@nirupamav ready for review.

**Comment by nirupamav** [comment]
**Verified and observed that CLA Manager is able to Sign CLA for new project**

**_When Yes is selected for Are you an authorized signatory with corporate authority?_**
![image](https://user-images.githubusercontent.com/60865903/77296561-e6a81900-6d0d-11ea-8d20-44cc28a1fd7a.png)

![image](https://user-images.githubusercontent.com/60865903/77296777-4a324680-6d0e-11ea-9d49-f46654abb369.png)

**_When No is selected for Are you an authorized signatory with corporate authority?_**
![image](https://user-images.githubusercontent.com/60865903/77297756-c416ff80-6d0f-11ea-81ee-bce8bac6a6c7.png)

![image](https://user-images.githubusercontent.com/60865903/77297826-dc871a00-6d0f-11ea-870e-55677ee34e6e.png)

![image](https://user-images.githubusercontent.com/60865903/77297914-02acba00-6d10-11ea-9b31-a014fba8fe79.png)

![image](https://user-images.githubusercontent.com/60865903/77298050-3a1b6680-6d10-11ea-9c62-a91c14db7c8f.png)

![image](https://user-images.githubusercontent.com/60865903/77298079-4acbdc80-6d10-11ea-8dac-e6a0a5c51b7d.png)
