### ISSUE TITLE
Not able to search for a company when there is letter after special characters

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#642]
## Background
1. Launch Corporate Console in dev environment
2. Login as CLA Manager
3. Click Get Started
4. Add a company name with apostrophe character for e.g **Niru's company** 
**Note:** Tried this as we have companies with special character. for e.g Hershey's
5. Due to bug #582 the spinning icon keeps spinning so refresh the page to see the added company
6. Click on Get Started button
7. Enter text Niru's
8. Observed there is no result for the search
**Without letter after special character able to see the company**
![image](https://user-images.githubusercontent.com/60865903/75768136-cbc73200-5d69-11ea-8ad7-08feb20c7ebd.png)

**With letter after special character not able to see the company**
![image](https://user-images.githubusercontent.com/60865903/75768183-e0a3c580-5d69-11ea-844e-f117cc99deff.png)

**Comment by hnexokonkwo** [comment]
pushed to DEV, ready for review/QA.

**Comment by nirupamav** [comment]
Verified and observed that user is able to search for company with special characters
![image](https://user-images.githubusercontent.com/60865903/77291460-51eced80-6d04-11ea-9474-a5fd8ae18822.png)

![image](https://user-images.githubusercontent.com/60865903/77291514-69c47180-6d04-11ea-983c-be8b7fdb6c48.png)


![image](https://user-images.githubusercontent.com/60865903/77291542-7a74e780-6d04-11ea-9631-b58f9672b8fa.png)

![image](https://user-images.githubusercontent.com/60865903/77291594-98424c80-6d04-11ea-9874-555ceb74ccfc.png)
