### ISSUE TITLE
Not able to request for CLA Signature when user is navigated to Contributor Console from github

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#644]
## Background

**Pre-requsite data**
-Github organization easyclatestplan with a repository corporateconsole should exist
-Github org should be installed for the project "CloudFoundry.org Foundation, Inc."
-CLA group "proj20200228182344" should be exist for both ccla and icla. Templates should be generated and "corporateconsole" repository of github organization "easyclatestplan" should be added to "proj20200228182344" cla group
-Github user should exist
-Company "i-flex" should exists and should not have signed CLA

**Steps to follow**
1. Launch github repository url https://github.com/easyclatestplan/corporateconsole
2. Login as github user
3. Update any file and Pull Request
4. Checks fail
5. Click on the link to Sign CLA
6. Click on Corporate
7. Select Company "i-flex"
8. Popup to select CLA Manager's email Id is displayed
9. Select Email ID
10. Click SEND button
11. Observed no action is performed and observed error in network tab console

**Error in Console**
![image](https://user-images.githubusercontent.com/60865903/75776921-f66db680-5d7a-11ea-95df-ec1cf7fb08af.png)

**Error in network tab**
![image](https://user-images.githubusercontent.com/60865903/75776955-0daca400-5d7b-11ea-9386-2d322828b1e6.png)

**Comment by nirupamav** [comment]
**_Tested and observed that email is not sent to the CLA Manager. Waited for 20 mins and still the CLA Manager did not receive the email and hence reopening the bug_**

![image](https://user-images.githubusercontent.com/60865903/77424960-fa2fae80-6df7-11ea-9048-a102f2a0bcbe.png)

![image](https://user-images.githubusercontent.com/60865903/77424988-0451ad00-6df8-11ea-9784-35c6dfe2ce4a.png)

**Comment by nirupamav** [comment]
**_Email is also not sent when Company does not exist and user manually enters CLA Manager details and requests access_**
![image](https://user-images.githubusercontent.com/60865903/77728969-9be71380-7023-11ea-9330-a4cf60991573.png)

**Comment by nirupamav** [comment]
@wanyaland 
Email is not sent even in the scenario when Company has signed CLA and Developer requests for whitelisting. 
Adding a comment here as it is related to the same email not sent issue. Let me know if I need to log another ticket for this issue

**Comment by WillsonHG** [comment]
This is still happening on staging. 
- email from contributor to manager requesting the company sign the cla was not delivered.
- email from contributor to manager requesting the manager to put them on the allow list was not delivered
- email from contributor requesting a cla manager to add their company was not delivered. 

The link to the logs where these events occur, an error can be seen for each  - https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/lambda/email-service-staging-email;stream=2020/04/16/%5B$LATEST%5D6426211be1274d7282db532b4ee3f0bd;start=2020-04-15T19:26:48Z

**Comment by dealako** [comment]
@nirupamav can you re-test/verify after I have updated the email logic.  Thanks!

**Comment by nirupamav** [comment]
@dealako 
Reopening the ticket as observed issues with emails and email content
**_Email is sent in below scenarios but observed issues_**
1. When ICLA is signed by Individual contributor email is sent but there are issues for which I have logged a ticket #963
2. When Employee Selects CLA Manager from list and send notification to authorize for company that has signed CLA, observed issues in email which is highlighted in below screenshot
![image](https://user-images.githubusercontent.com/60865903/79975901-52220980-84b9-11ea-8b9a-7af0a6e1b298.png)
3. When Employee enters CLA Manager's email directly and send notification to authorize for company that has signed CLA, observed issues in email which is highlighted in below screenshot
![image](https://user-images.githubusercontent.com/60865903/79976188-d4123280-84b9-11ea-8ccf-31b8de0595ab.png)
4. Company not signed and Employee send notification to CLA Manager to sign cla, observed issues in email which is highlighted in below screenshot. Also Company name is not displayed in content
![image](https://user-images.githubusercontent.com/60865903/79976558-716d6680-84ba-11ea-91dc-55c152e1fe4e.png)


**_Email is not sent below scenarios_**
1. When Company does not exist and contributor tries to send email notification to CLA Manager, observed no action is performed and error is displayed in console
![image](https://user-images.githubusercontent.com/60865903/79974972-d07dac00-84b7-11ea-9bf9-48ab1bf4531f.png)

**Comment by nirupamav** [comment]
Tested and updated the attached document with the issues in email content and links in email
[EmailNotifications.docx](https://github.com/communitybridge/easycla/files/4527293/EmailNotifications.docx)

**Comment by dealako** [comment]
The old v1 console is deprecated and removed.
