### ISSUE TITLE
EasyCLA V2 API for Usage Metrics + Adoption page - Total Contributors donut chart

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#659]
![image](https://user-images.githubusercontent.com/57362064/76094437-41104e00-5f88-11ea-9038-90d497656a31.png)

For rendering this donut graph the web page will get following data from EasyCLA API.

 Total contributors that contribute to projects where EasyCLA is enforced

- [x] Total number of Contributors
- [ ] Percentage of Corporate Contributors
- [ ] Percentage of Individual Contributors

Background
This data is needed for lfx-dev to implement this page.
Step 5 in the following PRD

https://confluence.linuxfoundation.org/pages/viewpage.action?pageId=42993133

User Story
As an employee of a company when I browse "Services" in CommunityBridge, I would like to see EasyCLA service, list out key relevant usage and adoption metrics related to that service.

Acceptance Criteria
API returns the metrics and information is rendered on LFX-Dev

**Comment by prasannamahajan** [comment]
API : GET {{apiserver}}/v4/metrics/total-count
api will return corporateContributorsCount, contributorsCount, individualContributorsCount

**Comment by nirupamav** [comment]
**Testing In Progress**
**_Test Plan Link_** https://confluence.linuxfoundation.org/display/PROD/total-count

**Comment by mkdolan** [comment]
We discussed not doing a split between corporate and individual. Please remove this and this is not High priority.

**Comment by dealako** [comment]
@pranab-bajpai can we close this one out?

**Comment by dealako** [comment]
incorporated in the v2 LFX contributor console.
