### ISSUE TITLE
EasyCLA V2 API for Usage Metrics + Adoption page - Total Number of Repositories Donut Chart

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#660]
![image](https://user-images.githubusercontent.com/57362064/76094604-83398f80-5f88-11ea-8077-3180b7d14f3d.png)

For rendering this donut graph the web page will get following data from EasyCLA API.

Total repositories where EasyCLA is enforced

- [x] Total number of Repositories
- [ ] Percentage of GitHub Repositories
- [ ] Percentage of Gerrit Repositories

Background
This data is needed for lfx-dev to implement this page.
Step 6 in the following PRD

https://confluence.linuxfoundation.org/pages/viewpage.action?pageId=42993133

User Story
As an employee of a company when I browse "Services" in CommunityBridge, I would like to see EasyCLA service, list out key relevant usage and adoption metrics related to that service.

Acceptance Criteria
API returns the metrics and information is rendered on LFX-Dev

**Comment by prasannamahajan** [comment]
API : GET {{apiserver}}/v4/metrics/total-count
This will return gerritRepositoriesCount, githubRepositoriesCount, repositoriesCount

**Comment by nirupamav** [comment]
**Testing In Progress**
**_Test Plan Link_** https://confluence.linuxfoundation.org/display/PROD/total-count

**_Bugs Logged_** #832, #835

**Comment by nirupamav** [comment]
**_Completed Testing and below is the status_**
**_Test Plan Link_** https://confluence.linuxfoundation.org/display/PROD/total-count
**TestId 16 - TestId 27**
![image](https://user-images.githubusercontent.com/60865903/80363242-8de61600-88a1-11ea-8c23-5b8c0ca9e233.png)

**Comment by dealako** [comment]
@pranab-bajpai can we close this one out?

**Comment by pranab-bajpai** [comment]
LF Staff pages were de-prioritized and redesigned with minimal metrics. Closing it.
