### ISSUE TITLE
EasyCLA V2 API for Usage Metrics + Adoption page - Total signed corporate CLAs donut chart

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#661]
![image](https://user-images.githubusercontent.com/57362064/76095053-3f935580-5f89-11ea-82be-cf23b10579f6.png)

For rendering this donut graph the web page will get following data from EasyCLA API.

Total signed corporate CLAs in EasyCLA

- [x] Total number of Corporate CLAs
- [ ] Percentage of Corporate CLAs signed by LF member companies
- [ ] Percentage of Corporate CLAs signed by non LF member companies

Background
This data is needed for lfx-dev to implement this page.
Step 7 in the following PRD

https://confluence.linuxfoundation.org/pages/viewpage.action?pageId=42993133

User Story
As an employee of a company when I browse "Services" in CommunityBridge, I would like to see EasyCLA service, list out key relevant usage and adoption metrics related to that service.

Acceptance Criteria
API returns the metrics and information is rendered on LFX-Dev

**Comment by prasannamahajan** [comment]
API to get total number of corporate cla
GET {{apiserver}}/v4/metrics/total-count

**Comment by prasannamahajan** [comment]
pull request : https://github.com/communitybridge/easycla/pull/744

**Comment by nirupamav** [comment]
Testing In Progress
**_Test Plan Link_** https://confluence.linuxfoundation.org/pages/viewpage.action?pageId=47579833

**Comment by swinslow** [comment]
As discussed on prior weekly call, we won't be doing this.

**Comment by dealako** [comment]
Closing out this ticket.
