### ISSUE TITLE
New user is not able to see added companies in Corporate Console

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#665]
## Background
1. Launch Corporate Console in dev environment
2. Create a new account
3. Verify email address
4. Add Company
5. Observed in newtork tab that added company is retrived in invites api but the company is not visible in UI
NOTE: Observed this issue with only new users. We are able to see companies added by exiting users
Cleared cache. Logged in as new user to corporate console. Added new company but still not able to see companies
**NEW USER**
![image](https://user-images.githubusercontent.com/60865903/76191276-fbac8480-6204-11ea-95e6-af052e261e08.png)

![image](https://user-images.githubusercontent.com/60865903/76191706-fdc31300-6205-11ea-866d-5348470f68c4.png)

**EXISTING USER**
![image](https://user-images.githubusercontent.com/60865903/76191832-424eae80-6206-11ea-9277-0b8d030d5166.png)

**Comment by dealako** [comment]
@amolsontakke3576 can you review and confirm?

**Comment by amolsontakke3576** [comment]
@dealako @wanyaland I have debugged this issue and below is my observation.

Request URL: https://api.dev.lfcla.com/v3/users/username/amolsontakke
Request Method: GET

response : 
```
{
  "companyID": "02c09d97-b726-4ccf-83a9-fb9074c50f46",
  "dateCreated": "2020-03-11T09:21:58Z",
  "dateModified": "2020-03-25T13:33:54Z",
  "emails": null,
  "lfEmail": "amols@proximabiz.com",
  "lfUsername": "amolsontakke",
  "userID": "c209eb98-6379-11ea-9c3e-4e72898c626d",
  "username": "Amol Santakke",
  "version": "v1"
}
```

As per above response when `companyID` present then only we are showing companies list and for new user `companyID` is missing.

**Comment by nirupamav** [comment]
**_Verified that issue is fixed_**

**New user**
![image](https://user-images.githubusercontent.com/60865903/77899284-1f119f00-729a-11ea-8d67-e273bb7412ea.png)

**Company Added to new user**
![image](https://user-images.githubusercontent.com/60865903/77899042-bd513500-7299-11ea-9643-b8cbaf50dbb4.png)
