### ISSUE TITLE
Contributor Console - Able to see Corporate option for Project that has only ICLA enabled

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#666]
## Background
**Prerequisite**
1. Valid github user with github organization "protractorframework" and repo "ui" for the organization should exist https://github.com/protractorframework/ui
2. CLA Group "Mar09CLAGroup1" with only ICLA enabled should exist.
3. Github repo "https://github.com/protractorframework/ui" should be added to CLA group "Mar09CLAGroup1"
![image](https://user-images.githubusercontent.com/60865903/76199543-120f0c00-6216-11ea-9565-6ee22c540ebc.png)

**Steps To Follow**
1. Launch github repo https://github.com/protractorframework/ui
2. Login as individual contributor(Any other github user)
3. Edit some file and create PR
4. Checks failed
5. Click on link to sign CLA
6. User is redirected to Contributor Console
7. Observed that Both Corporate and Individual options are displayed for project when only ICLA is enabled for the project
![image](https://user-images.githubusercontent.com/60865903/76199818-93ff3500-6216-11ea-9a03-52694d3be44e.png)

**Comment by dealako** [comment]
@amolsontakke3576 can you investigate. Seek assistance from @wanyaland if you need backend API support.

**Comment by nirupamav** [comment]
**Verified that only ICLA option is displayed when only ICLA is enabled for the project**
![image](https://user-images.githubusercontent.com/60865903/77282088-fc5a1600-6cee-11ea-865e-19109d348c30.png)

![image](https://user-images.githubusercontent.com/60865903/77282132-15fb5d80-6cef-11ea-8881-f8d79e33b62a.png)
