### ISSUE TITLE
Streamline the steps in the Documentation

### ISSUE THREAD

**Issue by timfong888** [communitybridge/easycla#67]
@manikantanr  -- it looks like you made some changes.  

Now it takes three steps just to know where to login, whereas mine had zero additional steps.  

Can you and Carey review: https://github.com/communitybridge/easycla/blob/master/docs/guide-to-user-guide.md

I made this to come up with a guide so that someone can just get into the app asap.

**Comment by jpalmerLinuxFoundation** [comment]
There is a series of sessions that are created when you log in. Logging out currently only removes one of them. There is a ticket open to address this so that a log out means what you think it means.

**Comment by dealako** [comment]
A couple of points:

**Comment by dealako** [comment]
Closing this issue during our backlog review. If additional help (be specific) is needed then please create a new ticket.
