### ISSUE TITLE
Corporate Console: Complete the signature process for a new project

### ISSUE THREAD

**Issue by wanyaland** [communitybridge/easycla#670]
## Summary

When a cla manager wants to begin the CLA signature process for a new project, they encounter an error 

## Background

1. A cla manager logs into corporate.lfcla.com and clicks their company
2. The cla manager selects the 'SIGN NEW CLA' button 
3. The cla manager selects the project
4. The cla manager clicks 'Yes' on the Cla requirement section 

## User Story

As a cla manager, I want to be able to sign a new CLA that takes me to the docusign process.

## Environment

* Environment: DEV

## Additional Context
When a request is made, the endpoint  api.dev.lfcla.com/v1/request-corporate-signature is hit and an error is thrown in the request-corporate-signature function(reference)

```
WARNING cla: No CCLA corporate signature for company: id:<company_id>, name: test_company_name, external id: None, manager id: <manager_id>, acl: {<user_id>} - Unable to load the Manager list.  Returning error response.
```

## Acceptance Criteria

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

https://github.com/communitybridge/easycla/blob/15cf3cb96ee357116264ffcd9ee2374c23e3d055/cla-backend/cla/models/docusign_models.py#L673-L682

**Comment by dealako** [comment]
@wanyaland If there is not CCLA present - then this is not an unrealistic error - we simply need to propagate this message/condition back to the user to that they can determine what do do next.

I am wondering if the query before this which looks to see if we have a CCLA actually checks to see if the CCLA was signed and approved. I would think that we would not get to this point and try to create the CCLA document when we don't have a signed document in the first place.

In summary:

1. If no manager -> user sends mail to someone he thinks can be the CLA Manager
1. If a manager, but no signed/approved CCLA -> user sends an email to the CLA Manager asking him/her to complete the signing process.
1. if a manager and signed/approved CCLA -> user can sign/request to be whitelisted

we need to make sure the API returns these conditions and the UI can handle them appropriately.

// CC @WillsonHG @pranab-bajpai - @wanyaland created this ticket from today's demo/illustration - feedback is welcome

**Comment by wanyaland** [comment]
@dealako Noted. Previously there was no check on signature approved and signature signed on the CCLA and probably was returning an unsigned instance which is now checked. I thought this stage would also handle signing new instances of CCLA since am signed in as a manager for a given company/project

**Comment by nirupamav** [comment]
Verified in #637 and hence closing the ticket
