### ISSUE TITLE
Align the content and definitions

### ISSUE THREAD

**Issue by timfong888** [communitybridge/easycla#68]
The blog has been worked through with @swinslow  and Dolan for messaging: 

https://github.com/communitybridge/easycla/blob/master/docs/getting-started.md#what-is-a-cla

Where is the content from here coming from and has legal reviewed?  We should have content aligned where we can:

 https://github.com/communitybridge/easycla/blob/master/docs/getting-started.md#what-is-a-cla

**Comment by jpalmerLinuxFoundation** [comment]
Are these two different links? Am I missing something?

**Comment by timfong888** [comment]
Oh, the cut and paste went wrong.  The versions are different, and I cut and paste from the blog into my original version of the getting-started doc.

https://www.linuxfoundation.org/blog/2019/07/easycla-beta/

Not sure if it's a good use of time introducing new content and then, if it hasn't been vetted, we go back and re-vet everything.

**Comment by dealako** [comment]
We've had several reviews on the current documentation since this issue was raised. Closing this issue during our backlog review. If additional help (be specific) is needed for the documentation, then please create a new ticket.
