### ISSUE TITLE
"Expected" status investigation.

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#682]
Ticket for investigating the "expected" status that has shown on a grpc repo with no apparent cause. Issue was resolved only after closing and reopening PR.

https://github.com/grpc/grpc/pull/22233

This issue is to track any other occurrences and gather information.

**Comment by WillsonHG** [comment]
Trying to match the timestamps in the pr with the logs to see where the "expected" status came from. there were several updates to the pr and there is one check in the logs at 20:48:28 that resulted in no status change being reported. The first link is an example of the pr being updated and the check rerunning and reporting success status. The second link is the check running and no status being reported. The third link is the last status report after she closed and reopened the pr, the status changed to success and the pr was merged.

3/4/2020 22:30:41 - creating new cla status on commit - success https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/lambda/cla-backend-prod-githubactivity;stream=2020/03/04/%5B$LATEST%5D81cdf9b5ce664484aa2cf34ed8b65951;refid=35310131134293755019564648020093724724185882790564265998;reftime=1583361041075

3/5/2020 20:48:28 - pr updated (force push) and https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/lambda/cla-backend-prod-githubactivity;stream=2020/03/05/%5B$LATEST%5Dc91e278677004fd0a9e9e87b0cd8c707;refid=35311921153649987305533918742285865954314906928570630179;reftime=1583441308319 no status reported

3/8/2020 23:09:51 - pr closed and reopened https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/lambda/cla-backend-prod-githubactivity;stream=2020/03/05/%5B$LATEST%5Daa0efa1bbb9a4298ae090c903af3e875;refid=35312110334194317475391101486495535077084997919977373754;reftime=1583449791468 - status updated as success.

**Comment by dealako** [comment]
Add additional debugging to check the GitHub API response code after we set the status. 

Confirm/Verify/Update:
- If successful, 200, indicate that the response was successful in the log
- If non-200, indicate the HTTP status code and any error message from GH in the log

**Comment by dealako** [comment]
@wanyaland Can you add some debug to confirm the status was sent back to GitHub and that we check the response code and report success or failure.

**Comment by dealako** [comment]
Not ready to close yet - added try/catch to note any exceptions.

**Comment by wanyaland** [comment]
So before creating a status was being logged for 2 cases ..unsigned and signed(failed, success) and this returns a 200. The try/catch was handling exceptions thrown by pygithub that would cater for successful(200) and non successful cases. Is that the flow you had requested for? Thanks
