### ISSUE TITLE
Open CLA button disappears after clicking New CLA

### ISSUE THREAD

**Issue by timfong888** [communitybridge/easycla#69]
https://cl.ly/af787c2f217f

1. Click New CLA
2. Select "Spinnaker"
3. Button appears saying "Open CLA"
4. Then disappears, User unable to click the Button.

@jacob

**Comment by jpalmerLinuxFoundation** [comment]
Hi @timfong888, I was able to reproduce. It looks like Dan L. setup Spinnaker, but did not set up a CLA template for CCLA managers to use. I'm not absolutely certain if this was set up as part of a demo or if it's going to be used to support a project. In any case, we should try to handle this scenario more elegantly.

**Comment by dealako** [comment]
For this task, we need to:

- [ ] Show an error page on the Corporate Console when the CLA Group has not created a CCLA/ICLA for the project.  We will need to review existing API calls to see if the information is available - or make a separate API call to fetch the template information (when missing we will show the error and hide the button.  The error message will have a link to the Support Page.
- [ ] Test/validate the scenario
- [ ] Demo to the stakeholders

**Comment by dealako** [comment]
Error Message suggestion:

**Comment by pranab-bajpai** [comment]
I agree this is short and to the point

**Comment by pranab-bajpai** [comment]
@dealako verified.
