### ISSUE TITLE
Add a CII badge

### ISSUE THREAD

**Issue by caniszczyk** [communitybridge/easycla#7]
https://bestpractices.coreinfrastructure.org/en

**Comment by dealako** [comment]
Registered EasyCLA: https://bestpractices.coreinfrastructure.org/en/projects?q=easycla

Need to do more analysis of security reporting and related processes.

**Comment by dealako** [comment]
Generated the CII Badge by filling out the self-survey here: https://bestpractices.coreinfrastructure.org/en/projects?q=easycla

Need to work with stakeholders and Product Owners to determine if we want to continue the evaluation and post the results to the main GH page.
