### ISSUE TITLE
Unable to sign in as Project Maintainer using my LFID

### ISSUE THREAD

**Issue by timfong888** [communitybridge/easycla#70]
This might because of a set-up, but we should also consider a clearer UX if it's because I am a project maintainer not added or my project isn't onboarded:

https://cl.ly/2fe5f791afbc

0. Create Incognito Tab
1. Click Sign in from https://project.lfcla.com/#/login
2. Enter my working LFID
3. Get login error message:

![image](https://user-images.githubusercontent.com/14055/61492362-2171e880-a9ec-11e9-8686-53643fbdf8d3.png)

**Comment by jpalmerLinuxFoundation** [comment]
@timfong888, I experienced this the first time I tried to use EasyCLA. You're right, it happens when your LF id doesn't have access to any projects. There's definitely a more elegant way to do this.
