### ISSUE TITLE
Email Service (Python) not reliable

### ISSUE THREAD

**Issue by wanyaland** [communitybridge/easycla#715]
## Summary

Currently the email service on the python backend is not reliable and in effect emails are not being sent.

## Background

1.Log onto the corporate console
2.Select company 
3. Click Sign New Cla
4. Select Project to Sign a CCLA
5. For CLA signing Requirement Click No(For non signatory with corporate authority)
6. Click No
7. Fill in details and complete process to send email to CLA signatory

## Expected behavior

Expected outcome is to receive an email ....however this is not certain and might be a success on some occasions

## Tasks
- [ ] Identify areas that use the python backend email service
- [ ] Publish message to an SNS topic in selected areas

**Comment by dealako** [comment]
@wanyaland I think this is where the email is sent: https://github.com/communitybridge/easycla/blob/master/cla-backend/cla/models/docusign_models.py#L946

which is via the docusign service API.  We need to investigate to see if our DEV account has a limit or other restrictions...

**Comment by dealako** [comment]
Issues is no longer present.
