### ISSUE TITLE
Project Manager has to refresh the page to view the newly added project(cla group)/Updated Project/generated templates/added repository

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#719]
## Background

1. Launch Project Management Console
2. Click on the Project
3. Add Project(CLA Group)
4. Earlier Page was auto refreshed and newly added project was visible. Now Project Manager has to refresh the page to view the Project
**_Project Manager has to refresh the page to even view the updated project , generated templates and added repositories_**

**After adding project**
![image](https://user-images.githubusercontent.com/60865903/77283027-75f30380-6cf1-11ea-8da6-8e4ca69e7eb1.png)

**After refreshing the page**
![image](https://user-images.githubusercontent.com/60865903/77283087-9c18a380-6cf1-11ea-85ea-2fe4e44e3730.png)

**Comment by dealako** [comment]
@hnexokonkwo please review and resolve.

**Comment by hnexokonkwo** [comment]
@nirupamav this is resolved. Please retest

**Comment by nirupamav** [comment]
**_Verified that the page auto refreshes after adding/editing project(cla group), adding/removing github repositories and after generating templates. Hence closing the ticket_**
![image](https://user-images.githubusercontent.com/60865903/77903752-0789e480-72a1-11ea-830f-b45a0e7440c5.png)
