### ISSUE TITLE
Move confluence docs to GitHub / README

### ISSUE THREAD

**Issue by caniszczyk** [communitybridge/easycla#72]
All documentation should be on GitHub and we should sunset confluence docs.

**Comment by timfong888** [comment]
When we do so @jacob (what is your handle?) and @carey (what is your handle) -- can we use my proposed guide?

I am open to changing it, but I want us to make it readable and usable (@manikantanr )

https://github.com/communitybridge/easycla/blob/master/docs/guide-to-user-guide.md

**Comment by timfong888** [comment]
@fayazg this GitHub is where we can track : https://jira.linuxfoundation.org/browse/PG-21  -- outstanding part of that thread is knowing sunsetting time.  Let's put that in the plan against this Issue.

**Comment by jpalmerLinuxFoundation** [comment]
> When we do so @jacob (what is your handle?) and @carey (what is your handle) -- can we use my proposed guide?
> 
> I am open to changing it, but I want us to make it readable and usable (@manikantanr )
> 
> https://github.com/communitybridge/easycla/blob/master/docs/guide-to-user-guide.md

@jpalmerLinuxFoundation

**Comment by caniszczyk** [comment]
Just checking up on this work

**Comment by timfong888** [comment]
There are alot of docs now ported: https://jira.linuxfoundation.org/browse/PG-21

@jpalmerLinuxFoundation  -- the docs from @CareyLF  are all correct and updated?

When the UX changes, these will need to bel updated as well when the time comes.

LMK then we can hopefully close this.
