### ISSUE TITLE
Footer is displayed on the top of the page and overlaps on the logo in contributor console

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#721]
## Background

1. Launch the github repository (which is configured to sign ICLA)
2. Login as contributor
3. Update any file and create PR
4. Checks fail
5. Click on the link to sign CLA
6. Contributor is redirected to contributor console
7. Click on Individual option
8. Observed that footer is displayed on the top of the page and overlaps on logo
![image](https://user-images.githubusercontent.com/60865903/77285365-cf116600-6cf6-11ea-95f3-2abf689c6dff.png)

**Comment by dealako** [comment]
@amolsontakke3576 please review the layout/footer to see if we can minimize the footer size and its ability to take over the UI....

**Comment by nirupamav** [comment]
**Verified in FF/Chrome/Edge and observed that the issue is fixed**
![image](https://user-images.githubusercontent.com/60865903/78869557-664e1b80-7a62-11ea-8d6a-b852dc0f5d9a.png)
