### ISSUE TITLE
Observed 400 bad request for Signing/monitoring api in network tab and user has to refresh the github repository page to see CLA Signed button

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#722]
# Background

1. Launch the github repository (which is configured to sign ICLA)
2. Login as contributor
3. Update any file and create PR
4. Checks fail
5. Click on the link to sign CLA
6. Contributor is redirected to contributor console
7. Click Individual option
8. User is navigated to docusign 
9. Enter all details in the template to sign the document
10. Click Finish
11. **Observed that after signing the document user is redirected to github repository page and "All Checks have passed" message is displayed but still CLA Not Signed button is displayed**
![image](https://user-images.githubusercontent.com/60865903/77286608-9fb02880-6cf9-11ea-9904-a0f8896a26bb.png)

12. **Observed that 400 bad request is returned for https://demo.docusign.net/Signing/monitoring?ti=7a9a2b7c0f4b4c50a1bdee3dc2171a34**

![image](https://user-images.githubusercontent.com/60865903/77286478-4fd16180-6cf9-11ea-92d8-ebfb2589135e.png)

13. **Observed that after user refreshes the page CLA Signed button is displayed**
![image](https://user-images.githubusercontent.com/60865903/77286703-d2f2b780-6cf9-11ea-8260-f769d882a6e4.png)

**Comment by dealako** [comment]
@wanyaland this is a tricky one - can you review the workflow to see if you can reproduce this issue that Niru has observed?

Normally GH auto-refreshes and shows a consistent view
Need to investigate the error from focusing to see if this is normal or not.

**Comment by dealako** [comment]
@wanyaland has confirmed that this is most-likely a GH refresh issue once the status has been updated for the PR. Nothing to fix or address on the EasyCLA side.

**Comment by WillsonHG** [comment]
We need to understand why this is happening in some cases. The most recent example is https://github.com/grpc/grpc/pull/22870

**Comment by dealako** [comment]
May be related to #2194

**Comment by dealako** [comment]
Created PR: https://github.com/communitybridge/easycla/pull/2202

How to test:

Create PR on repo which has EasyCLA configured and user has not signed
Notice the user is gated and the EasyCLA status check fails. Note the comment indicates failure.
Sign the CLA to authorize the user.
Navigate back to GitHub. Observe that the status check passes and that the old comment is updated with a pass/success.

**Comment by dealako** [comment]
Confirmed. Closing issue.
