### ISSUE TITLE
Observed 400 bad request for Signing/monitoring api in network tab and user has to refresh the Company page to see the CLA SignedProject

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#723]
# Background

1. Launch Corporate Console
2. Login as CLA Manager
3. Click on the Company
4. Click on SIGN NEW CLA Button
5. Select the project
6. Sign the CLA
7. **After the CLA is signed user is redirected to Companies page but the CLA Signed project is not displayed and observed 400 bad request for Signing/monitoring. CLA Manager has to refresh the page to view the project**
![image](https://user-images.githubusercontent.com/60865903/77297362-26bbcb80-6d0f-11ea-818a-9d0e1375f440.png)

**Comment by dealako** [comment]
@amolsontakke3576 please review and formulate a solution.

**Comment by amolsontakke3576** [comment]
@dealako @wanyaland I have checked this issue and it is from backend.
The `signatureSigned` key is missing for newly signed project for below end point

Request URL: https://api.dev.lfcla.com/v3/signatures/company/fed54bf8-b089-4677-a32d-6d1cf76f2e76?pageSize=50
Request Method: GET
Status Code: 200 

Response: 

`{
  "resultCount": 2,
  "signatures": [
    {
      "companyName": "Amol Company",
      "created": "2020-03-27T12:03:01.435811+0000",
      "domainWhitelist": null,
      "emailWhitelist": null,
      "githubOrgWhitelist": null,
      "githubWhitelist": null,
      "modified": "2020-03-27T12:03:01.435819+0000",
      "projectID": "7d5f7eee-10ab-4f7c-96d4-779a3699b569",
      "signatureACL": [
        {
          "companyID": "02c09d97-b726-4ccf-83a9-fb9074c50f46",
          "dateCreated": "2020-03-11T09:21:58Z",
          "dateModified": "2020-03-25T13:33:54Z",
          "emails": null,
          "lfEmail": "amols@proximabiz.com",
          "lfUsername": "amolsontakke",
          "userID": "c209eb98-6379-11ea-9c3e-4e72898c626d",
          "username": "Amol Santakke",
          "version": "v1"
        }
      ],
      "signatureApproved": true,
      "signatureCreated": "2020-03-27T12:03:01.435811+0000",
      "signatureID": "3b603974-cc39-4651-951c-4abaa78e3d6a",
      "signatureModified": "2020-03-27T12:03:01.435819+0000",
      "signatureReferenceID": "fed54bf8-b089-4677-a32d-6d1cf76f2e76",
      "signatureReferenceType": "company",
      "signatureSigned": true,
      "signatureType": "ccla",
      "version": "2.0"
    },
    {
      "companyName": "Amol Company",
      "created": "2020-03-27T12:03:01.435811+0000",
      "domainWhitelist": null,
      "emailWhitelist": null,
      "githubOrgWhitelist": null,
      "githubWhitelist": null,
      "modified": "2020-03-27T12:03:01.435819+0000",
      "projectID": "34d1bbaa-1b83-4141-9051-7667dffedbb3",
      "signatureACL": [
        {
          "companyID": "02c09d97-b726-4ccf-83a9-fb9074c50f46",
          "dateCreated": "2020-03-11T09:21:58Z",
          "dateModified": "2020-03-25T13:33:54Z",
          "emails": null,
          "lfEmail": "amols@proximabiz.com",
          "lfUsername": "amolsontakke",
          "userID": "c209eb98-6379-11ea-9c3e-4e72898c626d",
          "username": "Amol Santakke",
          "version": "v1"
        }
      ],
      "signatureApproved": true,
      "signatureCreated": "2020-03-27T12:03:01.435811+0000",
      "signatureID": "ca34ab00-c2cf-4b35-a404-d501d1eef7f1",
      "signatureModified": "2020-03-27T12:03:01.435819+0000",
      "signatureReferenceID": "fed54bf8-b089-4677-a32d-6d1cf76f2e76",
      "signatureReferenceType": "company",
      "signatureType": "ccla",
      "version": "2.0"
    }
  ],
  "totalCount": 11081
}`

**Comment by wanyaland** [comment]
@amolsontakke3576  On testing the workflow for signing up a new project  for a company, the api call  that you referenced above so happened to return the right response with right schema expected

**Comment by dealako** [comment]
The team discussed during the scrum. This is potentially a timing issue:

- Docusign webhook is called to update the database (signed = true)
- UI refreshes and shows the signed projects

If the UI refreshes before the API/DB is updated, we will not see the newly signed project in the list

@amolsontakke3576 please update the UI code to possibly delay or ?? to ensure the newly signed project appears.

**Comment by amolsontakke3576** [comment]
@dealako I have checked with timeout but it is not a feasible solution because 
1. Time required to update is unknown for us (Sometime it takes 1 sec some time 4 sec).
2. If we add max sec (Lets say 4 sec) then it will unnecessarily increase loading time for other workflow.

I think we need to discuss some other solution.

**Comment by dealako** [comment]
Async:
1. Docusign -> API via webhook -> Update Database -> signed = true
2. UI is redirected back to EasyCLA - on page load -> refresh of data -> wait 5 sec -> refresh data again - check to see if anything updated, refresh view

**Comment by nirupamav** [comment]
Verified that **wait we are loading signed CLA** is displayed until projects are loaded
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/7307dbb9-36f8-41ff-a4e1-94b0ece00a1f)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/886013f4-0c9f-46f0-8a00-12c6ed1d523b)
