### ISSUE TITLE
Error message issues while adding GitHub Organization

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#724]
## Background

1. Launch Project Management Console
2. Login as Project Manager
3. Click on the Project
4. Click on CONNECT GITHUB ORGANIZATION
5. Enter github organization with space for e.g. "CLASignature " 

**Issue1**
6. Observed error message "Github organization name not found. " is displayed
_Sometimes if user copy and pastes the org name there might be a spaces and hence spaces at the end should not be considered_
![image](https://user-images.githubusercontent.com/60865903/77299306-47395500-6d12-11ea-81d0-0d5e09f43453.png)

**Issue2**
7. Enter already existing github organization name and click connect. "This organization already exists" message is displayed. Now enter invalid github organization name and click Connect. Observed both messages "Github organization name not found. " and "This organization already exists" are displayed. 
_'This organization already exists' message should be cleared in this scenario_
![image](https://user-images.githubusercontent.com/60865903/77299840-1dccf900-6d13-11ea-9856-03b3aab557dd.png)

**Comment by dealako** [comment]
@nirupamav regarding issue #1 - this is expected, the GH Org check should return a 200 or 404 depending on the validity of the ORG

@hnexokonkwo regarding issue #2 identified above, ensure:
- we are trimming the GH org name (trim whitespace) when testing/validating
- clear error messages between attempts

**Comment by hnexokonkwo** [comment]
@nirupamav pushed to dev. please review

**Comment by nirupamav** [comment]
**_Verified that the issue is fixed. As soon as the user clicks on the "Enter GitHub Organization Account Name" field, the error message are cleared_**
