### ISSUE TITLE
CLA Manager/CLA Signatory is able to sign for a company a project with only ICLA template

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#727]
## Background
1. Launch Project Console
2. Login as Project Manager
3. Click on Foundation/External Project
4. Add CLA Group with only ICLA enabled and other required configuration for e.g Issue666
![image](https://user-images.githubusercontent.com/60865903/77311524-47435000-6d26-11ea-9548-8b2ea5bb5792.png)

5. Logout
6. Launch Corporate Console
7. Login as CLA Manager/ CLA Signatory
8. Click on the Company
9. Click on SIGN NEW CLA
10. Search and Select the project (for e.g Issue666)
11. Sign CLA
12. CLA Manager/CLA Signatory is able to sign a project with only ICLA enabled for the company
![image](https://user-images.githubusercontent.com/60865903/77311665-8ec9dc00-6d26-11ea-98ae-f41d9ea0baeb.png)

**Comment by dealako** [comment]
@wanyaland can you please review and diagnose the issue and formulate a solution?

**Comment by wanyaland** [comment]
@deelako During the signing process only unsigned projects for the company are returned and this can be filtered down to projects that have the project_ccla_enabled flag set to true

**Comment by wanyaland** [comment]
@nirupamav Could you verify ?

**Comment by nirupamav** [comment]
**_Verified and observed that only ICLA enabled projects are not displayed in project list in Corporate Console to Sign a CLA for a project_**

![image](https://user-images.githubusercontent.com/60865903/78013082-93fcdb80-7363-11ea-8dc9-d91b14e446b2.png)

![image](https://user-images.githubusercontent.com/60865903/78013113-9d864380-7363-11ea-9356-2fe130318853.png)

**_Also verified that projects with only CCLA or projects with both CCLA and ICLA are displayed in the projects list_**
![image](https://user-images.githubusercontent.com/60865903/78013217-c9092e00-7363-11ea-82ef-b84202ca677e.png)

![image](https://user-images.githubusercontent.com/60865903/78013248-d7574a00-7363-11ea-8d06-96501414d8f3.png)


![image](https://user-images.githubusercontent.com/60865903/78013297-e63dfc80-7363-11ea-961f-e15b352ae3fb.png)

![image](https://user-images.githubusercontent.com/60865903/78013334-f655dc00-7363-11ea-9bc7-2a1dd7324891.png)
