### ISSUE TITLE
Project Management Console - Ascending order sort issue in View Signatures Popup Window

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#734]
1. Launch Project Management Console
2. Login as Project Manager
3. Click on the External Project(Or Foundation)
4. Click on View Signatures for a Project(CLA Group) which has signatures
5. Click on any column for e.g Company
6. Data is sorted in ascending order
7. Now click again on the column
6. Data is sorted in descending order
7. Now click again on the column
8. Observed no action is performed
9. Now click again and data is sorted in ascending order.
**_Issue observed for all columns_**

**Comment by dealako** [comment]
@hnexokonkwo please review and confirm. If resolved, ask @nirupamav to re-test.

**Comment by hnexokonkwo** [comment]
@nirupamav issue resolved. PLea re-test

**Comment by nirupamav** [comment]
**Verified and observed that sort by company is not working as expected. Until this issue is fixed cannot verify this ticket**
**_By Ascending Order_**
![image](https://user-images.githubusercontent.com/60865903/77906031-e0cdad00-72a4-11ea-8fd2-8ec479072062.png)

**_By Descending Order_**
![image](https://user-images.githubusercontent.com/60865903/77906126-0eb2f180-72a5-11ea-8bfe-066d29cce107.png)

**Comment by hnexokonkwo** [comment]
@nirupamav This issue was due to the list not having company name in individual object. This has been fixed and I will send a PR soon.

**Comment by hnexokonkwo** [comment]
@nirupamav please retest

**Comment by nirupamav** [comment]
Verified and observed that the issue is fixed
