### ISSUE TITLE
Project Management Console - Search By Company is not working in View Signatures popup window

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#735]
## Background

1. Launch Project Management Console
2. Login as Project Manager
3. Click on the External Project(Or Foundation)
4. Click on View Signatures for a Project(CLA Group) which has CCLA signatures
5. Click on Company
6. Enter company name (which exists in the results) in search field and click on Search
7. No data is returned. Enabled Full Match and tried. Still no data was returned
**Before Search**
![image](https://user-images.githubusercontent.com/60865903/77398351-592bfe00-6dcd-11ea-8231-f4c1dee7cf60.png)

**After Search**
![image](https://user-images.githubusercontent.com/60865903/77398293-40bbe380-6dcd-11ea-8537-6d5a3c3490d3.png)

![image](https://user-images.githubusercontent.com/60865903/77398318-4a454b80-6dcd-11ea-8cfa-482fb1c8ac7a.png)

**Comment by dealako** [comment]
@hnexokonkwo can you review the search issue?

**Comment by nirupamav** [comment]
Verified Search by Company and name is working in View Sigantures
![image](https://user-images.githubusercontent.com/60865903/87412271-7720a700-c5e6-11ea-876c-f187e1fde1aa.png)

![image](https://user-images.githubusercontent.com/60865903/87412320-87388680-c5e6-11ea-800d-0a4023ffe8d0.png)
