### ISSUE TITLE
Project Management Console - Issues with sorting after data is sorted by Company in View Signatures popup window

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#737]
## Background

1. Launch Project Management Console
2. Login as Project Manager
3. Click on the External Project(Or Foundation)
4. Click on View Signatures for a Project(CLA Group) which has ICLA and CCLA signatures
5. Click on Company column
6. Data is sorted by ascending order of company
7. Now click on any other column for e.g Github Id or Date
8. Observed only data of Individual type are sorted

**_Initially when View Signatures popup window is opened_**
![image](https://user-images.githubusercontent.com/60865903/77399727-04d64d80-6dd0-11ea-908c-4f9a252fbda9.png)

**_After Clicking on Company Column_**
![image](https://user-images.githubusercontent.com/60865903/77399778-1cadd180-6dd0-11ea-8946-9d4029f6cd12.png)

**_After clicking on Date Column_**
![image](https://user-images.githubusercontent.com/60865903/77399844-3b13cd00-6dd0-11ea-970b-2fe8521f7a5b.png)

**Comment by dealako** [comment]
@hnexokonkwo please review and see if this is still an issue. In needed, please resolve. If not, please ask @nirupamav to retest.

**Comment by hnexokonkwo** [comment]
@nirupamav this is resolved. Please retest

**Comment by nirupamav** [comment]
Testing blocked by #734

**Comment by hnexokonkwo** [comment]
@nirupamav #734 has been fixed, please review

**Comment by amolsontakke3576** [comment]
@dealako  Verified and looks fixed.

**Comment by dealako** [comment]
The old console is deprecated and removed.
