### ISSUE TITLE
Project Management Console: Popup window is still displayed when navigated back to All Projects page in the browser

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#739]
## Background
1. Launch Project Management Console
2. Login as Project Manager
3. Click on Foundation(External Project)
4. Click on Add CLA Group
5. CLA Group popup window is opened
6. Click on Back button in the browser
7. User is able to navigate back to All Projects while the CLA Group popup window is still open
**_Issue also observed for all popups that are displayed in the page_**

![image](https://user-images.githubusercontent.com/60865903/77402999-8b415e00-6dd5-11ea-8996-b7efd76f0b39.png)

**Comment by nirupamav** [comment]
Issue is still reproducible for all popup's in the UI and hence reopening the ticket
![image](https://user-images.githubusercontent.com/60865903/77611129-8d78f900-6f4a-11ea-8c39-4f8afe869b08.png)

**Comment by amolsontakke3576** [comment]
@dealako @nirupamav  Solved browser back button issue for popup on below model. Please let me know if any missing.
- Connect Github Account
- Delete Github Account
- Add CLA Group
- Delete CLA Group
- View Signatures
- View Companies
- Configure Github Repositories
- Add Gerrit Instance

**Comment by nirupamav** [comment]
**_Observed that issue is not fixed for below scenarios and hence reopening the ticket_**

**1. CCLA template history popup**
![image](https://user-images.githubusercontent.com/60865903/79218626-55d8df00-7e6e-11ea-87b0-f07eb5003e8b.png)
**2. CCLA PDF Viewer**
![image](https://user-images.githubusercontent.com/60865903/79218739-8ae53180-7e6e-11ea-986c-36082336d1ae.png)
**3. ICLA template history popup**
![image](https://user-images.githubusercontent.com/60865903/79218684-6f7a2680-7e6e-11ea-9056-d547727e84c6.png)
**4. ICLA PDF viewer**
![image](https://user-images.githubusercontent.com/60865903/79218808-afd9a480-7e6e-11ea-9daa-e3227e5c4497.png)
**5. Connect LF CLA App to GitHub Organization popup**
![image](https://user-images.githubusercontent.com/60865903/79219036-2080c100-7e6f-11ea-95cf-cac8d4551947.png)
6. Github login alert
![image](https://user-images.githubusercontent.com/60865903/79219153-5c1b8b00-7e6f-11ea-9e28-0850bafb10a8.png)



**_Verified below scenarios and observed that popup window is closed and projects page is displayed_**
1. Add GitHub  Organization popup
2. CLA group popup when clicked on ADD CLA GROUP 
3. CLA group popup when clicked configuration icon for the cla group
4. View Signatures popup
5. View Companies popup from both the View Companies button
6. Delete alert popup
7. Delete confirmation popup
8. Configure Github Repositories popup
9. Add Gerrit Instance popup
10. Delete Github Organization


When clicked on back button from Select Template page user is redirected to Foundation details page

**Comment by amolsontakke3576** [comment]
@nirupamav Thanks for list down missing screens. I will solve the above.

**Comment by nirupamav** [comment]
**_Verified below scenarios and observed that popup window is closed and projects page is displayed_**
1. Add GitHub Organization popup
2. Connect LF CLA App to GitHub Organization popup
3. Github login alert popup from Connect LF CLA App to GitHub Organization
4. CLA group popup when clicked on ADD CLA GROUP
5. CLA group popup when clicked configuration icon for the cla group
6. View Signatures popup
7. View Companies popup from both the View Companies button
8. Delete CLA Group alert popup
9. Delete CLA Group confirmation popup
10. Configure Github Repositories popup
11. Add Gerrit Instance popup
12. Delete Github Organization
13. CCLA template history popup
14. CCLA PDF Viewer
15. ICLA template history popup
16. ICLA PDF Viewer

When clicked on back button from Select Template page user is redirected to Foundation details page
