### ISSUE TITLE
Contributor Console - Company name overlaps with Cancel and Send button when company has not signed CLA

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#741]
## Background
Pre-req
1. CLA project should be created with CCLA enabled
2. Github repository should be added to the CLA Project
3. **Company with name having too many characters should exist and Companu should not have signed CLA**

**Steps To Follow**
1. Launch github and login as developer
2. Navigate the repository
3. Edit some file and create PR
4. CLA checks fails
5. Click on CLA NOT SIGNED button
6. User is redirected to Contributor Console
7. Click Corporate
8. Select the Company which has not signed CLA
9. Observed company name overlaps with CANCEL and SEND button

![image](https://user-images.githubusercontent.com/60865903/77424357-fb141080-6df6-11ea-962c-ca5530eb56e1.png)

**Another Example**
![image](https://user-images.githubusercontent.com/60865903/77424726-9ad19e80-6df7-11ea-9b36-d76d14335003.png)

**Comment by dealako** [comment]
@amolsontakke3576 In this case, please shorten the name and then use ellipses after 25 characters. Add a tooltip/mouseover to show the full name if the user hovers over the text.

**Comment by nirupamav** [comment]
**Verified and observed that issue is fixed**
![image](https://user-images.githubusercontent.com/60865903/77900698-0c986500-729c-11ea-93c6-e97157d55599.png)

**Also observed that project name overlaps on cancel button when project name is long and bug #774 has been logged to track the issue**
