### ISSUE TITLE
Migrate Project Management Console APIs to Golang

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#748]
## Summary

Several of the APIs used by the Project management console need migration to golang to support 1) consolidated queries and 2) LFX V2 API integration.

## Background

Migrate the following Python APIs to Golang (v3):

'/v1/sfdc/' + sfid + '/github/organizations'
`/v1/github/get/namespace/${namespace}`
'/v1/github/organizations/' + organizationName + '/repositories' (edited) 

Provide Golang implementation for these endpoints:
- [x] Include these endpoints into the v3 swagger specification, review, and cleanup API endpoint/path as necessary (doesn't have to match exactly - e.g. what is a "namespace"? can we use a better term/concept here?)
- [x] Define the request, response, and error models in the swagger specification. Ensure documentation/examples are added to support api-docs readability.
- [x] If possible, when possible, consolidate the API quests into one endpoint (e.g. avoid duplicate/similar endpoints and data models)
- [x] Develop the golang handler to support the new v3 endpoints
- [x] Develop the service handler
- [x] Develop the repository/database handler
- [x] Write functional tests to query known data in DEV
- [x] Write v4 swagger specification - provide pass-through to v3 data models
- [x] Update acs-cli specification to allow queries of GH/Gerrit data for authenticated users (view_all for now).
 
## User Story

As a developer, I want to optimize the PMC queries.
As a developer, I want to consolidate API requests to the golang backend API.
As a developer, I want to support LFX v2 integration by using golang to invoke the legacy v3 API

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

\(Optional\) Provide any code or specification references that would be helpful for the developer implementing this feature.

@prasannamahajan please consult @hnexokonkwo for the PMC API calls and use-cases if needed.

**Comment by prasannamahajan** [comment]
@dealako @hnexokonkwo 
Pull request : 
https://github.com/LF-Engineering/acs-cli/pull/131
https://github.com/communitybridge/easycla/pull/776

API : GET {{apiserver}}/v4/project/a0941000002wBz4AAE/github/organizations
Sample Response:
`
{
    "list": [
        {
            "dateCreated": "2019-12-31T07:20:31.539542+0000",
            "dateModified": "2019-12-31T07:20:31.539549+0000",
            "githubInfo": {
                "error": "unable to get github info of https://github.com/KD-CLAOrg"
            },
            "organizationName": "https://github.com/KD-CLAOrg",
            "organizationSfid": "a0941000002wBz4AAE",
            "repositories": {
                "list": []
            },
            "version": "v1"
        },
        {
            "dateCreated": "2020-01-27T23:48:05.153149+0000",
            "dateModified": "2020-01-27T23:48:05.153155+0000",
            "githubInfo": {
                "error": "unable to get github info of https://github.com/project-Jan-27-2020"
            },
            "organizationName": "https://github.com/project-Jan-27-2020",
            "organizationSfid": "a0941000002wBz4AAE",
            "repositories": {
                "list": []
            },
            "version": "v1"
        },
        {
            "dateCreated": "2020-03-27T10:48:25.992595+0000",
            "dateModified": "2020-03-27T10:48:25.992604+0000",
            "githubInfo": {
                "details": {
                    "htmlUrl": "https://github.com/test-harold-org",
                    "id": 62747663
                }
            },
            "organizationInstallationID": 7581354,
            "organizationName": "test-harold-org",
            "organizationSfid": "a0941000002wBz4AAE",
            "repositories": {
                "list": [
                    "test-harold-org/repo1",
                    "test-harold-org/repo2"
                ]
            },
            "version": "v1"
        },
        {
            "dateCreated": "2020-02-06T09:31:49.245630+0000",
            "dateModified": "2020-02-06T09:31:49.245646+0000",
            "githubInfo": {
                "details": {
                    "htmlUrl": "https://github.com/kdhaigud",
                    "id": 52558085
                }
            },
            "organizationInstallationID": 6635271,
            "organizationName": "kdhaigud",
            "organizationSfid": "a0941000002wBz4AAE",
            "repositories": {
                "list": [
                    "kdhaigud/CLA_repo_7Feb",
                    "kdhaigud/easycla",
                    "kdhaigud/EdgeCheck",
                    "kdhaigud/fundingprojectdetails-spec.js",
                    "kdhaigud/Funding_API_Document",
                    "kdhaigud/latex",
                    "kdhaigud/Lorem-Ipsum-is-simply-dummy-text-of-the-printing-and-typesetting-industry.",
                    "kdhaigud/Mentorship_API_Document",
                    "kdhaigud/mypublicrepo",
                    "kdhaigud/mypublicrepo2",
                    "kdhaigud/mypublicrepo3",
                    "kdhaigud/mypublicrepo4",
                    "kdhaigud/myrepo",
                    "kdhaigud/publicrepo5",
                    "kdhaigud/publicrepo6",
                    "kdhaigud/publicrepo7",
                    "kdhaigud/testpaln",
                    "kdhaigud/VD-API-tets-case",
                    "kdhaigud/webpack"
                ]
            },
            "version": "v1"
        },
        {
            "dateCreated": "2020-02-25T16:53:07.607699+0000",
            "dateModified": "2020-02-25T16:53:07.607710+0000",
            "githubInfo": {
                "error": "unable to get github info of ngozi-test-org"
            },
            "organizationName": "ngozi-test-org",
            "organizationSfid": "a0941000002wBz4AAE",
            "repositories": {
                "list": []
            },
            "version": "v1"
        },
        {
            "dateCreated": "2020-01-28T09:12:24.988022+0000",
            "dateModified": "2020-01-28T09:12:24.988029+0000",
            "githubInfo": {
                "details": {
                    "htmlUrl": "https://github.com/prasannamahajan",
                    "id": 1476068
                }
            },
            "organizationInstallationID": 6462701,
            "organizationName": "prasannamahajan",
            "organizationSfid": "a0941000002wBz4AAE",
            "repositories": {
                "list": [
                    "prasannamahajan/testcla"
                ]
            },
            "version": "v1"
        },
        {
            "dateCreated": "2020-03-10T09:07:59.503760+0000",
            "dateModified": "2020-03-10T09:07:59.503767+0000",
            "githubInfo": {
                "details": {
                    "htmlUrl": "https://github.com/dsss",
                    "id": 6042439
                }
            },
            "organizationName": "dsss",
            "organizationSfid": "a0941000002wBz4AAE",
            "repositories": {
                "list": []
            },
            "version": "v1"
        },
        {
            "dateCreated": "2020-03-10T13:45:35.953944+0000",
            "dateModified": "2020-03-10T13:45:35.953952+0000",
            "githubInfo": {
                "details": {
                    "htmlUrl": "https://github.com/March-10-2020",
                    "id": 62021197
                }
            },
            "organizationInstallationID": 7247313,
            "organizationName": "March-10-2020",
            "organizationSfid": "a0941000002wBz4AAE",
            "repositories": {
                "list": [
                    "March-10-2020/repo1"
                ]
            },
            "version": "v1"
        },
        {
            "dateCreated": "2020-03-10T09:07:59.503760+0000",
            "dateModified": "2020-03-10T09:07:59.503767+0000",
            "githubInfo": {
                "details": {
                    "htmlUrl": "https://github.com/cla-testorg",
                    "id": 61993916
                }
            },
            "organizationName": "cla-testorg",
            "organizationSfid": "a0941000002wBz4AAE",
            "repositories": {
                "list": []
            },
            "version": "v1"
        },
        {
            "dateCreated": "2020-02-13T08:52:56.306683+0000",
            "dateModified": "2020-02-13T08:52:56.306690+0000",
            "githubInfo": {
                "details": {
                    "htmlUrl": "https://github.com/confugorg",
                    "id": 61005352
                }
            },
            "organizationName": "confugorg",
            "organizationSfid": "a0941000002wBz4AAE",
            "repositories": {
                "list": []
            },
            "version": "v1"
        },
        {
            "dateCreated": "2020-02-18T13:20:22.078282+0000",
            "dateModified": "2020-02-18T13:20:22.078289+0000",
            "githubInfo": {
                "error": "unable to get github info of ngozi-ionic"
            },
            "organizationInstallationID": 6854001,
            "organizationName": "ngozi-ionic",
            "organizationSfid": "a0941000002wBz4AAE",
            "repositories": {
                "error": "unable to get repositories for installation id : 6854001",
                "list": []
            },
            "version": "v1"
        }
    ]
}
`

**Comment by dealako** [comment]
Migrated.
