### ISSUE TITLE
Project Console - Page does not auto refresh after EascyCLA App is installed/configured in github 

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#754]
## Background
1. Launch Project Management Console
2. Login as Project Manager
3. Click on "Academy Software Foundation"
4. Click on CONNECT GITHUB ORGANIZATION
5. Enter valid Github organization name
6. Click CONNECT button
7. Click INSTALL
8. User is redirected ti github in another tab
9. SignIn to github if not already logged in
10. Install/Configure the EasyCLA APP
11. After the installation is complete, click on the browser tab where project console is opened
12. **_Earlier the UI used to auto refresh to display the configured github Organization. But now "Not Configured. Please connect the CLA App to the Github Org." message is still displayed and user has to refresh the page to view if org is configured_**

**Comment by amolsontakke3576** [comment]
@dealako Looks like working fine.

**Comment by dealako** [comment]
The old v1 console is deprecated and removed.
