### ISSUE TITLE
Project Console - Data is not Sorted in descending order (latest to oldest) when the CLA was signed in View Signatures popup window

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#758]
## Background

**Prerequisite**

1. A CLA Group(Project) should Exist
2. More than 100 CLA Signatures(ICLA and CCLA) should exist for the project

**Steps To Follow**

1. Launch Project Management Console
2. Login as Project Manager
3. Click on the Foundation "CloudFoundry.org Foundation, Inc."
4. Click on VIEW SIGNATURES for project "Issue666CCLA_ICLA"
5. **_Observed that each time data is returned in different order. As per the comments in #327 data should be sorted in descending order (latest to oldest) when the CLA was signed. Also when Reset button is clicked the data should be in default sort order i.e in descending order (latest to oldest) when the CLA was signed _**
![image](https://user-images.githubusercontent.com/60865903/77656203-862d0c00-6f99-11ea-83c2-363ee2ea62ed.png)

**_Attempt1_**
![image](https://user-images.githubusercontent.com/60865903/77656258-9cd36300-6f99-11ea-865b-73b78ad5279a.png)

**_Attempt2_**
![image](https://user-images.githubusercontent.com/60865903/77656315-afe63300-6f99-11ea-8adb-1a6f8d6a939b.png)

**_Attempt3_**
![image](https://user-images.githubusercontent.com/60865903/77656393-d1471f00-6f99-11ea-9bc2-f61e83062291.png)

**Comment by amolsontakke3576** [comment]
@dealako Tested and look working fine as per expected.

**Comment by dealako** [comment]
The old v1 console is deprecated and removed.
