### ISSUE TITLE
Project Console - VIEW COMPANIES is enabled for project which has only ICLA enabled

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#761]
## Background
1. Launch Project Management Console
2. Login as Project Manager
3. Click on Foundation "CloudFoundry.org Foundation, Inc. "
4. Add CLA Group with only ICLA enabled
5. Observed VIEW COMPANIES is enabled for the project with only ICLA enabled
![image](https://user-images.githubusercontent.com/60865903/77724596-62a9a600-7019-11ea-82b9-4812044ede46.png)

![image](https://user-images.githubusercontent.com/60865903/77724654-879e1900-7019-11ea-84f6-c130297582d2.png)

**Comment by nirupamav** [comment]
**_Tested and observed that View Companies is still displayed_**
![image](https://user-images.githubusercontent.com/60865903/80194122-8de2dd80-8637-11ea-8cdf-6b699fb2db7f.png)

**Comment by amolsontakke3576** [comment]
@nirupamav Issue is dependent on #981 once that it fixed it will be resolved.

**Comment by nirupamav** [comment]
Verified that VIEW COMPANIES is not displayed when only ICLA is enabled for the project
**_New Project_**
![image](https://user-images.githubusercontent.com/60865903/80347645-32f4f480-888a-11ea-8a0c-e6e16fd7778c.png)

**_Existing project_**
![image](https://user-images.githubusercontent.com/60865903/80347745-57e96780-888a-11ea-8e8d-8b6518a715b8.png)
