### ISSUE TITLE
CLA checks fails for developer/contributor when "Contributors under Corporate CLA must also sign Individual CLA" is unchecked

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#765]
## Background
**Prerequisite**
1. Project _**ProjectWithCCLAandICLAButNoICLASignForCorporate**_ with ICLA and CCLA enabled and **_Contributors under Corporate CLA must also sign Individual CLA checkbox unchecked_** should exist
![image](https://user-images.githubusercontent.com/60865903/77731666-5299c280-7029-11ea-83c8-5beef040888d.png)

2. Github repository should https://github.com/selenium-af/dev should be configured for the project
![image](https://user-images.githubusercontent.com/60865903/77731873-c6d46600-7029-11ea-8799-8bf7f99ffc5c.png)

3. Company **_CCLA_ICLAButNoICLASign_** should exist and should have signed CLA for project **_ProjectWithCCLAandICLAButNoICLASignForCorporate_**
![image](https://user-images.githubusercontent.com/60865903/77732327-a22cbe00-702a-11ea-92b5-26d7f5c3fb69.png)

Steps to **follow**
1. Launch the github repository https://github.com/selenium-af/dev
2. Login to github as developer/contributor
3. Update any file and create PR
4. **_Observed CLA checks failed even when Corporate has already signed the CLA for the project and 
"Contributors under Corporate CLA must also sign Individual CLA" checkbox is unchecked for the project_**
![image](https://user-images.githubusercontent.com/60865903/77732066-1fa3fe80-702a-11ea-916d-adccb2ff2df5.png)

**Comment by WillsonHG** [comment]
Corporate contributors still need to verify with their company. They need to select "corporate" --> their company --> i verify i am associated with company. At this point, the pr should refresh and status change to authorize. If the "contributor under cla must also sign icla " were checked, they would be redirected to sign an icla as well. Will verify in dev that this is the case.

**Comment by dealako** [comment]
This issue appears to be resolved. Closing ticket.
