### ISSUE TITLE
Corporate Console - Missing data and Overlap issues when Project name is too long

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#766]
## Background
1. Launch Corporate Console
2. Login as CLA Manager
3. Click on a Company
4. Sign CLA for a project with long project name
5. Observed alignment and overlap issues

**_Pending Requests column is missing_**
![image](https://user-images.githubusercontent.com/60865903/77732798-a9080080-702b-11ea-99a7-f7ff24a7ae84.png)

**_Click on View Manager for Signed Project. Project name overlaps on X(close) button_**
![image](https://user-images.githubusercontent.com/60865903/77732681-5cbcc080-702b-11ea-8549-0b011cab5194.png)

**Comment by WillsonHG** [comment]
We have project names as long as this test case in prod, so this would effect prod if we pushed without fixing this.

**Comment by nirupamav** [comment]
**_Verified that the issue is fixed_**
![image](https://user-images.githubusercontent.com/60865903/78010741-5a76a100-7360-11ea-9276-67389a978dbe.png)

![image](https://user-images.githubusercontent.com/60865903/78010786-65313600-7360-11ea-9130-338c43bf8f32.png)
