### ISSUE TITLE
Project Console - Data not loaded in View Companies for project Issue666CCLA_ICLA having more than 100 signatures

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#767]
## Background
**Prerequisite**

1. A CLA Group(Project) **Issue666CCLA_ICLA** should Exist
2. More than 100 CLA Signatures(ICLA and CCLA) should exist for the project

**Steps To Follow**

1. Launch Project Management Console
2. Login as Project Manager
3. Click on the Foundation **CloudFoundry.org Foundation, Inc.**
4. Click on VIEW COMPANIES for project **Issue666CCLA_ICLA**
5. Observed UI hangs with spinning icon and observed below error in console and 400 returned for the api call in network tab
**_NOTE - Data is fetched in VIEW SIGNATURES for the same project. Also observed this issue only for the project Issue666CCLA_ICLA. The only difference I see in this project is that it has more than 100 CLA signatures_**

![image](https://user-images.githubusercontent.com/60865903/77745020-91874280-7040-11ea-9e7f-e517f45cdd93.png)

![image](https://user-images.githubusercontent.com/60865903/77744948-71f01a00-7040-11ea-942b-32bcdbb7530d.png)

![image](https://user-images.githubusercontent.com/60865903/77744994-87654400-7040-11ea-9ecb-5ad24de5421b.png)

**Comment by amolsontakke3576** [comment]
@dealako @nirupamav I have tested as per the steps mentioned above and it's seem that there is no issue and companies loaded in popup. 
@nirupamav can you retest it again ?

PFA
![Screenshot from 2020-04-23 13-31-10](https://user-images.githubusercontent.com/56335654/80074505-e26a5800-8566-11ea-83fa-e1b8c0c7b1ef.png)

**Comment by nirupamav** [comment]
@amolsontakke3576 The ticket was logged 27 days ago. Looks like the issue is fixed now. Moving to Review Complete
![image](https://user-images.githubusercontent.com/60865903/80089387-78a87900-857b-11ea-9819-0d6b572e390c.png)
