### ISSUE TITLE
Pending Whitelists are fetched based on company and displayed in Manage whitelists for all projects

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#768]
## Background
1. Launch Corporate Console
2. Login as CLA Manager
3. Click on the Company which has signed more than 1 project and only one project should have pending whitelists
4. Observed that count is displayed correctly
![image](https://user-images.githubusercontent.com/60865903/77413835-06ab0b80-6de6-11ea-91e6-23f30dd80f43.png)
5. But when clicked on Manage Whitelist for the company which has 0 count, records of pending whitelists of other projects are displayed. So irrespective whether project has whitelist or not, the pending whitelists of the company are displayed for every project

![image](https://user-images.githubusercontent.com/60865903/77413736-d499a980-6de5-11ea-9312-17e643763a03.png)

**_Manage Whitelist UI for both Project Issue666CCLA_ICLA and Project Issue666CCLA display same data_**
![image](https://user-images.githubusercontent.com/60865903/77413868-162a5480-6de6-11ea-97d7-a949f51c04f6.png)

**Comment by nirupamav** [comment]
**_Verified that the issue is resolved as part of #908_**

![image](https://user-images.githubusercontent.com/60865903/80184754-caf3a380-8628-11ea-9f6c-f7fa573a6518.png)

![image](https://user-images.githubusercontent.com/60865903/80184804-e363be00-8628-11ea-9284-5ea52c84e9b3.png)

![image](https://user-images.githubusercontent.com/60865903/80184980-35a4df00-8629-11ea-8aaf-d4a560846cfe.png)

**Comment by amolsontakke3576** [comment]
@dealako  Verified and working fine now.

**Comment by dealako** [comment]
The old v1 console is deprecated and removed.
