### ISSUE TITLE
Project Name, Project Entity and Project Manager email address provided while generating pdf's are not displayed in the generated templates

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#775]
## Background
1. Launch Project Management Console
2. Login as Project Manager
3. Click on the Foundation for e.g. **CloudFoundry.org Foundation, Inc.**
4. Click on SELECT TEMPLATE for project which has both ccla and icla enabled. For e.g. **Issue719TestEdit**
5. Click on APACHE STYLE
6. Enter Project name, Project Entity and Project Email Address
7. Click on Generate PDFS
8. Click Done
9. Click on PDF icon for Corporate CLA 
10. Click on PDF from history popup to download the template
11. **Observed that Project Name, Project Entity and Project Manager email address provided while generating templates are not displayed in the downloaded template. Issue observed for ICLA template as well**
![image](https://user-images.githubusercontent.com/60865903/77909324-c991be00-72aa-11ea-8fa6-f0ec3fd5c6fd.png)

**Comment by dealako** [comment]
@hnexokonkwo is this a regression?

**Comment by hnexokonkwo** [comment]
Hello @dealako, this is a regression. I have debugged and found the issue. I am currently fixing it and will push soon

**Comment by nirupamav** [comment]
**Verified and observed that the issue is fixed**
![image](https://user-images.githubusercontent.com/60865903/79553116-a09a6700-80b9-11ea-8193-dd71942f2d45.png)

![image](https://user-images.githubusercontent.com/60865903/79553215-c6277080-80b9-11ea-9db9-b71b4e3f724a.png)

**Comment by amolsontakke3576** [comment]
@dealako Verified and working fine now.

**Comment by dealako** [comment]
The old v1 console is deprecated and removed.
