### ISSUE TITLE
Observed that the link on EasyCLA logo in github for failed checks redirects the developer to installation of EasyCLA app

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#777]
## Background
**Pre-req**

1. CLA project should be created with ICLA enabled
2. Github repository should be added to the CLA Project

**Steps To Follow**

1. Launch github and login as developer
2. Navigate the repository
3. Edit some file and create PR
4. CLA checks fails
5. **_Observed that mouser pointer is dsiplayed on the EasyCLA logo in All Checks Failed section_**
![image](https://user-images.githubusercontent.com/60865903/77909890-bdf2c700-72ab-11ea-8034-c21e9d15a52d.png)

6. **_When developer clicks on the logo, he/she is redirected to EasyCLA App Installation page._** 
![image](https://user-images.githubusercontent.com/60865903/77909997-f397b000-72ab-11ea-8bdd-4412ab9ba43c.png)

![image](https://user-images.githubusercontent.com/60865903/77910019-ff837200-72ab-11ea-8c73-cd8204955797.png)

**Comment by dealako** [comment]
@amolsontakke3576 can you work with @wanyaland on this? I think we simply need to decide and update the GitHub status message/body/html text that we send into GH for our link back to our product.  Review and ask @pranab-bajpai on where it should go.

**Comment by amolsontakke3576** [comment]
@dealako Sure I will check and update you

**Comment by wanyaland** [comment]
@deelako .. @amolsontakke3576 and I reviewed this issue and found out this is just a public link for a github application which even isnt editable for one who could have access to the App settings. It only changes by app name change . Its not a part of the comment/status on the PR

**Comment by dealako** [comment]
This link is a hard-coded link provided by the GitHub API. We are unable to change the link.

Closing issue.
