### ISSUE TITLE
Corporate Console - The email content in the notification emails is not formatted when CLA Manager request access for another company

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#779]
## Background

1. Launch Corporate Console
2. Login as CLA Manager
3. Click Get Started
4. Search for a company to join the company
5. Select the Company
6. Click JOIN COMPANY
7. Notification email is sent to the CLA Manager of the company

**_Issue1_**
8. Observed that email content is displayed as paragraph. Content should be displayed in proper format

![image](https://user-images.githubusercontent.com/60865903/78012188-403dc280-7362-11ea-9093-a862db4bbf23.png)

**_Issues2_**
9. Company name and user name cannot be differentiated and identified in the email
![image](https://user-images.githubusercontent.com/60865903/78018290-3e2c3180-736b-11ea-865d-477be43f0de9.png)

**_Issue3_**
10. Login to Corporate Console as CLA Manager to accept the request to join the company
11. Click on the Company which has CLA Manager request
12. Click Accept
13. The content in the email notification is not formatted
![image](https://user-images.githubusercontent.com/60865903/78014517-ac6df580-7365-11ea-95b0-b6652e415950.png)

**_Issue4_**
The Content in the email notification when CLA Manager Request is rejected is not formatted
![image](https://user-images.githubusercontent.com/60865903/79544535-c9682f80-80ac-11ea-868a-e576f0ac0c9c.png)

![image](https://user-images.githubusercontent.com/60865903/79544915-64610980-80ad-11ea-870e-737173c5c4c1.png)

**Comment by dealako** [comment]
This issue is resolved by v2. Closing ticket.
