### ISSUE TITLE
Email notification is not sent when CLA Manager request is rejected

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#780]
## Background

1. Launch Corporate Console
2. Login as CLA Manager
3. Click Get Started
4. Search for a company to join the company
5. Select the Company
6. Click JOIN COMPANY
7. Notification email is sent to the CLA Manager of the company
8. Login to Corporate Console as CLA Manager to accept the request to join the company
9. Click on the Company which has CLA Manager request
10. Click Reject
11. **_Observed that email notification about rejection is not sent to the CLA Manager who requested to join the company_**
![image](https://user-images.githubusercontent.com/60865903/78017748-61a2ac80-736a-11ea-86c8-cd5f05b15249.png)

**Comment by dealako** [comment]
@wanyaland we send an email when the CLA Manager is accepted, but not rejected. Can you help me review the backend, diagnose, and add logic to send the email upon rejection?

//CC @WillsonHG cause you brought this up today

**Comment by nirupamav** [comment]
**Verified and observed that email is sent when CLA Manager request is rejected**
![image](https://user-images.githubusercontent.com/60865903/79544535-c9682f80-80ac-11ea-868a-e576f0ac0c9c.png)


![image](https://user-images.githubusercontent.com/60865903/79544915-64610980-80ad-11ea-870e-737173c5c4c1.png)
