### ISSUE TITLE
No action performed when CLA Manager clicks on REQUEST ACCESS for the project

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#782]
## Background

1. Launch Corporate Console
2. Login as CLA Manager **_nirupamav_**
3. Click Get Started
4. Search for a company **_Issue327Comp40_**  to join the company
5. Select the Company
6. Click JOIN COMPANY
7. Notification email is sent to the CLA Manager **_nirupamav mentee1_** of the company **_Issue327Comp40_**
8. Login to Corporate Console as CLA Manager **_nirupamav mentee1_**
9. Click on the company **_Issue327Comp40_**
9. Accept the Request to join the company as CLA Manager
10. Login to corporate console as CLA Manager **_nirupamav_**
11. Click on the company **_Issue327Comp40_**
12. Click on the REQUEST ACCESS to request for CLA Manager privileges for the project
![image](https://user-images.githubusercontent.com/60865903/78020019-49349100-736e-11ea-9589-6d169d85e4bf.png)

13. **_Observed that no action is performed_**

**Comment by amolsontakke3576** [comment]
@dealako @nirupamav I have checked code and there is no method available for `Request Access` can you please explain workflow you want for this functionality ?

**Comment by nirupamav** [comment]
Tested and observed that no action is performed when clicked on REQUEST ACCESS for the project

**Comment by nirupamav** [comment]
Since the issue is fixed now moving the ticket to Review Complete
