### ISSUE TITLE
Project Console - IE EDGE - CORS error while loading github organizations

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#787]
## Background
1. Launch https://project.dev.lfcla.com in IE Edge
2. Login as Project Manager
3. Click on **Academy Software Foundation** 
4. Observed CORS error in console and UI hangs with spinning icon in Github Organizations section
**_NOTE: Issue observed only in IE and this is working fine in FF and Chrome_**

![image](https://user-images.githubusercontent.com/60865903/78101038-e1308a00-7403-11ea-8b08-0a3e1bfbb56b.png)

![image](https://user-images.githubusercontent.com/60865903/78101057-eee60f80-7403-11ea-9dd2-e16410da12ea.png)

**Comment by dealako** [comment]
@hnexokonkwo Why edge only? Can you help diagnose the issue?

**Comment by nirupamav** [comment]
**Verified and observed that CORS is not displayed and github organizations are loaded as expected in windows 10 IE/FF/Chrome**

**Comment by dealako** [comment]
The old v1 console is deprecated and removed.
