### ISSUE TITLE
Project Console - Github organizations are not displayed in any particular sort order

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#788]
## Background

1. Launch https://project.dev.lfcla.com
2. Login as Project Manager
3. Click on Academy Software Foundation
4. Data in Github Organization section are not sorted in any particular order
![image](https://user-images.githubusercontent.com/60865903/78101423-1a1d2e80-7405-11ea-9bdb-13844b59c881.png)

**Comment by nirupamav** [comment]
**Verified that github organizations are sorted in alphabetical order**
![image](https://user-images.githubusercontent.com/60865903/79552930-5b763500-80b9-11ea-8d33-35455ef19a30.png)

**Comment by amolsontakke3576** [comment]
@dealako Verified and working fine now.

**Comment by dealako** [comment]
The old v1 console is deprecated and removed.
