### ISSUE TITLE
Project Console - UI issues in View Companies and View Signatures when Project name and Company name is too long

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#789]
## Background
**Prerequisite**

1. Project having long name should exist
2. Company having long name should exist and should have signed CLA for the project with long name

**Steps to follow**
1. Launch https://project.dev.lfcla.com
2. Login as Project Manager
3. Click on **CloudFoundry.org Foundation, Inc.** 

**_Issue1_**
4. Click on **VIEW COMPANIES** for project **Issue741TestIssue741TestIssue741TestIssue741TestIssue741TestIssue741TestIssue741TestIssue741TestIssue741TestIssue741TestIssue741TestIssue741TestMoreth**
5. Observed that project name overlaps on CLOSE button
![image](https://user-images.githubusercontent.com/60865903/78102148-3752fc80-7407-11ea-864b-c3b695debb94.png)

**_Issue2_**
6. Click on **VIEW SIGNATURES** for project **Issue741TestIssue741TestIssue741TestIssue741TestIssue741TestIssue741TestIssue741TestIssue741TestIssue741TestIssue741TestIssue741TestIssue741TestMoreth**
7. Observed that project name overlaps on CLOSE button
![image](https://user-images.githubusercontent.com/60865903/78102355-c233f700-7407-11ea-83d2-cd8e5993d83e.png)

**_Issue3_**
8. Columns headers are not aligned properly in VIEW SIGNATURES
**NOTE: This alignment issue is not seen when browser zoom level is below 90%**
![image](https://user-images.githubusercontent.com/60865903/78102280-9b75c080-7407-11ea-8cd0-b9fea69bf609.png)

**Comment by dealako** [comment]
@hnexokonkwo can you review/diagnose/resolve?

**Comment by amolsontakke3576** [comment]
@dealako Verified and working fine.
![Screenshot from 2020-12-02 16-44-36.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/813de3cf-2484-4a78-98ed-98be668f47f9)

**Comment by dealako** [comment]
The old v1 console is deprecated and removed.
