### ISSUE TITLE
Corporate Console - Most of the times Join Company request does not work

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#790]
## Background
1. Launch https://corporate.dev.lfcla.com
2. Login as **nirupamavmentee1**
3. Click Get Started
4. Search and Select company **OnlyCCLACompany**
5. Click JOIN COMPANY
6. Notification sent message is displayed and put action was successful in network tab
![image](https://user-images.githubusercontent.com/60865903/78103502-c44b8500-740a-11ea-9509-8f734fa34c95.png)

![image](https://user-images.githubusercontent.com/60865903/78103519-cca3c000-740a-11ea-97b2-7ff047efd850.png)

7. **Email was not sent to the CLA Manager of the company _OnlyCCLACompany_**
8. Login as **nirupamavmentee2** (CLA Manager for company **OnlyCCLACompany**) in Corporate Console
9. Click on company OnlyCCLACompany
10. Observed that CLA Manager request from nirupamavmentee1 is not displayed

![image](https://user-images.githubusercontent.com/60865903/78103676-25735880-740b-11ea-9e80-ed496da8f4ca.png)

![image](https://user-images.githubusercontent.com/60865903/78103753-50f64300-740b-11ea-99ba-d716f32e133e.png)

**Comment by dealako** [comment]
@amolsontakke3576 sorry, we discussed in standup, but I forget the details. What's the status of this ticket? I thought I heard it was ready for review.

**Comment by amolsontakke3576** [comment]
Yes it is ready for review.

**Comment by nirupamav** [comment]
**Observed that Join Company flow is working as expected**

**_Join Company Request_**
![image](https://user-images.githubusercontent.com/60865903/78863584-993ee200-7a57-11ea-8755-125a4dd5e71e.png)

**_Request To Join Pending info_**
![image](https://user-images.githubusercontent.com/60865903/78863606-a3f97700-7a57-11ea-83fe-6e123e9178ae.png)

**_Email Sent to CLA Manager about the Join request_**
![image](https://user-images.githubusercontent.com/60865903/78864062-8082fc00-7a58-11ea-8972-873d59be56b8.png)

**_Pending CLA Manager request displayed for CLA Manager_**
![image](https://user-images.githubusercontent.com/60865903/78864086-8ed11800-7a58-11ea-8ef8-32dbdf604f62.png)

**_After accepting Pending CLA Manager request_**
![image](https://user-images.githubusercontent.com/60865903/78864172-bfb14d00-7a58-11ea-9f0b-390a5c6fa910.png)

**_After request accepted Request To Join Pending info is removed for the CLA Manager who requested to join _**
![image](https://user-images.githubusercontent.com/60865903/78864130-a8725f80-7a58-11ea-96f7-5139b5be0aa8.png)

![image](https://user-images.githubusercontent.com/60865903/78864209-cf309600-7a58-11ea-815d-181b39741286.png)
