### ISSUE TITLE
Corporate Console - User has to revisit or refresh the page to view the added CLA Manager

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#791]
## Background
1. Launch Corporate Console
2. Login as nirupamavmentee1
3. Click on Company **Issue327Comp40**
4. Click on Manage Whitelist for project 
5. Click on + icon under CLA Manager section to Add CLA Manager 
6. Enter LFID for e.g nirupamav and Click SAVE
7. Observed the added CLA Manager is not displayed
![image](https://user-images.githubusercontent.com/60865903/78105538-0676c580-740f-11ea-8017-bc4252dd1c35.png)

![image](https://user-images.githubusercontent.com/60865903/78105555-0f679700-740f-11ea-82e3-b5ba4210cc5b.png)

![image](https://user-images.githubusercontent.com/60865903/78105565-17273b80-740f-11ea-9917-297b6be7aa39.png)

8. **_Refresh the page or navigate back to All Companies and revisit the page and observed that the added CLA Manager is displayed_**
![image](https://user-images.githubusercontent.com/60865903/78106177-7cc7f780-7410-11ea-9cc4-22c63f695f32.png)

**Comment by dealako** [comment]
@amolsontakke3576 please review and diagnose - add refresh/reload of data?

**Comment by nirupamav** [comment]
**Verified and observed that the issue is resolved**
