### ISSUE TITLE
Corporate Console - Email notification is not sent to notify the user when the user is added or deleted as CLA Manager to the project

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#792]
## Background
1. Launch Corporate Console
2. Login as nirupamavmentee1
3. Click on Company **Issue327Comp202**
4. Click on Manage Whitelist for project 
5. Click on + icon under CLA Manager section to Add CLA Manager 
6. Enter LFID for e.g **nirupamav** and Click SAVE
![image](https://user-images.githubusercontent.com/60865903/78108927-e8609380-7415-11ea-9abc-2c43aa9e2a51.png)

7. Refresh the page and observed that the added CLA Manager is displayed
![image](https://user-images.githubusercontent.com/60865903/78109059-23fb5d80-7416-11ea-8245-5f6b28d72ba9.png)

8. **Observed that notification is not sent to the added CLA Manager _nirupamav_
However company is displayed for nirupamav in Corporate console**
![image](https://user-images.githubusercontent.com/60865903/78109176-5e64fa80-7416-11ea-8204-4a865ad8ee09.png)

**Comment by dealako** [comment]
@wanyaland let's send an email for this as well.

//CC @WillsonHG @pranab-bajpai - good use-case for us to send an email notification?

**Comment by dealako** [comment]
@wanyaland - please add logic to send email for both add and remove of users from the CLA Manager list.

@pranab-bajpai, @WillsonHG and the legal team will add notes on what the text should be.

**Comment by nirupamav** [comment]
**Tested and observed that email is not sent when CLA Manager is added/deleted and below are the issues observed in network tab**
![image](https://user-images.githubusercontent.com/60865903/79828484-68976a80-83be-11ea-85da-b38fd74dd244.png)

![image](https://user-images.githubusercontent.com/60865903/79828560-8fee3780-83be-11ea-928e-a8eccc08ae17.png)

**Comment by wanyaland** [comment]
Verified add and delete cla manager emails getting sent

**Comment by dealako** [comment]
The old v1 console is deprecated and removed.
