### ISSUE TITLE
Corporate Console - Back to project signatures link is removed and menu is displayed when the Manage Whitelist page is refreshed

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#793]
## Background
1. Launch https://corporate.dev.lfcla.com
2. Login as nirupamav
3. Click on Company **Issue327Comp40** 
4. Click on Manage Whitelist for project **Issue666CCLA_ICLA**
![image](https://user-images.githubusercontent.com/60865903/78110721-1dbab080-7419-11ea-83b0-aaff805c11fe.png)
5. Refresh page
6. Observed that back icon is removed and menu option is displayed
![image](https://user-images.githubusercontent.com/60865903/78110866-5a86a780-7419-11ea-9c99-c07cacecb404.png)

**Comment by dealako** [comment]
@amolsontakke3576 please review.

**Comment by nirupamav** [comment]
**_Verified and observed that the issue is fixed_**

**Before Refresh**
![image](https://user-images.githubusercontent.com/60865903/78642412-54d50a00-78d0-11ea-9f3f-d6760e866c63.png)

**After Refresh**
![image](https://user-images.githubusercontent.com/60865903/78642471-6ae2ca80-78d0-11ea-9e79-4dbfd292b4d6.png)
