### ISSUE TITLE
API - GH Org/Repos - Audit Log

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#804]
## Summary

Added audit log event entries for PMC GH Org/Repo Add/Delete.

## Background

Add audit log entries for the following:

- [x] GH Org API - AddGithubOrganization
- [x] GH Org API - DeleteGithubOrganization

## User Story

As a project manager, I want to record when GH Orgs/Repos are added or removed.

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

- [GH Repo Add/Delete](https://github.com/communitybridge/easycla/blob/master/cla-backend-go/github_organizations/repository.go#L33-L34)

**Comment by nirupamav** [comment]
**Verified and observed that only deletion even is added to cla-dev-events table and hence reopening the ticket
Tried with 2 organizations. Connect Org and Install the Easy CLA app for the org**
![image](https://user-images.githubusercontent.com/60865903/79222227-cf73cb80-7e74-11ea-8c7c-838a6de41fbf.png)

**Comment by prasannamahajan** [comment]
UI should use /v3 endpoint instead of /v1

**Comment by amolsontakke3576** [comment]
@prasannamahajan can you please provide more detail about endpoint?

**Comment by rinkeshbhutwala** [comment]
@amolsontakke3576 Looks like while click on select Project the JS issue is not allowed to further test on it.

**Comment by rinkeshbhutwala** [comment]
@nirupamav I have verified this ticket and Audit Logs are coming properly.

![Screenshot from 2020-10-15 16-43-16.png](https://images.zenhubusercontent.com/5f20ee93f9a45844ef8dfce5/4f060a62-739d-4dd3-9e0c-301ead778cc1)

**Comment by nirupamav** [comment]
Tested an observed below issues
**_V2_**
**Issue1 : When Branch Protection is enabled, event tdata is updated as auto-enable true and vice versa. auto-enable is for auto enabling repositories and not for enabling branch protection**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/354c8008-d6c5-4fe1-bf76-9069ad86a8cc)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/253dd194-e554-453d-ad69-bf49af716eae)

**Issue2 - Event summary says github deleted when github has been updated by auto enabling new repo and enabling branch protection. Also same is recorded when the options are disabled. instaed of github deleted it should be github updated**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/e8102d59-abc7-4104-8a22-b84ff6476e8e)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a21bb8c4-3191-4eda-bc5e-07327ea789da)

**Issue3 - Events are not logged when repositories are disabled. Only added event is logged but deleted event is not logged**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/140c1d10-e5ec-43ca-ab1a-5e5b21fc7842)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/da4dbbee-a18d-482c-9673-21099e70a3b3)'

**Issue4 - Events are not logged for disabled repositories when github org is deleted. Only github delete event is logged**

**_V1_**
**Issue5 - Events are not logged for disabled repositories when github org is deleted. Only github delete event is logged**

**_Below events are logged as expected for V2_**
1. Add github org
2. Enable repos
3. Disable repos
4. Auto Enable New Repositories
5. Delete github org

**_Below events are logged as expected for V1_**
1. Add github org
2. Enable repos
3. Disable repos
4. Delete github org

**Comment by vinod-kadam** [comment]
Marked it as v1 since the ticket seems very old one.

**Comment by dealako** [comment]
Merged updates to master for adding event logs when branch protection is updated. All other events are accounted for.
