### ISSUE TITLE
Employee who has requested for whitelist is displayed in Pending Whitelists for all clamanagers even if request was sent to only 1 cla manager

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#806]
## Background

**Prerequisite**
1. Project **ProjectWithOnlyCCLAEnabled** with ccla enabled should exist
2. Company **3clamanagercomp** should exist and should have signed cla
3. CLA Manager nirupamav+mentee1@proximabiz.com and nirupamav+mentee2@proximabiz.com should exist for the project

![image](https://user-images.githubusercontent.com/60865903/78231548-980a3400-74f0-11ea-8675-2ddbe7cc2584.png)
4. Employee should not be whitelisted for the project

**Steps to follow**

1. Launch github repository url https://github.com/selenium-af/prod
2. Login as github user
3. Update any file and Pull Request
4. Checks fail
5. Click on the link to Sign CLA
6. Click on Corporate
7. Select Company **3clamanagercomp**
8. Click Contact
9. Popup to select CLA Manager's email Id is displayed
10. Select Email ID nirupamav+mentee2@proximabiz.com and enter other required details
![image](https://user-images.githubusercontent.com/60865903/78231866-123ab880-74f1-11ea-96b3-3e2c8657f8d0.png)
10. Click SEND button
11. Launch Corporate Console
12. Login as nirupamav+mentee2@proximabiz.com 
13. Click on company **3clamanagercomp**
14. Click MANAGE WHITELIST for project 
15. Observed the employee pending request is displayed which is as expected
![image](https://user-images.githubusercontent.com/60865903/78232220-8e350080-74f1-11ea-8624-29fa90f345d5.png)

16. Login to Corporate Console as nirupamav+mentee1@proximabiz.com 
17. Click on company **3clamanagercomp**
18. Click MANAGE WHITELIST for project 
19. Observed the employee pending request is displayed even if the cla manager was not selected by employee
![image](https://user-images.githubusercontent.com/60865903/78232347-bb81ae80-74f1-11ea-9e9e-35e2fb3b3be6.png)

**Comment by dealako** [comment]
@wanyaland Please review and diagnose.

**Comment by dealako** [comment]
The request should be seen by all CLA managers for that project/company. Any of the CLA managers can process (approve/deny) the request.
