### ISSUE TITLE
Employee is not redirected to github after the Corporate workflow in Contributor Console

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#808]
## Background

1. Launch github repository url https://github.com/selenium-af/Issue719
2. Login as github user
3. Update any file and Pull Request
4. Checks fail
5. Click on the link to Sign CLA
6. Click on Corporate
7. Select Company CompSignAfterEmployeeRequest
8. Popup to request authorization is displayed
9. Select employee Email ID
10. Click SEND button and click DISMISS
11. Observed the UI with popup to select Company is displayed and user is not redirected to github
**NOTE: User is not redirected to github after any of the workflow related to Corporate**
![image](https://user-images.githubusercontent.com/60865903/78236549-c3445180-74f7-11ea-9169-abd0bae0a37f.png)

![image](https://user-images.githubusercontent.com/60865903/78236590-d2c39a80-74f7-11ea-8a02-a86644b8073d.png)

**Comment by dealako** [comment]
@hnexokonkwo please work with @nirupamav to test/evaluate/resolve this issue.

**Comment by dealako** [comment]
The old console is deprecated and removed.
