### ISSUE TITLE
User is able to delete the Project when it is signed by the company and after deletion in Corporate Console a row without project name exists

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#816]
## Background

**Prerequisite**
1. CLA project should be created with CCLA enabled
2. Github repository should be added to the CLA Project
3. Company should exist and Company should have signed CLA for the project
4. After the company has signed the CLA, Delete the EasyCLA app in github
5. Delete the Github organization in project console
6. Delete the project

**Steps to follow**
1. Login to Corporate Console as nirupamamentee2
2. Click on the Company DeleteGithubAndProjTestComp
**_Issue1_**
3. Observed a row without project name is displayed
![image](https://user-images.githubusercontent.com/60865903/78368698-a3895800-75e1-11ea-9759-85de599191ac.png)
4. Click Manage Whitelist

**_Issue2_**
5. Observed Page hang with spinning icon in CLA Managers section with error in console
![image](https://user-images.githubusercontent.com/60865903/78368818-d895aa80-75e1-11ea-9de2-96ecef3663f3.png)

![image](https://user-images.githubusercontent.com/60865903/78368798-d16e9c80-75e1-11ea-8cb9-71340efad261.png)

**_Issue3_**
7. Click Back link to navigate backed to Signed CLA's
8. Click View Managers
9. Observed no action is performed and below error is displayed in console
![image](https://user-images.githubusercontent.com/60865903/78369035-34f8ca00-75e2-11ea-8354-1041c9410586.png)

**Comment by dealako** [comment]
@wanyaland please review. If we add delete for a CLA Group/Project, we will need to:

- Warn user (ask UI team to add confirmation modal and indicate
- Remove all signatures for the CLA group/project in the signatures table
- Deregister/Unassign/Release repo from the CLA Group (search gerrit and GH tables)
- Remove all company invites for the CLA group/project
- Search users - remove CLA Group/project ID reference/column value from user table entries
- Remove CLA Group/Project table entry

**Comment by dealako** [comment]
@wanyaland yes, no action for users table. For signature table updates, we will need to:

- query all signatures for the project id - then toggle the signature_approved flag to false, also, add/append text to the `notes` column to say that: "Signature disabled due to CLA Group/Project {CLA Group/Project Name} being deleted."

Ask me if you need help.

Delete API -> service layer (perhaps), do the CLA Grop delete, signature update, remove invites...

**Comment by nirupamav** [comment]
**_Before Deletion of project_**
![image](https://user-images.githubusercontent.com/60865903/79216201-6a1add00-7e6a-11ea-9410-f6b2a64df1e9.png)

![image](https://user-images.githubusercontent.com/60865903/79216247-7c951680-7e6a-11ea-88c6-dd39d8fe7708.png)

![image](https://user-images.githubusercontent.com/60865903/79216275-86b71500-7e6a-11ea-9497-bafc804a685e.png)

**Activitylogtest Company**
![image](https://user-images.githubusercontent.com/60865903/79216309-959dc780-7e6a-11ea-8963-f1d4ac84b20d.png)

**MetricsTestComp company**
![image](https://user-images.githubusercontent.com/60865903/79216384-b0703c00-7e6a-11ea-89cf-47a8f348e9a1.png)

**_Deletion of project_**
![image](https://user-images.githubusercontent.com/60865903/79216499-e9a8ac00-7e6a-11ea-9ac5-682a2bcf38c3.png)

![image](https://user-images.githubusercontent.com/60865903/79216544-f9c08b80-7e6a-11ea-854f-1e43bd5eae68.png)

![image](https://user-images.githubusercontent.com/60865903/79216568-0644e400-7e6b-11ea-863e-dbda568e8dfd.png)

**_After deletion of Project_**
**Deleted project is not visible for all companies**
![image](https://user-images.githubusercontent.com/60865903/79217035-c6323100-7e6b-11ea-8c0d-cfab1fe6b211.png)

![image](https://user-images.githubusercontent.com/60865903/79217089-dea24b80-7e6b-11ea-9ea9-c28c6beb8f91.png)

**Comment by nirupamav** [comment]
**_After deletion of Project observed below issues and hence reopening the ticket. For reference, have commented above with the screenshots before delete and passed scenarios after deletion_**

**All signatures are not deleted from database and hence it might impact metrics**
![image](https://user-images.githubusercontent.com/60865903/79216849-7d7a7800-7e6b-11ea-94fd-f7f792f7104f.png)

**Comment by wanyaland** [comment]
@nirupamav based on discussions it was decided that the records shouldnt be deleted but signature_approved flag set to false and note attribute added. So these are the check points

**Comment by nirupamav** [comment]
@wanyaland 
Ok. I will perform regression testing for metrics and if there are any issues will log different ticket.
Moving the ticket to Review Complete as the flow is working as expected
