### ISSUE TITLE
Corporate Console - Free text is accepted while adding CLA Manager for a project in Manage Whitelist

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#818]
## Background
1. Launch Corporate Console and login as nirupamavmentee1
2. Click on Company Issue327Comp123
3. Click on Manage Whitelist for any project
4. Click on + icon under CLA Manager section to Add CLA Manager
5. Observed that user can enter any free text and save the data
![image](https://user-images.githubusercontent.com/60865903/78524705-56c89b80-77f2-11ea-9f79-ea2377567efd.png)

**Comment by dealako** [comment]
@hnexokonkwo can you review/diagnose/resolve?

**Comment by nirupamav** [comment]
**Observed that not able to add CLA Manager. When clicked on + icon error is displayed in console and no action is performed in UI**
![image](https://user-images.githubusercontent.com/60865903/79549128-2b786300-80b4-11ea-9df9-4a7b9b1df3e0.png)

@hnexokonkwo 
**Also could you please what is the fix like what characters are accepted so that I can test accordingly**

**Comment by nirupamav** [comment]
Able to add CLA Manager now and hence moving the ticket to Ready for review to proceed with testing

**Comment by amolsontakke3576** [comment]
@dealako Verified and now restrict the user to enter invalid characters.
![Screenshot from 2020-12-03 12-22-10.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/9d64cc0d-5d4f-42ab-9e39-55f7b0748250)

**Comment by dealako** [comment]
The old console is deprecated and removed.
