### ISSUE TITLE
(V2) cla-manager-distribution API Endpoint: CLA Manager who has not signed into the EascyCLA application is included in the count of CLA Managers

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#819]
## Background

1. Fetch the response from https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/metrics/cla-manager-distribution
Note the counts
2. Launch Corporate Console
3. Login as **nirupamavmentee3**
4. Click on Company **NotSignedInCLAManagerCompTest**
5. Click on Manage Whitelist for project
6. Click on + icon under CLA Manager section to Add CLA Manager
7. Enter LFID for e.g **nirupamavmentee100** and Click SAVE
8. CLA Manager is added to the project but status of the user is shown as not signed in
9. If required execute the cron job to fetch the latest count
10. Fetch the response from https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/metrics/cla-manager-distribution

**_Before Adding CLA Manager_**
![image](https://user-images.githubusercontent.com/60865903/78526114-a4470780-77f6-11ea-9063-dd5ce1b4319d.png)
{
    "createdAt": "2020-04-06T05:25:56Z",
    "fourOrMoreClaManagers": 51,
    "oneClaManager": 360,
    **"threeClaManagers": 88,**
    **"twoClaManagers": 178**
}

**_Before Adding CLA Manager who has not signed in_**
![image](https://user-images.githubusercontent.com/60865903/78526178-d2c4e280-77f6-11ea-9ab9-b1fa762342c3.png)

{
    "createdAt": "2020-04-06T05:27:50Z",
    "fourOrMoreClaManagers": 51,
    "oneClaManager": 360,
    **"threeClaManagers": 89,**
    **"twoClaManagers": 177**
}

## Expected Behaviour
CLA Manager who has not signed in should be included in the CLA Manager counts. 
After the CLA Manager sign into the EascyCLA app, the count should be included in the CLA Manager counts

**Comment by prasannamahajan** [comment]
Pull Request: https://github.com/communitybridge/easycla/pull/888

**Comment by nirupamav** [comment]
Verified and observed that the issue is fixed in both **cla-manager-distribution** and **total-count** endpoints

**Comment by dealako** [comment]
The old v1 console is deprecated and removed.
