### ISSUE TITLE
(V2) events/recent API Endpoint: Activities of Companies are fetched in the api response

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#821]
## Background
1. In Postman run the below API
**_API URL_**  https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/events/recent
**_Http Method_** GET
**_Header_** Authorization/[user token]

2. **Observed that recent activities of companies are fetched. But the endpoint should fetch recent activities of project**
![image](https://user-images.githubusercontent.com/60865903/78531089-6cde5800-7802-11ea-94aa-2c5568e777c3.png)

**Comment by dealako** [comment]
@prasannamahajan can you review/diagnose?

**Comment by nirupamav** [comment]
**Verified and observed that the issue is fixed**
- Added a new company
- Triggered Lambda function to get latest metrics
- Trigger the API https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/events/recent
- Observed that Create Company event was not fetched in the response

![image](https://user-images.githubusercontent.com/60865903/79191022-47c19900-7e43-11ea-82b4-87c097183eb2.png)

**Comment by prasannamahajan** [comment]
This api endpoint is not used anymore
We should remove it
