### ISSUE TITLE
Contributor Console - Individual Contribution for Corporate - Footer is displayed on the top of the page and overlaps on the logo

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#823]
## Background
**Prerequisite**
1. Valid Project should exists and should be ccla enabled
2. Valid Company should exist and should have signed the project
3. Contributor email should have been whitelisted for the Project

**Steps to follow**
1. Launch the github repository https://github.com/vdproject
2. Login as contributor
3. Update any file and create PR
4. Checks fail
5. Click on the link to sign CLA
6. Contributor is redirected to contributor console
7. Click on Corporate 
8. Observed that Footer is displayed on the top of the page and overlaps on the logo

![image](https://user-images.githubusercontent.com/60865903/78545014-b0dc5780-7818-11ea-927e-6b1ce25d9aaf.png)

**Comment by nirupamav** [comment]
**Verified that the issue is fixed**

**Comment by dealako** [comment]
Verified.

**Comment by nirupamav** [comment]
@WillsonHG @dealako 
Verified that the issue is fixed in Staging as well
![image](https://user-images.githubusercontent.com/60865903/79588480-9c8a3b80-80f1-11ea-9ad2-fbf071fe3f80.png)
