### ISSUE TITLE
Corporate Console - EasyCLA whitelist modified Email - Issues with the email content and whitelist needs to updated to Approved List

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#825]
## Background
**_<Niru 24-Apr-2020> Also as per latest changes whitelist needs to updated to Approved List_**
1. Launch Corporate Console
2. Login as nirupamavmentee2
3. Click on company **NotSignedInCLAManagerCompTest**
4. Click on Manage whitelist for project **ProjectActivityLogTest**
5. Add email nirupamav+pinky@proximabiz.com for Email Whitelist
![image](https://user-images.githubusercontent.com/60865903/78545425-65767900-7819-11ea-8233-06e4eaa17d29.png)
6. Email is sent to the employee
7. Observed grammar issues in the email content. Also email has to be formatted
![image](https://user-images.githubusercontent.com/60865903/78546224-b175ed80-781a-11ea-8475-2308b77e6f2a.png)

**Comment by dealako** [comment]
@nirupamav will review in 04/08/2020 stakeholder meeting.

**Comment by nirupamav** [comment]
Observed that email content is updated however it is still not formatted
![image](https://user-images.githubusercontent.com/60865903/82202839-1fd0c400-9920-11ea-810a-eae747b44720.png)

![image](https://user-images.githubusercontent.com/60865903/82202926-3a0aa200-9920-11ea-86ff-781b0935d705.png)

**Comment by wanyaland** [comment]
Verified email is formatted with the right content
[Uploading... Screenshot 2020-12-29 at 16.00.41.png ]

**Comment by dealako** [comment]
The old v1 console is deprecated and removed.
