### ISSUE TITLE
Few the events are not created in cla-dev-events table

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#827]
Observed that most of the events are not created in **cla-dev-events** table. Below are few events that were not logged in the table. 
- Create Project
- Generating templates for the project
- Adding Repositories to the project
- Company Signing the CLA
- Whitelisting Employee
- Whitelisted Employee Contributing for the project by creating PR(not merged)

**NOTE:** When company is created and when CLA Manager is added to Company in Manage Whitelist Page then event is added.

**Comment by dealako** [comment]
@prasannamahajan I think this will resolved with your recent refactor. Please confirm.

**Comment by prasannamahajan** [comment]
@dealako 
Following events will get resolved due to event refactoring. (which are present in v3 backend)
- Create Project
- Generating templates for the project
- Adding Repositories to the project

Need to check for other events

**Comment by dealako** [comment]
@nirupamav I think this is now resolved.

**Comment by nirupamav** [comment]
Verified that the issue is resolved
