### ISSUE TITLE
V2 API - Response message is not returned when token is expired/invalid token is provided/when no authorization header is provided

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#832]
## Background
401 response code is returned but appropriate response message is not returned for all V2 API endpoints when token is expired/invalid token is provided/when no authorization header is provided

**_Example_**
**Token is expired**
![image](https://user-images.githubusercontent.com/60865903/78746738-43016e80-7985-11ea-9ae6-0caeecbd857b.png)

**Invalid Token**
![image](https://user-images.githubusercontent.com/60865903/78746799-73490d00-7985-11ea-9f46-7b96af0e8646.png)

**No Authorization header**
![image](https://user-images.githubusercontent.com/60865903/78746844-878d0a00-7985-11ea-994e-283023eaacd2.png)

**Comment by dealako** [comment]
@prasannamahajan not required, but we could add additional details to the error response message.

**Comment by prasannamahajan** [comment]
@dealako this message should be returned by api-gw. 
If Authorization token is not valid / not provided then cla lambda would not get triggered. right ?

**Comment by dealako** [comment]
@nirupamav this response appears to be generated by the API-GW provided by the platform before it is routed to the EasyCLA application.  This is the default and accepted behavior. The 401 HTTP response is adequate and no more details are required.  Closing this ticket for now.
