### ISSUE TITLE
V2 API (metrics/total-count) - Issues with companiesCount and projectsCount in the response

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#833]
## Background

**Prerequisite**
1. Github organization should be connected 

**Steps to follow**
1. Launch Project Console
2. Login as Project Manager
3. Click on Foundation **CloudFoundry.org Foundation, Inc.** 
4. Click ADD CLA GROUP
5. Enter CLA Group name
6. Check all checboxes
7. Click SAVE
8. Add Github repository to the added cla group
9. Launch Corporate Console
10. Login as CLA Manager
11. Click Get Started
12. Enter new company name
13. Click ADD COMPANY
14. Click on the added company
15. Click SIGN NEW CLA
16. Search and select the above created project
17. Click SUBMIT
18. Click YES
19. Click OPEN CLA
20. Complete the docusign process
21. Execute the lambda function to fetch the latest metrics
22. Trigger below api
**API URL** https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/metrics/total-count
**Header** Authorization/(valid user token)
**Http Method** GET
23. Observed that companiesCount and projectsCount is not incremented in the response
As per discussion with @prasannamahajan, DynamoDB updates the number of items in a table approximately every six hours. If we manually click on Update in dynamoDB, the number of items gets updated. In ui metrics is fetched every one hour and hence the dynamodb issue might impact the metrics

**Comment by prasannamahajan** [comment]
Pull request : https://github.com/communitybridge/easycla/pull/845

**Comment by nirupamav** [comment]
**Verified that the issue is fixed**

**Comment by dealako** [comment]
Resolved - closing ticket.
