### ISSUE TITLE
V2 API (metrics/total-count) - Issues with githubRepositoriesCount and repositoriesCount when few added repos are disabled in github

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#835]
## Background
**Prerequisite**
1. Github Organization should be connected to Easy CLA Appilcation and should be configured for All Repositories
2. Valid project should exist
3. All Repos of the github should be added to the Project
4. Trigger the lambda function to get latest metrics and note down **githubRepositoriesCount** and **repositoriesCount** count
![image](https://user-images.githubusercontent.com/60865903/78773240-8f15d880-79b0-11ea-8238-518d055987eb.png)

![image](https://user-images.githubusercontent.com/60865903/78773526-fd5a9b00-79b0-11ea-9c42-f071710f88d9.png)

**Steps to Follow**
1. Launch github organization
2. Navigate to Settings -> Install Github Apps
3. Click Configure for DEV CommunityBridge: EasyCLA
4. Under Repository Access section click on Only select repositories
5. Select only few repositories for e.g 2 repositories
6. Click Save
![image](https://user-images.githubusercontent.com/60865903/78773423-d56b3780-79b0-11ea-8f96-fd5bdbd49681.png)

![image](https://user-images.githubusercontent.com/60865903/78773609-1c592d00-79b1-11ea-981b-618b0d821efa.png)

**_Though in Configure Github Repositories only 2 repositories are shown which is as expected,  still all repos are shown in Foundation details page for the project_**
![image](https://user-images.githubusercontent.com/60865903/78774115-d05ab800-79b1-11ea-9019-83296a45e526.png)

7. Trigger the Lambda function to fetch latest results
10. Observed count is not decremented for **githubRepositoriesCount** and **repositoriesCount**
![image](https://user-images.githubusercontent.com/60865903/78773909-896cc280-79b1-11ea-91a9-87f96e6cd69e.png)

**Comment by dealako** [comment]
@nirupamav - current behavior is working as expected.  The system detects that the GH repos has been disabled and sends an email to the Project Managers informing of this.  No further action is taken by the EasyCLA system - we are waiting on the PM's to fix/resolve the problem rather than make changes to the database.
