### ISSUE TITLE
V2 API (top-companies and company/{{companyID}}) - Company name is not returned for few records in the response

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#839]
## Background

Observed that for few records company name is not returned in for Endpoints top-companies and company/{{companyID}}. Queried the company ID and observed that company name exist for the records

**Example of the issue**
![image](https://user-images.githubusercontent.com/60865903/78796406-e1b4bc00-79d3-11ea-8592-dd00aa05fe25.png)

![image](https://user-images.githubusercontent.com/60865903/78796438-ed07e780-79d3-11ea-83e2-b8d25d793ec3.png)

![image](https://user-images.githubusercontent.com/60865903/78796511-0b6de300-79d4-11ea-9151-cb91b3a2660c.png)

**Comment by prasannamahajan** [comment]
@dealako fixed it by filling companyName from companies table
https://github.com/communitybridge/easycla/pull/845.
but root cause of issue is signature_reference_name is empty.

**Comment by nirupamav** [comment]
**Verified that the issue is fixed**
{
    "averageCompanyClaManagers": 1,
    "averageCompanyCorporateContributors": 2,
    "averageCompanyProjectCount": 1,
    "topCompaniesByClaManagers": [
        {
            "claManagersCount": 11,
            "companyName": "New Relic",
            "corporateContributorsCount": 10,
            "createdAt": "2020-04-10T10:23:25Z",
            "id": "d938e0a9-9f96-4dbb-a511-74b570fe1c04",
            "projectsCount": 1
        },
        {
            "claManagersCount": 10,
            "companyName": "Virtuozzo",
            "corporateContributorsCount": 2,
            "createdAt": "2020-04-10T10:23:36Z",
            "id": "9f79dacf-d5f4-4df7-9d5e-ef47477493f3",
            "projectsCount": 1
        },
        {
            "claManagersCount": 10,
            "companyName": "Spotify",
            "corporateContributorsCount": 3,
            "createdAt": "2020-04-10T10:23:41Z",
            "id": "d0503125-c52b-438e-943e-ac670352722c",
            "projectsCount": 1
        },
        {
            "claManagersCount": 8,
            "companyName": "Proxima India",
            "corporateContributorsCount": 0,
            "createdAt": "2020-04-10T10:23:47Z",
            "id": "08c1d2e9-7a22-48b8-b8b1-e56cb9a559e0",
            "projectsCount": 9
        },
        {
            "claManagersCount": 8,
            "companyName": "Salesforce",
            "corporateContributorsCount": 17,
            "createdAt": "2020-04-10T10:23:41Z",
            "id": "304e0245-7593-4e0a-a46f-2528dee4fa08",
            "projectsCount": 1
        }
    ],
    "topCompaniesByCorporateContributors": [
        {
            "claManagersCount": 3,
            "companyName": "Red Hat, Inc.",
            "corporateContributorsCount": 254,
            "createdAt": "2020-04-10T10:24:02Z",
            "id": "614190dc-14b1-47a6-a883-2998ed4c1a43",
            "projectsCount": 1
        },
        {
            "claManagersCount": 2,
            "companyName": "IBM",
            "corporateContributorsCount": 92,
            "createdAt": "2020-04-10T10:23:24Z",
            "id": "2840eb93-e4f0-4f5e-b102-ae8eb493de2e",
            "projectsCount": 1
        },
        {
            "claManagersCount": 3,
            "companyName": "VMware Inc",
            "corporateContributorsCount": 86,
            "createdAt": "2020-04-10T10:23:40Z",
            "id": "b42e91fb-1174-4e53-86d8-4b1f4fa06ac2",
            "projectsCount": 1
        },
        {
            "claManagersCount": 1,
            "companyName": "Microsoft",
            "corporateContributorsCount": 57,
            "createdAt": "2020-04-10T10:23:41Z",
            "id": "3f924148-a63f-4105-8167-f67b0e6ec4f9",
            "projectsCount": 1
        },
        {
            "claManagersCount": 5,
            "companyName": "Intel Corporation",
            "corporateContributorsCount": 53,
            "createdAt": "2020-04-10T10:23:35Z",
            "id": "2688cdd6-404e-4a31-a5b4-51e9c81f099d",
            "projectsCount": 1
        }
    ],
    "topCompaniesByProjectCount": [
        {
            "claManagersCount": 8,
            "companyName": "Proxima India",
            "corporateContributorsCount": 0,
            "createdAt": "2020-04-10T10:23:47Z",
            "id": "08c1d2e9-7a22-48b8-b8b1-e56cb9a559e0",
            "projectsCount": 9
        },
        {
            "claManagersCount": 1,
            "companyName": "company_new",
            "corporateContributorsCount": 0,
            "createdAt": "2020-04-10T10:23:47Z",
            "id": "a5b26bbf-3b1e-43ba-b910-22550dab3480",
            "projectsCount": 7
        },
        {
            "claManagersCount": 3,
            "companyName": "Biarca",
            "corporateContributorsCount": 5,
            "createdAt": "2020-04-10T10:23:35Z",
            "id": "2d72016c-7639-459d-9448-ba77da174e47",
            "projectsCount": 6
        },
        {
            "claManagersCount": 1,
            "companyName": "Apr09Comp2",
            "corporateContributorsCount": 0,
            "createdAt": "2020-04-10T10:23:36Z",
            "id": "bdb7a5a1-f4c1-4b5a-90e4-23a1a3591000",
            "projectsCount": 5
        },
        {
            "claManagersCount": 3,
            "companyName": "CompanyCount2",
            "corporateContributorsCount": 1,
            "createdAt": "2020-04-10T10:23:48Z",
            "id": "22566e52-6ff3-4b22-b8b2-dfaad5c93b0d",
            "projectsCount": 5
        }
    ]
}

**Comment by prasannamahajan** [comment]
@nirupamav 
Raised PR : https://github.com/communitybridge/easycla/pull/869
Change : setting signature_reference_name
If signature is of type ccla then it should be company name.
If signature is of type icla/employee signature then it should be user name,

**Comment by nirupamav** [comment]
Verified that the issue is fixed and also verified the CCLA flow and ICLA flow is working as expected

**Comment by wanyaland** [comment]
Verified this is fixed

```
{
    "averageCompanyClaManagers": 1,
    "averageCompanyCorporateContributors": 1,
    "averageCompanyProjectCount": 1,
    "topCompaniesByClaManagers": [
        {
            "claManagersCount": 14,
            "companyName": "Acme Inc",
            "corporateContributorsCount": 2,
            "createdAt": "2020-12-22T14:53:57Z",
            "id": "0aa83c93-5050-4ef1-9fe0-65b7c75fcf9e",
            "projectsCount": 17
        },
        {
            "claManagersCount": 14,
            "companyName": "proxima",
            "corporateContributorsCount": 6,
            "createdAt": "2020-12-22T14:56:41Z",
            "id": "1df614a0-7153-4802-8a08-d7d8fec951f2",
            "projectsCount": 36
        },
        {
            "claManagersCount": 11,
            "companyName": "New Relic, Inc.",
            "corporateContributorsCount": 8,
            "createdAt": "2020-12-22T14:47:00Z",
            "id": "d938e0a9-9f96-4dbb-a511-74b570fe1c04",
            "projectsCount": 1
        },
        {
            "claManagersCount": 11,
            "companyName": "Proxima Systems",
            "corporateContributorsCount": 0,
            "createdAt": "2020-12-22T15:06:44Z",
            "id": "8236f284-f76e-4e32-aa6d-adc44efda053",
            "projectsCount": 31
        },
        {
            "claManagersCount": 10,
            "companyName": "Proxima",
            "corporateContributorsCount": 0,
            "createdAt": "2020-12-22T15:03:47Z",
            "id": "7c737082-4d47-4532-8bab-f97d76618c9d",
            "projectsCount": 19
        }
    ],
    "topCompaniesByCorporateContributors": [
        {
            "claManagersCount": 3,
            "companyName": "Red Hat, Inc.",
            "corporateContributorsCount": 221,
            "createdAt": "2020-12-22T15:31:09Z",
            "id": "614190dc-14b1-47a6-a883-2998ed4c1a43",
            "projectsCount": 1
        },
        {
            "claManagersCount": 2,
            "companyName": "IBM",
            "corporateContributorsCount": 71,
            "createdAt": "2020-12-22T15:36:33Z",
            "id": "2840eb93-e4f0-4f5e-b102-ae8eb493de2e",
            "projectsCount": 1
        },
        {
            "claManagersCount": 3,
            "companyName": "VMware Inc",
            "corporateContributorsCount": 71,
            "createdAt": "2020-12-22T15:11:56Z",
            "id": "b42e91fb-1174-4e53-86d8-4b1f4fa06ac2",
            "projectsCount": 1
        },
        {
            "claManagersCount": 9,
            "companyName": "Intel Corporation",
            "corporateContributorsCount": 47,
            "createdAt": "2020-12-22T15:37:54Z",
            "id": "2688cdd6-404e-4a31-a5b4-51e9c81f099d",
            "projectsCount": 5
        },
        {
            "claManagersCount": 0,
            "companyName": "Microsoft",
            "corporateContributorsCount": 47,
            "createdAt": "2020-12-22T15:32:08Z",
            "id": "3f924148-a63f-4105-8167-f67b0e6ec4f9",
            "projectsCount": 0
        }
    ],
    "topCompaniesByProjectCount": [
        {
            "claManagersCount": 14,
            "companyName": "proxima",
            "corporateContributorsCount": 6,
            "createdAt": "2020-12-22T14:56:41Z",
            "id": "1df614a0-7153-4802-8a08-d7d8fec951f2",
            "projectsCount": 36
        },
        {
            "claManagersCount": 11,
            "companyName": "Proxima Systems",
            "corporateContributorsCount": 0,
            "createdAt": "2020-12-22T15:06:44Z",
            "id": "8236f284-f76e-4e32-aa6d-adc44efda053",
            "projectsCount": 31
        },
        {
            "claManagersCount": 10,
            "companyName": "Proxima",
            "corporateContributorsCount": 0,
            "createdAt": "2020-12-22T15:03:47Z",
            "id": "7c737082-4d47-4532-8bab-f97d76618c9d",
            "projectsCount": 19
        },
        {
            "claManagersCount": 14,
            "companyName": "Acme Inc",
            "corporateContributorsCount": 2,
            "createdAt": "2020-12-22T14:53:57Z",
            "id": "0aa83c93-5050-4ef1-9fe0-65b7c75fcf9e",
            "projectsCount": 17
        },
        {
            "claManagersCount": 9,
            "companyName": "Pinterest",
            "corporateContributorsCount": 1,
            "createdAt": "2020-12-22T14:42:02Z",
            "id": "eb4d7d71-693f-4047-bf8d-10d0e7764969",
            "projectsCount": 13
        }
    ]
}
```
