### ISSUE TITLE
Project Console - Two records one as Employee and other as Individual is displayed in View signature for a corporate contributor

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#849]
## Background

1. Valid Project with CCLA enabled should exist
2. Templates should be generated for the project
3. Github repository should be added for the project
4. Valid company should exist
5. Company should have signed CLA for the project
6. CLA Manager should have whitelisted the employee for the Project

1. Launch Github repository
2. Login as Corporate employee who as been whitelisted for the company
3. Update any file and create PR
4. CLA checks fail
5. Click on CLA NOT SIGNED
6. User is redirected to Contributor Console
7. Click Corporate
8. Select the Company and Submit
9. Click Continue (Sign ICLA docu sign if required else navigate back to repo)
10. Navigate to Project Console
11. Click on Foundation
12. Click on View Signatures for the project
13. Observed there are two entries(Individual and Employee) for the corporate contributor
![image](https://user-images.githubusercontent.com/60865903/78971564-7da40c00-7b29-11ea-878e-43800c88246a.png)

**Comment by nirupamav** [comment]
@prasannamahajan 
Due to this bug in https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/metrics/top-projects
when employee signs CLA from docusign both individualContributorsCount and corporateContributorsCount are incremented

**Comment by dealako** [comment]
I believe this to be the correct behavior.
