### ISSUE TITLE
[Inconsistent Behavior] Sometimes error is displayed in console while performing few actions and when cleared cache it works fine

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#851]
## Background

Observed that sometimes error is displayed in the console while working in the Corporate console and Project Console. I always start testing by clearing the cache. While working on few flows suddenly I see this issue. If clear cache and try again it will work

Below is error was displayed when I refreshed the Corporate Console and tried to click on the Company after the request to join this company was accepted by the CLA Manager of this company. Tried to reproduce this issue but could not
Had observed this issue in project console as well for few actions 
![image](https://user-images.githubusercontent.com/60865903/78974902-9ebc2b00-7b30-11ea-9f39-a99b735e010a.png)

**Comment by amolsontakke3576** [comment]
@dealako I had debug this issue and looks like it is mostly reproducible on Firefox. I had tried on `Contributor Console` and locally it works fine but not on Dev. So issue may be in building process. 
Below is the error 
`ERROR Error: "Uncaught (in promise): TypeError: modules[moduleId] is undefined
__webpack_require__@https://contributor.dev.lfcla.com/build/vendor.js:55:12
webpackAsyncContext/<@https://contributor.dev.lfcla.com/build/main.js:1009:10
F</l</t.prototype.invoke@https://contributor.dev.lfcla.com/build/polyfills.js:3:14976
onInvoke@https://contributor.dev.lfcla.com/build/vendor.js:5293:33
F</l</t.prototype.invoke@https://contributor.dev.lfcla.com/build/polyfills.js:3:14916
F</c</r.prototype.run@https://contributor.dev.lfcla.com/build/polyfills.js:3:10143
f/<@https://contributor.dev.lfcla.com/build/polyfills.js:3:20242
F</l</t.prototype.invokeTask@https://contributor.dev.lfcla.com/build/polyfills.js:3:15660
onInvokeTask@https://contributor.dev.lfcla.com/build/vendor.js:5284:33
F</l</t.prototype.invokeTask@https://contributor.dev.lfcla.com/build/polyfills.js:3:15581
F</c</r.prototype.runTask@https://contributor.dev.lfcla.com/build/polyfills.js:3:10834
o@https://contributor.dev.lfcla.com/build/polyfills.js:3:7894`

**Comment by nirupamav** [comment]
Observed this issue again today when created a company and clicked on the company and then clicked on SIGN NEW CLA
![image](https://user-images.githubusercontent.com/60865903/81162860-7d255680-8fab-11ea-8dd0-dbf1a8b65951.png)

**Comment by amolsontakke3576** [comment]
@dealako  As per the latest changes flow is working fine now
