### ISSUE TITLE
V2 API (top-companies and company/{{companyID}}) API Endpoints: CLA Manager who has not signed into the EascyCLA application is included in the count of CLA Managers

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#854]
## Background

1. Launch Corporate Console
2. Login as nirupamavmentee3
3. Click on Company NotSignedInCLAManagerCompTest
4. Click on Manage Whitelist for project
5. Click on + icon under CLA Manager section to Add CLA Manager
6. Enter LFID for e.g nirupamavmentee101 and Click SAVE
7. CLA Manager is added to the project but status of the user is shown as not signed in
8. If required execute the cron job to fetch the latest count
9. Fetch the response from below endpoints
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/metrics/company/22566e52-6ff3-4b22-b8b2-dfaad5c93b0d
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/metrics/top-companies
10. Observed that not signed in CLA Manager is included in the count of claManagersCount
![image](https://user-images.githubusercontent.com/60865903/78983747-6c1b2e00-7b42-11ea-835d-9df7aa9cfd2f.png)

![image](https://user-images.githubusercontent.com/60865903/78983784-80f7c180-7b42-11ea-8f67-1fbecc409df0.png)

**Comment by dealako** [comment]
I don't feel this is an issue.  It is working as expected - the list of CLA Managers is counted and returned (regardless if they have used the product - they are still authorized to manage the CLA approval lists).
