### ISSUE TITLE
Contributor Console - Individual Contributor/Corporate Contributor name is not auto populated 

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#862]
## Background
1. Launch github repository with a project with ICLA and CCLA enabled (Company should have signed CLA for the project)
2. Login as contributor
3. Update file and create PR
4. CLA check fails
5. Click on CLA NOT SIGNED
6. Click on Individual in Contributor Console
7. Click OPEN CLA
8. Click on Start in docusign
9. Click on Continue in docusign
10. Click on Sign button
11. **Contributor name is not auto populated.**
**_Observed this issue for Corporate Contributor as well_**
![image](https://user-images.githubusercontent.com/60865903/79114217-56a33f80-7da0-11ea-9aed-c773cff82184.png)

**Name of the contributor in github**
![image](https://user-images.githubusercontent.com/60865903/79114300-90744600-7da0-11ea-8e44-de62667db72b.png)

**Comment by nirupamav** [comment]
Observed this issue in V2 as well

**Comment by dealako** [comment]
Can you share the screenshot of the PDF document within DocuSign?  Let me know if the CLA Manager's name or the GitHub user's info is not pre-filled on the CCLA document.

The EasyCLA API only updates the PDF document - we have no control over the Docusign signature or profile.
