### ISSUE TITLE
Contributor Console - Options not visible to proceed further after clicking in Corporate/Individual

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#863]
## Background

**Prerequisites**
1. Project with ICLA enabled should exist
2. Project with CCLA enabled should exist
3. Templates should be generated for the projects
4. Github repositories should be added to the projects
5. Company Should exist and should have signed CLA for the project and should have whitelisted the employee

**Steps to Follow**
**_Issue1_**
1. Launch github repository of the project
2. Login as individual contributor
3. Update any file and create PR
4. CLA checks fail
5. Click on CLA NOT SIGNED
6. Click on Individual in contributor console
7. **Observed options are not visible to proceed further**
**Observed this issue with project which has both ICLA and CCLA enabled**
![image](https://user-images.githubusercontent.com/60865903/79111880-fd84dd00-7d9a-11ea-9209-7b3d5ddf2959.png)

**_Issue1_**
1. Launch github repository of the project
2. Login as corporate contributor
3. Update any file and create PR
4. CLA checks fail
5. Click on CLA NOT SIGNED
6. Click on Corporate in contributor console
7. Select Company
8. **Observed options are not visible to proceed further**
![image](https://user-images.githubusercontent.com/60865903/79117542-0c728c00-7da9-11ea-80e3-e867a2b37f33.png)

**User has to reduce the browser zoom level or should view in full screen(F11 from keyboard)**

![image](https://user-images.githubusercontent.com/60865903/79117565-18f6e480-7da9-11ea-9770-45d76bb8db22.png)

**Comment by amolsontakke3576** [comment]
@dealako @nirupamav I had fixed this but few days before @hnexokonkwo worked on it, and he has commented some CSS style. Because of this issue again opened.

**Comment by nirupamav** [comment]
**_Issue2 is fixed but observed that the footer is displayed on the top of the page and reopening the ticket_**
![image](https://user-images.githubusercontent.com/60865903/79215616-70f52000-7e69-11ea-897d-21b63154fe93.png)


**_Verified that the Issue1 is fixed_**
![image](https://user-images.githubusercontent.com/60865903/79214024-c2041480-7e67-11ea-92d2-b30450099c6d.png)

**Comment by nirupamav** [comment]
Closing the ticket as Issue1 is tracked in ticket #823
