### ISSUE TITLE
add authorization in v2 endpoints

### ISSUE THREAD

**Issue by prasannamahajan** [communitybridge/easycla#866]
## Summary
projects v2 endpoint needs to be protected.
api gateway writes X-ACL,X-USERNAME,X-EMAIL,X-REQUEST-ID fields.
X-ACL contains access information.

## Tasks
- [x] Add  X-ACL,X-USERNAME,X-EMAIL,X-REQUEST-ID in headers of all request
- [x] Add authorization in all projects v2 endpoints

**Comment by prasannamahajan** [comment]
Pull Request : https://github.com/communitybridge/easycla/pull/868
Changes : Added authorization in projects api
@dealako Havn't added authorization for GetProjects api. we don't get ExternalProjectID in request. 
what should we do for this.

**Comment by nirupamav** [comment]
**Testing In Progress**
**_Test Plan Link_** https://confluence.linuxfoundation.org/display/PROD/EascyCLA+-+Authorization+for+Projects+Endpoint

**_Bugs Logged_** #1000, #1001, #1003, #1004

**Comment by dealako** [comment]
This is completed. Closing ticket.
