### ISSUE TITLE
UI - Project Console - Module Cleanup

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#871]
## Summary

UI - Project Console - Module Cleanup.

## Background

- [x] Remove unused modules in the Project Console.  Ensure modules are not used or referenced.  Remove HTML, CSS, Module Definition and Typescript logic.
- [x] Remove any unused functions in the cla.services.ts (if any remain)
- [x] Confirm UI still builds and works as expected.

## User Story

As a developer, I want to reduce the UI clutter and not have extra unused files/modules in the source code repository.

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

\(Optional\) Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by nirupamav** [comment]
**_Verified below scenarios. There are few issues which were there even before this ticket was fixed and few new tickets are logged which are listed below against the test sceanrio_**
| Scenario  | Status | Bug | Comments |
| ------------- | ------------- | ------------- | ------------- |
| Foundatiosn name, logo and description in All Projects page| Passed  | | |
| LFX logo and link in menu options in All Projects page| Passed  | | |
| All Projects link in menu options in All Projects page| Passed  | | |
| Sign Out link in menu options in All Projects page| Passed  | | |
| Add invalid github organization | Passed  | | |
| Add duplicate github organization | Passed  | | |
| Configure and install valid github organization | Passed  |#1034 | |
| Delete the configured github organization | Passed  | | |
| Add and do not configure/install valid github organization | Passed  | | |
| Delete the github organization that is added but not configured/installed | Passed  | | |
| Configure/Install the github organization by clicking on the configure link of added but not configured github organization  | Passed  | | |
| Add CLA Group | Passed  | | |
| Update CLA Group | Passed  | | |
| Delete CLA Group | Passed  | | |
| Duplicate CLA Group | Passed  | | |
| Generate templates for CLA Group | Passed  | | |
| Back to Project from All pages of SELECT TEMPLATE | Passed  | | |
| View templates for CLA Group while generating templates | Passed  | | |
| View templates for CCLA and ICLA from View PDF History| Passed  | | |
| Singatures and Pagination in View Signatures| Passed  | | |
| Companies and Pagination in View Companies (From both View Companies button)| Passed  | | |
| Add Github repositories to CLA Group by clicking ADD on particular repositories| Passed  | | |
| Add Github repositories to CLA Group by clicking ADD ALL REPOS| Passed  | | |
| Remove Github repositories to CLA Group by clicking REMOVE on particular repositories| Passed  | | |
| Add Github repositories to CLA Group by clicking REMOVE ALL REPOS| Passed  | | |
| Gerrit Configuration for CLA Group| Passed  | | |
| Foundation name, logo and description in Project Details page| Passed  | | |
| Back to All Projects from Project Details page| Passed  | | |
| Header and Footer in all pages of Project Console| Passed  | | |
|EasyCLA Documentation link in all pages of Project Console| Passed  | | |
|Help link in footer in all pages of Project Console| Passed  | | |
|EascyCLA logo in all pages of Project Console| Passed  | | |
