### ISSUE TITLE
UI - Contributor Console - Module Cleanup

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#872]
## Summary

UI - Contributor Console - Module Cleanup.

## Background

- [x] Remove unused modules in the Contributor Console.  Ensure modules are not used or referenced.  Remove HTML, CSS, Module Definition and Typescript logic.
- [x] Remove any unused functions in the cla.services.ts (if any remain)
- [x] Confirm UI still builds and works as expected.

## User Story

As a developer, I want to reduce the UI clutter and not have extra unused files/modules in the source code repository.

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

\(Optional\) Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by dealako** [comment]
REsolved

**Comment by nirupamav** [comment]
**_Verified below scenarios_**
| Scenario  | Status | Bug | Comments |
| ------------- | ------------- | ------------- | ------------- |
| Redirect to Contributor Console when clicked on CLA NOT SIGNED in github PR | Passed  | | |
| Only Individual option is displayed when only ICLA is enabled for the project | Passed | | |
| UI alignment when only Individual option is displayed | Passed | | |
| UI alignment when only Individual option is clicked | Passed | | |
| Individual contribution when only ICLA is enabled | Passed | | |
| Only Corporate option is displayed when only CCLA is enabled for the project | Passed | | |
| UI alignment when only Corporate option is displayed | Passed | | |
| Company Selection Popup when clicked on Corporate | Passed | | |
| Company Selection Popup search functionality | Passed | | |
| Not signed Company popup when requesting for authorization | Passed | | |
| Both Individual and Corporate options are displayed when both ICLA and CCLA is enabled for the project | Passed | | |
| UI alignment when both Individual and Corporate options are displayed | Passed | | |
| Individual contribution when both CCLA and ICLA are enabled | Passed | | |
| Employee request for authorization by selecting cla manager from list when company has signed CLA | Passed | | |
| Employee request for authorization by directly entering cla manager from list when company has signed CLA | Passed | | |
| Whitelisted employee contribution when ICLA signature is required | Passed | | |
| Whitelisted employee contribution when ICLA signature is not required | Passed | | |
| Employee request for authorization when company is not in list and when contributor is not cla manager | Passed | | |
| Employee request for authorization when company is not in list and when contributor is cla manager. User redirected to Corporate Console | Passed | | |
