### ISSUE TITLE
v2 Metrics - Top 5 Projects

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#873]
## Summary

Create a metric summary that shows an ordered list of top 5 projects with the most contributors.

## Background

Create an API endpoint that returns the projects with the most contributors. Break down the counts as:

- [x] Top 5 Projects with the most Individual CLAs (ICLA)
- [x] Top 5 projects with the most Corporate CLAs (CCLA)
- [x] Top 5 projects with the most CLAs (ICLA + CCLA)

## User Story

As an LF admin, I want to see the top 5 projects based on contributors

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

## References

\(Optional\) Provide any code or specification references that would be helpful for the developer implementing this feature.

**Comment by dealako** [comment]
@pranab-bajpai this was requested by @kriva03

**Comment by kriva03** [comment]
<<Project 1>>
Total #of CLAs
Number of ICLAs:
Number of CCLAs:
<<Project 2>>
Total #of CLAs
Number of ICLAs:
Number of CCLAs:
<<Project 3>>
Total #of CLAs
Number of ICLAs:
Number of CCLAs:
<<Project 4>>
Total #of CLAs
Number of ICLAs:
Number of CCLAs:
<<Project 5>>
Total #of CLAs
Number of ICLAs:
Number of CCLAs:

**Comment by prasannamahajan** [comment]
Pull Requst : https://github.com/communitybridge/easycla/pull/875
API : {{apiserver}}/v4/metrics/top-projects
Only admin will have access of it.
Sample Response.
`{
    "topProjectsByCcla": [
        {
            "claManagersCount": 995,
            "companiesCount": 524,
            "corporateContributorsCount": 1844,
            "createdAt": "2020-04-14T12:30:58Z",
            "externalProjectID": "a0941000002wBz4AAE",
            "id": "b15286dd-4b34-4bb7-a57d-543e9c4a4efc",
            "individualContributorsCount": 8400,
            "projectName": "CNCF CLA Group",
            "repositoriesCount": 0,
            "totalContributorsCount": 10244
        },
        {
            "claManagersCount": 5,
            "companiesCount": 102,
            "corporateContributorsCount": 0,
            "createdAt": "2020-04-14T12:31:04Z",
            "externalProjectID": "a0941000002wBz5AAE",
            "id": "47f742ee-d925-43d2-b1e6-2693b000fca9",
            "individualContributorsCount": 1,
            "projectName": "Issue666CCLA_ICLA",
            "repositoriesCount": 0,
            "totalContributorsCount": 1
        },
        {
            "claManagersCount": 2,
            "companiesCount": 3,
            "corporateContributorsCount": 0,
            "createdAt": "2020-04-14T12:31:04Z",
            "externalProjectID": "a092M00001G3xhxQAB",
            "id": "14b2b048-c462-49d4-b46c-a7d7334ba305",
            "individualContributorsCount": 0,
            "projectName": "Amol Groups",
            "repositoriesCount": 0,
            "totalContributorsCount": 0
        },
        {
            "claManagersCount": 3,
            "companiesCount": 3,
            "corporateContributorsCount": 2,
            "createdAt": "2020-04-14T12:30:59Z",
            "externalProjectID": "a0941000005ouJFAAY",
            "id": "d5412846-5dda-4c58-8f62-4c111a3cd0d3",
            "individualContributorsCount": 0,
            "projectName": "Deal Project",
            "repositoriesCount": 4,
            "totalContributorsCount": 2
        },
        {
            "claManagersCount": 2,
            "companiesCount": 3,
            "corporateContributorsCount": 0,
            "createdAt": "2020-04-14T12:30:59Z",
            "externalProjectID": "a0941000002wBz4AAE",
            "id": "d675228f-4a9c-4204-847c-86cda7e4d8a7",
            "individualContributorsCount": 0,
            "projectName": "H-ICLAA",
            "repositoriesCount": 0,
            "totalContributorsCount": 0
        }
    ],
    "topProjectsByIcla": [
        {
            "claManagersCount": 995,
            "companiesCount": 524,
            "corporateContributorsCount": 1844,
            "createdAt": "2020-04-14T12:30:58Z",
            "externalProjectID": "a0941000002wBz4AAE",
            "id": "b15286dd-4b34-4bb7-a57d-543e9c4a4efc",
            "individualContributorsCount": 8400,
            "projectName": "CNCF CLA Group",
            "repositoriesCount": 0,
            "totalContributorsCount": 10244
        },
        {
            "claManagersCount": 2,
            "companiesCount": 1,
            "corporateContributorsCount": 2,
            "createdAt": "2020-04-14T12:30:59Z",
            "externalProjectID": "a0941000005ouJFAAY",
            "id": "c19928a5-7df9-40ea-9d5b-a1551f5bf5e9",
            "individualContributorsCount": 4,
            "projectName": "CLA Group July 30 A",
            "repositoriesCount": 0,
            "totalContributorsCount": 6
        },
        {
            "claManagersCount": 1,
            "companiesCount": 1,
            "corporateContributorsCount": 1,
            "createdAt": "2020-04-14T12:31:04Z",
            "externalProjectID": "a0941000002wBz4AAE",
            "id": "ca40210e-eb50-4bf2-8ec3-99d454f4bd89",
            "individualContributorsCount": 3,
            "projectName": "CLA group July 17 11PM",
            "repositoriesCount": 0,
            "totalContributorsCount": 4
        },
        {
            "claManagersCount": 1,
            "companiesCount": 2,
            "corporateContributorsCount": 1,
            "createdAt": "2020-04-14T12:30:58Z",
            "externalProjectID": "a0941000005ouJFAAY",
            "id": "97cedfe5-5445-485a-9cef-f837ae9e4eb0",
            "individualContributorsCount": 3,
            "projectName": "Test CLA group ONAP jul12",
            "repositoriesCount": 0,
            "totalContributorsCount": 4
        },
        {
            "claManagersCount": 1,
            "companiesCount": 1,
            "corporateContributorsCount": 1,
            "createdAt": "2020-04-14T12:30:59Z",
            "externalProjectID": "a0941000002wBz4AAE",
            "id": "2c84f0dd-598a-404c-8aab-6b3b94f44745",
            "individualContributorsCount": 2,
            "projectName": "CLA Group Jan 29",
            "repositoriesCount": 1,
            "totalContributorsCount": 3
        }
    ],
    "topProjectsByIclaAndCcla": [
        {
            "claManagersCount": 995,
            "companiesCount": 524,
            "corporateContributorsCount": 1844,
            "createdAt": "2020-04-14T12:30:58Z",
            "externalProjectID": "a0941000002wBz4AAE",
            "id": "b15286dd-4b34-4bb7-a57d-543e9c4a4efc",
            "individualContributorsCount": 8400,
            "projectName": "CNCF CLA Group",
            "repositoriesCount": 0,
            "totalContributorsCount": 10244
        },
        {
            "claManagersCount": 5,
            "companiesCount": 102,
            "corporateContributorsCount": 0,
            "createdAt": "2020-04-14T12:31:04Z",
            "externalProjectID": "a0941000002wBz5AAE",
            "id": "47f742ee-d925-43d2-b1e6-2693b000fca9",
            "individualContributorsCount": 1,
            "projectName": "Issue666CCLA_ICLA",
            "repositoriesCount": 0,
            "totalContributorsCount": 1
        },
        {
            "claManagersCount": 2,
            "companiesCount": 1,
            "corporateContributorsCount": 2,
            "createdAt": "2020-04-14T12:30:59Z",
            "externalProjectID": "a0941000005ouJFAAY",
            "id": "c19928a5-7df9-40ea-9d5b-a1551f5bf5e9",
            "individualContributorsCount": 4,
            "projectName": "CLA Group July 30 A",
            "repositoriesCount": 0,
            "totalContributorsCount": 6
        },
        {
            "claManagersCount": 1,
            "companiesCount": 2,
            "corporateContributorsCount": 1,
            "createdAt": "2020-04-14T12:30:58Z",
            "externalProjectID": "a0941000005ouJFAAY",
            "id": "97cedfe5-5445-485a-9cef-f837ae9e4eb0",
            "individualContributorsCount": 3,
            "projectName": "Test CLA group ONAP jul12",
            "repositoriesCount": 0,
            "totalContributorsCount": 4
        },
        {
            "claManagersCount": 1,
            "companiesCount": 1,
            "corporateContributorsCount": 1,
            "createdAt": "2020-04-14T12:31:04Z",
            "externalProjectID": "a0941000002wBz4AAE",
            "id": "ca40210e-eb50-4bf2-8ec3-99d454f4bd89",
            "individualContributorsCount": 3,
            "projectName": "CLA group July 17 11PM",
            "repositoriesCount": 0,
            "totalContributorsCount": 4
        }
    ]
}`

**Comment by nirupamav** [comment]
**Testing In Progress**
**_Test Plan Link_** https://confluence.linuxfoundation.org/display/PROD/top-projects

**Comment by swinslow** [comment]
@dealako @kriva03 This says that the "LF Admin" role will have access to this API. Who is included in that role?

**Comment by pranab-bajpai** [comment]
This information is not needed anymore. Ticket will be closed.
