### ISSUE TITLE
Contributor Error in PROD

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#877]
## Summary

A contributor follows the GitHub comment link to sign the ICLA or verify with CCLA. The console hangs here https://files.slack.com/files-pri/T02H1G4T9-F011R5T39AN/image.png
![image](https://user-images.githubusercontent.com/46732999/79242643-928ee100-7e42-11ea-91fa-a9383ddbb60d.png)

An error in the cloudwatch logs is observed
https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/lambda/cla-backend-prod-githubinstall;stream=2020/04/13/%5B$LATEST%5D65021e1a479d4b969bb6ebd20f3d11bf;refid=35387101494326561501761752536073768362420031120023748611;reftime=1586812511389

From the PR https://github.com/openjs-foundation/TEST-EasyCLA/pull/3

**Comment by WillsonHG** [comment]
The error in cloudwatch does not seem to the be the cause of this particular problem with the cla options not loading.

**Comment by dealako** [comment]
Discussed with the team, issue resolved.
