### ISSUE TITLE
[Staging] - Contributor/project Console - Logo is loaded very slowly when contributor navigates to Contributor console for the first time

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#881]
## Background
**Prerequisites**
1. Valid Project should exist
2. ICLA and CCLA should be enabled for the project
3. Templates should be generated for the project
4. Github repository should be added to the project

**Steps to Follow**
1. Launch github repository
2. Login as contributor
3. Update any file and create PR
4. CLA checks fail
5. Click on CLA NOT SIGNED
6. If required AUTHORIZE LF Engineering access
7. User is redirected to Contributor console
8. **Observed that Logo is loaded very slowly. Same issue observed when clicked on Corporate/Individual and proceed further with the flow
Issue observed in Project Console - All projects page as well**
![image](https://user-images.githubusercontent.com/60865903/79302920-422f8600-7f0b-11ea-90c5-0e5975178228.png)

![image](https://user-images.githubusercontent.com/60865903/79302956-4e1b4800-7f0b-11ea-963c-b5ba2e7db289.png)

**Comment by amolsontakke3576** [comment]
@dealako Verified and look cool now :)
![Screenshot from 2020-12-03 13-25-42.png](https://images.zenhubusercontent.com/5edefc0479e1e6535aa8f788/fc61a93e-3362-4c5a-a05f-033eb83b4092)

**Comment by dealako** [comment]
The old v1 console is deprecated and removed.
