### ISSUE TITLE
[Staging] Corporate Console - Company name is displayed outside the document in docusign when company name is too long

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#883]
## Background
Prerequisite
Company with long name should be exist

**Steps to follow**
1. Launch Corporate Console
2. Login as CLA Manager
3. Click on the Company
4. Click on SIGN NEW CLA
5. Click YES
6. Click OPEN CLA
7. Observed that company name is displayed outside the document in docusign

![image](https://user-images.githubusercontent.com/60865903/79312087-0355fc00-7f1c-11ea-8efd-b1c1dcf06a1b.png)

**Comment by nirupamav** [comment]
**Verified in Dev and observed that the issue is still reproducible**
![image](https://user-images.githubusercontent.com/60865903/80564715-37e1b180-8a0c-11ea-9d73-3e39ca7faa8f.png)

**Comment by amolsontakke3576** [comment]
@nirupamav It will not work for existing company name as restriction for name added during add company. You can try by creating new company.

**Comment by nirupamav** [comment]
**Verified that Company Name accepts only 60 characters and also issue in docusign is fixed**
![image](https://user-images.githubusercontent.com/60865903/80575201-cbbd7880-8a20-11ea-9f50-28ac46ceddf7.png)

**ADD COMPANY is disabled and error message is displayed when more than 60 characters are entered for Company name**
![image](https://user-images.githubusercontent.com/60865903/80575264-e7c11a00-8a20-11ea-94c7-36c1a0db065e.png)
