### ISSUE TITLE
[Intermittent Issue] Corporate Console - Sometimes Observed company_id not supplied error in api call when trying to sign cla

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#889]
## Background
**Observed in both Dev and Staging**

1. Launch Corporate Console
2. Login as CLA Manager
3. Click on the Company
4. Click SIGN NEW CLA
5. Search and select the project
6. Click SUBMIT
7. Click NO **_(Issue observed when YES is selected and proceeded further with the flow)_**
8. Enter Signatory details
9. Click SEND
10. Observed below issue
![image](https://user-images.githubusercontent.com/60865903/79341193-09160680-7f49-11ea-80af-78aed4f58ec7.png)

**Comment by amolsontakke3576** [comment]
@dealako Verified and working fine now.

**Comment by dealako** [comment]
The old v1 console is deprecated and removed.
