### ISSUE TITLE
GitHub checks can be bypassed by an admin

### ISSUE THREAD

**Issue by mkdolan** [communitybridge/easycla#89]
When someone submits a new PR, the admin can merge the PR even if the CLA check fails.

**Comment by jpalmerLinuxFoundation** [comment]
Hi Mike. Just to reiterate to make sure I understand. Do we want to limit admin's ability to merge code in the scenario that the user does not have a signed CLA? We'll have to look at what GitHub permits from Apps installed on Repos. I don't think it's generally permitted to restrict Admin activities, but we'll research this.

**Comment by jpalmerLinuxFoundation** [comment]
I'll be working with CNCF to see how v1 enforces this.

**Comment by dealako** [comment]
@kriva03 @pranab-bajpal based on my understanding, this is a GitHub restriction/policy/feature.  Owners of a given repository can force merge a PR using their Admin permissions.  This is outside the scope of EasyCLA.  Please confirm.

**Comment by pranab-bajpai** [comment]
Yes @dealako it seems like this depends on how the repo is setup. I found this in github help pages
https://help.github.com/en/github/administering-a-repository/enabling-required-status-checks. If you follow these steps you can force status checks on Administrator too. I don't think this in EasyCLAs domain.

**Comment by dlorenc** [comment]
The Google CLA bot actually allows project admins to bypass the check in a few conditions. It's basically designed to act as a break-glass feature in cases where the bot is wrong or down or something else goes wrong.

Maintainers can manually check that an individual signed the CLA, and then leave this information as a comment on the PR before bypassing.

**Comment by dealako** [comment]
After discussing, we are closing this issue as this is a GitHub feature/limitation (not an EasyCLA configuration setting).
