### ISSUE TITLE
WhiteList -> Approved List Language Update

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla#893]
## Impacted Docs

All impacted EasyCLA documents need to be reviewed and updated.

## Tasks

* [x] Update all documentation text that includes "Whitelist" - replace to say "Approved List"
* [ ] Replace all documentation screen captures that includes "Whitelist" - depends on #892 

## Verbiage

- Replace "Whitelist" with "Approved List"

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Documentation changes submitted as a Pull Request
1. Pull Request Reviewed and Approved by Product Owner
1. Documentation changes merged to 'master' branch

## Images

Attach any images or screenshots related to this documentation update.

**Comment by dibyaranjanlf** [comment]
Replaced **Whitelist** with **Approved List** in the doc including all the relevant screen grabs except one image, which is the **Contact** window that is displayed when a corporate contributor tries to contribute to a gerrit project, but is not authorized by the company.
@dealako @heather, Could you please help me getting the screen grab as I am not able to do it at my end. 

Here is the doc link for review: https://docs.linuxfoundation.org/docs/communitybridge/communitybridge-easycla

**Comment by dibyaranjanlf** [comment]
Thanks @WillsonHG . I have updated the image. Here is the doc link: https://docs.linuxfoundation.org/docs/communitybridge/easycla/getting-started

**Comment by WillsonHG** [comment]
Thank you @dibyaranjanlf  I'll mark this as resolved.
