### ISSUE TITLE
Remove unused metrics api.

### ISSUE THREAD

**Issue by prasannamahajan** [communitybridge/easycla#897]
## Summary

We have lot of metrics api which are not in use. We should remove them to clean
our code

## Background
Recently we have add metrics api which makes old metrics api absolute.
Remove these metrics api.

## User Story

As a maintainer of easycla, I want to remove the absolute unused metrics api.

## Acceptance Criteria

The "done" criteria when this feature or problem is resolved. Such as:

1. Unit Tests added and running in CI
1. Functional Tests updated to cover feature, if applicable
1. Demonstrate the set of capabilities to the product team while the code is running in the STAGING environment.

**Comment by prasannamahajan** [comment]
Pull Request: https://github.com/communitybridge/easycla/pull/898

**Comment by dealako** [comment]
Resolved.
