### ISSUE TITLE
[Staging] CLA manager request to join company hangs after pressing "Join Company"

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#901]
## Summary

When a potential cla manager requests to join a company, the modal hangs with no feedback to the user, but the email is sent.

![image](https://user-images.githubusercontent.com/46732999/79478200-1549a480-7fd9-11ea-9d6a-d617444db127.png)

**Comment by nirupamav** [comment]
Looks like it is inconsistent issue. Observed this issue in Dev env as well
![image](https://user-images.githubusercontent.com/60865903/80070321-6a009880-8560-11ea-80a8-3698ed2c0737.png)

![image](https://user-images.githubusercontent.com/60865903/80070371-7d136880-8560-11ea-8183-d55d7adada51.png)

**Comment by nirupamav** [comment]
Observed this issue again today. Intermittent issue
![image](https://user-images.githubusercontent.com/60865903/81163562-967ad280-8fac-11ea-930d-977d45c4fa28.png)

**Comment by amolsontakke3576** [comment]
@rinkeshbhutwala can you please look into it? below are the details for failed API

https://api.lfcla.dev.platform.linuxfoundation.org/v3/company/07206b03-d26a-498a-8de4-2de857576584/cla/accesslist/request
Request: PUT

Input : 
{
  "userID": "amolsontakke",
  "lfUsername": "amolsontakke",
  "lfEmail": "amols@proximabiz.com",
  "username": "Amol Santakke"
}

**Comment by rinkeshbhutwala** [comment]
@amolsontakke3576 @dealako I have verified this ticket locally and also tested Dev and Staging looks like issue is fixed so moving this ticket to **Ready For QA**
