### ISSUE TITLE
Update documentation link in consoles to "Getting Started" doc

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#907]
The project console at project.staging.lfcla.com does not have a "EasyCLA Documentation" button in the ribbon like the corporate console does. 

They should both point to https://docs.linuxfoundation.org/easycla/getting-started

- [x] add "EasyCLA Documentation " button to project console ribbon and point to https://docs.linuxfoundation.org/easycla/getting-started
- [x] change button in corporate console to https://docs.linuxfoundation.org/easycla/getting-started
- [ ] would also be a good idea to add a button to the contributor console ribbon as well.

**Comment by dealako** [comment]
@hnexokonkwo I have updated the link the corporate console, but need help adding the link to the:
- [ ] Project Console (all pages)
- [ ] Contributor Console (all pages)

Copy the same design pattern. I attempted this, but the Get Help component was floating on the top of the nav bar and not embedded within on the right margin. So, I'll defer to you to help get it on the above pages.

Thanks!
