### ISSUE TITLE
Corporate Console - Logo overlaps on Company name in Manage Approved List when Company name is too long

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#915]
## Background
1. https://corporate.dev.lfcla.com/
2. Login
3. Click on the company that has signed cla and has long name
4. Click on MANAGE APPROVED LIST
5. Observed that logo overlaps on company name

![image](https://user-images.githubusercontent.com/60865903/79550621-3b914200-80b6-11ea-8828-e11dd08099d1.png)

**Comment by nirupamav** [comment]
**Verified that the issue is fixed**
![image](https://user-images.githubusercontent.com/60865903/79828212-df803380-83bd-11ea-9381-719429c2cb37.png)

**Comment by dealako** [comment]
The old v1 console is deprecated and removed.
