### ISSUE TITLE
Project Console - IE EDGE - Observed that value null is displayed for GitHubID  and LFID in View signature

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#916]
## Background
1. Launch https://project.dev.lfcla.com in IE EDGE
2. Login
3. Click on the Foundation
4. Click on View Singatures of the project which has been signed by companies
5. Observed that null is displayed for GitHubID  and LFID when it does not have any value

![image](https://user-images.githubusercontent.com/60865903/79552304-7d22ec80-80b8-11ea-8794-a6148657d66f.png)

**Comment by dealako** [comment]
The old v1 console is deprecated and removed.
