### ISSUE TITLE
Corporate Console - Sorting order of companies and signed projects

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#917]
## Background
1. Launch Corporate Console
2. Login as CLA Manager
**3. Observed that companies are displayed randomly and does not follow any sorting order**
![image](https://user-images.githubusercontent.com/60865903/79555394-279d0e80-80bd-11ea-8181-7093ab4e0493.png)
4. Click on any company
**5. Observed that projects are displayed randomly and each time projects are displayed in different order**
![image](https://user-images.githubusercontent.com/60865903/79555568-7185f480-80bd-11ea-8cc3-d392e3d5a963.png)

![image](https://user-images.githubusercontent.com/60865903/79555603-7fd41080-80bd-11ea-8124-1d88ee7fe0c0.png)

**Comment by nirupamav** [comment]
**_Visited the page few times and refreshed the page few times and verified that Companies are sorted in alphabetical order and Companies with Join Pending request are displayed at the end in alphabetical order_**
![image](https://user-images.githubusercontent.com/60865903/80070616-d7acc480-8560-11ea-8085-ef5cd4910767.png)

![image](https://user-images.githubusercontent.com/60865903/80070595-cf548980-8560-11ea-817c-2ac7961d1da5.png)

**_Visited the page few times and refreshed the page few times and verified that projects are always displayed in alphabetical order_**
![image](https://user-images.githubusercontent.com/60865903/80070924-6a4d6380-8561-11ea-86ab-04ff801d0e41.png)

**Comment by nirupamav** [comment]
**Issue is again reproducible for Signed Projects and hence reopening the ticket**
![image](https://user-images.githubusercontent.com/60865903/81193936-a6f57200-8fd9-11ea-928d-b620d5d5a77e.png)

![image](https://user-images.githubusercontent.com/60865903/81193979-b379ca80-8fd9-11ea-8cae-894a0202387d.png)

**Comment by amolsontakke3576** [comment]
@dealako  @nirupamav Sorry to not inform you but due to sort it create issue in updating pending count for contributor which is separate API call. So currently removed sorting from code till get some concrete solution.
