### ISSUE TITLE
[Staging] Wrong behaviors when resuming signing a ccla

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#922]
When a CLA manager goes to sign a project's CLA, the manager can stop in the middle of the signing at docusign and hit back in the project console to select yes or no again. This starts a new session with docusign and this creates mulitple entries in the database. The project manager is also unable to go back and finish the signing process after leaving the corporate console and going back in.
Bug behavior in staging
1. cla manager selects "yes" when asked if they are able to sign
1. "false" signature created in database
1. cla manager does not complete the signing through docusign and instead hits the back arrow and selects "yes" again.
1. another "false" signature is created in database.
1. this repeats until the manager either leaves the corporate console, completes the signing, or hits "no" to send the cla to another person.
1. if manager selects "no", the program exits them from the process and the manager is unable to select the project from the list if he/she goes back in to sign again.
1. another "false" signature is created in the database for the "no" option.
1. if the process is abandoned by the cla manger, or the signatory does not sign the cla, there is no way for the manager to select the cla again and the signature remains "false" and inactive.

Different envelope ID's and no voided emails
![image](https://user-images.githubusercontent.com/46732999/79584530-869e5b80-809c-11ea-80ce-6506a763bdfa.png)

Correct behavior in prod:
Doing the above results in the same envelope id being used for the project and company combo - there is never duplicate signature entries made and the project is always selectable in the corporate console list of cla's to sign until the signature entry is changed to "true" when the signing is completed. Previous users who were trying to sign the same company and project combo get "voided" emails from docusign when more attempts are made at signing with the same combo.

Same signature entry and voided emails in Prod
![image](https://user-images.githubusercontent.com/46732999/79585276-92d6e880-809d-11ea-8e98-247d9685bb9b.png)

**Comment by dealako** [comment]
While reviewing the code for this issue, it seems that:

1. we query the database for CCLA documents - Signed = True, Approved = True
1. If the resulting signature count is zero signatures, then we initiate a new corporate signature signing process
1. If the resulting signature count is non-zero, we return an error indicating that we already have a valid CCLA signature

Key Point:

1. We are not handling the situation where we have 1 or more Signed = False, Approved = True existing records

Working on fix.

**Comment by dealako** [comment]
Task not fully resolved. Moving to the next sprint.

**Comment by dealako** [comment]
Need to confirm this is still an issue. We have made modifications to the queries and need to re-evaluate this issue.

**Comment by dealako** [comment]
I believe this is now resolved... can we re-validate @nirupamav

**Comment by nirupamav** [comment]
Issue was verified in #945 and hence moving the ticket to QA Done
