### ISSUE TITLE
Link to documentation on all Landing pages

### ISSUE THREAD

**Issue by WillsonHG** [communitybridge/easycla#924]
On lfcla.com, the "learn more" button should link to the documentation https://docs.linuxfoundation.org/easycla/getting-started instead of an old blogpost
![image](https://user-images.githubusercontent.com/46732999/79604814-c9702b80-80bc-11ea-8d22-06108bfb7e0e.png)

On project.lfcla.com and corproate.linuxfoundation.org we need to add a "EasyCLA Documentation" link to go to https://docs.linuxfoundation.org/easycla/getting-started  It could be put in the bottom right corner with the "Get Help" link.
![image](https://user-images.githubusercontent.com/46732999/79605315-a98d3780-80bd-11ea-96b2-e4a6a46cd8d7.png)

@pranab-bajpai  any feedback about the placement of the links is welcome.

**Comment by amolsontakke3576** [comment]
@WillsonHG @dealako @pranab-bajpai @nirupamav As per the latest discussion, the documentation link now updated to the below URL
New link : `https://docs.linuxfoundation.org/docs/communitybridge/easycla`

**Comment by nirupamav** [comment]
As per below description in issue link to documentation should be available along with Get Help in Project Console and Corporate console but it is not available
On project.lfcla.com and corproate.linuxfoundation.org we need to add a "EasyCLA Documentation" link to go to https://docs.linuxfoundation.org/easycla/getting-started It could be put in the bottom right corner with the "Get Help" link.

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/5b313642-6e86-459b-83aa-dc4176fbbef7)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/64b09964-8642-48d2-b00e-1c48a84d7c92)

**Working scenario**
When clicked on Learn More from https://lfcla.com/ user is redirected to https://docs.linuxfoundation.org/docs/communitybridge/easycla
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/89acfc5a-a5e3-47af-a358-a5235ab87502)

**Comment by nirupamav** [comment]
**Verified that the above reported issues are fixed. User is redirected to https://docs.linuxfoundation.org/docs/communitybridge/easycla when clicked on EasyCLA Documentation link**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/c0d21198-3f45-499d-9b4c-22b01f54c527)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/2982b127-b92d-4bfa-b370-46ddc0c43c15)
