### ISSUE TITLE
CLA Managers From My Organization

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#929]
## Summary
Any user associated with a company will be taken to this page after they switch to member console, select foundation from left navigation and EasyCLA from top navigation.

Here is the link to [wireframe ](https://wireframepro.mockflow.com/view/corporate-console#/page/D702f061837fbb5ff5b4911bbf7149bfd)for the foundation page for EasyCLA.

![image](https://user-images.githubusercontent.com/57362064/79611694-c414e000-80c0-11ea-97eb-f1669bb9f35a.png)

Step 3 in PRD https://confluence.linuxfoundation.org/display/PROD/Foundation+Dashboard+for+EasyCLA

**CLA Managers From My Organization will list information about CLA Managers from user's company**. 
The table displays following columns:

**Name** i.e. the CLA Manager name along with photo (if available from their individual profile page)
**Email Address** of the CLA Manager.
**Approved on** i.e. the date they were added as CLA Manager. 
**CLA Group** shows the CLA Group for which person is the CLA Manager
**Project or Foundation name** with project or foundation's icon.
The information for this table will be provided by EasyCLA API

**NOTE :**

**If the user's company has not got any signed CLAs OR any CLA Managers that fall under this foundation then this table display is empty.**
**There is no pagination on this table, all the values will be displayed at once.**
**Data in this table is sorted alphabetically A→Z by CLA Manager FirstName in the Name column.**

##Acceptance Criteria
- [ ] Design Changes Required ?--> Not Applicable (N/A)   
- [ ] Unit Testing Complete 
    - [ ] Unit Testing complete for backend API
    - [ ] Unit Testing complete for UI
- [ ] Functional Testing Complete 
    - [ ] Functional Testing complete for backend API
    - [ ] Functional Testing complete for UI
- [ ] Integration Testing Complete 
    - [ ] Integration Testing complete for backend API and UI
    - [ ] Integration Testing complete end to end dev deployment
- [ ] Documentation Updated 
- [ ] Any Open Sev. 1 or Sev 2 bug(s)

**Comment by prasannamahajan** [comment]
Note: 
we don't have approved_on data available of cla_manager.

**Comment by dealako** [comment]
@prasannamahajan have we addressed everything for this issue? If so, can we work with @nirupamav to review and possibly write a functional test?

**Comment by nirupamav** [comment]
Since it is not ready for testing moving the ticket to In Progress

**Comment by prasannamahajan** [comment]
@nirupamav its ready for testing now

**Comment by nirupamav** [comment]
@pranab-bajpai @dealako 
Observed that CLA group name is returned instead of project/foundation name. Is this expected behavior
{
    "list": [
        {
            "approved_on": "2020-05-14T09:37:01.322514+0000",
            "email": "nirupamav+clamanger2@proximabiz.com",
            "lf_username": "clamanager2",
            "logo_url": "",
            "name": "niupamav clamanager2",
            "project_id": "67e9b2e1-44fc-4b67-9712-6610e80f507a",
            "project_name": "Cello_CNCF",
            "project_sfid": "a0941000002wBz4AAE",
            "user_sfid": "00Q1700000BhPmBEAV"
        },
        {
            "approved_on": "2020-05-14T05:50:12.930521+0000",
            "email": "nirupamav+clamanger2@proximabiz.com",
            "lf_username": "clamanager2",
            "logo_url": "",
            "name": "niupamav clamanager2",
            "project_id": "79c8ea6e-e7c7-4b60-bc5a-e6f0874b7f81",
            "project_name": "EMM",
            "project_sfid": "a0941000002wBz5AAE",
            "user_sfid": "00Q1700000BhPmBEAV"
        }
    ]
}

**Comment by nirupamav** [comment]
Based on the discussion in the standup call, the fields in response needs to be updated and hence reopening the ticket

**Comment by nirupamav** [comment]
Since the Endpoint needs modification reopening the ticket

**Comment by nirupamav** [comment]
**Performed testing for happy path and happy path is working as expected. Testing is Inprogress for other scenarios**
At Foundation Level CLA Managers for Foundation and CLA Managers for all projects under foundation are fetched
**Test Data used**
**_Role_** cla-manager
**_Scope_**
Cloud Native Computing Foundation|Bakbone

**_Endpoint_**
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company/0014100000Te1DWAAZ/project/a0941000002wBz4AAE/cla-managers

**_Response_**
{
    "list": [
        {
            "approved_on": "2020-05-14T09:37:01.322514+0000",
            "cla_group_name": "Cello_CNCF",
            "email": "nirupamav+clamanager10@proximabiz.com",
            "lf_username": "nirupamavclamanager10",
            "logo_url": "",
            "name": "nirupamav clamanager10",
            "project_id": "67e9b2e1-44fc-4b67-9712-6610e80f507a",
            "project_name": "Cloud Native Computing Foundation",
            "project_sfid": "a0941000002wBz4AAE",
            "user_sfid": "00Q1700000BhhoZEAR"
        },
        {
            "approved_on": "2020-06-01T10:11:39.485378+0000",
            "cla_group_name": "CRI-O CLA Group2",
            "email": "nirupamav+clamanager10@proximabiz.com",
            "lf_username": "nirupamavclamanager10",
            "logo_url": "",
            "name": "nirupamav clamanager10",
            "project_id": "3d354e3d-1561-49bf-a66c-ffa31392a018",
            "project_name": "CRI-O",
            "project_sfid": "a092M00001IV45HQAT",
            "user_sfid": "00Q1700000BhhoZEAR"
        },
        {
            "approved_on": "2020-05-26T14:30:57.128755+0000",
            "cla_group_name": "Cello_CNCF1",
            "email": "nirupamav+clamanager10@proximabiz.com",
            "lf_username": "nirupamavclamanager10",
            "logo_url": "",
            "name": "nirupamav clamanager10",
            "project_id": "9fb628ad-c72e-4849-8272-8a440f372887",
            "project_name": "Cloud Native Computing Foundation",
            "project_sfid": "a0941000002wBz4AAE",
            "user_sfid": "00Q1700000BhhoZEAR"
        },
        {
            "approved_on": "2020-06-01T10:11:39.485378+0000",
            "cla_group_name": "CRI-O CLA Group1",
            "email": "nirupamav+clamanager10@proximabiz.com",
            "lf_username": "nirupamavclamanager10",
            "logo_url": "",
            "name": "nirupamav clamanager10",
            "project_id": "2e3f95be-962e-4eb0-90d6-48cce5a0218f",
            "project_name": "CRI-O",
            "project_sfid": "a092M00001IV45HQAT",
            "user_sfid": "00Q1700000BhhoZEAR"
        },
        {
            "approved_on": "2020-05-29T14:17:46.654807+0000",
            "cla_group_name": "BrigadeCLAGroup",
            "email": "nirupamav+clamanager10@proximabiz.com",
            "lf_username": "nirupamavclamanager10",
            "logo_url": "",
            "name": "nirupamav clamanager10",
            "project_id": "3564e0ad-5da9-4164-a158-1234a9845f75",
            "project_name": "Brigade",
            "project_sfid": "a092M00001IV4PgQAL",
            "user_sfid": "00Q1700000BhhoZEAR"
        },
        {
            "approved_on": "2020-06-01T10:30:16.413511+0000",
            "cla_group_name": "CloudEvents CLAGroup1",
            "email": "nirupamav+clamanager10@proximabiz.com",
            "lf_username": "nirupamavclamanager10",
            "logo_url": "",
            "name": "nirupamav clamanager10",
            "project_id": "33f79dc8-eacf-4e83-b372-4d25497eaa32",
            "project_name": "CloudEvents",
            "project_sfid": "a092M00001IV4PvQAL",
            "user_sfid": "00Q1700000BhhoZEAR"
        },
        {
            "approved_on": "2020-05-14T09:37:01.322514+0000",
            "cla_group_name": "Cello_CNCF",
            "email": "nirupamav+clamanger2@proximabiz.com",
            "lf_username": "clamanager2",
            "logo_url": "",
            "name": "niupamav clamanager2",
            "project_id": "67e9b2e1-44fc-4b67-9712-6610e80f507a",
            "project_name": "Cloud Native Computing Foundation",
            "project_sfid": "a0941000002wBz4AAE",
            "user_sfid": "00Q1700000BhPmBEAV"
        },
        {
            "approved_on": "2020-05-26T14:30:57.128755+0000",
            "cla_group_name": "Cello_CNCF1",
            "email": "nirupamav+clamanger2@proximabiz.com",
            "lf_username": "clamanager2",
            "logo_url": "",
            "name": "niupamav clamanager2",
            "project_id": "9fb628ad-c72e-4849-8272-8a440f372887",
            "project_name": "Cloud Native Computing Foundation",
            "project_sfid": "a0941000002wBz4AAE",
            "user_sfid": "00Q1700000BhPmBEAV"
        },
        {
            "approved_on": "2020-05-29T14:17:46.654807+0000",
            "cla_group_name": "BrigadeCLAGroup",
            "email": "nirupamav+clamanger2@proximabiz.com",
            "lf_username": "clamanager2",
            "logo_url": "",
            "name": "niupamav clamanager2",
            "project_id": "3564e0ad-5da9-4164-a158-1234a9845f75",
            "project_name": "Brigade",
            "project_sfid": "a092M00001IV4PgQAL",
            "user_sfid": "00Q1700000BhPmBEAV"
        }
    ]
}

**Comment by prasannamahajan** [comment]
added projectSFID as input parameter
API: [https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/getCompanyProjectClaManagers](url)

Moving ticket to "Ready for review" state

**Comment by nirupamav** [comment]
**Tested and have below queries and issues**
1. In response data for organization_name and organization_sfid is not returned
![image](https://user-images.githubusercontent.com/60865903/83733779-a816cf00-a66b-11ea-9cdf-2ceab6563135.png)

2. When invalid projectsfid is provided 400 is returned instead of 404. Is this expected behavior
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company/0014100000Te1DWAAZ/project/a092M00001IV45HQAG/cla-managers
![image](https://user-images.githubusercontent.com/60865903/83727603-f673a000-a662-11ea-8150-c4c3602f070e.png)
3. When invalid projectsfid is provided 403 is returned instead of 404. Is this expected behavior
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company/0014100000Te1DWAAP/project/a092M00001IV45HQAT/cla-managers
4. 403 is returned for user with lf-operations role and admin scope. . Is this expected behavior
5. When projectsfid/companysfid is not provided 403 is returned instead of 400. Is this expected behavior
6. As of now API returns date when CLA was signed for Approved on and not the date when CLA Manager was added. Could you please confirm if this is expected behavior
7. As per Foundation Dashboard for EasyCLA PRD, data in this section is sorted alphabetically. But in Project Dashboard data is sorted by Added On. Should the behavior be consistent in both the Foundation and Project Dashboard? If so which sort order needs to be followed?
