### ISSUE TITLE
Recent Activity Log for my organization

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#930]
##Summary
Any user associated with a company will be taken to this page after they switch to member console, select foundation from left navigation and EasyCLA from top navigation.

Here is the link to [wireframe ](https://wireframepro.mockflow.com/view/corporate-console#/page/D702f061837fbb5ff5b4911bbf7149bfd)for the foundation page for EasyCLA.

![image](https://user-images.githubusercontent.com/57362064/79611818-0a6a3f00-80c1-11ea-8c43-50633391ed3a.png)

Step 4 in PRD https://confluence.linuxfoundation.org/display/PROD/Foundation+Dashboard+for+EasyCLA

**Shows recent EasyCLA activity log for user's company. This includes information from all projects under this foundation for which your company has signed CLA. For project EasyCLA page this chart will only show information for that project associated with user's company.**

The activity-log should display project icons along with date/time stamp in the same format as shown in the wireframe design.

The list of projects will be scrollable and will show 5 events per page until the top 10 events are displayed. Notice that the web page will show x of y events at the bottom of the page. The value of 'x' refers to a number of records displayed and the value of 'y' refers to the maximum number of records found, limit the value of 'y' to 10.

The information for this table will be provided by EasyCLA API.

**NOTE :**

**If the user's company has not got any signed CLAs that fall under this foundation then this table display is empty. Green dot doesn't have any significance, it is just showing the latest event.**

##Acceptance Criteria
- [ ] Design Changes Required ?--> Not Applicable (N/A)   
- [ ] Unit Testing Complete 
    - [ ] Unit Testing complete for backend API
    - [ ] Unit Testing complete for UI
- [ ] Functional Testing Complete 
    - [ ] Functional Testing complete for backend API
    - [ ] Functional Testing complete for UI
- [ ] Integration Testing Complete 
    - [ ] Integration Testing complete for backend API and UI
    - [ ] Integration Testing complete end to end dev deployment
- [ ] Documentation Updated 
- [ ] Any Open Sev. 1 or Sev 2 bug(s)

**Comment by dealako** [comment]
@prasannamahajan for Organization Access:

users must be in one of the following roles for the associated Organization ID:
- company-admin
- company-alternate-owner
- company-owner
- cla-manager
- cla-signatory
- lf-admin
- lf-legal
- lf-operations
- super-admin

**Comment by prasannamahajan** [comment]
Pull request:
https://github.com/communitybridge/easycla/pull/1069

**Comment by prasannamahajan** [comment]
Change needed : we also have query for sub projects if projectSFID is of the foundation type

**Comment by dealako** [comment]
Moved to the next sprint. Awaiting QA @nirupamav

**Comment by nirupamav** [comment]
@dealako @pranab-bajpai 
Could you please provide the list of events that are displayed in this section and the standard format of display for each event

**Comment by nirupamav** [comment]
**_Tested and observed below issues_**
1. 403 is returned for cla-manager-designee who has access to project but not foundation when events are fetched at foundation level
**Steps followed**
     - As company admin (Company: Black Duck Software, Inc.)Start CLA process for ATOM project under Open Mainframe Project
     - Identify user that has LFID (having just user role and not associated to any company) as company cla-manager-designee. From backend cla-manager-desingee role is assigned for the user with scope ATOM|Black Duck Software, Inc.
     - Now try to fetch events at foundation level. Observed 403 is returned

2. Always empty object is returned for the foundation even if events exists for projects
**Foundation Level**
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company/0014100000TdznTAAR/project/a0941000002wBymAAE/events
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/8a35e311-06b9-45ae-b12b-83324e6f913d)

**Project Level**
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company/0014100000TdznTAAR/project/a092M00001IfR9lQAF/events
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/93528bfc-ee25-4ca2-8181-7a786d3caaf7)

**Comment by prasannamahajan** [comment]
@nirupamav 
Can you test this again. 
I have provided cla-manager-designee permissions.
And this api got modified in https://app.zenhub.com/workspaces/easyclav2-5ed619832c71a855a76ef404/issues/communitybridge/easycla/1267

**Comment by nirupamav** [comment]
**Observed that data is fetched in the response now. But I will be testing it during end-end flow testing when project console and contributor console is ready to make sure all events are fetched**

**Comment by nirupamav** [comment]
**_Tested and observed below issues
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/events/foundation/a0941000002wBzCAAU_**

**1. When CLA is signed by Signatory still the even is logged as EmployeeSignatureSigned**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/59dbba78-6c0c-43df-a138-88b24bc7b9d1)

**2. Company name is undefined for event when Individual Contributor signs ICLA for the project**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/703bbe82-f23b-4b21-8883-49010fc97dda)

**3. User None is displayed for both Individual and Employee signature events**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/e5a268fc-6211-4918-b469-ba15689ba3a9)

**4. CLA group id is displayed in EventData when approval list is added or removed**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a5c02d8a-abaf-4512-a3ff-a81622fd2a6d)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/a0a560ee-4598-4375-acdc-747b25a13f37)

**5. None in displayed in the user association event when corporate contributor(who has not raised PR for the project) is added to approval list, and corporate contributor created PR, completed the CLA process to get acknowledged (This scenario is when corporate contributor need not sign ICLA)** 
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/af7c3cbb-68da-42b9-9c3b-c3ce03f5c265)

**Comment by prasannamahajan** [comment]
@dealako @nirupamav Issues raised in this ticket are not related to this api 
but it is related to event data.

**Comment by dealako** [comment]
Resolved these issues during a stakeholder review meeting. The next phase will cleanup the summary data to make it more english-sentence-like.
