### ISSUE TITLE
CLA Statistics for my organization

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#931]
##Summary
Any user associated with a company will be taken to this page after they switch to member console, select foundation from left navigation and EasyCLA from top navigation.

Here is the link to [wireframe ](https://wireframepro.mockflow.com/view/corporate-console#/page/D702f061837fbb5ff5b4911bbf7149bfd)for the foundation page for EasyCLA.

![image](https://user-images.githubusercontent.com/57362064/79611946-4e5d4400-80c1-11ea-95ae-60b4690f29ac.png)

Step 5 in PRD https://confluence.linuxfoundation.org/display/PROD/Foundation+Dashboard+for+EasyCLA

**This table shows the CLA Statistics for my organization for different projects in this foundation.** Project name is shown with that project's icon.

It shows number of CLA Managers and number of approved contributors for different projects in this foundation.
Need to aggregate the CLA Group level data so that we can display project level data.

**NOTE :**

**If the user's company has not got any signed CLAs that fall under this foundation then this table display is empty. Data in this table is sorted alphabetically A→Z by Project column.**

##Acceptance Criteria
- [ ] Design Changes Required ?--> Not Applicable (N/A)   
- [ ] Unit Testing Complete 
    - [ ] Unit Testing complete for backend API
    - [ ] Unit  complete for UI
- [ ] Functional Testing Complete 
    - [ ] Functional Testing complete for backend API
    - [ ] Functional Testing complete for UI
- [ ] Integration Testing Complete 
    - [ ] Integration Testing complete for backend API and UI
    - [ ] Integration Testing complete end to end dev deployment
- [ ] Documentation Updated 
- [ ] Any Open Sev. 1 or Sev 2 bug(s)

**Comment by prasannamahajan** [comment]
Pull Request:
https://github.com/communitybridge/easycla/pull/1069

**Comment by prasannamahajan** [comment]
Changes: Need to aggregate the CLA Group level data so that we can display project level data.

**Comment by vinod-kadam** [comment]
As updated by David and Pranab this can be closed.
