### ISSUE TITLE
Minicard view of projects with cla enabled within the foundation

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#932]
## Summary
Any user associated with a company will be taken to this page after they switch to member console, select foundation from left navigation and EasyCLA from top navigation.

Here is the link to [wireframe ](https://wireframepro.mockflow.com/view/corporate-console#/page/D702f061837fbb5ff5b4911bbf7149bfd)for the foundation page for EasyCLA.

![image](https://user-images.githubusercontent.com/57362064/79612097-9b411a80-80c1-11ea-9d9c-d9a6d80e3d59.png)

Step 6 in PRD https://confluence.linuxfoundation.org/display/PROD/Foundation+Dashboard+for+EasyCLA

This is a mini card view of the projects that have CLA enabled and that are part of this foundation. 

These mini cards are clickable and when user clicks on view details they will be taken to the EasyCLA project page. 

## Acceptance Criteria
- [ ] Design Changes Required ?--> Not Applicable (N/A)   
- [ ] Unit Testing Complete 
    - [ ] Unit Testing complete for backend API
    - [ ] Unit Testing complete for UI
- [ ] Functional Testing Complete 
    - [ ] Functional Testing complete for backend API
    - [ ] Functional Testing complete for UI
- [ ] Integration Testing Complete 
    - [ ] Integration Testing complete for backend API and UI
    - [ ] Integration Testing complete end to end dev deployment
- [ ] Documentation Updated 
- [ ] Any Open Sev. 1 or Sev 2 bug(s)

**Comment by nirupamav** [comment]
@wanyaland 
Could you please provide the API endpoint to test this user story

**Comment by wanyaland** [comment]
@nirupamav . 
Endpoint: https://api-gw.dev.platform.linuxfoundation.org/v4/project/enabled/{externalID}

**Comment by nirupamav** [comment]
TestPlan https://confluence.linuxfoundation.org/display/PROD/EasyCLA-CLA+Enabled+Projects
**Observed below issues**
1. Projects returned are not sorted by project name
2. 200 response code with projects as null is returned for user with project-manager/super-admin role who does not have access to the externalId. 403 should be returned as the user does not have access to the project
**Also observed that not able to assign project to super-admin in IAM. So what is the behavior for super-admin**
3. 200 response code with projects is returned for user with project-manager role who does not have access to the externalId. For e.g nirupamav does not have access to Tungsten Fabric but able to get the projects
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/project/enabled/a092M00001F1Yv4QAF
4. projectCorporateDocuments/projectIndividualDocuments data is returned as null even if data exists
for e.g. b15286dd-4b34-4bb7-a57d-543e9c4a4efc
![image](https://user-images.githubusercontent.com/60865903/81671252-6dec5000-9466-11ea-876d-e00f0912bc4a.png)
![image](https://user-images.githubusercontent.com/60865903/81671480-aab84700-9466-11ea-985b-109ec0483fad.png)
5. Response code when invalid externalId is provided #1036

**Comment by dealako** [comment]
@wanyaland 

Review @prasannamahajan example -> get active CLAs for companies in v2 (v2 company service).

Basically: get foundation/project ID -> go to the Platform Project Service -> query -> get back results.

If type == foundation, it will have a list (zero or more) projects - which includes the external project ID, take this and query EasyCLA CLA groups to check to see if this project has a CLA group or not. If exists, return the results from the project service (not EasyCLA service - we are only checking to see if it exists or not).

For ACS-CLI config, review Pranab's permissions table: https://confluence.linuxfoundation.org/display/PROD/EasyCLA+PRD+for+Version+2, make sure the endpoint is supported with the correct roles.

**Comment by nirupamav** [comment]
**Tested for a0941000002wBz4AAE and observed below issues when user does not have access for a0941000002wBz4AAE in role scope and as well as in cla-dev-user-permissions**

**User I tested with has access to only a092M00001G3xhxQAB in cla-dev-user-permissions, and a0941000002wBz4AAE is not added in role scope**
**_Endpoint:_** https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/project/enabled/a0941000002wBz4AAE
Same issue observed for other roles cla-signatory, cla-manager, company-admin, company-owner, company-alternate-owner, lf-admin, lf-legal
|Role|Scope|TestData|Actual Response|Expected Response|Execution Status|
|----------------|----------------|-----------------|----------------|----------------|----------------|
|project-manager|Community|N/A|200 and returned only Thanos project with project sf_id=a092M00001IfVmKQAV|403/401|Failed|
|project-manager|Organization|Hewlett Packard Enterprise|200 and returned only Thanos project with project sf_id=a092M00001IfVmKQAV|403/401|Failed|
|project-manager|Project|Kinetic Open Storage Project|200 and returned only Thanos project with project sf_id=a092M00001IfVmKQAV|403/401|Failed|
|project-manager|Project-Organization|Academy Software Foundation-Bakbone |200 and returned only Thanos project with project sf_id=a092M00001IfVmKQAV |403/401|Failed|

**Comment by nirupamav** [comment]
**Below issues are still reproducible. Also could you please share the ACS policies for the endpoint so that I can test for different roles**
1. Earlier when projectsdfcid was not provided in endpoint 400 was returned but now 403 is returned
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/project/enabled/
2. Earlier 200 with empty set was returned when invalid projectsdfcid is provided. Now 500 is returned
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/project/enabled/a0941000002wBz4AA8

**Comment by nirupamav** [comment]
Verified that the issue is fixed. Issue1 mentioned above is as expected. 200 with empty list is returned for invalid SFID
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/fb460967-a846-4720-bf1e-fee848839252)
