### ISSUE TITLE
CLA Insights for CLA Foundation Page

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#934]
## Summary
Any user associated with a company will be taken to this page after they switch to member console, select foundation from left navigation and EasyCLA from top navigation.

Here is the link to [wireframe ](https://wireframepro.mockflow.com/view/corporate-console#/page/D702f061837fbb5ff5b4911bbf7149bfd)for the foundation page for EasyCLA.
![image](https://user-images.githubusercontent.com/57362064/79700994-2c012d00-825f-11ea-8502-114678019258.png)

Step 1 in PRD https://confluence.linuxfoundation.org/display/PROD/Foundation+Dashboard+for+EasyCLA

Need EasyCLA API that will get the statistics for this section. This for overall EasyCLA.

**Moving from left to right. This data will be provided by this backend API -  https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/metrics/total-count**

Number of Projects where EasyCLA is enforced. This is the "projectsCount": 193,
Number of CLA Signed. This is the total number of ICLA (Individual CLA) + CCLA (Corporate CLA) signed by companies without counting the whitelisted contributors. This is the total of "companiesProjectContributionCount": 603 +  "individualContributorsCount": 8423,
Total number of Individual Contributors and total number of Corporate Contributors including whitelisted contributors. This value corresponds to "Contributors Count" in API.  This is "contributorsCount": 10027,
Number of GitHub and Gerrit repositories on which EasyCLA is enforced. This is  "repositoriesCount": 43 in the API response

NOTE :

CLA Highlights for the foundation are always displayed. It doesn't matter if the user's company has a signed CLA for this foundation or for a project within this foundation.
##Acceptance Criteria
- [ ] Design Changes Required ?--> Not Applicable (N/A)   
- [ ] Unit Testing Complete 
    - [ ] Unit Testing complete for backend API
    - [ ] Unit Testing complete for UI
- [ ] Functional Testing Complete 
    - [ ] Functional Testing complete for backend API
    - [ ] Functional Testing complete for UI
- [ ] Integration Testing Complete 
    - [ ] Integration Testing complete for backend API and UI
    - [ ] Integration Testing complete end to end dev deployment
- [ ] Documentation Updated 
- [ ] Any Open Sev. 1 or Sev 2 bug(s)

**Comment by dealako** [comment]
Moved to the next sprint. Awaiting QA @nirupamav

**Comment by nirupamav** [comment]
@dealako 
The end point was tested in April in https://github.com/communitybridge/easycla/issues/624
Are there any changes now to endpoint? if so can you please let me know the changes so that I can test accordingly

**Comment by dealako** [comment]
Reviewed by QA - closing issue.
