### ISSUE TITLE
CLA Managers for my organzation for project cla page 

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#936]
##Summary
Any user associated with a company will be taken to this page after they switch to member console, select project from left navigation and EasyCLA from top navigation.

Here is the link to [wireframe ](https://wireframepro.mockflow.com/view/corporate-console#/page/Dfbd923b389bffae1192a3a2ca50c3faa)for the project page for EasyCLA.
![image](https://user-images.githubusercontent.com/57362064/79701375-2fe27e80-8262-11ea-97af-ad099ff24c3e.png)

Step 3 in PRD 
https://confluence.linuxfoundation.org/display/PROD/Project+Dashboard+for+EasyCLA

**CLA Managers From My Organization will list information about CLA Managers from user's company.** The table displays following columns:

**Name** i.e. the CLA Manager name.
**Email Address** of the CLA Manager.
**Approved on** i.e. the date they were added as CLA Manager. 
**Project or Foundation name** with project or foundation's icon.
The information for this table will be provided by EasyCLA API

Manage column 
![image](https://user-images.githubusercontent.com/57362064/79701415-8e0f6180-8262-11ea-85d8-9545456e5cec.png)
allows the editing of CLA Manager information and delete of CLA Manager record. 
![image](https://user-images.githubusercontent.com/57362064/79701429-aa130300-8262-11ea-8cc5-e8e217d1e4a4.png)
Button is explained in step 3.1 of the PRD

**NOTE :**

If the user's company has not got any signed CLAs OR any CLA Managers that fall under this foundation then this table display is empty.
There is no pagination on this table, all the values will be displayed at once.

##Acceptance Criteria
- [ ] Design Changes Required ?--> Not Applicable (N/A)   
- [ ] Unit Testing Complete 
    - [ ] Unit Testing complete for backend API
    - [ ] Unit Testing complete for UI
- [ ] Functional Testing Complete 
    - [ ] Functional Testing complete for backend API
    - [ ] Functional Testing complete for UI
- [ ] Integration Testing Complete 
    - [ ] Integration Testing complete for backend API and UI
    - [ ] Integration Testing complete end to end dev deployment
- [ ] Documentation Updated 
- [ ] Any Open Sev. 1 bug(s)

**Comment by nirupamav** [comment]
**Performed testing for happy path and happy path is working as expected. Testing is Inprogress for other scenarios**
At Project Level CLA Managers of only the project are fetched
**Test Data used**
**_Role_** cla-manager
**_Scope_**
Cloud Native Computing Foundation|Bakbone

**Endpoint**
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/company/0014100000Te1DWAAZ/project/a092M00001IV4PgQAL/cla-managers

**_Response_**
{
    "list": [
        {
            "approved_on": "2020-05-29T14:17:46.654807+0000",
            "cla_group_name": "BrigadeCLAGroup",
            "email": "nirupamav+clamanager10@proximabiz.com",
            "lf_username": "nirupamavclamanager10",
            "logo_url": "",
            "name": "nirupamav clamanager10",
            "project_id": "3564e0ad-5da9-4164-a158-1234a9845f75",
            "project_name": "Brigade",
            "project_sfid": "a092M00001IV4PgQAL",
            "user_sfid": "00Q1700000BhhoZEAR"
        },
        {
            "approved_on": "2020-05-29T14:17:46.654807+0000",
            "cla_group_name": "BrigadeCLAGroup",
            "email": "nirupamav+clamanger2@proximabiz.com",
            "lf_username": "clamanager2",
            "logo_url": "",
            "name": "niupamav clamanager2",
            "project_id": "3564e0ad-5da9-4164-a158-1234a9845f75",
            "project_name": "Brigade",
            "project_sfid": "a092M00001IV4PgQAL",
            "user_sfid": "00Q1700000BhPmBEAV"
        }
    ]
}

**Comment by prasannamahajan** [comment]
added projectSFID as input parameter
API: [https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/getCompanyProjectClaManagers](url)

Moving ticket to "Ready for review" state

**Comment by nirupamav** [comment]
Testing is In Progress in #929 as API endpoint is same

**Comment by nirupamav** [comment]
Testing completed in #929

**Comment by dealako** [comment]
Closing issue since testing is complete.
