### ISSUE TITLE
Approved List of Contributors From My Organization in Project EasyCLA page

### ISSUE THREAD

**Issue by pranab-bajpai** [communitybridge/easycla#938]
## Summary
Any user associated with a company will be taken to this page after they switch to member console, select project from left navigation and EasyCLA from top navigation.

Here is the link to [wireframe ](https://wireframepro.mockflow.com/view/corporate-console#/page/Dfbd923b389bffae1192a3a2ca50c3faa)for the project page for EasyCLA.

![image](https://user-images.githubusercontent.com/57362064/79701890-54405a00-8266-11ea-9152-8bb27681c15c.png)

Step 4 in PRD 
https://confluence.linuxfoundation.org/display/PROD/Project+Dashboard+for+EasyCLA

**Approved List of Contributors From My Organization will show the CLAs signed by user's company. The table displays following columns:**

**Approved List** is the emaild or GitHub userid or GitHub Organization or Domain name that is in approved list.
**Coverage Type** explains the type of approved list in column 1.
**Added on** i.e. date it was added to approved list.
**Manage** allows you to edit the approved list or delete it. There is no confirmation dialog box for editing or deleting a contributor. **Only users who have CLA Manager permission for this project should be shown this manage option**
The information for this table will be provided by EasyCLA API

NOTE :

If the user's company has not got any signed CLAs that fall under this foundation then this table display is empty.
There is no pagination on this table, all the values will be displayed at once

## Acceptance Criteria
- [ ] Design Changes Required ?--> Not Applicable (N/A)   
- [ ] Unit Testing Complete 
    - [ ] Unit Testing complete for backend API
    - [ ] Unit Testing complete for UI
- [x] Functional Testing Complete 
    - [ ] Functional Testing complete for backend API
    - [ ] Functional Testing complete for UI
- [ ] Integration Testing Complete 
    - [ ] Integration Testing complete for backend API and UI
    - [ ] Integration Testing complete end to end dev deployment
- [ ] Documentation Updated 
- [ ] Any Open Sev. 1 bug(s)

**Comment by dealako** [comment]
@nirupamav I have created a few functional tests for this one. We can easily expend this set of tests to be more comprehensive.  Please review: https://github.com/communitybridge/easycla/blob/master/cla-backend-go/cmd/functional_tests/signatures/signatures.go#L199  Let's discuss more on Monday.

**Comment by nirupamav** [comment]
@pranab-bajpai @dealako 
Could you please clarify below queries
1. As per the PRD, Name and Added On are listed. But in our response we are not getting name and added on. As per my understanding, the contributor might not be in our user system to fetch from user service. If my understanding is wrong LFX team fetch the data from user service
2. As per PRD, CLA Manager and Non-CLA Manager can view data but only CLA Manager can edit the data. 
I tested it with different roles and observed that except for cla-manager and lf-operations roles, 401 is returned for other roles
3. As per PRD, CLA-Manager who has access to the project of the organization can manage the list. As of now the API returns 401 if the scope is project|Organization and returns data with 200 when role scope is Organization. Does this mean that if the user is CLA Manager for the Organization, he can manage all projects of the organization

**Comment by dealako** [comment]
For #1 defined above, for now, we won't load the user's name if they are in the email field. We would have to search around for the user's name - not stored in the signature, most-likely not in the EasyCLA user's table, and probably not in the Platform User service. Most of these users will be GH users with no relationship with CommunityBridge other than pass/fail of the EasyCLA gating.

**Comment by dealako** [comment]
For #2 - will review the permissions. For now, it's locked down to the CLA Manager and admins.

**Comment by nirupamav** [comment]
As Endpoint needs modification reopening the ticket

**Comment by vinod-kadam** [comment]
@prasannamahajan what is the latest update on this one? If it is work in progress then please provide the ETA.

**Comment by prasannamahajan** [comment]
API : [https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/api-docs#operation/getProjectCompanySignatures](url)

Moving ticket in "Ready for review" state

**Comment by nirupamav** [comment]
**Performed testing for happy path and happy path is working as expected. However I have query regarding CLA group and if @pranab-bajpai clarifies that CLA group is required then endpoint may require changes else if @pranab-bajpai confirms that current behavior is as expected then no change is required for the endpoint.
Testing is Inprogress for other scenarios**
At Project Level CLA Managers of only the project are fetched
**Test Data used**
**_Role_** cla-manager
**_Scope_**
Cloud Native Computing Foundation|Bakbone

**_Endpoint_**
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/signatures/project/a092M00001IV45HQAT/company/0014100000Te1DWAAZ

**_Response_**
{
    "resultCount": 2,
    "signatures": [
        {
            "companyName": "Bakbone",
            "created": "2020-06-01T10:11:39.485378+0000",
            "domainApprovalList": [
                "proximabiz.com"
            ],
            "emailApprovalList": [
                "nirupamav+mentee12341@proximabiz.com"
            ],
            "githubOrgApprovalList": [
                "niruorg"
            ],
            "githubUsernameApprovalList": [
                "nirupamav"
            ],
            "modified": "2020-06-01T10:11:39.485385+0000",
            "projectID": "3d354e3d-1561-49bf-a66c-ffa31392a018",
            "signatureACL": [
                {
                    "dateCreated": "2020-05-18T09:25:29Z",
                    "dateModified": "2020-06-01T07:27:43Z",
                    "emails": null,
                    "lfEmail": "nirupamav+clamanager10@proximabiz.com",
                    "lfUsername": "nirupamavclamanager10",
                    "userID": "83b550d0-98e9-11ea-b69b-fa63295d7f2d",
                    "username": "nirupamav clamanager10",
                    "version": "v1"
                }
            ],
            "signatureApproved": true,
            "signatureCreated": "2020-06-01T10:11:39.485378+0000",
            "signatureID": "07f3dc1b-56b2-46a7-bc14-62d5b344e0b3",
            "signatureMajorVersion": "2",
            "signatureMinorVersion": "0",
            "signatureModified": "2020-06-01T10:11:39.485385+0000",
            "signatureReferenceID": "0014100000Te1DWAAZ",
            "signatureReferenceName": "Bakbone",
            "signatureReferenceNameLower": "bakbone",
            "signatureReferenceType": "company",
            "signatureSigned": true,
            "signatureType": "ccla",
            "version": "2.0"
        },
        {
            "companyName": "Bakbone",
            "created": "2020-06-01T10:11:39.485378+0000",
            "domainApprovalList": null,
            "emailApprovalList": null,
            "githubOrgApprovalList": null,
            "githubUsernameApprovalList": null,
            "modified": "2020-06-01T10:11:39.485385+0000",
            "projectID": "2e3f95be-962e-4eb0-90d6-48cce5a0218f",
            "signatureACL": [
                {
                    "dateCreated": "2020-05-18T09:25:29Z",
                    "dateModified": "2020-06-01T07:27:43Z",
                    "emails": null,
                    "lfEmail": "nirupamav+clamanager10@proximabiz.com",
                    "lfUsername": "nirupamavclamanager10",
                    "userID": "83b550d0-98e9-11ea-b69b-fa63295d7f2d",
                    "username": "nirupamav clamanager10",
                    "version": "v1"
                }
            ],
            "signatureApproved": true,
            "signatureCreated": "2020-06-01T10:11:39.485378+0000",
            "signatureID": "732730d0-ddb5-43f6-bfb6-8fbdcab63772",
            "signatureMajorVersion": "2",
            "signatureMinorVersion": "0",
            "signatureModified": "2020-06-01T10:11:39.485385+0000",
            "signatureReferenceID": "0014100000Te1DWAAZ",
            "signatureReferenceName": "Bakbone",
            "signatureReferenceNameLower": "bakbone",
            "signatureReferenceType": "company",
            "signatureSigned": true,
            "signatureType": "ccla",
            "version": "2.0"
        }
    ],
    "totalCount": 0
}

**Comment by vinod-kadam** [comment]
Prasanna informed on lfx-dev slack channel that this api is ready for  consumption by lfx team.

**Comment by nirupamav** [comment]
**Tested and have below queries and issues**
1. When invalid projectsfId is provided 404 should be returned, but 200 is returned with below response
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/signatures/project/a092M00001IV4PgQLA/company/0014100000Te1DWAAZ
![image](https://user-images.githubusercontent.com/60865903/83742207-c59d6600-a676-11ea-9c22-5f77cc641bc5.png)
2. When invalid companysfId is provided 404 should be returned, but 403 is returned with below response
https://api-gw.dev.platform.linuxfoundation.org/cla-service/v4/signatures/project/a092M00001IV45HQAT/company/a092M00001IV4PgQAL
![image](https://user-images.githubusercontent.com/60865903/83742532-23ca4900-a677-11ea-8f84-3e798b2076b9.png)
3. When projectsfid/companysfid is not provided 400 should be returned, but 403 is returned
4. In the response, null is returned for emails in signatureACL object even though there is a secondary email for the user
![image](https://user-images.githubusercontent.com/60865903/83748395-bf5fb780-a67f-11ea-823d-fb4833d4add4.png)
5. As per the  the response model, git hub details should be displayed in the signatureACL object.  But we do not store the github details of the user in cla_dev_users so should those details be in the response model
6. As per the  the response model, admin and userExternalID details should be displayed in the signatureACL object.  For the CLA Manager admin value exists in cla_dev_users table but is not returned in response. Should sfid for the CLA Manager be returned for userExternalID?
7. In UI added on is displayed for the approved list and the list is sorted by Added on Date. But API does not return added on date for each approved list

**Comment by nirupamav** [comment]
@pranab-bajpai 
I have completed testing. Could you please review test plan and let me know if I missed to test any scenarios
Failed test cases are due to tickets #1173, #1036
I test case is blocked due to query related to the sort order of the data which I have posted in PRD. Based on the clarification if required will log a separate ticket for sort order.

**_Test Plan_**  https://confluence.linuxfoundation.org/display/PROD/getProjectCompanySignatures

![image](https://user-images.githubusercontent.com/60865903/83790317-9f4aeb00-a6b5-11ea-9344-adb190fe3d8e.png)

**Comment by dealako** [comment]
1. Working on fix for this, see: https://github.com/communitybridge/easycla/pull/1182
2. For invalid company SFID - you probably don't have permissions or it, so the permissions check is caught first
3. When projectsfid/companysfid is not provided 400 should be returned, but 403 is returned -> permissions are checked and caught first, so 403 is correct.  This is the desired behavior.
4. This is what we have in the DB. We can raise a separate ticket to keep SF and EasyCLA user emails in sync.

Added logic to show all validation errors - not just the first.

**Comment by dealako** [comment]
Addressed issues - subsequent tickets can be opened if error message need updates. Core functionality works.
