### ISSUE TITLE
Corporate Console - Not able to open Manage Approved List page and hence blocked with approved list management

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#940]
## Background
1. Launch Corporate Console
2. Login
3. Click on the company that has signed CLA
4. Click on MANAGE APPROVED LIST
5. Observed that no action was performed and error was displayed in console
![image](https://user-images.githubusercontent.com/60865903/79722941-93bc8400-8302-11ea-93e1-b23d29b77071.png)

**Comment by nirupamav** [comment]
**Verified and observed that the issue is fixed**
![image](https://user-images.githubusercontent.com/60865903/79828717-f1aea180-83be-11ea-9b52-31faad31ea18.png)

**Comment by amolsontakke3576** [comment]
@nirupamav Verified and works properly.

**Comment by nirupamav** [comment]
Verified that the issue is fixed
