### ISSUE TITLE
Corporate Console - User is not able to navigate back to Companies page when clicked on Back link from menu

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#941]
## Background
1. Launch Corporate Console
2. Login
3. Click on the company 
4. Click SIGN NEW CLA
5. Select Project and Click SUBMIT
6. Click YES
7. Click on Back link from menu
![image](https://user-images.githubusercontent.com/60865903/79742578-a80f7980-8320-11ea-9b08-be63c911c3b3.png)

8.Now when clicked on Menu bar to select option to navigate to homepage or previous page, no action is performed. User has to refresh page to navigate back Company details page.
![image](https://user-images.githubusercontent.com/60865903/79742829-0e949780-8321-11ea-865b-37d21153f50e.png)

**Comment by nirupamav** [comment]
**_Verified that the issue is fixed. Back link is displayed and when clicked in back link CLA Manager is navigated to Company Details page_**
![image](https://user-images.githubusercontent.com/60865903/80194700-66404500-8638-11ea-8163-a96ffe79dc3a.png)

**Comment by amolsontakke3576** [comment]
@nirupamav Tested and works fine.

**Comment by nirupamav** [comment]
Issue was already verified and hence moving the ticket to QA Done
