### ISSUE TITLE
Mulitple windows/tabs are opened during CLA signing/Contribution request process

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#942]
## Background

**_CORPORATE CONSOLE_**

1. Launch Corporate Console
2. Login
3. Click on the company
4. Click SIGN NEW CLA
5. Select Project and Click SUBMIT
6. Click YES
7. Click OPEN CLA
**8. Observed that docusign is opened in new tab and after signing process is complete, user is redirected to corporate console in the tab where docusign was opened and hence now 2 tabs are opened. After docusign process is complete, docusign should be closed and user should be navigated back to company details page in the tab where Open CLA button is clicked**

**_CONTRIBUTOR CONSOLE - Individual_**
1. Launch github repository
2. Login as individual contributor
3. Update any file and create PR
4. Click on CLA NOT SIGNED
5. Click on Individual in Contributor Console
6. Click OPEN CLA
**7. Observed that docusign is opened in new tab and after signing process is complete, user is redirected to github in the tab where docusign was opened and hence now 2 tabs are opened. After docusign process is complete, docusign should be closed and user should be navigated back to github in the tab where Open CLA button is clicked**

**_CONTRIBUTOR CONSOLE - Corporate_**
1. Launch github repository
2. Login as individual contributor
3. Update any file and create PR
4. Click on CLA NOT SIGNED
5. Click on Corporate in Contributor console
6. Select Company for which the contributor is already whitelisted
7. Acknowledge and Click on Continue
8. Button to return to repo is displayed.
9. When clicked on the button, github is opened in new tab. How many ever times I click on the button, that many new tabs are displayed for github. Instead user should be redirected to github in same tab

**Comment by nirupamav** [comment]
**_Verified that Issue1 and Issue2 are fixed but Issue 3 is still reproducible and hence reopening the ticket_**
![image](https://user-images.githubusercontent.com/60865903/80345907-8fa2e000-8887-11ea-8070-b2d805095dbf.png)


![image](https://user-images.githubusercontent.com/60865903/80345887-84e84b00-8887-11ea-833c-6c81345d5868.png)

**Comment by nirupamav** [comment]
**Verified and observed that all the three issues are fixed**

**Comment by amolsontakke3576** [comment]
@nirupamav Verified and works fine.

**Comment by nirupamav** [comment]
Issue was already verified and hence moving the ticket to QA Done
