### ISSUE TITLE
Any github user is able to sign the CLA document with the docusign link

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#944]
## Background

1. Launch github repository
2. Login as individual contributor
3. Update file and create pr
4. Click on CLA NOT SIGNED
5. Click on Individual
6. Click on OPEN CLA
7. Complete docu sign process
8. User is redirected to github and CLA checks passed
9. Now copy the CLA NOT SIGNED link from the email sent for failed CLA check
![image](https://user-images.githubusercontent.com/60865903/79747182-e446d800-8328-11ea-842e-34bc895ca04b.png)
10. Open that link in any browser
11. Login as different github user
12. User is navigated to Contributor Console and able to click on Individual and complete the docusign process

**Comment by dealako** [comment]
Given that this is a self-help system, this is the desired behavior.  Any user can sign a given CLA - no restrictions are required by the stakeholders. Closing this issue.
