### ISSUE TITLE
Observed issues with docusign when docusign session expires or decline/FinishLater selectec from other actions

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#945]
## Background
**Issue1**
1. Launch github repository
2. Login as individual contributor
3. Update file and create pr
4. Click on CLA NOT SIGNED
5. Click on Individual
6. Click on OPEN CLA
7. Keep the document open for around 45mins
8. docusign session expires with dialogue box to click continue
9. When clicked on continue observed below error

![image](https://user-images.githubusercontent.com/60865903/79754867-ccc21c00-8335-11ea-9c5b-442edeeb4a89.png)

10. When clicked on CLA NOT SIGNED again from github and clicked on Individual and OPEN CLA from contributor console observed below error
**NOTE: For this user for another github org repo I had declined the signature from docusign by clicking in Other Actions. Not sure if below error was because of this or due to session expiration. However when I tried after 0.5 hour I was able to proceed with docusign**
![image](https://user-images.githubusercontent.com/60865903/79754924-e2374600-8335-11ea-9f4a-42d05b7bf8d6.png)

**Issue2**
When user selects Finish Later from docusign->Other options user is redirected to github. When user tries to sign the document after sometime below error is displayed and user is not able to sign cla
![image](https://user-images.githubusercontent.com/60865903/79755245-72758b00-8336-11ea-8a12-3b8d987f4ae0.png)

**Comment by dealako** [comment]
@nirupamav I have fixed this for ICLA - both v1 and v2 Contributor Console.

@WillsonHG have you tested this recently? I know you were testing CCLAs (today).

**Comment by dealako** [comment]
API resolved, but v1 UI needs to be updated so that previously attempted DocuSign flows can resume and the signing process can resume.

**Comment by nirupamav** [comment]
**Tested and observed that for CCLA in V1 corporate console when session expires CLA Manager is redirected to V1 Corporate Console and project does not appear in the projects list to try to sign again. Same issue observed when docusing is closed wihout signing**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/dee97a6c-c9d7-4f4d-b649-ebeb0fb3a27f)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/9ee05124-e2d8-4176-8b89-4cd505b870ca)

**_Verified that below flows are working as expected_**

| Docusign Flow  | EasyCLA Version | CLA Type | Actual behavior |
| ------------- | ------------- | ------------- | ------------- |
| Session Expire  | V1 | ICLA | Contributor is redirected to github when session expires |
| Other Actions -> Finish Later  | V1 | ICLA | Contributor is able to open the docusign again |
| Other Actions -> Decline To Sign  | V1 | ICLA | Contributor is able to open the docusign again |
| Close the docusign without signing  | V1 | ICLA |  Contributor is able to open the docusign again |
| Session Expire  | V2 | ICLA | Contributor is redirected to github when session expires |
| Other Actions -> Finish Later  | V2 | ICLA | Contributor is able to open the docusign again |
| Other Actions -> Decline To Sign  | V2 | ICLA | Contributor is able to open the docusign again |
| Close the docusign without signing  | V2 | ICLA | Contributor is able to open the docusign again |

**Comment by dealako** [comment]
[Created PR](https://github.com/communitybridge/easycla/pull/1405) to resolve CCLA sign/pause/sign flow.

**Comment by dealako** [comment]
@nirupamav @WillsonHG Merged PR - ready for re-test on the CCLA flow.

**Comment by nirupamav** [comment]
Verified below scenarios for CCLA in V1 and observed that the issue is fixed

| Docusign Flow  | EasyCLA Version | CLA Type | Actual behavior |
| ------------- | ------------- | ------------- | ------------- |
| Session Expire | V1 | CCLA | CLA Manger is redirected to Corporate Console and is able to fetch the project  to attempt signing the CCLA |
| Other Actions -> Finish Later | V1 | CCLA | CLA Manger is redirected to Corporate Console and is able to fetch the project  to attempt signing the CCLA |
| Other Actions -> Decline To Sign | V1 | CCLA | CLA Manger is redirected to Corporate Console and is able to fetch the project  to attempt signing the CCLA |
| Close the docusign without signing | V1 | CCLA |  CLA Manger is redirected to Corporate Console and is able to fetch the project  to attempt signing the CCLA |
| Click Back link in the screen when template is generated and OpenCLA button is enabled to navigate back to corporate console | V1 | CCLA |  CLA Manger is redirected to Corporate Console and is able to fetch the project to attempt signing the CCLA |
| After attempting all abve flows try to sign CCLA | V1 | CCLA |  CLA Manger is able to sign CCLA and view the project in the Signed CLA's table |
