### ISSUE TITLE
Logged in CLA Manager is still displayed as not signed in MANAGE APPROVED LIST

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#952]
## Background
**_This was working fine earlier_**
1. Launch Corporate Console
2. Login
3. Click on the company that has signed cla
4. Click on MANAGE APPROVED LIST
5. Add clamanager that exists in lf dev domain but has not signed in to easycla application
6. Login as added cla manager to Corporate console
7. Observed that even after the added cla manager has logged into easyc cla application, cla manager is displayed as user not signed 
![image](https://user-images.githubusercontent.com/60865903/79841940-c1263200-83d5-11ea-858f-2030b7990627.png)

![image](https://user-images.githubusercontent.com/60865903/79841961-cbe0c700-83d5-11ea-87ec-9fcb799073c7.png)

![image](https://user-images.githubusercontent.com/60865903/79842071-fb8fcf00-83d5-11ea-933b-a9a35a05a77c.png)

**Comment by dealako** [comment]
@amolsontakke3576 please review and investigate.

**Comment by amolsontakke3576** [comment]
@dealako It is working fine the IFID mentioned in screenshot. Even I had tested on different ID's and looks like no issue 
@nirupamav Can you confirm again ?

**Comment by nirupamav** [comment]
@amolsontakke3576 
Retested and observed that issue is fixed now.

**Comment by amolsontakke3576** [comment]
Verified and working fine now
