### ISSUE TITLE
Contributor Console - Error message is not displayed in the Request Access popup when company does not exist in the list

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#953]
## Background
1. Launch github repository (That is added to project that has both ccla and icla enabled)
2. Login as Contributor
3. Update file and create pr
4. Click on CLA NOT SIGNED
5. Click on Corporate
6. Click on COMPANY NOT IN LIST? CLICK HERE
7. Click NO
8. Observed that error message is not displayed when no data is entered
![image](https://user-images.githubusercontent.com/60865903/79856019-64cd0d80-83e9-11ea-8633-6f8a52bf71fe.png)

**Comment by nirupamav** [comment]
**_Verified below scenarios_**

1. When no data is entered SEND button is disabled
2. Initially when invalid data is entered observed error message
![image](https://user-images.githubusercontent.com/60865903/80068598-80592500-855d-11ea-89ea-b585d30506d2.png)

![image](https://user-images.githubusercontent.com/60865903/80068621-8e0eaa80-855d-11ea-9e8b-2744da9a072e.png)

![image](https://user-images.githubusercontent.com/60865903/80068638-9961d600-855d-11ea-92d3-a4964df8b85a.png)

3. Observed that error messages are cleared when valid data is entered
4. Enter all valid data and observed SEND button is enabled
5. Clear fields after SEND button is enabled and observed below error messages for the fields
![image](https://user-images.githubusercontent.com/60865903/80068351-1476bc80-855d-11ea-9420-ae8b3836a214.png)

![image](https://user-images.githubusercontent.com/60865903/80068377-248e9c00-855d-11ea-9f99-f6bb45b162fd.png)

**Comment by dealako** [comment]
Resolved - closing ticket.
