### ISSUE TITLE
Email - Contributor Console - ICLA - Document is not attached in email and also content is not formatted

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#963]
## Background
1. Launch github repository which has ICLA enabled
2. Login as contributor
3. Update any file and create PR
4. Click on CLA NOT SIGNED
5. Click on Individual
6. Click OPEN CLA and complete docusign process
7. Observed that the contributor received a notification. But as per description in email the signed document is not attached. Also Email content is not formatted. There is no greetings and signoffs in the email.
![image](https://user-images.githubusercontent.com/60865903/79973153-ab3b6e80-84b4-11ea-8642-7f8dc8c4c4a2.png)

**Comment by WillsonHG** [comment]
This is happening in production with ICLAs and with CCLAs

**Comment by dealako** [comment]
How is docusign sharing the signed documents when the Signatory signs a CCLA? Do they send an email with an attachment - or is it a link to the document (and will need to sign in to DocuSign to review?)?

**Comment by dealako** [comment]
Merged PR:
https://github.com/communitybridge/easycla/pull/1414
https://github.com/communitybridge/easycla/pull/1415

These provide an updated API to allow the user to fetch and download their ICLA document.

Updated email text/content to match EasyCLA system emails and to provide a link to download the PDF document.

**Comment by dealako** [comment]
![Screen Shot 2020-07-16 at 4.06.48 PM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/220b9991-9001-40b6-9862-69ae4bc1088b)

![Screen Shot 2020-07-16 at 4.10.47 PM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/ee241c71-416e-42d7-9142-a2d9dce4ea4e)

![Screen Shot 2020-07-16 at 4.10.56 PM.png](https://images.zenhubusercontent.com/5ed6694b9d49d1a6a85690e0/66383731-8366-4af6-aeae-4361f2bda124)

Works locally, but when I attempt to download via API-GW, the PDF seems to be base64 encoded.  Need to investigate the library we use for API-GW + Lambda request/response management.

**Comment by dealako** [comment]
Updated API-GW settings.
Ready for test @nirupamav

**Comment by nirupamav** [comment]
Testing blocked due to #1418

**Comment by nirupamav** [comment]
Tested V1 - ICLA and V2 - ICLA flows and observed that there is a link in the email to view signed document. However the document does not load when accessed from email. Tried in Firefox, Chrome and IE in Windows 10 
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/db485216-93d7-4ed1-a9b7-82d0b75e29cc)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/98f217be-3e31-4585-b7ea-f212a8e86b7b)

**Comment by dealako** [comment]
Deploying update/change which provides a direct S3 PDF link via API redirect with signed S3 document.

**Comment by dealako** [comment]
Ready for review @nirupamav

**Comment by nirupamav** [comment]
**_Observed CCLA document is not accessible from email notification sent from V2 flow_**
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/79c8f2c8-bc90-4165-b31e-3bb0cb98bea1)


**_Testing Status of other scenarios_**
| Scenario  | EasyCLA Version | Testing Status |
| ------------- | ------------- | ------------- |
| Individual Contributor - Signs ICLA document  | V1  | Passed |
| Corporate Contributor - Signs ICLA document  | V1  | Blocked due to #1424 |
| CLA Signatory - Signs CCLA document  | V1  | Blocked due to #1424 |
| Individual Contributor - Signs ICLA document  | V2  | Blocked due to #1244 |
| Corporate Contributor - Signs ICLA document  | V2  | Blocked due to #1448 |
| CLA Signatory - Signs CCLA document  | V2  | Failed |

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/196393ab-d7eb-4109-83da-a58e0ab02f79)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/50ebf25a-aee5-46ac-9554-055f9d53f1e2)

![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/9c50231c-d41d-492f-83c6-c22cee9c05cf)

**Comment by dealako** [comment]
Working for ICLA now.

Need to investigate CCLA by Signatory as a separate ticket.
