### ISSUE TITLE
Contributor Console - User is not able to search for companies when navigated to console from gerrit

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#973]
## Background
1. Launch the Gerrit Contributor Agreement Link for Corporate
2. User is redirected to Contributor Console
3. User is not able to search for companies and instead when clicked on areas on the top, the area selected as company and there is no option to type search criteria

![image](https://user-images.githubusercontent.com/60865903/80092873-29654700-8581-11ea-862f-a13dd5be0e73.png)

![image](https://user-images.githubusercontent.com/60865903/80092907-34b87280-8581-11ea-86bc-8ed03cadd740.png)

![image](https://user-images.githubusercontent.com/60865903/80092960-47cb4280-8581-11ea-9181-cfa35caa4837.png)

![image](https://user-images.githubusercontent.com/60865903/80092983-5580c800-8581-11ea-8a5a-962128315f59.png)

![image](https://user-images.githubusercontent.com/60865903/80093082-806b1c00-8581-11ea-915e-0de3c7dff84f.png)

![image](https://user-images.githubusercontent.com/60865903/80093107-8a8d1a80-8581-11ea-98a4-30b4357b93c5.png)

**Comment by dealako** [comment]
The old console is deprecated and removed.
