### ISSUE TITLE
Corporate Console - Open CLA button font has been changed and is not consistent with other pages

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#978]
## Background

1. Launch Corporate Console
2. Login as CLA Manager
3. Click on the company
4. Click on SIGN NEW CLA
5. Select Project
6. Click SUBMIT
7. Click YES
8. Observed that Open CLA button in font has been changed and is not consistent with OPEN CLA button in other pages
![image](https://user-images.githubusercontent.com/60865903/80183022-b3ff8200-8625-11ea-811a-3d1dfc9ac650.png)

**Comment by nirupamav** [comment]
**_Verified and observed that the issue is fixed_**
![image](https://user-images.githubusercontent.com/60865903/80563434-c94f2480-8a08-11ea-89a9-bc0734b09f4f.png)

**Comment by dealako** [comment]
The old console is deprecated and removed.
