### ISSUE TITLE
Corporate Console - CLA Manager is able to see all projects and REQUEST ACCESS status is displayed for the project When CLA Manager is added to a project 

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#980]
## Background
1. Login as nirupamavkrsna to corporate console
2. Click on Company **Notification Company**
3. Click on MANAGE APPROVED LIST for project **EmailNotificationTestProj**
4. Add CLA Manager nirupamavmentee6
![image](https://user-images.githubusercontent.com/60865903/80191771-d00a2000-8633-11ea-8b92-b63c9c0c7119.png)
5. Logout
6. Clear cache and Login as nirupamavmentee6 to corporate console
7. Click on Company **Notification Company**
**_Issue1_**
8. CLA Manager was added to only  **EmailNotificationTestProj** but all projects are displayed for the CLA Manager. However CLA Manager has read-only access for other projects
![image](https://user-images.githubusercontent.com/60865903/80192020-2e370300-8634-11ea-981a-8b47e8ed4f0f.png)

**_Issue2_**
9. Even if CLA Manager has access to project, REQUEST ACCESS status is displayed for the project and VIEW APPROVED LIST is displayed. However CLA Manager is able to edit data for the project
![image](https://user-images.githubusercontent.com/60865903/80192206-79511600-8634-11ea-81a9-ec633be2590a.png)

![image](https://user-images.githubusercontent.com/60865903/80192284-92f25d80-8634-11ea-912f-898a4a45b459.png)

**Comment by dealako** [comment]
The old v1 console is deprecated and removed.
