### ISSUE TITLE
CLA Manager has to refresh the page to view the companies when the CLA manager is logging into Easy CLA application for the first time

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#982]
## Background
1. Launch Corporate Console
2. Login as CLA Manager
3. Click on Company that has signed CLA
4. Click on MANAGE APPROVED LIST for a project
5. Add a CLA MANAGER that exists in lfx system but has never signed into to Corporate Console
![image](https://user-images.githubusercontent.com/60865903/80206556-24b89580-864a-11ea-8e99-df6e085859ed.png)

6. Now Login to Corporate Console as the added CLA Manager that has never signed in
7. Observed that Companies are not displayed
![image](https://user-images.githubusercontent.com/60865903/80206632-4c0f6280-864a-11ea-8acc-d8a3ce07a13f.png)

8. Refresh the page
9. CLA Manager is able to see companies
![image](https://user-images.githubusercontent.com/60865903/80206669-61848c80-864a-11ea-9e6c-f52d75eb06f2.png)

**Comment by amolsontakke3576** [comment]
@dealako @wanyaland @prasannamahajan 
When user login to system very first time below endpoint return 404. After refresh the page it will return the user. Can some debug this ?

Request URL: https://api.dev.lfcla.com/v3/users/username/test.lfpm
Request Method: GET
Status Code: 404

**Comment by dealako** [comment]
The old v1 console is deprecated and removed.
