### ISSUE TITLE
Project Console : ICLA template created even only CCLA is enabled while creating CLA group.

### ISSUE THREAD

**Issue by amolsontakke3576** [communitybridge/easycla#983]
## Summary
ICLA template automatically created even only CCLA is enabled while creating CLA group.
## Background

- Launch project Management Console
- Login as Project Manager
- Create a CLA group with only CCLA Enabled and generate pdf's for the project
- Select template and completed procedure.
- Now you can see CCLA has template assigned.
- Edit same CLA group and enabled ICLA.
- Attached template for ICLA.
- Click on view PDF icon.
- Two styles (Template) entries for ICLA. (PFA)

## Expected behavior

- If ICLA selected then only ICLA template will be created.
- If CCLA selected then only CCLA template will be created.
- If CCLA and ICLA selected then both the templates will be created.

## Screenshots

![Screenshot from 2020-04-24 17-16-28](https://user-images.githubusercontent.com/56335654/80210069-b75c3300-8650-11ea-9344-08331c80c2d9.png)

**Comment by nirupamav** [comment]
**_Verified below scenarios_**
1. **Only CCLA template is created when only CCLA is enabled**
![image](https://user-images.githubusercontent.com/60865903/80565656-a162bf80-8a0e-11ea-8167-f091287f7012.png)

![image](https://user-images.githubusercontent.com/60865903/80565678-b2133580-8a0e-11ea-8d2a-d4a2988b4f4e.png)

2. **Only ICLA template is created when only ICLA is enabled**
![image](https://user-images.githubusercontent.com/60865903/80565750-e8e94b80-8a0e-11ea-9ac0-b6eef780ce57.png)

![image](https://user-images.githubusercontent.com/60865903/80565777-f6063a80-8a0e-11ea-9a82-2c28a1c3747e.png)

3. **Both CCLA and ICLA templates are created when both ICLA and CCLA are enabled**
![image](https://user-images.githubusercontent.com/60865903/80565879-39f93f80-8a0f-11ea-8d5e-a5f2c09b3383.png)

![image](https://user-images.githubusercontent.com/60865903/80565901-467d9800-8a0f-11ea-9c32-9a4d6fd4e452.png)

**Comment by amolsontakke3576** [comment]
@nirupamav In this ticket we need to verify PDF history version.

**Comment by nirupamav** [comment]
@amolsontakke3576 
**_Verified below scenarios as per your suggestion. Please let me know if I missed to test any other scenarios_**
1. Create project with only CCLA enabled. Generate templates. Update project and enable ICLA. Generate template. Verified the PDF history for ICLA and also verified that CCLA is again generated and both ICLA and CCLA have new template generated time updated
![image](https://user-images.githubusercontent.com/60865903/80568535-d2de8980-8a14-11ea-8bab-caa4a9533e29.png)

![image](https://user-images.githubusercontent.com/60865903/80569005-9d866b80-8a15-11ea-9f1c-e8d3bdf22f83.png)

2. Create project with only ICLA enabled. Generate templates. Update project and enable CCLA. Generate template. Verified the PDF history for CCLA and also verified that ICLA is again generated and both ICLA and CCLA have new template generated time updated
![image](https://user-images.githubusercontent.com/60865903/80569862-61540a80-8a17-11ea-83f7-6ee967f8d7cc.png)

![image](https://user-images.githubusercontent.com/60865903/80571025-821d5f80-8a19-11ea-9f53-995d9117d2ca.png)

**Comment by nirupamav** [comment]
This was already tested and hence closing the ticket
