### ISSUE TITLE
Project Console - UI hangs with spinning icon when trying to edit CLA group with duplicate CLA group name

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#986]
## Background
1. Launch Project Management Console
2. Login
3. Click on the foundation
4. Click on Configuration icon for any cCLA group
5. Enter any existing CLA Group name
6. Click Save
7. UI hangs with spinning icon. However observed that API call fails with 409 which is as expected
![image](https://user-images.githubusercontent.com/60865903/80339715-de974800-887c-11ea-9190-5e488385f9f9.png)

![image](https://user-images.githubusercontent.com/60865903/80339777-0090ca80-887d-11ea-91a0-455c4b0b06a2.png)

**Comment by nirupamav** [comment]
**_Verified and observed that the issue is fixed_**
![image](https://user-images.githubusercontent.com/60865903/80563011-33ff6080-8a07-11ea-9c5c-614ff35f6b24.png)

**Comment by amolsontakke3576** [comment]
Verified and working fine

**Comment by dealako** [comment]
The old console is deprecated and removed.
