### ISSUE TITLE
Corporate Console - Wrong email sent when Employee is approved/declined for the project and email is not sent to github email id

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#987]
## Background
1. Launch github repository (company should have signed the project with this repository and project should be ccla enabled)
2. Login
3. Update any file and create PR
4. Click on CLA NOT SIGNED
5. Click on Corporate in Contributor console
6. Select Company and click SUBMIT
7. Enter all required details and click SEND
8. Launch Corporate Console
9. Login as CLA manager of the company that has signed the project with above github repository
10. Click on the company
11. Click MANAGE APPROVED LIST
12. Click ACCEPT
**_Issue1_**
13. Observed that Alert message is displayed 
![image](https://user-images.githubusercontent.com/60865903/80342696-37b5aa80-8882-11ea-812e-ad099ce60732.png)
14. Click ACCEPT
15. Observed that CLA Manager Access Approved email is sent instead of Employee approval email
![image](https://user-images.githubusercontent.com/60865903/80342947-aeeb3e80-8882-11ea-8f04-2f6ba2e30787.png)

**_Issue2_**
When github email id is selected by employee, email is not sent to user and not able to see any notification in github account when the employee is approved by CLA Manager
**62586327+nirupamavpink@users.noreply.github.com**
![image](https://user-images.githubusercontent.com/60865903/80341508-34b9ba80-8880-11ea-99b9-57e61f60eb7e.png)

**Comment by nirupamav** [comment]
**Observed this issue when contributor approval is declined**

**Comment by pranab-bajpai** [comment]
We show a message like this
"We cannot email you at this address <email address>. Please make your GitHub profile public and try again so that we can send you an email at a correct email address"

**Comment by dealako** [comment]
@wanyaland 
- Make sure that the "whitelist" keyword is replaced with "Approval List".
- Identify the correct email content to send - if missing, work with David or Pranab for the content. You can draft it, just let's review before the PR.

**Comment by dealako** [comment]
The old v1 console is deprecated and removed.
