### ISSUE TITLE
Corporate Console - Pending Manage Approved List count is not changed when Employee is accepted/rejected

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#988]
## Background
**_Prerequisite_**
1. Valid Project should exists and CCLA should be enabled for the project
2. Github repository should be added to the project
3. Valid Company should exist and should have signed CLA for the project
4. Employees should have requested for approval from Contributor Console

**_Steps to Follow_**
Login as CLA manager of the company that has signed the project with above github repository
Click on the company
Click MANAGE APPROVED LIST
ACCEPT few employee and DECLINE few employees
Observed the pending MANAGE APPROVED LIST count is not changed
https://api.dev.lfcla.com/v3/company/53cea6e9-c8ec-4c39-b54a-3a605ef72b0e/ccla-whitelist-requests/da182828-e52a-47e4-b5ab-c35b0978ae19

![image](https://user-images.githubusercontent.com/60865903/80344360-130f0200-8885-11ea-85e8-93814d6ef984.png)

![image](https://user-images.githubusercontent.com/60865903/80344439-35a11b00-8885-11ea-8842-abc75f449331.png)

**Comment by dealako** [comment]
The old v1 console is deprecated and removed.
