### ISSUE TITLE
Contributor Console - Employee has to again select Corporate and Select Company When Employee has been approved and whitelisted

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#989]
## Background

1. Launch github repository (company should have signed the project with this repository and project should be ccla enabled)
2. Login
3. Update any file and create PR
4. Click on CLA NOT SIGNED
5. Click on Corporate in Contributor console
6. Select Company and click SUBMIT
7. Enter all required details and click SEND
8. Launch Corporate Console
9. Login as CLA manager of the company that has signed the project with above github repository
10. Click on the company
11. Click MANAGE APPROVED LIST
12. Click ACCEPT
13. Whilte list the Employee by email/domain or any other option
14. Launch github pull request
15. Login as employee
16. Click on CLA NOT SIGNED
17. Employee has to again click on Corporate and again select company. Since employee has already completed that proceed while requesting for approval and also since the employee has been approved and whitelisted, Employee should be redirected to Acknowledgement UI or docusign UI based on the project configuration

**Comment by dealako** [comment]
@amolsontakke3576 let's review this flow with @pranab-bajpai in our daily standup

**Comment by vinod-kadam** [comment]
As discussed with Pranab, even though v2 issue, was logeed by Nirupama as enhancement; in yesterday's demo e2e flow was checked. So moving to icebox.

**Comment by dealako** [comment]
The old v1 console is deprecated and removed.
