### ISSUE TITLE
V2 API (top-projects API Endpoint): User with role other then lf-admin/admin is able to fetch the data

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla#997]
## Background
Trigger the api with authorization token of user having roles other then lf-admin/admin

User **nirupamavmentee2** has role **user** and when trying to fetch top-projects with the authorization token of this user data is fetched
![image](https://user-images.githubusercontent.com/60865903/80462230-07d6d780-8954-11ea-8c84-739a29577f4f.png)

Similarly user with **Project Manager**, **lf-operations** and **user** role is also able to fetch data
![image](https://user-images.githubusercontent.com/60865903/80462351-348aef00-8954-11ea-8b9a-bca773122096.png)

**Comment by dealako** [comment]
@rinkeshbhutwala please review permissions and validate with Sudhakar Shenoy against this spreadsheet: https://docs.google.com/spreadsheets/d/1KffX1dmJEEMhXQYXDpe7RTsuFTkuEMgjYLak07b4nI4/edit#gid=756183687

**Comment by sudhakar-proxima** [comment]
@rinkeshbhutwala for this release, check the following roles with the given scope
Project| Organization scope - contact, contributor, company-owner, company-admin,atlernate-company-owner,cla-manager,cla-manager-designee,cla-signatory
Project|* scope - project manager, community-program-manager, lf-program-manager, lf-executive, lf-admin,lf-legal,lf-finance,lf-operations

Following roles arent supported for this release and can be ignored for now
mentor, mentee, donor, HR, lf-training, lf-events.

**Comment by nirupamav** [comment]
As per below comment by @pranab-bajpai in tikcet, this endpoint is not used anymore and hence closing the ticket #873, without testing the endpoint
![image.png](https://images.zenhubusercontent.com/5eda192d0167eac230ac5cee/ccf71b54-bf9b-4354-9535-a8f3b8687955)
